CytoSim: Object Class Reference
Object Class Reference
#include <Object.h>
Public Member Functions
object_id getID ()
return the object_id associated with this object
virtual void writeSelf (std::ofstream &fout)
Write the Object into the provided output filestream, fout.
virtual void initializeFromStream (std::ifstream &fin)
initialize the Object based on the data from the inpute filestream
Static Public Member Functions
static Object * getObjectbyID (object_id id)
A static method, which should be invoked as,.
Protected Member Functions
Object ()
Default constructor without arguments is the usual way to initialize Object.
Object (object_id ID)
The main reason for using this constructor is reconstruction of Objects when read from a file (i.e.
Object * cloneObject ()
Duplicate the Object instance.
Detailed Description
This is the base class of Species, Reactions, Compartments, Filaments, etc.
Note:
A class derived from Object cannot be copied, but instead should be duplicated in a special way. Classes inherited from Object need to implement the Persistence interface, so to be able to write themselves into an output filestream and read themselves from an input filestream
Definition at line 36 of file Object.h.
Constructor & Destructor Documentation
Object::Object () [inline, protected]
Default constructor without arguments is the usual way to initialize Object.
Definition at line 68 of file Object.h.
Referenced by cloneObject().
Object::Object (object_id ID) [inline, protected]
The main reason for using this constructor is reconstruction of Objects when read from a file (i.e.
to implement persistence). It should not be necessary otherwise.
Definition at line 77 of file Object.h.
Member Function Documentation
Object* Object::cloneObject () [inline, protected]
Duplicate the Object instance.
Despite its name, the _id variable is not duplicated, because all Object IDs are required to be unique during any time of the program run.
Definition at line 86 of file Object.h.
References Object().
object_id Object::getID () [inline]
return the object_id associated with this object
Definition at line 39 of file Object.h.
static Object* Object::getObjectbyID (object_id id) [inline, static]
A static method, which should be invoked as,.
 object_id ID = 35;
 Object* o = Object::getObjectbyID(ID);
 ...
Definition at line 47 of file Object.h.
virtual void Object::initializeFromStream (std::ifstream & fin) [inline, virtual]
initialize the Object based on the data from the inpute filestream
Reimplemented in SBulk, and Species.
Definition at line 53 of file Object.h.
Referenced by Species::initializeFromStream().
virtual void Object::writeSelf (std::ofstream & fout) [inline, virtual]
Write the Object into the provided output filestream, fout.
Reimplemented in SBulk, and Species.
Definition at line 50 of file Object.h.
Referenced by Species::writeSelf().
The documentation for this class was generated from the following files:
/Users/papoian/Dropbox/Codes/CytoSim/CytoSim/Object.h
/Users/papoian/Dropbox/Codes/CytoSim/CytoSim/Object.cpp