CytoSim: chem::ChemSim Class Reference
chem::ChemSim Class Reference
ChemSim is used to manage running a network of chemical reactions.
#include <ChemSim.h>
Public Member Functions
ChemSim (ChemSimImpl *csi)
Constructor.
ChemSim (const ChemSim &rhs)
Copying is not allowed.
ChemSim & operator= (ChemSim &rhs)
Assignment is not allowed.
void initialize ()
After all initial reactions have been added via addReaction(...) method, invoke initialize() prior to invoking run()
void addReaction (Reaction *r)
Add Reaction *r to the chemical network which needs to be simulated.
void removeReaction (Reaction *r)
Remove Reaction *r from the simulated chemical network.
bool run (int steps)
Run the chemical dynamics for a specific number of steps.
void printReactions () const
Mainly used for debugging: print chemical reactions in the network at this moment.
Private Attributes
ChemSimImpl * _pimpl
Store a pointer to a specific implementation of stochastic chemical kinetics; no ownership.
Detailed Description
ChemSim is used to manage running a network of chemical reactions.
ChemSim implements a Strategy pattern, allowing custom algorithms for running stochastic chemical simulations. After the specific algorithm is chosen and ChemSim is instantiated, ChemSim can be used to manage simulations, through such methods as run(steps) etc. Here is an example:
        SpeciesBulk A1("A1",  25);
        SpeciesBulk A2("A2", 25);
        Reaction r1 = { {&A1,&A2}, 1, 1, 100.0 };
        ChemNRMImpl chem_nrm_impl;
        ChemSim chem(&chem_nrm_impl);
        chem.addReaction(&r1);
        chem.initialize();
        chem.printReactions();
        chem.run(100);
        chem.printReactions();
Definition at line 37 of file ChemSim.h.
Constructor & Destructor Documentation
chem::ChemSim::ChemSim (ChemSimImpl * csi)
Constructor.
Parameters:
ChemSimImpl *csi is a pointer the concrete implementation of stochastic simulation algorithm.
Note:
ChemSim simply stores the csi pointer but does not manage its memory. Make sure that csi is always a valid pointer while ChemSim is used.
Definition at line 16 of file ChemSim.cpp.
References _pimpl.
chem::ChemSim::ChemSim (const ChemSim & rhs)
Copying is not allowed.
Member Function Documentation
void chem::ChemSim::addReaction (Reaction * r)
Add Reaction *r to the chemical network which needs to be simulated.
Definition at line 21 of file ChemSim.cpp.
References _pimpl, and chem::ChemSimImpl::addReaction().
void chem::ChemSim::initialize ()
After all initial reactions have been added via addReaction(...) method, invoke initialize() prior to invoking run()
Definition at line 33 of file ChemSim.cpp.
References _pimpl, and chem::ChemSimImpl::initialize().
ChemSim& chem::ChemSim::operator= (ChemSim & rhs)
Assignment is not allowed.
void chem::ChemSim::printReactions () const
Mainly used for debugging: print chemical reactions in the network at this moment.
Definition at line 37 of file ChemSim.cpp.
References _pimpl, and chem::ChemSimImpl::printReactions().
void chem::ChemSim::removeReaction (Reaction * r)
Remove Reaction *r from the simulated chemical network.
Definition at line 25 of file ChemSim.cpp.
References _pimpl, and chem::ChemSimImpl::removeReaction().
bool chem::ChemSim::run (int steps)
Run the chemical dynamics for a specific number of steps.
Definition at line 29 of file ChemSim.cpp.
References _pimpl, and chem::ChemSimImpl::run().
Member Data Documentation
ChemSimImpl* chem::ChemSim::_pimpl [private]
Store a pointer to a specific implementation of stochastic chemical kinetics; no ownership.
Definition at line 66 of file ChemSim.h.
Referenced by addReaction(), ChemSim(), initialize(), printReactions(), removeReaction(), and run().
The documentation for this class was generated from the following files:
CytoSim/ChemSim.h
CytoSim/ChemSim.cpp