CytoSim: chem::SpeciesDiffusing Class Reference
chem::SpeciesDiffusing Class Reference
#include <Species.h>
Public Member Functions
SpeciesDiffusing ()
Default constructor.
SpeciesDiffusing (const std::string &name, species_copy_t n=0, species_copy_t ulim=max_ulim)
The main constructor.
SpeciesDiffusing (const SpeciesDiffusing &rhs)
Copy constructor.
SpeciesDiffusing (SpeciesDiffusing &&rhs) noexcept
Move constructor.
SpeciesDiffusing & operator= (const SpeciesDiffusing &rhs)
Regular Assignment.
SpeciesDiffusing & operator= (SpeciesDiffusing &&rhs)
Move assignment.
virtual std::string getFullName () const
Return the full name of this Species in a std::string format (e.g. "Arp2/3{Diffusing}".
~SpeciesDiffusing () noexcept
Default destructor.
RSpecies & getRSpecies ()
Return a reference to RSpecies.
const RSpecies & getRSpecies () const
Return a constant reference to RSpecies.
void setN (species_copy_t n)
Sets the copy number for this Species.
species_copy_t getN () const
Return the current copy number of this Species.
species_copy_t getUpperLimitForN () const
Return the upper limit for the copy number of this Species.
std::string getName () const
Return this Species' name.
bool isSignaling () const
Return true if this Species emits signals on copy number change.
void startSignaling ()
Set the signaling behavior of this Species Gillespie-like simulation algorithm)
void stopSignaling ()
Destroy the signal associated with this Species.
boost::signals2::connection connect (std::function< void(RSpecies *, int)> const &RSpecies_callback, int priority=5)
Connect the callback, rspecies_callback to a signal corresponding to RSpecies *s.
virtual bool is_equal (const Species &b) const
Default implementation returns true; subclasses should specialize it, if needed.
virtual size_t countSpecies () const
Composite * getParent ()
void setParent (Composite *other)
bool isRoot () const
Composite * getRoot ()
virtual bool hasChildren ()
virtual bool apply (Visitor &v)
virtual bool apply_if (ConditionalVisitor &v)
Friends
bool operator== (const Species &a, const Species &b)
Returns true if two Species objects are equal.
bool operator!= (const Species &a, const Species &b)
Return true if two Species are not equal.
Detailed Description
Definition at line 295 of file Species.h.
Constructor & Destructor Documentation
chem::SpeciesDiffusing::SpeciesDiffusing () [inline]
Default constructor.
Definition at line 298 of file Species.h.
chem::SpeciesDiffusing::SpeciesDiffusing (const std::string & name, species_copy_t n = 0, species_copy_t ulim = max_ulim) [inline]
The main constructor.
Parameters:
name - Example, "G-Actin" or "Arp2/3"
n - copy number
Definition at line 303 of file Species.h.
chem::SpeciesDiffusing::SpeciesDiffusing (const SpeciesDiffusing & rhs) [inline]
Copy constructor.
Definition at line 306 of file Species.h.
chem::SpeciesDiffusing::SpeciesDiffusing (SpeciesDiffusing && rhs) [inline]
Move constructor.
Definition at line 309 of file Species.h.
chem::SpeciesDiffusing::~SpeciesDiffusing () [inline]
Default destructor.
Definition at line 329 of file Species.h.
Member Function Documentation
bool chem::Component::apply (Visitor & v) [virtual, inherited]
Reimplemented in chem::Composite.
Definition at line 23 of file Component.cpp.
References chem::Visitor::visit().
bool chem::Component::apply_if (ConditionalVisitor & v) [virtual, inherited]
Reimplemented in chem::Composite.
Definition at line 27 of file Component.cpp.
References chem::ConditionalVisitor::visit_if().
boost::signals2::connection chem::Species::connect (std::function< void(RSpecies *, int)> const & RSpecies_callback, int priority = 5) [inherited]
Connect the callback, rspecies_callback to a signal corresponding to RSpecies *s.
Parameters:
std::function<void (RSpecies *, int)> const &RSpecies_callback - a function object to be called (a slot)
int priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Returns:
a connection object which can be used to later disconnect this particular slot or temporarily block it
Definition at line 25 of file Species.cpp.
References chem::Species::_rspecies, chem::Species::isSignaling(), and chem::Species::startSignaling().
virtual size_t chem::Species::countSpecies () const [inline, virtual, inherited]
Implements chem::Component.
Definition at line 255 of file Species.h.
virtual std::string chem::SpeciesDiffusing::getFullName () const [inline, virtual]
Return the full name of this Species in a std::string format (e.g. "Arp2/3{Diffusing}".
Reimplemented from chem::Species.
Definition at line 326 of file Species.h.
References chem::Species::getName().
species_copy_t chem::Species::getN () const [inline, inherited]
Return the current copy number of this Species.
Definition at line 194 of file Species.h.
References chem::Species::_rspecies.
Referenced by main(), operator<<(), chem::Species::operator=(), and chem::Species::Species().
std::string chem::Species::getName () const [inline, inherited]
Return this Species' name.
Definition at line 200 of file Species.h.
References chem::Species::_molecule, chem::SpeciesNamesDB::Instance(), and chem::SpeciesNamesDB::intToString().
Referenced by chem::Species::getFullName(), chem::SpeciesBulk::getFullName(), and getFullName().
Composite* chem::Component::getParent () [inline, inherited]
Definition at line 23 of file Component.h.
References chem::Component::_parent.
Referenced by chem::Component::getRoot().
Composite * chem::Component::getRoot () [inherited]
Definition at line 16 of file Component.cpp.
References chem::Component::getParent(), chem::Component::getRoot(), and chem::Component::isRoot().
Referenced by chem::Component::getRoot().
RSpecies& chem::Species::getRSpecies () [inline, inherited]
Return a reference to RSpecies.
Notice that value copying won't be allowed because RSpecies is not copyable.
Definition at line 183 of file Species.h.
References chem::Species::_rspecies.
const RSpecies& chem::Species::getRSpecies () const [inline, inherited]
Return a constant reference to RSpecies.
Definition at line 186 of file Species.h.
References chem::Species::_rspecies.
species_copy_t chem::Species::getUpperLimitForN () const [inline, inherited]
Return the upper limit for the copy number of this Species.
Definition at line 197 of file Species.h.
References chem::Species::_rspecies.
Referenced by chem::Species::operator=(), and chem::Species::Species().
virtual bool chem::Component::hasChildren () [inline, virtual, inherited]
Reimplemented in chem::Composite.
Definition at line 27 of file Component.h.
virtual bool chem::Species::is_equal (const Species & b) const [inline, virtual, inherited]
Default implementation returns true; subclasses should specialize it, if needed.
Definition at line 251 of file Species.h.
bool chem::Component::isRoot () const [inline, inherited]
Definition at line 25 of file Component.h.
References chem::Component::_parent.
Referenced by chem::Component::getRoot().
bool chem::Species::isSignaling () const [inline, inherited]
Return true if this Species emits signals on copy number change.
Definition at line 203 of file Species.h.
References chem::Species::_rspecies.
Referenced by chem::Species::connect().
SpeciesDiffusing& chem::SpeciesDiffusing::operator= (const SpeciesDiffusing & rhs) [inline]
Regular Assignment.
Definition at line 313 of file Species.h.
Referenced by operator=().
SpeciesDiffusing& chem::SpeciesDiffusing::operator= (SpeciesDiffusing && rhs) [inline]
Move assignment.
Definition at line 319 of file Species.h.
References operator=().
void chem::Species::setN (species_copy_t n) [inline, inherited]
Sets the copy number for this Species.
Parameters:
n should be a non-negative number, but no checking is done in run time
Note:
The operation does not emit any signals about the copy number change.
Definition at line 191 of file Species.h.
References chem::Species::_rspecies.
Referenced by main().
void chem::Component::setParent (Composite * other) [inline, inherited]
Definition at line 24 of file Component.h.
References chem::Component::_parent.
void chem::Species::startSignaling () [inline, inherited]
Set the signaling behavior of this Species Gillespie-like simulation algorithm)
Definition at line 207 of file Species.h.
References chem::Species::_rspecies.
Referenced by chem::Species::connect().
void chem::Species::stopSignaling () [inline, inherited]
Destroy the signal associated with this Species.
Note:
To start signaling again, makeSignaling(...) needs to be called
Definition at line 211 of file Species.h.
References chem::Species::_rspecies.
Friends And Related Function Documentation
bool operator!= (const Species & a, const Species & b) [friend, inherited]
Return true if two Species are not equal.
See also:
operator ==(const Species& a, const Species& b) above
Definition at line 235 of file Species.h.
bool operator== (const Species & a, const Species & b) [friend, inherited]
Returns true if two Species objects are equal.
This function would accept derived class of Species, such as SpeciesBulk Two Species are equal if their SType(s) are equal (i.e. are of the same class), their names are equal and their copy numbers are equal Note that specialized versions can be defined in derived classes by re-implementing:
See also:
virtual bool is_equal(const Species& b) const
Definition at line 226 of file Species.h.
The documentation for this class was generated from the following file:
CytoSim/Species.h