CytoSim: chem::ConditionalVisitor Class Reference
chem::ConditionalVisitor Class Reference
An abstract interface to traverse those nodes in the Composite pattern which fulfil a certain predicate.
#include <Visitor.h>
Public Member Functions
bool visit_if (Component *c)
When this conditional visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
virtual ~ConditionalVisitor ()
Virtual destructor.
Protected Member Functions
virtual bool visitImpl (Component *c)=0
When this visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
virtual bool predImpl (Component *c)=0
Return true if the Component *c satisfies the desired predicate.
Detailed Description
An abstract interface to traverse those nodes in the Composite pattern which fulfil a certain predicate.
The visitor pattern allows a functor to visit each node of the Composite pattern. Concrete classes derived from Visitor must implement the visit(Component *c) method. ConditionalVisitor, cv, allows a predicate to be applied at each node, *c, and cv->visit(c) is called only if that node satisfies the predicate. For example, this can be used to visit only filaments in the hieararchy.
Definition at line 66 of file Visitor.h.
Constructor & Destructor Documentation
virtual chem::ConditionalVisitor::~ConditionalVisitor () [inline, virtual]
Virtual destructor.
Definition at line 83 of file Visitor.h.
Member Function Documentation
virtual bool chem::ConditionalVisitor::predImpl (Component * c) [protected, pure virtual]
Return true if the Component *c satisfies the desired predicate.
Implemented in chem::ConditionalVisitorLambda, and chem::CompositeVisitor.
Referenced by visit_if().
bool chem::ConditionalVisitor::visit_if (Component * c) [inline]
When this conditional visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
If v->visit(c) returns a false value, then the further propagation of the tree is terminated.
Definition at line 71 of file Visitor.h.
References predImpl(), and visitImpl().
Referenced by chem::Component::apply_if(), and chem::Composite::apply_if().
virtual bool chem::ConditionalVisitor::visitImpl (Component * c) [protected, pure virtual]
When this visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Implemented in chem::ConditionalVisitorLambda, and chem::CompositeVisitor.
Referenced by visit_if().
The documentation for this class was generated from the following file:
CytoSim/Visitor.h