CytoSim: chem::Species Class Reference
chem::Species Class Reference
Species class represents chemical molecules, tracks their copy number and can be used in Reactions.
#include <Species.h>
Public Member Functions
Species ()
Default Constructor; Should not be used by the end users - only internally (although it is not marked as private)
Species (const std::string &name, species_copy_t n=0, species_copy_t ulim=max_ulim)
The constructor for this base class of Species should not be called directly - only by the concrete subclasses.
Species (const Species &rhs)
Copy constructor.
Species (Species &&rhs) noexcept
Move constructor - makes it possible to easily add Species to STL containers, such as vector<Species> One has to be careful with vector<Species> as opposed to vector<Species*>.
Species & operator= (const Species &rhs)
Assignment operator An assignment A = B copies the name of B to A.
Species & operator= (Species &&rhs)
Move assignment is needed for the same reasons as move constructor.
virtual Species * clone ()
RSpecies & getRSpecies ()
Return a reference to RSpecies.
const RSpecies & getRSpecies () const
Return a constant reference to RSpecies.
void setN (species_copy_t n)
Sets the copy number for this Species.
species_copy_t getN () const
Return the current copy number of this Species.
species_copy_t getUpperLimitForN () const
Return the upper limit for the copy number of this Species.
std::string getName () const
Return this Species' name.
int getMolecule () const
Return the molecule index associated with this Species' (as int)
bool isSignaling () const
Return true if this Species emits signals on copy number change.
void startSignaling ()
Set the signaling behavior of this Species Gillespie-like simulation algorithm)
void stopSignaling ()
Destroy the signal associated with this Species.
boost::signals2::connection connect (std::function< void(RSpecies *, int)> const &RSpecies_callback, int priority=5)
Connect the callback, rspecies_callback to a signal corresponding to RSpecies *s.
virtual ~Species () noexcept
Virtual destructor.
virtual std::string getFullName () const
Return the full name of this Species in a std::string format (e.g. "Arp2/3{Bulk}".
virtual bool is_equal (const Species &b) const
Default implementation returns true; subclasses should specialize it, if needed.
virtual size_t countSpecies () const
virtual bool apply (Visitor &v)
virtual bool apply_if (ConditionalVisitor &v)
Composite * getParent ()
void setParent (Composite *other)
bool isRoot () const
Composite * getRoot ()
virtual size_t numberOfChildren () const
virtual bool isComposite () const
virtual bool isSpeciesContainer () const
virtual bool isReactionsContainer () const
virtual size_t countReactions () const
Private Attributes
int _molecule
unique id identifying the molecule (e.g. the integer id corresponding to "Arp2/3")
std::unique_ptr< RSpecies > _rspecies
pointer to RSpecies; Species is responsible for creating and destroying RSpecies
Friends
bool operator== (const Species &a, const Species &b)
Returns true if two Species objects are equal.
bool operator!= (const Species &a, const Species &b)
Return true if two Species are not equal.
Detailed Description
Species class represents chemical molecules, tracks their copy number and can be used in Reactions.
This class represents chemical species, such as G-Actin. As a class, it provides Species' name, the current copy number of molecules, Species type (e.g. SType::Bulk), and a few other characteristics of a Species. This class is synergetic with the Reaction, since Species can be added to Reactions.
As a type, Species is composed of the following primary fields: type, name, copy number. A subclass may added additional primary fields. Two Species are mathematically equal, if their primary fields are equal. This means that applying the copy constructor will guarantee that primary fields will be equal:
  SpeciesBulk A{"Arp2/3",25};
  SpeciesBulk B(A);
  assert(A==B); // A must be equal to B
Note:
Each Species owns an unshared RSpecies object. However, the RSpecies field is not among the primary fields defining the Species identity (hence, the equality operator). In particular, upon copying, the source and target Species will have distinct RSpecies fields. However, in a fully constructed program, the source and target species (after applying the copy constructor) should eventually be involved in the same set of equivalent reactions. This means that their respective reactions will return true when the equlaity operator is applied.
The Species class allows callbacks (see makeSignaling and related methods).
Definition at line 114 of file Species.h.
Constructor & Destructor Documentation
chem::Species::Species () [inline]
Default Constructor; Should not be used by the end users - only internally (although it is not marked as private)
Definition at line 120 of file Species.h.
References _molecule, _rspecies, chem::SpeciesNamesDB::Instance(), and chem::SpeciesNamesDB::stringToInt().
Referenced by clone().
chem::Species::Species (const std::string & name, species_copy_t n = 0, species_copy_t ulim = max_ulim) [inline]
The constructor for this base class of Species should not be called directly - only by the concrete subclasses.
Parameters:
name - a string for the Species name associated with this Species. For example, "G-Actin" or "Arp2/3"
type_enum - SType enum, such as SType::Diffusing
n - copy number
ulim - upper limit for this species' copy number
Definition at line 131 of file Species.h.
References _molecule, _rspecies, chem::SpeciesNamesDB::Instance(), and chem::SpeciesNamesDB::stringToInt().
chem::Species::Species (const Species & rhs) [inline]
Copy constructor.
Note:
The associated RSpecies subpart is not copied, but a new one is created. This means that the copied destination Species won't be included in any Reaction interactions of the original source Species. The species copy numbered is copied to the target.
Definition at line 143 of file Species.h.
References _rspecies, getN(), and getUpperLimitForN().
chem::Species::Species (Species && rhs) [inline]
Move constructor - makes it possible to easily add Species to STL containers, such as vector<Species> One has to be careful with vector<Species> as opposed to vector<Species*>.
The latter is "safe" in terms of being internally moved around by vector.resize, etc., but vector<Species> would copy Species if a move constructor is not available. This will then destruct the original Species (with its associated RSpecies), hence, the Reaction network of the Species will be lost. Since this behavior is most likely not desired or unacceptable, the internal vector operations should only "move" the Species around, without copying. Moving transfers the RSpecies pointer from source to target, stealing resources from the source, leaving it for destruction.
Definition at line 156 of file Species.h.
virtual chem::Species::~Species () [inline, virtual]
Virtual destructor.
Note:
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 252 of file Species.h.
Member Function Documentation
bool chem::Component::apply (Visitor & v) [virtual, inherited]
Reimplemented in chem::Composite.
Definition at line 24 of file Component.cpp.
References chem::Visitor::visit().
bool chem::Component::apply_if (ConditionalVisitor & v) [virtual, inherited]
Reimplemented in chem::Composite.
Definition at line 28 of file Component.cpp.
References chem::ConditionalVisitor::visit_if().
virtual Species* chem::Species::clone () [inline, virtual]
Reimplemented in chem::SpeciesDiffusing, and chem::SpeciesBulk.
Definition at line 181 of file Species.h.
References Species().
boost::signals2::connection chem::Species::connect (std::function< void(RSpecies *, int)> const & RSpecies_callback, int priority = 5)
Connect the callback, rspecies_callback to a signal corresponding to RSpecies *s.
Parameters:
std::function<void (RSpecies *, int)> const &RSpecies_callback - a function object to be called (a slot)
int priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Returns:
a connection object which can be used to later disconnect this particular slot or temporarily block it
Definition at line 25 of file Species.cpp.
References _rspecies, isSignaling(), and startSignaling().
virtual size_t chem::Component::countReactions () const [inline, virtual, inherited]
Reimplemented in chem::Composite.
Definition at line 37 of file Component.h.
virtual size_t chem::Species::countSpecies () const [inline, virtual]
Reimplemented from chem::Component.
Definition at line 262 of file Species.h.
virtual std::string chem::Species::getFullName () const [inline, virtual]
Return the full name of this Species in a std::string format (e.g. "Arp2/3{Bulk}".
Reimplemented from chem::Component.
Reimplemented in chem::SpeciesDiffusing, and chem::SpeciesBulk.
Definition at line 255 of file Species.h.
References getName().
Referenced by chem::RSpecies::getFullName(), and operator<<().
int chem::Species::getMolecule () const [inline]
Return the molecule index associated with this Species' (as int)
Definition at line 207 of file Species.h.
References _molecule.
species_copy_t chem::Species::getN () const [inline]
Return the current copy number of this Species.
Definition at line 198 of file Species.h.
References _rspecies.
Referenced by operator<<(), operator=(), and Species().
std::string chem::Species::getName () const [inline]
Return this Species' name.
Definition at line 204 of file Species.h.
References _molecule, chem::SpeciesNamesDB::Instance(), and chem::SpeciesNamesDB::intToString().
Referenced by getFullName(), chem::SpeciesBulk::getFullName(), and chem::SpeciesDiffusing::getFullName().
Composite* chem::Component::getParent () [inline, inherited]
Definition at line 25 of file Component.h.
References chem::Component::_parent.
Referenced by chem::Component::getRoot().
Composite * chem::Component::getRoot () [inherited]
Definition at line 17 of file Component.cpp.
References chem::Component::getParent(), chem::Component::getRoot(), and chem::Component::isRoot().
Referenced by chem::Component::getRoot().
RSpecies& chem::Species::getRSpecies () [inline]
Return a reference to RSpecies.
Notice that value copying won't be allowed because RSpecies is not copyable.
Definition at line 187 of file Species.h.
References _rspecies.
Referenced by main().
const RSpecies& chem::Species::getRSpecies () const [inline]
Return a constant reference to RSpecies.
Definition at line 190 of file Species.h.
References _rspecies.
species_copy_t chem::Species::getUpperLimitForN () const [inline]
Return the upper limit for the copy number of this Species.
Definition at line 201 of file Species.h.
References _rspecies.
Referenced by operator=(), and Species().
virtual bool chem::Species::is_equal (const Species & b) const [inline, virtual]
Default implementation returns true; subclasses should specialize it, if needed.
Definition at line 258 of file Species.h.
virtual bool chem::Component::isComposite () const [inline, virtual, inherited]
Definition at line 31 of file Component.h.
virtual bool chem::Component::isReactionsContainer () const [inline, virtual, inherited]
Reimplemented in chem::Compartment.
Definition at line 33 of file Component.h.
Referenced by chem::Composite::countReactions().
bool chem::Component::isRoot () const [inline, inherited]
Definition at line 27 of file Component.h.
References chem::Component::_parent.
Referenced by chem::Component::getRoot().
bool chem::Species::isSignaling () const [inline]
Return true if this Species emits signals on copy number change.
Definition at line 210 of file Species.h.
References _rspecies.
Referenced by connect().
virtual bool chem::Component::isSpeciesContainer () const [inline, virtual, inherited]
Reimplemented in chem::Compartment.
Definition at line 32 of file Component.h.
Referenced by chem::Composite::countSpecies().
virtual size_t chem::Component::numberOfChildren () const [inline, virtual, inherited]
Reimplemented in chem::Composite.
Definition at line 30 of file Component.h.
Species& chem::Species::operator= (const Species & rhs) [inline]
Assignment operator An assignment A = B copies the name of B to A.
It destroys the Reaction interactions of A, and resents them to a blank value (i.e. A won't be involced in any Reactions). B's Reaction interactions are not copied. The copy number of B is copied to A.
Definition at line 165 of file Species.h.
References _molecule, _rspecies, getN(), and getUpperLimitForN().
Species& chem::Species::operator= (Species && rhs) [inline]
Move assignment is needed for the same reasons as move constructor.
See also:
Species (Species &&rhs)
Definition at line 174 of file Species.h.
References _molecule, and _rspecies.
void chem::Species::setN (species_copy_t n) [inline]
Sets the copy number for this Species.
Parameters:
n should be a non-negative number, but no checking is done in run time
Note:
The operation does not emit any signals about the copy number change.
Definition at line 195 of file Species.h.
References _rspecies.
void chem::Component::setParent (Composite * other) [inline, inherited]
Definition at line 26 of file Component.h.
References chem::Component::_parent.
Referenced by chem::Compartment::addReaction(), chem::Compartment::addReactionUnique(), chem::Compartment::addSpecies(), and chem::Compartment::addSpeciesUnique().
void chem::Species::startSignaling () [inline]
Set the signaling behavior of this Species Gillespie-like simulation algorithm)
Definition at line 214 of file Species.h.
References _rspecies.
Referenced by connect().
void chem::Species::stopSignaling () [inline]
Destroy the signal associated with this Species.
Note:
To start signaling again, makeSignaling(...) needs to be called
Definition at line 218 of file Species.h.
References _rspecies.
Friends And Related Function Documentation
bool operator!= (const Species & a, const Species & b) [friend]
Return true if two Species are not equal.
See also:
operator ==(const Species& a, const Species& b) above
Definition at line 242 of file Species.h.
bool operator== (const Species & a, const Species & b) [friend]
Returns true if two Species objects are equal.
This function would accept derived class of Species, such as SpeciesBulk Two Species are equal if their SType(s) are equal (i.e. are of the same class), their names are equal and their copy numbers are equal Note that specialized versions can be defined in derived classes by re-implementing:
See also:
virtual bool is_equal(const Species& b) const
Definition at line 233 of file Species.h.
Member Data Documentation
int chem::Species::_molecule [private]
unique id identifying the molecule (e.g. the integer id corresponding to "Arp2/3")
Definition at line 116 of file Species.h.
Referenced by getMolecule(), getName(), operator=(), and Species().
std::unique_ptr<RSpecies> chem::Species::_rspecies [private]
pointer to RSpecies; Species is responsible for creating and destroying RSpecies
Definition at line 117 of file Species.h.
Referenced by connect(), getN(), getRSpecies(), getUpperLimitForN(), isSignaling(), operator=(), setN(), Species(), startSignaling(), and stopSignaling().
The documentation for this class was generated from the following files:
CytoSim/Species.h
CytoSim/Species.cpp