CytoSim: chem::ChemSignal Class Reference
chem::ChemSignal Class Reference
ChemSignal manages callbacks for RSpecies and Reactions objects.
#include <Signaling.h>
Public Member Functions
void emitReactionSignal (ReactionBase *r) const
Broadcasts signal corresponding to ReactionBase *r.
void emitRSpeciesSignal (RSpecies *s, int delta) const
Broadcasts signal corresponding to RSpecies *s.
void addSignalingRSpecies (RSpecies *s)
Inserts a signal corresponding to RSpecies *s into the map.
void addSignalingReaction (ReactionBase *r)
Inserts a signal corresponding to ReactionBase *r into the map.
boost::signals2::connection connect (ReactionBase *r, std::function< void(ReactionBase *)> const &react_callback, int priority=5)
Connect the callback, react_callback to a signal corresponding to ReactionBase *r.
boost::signals2::connection connect (Species *s, std::function< void(RSpecies *, int)> const &RSpecies_callback, int priority=5)
Connect the callback, RSpecies_callback to a signal corresponding to RSpecies *s.
void disconnect (ReactionBase *r)
Destroy signal corresponding to Reaction r.
void disconnect (RSpecies *s)
Destroy signal corresponding to Reaction r.
Private Member Functions
std::unordered_map
< ReactionBase
*, std::unique_ptr
< ReactionEventSignal >
>::const_iterator findSignal (ReactionBase *r) const
Search the map for a signal corresponding to parameter, ReactionBase *r. Throw std::out_of_range exception if not found.
std::unordered_map< RSpecies
*, std::unique_ptr
< RSpeciesCopyNChangedSignal >
>::const_iterator findSignal (RSpecies *s) const
Search the map for a signal corresponding to parameter, RSpecies *s. Throw std::out_of_range exception if not found.
void assertSignalDoesNotExist (ReactionBase *r)
Assert that a signal corresponding to ReactionBase *r does not exist or throw std::runtime_error.
void assertSignalDoesNotExist (RSpecies *s)
Assert that a signal corresponding to RSpecies *s does not exist or throw std::runtime_error.
Private Attributes
std::unordered_map< RSpecies
*, std::unique_ptr
< RSpeciesCopyNChangedSignal > > _map_RSpecies_signal
Keep track of signals corresponding to various RSpecies.
std::unordered_map
< ReactionBase
*, std::unique_ptr
< ReactionEventSignal > > _map_reaction_signal
Keep track of signals corresponding to various Reactions.
Detailed Description
ChemSignal manages callbacks for RSpecies and Reactions objects.
One ChemSignal should be instantiated per chemical network. RSpecies and Reactions that need to be monitored can be made to signal, based on the boost:signal2 library. Multiple receiving slots can be connected to signals.
Slots can be temporarily blocked or completely disconnected. Signals can be destroyed. Here is an example of usage:
 ...
 Species* A1 = ...
 ...
 ChemSignal sm;
 A1->makeSignaling(sm);
 PrintRSpecies ps;
 ...
 std::function<void (RSpecies *, int)> psf(ps);
 boost::signals2::shared_connection_block conn_a1(sm.connect(A1, [](RSpecies *s, int i){s->printSelf();}), true);
 // or   sm.connect(A1, print_RSpecies);
 // or  sm.connect(A1, PrintRSpecies());
 // or   boost::signals2::shared_connection_block conn_a1(sm.connect(A1,psf), false);
...
// run simulation for some time
 ...
 conn_a1.block(); // this temporarily stops slots from being called.
...
 conn_a1.disconnect(); // this permanently disconnects the slot
...
 A1->stopSignaling(sm); // this destroys the Signal itself (with associated multiple slots)
...
Definition at line 66 of file Signaling.h.
Member Function Documentation
void chem::ChemSignal::addSignalingReaction (ReactionBase * r) [inline]
Inserts a signal corresponding to ReactionBase *r into the map.
Should only be called by the Reaction class.
Note:
other classes should instead call void Reaction::makeSignaling(ChemSignal &sm);
Definition at line 128 of file Signaling.h.
References _map_reaction_signal, and assertSignalDoesNotExist().
void chem::ChemSignal::addSignalingRSpecies (RSpecies * s) [inline]
Inserts a signal corresponding to RSpecies *s into the map.
Should only be called by the RSpecies class.
Note:
other classes should instead call void RSpecies::makeSignaling(ChemSignal &sm);
Definition at line 120 of file Signaling.h.
References _map_RSpecies_signal, and assertSignalDoesNotExist().
void chem::ChemSignal::assertSignalDoesNotExist (ReactionBase * r) [inline, private]
Assert that a signal corresponding to ReactionBase *r does not exist or throw std::runtime_error.
Definition at line 90 of file Signaling.h.
References _map_reaction_signal.
Referenced by addSignalingReaction(), and addSignalingRSpecies().
void chem::ChemSignal::assertSignalDoesNotExist (RSpecies * s) [inline, private]
Assert that a signal corresponding to RSpecies *s does not exist or throw std::runtime_error.
Definition at line 97 of file Signaling.h.
References _map_RSpecies_signal.
boost::signals2::connection chem::ChemSignal::connect (ReactionBase * r, std::function< void(ReactionBase *)> const & react_callback, int priority = 5) [inline]
Connect the callback, react_callback to a signal corresponding to ReactionBase *r.
Parameters:
ReactionBase *r - the signal will correspond to this Reaction
std::function<void (ReactionBase *)> const &react_callback - a function object to be called (a slot)
int priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Definition at line 138 of file Signaling.h.
References findSignal().
boost::signals2::connection chem::ChemSignal::connect (Species * s, std::function< void(RSpecies *, int)> const & RSpecies_callback, int priority = 5) [inline]
Connect the callback, RSpecies_callback to a signal corresponding to RSpecies *s.
Parameters:
RSpecies *s - the signal will correspond to this RSpecies
std::function<void (RSpecies *, int)> const &RSpecies_callback - a function object to be called (a slot). int here corresponds to delta, the change in copy number of the RSpecies (for which the signal was emitted)
int priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Definition at line 149 of file Signaling.h.
References findSignal(), and chem::Species::getRSpecies().
void chem::ChemSignal::disconnect (ReactionBase * r) [inline]
Destroy signal corresponding to Reaction r.
Should only be used by the Reaction class.
Note:
Other classes should instead call void Reaction::stopSignaling (ChemSignal &sm);
Definition at line 157 of file Signaling.h.
References _map_reaction_signal, and findSignal().
void chem::ChemSignal::disconnect (RSpecies * s) [inline]
Destroy signal corresponding to Reaction r.
Should only be used by the RSpecies class.
Note:
Other classes should instead call void RSpecies::stopSignaling (ChemSignal &sm);
Definition at line 164 of file Signaling.h.
References _map_RSpecies_signal, and findSignal().
void chem::ChemSignal::emitReactionSignal (ReactionBase * r) const [inline]
Broadcasts signal corresponding to ReactionBase *r.
If the Reaction is not found, std::out_of_range exception will be thrown. This method is usally only called by the Gillespie-like algorithm, and not the outside code.
Definition at line 106 of file Signaling.h.
References findSignal().
void chem::ChemSignal::emitRSpeciesSignal (RSpecies * s, int delta) const [inline]
Broadcasts signal corresponding to RSpecies *s.
If the Specis is not found, std::out_of_range exception will be thrown. This method is usally only called by the Gillespie-like algorithm, and not the outside code.
Definition at line 113 of file Signaling.h.
References findSignal().
std::unordered_map<ReactionBase *, std::unique_ptr<ReactionEventSignal> >::const_iterator chem::ChemSignal::findSignal (ReactionBase * r) const [inline, private]
Search the map for a signal corresponding to parameter, ReactionBase *r. Throw std::out_of_range exception if not found.
Definition at line 73 of file Signaling.h.
References _map_reaction_signal.
Referenced by connect(), disconnect(), emitReactionSignal(), and emitRSpeciesSignal().
std::unordered_map<RSpecies *, std::unique_ptr<RSpeciesCopyNChangedSignal> >::const_iterator chem::ChemSignal::findSignal (RSpecies * s) const [inline, private]
Search the map for a signal corresponding to parameter, RSpecies *s. Throw std::out_of_range exception if not found.
Definition at line 82 of file Signaling.h.
References _map_RSpecies_signal.
Member Data Documentation
std::unordered_map<ReactionBase *, std::unique_ptr<ReactionEventSignal> > chem::ChemSignal::_map_reaction_signal [private]
Keep track of signals corresponding to various Reactions.
Definition at line 69 of file Signaling.h.
Referenced by addSignalingReaction(), assertSignalDoesNotExist(), disconnect(), and findSignal().
std::unordered_map<RSpecies *, std::unique_ptr<RSpeciesCopyNChangedSignal> > chem::ChemSignal::_map_RSpecies_signal [private]
Keep track of signals corresponding to various RSpecies.
Definition at line 68 of file Signaling.h.
Referenced by addSignalingRSpecies(), assertSignalDoesNotExist(), disconnect(), and findSignal().
The documentation for this class was generated from the following file:
CytoSim/Signaling.h