CytoSim: chem::RNodeNRM Class Reference
chem::RNodeNRM Class Reference
RNodeNRM stands for Reaction Node Next Reaction Method.
#include <ChemNRMImpl.h>
Public Member Functions
RNodeNRM (ReactionBase *r, ChemNRMImpl &chem_nrm)
Ctor:
RNodeNRM (const RNodeNRM &rhs)
Copying is not allowed.
RNodeNRM & operator= (RNodeNRM &rhs)
Assignment is not allowed.
virtual ~RNodeNRM ()
Dtor: 1) Erases the corresponding PQNode element in the heap via the handle; 2) The RNode pointer of the tracked Reaction object is set to nullptr.
void generateNewRandTau ()
This methods recomputes the reaction propensity based on current coefficients and the rate, and then obtains a corresponding new tau drawn from an exponential distribution.
ReactionBase * getReaction () const
Returns a pointer to the Reaction which corresponds to this RNodeNRM.
void updateHeap ()
The heap is updated only with respect to the specific PQNode element which presumably was modified (e.g.
double getTau () const
Returns the tau from the the associated PQNode element.
void setTau (double tau)
Sets the tau of the the associated PQNode element. Does not update the heap.
handle_t & getHandle ()
Returns a handle to the associated PQNode element, which can be used to access tau, for example.
double getPropensity () const
Return the currently stored propensity, "a", for this Reaction.
double reComputePropensity ()
(Re)Compute and return the propensity associated with this Reaction.
int getProductOfReactants ()
Compute and return the product of reactant copy numbers.
void makeStep ()
This method calls the corresponding Reaction::makeStep() method of the underyling Reaction object.
virtual void activateReaction ()
When this method is called, a new tau is computed and the corresponding PQNode element is updated in the heap.
virtual void passivateReaction ()
When this method is called, reaction's tau is set to infinity, the propensity is set to 0, and the corresponding PQNode element is updated in the heap.
bool isPassivated () const
Return true if the Reaction is currently passivated.
void printSelf () const
Print information about this RNodeNRM such as tau, a and the Reaction which this RNodeNRM tracks.
void printDependents () const
Print the RNode objects which are dependents of this RNode (via the tracked Reaction object dependencies)
Private Attributes
ChemNRMImpl & _chem_nrm
A reference to the ChemNRMImpl which containts the heap, random number generators, etc.
handle_t _handle
The handle to the associated PQNode element in the heap.
ReactionBase * _react
The pointer to the associated Reaction object. The corresponding memory is not managed by RNodeNRM.
double _a
The propensity associated with the Reaction. It may be outdated and may need to be recomputed if needed.
Detailed Description
RNodeNRM stands for Reaction Node Next Reaction Method.
RNodeNRM manages a single chemical reaction within the NRM algorithm. It has a pointer to the PQ element containing the Reaction via a handle_t object (and hence can modify both the corresponding PQNode, such as PQNode's tau or the underlying Reaction instance). RNodeNRM can recompute tau if needed and has auxiliary methods for computing reaction's propensity. When the propensity drops to zero, the RNodeNRM can execute the passivateReaction() method. Alternatively, passivated RNodeNRM can be activated via activateReaction(). The main part of the NRM algoritm is implemented in the makeStep() method.
Definition at line 103 of file ChemNRMImpl.h.
Constructor & Destructor Documentation
chem::RNodeNRM::RNodeNRM (ReactionBase * r, ChemNRMImpl & chem_nrm)
Ctor:
Parameters:
*r is the Reaction object corresponding to this RNodeNRM
&chem_nrm is a refernce to ChemNRMImpl object, which does the overall management of the NRM scheme (e.g. it gives acces to the heap itself, random distribution generators, etc.)
Definition at line 79 of file ChemNRMImpl.cpp.
References _a, _chem_nrm, _handle, _react, chem::ReactionBase::computePropensity(), chem::ChemNRMImpl::getHeap(), and chem::ReactionBase::setRnode().
chem::RNodeNRM::RNodeNRM (const RNodeNRM & rhs)
Copying is not allowed.
chem::RNodeNRM::~RNodeNRM () [virtual]
Dtor: 1) Erases the corresponding PQNode element in the heap via the handle; 2) The RNode pointer of the tracked Reaction object is set to nullptr.
Definition at line 87 of file ChemNRMImpl.cpp.
References _chem_nrm, _handle, _react, chem::ChemNRMImpl::getHeap(), and chem::ReactionBase::setRnode().
Member Function Documentation
void chem::RNodeNRM::activateReaction () [virtual]
When this method is called, a new tau is computed and the corresponding PQNode element is updated in the heap.
Note:
This method does not activate the Reaction itself, but instead only deals with the activation process related to the corresponding PQNode element.
Implements chem::RNode.
Definition at line 132 of file ChemNRMImpl.cpp.
References generateNewRandTau(), and updateHeap().
void chem::RNodeNRM::generateNewRandTau ()
This methods recomputes the reaction propensity based on current coefficients and the rate, and then obtains a corresponding new tau drawn from an exponential distribution.
Note:
This methods modifies tau which is stored in the associated PQNode object. However, it does not update the heap - this needs to be done seprately.
Definition at line 116 of file ChemNRMImpl.cpp.
References _a, _chem_nrm, chem::ChemNRMImpl::generateTau(), chem::ChemNRMImpl::getTime(), reComputePropensity(), setTau(), and tau().
Referenced by activateReaction(), and chem::ChemNRMImpl::makeStep().
handle_t& chem::RNodeNRM::getHandle () [inline]
Returns a handle to the associated PQNode element, which can be used to access tau, for example.
Definition at line 141 of file ChemNRMImpl.h.
References _handle.
int chem::RNodeNRM::getProductOfReactants () [inline]
Compute and return the product of reactant copy numbers.
This method can be used to quickly check whether this reaction needs to be passivated, if the returned result is zero.
Definition at line 152 of file ChemNRMImpl.h.
References _react, and chem::ReactionBase::getProductOfReactants().
double chem::RNodeNRM::getPropensity () const [inline]
Return the currently stored propensity, "a", for this Reaction.
Note:
The propensity is not recomputed in this method, so it potentially can be out of sync.
Definition at line 145 of file ChemNRMImpl.h.
References _a.
Referenced by chem::ChemNRMImpl::makeStep().
ReactionBase* chem::RNodeNRM::getReaction () const [inline]
Returns a pointer to the Reaction which corresponds to this RNodeNRM.
Definition at line 128 of file ChemNRMImpl.h.
References _react.
Referenced by chem::ChemNRMImpl::makeStep().
double chem::RNodeNRM::getTau () const [inline]
Returns the tau from the the associated PQNode element.
Definition at line 135 of file ChemNRMImpl.h.
Referenced by chem::ChemNRMImpl::makeStep(), and printSelf().
bool chem::RNodeNRM::isPassivated () const [inline, virtual]
Return true if the Reaction is currently passivated.
Implements chem::RNode.
Definition at line 169 of file ChemNRMImpl.h.
References _react, and chem::ReactionBase::isPassivated().
Referenced by chem::ChemNRMImpl::makeStep().
void chem::RNodeNRM::makeStep () [inline]
This method calls the corresponding Reaction::makeStep() method of the underyling Reaction object.
Definition at line 155 of file ChemNRMImpl.h.
References _react, and chem::ReactionBase::makeStep().
Referenced by chem::ChemNRMImpl::makeStep().
RNodeNRM& chem::RNodeNRM::operator= (RNodeNRM & rhs)
Assignment is not allowed.
void chem::RNodeNRM::passivateReaction () [virtual]
When this method is called, reaction's tau is set to infinity, the propensity is set to 0, and the corresponding PQNode element is updated in the heap.
Note:
This method does not passivate the Reaction itself, but instead only deals with the activation process related to the corresponding PQNode element.
Implements chem::RNode.
Definition at line 141 of file ChemNRMImpl.cpp.
References _a, setTau(), tau(), and updateHeap().
void chem::RNodeNRM::printDependents () const
Print the RNode objects which are dependents of this RNode (via the tracked Reaction object dependencies)
Definition at line 101 of file ChemNRMImpl.cpp.
References _react, chem::ReactionBase::dependents(), and printSelf().
void chem::RNodeNRM::printSelf () const
Print information about this RNodeNRM such as tau, a and the Reaction which this RNodeNRM tracks.
Definition at line 96 of file ChemNRMImpl.cpp.
References _a, and getTau().
Referenced by printDependents().
double chem::RNodeNRM::reComputePropensity () [inline]
(Re)Compute and return the propensity associated with this Reaction.
Definition at line 148 of file ChemNRMImpl.h.
References _a, _react, and chem::ReactionBase::computePropensity().
Referenced by generateNewRandTau(), and chem::ChemNRMImpl::makeStep().
void chem::RNodeNRM::setTau (double tau) [inline]
Sets the tau of the the associated PQNode element. Does not update the heap.
Definition at line 138 of file ChemNRMImpl.h.
References tau().
Referenced by generateNewRandTau(), chem::ChemNRMImpl::makeStep(), and passivateReaction().
void chem::RNodeNRM::updateHeap ()
The heap is updated only with respect to the specific PQNode element which presumably was modified (e.g.
via generateNewRandTau()).
Definition at line 111 of file ChemNRMImpl.cpp.
References _chem_nrm, _handle, and chem::ChemNRMImpl::getHeap().
Referenced by activateReaction(), chem::ChemNRMImpl::makeStep(), and passivateReaction().
Member Data Documentation
double chem::RNodeNRM::_a [private]
The propensity associated with the Reaction. It may be outdated and may need to be recomputed if needed.
Definition at line 189 of file ChemNRMImpl.h.
Referenced by generateNewRandTau(), getPropensity(), passivateReaction(), printSelf(), reComputePropensity(), and RNodeNRM().
ChemNRMImpl& chem::RNodeNRM::_chem_nrm [private]
A reference to the ChemNRMImpl which containts the heap, random number generators, etc.
Definition at line 186 of file ChemNRMImpl.h.
Referenced by generateNewRandTau(), RNodeNRM(), updateHeap(), and ~RNodeNRM().
handle_t chem::RNodeNRM::_handle [private]
The handle to the associated PQNode element in the heap.
Definition at line 187 of file ChemNRMImpl.h.
Referenced by getHandle(), RNodeNRM(), updateHeap(), and ~RNodeNRM().
ReactionBase* chem::RNodeNRM::_react [private]
The pointer to the associated Reaction object. The corresponding memory is not managed by RNodeNRM.
Definition at line 188 of file ChemNRMImpl.h.
Referenced by getProductOfReactants(), getReaction(), isPassivated(), makeStep(), printDependents(), reComputePropensity(), RNodeNRM(), and ~RNodeNRM().
The documentation for this class was generated from the following files:
CytoSim/ChemNRMImpl.h
CytoSim/ChemNRMImpl.cpp