CytoSim: chem::Component Class Reference
chem::Component Class Reference
Component class is the base class for the Composite pattern hieararchy.
#include <Component.h>
Public Member Functions
Component ()
Default Constructor; Parent is assigned to nullptr.
virtual ~Component () noexcept
Virtual Destructor.
virtual bool apply (Visitor &v)
When this function is applied to a Visitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
virtual bool apply_if (Visitor &v)
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
virtual bool apply (SpeciesVisitor &v)
When this function is applied to a SpeciesVisitor sv, the corresponding v.visit(s) is called for each Species pointer *s owned by the node.
virtual bool apply_if (SpeciesVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl_if (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply (ReactionVisitor &v)
When this function is applied to a ReactionVisitor sv, the corresponding v.visit(s) is called for each ReactionBase pointer *s owned by the node.
virtual bool apply_if (ReactionVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionVisitor v to every ReactionBase* object directly owned by this node.
virtual bool apply_impl_if (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node. The returned value could be a nullptr if a parent does not exist.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual size_t numberOfChildren () const
Returns the number of children of this node.
virtual bool isComposite () const
Returns true if this node is a Composite node.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e. ReactionBase pointers)
virtual size_t numberOfSpecies () const
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t numberOfReactions () const
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual std::string getFullName () const
Return a std::string indicating the full name of this node (presumably used mainly for debugging)
virtual size_t countSpecies () const
Return the number of Species contained under this node's hieararchy.
virtual size_t countReactions () const
Return the number of ReactionBase objects contained under this node's hieararchy.
virtual void printSelf ()
Prints information about this node. Useful for debugging.
Private Attributes
Composite * _parent
The parent of this object. May be a nullptr if this object has no parent.
Detailed Description
Component class is the base class for the Composite pattern hieararchy.
The Composite patter allows building of complex hieararchical objects, with convenient methods for applying a function to all nodes (i.e. the Visitor pattern). Each node in the hieararchy may have a parent and may contain several children nodes. A class that is derived directly from Component and not from Composite, cannot contain children, i.e. it is a leaf node.
Note:
Component objects may contain Species and ReactionBase collections, however, this is treated seperately from the Composite pattern (i.e. separate methods exist for the corresponding access to elements, changes, etc.)
Definition at line 30 of file Component.h.
Constructor & Destructor Documentation
chem::Component::Component () [inline]
Default Constructor; Parent is assigned to nullptr.
Definition at line 36 of file Component.h.
virtual chem::Component::~Component () [inline, virtual]
Virtual Destructor.
Definition at line 39 of file Component.h.
Member Function Documentation
bool chem::Component::apply (Visitor & v) [virtual]
When this function is applied to a Visitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
Reimplemented in chem::Composite.
Definition at line 24 of file Component.cpp.
References chem::Visitor::visit().
virtual bool chem::Component::apply (SpeciesVisitor & v) [inline, virtual]
When this function is applied to a SpeciesVisitor sv, the corresponding v.visit(s) is called for each Species pointer *s owned by the node.
v is further applied to all children of this node recursively.
Reimplemented in chem::Composite.
Definition at line 52 of file Component.h.
References apply_impl().
virtual bool chem::Component::apply (ReactionVisitor & v) [inline, virtual]
When this function is applied to a ReactionVisitor sv, the corresponding v.visit(s) is called for each ReactionBase pointer *s owned by the node.
v is further applied to all children of this node recursively.
Reimplemented in chem::Composite.
Definition at line 68 of file Component.h.
References apply_impl().
bool chem::Component::apply_if (Visitor & v) [virtual]
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
However, the ConditionalVisitor allows the visit() function to be applied only selectively to nodes that conform to specific criteria.
Reimplemented in chem::Composite.
Definition at line 28 of file Component.cpp.
References chem::Visitor::visit_if().
virtual bool chem::Component::apply_if (SpeciesVisitor & v) [inline, virtual]
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented in chem::Composite.
Definition at line 56 of file Component.h.
References apply_impl().
virtual bool chem::Component::apply_if (ReactionVisitor & v) [inline, virtual]
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented in chem::Composite.
Definition at line 72 of file Component.h.
References apply_impl().
virtual bool chem::Component::apply_impl (SpeciesVisitor & v) [inline, virtual]
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in chem::Compartment.
Definition at line 60 of file Component.h.
Referenced by apply(), chem::Composite::apply(), and apply_if().
virtual bool chem::Component::apply_impl (ReactionVisitor & v) [inline, virtual]
Applies ReactionVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in chem::Compartment.
Definition at line 76 of file Component.h.
virtual bool chem::Component::apply_impl_if (SpeciesVisitor & v) [inline, virtual]
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in chem::Compartment.
Definition at line 64 of file Component.h.
Referenced by chem::Composite::apply_if().
virtual bool chem::Component::apply_impl_if (ReactionVisitor & v) [inline, virtual]
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in chem::Compartment.
Definition at line 80 of file Component.h.
virtual size_t chem::Component::countReactions () const [inline, virtual]
Return the number of ReactionBase objects contained under this node's hieararchy.
Note:
This is a recursive call, and all nodes under this node are visited.
Reimplemented in chem::Composite.
Definition at line 125 of file Component.h.
virtual size_t chem::Component::countSpecies () const [inline, virtual]
Return the number of Species contained under this node's hieararchy.
Note:
This is a recursive call, and all nodes under this node are visited.
Reimplemented in chem::Composite.
Definition at line 121 of file Component.h.
Referenced by chem::ConcreteVisitor::visitImpl(), and chem::CompositeVisitor::visitImpl().
virtual std::string chem::Component::getFullName () const [inline, virtual]
Return a std::string indicating the full name of this node (presumably used mainly for debugging)
Reimplemented in chem::CompartmentCubic< NDIM >, chem::Compartment, chem::Composite, and chem::CompartmentsSimpleGrid< NDIM >.
Definition at line 117 of file Component.h.
Referenced by chem::ConcreteVisitor::visitImpl(), and chem::CompositeVisitor::visitImpl().
Composite* chem::Component::getParent () [inline]
Returns the pointer to the parent node. The returned value could be a nullptr if a parent does not exist.
Definition at line 83 of file Component.h.
References _parent.
Referenced by getRoot().
Composite * chem::Component::getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 17 of file Component.cpp.
References getParent(), getRoot(), and isRoot().
Referenced by getRoot(), chem::ReactionBase::getRoot(), and chem::Species::getRoot().
virtual bool chem::Component::isComposite () const [inline, virtual]
Returns true if this node is a Composite node.
Reimplemented in chem::Composite.
Definition at line 100 of file Component.h.
virtual bool chem::Component::isReactionsContainer () const [inline, virtual]
Returns true if this node contains non-zero number of reactions (i.e. ReactionBase pointers)
Reimplemented in chem::Compartment.
Definition at line 106 of file Component.h.
Referenced by chem::Composite::countReactions().
bool chem::Component::isRoot () const [inline]
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 90 of file Component.h.
References _parent.
Referenced by getRoot().
virtual bool chem::Component::isSpeciesContainer () const [inline, virtual]
Returns true if this node contains non-zero number of Species.
Reimplemented in chem::Compartment.
Definition at line 103 of file Component.h.
Referenced by chem::Composite::countSpecies().
virtual size_t chem::Component::numberOfChildren () const [inline, virtual]
Returns the number of children of this node.
Note:
Species and ReactionBase objects are not counted.
Reimplemented in chem::Composite.
Definition at line 97 of file Component.h.
virtual size_t chem::Component::numberOfReactions () const [inline, virtual]
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented in chem::Compartment, and chem::Composite.
Definition at line 114 of file Component.h.
virtual size_t chem::Component::numberOfSpecies () const [inline, virtual]
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.
Reimplemented in chem::Compartment, and chem::Composite.
Definition at line 110 of file Component.h.
virtual void chem::Component::printSelf () [inline, virtual]
Prints information about this node. Useful for debugging.
Reimplemented in chem::CompartmentCubic< NDIM >, chem::Compartment, and chem::CompartmentsSimpleGrid< NDIM >.
Definition at line 128 of file Component.h.
void chem::Component::setParent (Composite * other) [inline]
Sets the parent of this node to other.
Definition at line 86 of file Component.h.
References _parent.
Member Data Documentation
Composite* chem::Component::_parent [private]
The parent of this object. May be a nullptr if this object has no parent.
Definition at line 32 of file Component.h.
Referenced by getParent(), isRoot(), and setParent().
The documentation for this class was generated from the following files:
CytoSim/Component.h
CytoSim/Component.cpp