CytoSim: chem::Visitor Class Reference
chem::Visitor Class Reference
An abstract interface to traverse those nodes in the Composite pattern which fulfil a certain predicate.
#include <Visitor.h>
Public Member Functions
bool visit (Component *c)
When this visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c).
bool visit_if (Component *c)
When this conditional visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
virtual ~Visitor ()
Virtual destructor.
Protected Member Functions
virtual bool visitImpl (Component *c)=0
When this visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
virtual bool predImpl (Component *c)=0
Return true if the Component *c satisfies the desired predicate.
Detailed Description
An abstract interface to traverse those nodes in the Composite pattern which fulfil a certain predicate.
The visitor pattern allows a functor to visit each node of the Composite pattern. Concrete classes derived from Visitor must implement the visit(Component *c) method. Visitor, v, allows a predicate to be applied at each node, *c, and cv->visit(c) is called only if that node satisfies the predicate. For example, this can be used to visit only filaments in the hieararchy.
Definition at line 25 of file Visitor.h.
Constructor & Destructor Documentation
virtual chem::Visitor::~Visitor () [inline, virtual]
Virtual destructor.
Definition at line 48 of file Visitor.h.
Member Function Documentation
virtual bool chem::Visitor::predImpl (Component * c) [protected, pure virtual]
Return true if the Component *c satisfies the desired predicate.
Implemented in chem::VisitorLambda, and chem::CompositeVisitor.
Referenced by visit_if().
bool chem::Visitor::visit (Component * c) [inline]
When this visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Definition at line 31 of file Visitor.h.
References visitImpl().
Referenced by chem::Component::apply(), and chem::Composite::apply().
bool chem::Visitor::visit_if (Component * c) [inline]
When this conditional visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
If v->visit(c) returns a false value, then the further propagation of the tree is terminated.
Definition at line 36 of file Visitor.h.
References predImpl(), and visitImpl().
Referenced by chem::Component::apply_if(), and chem::Composite::apply_if().
virtual bool chem::Visitor::visitImpl (Component * c) [protected, pure virtual]
When this visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Implemented in chem::VisitorLambda, chem::CompositeVisitor, and chem::ConcreteVisitor.
Referenced by visit(), and visit_if().
The documentation for this class was generated from the following file:
CytoSim/Visitor.h