CytoSim: CompartmentProto Class Reference
CompartmentProto Class Reference
#include <Compartment.h>
Public Member Functions
CompartmentProto (System *system)
bool setSpecies ()
void printSpecies ()
Detailed Description
Definition at line 27 of file Compartment.h.
Constructor & Destructor Documentation
CompartmentProto::CompartmentProto (System * system) [inline]
Definition at line 34 of file Compartment.h.
Member Function Documentation
void CompartmentProto::printSpecies () [inline]
Definition at line 36 of file Compartment.h.
Referenced by System::parseSystem().
bool CompartmentProto::setSpecies ()
Definition at line 13 of file Compartment.cpp.
References System::allSpeciesType().
Referenced by System::parseSystem().
The documentation for this class was generated from the following files:
CytoSim/Compartment.h
CytoSim/Compartment.cpp