CytoSim: chem::ChemNRMImpl Class Reference
chem::ChemNRMImpl Class Reference
ChemNRMImpl stands for Chemical Next Reaction Method Implementation.
#include <ChemNRMImpl.h>
Public Member Functions
ChemNRMImpl ()
Ctor: Seeds the random number generator, sets global time to 0.0 and the number of reactions to 0.
ChemNRMImpl (const ChemNRMImpl &rhs)
Copying is not allowed.
ChemNRMImpl & operator= (ChemNRMImpl &rhs)
Assignment is not allowed.
virtual ~ChemNRMImpl ()
Dtor: The reaction network is cleared.
size_t getSize () const
Return the number of reactions in the network.
double getTime () const
Return the current global time (as defined in the NRM algorithm)
void resetTime ()
Sets global time to 0.0.
void syncGlobalTime ()
Sets global time variable to ChemNRMImpl's global time.
boost_heap * getHeap ()
Return a pointer to the heap.
virtual void addReaction (Reaction *r)
Add Reaction *r to the network.
virtual void removeReaction (Reaction *r)
Remove Reaction *r from the network.
double generateTau (double a)
A pure function (without sideeffects), which returns a random time tau, drawn from the exponential distribution, with the propensity given by a.
virtual void initialize ()
This function iterates over all RNodeNRM objects in the network, generating new tau-s for each case and subsequently updating the heap.
virtual bool run (int steps)
This method runs the NRM algorithm for the given number of steps.
virtual void printReactions () const
Prints all RNodes in the reaction network.
Private Member Functions
bool makeStep ()
This is a somewhat complex subroutine which implements the main part of the Gibson-Bruck NRM algoritm.
Private Attributes
std::unordered_map< Reaction
*, std::unique_ptr< RNodeNRM > > _map_rnodes
The database of RNodeNRM objects, representing the reaction network.
boost_heap _heap
A priority queue for the NRM algorithm, containing PQNode elements.
std::mt19937 _eng
Random number generator.
std::exponential_distribution
< double > _exp_distr
Adaptor for the exponential distribution.
double _t
global time
size_t _n_reacts
number of reactions in the network
Detailed Description
ChemNRMImpl stands for Chemical Next Reaction Method Implementation.
ChemNRMImpl manages the NRM algorithm at the level of the network of reactions. In particular, this class contains the NRM heap and the exponential random number generator. Reaction objects can be added and removed from the ChemNRMImpl instance.
Definition at line 167 of file ChemNRMImpl.h.
Constructor & Destructor Documentation
chem::ChemNRMImpl::ChemNRMImpl () [inline]
Ctor: Seeds the random number generator, sets global time to 0.0 and the number of reactions to 0.
Definition at line 170 of file ChemNRMImpl.h.
References resetTime().
chem::ChemNRMImpl::ChemNRMImpl (const ChemNRMImpl & rhs)
Copying is not allowed.
chem::ChemNRMImpl::~ChemNRMImpl () [virtual]
Dtor: The reaction network is cleared.
The RNodeNRM objects will be destructed, but Reaction objects will stay intact. When the RNodeNRM objects are destructed, they in turn destruct the corresponding PQNode element, setting the RNode pointer of the Reaction object to null. At the end, the heap itself will go out of scope.
Definition at line 102 of file ChemNRMImpl.cpp.
References _map_rnodes.
Member Function Documentation
void chem::ChemNRMImpl::addReaction (Reaction * r) [virtual]
Add Reaction *r to the network.
Implements chem::ChemSimImpl.
Definition at line 171 of file ChemNRMImpl.cpp.
References _map_rnodes, and _n_reacts.
double chem::ChemNRMImpl::generateTau (double a)
A pure function (without sideeffects), which returns a random time tau, drawn from the exponential distribution, with the propensity given by a.
Definition at line 106 of file ChemNRMImpl.cpp.
References _eng, and _exp_distr.
Referenced by chem::RNodeNRM::generateNewRandTau().
boost_heap* chem::ChemNRMImpl::getHeap () [inline]
Return a pointer to the heap.
Definition at line 199 of file ChemNRMImpl.h.
References _heap.
Referenced by chem::RNodeNRM::RNodeNRM(), chem::RNodeNRM::updateHeap(), and chem::RNodeNRM::~RNodeNRM().
size_t chem::ChemNRMImpl::getSize () const [inline]
Return the number of reactions in the network.
Definition at line 187 of file ChemNRMImpl.h.
References _n_reacts.
double chem::ChemNRMImpl::getTime () const [inline]
Return the current global time (as defined in the NRM algorithm)
Definition at line 190 of file ChemNRMImpl.h.
References _t.
Referenced by chem::RNodeNRM::generateNewRandTau().
void chem::ChemNRMImpl::initialize () [virtual]
This function iterates over all RNodeNRM objects in the network, generating new tau-s for each case and subsequently updating the heap.
It needs to be called before calling run(...).
Note:
If somewhere in the middle of simulaiton initialize() is called, it will be analogous to starting the simulation from scratch, except with the Species copy numbers given at that moment in time. The global time is reset to zero again.
Implements chem::ChemSimImpl.
Definition at line 93 of file ChemNRMImpl.cpp.
References _map_rnodes, and resetTime().
bool chem::ChemNRMImpl::makeStep () [private]
This is a somewhat complex subroutine which implements the main part of the Gibson-Bruck NRM algoritm.
See the implementation for details. After this method returns, roughly the following will have happened: 1) The Reaction corresponding to the lowest tau RNodeNRM is executed and the corresponding Species copy numbers are changed 2) A new tau is computed from this Reaction and the corresponding PQNode element is updated in the heap 3) The other affected Reaction objects are found, their taus are recomputed and corresponding PQNode elements are updated in the heap. 4) For the Reaction and associated Species signals are emitted, if these objects broadcast signals upon change. Returns true if successful, and false if the heap is exchausted and there no more reactions to fire
Definition at line 112 of file ChemNRMImpl.cpp.
References _heap, _t, chem::Reaction::beginProducts(), chem::Reaction::beginReactants(), chem::Reaction::dependents(), chem::Reaction::emitSignal(), chem::Reaction::endProducts(), chem::Reaction::endReactants(), chem::RNodeNRM::generateNewRandTau(), chem::RNodeNRM::getPropensity(), chem::RNodeNRM::getReaction(), chem::RNodeNRM::getTau(), chem::RNodeNRM::isPassivated(), chem::RNodeNRM::makeStep(), chem::RNodeNRM::reComputePropensity(), chem::RNodeNRM::setTau(), syncGlobalTime(), and chem::RNodeNRM::updateHeap().
Referenced by run().
ChemNRMImpl& chem::ChemNRMImpl::operator= (ChemNRMImpl & rhs)
Assignment is not allowed.
void chem::ChemNRMImpl::printReactions () const [virtual]
Prints all RNodes in the reaction network.
Implements chem::ChemSimImpl.
Definition at line 181 of file ChemNRMImpl.cpp.
References _map_rnodes.
void chem::ChemNRMImpl::removeReaction (Reaction * r) [virtual]
Remove Reaction *r from the network.
Implements chem::ChemSimImpl.
Definition at line 176 of file ChemNRMImpl.cpp.
References _map_rnodes, and _n_reacts.
void chem::ChemNRMImpl::resetTime () [inline]
Sets global time to 0.0.
Definition at line 193 of file ChemNRMImpl.h.
References _t, and syncGlobalTime().
Referenced by ChemNRMImpl(), and initialize().
virtual bool chem::ChemNRMImpl::run (int steps) [inline, virtual]
This method runs the NRM algorithm for the given number of steps.
Implements chem::ChemSimImpl.
Definition at line 219 of file ChemNRMImpl.h.
References makeStep().
void chem::ChemNRMImpl::syncGlobalTime () [inline]
Sets global time variable to ChemNRMImpl's global time.
Definition at line 196 of file ChemNRMImpl.h.
References _t, and global_time.
Referenced by makeStep(), and resetTime().
Member Data Documentation
std::mt19937 chem::ChemNRMImpl::_eng [private]
Random number generator.
Definition at line 246 of file ChemNRMImpl.h.
Referenced by generateTau().
std::exponential_distribution<double> chem::ChemNRMImpl::_exp_distr [private]
Adaptor for the exponential distribution.
Definition at line 247 of file ChemNRMImpl.h.
Referenced by generateTau().
boost_heap chem::ChemNRMImpl::_heap [private]
A priority queue for the NRM algorithm, containing PQNode elements.
Definition at line 245 of file ChemNRMImpl.h.
Referenced by getHeap(), and makeStep().
std::unordered_map<Reaction*, std::unique_ptr<RNodeNRM> > chem::ChemNRMImpl::_map_rnodes [private]
The database of RNodeNRM objects, representing the reaction network.
Definition at line 244 of file ChemNRMImpl.h.
Referenced by addReaction(), initialize(), printReactions(), removeReaction(), and ~ChemNRMImpl().
size_t chem::ChemNRMImpl::_n_reacts [private]
number of reactions in the network
Definition at line 249 of file ChemNRMImpl.h.
Referenced by addReaction(), getSize(), and removeReaction().
double chem::ChemNRMImpl::_t [private]
global time
Definition at line 248 of file ChemNRMImpl.h.
Referenced by getTime(), makeStep(), resetTime(), and syncGlobalTime().
The documentation for this class was generated from the following files:
CytoSim/ChemNRMImpl.h
CytoSim/ChemNRMImpl.cpp