CytoSim: chem::RSpecies Class Reference
chem::RSpecies Class Reference
RSpecies class represents the reactive aspect of chemical molecules. It tracks their copy number and can be used in Reactions.
#include <RSpecies.h>
Public Member Functions
~RSpecies ()
It is required that all Reactions associated with this RSpecies are destructed before this RSpecies is destructed.
void emitSignal (int delta)
Broadcasts signal indicating that the copy number of this RSpecies has changed This method should usually called by the code which runs the chemical dynamics (i.e.
species_copy_t getN () const
Return the current copy number of this RSpecies.
species_copy_t getUpperLimitForN () const
Return the upper limit for the copy number of this RSpecies.
Species & getSpecies ()
return parent Species as a reference
const Species & getSpecies () const
return parent Species as a const reference
std::string getFullName () const
Return the full name of this Species in a std::string format (e.g. "Arp2/3{Bulk}".
bool isSignaling () const
Return true if this RSpecies emits signals on copy number change.
std::vector< Reaction * > ReactantReactions ()
Return std::vector<Reaction *>, which contains pointers to all Reactions where this RSpecies is involved as a Reactant.
std::vector< Reaction * > ProductReactions ()
Return std::vector<Reaction *>, which contains pointers to all Reactions where this RSpecies is involved as a Product.
vr_iterator beginReactantReactions ()
Return std::vector<Reaction *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Reactant.
vr_iterator beginProductReactions ()
Return std::vector<Reaction *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Product.
vr_iterator endReactantReactions ()
Return std::vector<Reaction *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Reactant.
vr_iterator endProductReactions ()
Return std::vector<Reaction *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Product.
Private Member Functions
RSpecies (Species &parent, species_copy_t n=0, species_copy_t ulim=max_ulim)
Constructors.
RSpecies (const RSpecies &r)
deleted copy constructor - each RSpecies is uniquely created by the parent Species
RSpecies (RSpecies &&r)
deleted move constructor - each RSpecies is uniquely created by the parent Species
RSpecies & operator= (RSpecies &)
deleted assignment operator - each RSpecies is uniquely created by the parent Species
void setN (species_copy_t n)
Sets the copy number for this RSpecies.
void setUpperLimitForN (species_copy_t ulim)
Sets the upper limit for the copy number of this RSpecies.
void up ()
Increases the copy number by 1.
void down ()
Decreases the copy number by 1.
void addAsReactant (Reaction *r)
void addAsProduct (Reaction *r)
void removeAsReactant (const Reaction *r)
void removeAsProduct (const Reaction *r)
void activateAssocReactantReactions ()
void activateAssocProductReactions ()
void passivateAssocReactantReactions ()
void passivateAssocProductReactions ()
void startSignaling ()
Set the signaling behavior of this RSpecies.
void stopSignaling ()
Destroy the signal associated with this RSpecies; all associated slots will be destroyed.
Private Attributes
std::vector< Reaction * > _as_reactants
a vector of Reactions where this RSpecies is a Reactant
std::vector< Reaction * > _as_products
a vector of Reactions where this RSpecies is a Product
Species & _species
reference to the parent Species object
species_copy_t _n
Current copy number of this RSpecies.
species_copy_t _ulim
Upper limit for the copy number, afterwards all reactions leading to further accum. are turned off.
RSpeciesCopyNChangedSignal * _signal
Can be used to broadcast a signal associated with change of n of.
Friends
class Reaction
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
class Species
Detailed Description
RSpecies class represents the reactive aspect of chemical molecules. It tracks their copy number and can be used in Reactions.
This class represents the reactivity of chemical species. The name RSpecies stems from reacting species. RSpecies tracks the copy number of molecules and the Reactions in which it is involed (
See also:
Reaction).
Note:
Each intantiation of RSpecies is unique, and hence, cannot be neither copied nor moved (C++11). This has significant implications - e.g., RSpecies cannot be used in std::vector<RSpecies>. Instead, one should use either std::vector<RSpecies*> if not owning the RSpecies pointers, or std::vector<std::unique_ptr<RSpecies>> if owning the RSpecies pointers. A special allocator can be written such that dynamically allocated RSpecies (through new), are arranged contigiously in memory.
Definition at line 57 of file RSpecies.h.
Constructor & Destructor Documentation
chem::RSpecies::RSpecies (Species & parent, species_copy_t n = 0, species_copy_t ulim = max_ulim) [inline, private]
Constructors.
Parameters:
parent - the Species object to which this RSpecies belongs
n - copy number
Definition at line 75 of file RSpecies.h.
chem::RSpecies::RSpecies (const RSpecies & r) [private]
deleted copy constructor - each RSpecies is uniquely created by the parent Species
chem::RSpecies::RSpecies (RSpecies && r) [private]
deleted move constructor - each RSpecies is uniquely created by the parent Species
chem::RSpecies::~RSpecies () [inline]
It is required that all Reactions associated with this RSpecies are destructed before this RSpecies is destructed.
Most of the time, this will occur naturally. If not, an assertion will ungracefully terminate the program.
Definition at line 180 of file RSpecies.h.
References _as_products, _as_reactants, and _signal.
Member Function Documentation
void chem::RSpecies::activateAssocProductReactions () [private]
Attempts to activate previously passivated Reactions where this RSpecies is involved as a Product. Usually, the Reaction was first passivated, for example if the RSpecies copy number of one of the reactants went up to max_ulim.
Definition at line 31 of file RSpecies.cpp.
References _as_products.
Referenced by down().
void chem::RSpecies::activateAssocReactantReactions () [private]
Attempts to activate previously passivated Reactions where this RSpecies is involved as a Reactant. Usually, the Reaction was first passivated, for example if the RSpecies copy number of one of the reactants dropeed to zero. This attempt may not succeed if there are still other reactants in the same Reaction with zero copy count.
Definition at line 26 of file RSpecies.cpp.
References _as_reactants.
Referenced by up().
void chem::RSpecies::addAsProduct (Reaction * r) [inline, private]
Definition at line 133 of file RSpecies.h.
References _as_products.
Referenced by chem::Reaction::Reaction().
void chem::RSpecies::addAsReactant (Reaction * r) [inline, private]
Definition at line 129 of file RSpecies.h.
References _as_reactants.
Referenced by chem::Reaction::Reaction().
vr_iterator chem::RSpecies::beginProductReactions () [inline]
Return std::vector<Reaction *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Product.
Definition at line 226 of file RSpecies.h.
References _as_products.
vr_iterator chem::RSpecies::beginReactantReactions () [inline]
Return std::vector<Reaction *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Reactant.
Definition at line 222 of file RSpecies.h.
References _as_reactants.
void chem::RSpecies::down () [inline, private]
Decreases the copy number by 1.
If the copy number changes becomes 0, calls a "callback"-like method to passivate Reactions, where this RSpecies is a Reactant.
Definition at line 112 of file RSpecies.h.
References _n, _ulim, activateAssocProductReactions(), and passivateAssocReactantReactions().
void chem::RSpecies::emitSignal (int delta) [inline]
Broadcasts signal indicating that the copy number of this RSpecies has changed This method should usually called by the code which runs the chemical dynamics (i.e.
Gillespie-like algorithm)
Definition at line 189 of file RSpecies.h.
References isSignaling().
vr_iterator chem::RSpecies::endProductReactions () [inline]
Return std::vector<Reaction *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Product.
Definition at line 234 of file RSpecies.h.
References _as_products.
vr_iterator chem::RSpecies::endReactantReactions () [inline]
Return std::vector<Reaction *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Reactant.
Definition at line 230 of file RSpecies.h.
References _as_reactants.
std::string chem::RSpecies::getFullName () const
Return the full name of this Species in a std::string format (e.g. "Arp2/3{Bulk}".
Definition at line 21 of file RSpecies.cpp.
References _species, and chem::Species::getFullName().
Referenced by operator<<().
species_copy_t chem::RSpecies::getN () const [inline]
Return the current copy number of this RSpecies.
Definition at line 195 of file RSpecies.h.
References _n.
Referenced by chem::Reaction::computePropensity(), and operator<<().
Species& chem::RSpecies::getSpecies () [inline]
return parent Species as a reference
Definition at line 201 of file RSpecies.h.
References _species.
const Species& chem::RSpecies::getSpecies () const [inline]
return parent Species as a const reference
Definition at line 204 of file RSpecies.h.
References _species.
species_copy_t chem::RSpecies::getUpperLimitForN () const [inline]
Return the upper limit for the copy number of this RSpecies.
Definition at line 198 of file RSpecies.h.
References _ulim.
bool chem::RSpecies::isSignaling () const [inline]
Return true if this RSpecies emits signals on copy number change.
Definition at line 210 of file RSpecies.h.
References _signal.
Referenced by emitSignal().
RSpecies& chem::RSpecies::operator= (RSpecies &) [private]
deleted assignment operator - each RSpecies is uniquely created by the parent Species
void chem::RSpecies::passivateAssocProductReactions () [private]
Passivates all Reactions where this RSpecies is among the products.
Definition at line 41 of file RSpecies.cpp.
References _as_products.
Referenced by up().
void chem::RSpecies::passivateAssocReactantReactions () [private]
Passivates all Reactions where this RSpecies is among the reactants.
Definition at line 36 of file RSpecies.cpp.
References _as_reactants.
Referenced by down().
std::vector<Reaction *> chem::RSpecies::ProductReactions () [inline]
Return std::vector<Reaction *>, which contains pointers to all Reactions where this RSpecies is involved as a Product.
Definition at line 218 of file RSpecies.h.
References _as_products.
std::vector<Reaction *> chem::RSpecies::ReactantReactions () [inline]
Return std::vector<Reaction *>, which contains pointers to all Reactions where this RSpecies is involved as a Reactant.
Definition at line 214 of file RSpecies.h.
References _as_reactants.
void chem::RSpecies::removeAsProduct (const Reaction * r) [inline, private]
Definition at line 146 of file RSpecies.h.
References _as_products.
Referenced by chem::Reaction::~Reaction().
void chem::RSpecies::removeAsReactant (const Reaction * r) [inline, private]
Definition at line 137 of file RSpecies.h.
References _as_products, and _as_reactants.
Referenced by chem::Reaction::~Reaction().
void chem::RSpecies::setN (species_copy_t n) [inline, private]
Sets the copy number for this RSpecies.
Parameters:
n should be a non-negative number, but no checking is done in run time
Note:
The operation does not emit any signals about the copy number change.
Definition at line 90 of file RSpecies.h.
References _n.
void chem::RSpecies::setUpperLimitForN (species_copy_t ulim) [inline, private]
Sets the upper limit for the copy number of this RSpecies.
Parameters:
ulim should be a non-negative number, but no checking is done in run time
Definition at line 94 of file RSpecies.h.
References _ulim.
void chem::RSpecies::startSignaling () [private]
Set the signaling behavior of this RSpecies.
Definition at line 46 of file RSpecies.cpp.
References _signal.
void chem::RSpecies::stopSignaling () [private]
Destroy the signal associated with this RSpecies; all associated slots will be destroyed.
Note:
To start signaling again, startSignaling() needs to be called
Definition at line 50 of file RSpecies.cpp.
References _signal.
void chem::RSpecies::up () [inline, private]
Increases the copy number by 1.
If the copy number changes from 0 to 1, calls a "callback"-like method to activated previously passivated Reactions, where this RSpecies is a Reactant.
Definition at line 98 of file RSpecies.h.
References _n, _ulim, activateAssocReactantReactions(), and passivateAssocProductReactions().
Friends And Related Function Documentation
friend class Reaction [friend]
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
Definition at line 59 of file RSpecies.h.
friend class Species [friend]
Definition at line 60 of file RSpecies.h.
Member Data Documentation
std::vector<Reaction *> chem::RSpecies::_as_products [private]
a vector of Reactions where this RSpecies is a Product
Definition at line 64 of file RSpecies.h.
Referenced by activateAssocProductReactions(), addAsProduct(), beginProductReactions(), endProductReactions(), passivateAssocProductReactions(), ProductReactions(), removeAsProduct(), removeAsReactant(), and ~RSpecies().
std::vector<Reaction *> chem::RSpecies::_as_reactants [private]
a vector of Reactions where this RSpecies is a Reactant
Definition at line 63 of file RSpecies.h.
Referenced by activateAssocReactantReactions(), addAsReactant(), beginReactantReactions(), endReactantReactions(), passivateAssocReactantReactions(), ReactantReactions(), removeAsReactant(), and ~RSpecies().
species_copy_t chem::RSpecies::_n [private]
Current copy number of this RSpecies.
Definition at line 66 of file RSpecies.h.
Referenced by down(), getN(), setN(), and up().
RSpeciesCopyNChangedSignal* chem::RSpecies::_signal [private]
Can be used to broadcast a signal associated with change of n of.
this RSpecies (usually when a single step of this Reaction occurs)
Definition at line 68 of file RSpecies.h.
Referenced by isSignaling(), startSignaling(), stopSignaling(), and ~RSpecies().
Species& chem::RSpecies::_species [private]
reference to the parent Species object
Definition at line 65 of file RSpecies.h.
Referenced by getFullName(), and getSpecies().
species_copy_t chem::RSpecies::_ulim [private]
Upper limit for the copy number, afterwards all reactions leading to further accum. are turned off.
Definition at line 67 of file RSpecies.h.
Referenced by down(), getUpperLimitForN(), setUpperLimitForN(), and up().
The documentation for this class was generated from the following files:
CytoSim/RSpecies.h
CytoSim/RSpecies.cpp