CytoSim: SignalingManager Class Reference
SignalingManager Class Reference
SignalingManager manages callbacks for Species and Reactions objects.
#include <Signaling.h>
Public Member Functions
void emitReactionSignal (Reaction *r) const
Broadcasts signal corresponding to Reaction *r.
void emitSpeciesSignal (Species *s, int delta) const
Broadcasts signal corresponding to Species *s.
void addSignalingSpecies (Species *s)
Inserts a signal corresponding to Species *s into the map.
void addSignalingReaction (Reaction *r)
Inserts a signal corresponding to Reaction *r into the map.
boost::signals2::connection connect (Reaction *r, std::function< void(Reaction *)> const &react_callback, int priority=5)
Connect the callback, react_callback to a signal corresponding to Reaction *r.
boost::signals2::connection connect (Species *s, std::function< void(Species *, int)> const &species_callback, int priority=10)
Connect the callback, species_callback to a signal corresponding to Species *s.
void disconnect_semiprivate (Reaction *r)
Destroy signal corresponding to Reaction r.
void disconnect_semiprivate (Species *s)
Destroy signal corresponding to Reaction r.
Private Member Functions
std::unordered_map< Reaction
*, std::unique_ptr
< ReactionEventSignal >
>::const_iterator findSignal (Reaction *r) const
Search the map for a signal corresponding to parameter, Reaction *r. Throw std::out_of_range exception if not found.
std::unordered_map< Species
*, std::unique_ptr
< SpeciesCopyNChangedSignal >
>::const_iterator findSignal (Species *s) const
Search the map for a signal corresponding to parameter, Species *s. Throw std::out_of_range exception if not found.
void assertSignalDoesNotExist (Reaction *r)
Assert that a signal corresponding to Reaction *r does not exist or throw std::runtime_error.
void assertSignalDoesNotExist (Species *s)
Assert that a signal corresponding to Species *s does not exist or throw std::runtime_error.
Private Attributes
std::unordered_map< Species
*, std::unique_ptr
< SpeciesCopyNChangedSignal > > _map_species_signal
Keep track of signals corresponding to various Species.
std::unordered_map< Reaction
*, std::unique_ptr
< ReactionEventSignal > > _map_reaction_signal
Keep track of signals corresponding to various Reactions.
Detailed Description
SignalingManager manages callbacks for Species and Reactions objects.
One SignalingManager should be instantiated per chemical network. Species and Reactions that need to be monitored can be made to signal, based on the boost:signal2 library. Multiple receiving slots can be connected to signals.
Slots can be temporarily blocked or completely disconnected. Signals can be destroyed. Here is an example of usage:
 ...
 Species* A1 = sc.getSpecies("A1");
 ...
 SignalingManager sm;
 A1->makeSignaling(sm);
 PrintSpecies ps;
 std::function<void (Species *, int)> psf(ps);
 boost::signals2::shared_connection_block conn_a1(sm.connect(A1, [](Species *s, int i){s->printSelf();}), true);
 // or   sm.connect(A1, print_species);
 // or  sm.connect(A1, PrintSpecies());
 // or   boost::signals2::shared_connection_block conn_a1(sm.connect(A1,psf), false);
...
// run simulation for some time
 ...
 conn_a1.block(); // this temporarily stops slots from being called.
...
 conn_a1.disconnect(); // this permanently disconnects the slot
...
 A1->stopSignaling(sm); // this destroys the Signal itself (with associated multiple slots)
...
Definition at line 63 of file Signaling.h.
Member Function Documentation
void SignalingManager::addSignalingReaction (Reaction * r) [inline]
Inserts a signal corresponding to Reaction *r into the map.
Should only be called by the Reaction class.
Note:
other classes should instead call void Reaction::makeSignaling(SignalingManager &sm);
Definition at line 122 of file Signaling.h.
References _map_reaction_signal, and assertSignalDoesNotExist().
Referenced by Reaction::makeSignaling().
void SignalingManager::addSignalingSpecies (Species * s) [inline]
Inserts a signal corresponding to Species *s into the map.
Should only be called by the Species class.
Note:
other classes should instead call void Species::makeSignaling(SignalingManager &sm);
Definition at line 114 of file Signaling.h.
References _map_species_signal, and assertSignalDoesNotExist().
Referenced by Species::makeSignaling().
void SignalingManager::assertSignalDoesNotExist (Reaction * r) [inline, private]
Assert that a signal corresponding to Reaction *r does not exist or throw std::runtime_error.
Definition at line 84 of file Signaling.h.
References _map_reaction_signal.
Referenced by addSignalingReaction(), and addSignalingSpecies().
void SignalingManager::assertSignalDoesNotExist (Species * s) [inline, private]
Assert that a signal corresponding to Species *s does not exist or throw std::runtime_error.
Definition at line 91 of file Signaling.h.
References _map_species_signal.
boost::signals2::connection SignalingManager::connect (Reaction * r, std::function< void(Reaction *)> const & react_callback, int priority = 5) [inline]
Connect the callback, react_callback to a signal corresponding to Reaction *r.
Parameters:
Reaction *r - the signal will correspond to this Reaction
std::function<void (Reaction *)> const &react_callback - a function object to be called (a slot)
int priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Definition at line 132 of file Signaling.h.
References findSignal().
Referenced by main().
boost::signals2::connection SignalingManager::connect (Species * s, std::function< void(Species *, int)> const & species_callback, int priority = 10) [inline]
Connect the callback, species_callback to a signal corresponding to Species *s.
Parameters:
Species *s - the signal will correspond to this Species
std::function<void (Species *, int)> const &species_callback - a function object to be called (a slot). int here corresponds to delta, the change in copy number of the Species (for which the signal was emitted)
int priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Definition at line 143 of file Signaling.h.
References findSignal().
void SignalingManager::disconnect_semiprivate (Reaction * r) [inline]
Destroy signal corresponding to Reaction r.
Should only be used by the Reaction class.
Note:
Other classes should instead call void Reaction::stopSignaling (SignalingManager &sm);
Definition at line 150 of file Signaling.h.
References _map_reaction_signal, and findSignal().
Referenced by Reaction::stopSignaling(), and Species::stopSignaling().
void SignalingManager::disconnect_semiprivate (Species * s) [inline]
Destroy signal corresponding to Reaction r.
Should only be used by the Species class.
Note:
Other classes should instead call void Species::stopSignaling (SignalingManager &sm);
Definition at line 157 of file Signaling.h.
References _map_species_signal, and findSignal().
void SignalingManager::emitReactionSignal (Reaction * r) const [inline]
Broadcasts signal corresponding to Reaction *r.
If the Reaction is not found, std::out_of_range exception will be thrown. This method is usally only called by the Gillespie-like algorithm, and not the outside code.
Definition at line 100 of file Signaling.h.
References findSignal().
Referenced by ChemNRMImpl::makeStep().
void SignalingManager::emitSpeciesSignal (Species * s, int delta) const [inline]
Broadcasts signal corresponding to Species *s.
If the Specis is not found, std::out_of_range exception will be thrown. This method is usally only called by the Gillespie-like algorithm, and not the outside code.
Definition at line 107 of file Signaling.h.
References findSignal().
Referenced by ChemNRMImpl::makeStep().
std::unordered_map<Reaction *, std::unique_ptr<ReactionEventSignal> >::const_iterator SignalingManager::findSignal (Reaction * r) const [inline, private]
Search the map for a signal corresponding to parameter, Reaction *r. Throw std::out_of_range exception if not found.
Definition at line 67 of file Signaling.h.
References _map_reaction_signal.
Referenced by connect(), disconnect_semiprivate(), emitReactionSignal(), and emitSpeciesSignal().
std::unordered_map<Species *, std::unique_ptr<SpeciesCopyNChangedSignal> >::const_iterator SignalingManager::findSignal (Species * s) const [inline, private]
Search the map for a signal corresponding to parameter, Species *s. Throw std::out_of_range exception if not found.
Definition at line 76 of file Signaling.h.
References _map_species_signal.
Member Data Documentation
std::unordered_map<Reaction *, std::unique_ptr<ReactionEventSignal> > SignalingManager::_map_reaction_signal [private]
Keep track of signals corresponding to various Reactions.
Definition at line 163 of file Signaling.h.
Referenced by addSignalingReaction(), assertSignalDoesNotExist(), disconnect_semiprivate(), and findSignal().
std::unordered_map<Species *, std::unique_ptr<SpeciesCopyNChangedSignal> > SignalingManager::_map_species_signal [private]
Keep track of signals corresponding to various Species.
Definition at line 162 of file Signaling.h.
Referenced by addSignalingSpecies(), assertSignalDoesNotExist(), disconnect_semiprivate(), and findSignal().
The documentation for this class was generated from the following file:
CytoSim/Signaling.h