CytoSim: chem::ConcreteVisitor Class Reference
chem::ConcreteVisitor Class Reference
ConcreteVisitor is an example visitor, following the regular Visitor pattern.
#include <VisitorConcrete.h>
Public Member Functions
bool visit (Component *c)
When this visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c).
bool visit_if (Component *c)
When this conditional visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
Protected Member Functions
virtual bool visitImpl (Component *c) override
When this visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
virtual bool predImpl (Component *c)=0
Return true if the Component *c satisfies the desired predicate.
Detailed Description
ConcreteVisitor is an example visitor, following the regular Visitor pattern.
Definition at line 19 of file VisitorConcrete.h.
Member Function Documentation
virtual bool chem::Visitor::predImpl (Component * c) [protected, pure virtual, inherited]
Return true if the Component *c satisfies the desired predicate.
Implemented in chem::VisitorLambda, and chem::CompositeVisitor.
Referenced by chem::Visitor::visit_if().
bool chem::Visitor::visit (Component * c) [inline, inherited]
When this visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Definition at line 31 of file Visitor.h.
References chem::Visitor::visitImpl().
Referenced by chem::Component::apply(), and chem::Composite::apply().
bool chem::Visitor::visit_if (Component * c) [inline, inherited]
When this conditional visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
If v->visit(c) returns a false value, then the further propagation of the tree is terminated.
Definition at line 36 of file Visitor.h.
References chem::Visitor::predImpl(), and chem::Visitor::visitImpl().
Referenced by chem::Component::apply_if(), and chem::Composite::apply_if().
virtual bool chem::ConcreteVisitor::visitImpl (Component * c) [inline, override, protected, virtual]
When this visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Implements chem::Visitor.
Definition at line 21 of file VisitorConcrete.h.
References chem::Component::countSpecies(), and chem::Component::getFullName().
The documentation for this class was generated from the following file:
CytoSim/VisitorConcrete.h