CytoSim: chem::ChemSimImpl Class Reference
chem::ChemSimImpl Class Reference
ChemSimImpl is an abstract base class for algorithms that run stochastic chemical kinetics.
#include <ChemSimImpl.h>
Public Member Functions
virtual ~ChemSimImpl ()
virtual void initialize ()=0
After all initial reactions have been added via addReaction(...) method, invoke initialize() prior to invoking run()
virtual void addReaction (ReactionBase *r)=0
Add Reaction *r to the chemical network which needs to be simulated.
virtual void removeReaction (ReactionBase *r)=0
Remove Reaction *r from the simulated chemical network.
virtual bool run (int steps)=0
Run the chemical dynamics for a specific number of steps.
virtual void printReactions () const =0
Mainly used for debugging: print chemical reactions in the network at this moment.
Detailed Description
ChemSimImpl is an abstract base class for algorithms that run stochastic chemical kinetics.
Specific stochastic kinetics algorithm classes should inherit from ChemSimImpl. A user will then attach the corresponding algorithm to ChemSim via the algoritm's base class ChemSimImpl.
Definition at line 19 of file ChemSimImpl.h.
Constructor & Destructor Documentation
virtual chem::ChemSimImpl::~ChemSimImpl () [inline, virtual]
Definition at line 21 of file ChemSimImpl.h.
Member Function Documentation
virtual void chem::ChemSimImpl::addReaction (ReactionBase * r) [pure virtual]
Add Reaction *r to the chemical network which needs to be simulated.
Implemented in chem::ChemNRMImpl, chem::ChemGillespieImpl, and chem::ChemSimpleGillespieImpl.
Referenced by chem::ChemSim::addReaction().
virtual void chem::ChemSimImpl::initialize () [pure virtual]
After all initial reactions have been added via addReaction(...) method, invoke initialize() prior to invoking run()
Implemented in chem::ChemNRMImpl, chem::ChemGillespieImpl, and chem::ChemSimpleGillespieImpl.
Referenced by chem::ChemSim::initialize().
virtual void chem::ChemSimImpl::printReactions () const [pure virtual]
Mainly used for debugging: print chemical reactions in the network at this moment.
Implemented in chem::ChemNRMImpl, chem::ChemGillespieImpl, and chem::ChemSimpleGillespieImpl.
Referenced by chem::ChemSim::printReactions().
virtual void chem::ChemSimImpl::removeReaction (ReactionBase * r) [pure virtual]
Remove Reaction *r from the simulated chemical network.
Implemented in chem::ChemNRMImpl, chem::ChemGillespieImpl, and chem::ChemSimpleGillespieImpl.
Referenced by chem::ChemSim::removeReaction().
virtual bool chem::ChemSimImpl::run (int steps) [pure virtual]
Run the chemical dynamics for a specific number of steps.
Implemented in chem::ChemNRMImpl, chem::ChemGillespieImpl, and chem::ChemSimpleGillespieImpl.
Referenced by chem::ChemSim::run().
The documentation for this class was generated from the following file:
CytoSim/ChemSimImpl.h