CytoSim: chem::SpeciesType Class Reference
chem::SpeciesType Class Reference
SpeciesType class represents the type of chemical Species (for example, a Species with name "Arp2/3" and SType Diffusing)
#include <SpeciesType.h>
Public Member Functions
SpeciesType (const std::string &name, SType type)
Given a species name as a string and its SType, constructs the SpeciesType.
SpeciesType (const SpeciesType &st)
Given a species name as a string and its type as a string, constructs the SpeciesType.
SpeciesType (SpeciesType &&st)
The move constructor.
void swap (SpeciesType &other)
Specialize swap.
SpeciesType & operator= (const SpeciesType &other)
The lvalue assignment operator.
SpeciesType & operator= (SpeciesType &&st)
Move assignment operator (i.e. rvalue asignment)
bool operator== (const SpeciesType &species_type) const
Equality operator use both species name and type to compare to SpeciesType objects.
bool operator!= (const SpeciesType &species_type) const
Inequality operator use both species name and type to compare to SpeciesType objects.
std::string getName () const
Returns the name associated with this SpeciesType as a string.
SType getType () const
Returns the SType associated with this SpeciesType.
std::string getTypeAsString () const
Returns a string representing this SpeciesType by concatanating its name and type.
bool is_of_type (const std::string &name, SType type) const
Return if true if this SpeciesType has name and SType given as parameters to this function.
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
This class can be serialized via Boost::Serialization empty f-n - because SpeciesType does not have default ctor, we have to use instead save_construct_data and load_construct_data.
Private Attributes
std::string _name
the descriptive name associated with this Species
SType _type
the type of species, such as Bulk, Diffusing, etc.
Friends
class boost::serialization::access
Needed by Boost::Serialization machinery.
std::size_t hash_value (SpeciesType const &species_type)
boost::flyweight needs a hashing function, defined here.
std::ostream & operator<< (std::ostream &os, const SpeciesType &st)
Prints the SpeciesType to ostream with a format name[SType], such as "Arp2/3[Diffusing]".
Detailed Description
SpeciesType class represents the type of chemical Species (for example, a Species with name "Arp2/3" and SType Diffusing)
This class describes the type of Species. The description is based on a name (std::string) and SType (Bulk, Diffusing, etc.).
Note:
In the future may implement the Logging and Persistence interfaces.
SpeciesType is used by Species with the flyweight pattern, since in a large system millions of unique Species may exist, but only a handful of SpeciesType objects. For example: one ("F-Actin",Filament) may correspond to millions of individual Species.
Definition at line 41 of file SpeciesType.h.
Constructor & Destructor Documentation
chem::SpeciesType::SpeciesType (const std::string & name, SType type) [inline]
Given a species name as a string and its SType, constructs the SpeciesType.
Definition at line 57 of file SpeciesType.h.
chem::SpeciesType::SpeciesType (const SpeciesType & st) [inline]
Given a species name as a string and its type as a string, constructs the SpeciesType.
Definition at line 60 of file SpeciesType.h.
chem::SpeciesType::SpeciesType (SpeciesType && st) [inline]
The move constructor.
Definition at line 63 of file SpeciesType.h.
Member Function Documentation
std::string chem::SpeciesType::getName () const [inline]
Returns the name associated with this SpeciesType as a string.
Definition at line 100 of file SpeciesType.h.
References _name.
Referenced by operator==(), and boost::serialization::save_construct_data().
SType chem::SpeciesType::getType () const [inline]
Returns the SType associated with this SpeciesType.
Definition at line 104 of file SpeciesType.h.
References _type.
Referenced by operator==(), and boost::serialization::save_construct_data().
std::string chem::SpeciesType::getTypeAsString () const
Returns a string representing this SpeciesType by concatanating its name and type.
Definition at line 16 of file SpeciesType.cpp.
References _type, and chem::vec_type_name.
bool chem::SpeciesType::is_of_type (const std::string & name, SType type) const [inline]
Return if true if this SpeciesType has name and SType given as parameters to this function.
Definition at line 110 of file SpeciesType.h.
References _name, and _type.
bool chem::SpeciesType::operator!= (const SpeciesType & species_type) const [inline]
Inequality operator use both species name and type to compare to SpeciesType objects.
Definition at line 94 of file SpeciesType.h.
SpeciesType& chem::SpeciesType::operator= (const SpeciesType & other) [inline]
The lvalue assignment operator.
Definition at line 73 of file SpeciesType.h.
References _name, and _type.
SpeciesType& chem::SpeciesType::operator= (SpeciesType && st) [inline]
Move assignment operator (i.e. rvalue asignment)
Definition at line 81 of file SpeciesType.h.
References _name, and _type.
bool chem::SpeciesType::operator== (const SpeciesType & species_type) const [inline]
Equality operator use both species name and type to compare to SpeciesType objects.
Definition at line 88 of file SpeciesType.h.
References _name, _type, getName(), and getType().
template<class Archive > void chem::SpeciesType::serialize (Archive & ar, const unsigned int version) [inline, private]
This class can be serialized via Boost::Serialization empty f-n - because SpeciesType does not have default ctor, we have to use instead save_construct_data and load_construct_data.
Definition at line 50 of file SpeciesType.h.
void chem::SpeciesType::swap (SpeciesType & other) [inline]
Specialize swap.
Definition at line 66 of file SpeciesType.h.
References _name, and _type.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Needed by Boost::Serialization machinery.
Definition at line 54 of file SpeciesType.h.
std::size_t hash_value (SpeciesType const & species_type) [friend]
boost::flyweight needs a hashing function, defined here.
Definition at line 113 of file SpeciesType.h.
std::ostream& operator<< (std::ostream & os, const SpeciesType & st) [friend]
Prints the SpeciesType to ostream with a format name[SType], such as "Arp2/3[Diffusing]".
Definition at line 123 of file SpeciesType.h.
Member Data Documentation
std::string chem::SpeciesType::_name [private]
the descriptive name associated with this Species
Definition at line 43 of file SpeciesType.h.
Referenced by getName(), is_of_type(), operator=(), operator==(), and swap().
SType chem::SpeciesType::_type [private]
the type of species, such as Bulk, Diffusing, etc.
Definition at line 44 of file SpeciesType.h.
Referenced by getType(), getTypeAsString(), is_of_type(), operator=(), operator==(), and swap().
The documentation for this class was generated from the following files:
CytoSim/SpeciesType.h
CytoSim/SpeciesType.cpp