CytoSim: chem::Composite Class Reference
chem::Composite Class Reference
Composite class is the aggregating class for the Composite pattern.
#include <Composite.h>
Public Member Functions
Composite ()
Default Constructor does nothing.
virtual ~Composite () noexcept
Virtual Destructor does nothing.
virtual bool apply (Visitor &v) override
Implements the apply() method of the Component class by recursively applying it to itself and all its children.
virtual bool apply_if (Visitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
virtual bool apply (SpeciesVisitor &v) override
Implements the apply() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply_if (SpeciesVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v) override
When this function is applied to a ReactionVisitor sv, the corresponding v.visit(s) is called for each ReactionBase pointer *s owned by the node.
virtual bool apply_if (ReactionVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool isComposite () const override
Returns true.
virtual std::string getFullName () const override
Returns the full name of this node.
virtual void addChild (std::unique_ptr< Component > &&child)
Adds a Component child to this Composite node.
virtual void removeChild (Component *child)
Remove *child from this node's children. The child's destructor will be called and the memory will be freed.
virtual size_t numberOfChildren () const
Returns the number of immediate children of this node.
virtual size_t numberOfSpecies () const override
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t countSpecies () const override
Returns the number of Species being managed by this node and its descendent nodes.
virtual size_t numberOfReactions () const override
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual size_t countReactions () const override
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
virtual std::vector
< std::unique_ptr< Component > > & children ()
Returns a reference to the container of Component children of this node.
virtual const std::vector
< std::unique_ptr< Component > > & children () const
Returns a const reference to the container of Component children of this node.
virtual Component * children (size_t i)
Returns a pointer to the i-th Component child of this node.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionVisitor v to every ReactionBase* object directly owned by this node.
virtual bool apply_impl_if (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl_if (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node. The returned value could be a nullptr if a parent does not exist.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e. ReactionBase pointers)
virtual void printSelf ()
Prints information about this node. Useful for debugging.
Private Attributes
std::vector< std::unique_ptr
< Component > > _children
Child node pointers of this Composite node.
Detailed Description
Composite class is the aggregating class for the Composite pattern.
The Composite pattern allows building of complex hieararchical objects, with convenient methods for applying a function to all nodes (i.e. the Visitor pattern). Each node in the hieararchy may have a parent and may contain several children nodes. A class that is derived from Composite can contain children Component objects.
Note:
Composite objects may contain Species and ReactionBase collections, however, this is treated seperately from the Composite pattern (i.e. separate methods exist for the corresponding access to elements, changes, etc.)
Definition at line 37 of file Composite.h.
Constructor & Destructor Documentation
chem::Composite::Composite () [inline]
Default Constructor does nothing.
Definition at line 43 of file Composite.h.
virtual chem::Composite::~Composite () [inline, virtual]
Virtual Destructor does nothing.
Definition at line 46 of file Composite.h.
Member Function Documentation
virtual void chem::Composite::addChild (std::unique_ptr< Component > && child) [inline, virtual]
Adds a Component child to this Composite node.
Parameters:
child - is a std::unique_ptr<Component>, hence, this node takes the memory ownership of the corresponding child pointer.
Note:
the rvalue semantics - the std::unique_ptr<...> cannot be copied, but only can be moved
Definition at line 83 of file Composite.h.
References _children.
Referenced by chem::CompartmentsSimpleGrid< NDIM >::initialize().
bool Composite::apply (Visitor & v) [override, virtual]
Implements the apply() method of the Component class by recursively applying it to itself and all its children.
Reimplemented from chem::Component.
Definition at line 15 of file Composite.cpp.
References children(), and chem::Visitor::visit().
bool Composite::apply (SpeciesVisitor & v) [override, virtual]
Implements the apply() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented from chem::Component.
Definition at line 39 of file Composite.cpp.
References chem::Component::apply_impl(), and children().
bool Composite::apply (ReactionVisitor & v) [override, virtual]
When this function is applied to a ReactionVisitor sv, the corresponding v.visit(s) is called for each ReactionBase pointer *s owned by the node.
v is further applied to all children of this node recursively.
Reimplemented from chem::Component.
Definition at line 64 of file Composite.cpp.
References chem::Component::apply_impl(), and children().
bool Composite::apply_if (Visitor & v) [override, virtual]
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
Reimplemented from chem::Component.
Definition at line 27 of file Composite.cpp.
References children(), and chem::Visitor::visit_if().
bool Composite::apply_if (SpeciesVisitor & v) [override, virtual]
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented from chem::Component.
Definition at line 52 of file Composite.cpp.
References chem::Component::apply_impl_if(), and children().
bool Composite::apply_if (ReactionVisitor & v) [override, virtual]
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented from chem::Component.
Definition at line 77 of file Composite.cpp.
References chem::Component::apply_impl_if(), and children().
virtual bool chem::Component::apply_impl (SpeciesVisitor & v) [inline, virtual, inherited]
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in chem::Compartment.
Definition at line 60 of file Component.h.
Referenced by chem::Component::apply(), apply(), and chem::Component::apply_if().
virtual bool chem::Component::apply_impl (ReactionVisitor & v) [inline, virtual, inherited]
Applies ReactionVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in chem::Compartment.
Definition at line 76 of file Component.h.
virtual bool chem::Component::apply_impl_if (SpeciesVisitor & v) [inline, virtual, inherited]
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in chem::Compartment.
Definition at line 64 of file Component.h.
Referenced by apply_if().
virtual bool chem::Component::apply_impl_if (ReactionVisitor & v) [inline, virtual, inherited]
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in chem::Compartment.
Definition at line 80 of file Component.h.
virtual std::vector<std::unique_ptr<Component> >& chem::Composite::children () [inline, virtual]
Returns a reference to the container of Component children of this node.
Definition at line 136 of file Composite.h.
References _children.
Referenced by chem::CompartmentsSimpleGrid< NDIM >::addChemSimReactions(), apply(), apply_if(), countReactions(), countSpecies(), chem::CompartmentsSimpleGrid< NDIM >::getCompartment(), chem::CompartmentsSimpleGrid< NDIM >::initialize(), numberOfChildren(), and chem::CompartmentsSimpleGrid< NDIM >::printSelf().
virtual const std::vector<std::unique_ptr<Component> >& chem::Composite::children () const [inline, virtual]
Returns a const reference to the container of Component children of this node.
Definition at line 139 of file Composite.h.
References _children.
virtual Component* chem::Composite::children (size_t i) [inline, virtual]
Returns a pointer to the i-th Component child of this node.
Definition at line 142 of file Composite.h.
References _children.
virtual size_t chem::Composite::countReactions () const [inline, override, virtual]
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
Reimplemented from chem::Component.
Definition at line 126 of file Composite.h.
References children(), chem::Component::isReactionsContainer(), and numberOfReactions().
virtual size_t chem::Composite::countSpecies () const [inline, override, virtual]
Returns the number of Species being managed by this node and its descendent nodes.
Reimplemented from chem::Component.
Definition at line 112 of file Composite.h.
References children(), chem::Component::isSpeciesContainer(), and numberOfSpecies().
Referenced by main().
virtual std::string chem::Composite::getFullName () const [inline, override, virtual]
Returns the full name of this node.
Reimplemented from chem::Component.
Reimplemented in chem::CompartmentCubic< NDIM >, chem::Compartment, and chem::CompartmentsSimpleGrid< NDIM >.
Definition at line 77 of file Composite.h.
Composite* chem::Component::getParent () [inline, inherited]
Returns the pointer to the parent node. The returned value could be a nullptr if a parent does not exist.
Definition at line 83 of file Component.h.
References chem::Component::_parent.
Referenced by chem::Component::getRoot().
Composite * chem::Component::getRoot () [inherited]
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 17 of file Component.cpp.
References chem::Component::getParent(), chem::Component::getRoot(), and chem::Component::isRoot().
Referenced by chem::Component::getRoot(), chem::ReactionBase::getRoot(), and chem::Species::getRoot().
virtual bool chem::Composite::isComposite () const [inline, override, virtual]
Returns true.
Reimplemented from chem::Component.
Definition at line 74 of file Composite.h.
virtual bool chem::Component::isReactionsContainer () const [inline, virtual, inherited]
Returns true if this node contains non-zero number of reactions (i.e. ReactionBase pointers)
Reimplemented in chem::Compartment.
Definition at line 106 of file Component.h.
Referenced by countReactions().
bool chem::Component::isRoot () const [inline, inherited]
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 90 of file Component.h.
References chem::Component::_parent.
Referenced by chem::Component::getRoot().
virtual bool chem::Component::isSpeciesContainer () const [inline, virtual, inherited]
Returns true if this node contains non-zero number of Species.
Reimplemented in chem::Compartment.
Definition at line 103 of file Component.h.
Referenced by countSpecies().
virtual size_t chem::Composite::numberOfChildren () const [inline, virtual]
Returns the number of immediate children of this node.
Note:
Species and reactions and not included in this tally
Reimplemented from chem::Component.
Definition at line 105 of file Composite.h.
References children().
Referenced by chem::CompartmentsSimpleGrid< NDIM >::printSelf().
virtual size_t chem::Composite::numberOfReactions () const [inline, override, virtual]
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented from chem::Component.
Reimplemented in chem::Compartment.
Definition at line 123 of file Composite.h.
Referenced by countReactions().
virtual size_t chem::Composite::numberOfSpecies () const [inline, override, virtual]
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.
Reimplemented from chem::Component.
Reimplemented in chem::Compartment.
Definition at line 109 of file Composite.h.
Referenced by countSpecies().
virtual void chem::Component::printSelf () [inline, virtual, inherited]
Prints information about this node. Useful for debugging.
Reimplemented in chem::CompartmentCubic< NDIM >, chem::Compartment, and chem::CompartmentsSimpleGrid< NDIM >.
Definition at line 128 of file Component.h.
virtual void chem::Composite::removeChild (Component * child) [inline, virtual]
Remove *child from this node's children. The child's destructor will be called and the memory will be freed.
Definition at line 90 of file Composite.h.
References _children.
void chem::Component::setParent (Composite * other) [inline, inherited]
Sets the parent of this node to other.
Definition at line 86 of file Component.h.
References chem::Component::_parent.
Member Data Documentation
std::vector<std::unique_ptr<Component> > chem::Composite::_children [private]
Child node pointers of this Composite node.
Definition at line 39 of file Composite.h.
Referenced by addChild(), children(), and removeChild().
The documentation for this class was generated from the following files:
CytoSim/Composite.h
CytoSim/Composite.cpp