CytoSim: chem::SpeciesNamesDB Class Reference
chem::SpeciesNamesDB Class Reference
SpeciesNamesDB class is used to associate unique integers with character based names of Species.
#include <Species.h>
Public Member Functions
std::string intToString (unsigned int i) const
Given an integer "i", returns the std::string associated with that integer. Throws an out of range exception.
int stringToInt (std::string name)
Given a std::string "name", returns the unique integer associated with that string.
void clear ()
Clear the contents of the database.
Static Public Member Functions
static SpeciesNamesDB * Instance ()
returns the unique instance of the singleton, which can be used to access the names DB
Private Member Functions
SpeciesNamesDB ()
Private Attributes
std::unordered_map
< std::string, int > _map_string_int
std::vector< std::string > _vec_int_string
Static Private Attributes
static SpeciesNamesDB * _instance = 0
the singleton instance
Detailed Description
SpeciesNamesDB class is used to associate unique integers with character based names of Species.
Often Species of the same type, let's say "Arp2/3" can be found in different forms, for example in cytosol vs bound to a filament. The corresponding specific Species will be distinct, however, they will share the same name, as returned by Species::getName(). This, in turn, helps to match "Arp2/3" bound to filaments with diffusing "Arp2/3". SpeciesNamesDB associates a unique integer with Species of the same type (e.g. "Arp2/3", regardless whether it is bound or not), and provides conversion functions fron integer to std::string (SpeciesNamesDB::intToString(int i)) and vice versa (SpeciesNamesDB::stringToInt (std::string name)). class SpeciesNamesDB is a singleton, and should be used by first calling SpeciesNamesDB::Instance() method.
  int y = SpeciesNamesDB::Instance()->stringToInt("Arp2/3"); // let's say y=2
  std::string x = SpeciesNamesDB::Instance()->intToString(2); // then x should be "Arp2/3"
Definition at line 54 of file Species.h.
Constructor & Destructor Documentation
chem::SpeciesNamesDB::SpeciesNamesDB () [inline, private]
Definition at line 57 of file Species.h.
Referenced by Instance().
Member Function Documentation
void chem::SpeciesNamesDB::clear () [inline]
Clear the contents of the database.
Definition at line 86 of file Species.h.
References _map_string_int, and _vec_int_string.
SpeciesNamesDB * chem::SpeciesNamesDB::Instance () [static]
returns the unique instance of the singleton, which can be used to access the names DB
Definition at line 19 of file Species.cpp.
References _instance, and SpeciesNamesDB().
Referenced by chem::Species::getName(), and chem::Species::Species().
std::string chem::SpeciesNamesDB::intToString (unsigned int i) const [inline]
Given an integer "i", returns the std::string associated with that integer. Throws an out of range exception.
Definition at line 66 of file Species.h.
References _vec_int_string.
Referenced by chem::Species::getName().
int chem::SpeciesNamesDB::stringToInt (std::string name) [inline]
Given a std::string "name", returns the unique integer associated with that string.
If the string does not exist yet, it is created.
Definition at line 74 of file Species.h.
References _map_string_int, and _vec_int_string.
Referenced by chem::Species::Species().
Member Data Documentation
SpeciesNamesDB * chem::SpeciesNamesDB::_instance = 0 [static, private]
the singleton instance
Definition at line 56 of file Species.h.
Referenced by Instance().
std::unordered_map<std::string,int> chem::SpeciesNamesDB::_map_string_int [private]
Definition at line 59 of file Species.h.
Referenced by clear(), and stringToInt().
std::vector<std::string> chem::SpeciesNamesDB::_vec_int_string [private]
Definition at line 60 of file Species.h.
Referenced by clear(), intToString(), and stringToInt().
The documentation for this class was generated from the following files:
CytoSim/Species.h
CytoSim/Species.cpp