CytoSim: chem::Reaction< M, N > Class Template Reference
chem::Reaction< M, N > Class Template Reference
Reaction<M,N> class represents a concrete chemical reaction, such as A + B -> C, where M is the number of reactants and N is the number of products.
#include <Reaction.h>
Public Member Functions
Reaction (std::initializer_list< Species * > species, float rate=0.0)
The main constructor:
template<typename InputContainer >
Reaction (const InputContainer &species, float rate=0.0)
The main constructor:
Reaction (const Reaction &rb)
no copying (including all derived classes)
Reaction & operator= (Reaction &rb)
no assignment (including all derived classes)
virtual ~Reaction () noexcept
Destructor Tell Rspecies to remove this Reaction from its internal lists if reactions.
virtual RSpecies ** rspecies () override
Returns a pointer to the first element of std::array<RSpecies*, M+N> The type of the pointer is RSpecies**.
virtual std::vector
< ReactionBase * > getAffectedReactions () override
Return a list of reactions which rates would be affected if this reaction were to be executed.
ReactionBase * clone (const SpeciesPtrContainerVector &spcv)
Copy this reaction using SpeciesPtrContainerVector &spcv as a source of analogous Species.
void setRate (float rate)
Sets the ReactionBase rate to the parameter "rate".
void setRnode (RNode *rhs)
Sets the RNode pointer associated with this ReactionBase to rhs.
float getRate () const
Returns the rate associated with this ReactionBase.
RNode * getRnode () const
Returns a pointer to the RNode associated with this ReactionBase.
unsigned short getM () const
Returns the number of reactant RSpecies.
unsigned short getN () const
Returns the number of product RSpecies.
unsigned short size () const
Returns the total number of RSpecies.
Composite * getParent ()
Return the parent Composite object pointer, to which this Reaction belongs to.
void setParent (Composite *other)
Set the parent Composite object pointer to which this Reaction belongs to.
bool hasParent () const
Returns true if this Reaction has a parent Composite object to which it belongs to.
Composite * getRoot ()
Get the root parent (i.e. follow the pointers of parentage until the root node in the Composition hieararchy)
int getProductOfReactants () const
Computes the product of the copy number of all reactant RSpecies.
int getProductOfProducts () const
Computes the product of the copy number of all product RSpecies minus maxium allowed copy number.
bool isPassivated () const
Return true if the ReactionBase is currently passivated.
bool containsSpecies (Species *s) const
Returns true of this Reaction contains Species *s either as a reactant or a product.
bool isSignaling () const
Return true if this RSpecies emits signals on copy number change.
void startSignaling ()
Set the signaling behavior of this ReactionBase.
void stopSignaling ()
Destroy the signal associated with this ReactionBase; all associated slots will be destroyed.
boost::signals2::connection connect (std::function< void(ReactionBase *)> const &react_callback, int priority=5)
Connect the callback, react_callback to a signal corresponding to ReactionBase *r.
void emitSignal ()
Broadcasts signal indicating that the ReactionBase event has taken place This method is only called by the code which runs the chemical dynamics (i.e.
const std::vector
< ReactionBase * > & dependents ()
Return a const reference to the vector of dependent ReactionBases.
void makeStep ()
Fire the ReactionBase - make a single step, where reactant RSpecies copy numbers are decreased by one, and the product RSpecies copy numbers are increased by one.
float computePropensity () const
Compute the ReactionBase propensity that is needed by a Gillespie like algorithm: rate*reactant_1.getN()*reactant_2.getN()...
void passivateReaction ()
Usually is applied to ReactionBase objects with propensity of 0 (e.g.
void activateReactionUnconditional ()
Requests that ReactionBase objects that may affect this Reaction to start tracking it, which can be used to follow ReactionBase objects whose propensities change upong firing of some ReactionBase.
void activateReaction ()
Requests that Reaction objects that may affect this Reaction to start tracking it, which can be used to follow Reaction objects whose propensities change upong firing of some Reaction.
void printDependents ()
Print the ReactionBases that are affacted by this ReactionBase being fired.
void registerNewDependent (ReactionBase *r)
Request that the ReactionBase *r adds this ReactionBase to its list of dependents which it affects.
void unregisterDependent (ReactionBase *r)
Request that the ReactionBase *r removes this ReactionBase from its list of dependents which it affects.
Protected Member Functions
template<typename InputContainer >
void initializeSpecies (const InputContainer &species)
An implementation method used by the constructor.
virtual unsigned short getMImpl () const override
Implementation of getM()
virtual unsigned short getNImpl () const override
Implementation of getN()
virtual unsigned short sizeImpl () const override
Implementation of size()
virtual bool is_equal (const ReactionBase &other) const override
Implementation of the operator==(...)
virtual int getProductOfReactantsImpl () const override
Implementation of getProductOfReactants()
virtual float computePropensityImpl () const override
Implementation of computePropensity()
virtual int getProductOfProductsImpl () const override
Implementation of getProductOfProducts()
virtual bool containsSpeciesImpl (Species *s) const override
Implementation of containsSpecies()
virtual void makeStepImpl () override
Implementation of makeStep()
virtual void activateReactionUnconditionalImpl () override
Implementation of activateReactionUnconditional()
virtual void passivateReactionImpl () override
Implementation of passivateReaction()
virtual void printToStream (std::ostream &os) const override
Print information about this reaction to std::ostream.
virtual void broadcastRSpeciesSignals ()
This method may be called after a makeStep() took place.
virtual Reaction< M, N > * cloneImpl (const SpeciesPtrContainerVector &spcv) override
Implementation of clone()
template<>
float computePropensityImpl () const
(Private) implementation of the computePropensity() method to be elaborated in derived classes.
template<>
void makeStepImpl ()
(Private) implementation of the makeStep() method to be elaborated in derived classes.
template<>
void broadcastRSpeciesSignals ()
Protected Attributes
std::vector< ReactionBase * > _dependents
Pointers to ReactionBase objects that depend on this ReactionBase being executed.
RNode * _rnode
A pointer to an RNode object which is used to implement a Gillespie-like algorithm (e.g. NRM)
Composite * _parent
A pointer to a Composite object to which this Reaction belongs.
float _rate
the rate for this ReactionBase
ReactionEventSignal * _signal
Can be used to broadcast a signal associated with this ReactionBase (usuall when a single step of this ReactionBase occurs)
bool _passivated
Indicates whether the ReactionBase is currently passivated.
Private Attributes
std::array< RSpecies *, M+N > _rspecies
An array of RSpecies objects (reactants followed by products)
Friends
bool operator== (const ReactionBase &a, const ReactionBase &b)
Returns true if two ReactionBase objects are equal.
bool operator!= (const ReactionBase &a, const ReactionBase &b)
Return true if two ReactionBase are not equal.
std::ostream & operator<< (std::ostream &os, const ReactionBase &rr)
Print self into an iostream.
Detailed Description
template<unsigned short M, unsigned short N>
class chem::Reaction< M, N >
Reaction<M,N> class represents a concrete chemical reaction, such as A + B -> C, where M is the number of reactants and N is the number of products.
Reaction<M,N> encodes a chemical reaction between M reactants and N products. It follows the ReactionBase interface, where many methods are defined. Most of the methods defined in Reaction<M,N> are specific implementations of virtual functions declared in ReactionBase. Hence, to a very large degree, Reaction<M,N> is an implementation class, while ReactionBase provides the public interface for reaction objects. The documentation of the latter should be mainly consulted when working with reactions.
Definition at line 25 of file Reaction.h.
Constructor & Destructor Documentation
template<unsigned short M, unsigned short N> chem::Reaction< M, N >::Reaction (std::initializer_list< Species * > species, float rate = 0.0) [inline]
The main constructor:
Parameters:
species - are reactants and products put together into a single list (starting from reactants)
rate - the rate constant for this ReactionBase
Definition at line 32 of file Reaction.h.
References chem::Reaction< M, N >::initializeSpecies().
template<unsigned short M, unsigned short N> template<typename InputContainer > chem::Reaction< M, N >::Reaction (const InputContainer & species, float rate = 0.0) [inline]
The main constructor:
Parameters:
it_begin - an iterator to the beginning of an RSpecies* container
it_end - an iterator to the end of an RSpecies* container
rate - the rate constant for this ReactionBase
Definition at line 43 of file Reaction.h.
References chem::Reaction< M, N >::initializeSpecies().
template<unsigned short M, unsigned short N> chem::Reaction< M, N >::Reaction (const Reaction< M, N > & rb)
no copying (including all derived classes)
template<unsigned short M, unsigned short N> virtual chem::Reaction< M, N >::~Reaction () [inline, virtual]
Destructor Tell Rspecies to remove this Reaction from its internal lists if reactions.
Definition at line 63 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies.
Member Function Documentation
void chem::ReactionBase::activateReaction () [inline, inherited]
Requests that Reaction objects that may affect this Reaction to start tracking it, which can be used to follow Reaction objects whose propensities change upong firing of some Reaction.
This request will be ignored if the Reaction's propensity is still zero.
Definition at line 276 of file ReactionBase.h.
References chem::ReactionBase::activateReactionUnconditional(), chem::ReactionBase::getProductOfProducts(), and chem::ReactionBase::getProductOfReactants().
void chem::ReactionBase::activateReactionUnconditional () [inline, inherited]
Requests that ReactionBase objects that may affect this Reaction to start tracking it, which can be used to follow ReactionBase objects whose propensities change upong firing of some ReactionBase.
This request is acted upond unconditionally.
Definition at line 269 of file ReactionBase.h.
References chem::ReactionBase::activateReactionUnconditionalImpl().
Referenced by chem::ReactionBase::activateReaction().
template<unsigned short M, unsigned short N> template void chem::Reaction< M, N >::activateReactionUnconditionalImpl () [override, protected, virtual]
Implementation of activateReactionUnconditional()
Implements chem::ReactionBase.
Definition at line 24 of file Reaction.cpp.
References chem::RSpecies::beginProductReactions(), chem::RSpecies::beginReactantReactions(), chem::RSpecies::endProductReactions(), and chem::RSpecies::endReactantReactions().
template<unsigned short M, unsigned short N> virtual void chem::Reaction< M, N >::broadcastRSpeciesSignals () [inline, protected, virtual]
This method may be called after a makeStep() took place.
It iterates over all reactants and products, and call the emitSignal(delta) of the corresponding RSpecies objects, where delta=-1 for reactants and delta=+1 for products.
Implements chem::ReactionBase.
Definition at line 225 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies, chem::ReactionBase::emitSignal(), and chem::ReactionBase::isSignaling().
template<> void chem::Reaction< 1, 1 >::broadcastRSpeciesSignals () [inline, protected, virtual]
Implements chem::ReactionBase.
Definition at line 276 of file Reaction.h.
ReactionBase* chem::ReactionBase::clone (const SpeciesPtrContainerVector & spcv) [inline, inherited]
Copy this reaction using SpeciesPtrContainerVector &spcv as a source of analogous Species.
Returns:
the cloned ReactionBase pointer.
Note:
the receving object should take care of the memory management of the returned pointer
Definition at line 91 of file ReactionBase.h.
References chem::ReactionBase::cloneImpl().
template<unsigned short M, unsigned short N> template Reaction< 2, 2 > * chem::Reaction< M, N >::cloneImpl (const SpeciesPtrContainerVector & spcv) [override, protected, virtual]
Implementation of clone()
Implements chem::ReactionBase.
Definition at line 66 of file Reaction.cpp.
References chem::SpeciesPtrContainerVector::species().
float chem::ReactionBase::computePropensity () const [inline, inherited]
Compute the ReactionBase propensity that is needed by a Gillespie like algorithm: rate*reactant_1.getN()*reactant_2.getN()...
Definition at line 252 of file ReactionBase.h.
References chem::ReactionBase::computePropensityImpl().
Referenced by chem::ChemSimpleGillespieImpl::makeStep(), chem::Reaction< M, N >::printToStream(), chem::RNodeGillespie::reComputePropensity(), chem::RNodeNRM::reComputePropensity(), chem::RNodeGillespie::reset(), and chem::RNodeNRM::RNodeNRM().
template<unsigned short M, unsigned short N> virtual float chem::Reaction< M, N >::computePropensityImpl () const [inline, override, protected, virtual]
Implementation of computePropensity()
Implements chem::ReactionBase.
Definition at line 141 of file Reaction.h.
References chem::ReactionBase::_rate, and chem::Reaction< M, N >::getProductOfReactantsImpl().
template<> float chem::Reaction< 1, 1 >::computePropensityImpl () const [inline, protected, virtual]
(Private) implementation of the computePropensity() method to be elaborated in derived classes.
Implements chem::ReactionBase.
Definition at line 254 of file Reaction.h.
boost::signals2::connection chem::ReactionBase::connect (std::function< void(ReactionBase *)> const & react_callback, int priority = 5) [inherited]
Connect the callback, react_callback to a signal corresponding to ReactionBase *r.
Parameters:
std::function<void (ReactionBase *)> const &react_callback - a function object to be called (a slot)
int priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Returns:
a connection object which can be used to later disconnect this particular slot or temporarily block it
Definition at line 58 of file ReactionBase.cpp.
References chem::ReactionBase::_signal, chem::ReactionBase::isSignaling(), and chem::ReactionBase::startSignaling().
bool chem::ReactionBase::containsSpecies (Species * s) const [inline, inherited]
Returns true of this Reaction contains Species *s either as a reactant or a product.
Definition at line 181 of file ReactionBase.h.
References chem::ReactionBase::containsSpeciesImpl().
template<unsigned short M, unsigned short N> virtual bool chem::Reaction< M, N >::containsSpeciesImpl (Species * s) const [inline, override, protected, virtual]
Implementation of containsSpecies()
Implements chem::ReactionBase.
Definition at line 173 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies.
const std::vector<ReactionBase*>& chem::ReactionBase::dependents () [inline, inherited]
Return a const reference to the vector of dependent ReactionBases.
Note:
One can obtain two different lists of affected ReactionBases: 1) via getAffectedReactionBases(), where the copy numbers do influence the dependencies, and 2) via dependents(), where dependencies stop being counted if the copy numbers of reactant species drop to 0.
Definition at line 221 of file ReactionBase.h.
References chem::ReactionBase::_dependents.
Referenced by chem::ChemGillespieImpl::makeStep(), chem::ChemNRMImpl::makeStep(), chem::RNodeGillespie::printDependents(), and chem::RNodeNRM::printDependents().
void chem::ReactionBase::emitSignal () [inline, inherited]
Broadcasts signal indicating that the ReactionBase event has taken place This method is only called by the code which runs the chemical dynamics (i.e.
Gillespie-like algorithm)
Definition at line 206 of file ReactionBase.h.
References chem::ReactionBase::isSignaling().
Referenced by chem::Reaction< M, N >::broadcastRSpeciesSignals(), chem::ChemSimpleGillespieImpl::makeStep(), chem::ChemGillespieImpl::makeStep(), and chem::ChemNRMImpl::makeStep().
template<unsigned short M, unsigned short N> virtual std::vector<ReactionBase*> chem::Reaction< M, N >::getAffectedReactions () [inline, override, virtual]
Return a list of reactions which rates would be affected if this reaction were to be executed.
Implements chem::ReactionBase.
Definition at line 79 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies.
Referenced by chem::Reaction< M, N >::initializeSpecies().
unsigned short chem::ReactionBase::getM () const [inline, inherited]
Returns the number of reactant RSpecies.
Definition at line 117 of file ReactionBase.h.
References chem::ReactionBase::getMImpl().
template<unsigned short M, unsigned short N> virtual unsigned short chem::Reaction< M, N >::getMImpl () const [inline, override, protected, virtual]
Implementation of getM()
Implements chem::ReactionBase.
Definition at line 110 of file Reaction.h.
unsigned short chem::ReactionBase::getN () const [inline, inherited]
Returns the number of product RSpecies.
Definition at line 123 of file ReactionBase.h.
References chem::ReactionBase::getNImpl().
Referenced by chem::Reaction< M, N >::getProductOfReactantsImpl().
template<unsigned short M, unsigned short N> virtual unsigned short chem::Reaction< M, N >::getNImpl () const [inline, override, protected, virtual]
Implementation of getN()
Implements chem::ReactionBase.
Definition at line 113 of file Reaction.h.
Composite* chem::ReactionBase::getParent () [inline, inherited]
Return the parent Composite object pointer, to which this Reaction belongs to.
If not present, return a nullptr.
Definition at line 136 of file ReactionBase.h.
References chem::ReactionBase::_parent.
Referenced by chem::ReactionBase::getRoot().
int chem::ReactionBase::getProductOfProducts () const [inline, inherited]
Computes the product of the copy number of all product RSpecies minus maxium allowed copy number.
Can be used to quickly determine whether this ReactionBase should be allowed to activate - if one of the products has a copy number equal to the maximum allowed, then zero is returned, indicating that this ReactionBase should not be (yet) activated.
Definition at line 168 of file ReactionBase.h.
References chem::ReactionBase::getProductOfProductsImpl().
Referenced by chem::ReactionBase::activateReaction().
template<unsigned short M, unsigned short N> virtual int chem::Reaction< M, N >::getProductOfProductsImpl () const [inline, override, protected, virtual]
Implementation of getProductOfProducts()
Implements chem::ReactionBase.
Definition at line 158 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies.
int chem::ReactionBase::getProductOfReactants () const [inline, inherited]
Computes the product of the copy number of all reactant RSpecies.
Can be used to quickly determine whether this ReactionBase should be allowed to activate - if one of the reactants has a copy number equal to zero, then zero is returned, indicating that this ReactionBase should not be (yet) activated.
Definition at line 159 of file ReactionBase.h.
References chem::ReactionBase::getProductOfReactantsImpl().
Referenced by chem::ReactionBase::activateReaction(), and chem::RNodeNRM::getProductOfReactants().
template<unsigned short M, unsigned short N> virtual int chem::Reaction< M, N >::getProductOfReactantsImpl () const [inline, override, protected, virtual]
Implementation of getProductOfReactants()
Implements chem::ReactionBase.
Definition at line 131 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies, and chem::ReactionBase::getN().
Referenced by chem::Reaction< M, N >::computePropensityImpl().
float chem::ReactionBase::getRate () const [inline, inherited]
Returns the rate associated with this ReactionBase.
Definition at line 111 of file ReactionBase.h.
References chem::ReactionBase::_rate.
Referenced by chem::Reaction< M, N >::printToStream().
RNode* chem::ReactionBase::getRnode () const [inline, inherited]
Returns a pointer to the RNode associated with this ReactionBase.
Definition at line 114 of file ReactionBase.h.
References chem::ReactionBase::_rnode.
Composite * chem::ReactionBase::getRoot () [inherited]
Get the root parent (i.e. follow the pointers of parentage until the root node in the Composition hieararchy)
Definition at line 27 of file ReactionBase.cpp.
References chem::ReactionBase::getParent(), chem::Component::getRoot(), and chem::ReactionBase::hasParent().
bool chem::ReactionBase::hasParent () const [inline, inherited]
Returns true if this Reaction has a parent Composite object to which it belongs to.
Definition at line 142 of file ReactionBase.h.
References chem::ReactionBase::_parent.
Referenced by chem::ReactionBase::getRoot().
template<unsigned short M, unsigned short N> template<typename InputContainer > void chem::Reaction< M, N >::initializeSpecies (const InputContainer & species) [inline, protected]
An implementation method used by the constructor.
Definition at line 95 of file Reaction.h.
References chem::ReactionBase::_dependents, chem::Reaction< M, N >::_rspecies, and chem::Reaction< M, N >::getAffectedReactions().
Referenced by chem::Reaction< M, N >::Reaction().
template<unsigned short M, unsigned short N> virtual bool chem::Reaction< M, N >::is_equal (const ReactionBase & other) const [inline, override, protected, virtual]
Implementation of the operator==(...)
Implements chem::ReactionBase.
Definition at line 119 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies, and chem::RSpecies::getSpecies().
bool chem::ReactionBase::isPassivated () const [inline, inherited]
Return true if the ReactionBase is currently passivated.
Definition at line 175 of file ReactionBase.h.
References chem::ReactionBase::_passivated.
Referenced by chem::RNodeGillespie::isPassivated(), and chem::RNodeNRM::isPassivated().
bool chem::ReactionBase::isSignaling () const [inline, inherited]
Return true if this RSpecies emits signals on copy number change.
Definition at line 188 of file ReactionBase.h.
References chem::ReactionBase::_signal.
Referenced by chem::Reaction< M, N >::broadcastRSpeciesSignals(), chem::ReactionBase::connect(), and chem::ReactionBase::emitSignal().
void chem::ReactionBase::makeStep () [inline, inherited]
Fire the ReactionBase - make a single step, where reactant RSpecies copy numbers are decreased by one, and the product RSpecies copy numbers are increased by one.
Note:
This method does not send a ReactionBase event Signal. The latter is usually done from within a Gillespie-like algorithm.
Definition at line 245 of file ReactionBase.h.
References chem::ReactionBase::makeStepImpl().
Referenced by chem::RNodeGillespie::makeStep(), chem::ChemSimpleGillespieImpl::makeStep(), and chem::RNodeNRM::makeStep().
template<unsigned short M, unsigned short N> virtual void chem::Reaction< M, N >::makeStepImpl () [inline, override, protected, virtual]
Implementation of makeStep()
Implements chem::ReactionBase.
Definition at line 182 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies.
template<> void chem::Reaction< 1, 1 >::makeStepImpl () [inline, protected, virtual]
(Private) implementation of the makeStep() method to be elaborated in derived classes.
Implements chem::ReactionBase.
Definition at line 267 of file Reaction.h.
template<unsigned short M, unsigned short N> Reaction& chem::Reaction< M, N >::operator= (Reaction< M, N > & rb)
no assignment (including all derived classes)
void chem::ReactionBase::passivateReaction () [inline, inherited]
Usually is applied to ReactionBase objects with propensity of 0 (e.g.
when one of the copy numbers of reactants has dropped to 0. This method call notifies all other ReactionBase objects that may affect this ReactionBase to stop tracking this ReactionBase. Eventually, activateReaction() may be called to restart tracking, if the propensity stops being 0.
Definition at line 261 of file ReactionBase.h.
References chem::ReactionBase::passivateReactionImpl().
template<unsigned short M, unsigned short N> template void chem::Reaction< M, N >::passivateReactionImpl () [override, protected, virtual]
Implementation of passivateReaction()
Implements chem::ReactionBase.
Definition at line 45 of file Reaction.cpp.
References chem::RSpecies::beginProductReactions(), chem::RSpecies::beginReactantReactions(), chem::RSpecies::endProductReactions(), and chem::RSpecies::endReactantReactions().
void chem::ReactionBase::printDependents () [inherited]
Print the ReactionBases that are affacted by this ReactionBase being fired.
Definition at line 65 of file ReactionBase.cpp.
References chem::ReactionBase::_dependents.
template<unsigned short M, unsigned short N> virtual void chem::Reaction< M, N >::printToStream (std::ostream & os) const [inline, override, protected, virtual]
Print information about this reaction to std::ostream.
Implements chem::ReactionBase.
Definition at line 197 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies, chem::ReactionBase::computePropensity(), and chem::ReactionBase::getRate().
void chem::ReactionBase::registerNewDependent (ReactionBase * r) [inherited]
Request that the ReactionBase *r adds this ReactionBase to its list of dependents which it affects.
Definition at line 35 of file ReactionBase.cpp.
References chem::ReactionBase::_dependents.
template<unsigned short M, unsigned short N> virtual RSpecies** chem::Reaction< M, N >::rspecies () [inline, override, virtual]
Returns a pointer to the first element of std::array<RSpecies*, M+N> The type of the pointer is RSpecies**.
In conjunction with getM() and getN(), this pointer can be used to iterate over RSpecies associated with this reaction.
Implements chem::ReactionBase.
Definition at line 75 of file Reaction.h.
References chem::Reaction< M, N >::_rspecies.
void chem::ReactionBase::setParent (Composite * other) [inline, inherited]
Set the parent Composite object pointer to which this Reaction belongs to.
Definition at line 139 of file ReactionBase.h.
References chem::ReactionBase::_parent.
Referenced by chem::Compartment::addDiffusionReaction(), chem::Compartment::addDiffusionReactionUnique(), chem::Compartment::addInternal(), chem::Compartment::addInternalReaction(), and chem::Compartment::addInternalReactionUnique().
void chem::ReactionBase::setRate (float rate) [inline, inherited]
Sets the ReactionBase rate to the parameter "rate".
Definition at line 104 of file ReactionBase.h.
References chem::ReactionBase::_rate.
void chem::ReactionBase::setRnode (RNode * rhs) [inline, inherited]
Sets the RNode pointer associated with this ReactionBase to rhs.
Usually is called only by the Gillespie-like algorithms.
Definition at line 108 of file ReactionBase.h.
References chem::ReactionBase::_rnode.
Referenced by chem::RNodeGillespie::RNodeGillespie(), chem::RNodeNRM::RNodeNRM(), chem::RNodeGillespie::~RNodeGillespie(), and chem::RNodeNRM::~RNodeNRM().
unsigned short chem::ReactionBase::size () const [inline, inherited]
Returns the total number of RSpecies.
Definition at line 129 of file ReactionBase.h.
References chem::ReactionBase::sizeImpl().
template<unsigned short M, unsigned short N> virtual unsigned short chem::Reaction< M, N >::sizeImpl () const [inline, override, protected, virtual]
Implementation of size()
Implements chem::ReactionBase.
Definition at line 116 of file Reaction.h.
void chem::ReactionBase::startSignaling () [inherited]
Set the signaling behavior of this ReactionBase.
Definition at line 48 of file ReactionBase.cpp.
References chem::ReactionBase::_signal.
Referenced by chem::ReactionBase::connect().
void chem::ReactionBase::stopSignaling () [inherited]
Destroy the signal associated with this ReactionBase; all associated slots will be destroyed.
Note:
To start signaling again, startSignaling() needs to be called
Definition at line 52 of file ReactionBase.cpp.
References chem::ReactionBase::_signal.
void chem::ReactionBase::unregisterDependent (ReactionBase * r) [inherited]
Request that the ReactionBase *r removes this ReactionBase from its list of dependents which it affects.
This is usually requested when the ReactionBase propensity drops to zero (i.e. via passivateReactionBase()).
Definition at line 40 of file ReactionBase.cpp.
References chem::ReactionBase::_dependents.
Friends And Related Function Documentation
bool operator!= (const ReactionBase & a, const ReactionBase & b) [friend, inherited]
Return true if two ReactionBase are not equal.
See also:
operator ==(const ReactionBase& a, const ReactionBase& b) above
Definition at line 237 of file ReactionBase.h.
std::ostream& operator<< (std::ostream & os, const ReactionBase & rr) [friend, inherited]
Print self into an iostream.
Definition at line 307 of file ReactionBase.h.
bool operator== (const ReactionBase & a, const ReactionBase & b) [friend, inherited]
Returns true if two ReactionBase objects are equal.
Two ReactionBase objects are equal if each of their reactants and products are equal
Definition at line 225 of file ReactionBase.h.
Member Data Documentation
std::vector<ReactionBase*> chem::ReactionBase::_dependents [protected, inherited]
Pointers to ReactionBase objects that depend on this ReactionBase being executed.
Definition at line 57 of file ReactionBase.h.
Referenced by chem::ReactionBase::dependents(), chem::Reaction< M, N >::initializeSpecies(), chem::ReactionBase::printDependents(), chem::ReactionBase::registerNewDependent(), and chem::ReactionBase::unregisterDependent().
Composite* chem::ReactionBase::_parent [protected, inherited]
A pointer to a Composite object to which this Reaction belongs.
Definition at line 59 of file ReactionBase.h.
Referenced by chem::ReactionBase::getParent(), chem::ReactionBase::hasParent(), and chem::ReactionBase::setParent().
bool chem::ReactionBase::_passivated [protected, inherited]
Indicates whether the ReactionBase is currently passivated.
Definition at line 65 of file ReactionBase.h.
Referenced by chem::ReactionBase::isPassivated(), and chem::ReactionBase::ReactionBase().
float chem::ReactionBase::_rate [protected, inherited]
the rate for this ReactionBase
Definition at line 60 of file ReactionBase.h.
Referenced by chem::Reaction< M, N >::computePropensityImpl(), chem::ReactionBase::getRate(), and chem::ReactionBase::setRate().
RNode* chem::ReactionBase::_rnode [protected, inherited]
A pointer to an RNode object which is used to implement a Gillespie-like algorithm (e.g. NRM)
Definition at line 58 of file ReactionBase.h.
Referenced by chem::ReactionBase::getRnode(), and chem::ReactionBase::setRnode().
template<unsigned short M, unsigned short N> std::array<RSpecies*, M+N> chem::Reaction< M, N >::_rspecies [private]
An array of RSpecies objects (reactants followed by products)
Definition at line 27 of file Reaction.h.
Referenced by chem::Reaction< M, N >::broadcastRSpeciesSignals(), chem::Reaction< M, N >::containsSpeciesImpl(), chem::Reaction< M, N >::getAffectedReactions(), chem::Reaction< M, N >::getProductOfProductsImpl(), chem::Reaction< M, N >::getProductOfReactantsImpl(), chem::Reaction< M, N >::initializeSpecies(), chem::Reaction< M, N >::is_equal(), chem::Reaction< M, N >::makeStepImpl(), chem::Reaction< M, N >::printToStream(), chem::Reaction< M, N >::rspecies(), and chem::Reaction< M, N >::~Reaction().
ReactionEventSignal* chem::ReactionBase::_signal [protected, inherited]
Can be used to broadcast a signal associated with this ReactionBase (usuall when a single step of this ReactionBase occurs)
Definition at line 62 of file ReactionBase.h.
Referenced by chem::ReactionBase::connect(), chem::ReactionBase::isSignaling(), chem::ReactionBase::ReactionBase(), chem::ReactionBase::startSignaling(), chem::ReactionBase::stopSignaling(), and chem::ReactionBase::~ReactionBase().
The documentation for this class was generated from the following files:
CytoSim/Reaction.h
CytoSim/Reaction.cpp