CytoSim: Chemistry
Chemistry
Classes
class SpeciesType
SpeciesType class represents the type of chemical Species (for example, a Species with name "Arp2/3" and SType Diffusing)
class Species
Species class represents chemical molecules, tracks their copy number and can be used in Reactions.
class SpeciesContainer
Typedefs
typedef std::vector< Reaction * >
::iterator vr_iterator
typedef std::vector< Species * >
::iterator vsp_iterator
typedef std::unordered_map
< std::string, std::unique_ptr
< Species > > map_str_species
Enumerations
enum SType {
Bulk = 0, Diffusing = 1, Membrane = 2, Filament = 3,
Walking = 4, Motors = 5
}
Functions
SpeciesType::SpeciesType (const std::string &name, SType type)
Given a species name as a string and its SType, constructs the SpeciesType.
SpeciesType::SpeciesType (const SpeciesType &st)
Given a species name as a string and its type as a string, constructs the SpeciesType.
SpeciesType::SpeciesType (SpeciesType &&st)
The move constructor. May be needed for boost::flyweight?
SpeciesType & SpeciesType::operator= (const SpeciesType &st)
SpeciesType & SpeciesType::operator= (SpeciesType &&st)
Assignment operators copies all fields. May be needed for boost::flyweight?
bool SpeciesType::operator== (const SpeciesType &species_type) const
Equality operator use both species name and type to compare to SpeciesType objects.
std::string SpeciesType::getName () const
Returns the name associated with this SpeciesType as a string.
SType SpeciesType::getType () const
Returns the SType associated with this SpeciesType.
std::string SpeciesType::getTypeAsString () const
Returns a string representing this SpeciesType by concatanating its name and type.
bool SpeciesType::is_of_type (const std::string &name, SType type) const
Return if true if this SpeciesType has name and SType given as parameters to this function.
void Species::up ()
Increases the copy number by 1.
void Species::down ()
Decreases the copy number by 1.
void Species::addAsReactant (Reaction *r)
void Species::addAsProduct (Reaction *r)
void Species::removeAsReactant (const Reaction *r)
void Species::removeAsProduct (const Reaction *r)
void Species::activateAssocReactions ()
void Species::passivateAssocReacts ()
Species::Species (const SpeciesType &type, species_copy_t n=0, bool is_signaling=false)
Constructors.
Species::Species (const std::string &name, SType type, species_copy_t n=0, bool is_signaling=false)
Species::Species (const Species &r)
deleted copy constructor and assignment operators - each Species is unique
Species & Species::operator= (Species &)
Species::~Species ()
It is required that all Reactions associated with this Species are destructed before this Species is destructed.
std::unique_ptr< Species > Species::clone ()
Cloning constructs completely new Species enveloped in a unique_ptr.
void Species::setN (species_copy_t n)
Setters & Mutators Sets the copy number for this Species.
species_copy_t Species::getN () const
Return the current copy number of this Species.
flyweight< SpeciesType > Species::getType () const
Return SpeciesType associated with this Species.
std::string Species::getFullName () const
Return the full name of this Species in a std::string format (e.g. "Arp2/3{Bulk}".
bool Species::isSignaling () const
Return true if this Species emits signals on copy number change.
void Species::makeSignaling (SignalingManager &sm)
Set the signaling behavior of this Species.
void Species::stopSignaling (SignalingManager &sm)
Destroy the signal associated with this Species.
std::vector< Reaction * > Species::ReactantReactions ()
Return std::vector<Reaction *>, which contains pointers to all Reactions where this Species is involved as a Reactant.
std::vector< Reaction * > Species::ProductReactions ()
Return std::vector<Reaction *>, which contains pointers to all Reactions where this Species is involved as a Product.
vr_iterator Species::beginReactantReactions ()
Return std::vector<Reaction *>::iterator, which points to the beginning of all Reactions where this Species is involved as a Reactant.
vr_iterator Species::beginProductReactions ()
Return std::vector<Reaction *>::iterator, which points to the beginning of all Reactions where this Species is involved as a Product.
vr_iterator Species::endReactantReactions ()
Return std::vector<Reaction *>::iterator, which points to the end of all Reactions where this Species is involved as a Reactant.
vr_iterator Species::endProductReactions ()
Return std::vector<Reaction *>::iterator, which points to the end of all Reactions where this Species is involved as a Product.
bool Species::is_of_species_type (const std::string &name, SType type) const
A helper function which determines whether parameter std:string name corresponds the SpeciesType associated with this Species.
void Species::printSelf () const
Prints some helpful information about this Species.
SpeciesContainer::SpeciesContainer ()
SpeciesContainer::SpeciesContainer (const SpeciesContainer &)
SpeciesContainer & SpeciesContainer::operator= (SpeciesContainer &)
void SpeciesContainer::addSpecies (const std::string &unq_key, const std::string &name, SType type, species_copy_t N)
Species * SpeciesContainer::getSpecies (const std::string &unq_key)
Variables
std::string SpeciesType::_name
the descriptive name associated with this Species
SType SpeciesType::_type
the type of species, such as Bulk, Diffusing, etc.
static std::vector< std::string > SpeciesType::_vec_type_name = {"Bulk", "Diffusing", "Membrane", "Filament", "Walking", "Motors" }
this variable is used to help translate strings to enum values for the SType
std::vector< Reaction * > Species::_as_reactants
a vector of Reactions where this Species is a Reactant
std::vector< Reaction * > Species::_as_products
a vector of Reactions where this Species is a Product
flyweight< SpeciesType > Species::_type
This Species' type.
species_copy_t Species::_n
Current copy number of this Species.
bool Species::_is_signaling
If true, indicates a signal may be sent when a copy number of this Reaction changes.
map_str_species SpeciesContainer::_map_species
Friends
class Species::Reaction
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
std::size_t SpeciesType::hash_value (SpeciesType const &species_type)
boost::flyweight needs a hashing function, defined here.
Typedef Documentation
typedef std::unordered_map<std::string,std::unique_ptr<Species> > map_str_species
Definition at line 287 of file Species.h.
typedef std::vector<Reaction*>::iterator vr_iterator
Definition at line 42 of file Species.h.
typedef std::vector<Species*>::iterator vsp_iterator
Definition at line 45 of file Species.h.
Enumeration Type Documentation
enum SType
Enumerator:
Bulk
Species that have no spatial association (i.e. are "well-mixed")
Diffusing
Species that diffuse between cytosolic compartments.
Membrane
Species that diffuse within a membrane.
Filament
Species that comprise filaments (such as F-Actin)
Walking
Species that can walk ("convectively") on filaments (like Myosin X)
Motors
Species that bind to filaments and generate forces (like Myosin II)
Definition at line 47 of file Species.h.
Function Documentation
Species::Species (const SpeciesType & type, species_copy_t n = 0, bool is_signaling = false) [inline]
Constructors.
Parameters:
type - is SpeciesType associated for this Species.
n - copy number
Definition at line 201 of file Species.h.
Species::Species (const std::string & name, SType type, species_copy_t n = 0, bool is_signaling = false) [inline]
Parameters:
name - a string for the Species name associated with this Species. For example, "G-Actin" or "Arp2/3"
n - copy number
Definition at line 206 of file Species.h.
Species::Species (const Species & r)
deleted copy constructor and assignment operators - each Species is unique
SpeciesContainer::SpeciesContainer ()
SpeciesContainer::SpeciesContainer (const SpeciesContainer &)
SpeciesType::SpeciesType (const std::string & name, SType type) [inline]
Given a species name as a string and its SType, constructs the SpeciesType.
Definition at line 73 of file Species.h.
SpeciesType::SpeciesType (const SpeciesType & st) [inline]
Given a species name as a string and its type as a string, constructs the SpeciesType.
Definition at line 76 of file Species.h.
SpeciesType::SpeciesType (SpeciesType && st) [inline]
The move constructor. May be needed for boost::flyweight?
Definition at line 79 of file Species.h.
Species::~Species () [inline]
It is required that all Reactions associated with this Species are destructed before this Species is destructed.
Most of the time, this will occur naturally. If not, a an assertion will ungracefully terminate the program.
Definition at line 215 of file Species.h.
void Species::activateAssocReactions () [private]
Attempts to activate previously passivated Reactions where this Species is involved as a Reactant. Usually, the Reaction was first passivated, for example if the Species copy number of one of the reactants dropeed to zero. This attempt may not succeed if there are still other reactants in the same Reaction with zero copy count.
Definition at line 17 of file Species.cpp.
References Species::_as_reactants.
void Species::addAsProduct (Reaction * r) [inline, private]
Definition at line 167 of file Species.h.
Referenced by Reaction::Reaction().
void Species::addAsReactant (Reaction * r) [inline, private]
Definition at line 163 of file Species.h.
Referenced by Reaction::Reaction().
void SpeciesContainer::addSpecies (const std::string & unq_key, const std::string & name, SType type, species_copy_t N) [inline]
Definition at line 294 of file Species.h.
Referenced by main().
vr_iterator Species::beginProductReactions () [inline]
Return std::vector<Reaction *>::iterator, which points to the beginning of all Reactions where this Species is involved as a Product.
Definition at line 263 of file Species.h.
vr_iterator Species::beginReactantReactions () [inline]
Return std::vector<Reaction *>::iterator, which points to the beginning of all Reactions where this Species is involved as a Reactant.
Definition at line 259 of file Species.h.
Referenced by main().
std::unique_ptr<Species> Species::clone () [inline]
Cloning constructs completely new Species enveloped in a unique_ptr.
Definition at line 220 of file Species.h.
void Species::down () [inline, private]
Decreases the copy number by 1.
If the copy number changes becomes 0, calls a "callback"-like method to passivate Reactions, where this Species is a Reactant.
Definition at line 155 of file Species.h.
vr_iterator Species::endProductReactions () [inline]
Return std::vector<Reaction *>::iterator, which points to the end of all Reactions where this Species is involved as a Product.
Definition at line 271 of file Species.h.
vr_iterator Species::endReactantReactions () [inline]
Return std::vector<Reaction *>::iterator, which points to the end of all Reactions where this Species is involved as a Reactant.
Definition at line 267 of file Species.h.
Referenced by main().
std::string Species::getFullName () const [inline]
Return the full name of this Species in a std::string format (e.g. "Arp2/3{Bulk}".
Definition at line 234 of file Species.h.
Referenced by print_species(), and Species::printSelf().
species_copy_t Species::getN () const [inline]
Return the current copy number of this Species.
Definition at line 228 of file Species.h.
Referenced by Reaction::computePropensity(), and print_species().
std::string SpeciesType::getName () const [inline]
Returns the name associated with this SpeciesType as a string.
Definition at line 102 of file Species.h.
Referenced by SpeciesType::operator==().
Species* SpeciesContainer::getSpecies (const std::string & unq_key) [inline]
Definition at line 301 of file Species.h.
Referenced by main().
SType SpeciesType::getType () const [inline]
Returns the SType associated with this SpeciesType.
Definition at line 106 of file Species.h.
Referenced by SpeciesType::operator==().
flyweight<SpeciesType> Species::getType () const [inline]
Return SpeciesType associated with this Species.
Definition at line 231 of file Species.h.
std::string SpeciesType::getTypeAsString () const [inline]
Returns a string representing this SpeciesType by concatanating its name and type.
Definition at line 109 of file Species.h.
bool Species::is_of_species_type (const std::string & name, SType type) const [inline]
A helper function which determines whether parameter std:string name corresponds the SpeciesType associated with this Species.
Definition at line 275 of file Species.h.
bool SpeciesType::is_of_type (const std::string & name, SType type) const [inline]
Return if true if this SpeciesType has name and SType given as parameters to this function.
Definition at line 112 of file Species.h.
bool Species::isSignaling () const [inline]
Return true if this Species emits signals on copy number change.
Definition at line 237 of file Species.h.
References Reaction::_is_signaling.
void Species::makeSignaling (SignalingManager & sm)
Set the signaling behavior of this Species.
Parameters:
is the SignalingManager which will call the associated Signal (typically initiated by the Gillespie-like simulation algorithm)
Definition at line 27 of file Species.cpp.
References Species::_is_signaling, and SignalingManager::addSignalingSpecies().
Referenced by main().
SpeciesType& SpeciesType::operator= (const SpeciesType & st) [inline]
Definition at line 80 of file Species.h.
References SpeciesType::_name, and SpeciesType::_type.
SpeciesType& SpeciesType::operator= (SpeciesType && st) [inline]
Assignment operators copies all fields. May be needed for boost::flyweight?
Definition at line 89 of file Species.h.
Species& Species::operator= (Species &)
SpeciesContainer& SpeciesContainer::operator= (SpeciesContainer &)
bool SpeciesType::operator== (const SpeciesType & species_type) const [inline]
Equality operator use both species name and type to compare to SpeciesType objects.
Definition at line 96 of file Species.h.
References SpeciesType::getName(), and SpeciesType::getType().
void Species::passivateAssocReacts () [private]
Passivates all Reactions where this Species is among the reactants.
Definition at line 22 of file Species.cpp.
References Species::_as_reactants.
void Species::printSelf () const
Prints some helpful information about this Species.
Should be used mainly for debugging and development purposes.
Definition at line 37 of file Species.cpp.
References Species::_n, and Species::getFullName().
Referenced by main(), and PrintSpecies::operator()().
std::vector<Reaction *> Species::ProductReactions () [inline]
Return std::vector<Reaction *>, which contains pointers to all Reactions where this Species is involved as a Product.
Definition at line 255 of file Species.h.
std::vector<Reaction *> Species::ReactantReactions () [inline]
Return std::vector<Reaction *>, which contains pointers to all Reactions where this Species is involved as a Reactant.
Definition at line 251 of file Species.h.
void Species::removeAsProduct (const Reaction * r) [inline, private]
Definition at line 180 of file Species.h.
Referenced by Reaction::~Reaction().
void Species::removeAsReactant (const Reaction * r) [inline, private]
Definition at line 171 of file Species.h.
Referenced by Reaction::~Reaction().
void Species::setN (species_copy_t n) [inline]
Setters & Mutators Sets the copy number for this Species.
Parameters:
should be a non-negative number, but no checking is done in run time
Definition at line 225 of file Species.h.
void Species::stopSignaling (SignalingManager & sm)
Destroy the signal associated with this Species.
Parameters:
is the SignalingManager which manages signals
Note:
To start signaling again, makeSignaling(...) needs to be called
Definition at line 32 of file Species.cpp.
References Species::_is_signaling, and SignalingManager::disconnect_semiprivate().
void Species::up () [inline, private]
Increases the copy number by 1.
If the copy number changes from 0 to 1, calls a "callback"-like method to activated previously passivated Reactions, where this Species is a Reactant.
Definition at line 147 of file Species.h.
Variable Documentation
std::vector<Reaction *> Species::_as_products [private]
a vector of Reactions where this Species is a Product
Definition at line 139 of file Species.h.
std::vector<Reaction *> Species::_as_reactants [private]
a vector of Reactions where this Species is a Reactant
Definition at line 138 of file Species.h.
Referenced by Species::activateAssocReactions(), and Species::passivateAssocReacts().
bool Species::_is_signaling [private]
If true, indicates a signal may be sent when a copy number of this Reaction changes.
Definition at line 142 of file Species.h.
Referenced by Species::makeSignaling(), and Species::stopSignaling().
map_str_species SpeciesContainer::_map_species [private]
Definition at line 308 of file Species.h.
species_copy_t Species::_n [private]
Current copy number of this Species.
Definition at line 141 of file Species.h.
Referenced by Species::printSelf().
std::string SpeciesType::_name [private]
the descriptive name associated with this Species
Definition at line 67 of file Species.h.
Referenced by SpeciesType::operator=().
SType SpeciesType::_type [private]
the type of species, such as Bulk, Diffusing, etc.
Definition at line 68 of file Species.h.
Referenced by SpeciesType::operator=().
flyweight<SpeciesType> Species::_type [private]
This Species' type.
Definition at line 140 of file Species.h.
std::vector< std::string > SpeciesType::_vec_type_name = {"Bulk", "Diffusing", "Membrane", "Filament", "Walking", "Motors" } [static, private]
this variable is used to help translate strings to enum values for the SType
Definition at line 69 of file Species.h.
Friends
std::size_t hash_value (SpeciesType const & species_type) [friend]
boost::flyweight needs a hashing function, defined here.
Definition at line 115 of file Species.h.
friend class Reaction [friend]
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
Definition at line 135 of file Species.h.