CytoSim: chem Namespace Reference
chem Namespace Reference
Classes
class RNodeGillespie
RNodeGillespie is used by ChemGillespieImpl to implement the cached version of the Gillespie algorithm.
class ChemGillespieImpl
ChemGillespieImpl implements a slightly optimized version of the Gillespie algorithm.
class PQNode
PQNode stands for Priority Queue Node.
class RNodeNRM
RNodeNRM stands for Reaction Node Next Reaction Method.
class ChemNRMImpl
ChemNRMImpl stands for Chemical Next Reaction Method Implementation.
class RNode
This is an abstract base class for classes that need to be associated with the given Reaction object.
class ChemSim
ChemSim is used to manage running a network of chemical reactions.
class ChemSimImpl
ChemSimImpl is an abstract base class for algorithms that run stochastic chemical kinetics.
class ChemSimpleGillespieImpl
ChemSimpleGillespieImpl implements the simplest version of the Gillespie algorithm, without caching, etc.
class Compartment
class CompartmentCubic
class CompartmentsSimpleGrid
class Component
class Composite
class ReactionBase
ReactionBase class represents an abstract interface for simple chemical Reactions of the form A + B -> C.
class Reaction
Reaction<M,N> class represents a concrete chemical reaction, such as A + B -> C, where M is the number of reactants and N is the number of products.
class ReactionPtrContainerIFace
class ReactionPtrContainerVector
class RSpecies
RSpecies class represents the reactive aspect of chemical molecules. It tracks their copy number and can be used in Reactions.
class ChemSignal
ChemSignal manages callbacks for RSpecies and Reactions objects.
class SpeciesNamesDB
SpeciesNamesDB class is used to associate unique integers with character based names of Species.
class Species
Species class represents chemical molecules, tracks their copy number and can be used in Reactions.
class SpeciesBulk
SpeciesBulk should be used for Species without spatial information (i.e. well-mixed in the container)
class SpeciesDiffusing
SpeciesDiffusing should be used for Species which can move spatially from one compartment to the neighboring one (i.e. they are the stochastic analogue of determenistic reaction-diffusion processes)
class SpeciesPtrContainerIFace
class SpeciesPtrContainerVector
class SpeciesContainerIFace
class SpeciesContainerVector
class Visitor
class ConditionalVisitor
class ConcreteVisitor
class FindFirstSpeciesVisitor
class CompositeVisitor
Typedefs
typedef
boost::fast_pool_allocator
< PQNode > fast_allocator_t
typedef
boost::heap::pairing_heap
< PQNode,
boost::heap::allocator
< fast_allocator_t > > boost_heap
typedef
boost::heap::pairing_heap
< PQNode,
boost::heap::allocator
< fast_allocator_t >
>::handle_type handle_t
typedef
boost::signals2::signal< void(ReactionBase *)> ReactionEventSignal
This is a ReactionBase signal object that may be called by a ReactionBase simulation algorithm.
typedef std::vector
< ReactionBase * >::iterator vr_iterator
vr stands for vector of Reactions
typedef std::vector
< ReactionBase * >
::const_iterator vr_const_iterator
typedef std::vector< RSpecies * >
::iterator vrsp_iterator
vsp stands for vector of RSpecies
typedef std::vector< RSpecies * >
::const_iterator vrsp_const_iterator
typedef
boost::signals2::signal< void(RSpecies
*, int)> RSpeciesCopyNChangedSignal
This is a RSpecies signal object that can be used to signal when the copy number changes.
Functions
boost::pool allocator_rnodenrm (sizeof(RNodeNRM), BOOL_POOL_NSIZE)
boost::pool allocator_pqnode (sizeof(PQNode), BOOL_POOL_NSIZE)
bool operator== (const Compartment &a, const Compartment &b)
boost::pool allocator_rspecies (sizeof(RSpecies), BOOL_POOL_NSIZE)
Variables
long long int elapsed14 = 0
long long int elapsed16 = 0
long long int elapsed23 = 0
long long int elapsed45 = 0
long long int elapsed56 = 0
Typedef Documentation
typedef boost::heap::pairing_heap<PQNode, boost::heap::allocator<fast_allocator_t> > chem::boost_heap
Definition at line 43 of file ChemNRMImpl.h.
typedef boost::fast_pool_allocator<PQNode> chem::fast_allocator_t
Definition at line 39 of file ChemNRMImpl.h.
typedef boost::heap::pairing_heap<PQNode, boost::heap::allocator<fast_allocator_t> >::handle_type chem::handle_t
Definition at line 44 of file ChemNRMImpl.h.
typedef boost::signals2::signal< void(ReactionBase *)> chem::ReactionEventSignal
This is a ReactionBase signal object that may be called by a ReactionBase simulation algorithm.
This is a Reaction signal object that will be called by ChemSignal, usually when requested by the reaction simulation algorithm.
Definition at line 32 of file Reaction.h.
typedef boost::signals2::signal< void(RSpecies *, int)> chem::RSpeciesCopyNChangedSignal
This is a RSpecies signal object that can be used to signal when the copy number changes.
This is a RSpecies signal object that will be called by ChemSignal, usually when requested by the reaction simulation algorithm.
Definition at line 44 of file RSpecies.h.
typedef std::vector<ReactionBase*>::const_iterator chem::vr_const_iterator
Definition at line 37 of file RSpecies.h.
typedef std::vector<ReactionBase*>::iterator chem::vr_iterator
vr stands for vector of Reactions
Definition at line 33 of file RSpecies.h.
typedef std::vector<RSpecies*>::const_iterator chem::vrsp_const_iterator
Definition at line 41 of file RSpecies.h.
typedef std::vector<RSpecies*>::iterator chem::vrsp_iterator
vsp stands for vector of RSpecies
Definition at line 40 of file RSpecies.h.
Function Documentation
boost::pool chem::allocator_pqnode (sizeof(PQNode) , BOOL_POOL_NSIZE)
boost::pool chem::allocator_rnodenrm (sizeof(RNodeNRM) , BOOL_POOL_NSIZE)
boost::pool chem::allocator_rspecies (sizeof(RSpecies) , BOOL_POOL_NSIZE)
bool chem::operator== (const Compartment & a, const Compartment & b)
Two Compartment objects are equal if each contains analogous Species and Reaction objects, in the same order
Definition at line 42 of file Compartment.cpp.
References chem::Compartment::_internal_reactions, chem::Compartment::_species, chem::Compartment::numberOfInternalReactions(), chem::Compartment::numberOfSpecies(), chem::ReactionPtrContainerVector::reactions(), and chem::SpeciesPtrContainerVector::species().
Variable Documentation
long long int chem::elapsed14 = 0
Definition at line 73 of file ChemNRMImpl.cpp.
long long int chem::elapsed16 = 0
Definition at line 74 of file ChemNRMImpl.cpp.
long long int chem::elapsed23 = 0
Definition at line 75 of file ChemNRMImpl.cpp.
long long int chem::elapsed45 = 0
Definition at line 76 of file ChemNRMImpl.cpp.
long long int chem::elapsed56 = 0
Definition at line 77 of file ChemNRMImpl.cpp.