MEDYAN: BranchingFF Class Reference
BranchingFF Class Reference
Branching FF is an implementation of the ForceField class that calculates BranchingPoint interactions.
#include <BranchingFF.h>
Public Member Functions
BranchingFF (string &stretching, string &bending, string &dihedral, string &position)
Constructor, intializes all interaction at the branching point.
virtual string getName ()
Get the name of this forcefield.
virtual void whoIsCulprit ()
In the case of a calculation error, print the culprit of the FF error.
virtual double computeEnergy (double d)
Compute total energy of this forcefield in the system.
virtual void computeForces ()
Compute forces of this forcefield in the system.
virtual void computeForcesAux ()
Compute auxiliary forces of this forcefield in the system.
virtual void computeLoadForces ()
Compute all load forces on beads in this system.
virtual vector< NeighborList * > getNeighborLists ()
Get all neighbor lists associated with a ForceField.
Private Attributes
vector< unique_ptr< BranchingInteractions > > _branchingInteractionVector
Vector of initialized branching interactions.
BranchingInteractions * _culpritInteraction
Culprit in case of error.
Detailed Description
Branching FF is an implementation of the ForceField class that calculates BranchingPoint interactions.
Definition at line 29 of file BranchingFF.h.
Constructor & Destructor Documentation
BranchingFF()
BranchingFF::BranchingFF (string & stretching, string & bending, string & dihedral, string & position)
Constructor, intializes all interaction at the branching point.
Definition at line 30 of file BranchingFF.cpp.
References _branchingInteractionVector.
Member Function Documentation
computeEnergy()
double BranchingFF::computeEnergy (double d) virtual
Compute total energy of this forcefield in the system.
Returns
the energy value if valid. If an inf or NaN value has been calculated, return -1.
Implements ForceField.
Definition at line 84 of file BranchingFF.cpp.
References _branchingInteractionVector, and _culpritInteraction.
Referenced by getName().
computeForces()
void BranchingFF::computeForces () virtual
Compute forces of this forcefield in the system.
Update Bead forces accordingly.
Implements ForceField.
Definition at line 104 of file BranchingFF.cpp.
References _branchingInteractionVector.
Referenced by getName().
computeForcesAux()
void BranchingFF::computeForcesAux () virtual
Compute auxiliary forces of this forcefield in the system.
Update Bead auxiliary forces accordingly.
Implements ForceField.
Definition at line 110 of file BranchingFF.cpp.
References _branchingInteractionVector.
Referenced by getName().
computeLoadForces()
virtual void BranchingFF::computeLoadForces () inline virtual
Compute all load forces on beads in this system.
Updates all Bead's load force components for Reaction updating.
Implements ForceField.
Definition at line 48 of file BranchingFF.h.
getName()
virtual string BranchingFF::getName () inline virtual
Get the name of this forcefield.
Implements ForceField.
Definition at line 41 of file BranchingFF.h.
References computeEnergy(), computeForces(), computeForcesAux(), and whoIsCulprit().
getNeighborLists()
virtual vector<NeighborList*> BranchingFF::getNeighborLists () inline virtual
Get all neighbor lists associated with a ForceField.
Implements ForceField.
Definition at line 50 of file BranchingFF.h.
whoIsCulprit()
void BranchingFF::whoIsCulprit () virtual
In the case of a calculation error, print the culprit of the FF error.
Typically, will just print the Trackable element where the error came from.
Implements ForceField.
Definition at line 71 of file BranchingFF.cpp.
References BranchingInteractions::_branchingCulprit, _culpritInteraction, BranchingInteractions::getName(), and BranchingPoint::printSelf().
Referenced by getName().
Member Data Documentation
_branchingInteractionVector
vector<unique_ptr<BranchingInteractions> > BranchingFF::_branchingInteractionVector private
Vector of initialized branching interactions.
Definition at line 33 of file BranchingFF.h.
Referenced by BranchingFF(), computeEnergy(), computeForces(), and computeForcesAux().
_culpritInteraction
BranchingInteractions* BranchingFF::_culpritInteraction private
Culprit in case of error.
Definition at line 35 of file BranchingFF.h.
Referenced by computeEnergy(), and whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Branching/BranchingFF.h
src/Mechanics/ForceField/Branching/BranchingFF.cpp