MEDYAN: CylinderCylinderNL Class Reference
CylinderCylinderNL Class Reference
An implementation of NeighborList for Cylinder-Cylinder interactions This can be a half or full list depending on the usage.
#include <NeighborListImpl.h>
Public Member Functions
CylinderCylinderNL (float rMax, float rMin=0.0, bool full=false)
virtual void addNeighbor (Neighbor *n)
Add neighbor.
virtual void removeNeighbor (Neighbor *n)
Remove a neighbor if possible.
virtual void reset ()
Re-initialize the neighborlist.
vector< Cylinder * > getNeighbors (Cylinder *cylinder)
Get all cylinder neighbors.
virtual void addDynamicNeighbor (DynamicNeighbor *n)
The implementation of these functions calls the static version, all cylinders are dynamic.
virtual void removeDynamicNeighbor (DynamicNeighbor *n)
The implementation of these functions calls the static version, all cylinders are dynamic.
Protected Attributes
float _rMax
max distance cutoff
float _rMin
min distance cutoff
Private Member Functions
void updateNeighbors (Cylinder *cylinder, bool runtime=false)
Helper function to update neighbors.
Private Attributes
unordered_map< Cylinder *, vector< Cylinder * > > _list
The neighbors list, as a hash map.
bool _full
Specifying whether this is a full or half list.
Detailed Description
An implementation of NeighborList for Cylinder-Cylinder interactions This can be a half or full list depending on the usage.
Definition at line 32 of file NeighborListImpl.h.
Constructor & Destructor Documentation
CylinderCylinderNL()
CylinderCylinderNL::CylinderCylinderNL (float rMax, float rMin = 0.0, bool full = false) inline
Definition at line 46 of file NeighborListImpl.h.
References addDynamicNeighbor(), addNeighbor(), and removeNeighbor().
Member Function Documentation
addDynamicNeighbor()
virtual void CylinderCylinderNL::addDynamicNeighbor (DynamicNeighbor * n) inline virtual
The implementation of these functions calls the static version, all cylinders are dynamic.
Implements NeighborList.
Definition at line 56 of file NeighborListImpl.h.
Referenced by BoundaryBubbleNL::BoundaryBubbleNL(), BoundaryCylinderNL::BoundaryCylinderNL(), BubbleBubbleNL::BubbleBubbleNL(), BubbleCylinderNL::BubbleCylinderNL(), and CylinderCylinderNL().
addNeighbor()
void CylinderCylinderNL::addNeighbor (Neighbor * n) virtual
Add neighbor.
Implements NeighborList.
Definition at line 74 of file NeighborListImpl.cpp.
Referenced by BoundaryBubbleNL::BoundaryBubbleNL(), BoundaryCylinderNL::BoundaryCylinderNL(), BubbleBubbleNL::BubbleBubbleNL(), BubbleCylinderNL::BubbleCylinderNL(), and CylinderCylinderNL().
getNeighbors()
vector< Cylinder * > CylinderCylinderNL::getNeighbors (Cylinder * cylinder)
Get all cylinder neighbors.
Definition at line 109 of file NeighborListImpl.cpp.
Referenced by BoundaryBubbleNL::BoundaryBubbleNL(), BoundaryCylinderNL::BoundaryCylinderNL(), removeDynamicNeighbor(), BubbleBubbleNL::removeDynamicNeighbor(), and BubbleCylinderNL::removeDynamicNeighbor().
removeDynamicNeighbor()
virtual void CylinderCylinderNL::removeDynamicNeighbor (DynamicNeighbor * n) inline virtual
The implementation of these functions calls the static version, all cylinders are dynamic.
Implements NeighborList.
Definition at line 57 of file NeighborListImpl.h.
References getNeighbors(), removeNeighbor(), and reset().
Referenced by BoundaryBubbleNL::BoundaryBubbleNL(), and BoundaryCylinderNL::BoundaryCylinderNL().
removeNeighbor()
void CylinderCylinderNL::removeNeighbor (Neighbor * n) virtual
Remove a neighbor if possible.
Implements NeighborList.
Definition at line 84 of file NeighborListImpl.cpp.
Referenced by BoundaryBubbleNL::BoundaryBubbleNL(), BoundaryCylinderNL::BoundaryCylinderNL(), BubbleBubbleNL::BubbleBubbleNL(), BubbleCylinderNL::BubbleCylinderNL(), CylinderCylinderNL(), removeDynamicNeighbor(), BubbleBubbleNL::removeDynamicNeighbor(), and BubbleCylinderNL::removeDynamicNeighbor().
reset()
void CylinderCylinderNL::reset () virtual
Re-initialize the neighborlist.
Implements NeighborList.
Definition at line 99 of file NeighborListImpl.cpp.
References Cylinder::getCylinders().
Referenced by BoundaryBubbleNL::BoundaryBubbleNL(), BoundaryCylinderNL::BoundaryCylinderNL(), removeDynamicNeighbor(), BubbleBubbleNL::removeDynamicNeighbor(), and BubbleCylinderNL::removeDynamicNeighbor().
updateNeighbors()
void CylinderCylinderNL::updateNeighbors (Cylinder * cylinder, bool runtime = false) private
Helper function to update neighbors.
Parameters
runtime - specifying whether the cylinder is being created/destroyed at runtime vs at a full neighbor list update.
Definition at line 29 of file NeighborListImpl.cpp.
References Cylinder::coordinate, GController::findCompartments(), SysParams::Geometry(), Cylinder::getCompartment(), Cylinder::getID(), Component::getParent(), Cylinder::getPosition(), GeoParams::largestCompartmentSide, and mathfunc::twoPointDistance().
Member Data Documentation
_full
bool CylinderCylinderNL::_full private
Specifying whether this is a full or half list.
Definition at line 38 of file NeighborListImpl.h.
_list
unordered_map<Cylinder*, vector<Cylinder*> > CylinderCylinderNL::_list private
The neighbors list, as a hash map.
Definition at line 35 of file NeighborListImpl.h.
_rMax
float NeighborList::_rMax protected inherited
max distance cutoff
Definition at line 36 of file NeighborList.h.
_rMin
float NeighborList::_rMin protected inherited
min distance cutoff
Definition at line 37 of file NeighborList.h.
The documentation for this class was generated from the following files:
src/Structure/NeighborListImpl.h
src/Structure/NeighborListImpl.cpp