MEDYAN: SysParams Class Reference
SysParams Class Reference
Static class that holds all simulation parameters, initialized by the SystemParser.
#include <SysParams.h>
Static Public Member Functions
static bool checkChemParameters (ChemistryData &chem)
static bool checkMechParameters (MechanicsFFType &mech)
static bool checkDyRateParameters (DynamicRateType &dy)
static bool checkGeoParameters ()
Static Private Attributes
static MechParams MParams
Public access if testing only.
static ChemParams CParams
The chemistry parameters.
static GeoParams GParams
The geometry parameters.
static BoundParams BParams
The boundary parameters.
static DyRateParams DRParams
The dynamic rate parameters.
Friends
class Controller
class SystemParser
class ChemManager
static bool RUNSTATE =true
Const getter.
static vector< float > MUBBareRate ={}
Const getter.
static vector< float > LUBBareRate ={}
Const getter.
static vector< float > BUBBareRate ={}
Const getter.
static const MechParams & Mechanics ()
Const getter.
static const ChemParams & Chemistry ()
Const getter.
static const GeoParams & Geometry ()
Const getter.
static const BoundParams & Boundaries ()
Const getter.
static const DyRateParams & DynamicRates ()
Const getter.
Detailed Description
Static class that holds all simulation parameters, initialized by the SystemParser.
Definition at line 239 of file SysParams.h.
Member Function Documentation
Boundaries()
static const BoundParams& SysParams::Boundaries () inline static
Const getter.
Definition at line 265 of file SysParams.h.
Referenced by BoundaryBubbleRepulsion< BRepulsionInteractionType >::BoundaryBubbleRepulsion(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::BoundaryCylinderRepulsion(), RandomFilamentDist::createFilaments(), ConnectedFilamentDist::createFilaments(), CylinderZ::CylinderZ(), HalfSphereZ::HalfSphereZ(), GController::initializeBoundary(), Controller::moveBoundary(), Plane::Plane(), and Sphere::Sphere().
checkChemParameters()
bool SysParams::checkChemParameters (ChemistryData & chem) static
Cylinder and monomer lengths specified
Definition at line 19 of file SysParams.cpp.
References ChemistryData::B_BINDING_INDEX, CParams, ChemistryData::L_BINDING_INDEX, ChemistryData::M_BINDING_INDEX, ChemParams::motorNumHeadsMax, ChemParams::motorNumHeadsMin, ChemParams::motorStepSize, ChemParams::numBoundSpecies, ChemParams::numBrancherSpecies, ChemParams::numBulkSpecies, ChemParams::numDiffusingSpecies, ChemParams::numFilaments, ChemParams::numFilamentSpecies, ChemParams::numLinkerSpecies, ChemParams::numMinusEndSpecies, ChemParams::numMotorSpecies, ChemParams::numPlusEndSpecies, ChemistryData::speciesBound, ChemistryData::speciesBrancher, ChemistryData::speciesBulk, ChemistryData::speciesDiffusing, ChemistryData::speciesFilament, ChemistryData::speciesLinker, ChemistryData::speciesMinusEnd, ChemistryData::speciesMotor, ChemistryData::speciesPlusEnd, and std::sum().
Referenced by Controller::initialize().
checkDyRateParameters()
bool SysParams::checkDyRateParameters (DynamicRateType & dy) static
Cylinder and monomer lengths specified
Definition at line 396 of file SysParams.cpp.
References BParams, CParams, DynamicRateType::dFPolymerizationType, DynamicRateType::dLUnbindingType, DynamicRateType::dMUnbindingType, DynamicRateType::dMWalkingType, DRParams, DynamicRates(), GParams, MParams, ChemParams::numFilaments, ChemParams::numLinkerSpecies, ChemParams::numMotorSpecies, and std::sum().
Referenced by Controller::initialize().
checkGeoParameters()
bool SysParams::checkGeoParameters () static
Cylinder and monomer lengths specified
Definition at line 380 of file SysParams.cpp.
References GeoParams::compartmentSizeX, GeoParams::compartmentSizeY, GeoParams::compartmentSizeZ, GParams, GeoParams::nDim, GeoParams::NX, GeoParams::NY, and GeoParams::NZ.
Referenced by Controller::initialize().
checkMechParameters()
bool SysParams::checkMechParameters (MechanicsFFType & mech) static
Cylinder and monomer lengths specified
Definition at line 196 of file SysParams.cpp.
References areEqual(), BoundParams::BoundaryCutoff, MechanicsFFType::BoundaryFFType, BoundParams::BoundaryK, BParams, MechParams::BrBendingK, MechParams::BrBendingTheta, MechanicsFFType::BrBendingType, MechParams::BrDihedralK, MechanicsFFType::BrDihedralType, MechParams::BrPositionK, MechanicsFFType::BrPositionType, MechParams::BrStretchingK, MechParams::BrStretchingL, MechanicsFFType::BrStretchingType, BoundParams::BScreenLength, MechParams::BubbleCutoff, MechanicsFFType::BubbleFFType, MechParams::BubbleK, MechParams::BubbleRadius, MechParams::BubbleScreenLength, CParams, GeoParams::cylinderSize, MechParams::FBendingK, MechanicsFFType::FBendingType, MechParams::FStretchingK, MechanicsFFType::FStretchingType, MechParams::FTwistingK, MechanicsFFType::FTwistingType, GParams, MechParams::LBendingK, MechParams::LBendingTheta, MechanicsFFType::LBendingType, MechParams::LStretchingK, MechanicsFFType::LStretchingType, MechParams::LTwistingK, MechParams::LTwistingPhi, MechanicsFFType::LTwistingType, MechParams::MBendingK, MechParams::MBendingTheta, MechanicsFFType::MBendingType, GeoParams::monomerSize, MParams, MechParams::MStretchingK, MechanicsFFType::MStretchingType, MechParams::MTwistingK, MechParams::MTwistingPhi, MechanicsFFType::MTwistingType, ChemParams::numBrancherSpecies, MechParams::numBubbleTypes, ChemParams::numFilaments, ChemParams::numLinkerSpecies, ChemParams::numMotorSpecies, std::sum(), MechParams::VolumeCutoff, MechanicsFFType::VolumeFFType, and MechParams::VolumeK.
Referenced by Controller::initialize().
Chemistry()
static const ChemParams& SysParams::Chemistry () inline static
Const getter.
Definition at line 263 of file SysParams.h.
Referenced by CMonomer::activeSpeciesBrancher(), CMonomer::activeSpeciesFilament(), CMonomer::activeSpeciesLinker(), CMonomer::activeSpeciesMinusEnd(), CMonomer::activeSpeciesMotor(), CMonomer::activeSpeciesPlusEnd(), BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), SeveringTemplate::addReaction(), Restart::addtoHeapbranchers(), Restart::addtoHeaplinkermotor(), CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), ChemManager::configCMonomer(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), Controller::executeSpecialProtocols(), ChemManager::genFilBindingReactions(), ChemManager::genFilReactionTemplates(), ChemManager::genNucleationReactions(), ChemManager::genSpecies(), DRController::initialize(), ChemManager::initializeCCylinder(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), MotorGhost::MotorGhost(), MotorStall::MotorStall(), CMotorGhost::moveMotorHead(), Filament::nucleate(), Chemistry::print(), BranchingManager::removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), ChemManager::setupBindingSites(), Controller::setupInitialNetwork(), Filament::sever(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), MotorBindingManager::updateAllPossibleBindings(), and BranchingPoint::~BranchingPoint().
DynamicRates()
static const DyRateParams& SysParams::DynamicRates () inline static
Const getter.
Definition at line 266 of file SysParams.h.
Referenced by checkDyRateParameters(), and DRController::initialize().
Geometry()
static const GeoParams& SysParams::Geometry () inline static
Const getter.
Definition at line 264 of file SysParams.h.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Restart::addtoHeapbranchers(), Restart::addtoHeaplinkermotor(), Bead::Bead(), BranchingPoint::BranchingPoint(), CCylinder::CCylinder(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), RandomFilamentDist::createFilaments(), ConnectedFilamentDist::createFilaments(), MTOCFilamentDist::createFilaments(), Restart::crosschecklinkermotor(), Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), Filament::Filament(), ChemManager::genFilBindingReactions(), Bead::getLoadForcesM(), Bead::getLoadForcesP(), GController::initializeGrid(), Linker::Linker(), MotorGhost::MotorGhost(), MotorStall::MotorStall(), MotorGhost::moveMotorHead(), Filament::nucleate(), Filament::polymerizeMinusEnd(), Filament::polymerizePlusEnd(), SystemParser::readBoundParams(), SystemParser::readChemParams(), SystemParser::readGeoParams(), MCylinder::setEqLength(), Controller::setupInitialNetwork(), Controller::setupSpecialStructures(), Filament::sever(), Filament::straightFilamentProjection(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), MotorBindingManager::updateAllPossibleBindings(), CylinderCylinderNL::updateNeighbors(), Cylinder::updatePosition(), BoundaryCubic::within(), BoundarySpherical::within(), Filament::zigZagFilamentProjection(), and BranchingPoint::~BranchingPoint().
Mechanics()
static const MechParams& SysParams::Mechanics () inline static
Const getter.
Definition at line 262 of file SysParams.h.
Referenced by BoundaryFF::BoundaryFF(), Bubble::Bubble(), BubbleBubbleRepulsion< BRepulsionInteractionType >::BubbleBubbleRepulsion(), BubbleCylinderRepulsion< BRepulsionInteractionType >::BubbleCylinderRepulsion(), BoundaryCylinderAttachment< BAttachmentInteractionType >::computeEnergy(), BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForces(), BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForcesAux(), RandomBubbleDist::createBubbles(), CylinderExclVolume< CVolumeInteractionType >::CylinderExclVolume(), Controller::executeSpecialProtocols(), MBranchingPoint::MBranchingPoint(), MCylinder::MCylinder(), MLinker::MLinker(), MMotorGhost::MMotorGhost(), Controller::pinBoundaryFilaments(), WallTensions::print(), MCylinder::setEqLength(), MMotorGhost::setStretchingConstant(), Controller::setupInitialNetwork(), and Controller::setupSpecialStructures().
Friends And Related Function Documentation
ChemManager
friend class ChemManager friend
Definition at line 242 of file SysParams.h.
Controller
friend class Controller friend
Definition at line 240 of file SysParams.h.
SystemParser
friend class SystemParser friend
Definition at line 241 of file SysParams.h.
Member Data Documentation
BParams
BoundParams SysParams::BParams static private
The boundary parameters.
Definition at line 250 of file SysParams.h.
Referenced by checkDyRateParameters(), checkMechParameters(), and SystemParser::readBoundParams().
BUBBareRate
vector< float > SysParams::BUBBareRate ={} static
Const getter.
Definition at line 260 of file SysParams.h.
Referenced by ChemManager::genFilBindingReactions().
CParams
ChemParams SysParams::CParams static private
The chemistry parameters.
Definition at line 248 of file SysParams.h.
Referenced by checkChemParameters(), checkDyRateParameters(), checkMechParameters(), ChemManager::genFilBindingReactions(), ChemManager::genFilReactionTemplates(), ChemManager::initializeCCylinder(), SystemParser::readChemParams(), and ChemManager::setupBindingSites().
DRParams
DyRateParams SysParams::DRParams static private
The dynamic rate parameters.
Definition at line 251 of file SysParams.h.
Referenced by checkDyRateParameters(), and SystemParser::readDyRateParams().
GParams
GeoParams SysParams::GParams static private
The geometry parameters.
Definition at line 249 of file SysParams.h.
Referenced by checkDyRateParameters(), checkGeoParameters(), checkMechParameters(), and SystemParser::readGeoParams().
LUBBareRate
vector< float > SysParams::LUBBareRate ={} static
Const getter.
Definition at line 259 of file SysParams.h.
Referenced by ChemManager::genFilBindingReactions().
MParams
MechParams SysParams::MParams static private
Public access if testing only.
The mechanical parameters
Definition at line 247 of file SysParams.h.
Referenced by checkDyRateParameters(), checkMechParameters(), and SystemParser::readMechParams().
MUBBareRate
vector< float > SysParams::MUBBareRate ={} static
Const getter.
Definition at line 258 of file SysParams.h.
Referenced by ChemManager::genFilBindingReactions().
RUNSTATE
bool SysParams::RUNSTATE =true static
Const getter.
Definition at line 256 of file SysParams.h.
Referenced by SystemParser::readFilamentSetup(), Controller::run(), Linker::updateReactionRates(), and MotorGhost::updateReactionRates().
The documentation for this class was generated from the following files:
src/SysParams.h
src/SysParams.cpp