MEDYAN: BoundaryCylinderAttachmentHarmonic Class Reference
BoundaryCylinderAttachmentHarmonic Class Reference
A harmonic attractive potential used by the BoundaryCylinderAttachment template.
#include <BoundaryCylinderAttachmentHarmonic.h>
Public Member Functions
double energy (Bead *, double)
double energy (Bead *, double, double)
void forces (Bead *, double)
void forcesAux (Bead *, double)
Detailed Description
A harmonic attractive potential used by the BoundaryCylinderAttachment template.
Definition at line 26 of file BoundaryCylinderAttachmentHarmonic.h.
Member Function Documentation
energy() [1/2]
double BoundaryCylinderAttachmentHarmonic::energy (Bead * b, double kAttr)
Definition at line 22 of file BoundaryCylinderAttachmentHarmonic.cpp.
References Bead::coordinate, Bead::pinnedPosition, and mathfunc::twoPointDistance().
energy() [2/2]
double BoundaryCylinderAttachmentHarmonic::energy (Bead * b, double kAttr, double d)
Definition at line 28 of file BoundaryCylinderAttachmentHarmonic.cpp.
References Bead::coordinate, Bead::force, Bead::pinnedPosition, and mathfunc::twoPointDistanceStretched().
forces()
void BoundaryCylinderAttachmentHarmonic::forces (Bead * b, double kAttr)
Definition at line 36 of file BoundaryCylinderAttachmentHarmonic.cpp.
References areEqual(), Bead::coordinate, Bead::force, mathfunc::normalizedVector(), Bead::pinnedPosition, mathfunc::twoPointDirection(), and mathfunc::twoPointDistance().
forcesAux()
void BoundaryCylinderAttachmentHarmonic::forcesAux (Bead * b, double kAttr)
Definition at line 50 of file BoundaryCylinderAttachmentHarmonic.cpp.
References areEqual(), Bead::coordinate, Bead::forceAux, mathfunc::normalizedVector(), Bead::pinnedPosition, mathfunc::twoPointDirection(), and mathfunc::twoPointDistance().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Boundary/BoundaryCylinderAttachmentHarmonic.h
src/Mechanics/ForceField/Boundary/BoundaryCylinderAttachmentHarmonic.cpp