M3Sym: NeighborListDB Class Reference
NeighborListDB Class Reference
A database to store all NeighborLists in the system.
#include <NeighborListDB.h>
Public Member Functions
NeighborListDB (const NeighborListDB &rhs)=delete
Copying is not allowed.
NeighborListDB & operator= (NeighborListDB &rhs)=delete
Assignment is not allowed.
void addNeighborList (NeighborList *n)
Add a cylinder neighbor list.
void removeNeighborList (NeighborList *n)
Remove a neighborlist.
void resetAll ()
Reset all neighbors lists.
void addNeighbor (Neighbor *n)
Add a neighbor to the db. adds to all possible lists.
void removeNeighbor (Neighbor *n)
Remove a neighbor from the db. removes from all possible lists.
Static Public Member Functions
static NeighborListDB * instance ()
Get instance.
Private Types
typedef list< NeighborList * > ndb
Private Member Functions
NeighborListDB ()
Private Attributes
T elements
STL member.
Static Private Attributes
static NeighborListDB * _instance = 0
Singleton instance.
Detailed Description
A database to store all NeighborLists in the system.
This NeighborListDB inherits from list and manage all creations and removing of NeighborLists objects, as well as some standard list functions and iterators.
Definition at line 31 of file NeighborListDB.h.
Member Typedef Documentation
typedef list<NeighborList*> NeighborListDB::ndb private
Definition at line 33 of file NeighborListDB.h.
Constructor & Destructor Documentation
NeighborListDB::NeighborListDB (const NeighborListDB & rhs) delete
Copying is not allowed.
NeighborListDB::NeighborListDB () inline private
Definition at line 66 of file NeighborListDB.h.
Referenced by instance().
Member Function Documentation
void NeighborListDB::addNeighbor (Neighbor * n) inline
Add a neighbor to the db. adds to all possible lists.
Definition at line 60 of file NeighborListDB.h.
Referenced by BoundaryElement::BoundaryElement(), and Cylinder::Cylinder().
void NeighborListDB::addNeighborList (NeighborList * n) inline
Add a cylinder neighbor list.
Definition at line 51 of file NeighborListDB.h.
Referenced by BoundaryElementNLContainer::BoundaryElementNLContainer(), and CylinderNLContainer::CylinderNLContainer().
NeighborListDB * NeighborListDB::instance () static
Get instance.
Definition at line 18 of file NeighborListDB.cpp.
References _instance, and NeighborListDB().
Referenced by BoundaryElement::BoundaryElement(), BoundaryElementNLContainer::BoundaryElementNLContainer(), Cylinder::Cylinder(), CylinderNLContainer::CylinderNLContainer(), Controller::updateSystem(), BoundaryElement::~BoundaryElement(), BoundaryElementNLContainer::~BoundaryElementNLContainer(), Cylinder::~Cylinder(), and CylinderNLContainer::~CylinderNLContainer().
NeighborListDB& NeighborListDB::operator= (NeighborListDB & rhs) delete
Assignment is not allowed.
void NeighborListDB::removeNeighbor (Neighbor * n) inline
Remove a neighbor from the db. removes from all possible lists.
Definition at line 62 of file NeighborListDB.h.
Referenced by BoundaryElement::~BoundaryElement(), and Cylinder::~Cylinder().
void NeighborListDB::removeNeighborList (NeighborList * n) inline
Remove a neighborlist.
Definition at line 54 of file NeighborListDB.h.
Referenced by BoundaryElementNLContainer::~BoundaryElementNLContainer(), and CylinderNLContainer::~CylinderNLContainer().
void NeighborListDB::resetAll () inline
Reset all neighbors lists.
Definition at line 57 of file NeighborListDB.h.
Referenced by Controller::updateSystem().
Member Data Documentation
NeighborListDB * NeighborListDB::_instance = 0 static private
Singleton instance.
Definition at line 65 of file NeighborListDB.h.
Referenced by instance().
T std::list< T >::elements inherited
STL member.
The documentation for this class was generated from the following files:
M3SYM/Structure/NeighborListDB.h
M3SYM/Structure/NeighborListDB.cpp