MEDYAN: BoundarySpherical Class Reference
BoundarySpherical Class Reference
A spherical Boundary implementation.
#include <BoundaryImpl.h>
Public Member Functions
BoundarySpherical (SubSystem *s, double diameter, BoundaryMove move)
Default constructor, will create an sphere with given diameter.
virtual bool within (Compartment *C)
virtual bool within (const vector< double > &coordinates)
Check if coordinates are within boundary.
virtual double distance (const vector< double > &coordinates)
Get the distance from the boundary.
virtual void move (double dist)
virtual vector< double > normal (vector< double > &coordinate)
Returns the normal inward at this coordinate.
BoundaryShape getShape ()
Get shape of this boundary.
const vector< unique_ptr< BoundarySurface > > & getBoundarySurfaces ()
Get boundary surfaces.
Protected Attributes
SubSystem * _subSystem
SubSystem ptr.
vector< unique_ptr< BoundarySurface > > _boundarySurfaces
Vector of boundarysurfaces (could be different implementations)
BoundaryShape _shape
Shape of boundary.
BoundaryMove _move
Movement of boundary.
short _nDim
Dimensionality.
Detailed Description
A spherical Boundary implementation.
Definition at line 47 of file BoundaryImpl.h.
Constructor & Destructor Documentation
BoundarySpherical()
BoundarySpherical::BoundarySpherical (SubSystem * s, double diameter, BoundaryMove move)
Default constructor, will create an sphere with given diameter.
Parameters
diameter - diameter of sphere
Definition at line 186 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces, GController::getSize(), and Sphere.
Member Function Documentation
distance()
double BoundarySpherical::distance (const vector< double > & coordinates) virtual
Get the distance from the boundary.
Returns the distance from closest boundary element in the boundary. Will return infinity if outside of the boundary.
Implements Boundary.
Definition at line 235 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces.
Referenced by SphereBoundaryElement::stretchedDistance().
getBoundarySurfaces()
const vector<unique_ptr<BoundarySurface> >& Boundary::getBoundarySurfaces () inline inherited
Get boundary surfaces.
Definition at line 59 of file Boundary.h.
getShape()
BoundaryShape Boundary::getShape () inline inherited
Get shape of this boundary.
Definition at line 56 of file Boundary.h.
move()
virtual void BoundarySpherical::move (double dist) inline virtual
Note
- not yet implemented.
Implements Boundary.
Definition at line 62 of file BoundaryImpl.h.
References BoundaryCubic::normal().
normal()
vector< double > BoundarySpherical::normal (vector< double > & coordinate) virtual
Returns the normal inward at this coordinate.
Implements Boundary.
Definition at line 246 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces.
Referenced by within().
within() [1/2]
bool BoundarySpherical::within (Compartment * C) virtual
Note
- not yet implemented correctly. Essentially checks if the midpoint of the compartment is within the boundary.
Implements Boundary.
Definition at line 198 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces, GeoParams::compartmentSizeX, GeoParams::compartmentSizeY, GeoParams::compartmentSizeZ, Compartment::coordinates(), SysParams::Geometry(), and normal().
within() [2/2]
bool BoundarySpherical::within (const vector< double > & coordinates) virtual
Check if coordinates are within boundary.
Implements Boundary.
Definition at line 226 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces.
Member Data Documentation
_boundarySurfaces
vector<unique_ptr<BoundarySurface> > Boundary::_boundarySurfaces protected inherited
Vector of boundarysurfaces (could be different implementations)
Definition at line 42 of file Boundary.h.
Referenced by BoundaryCapsule::BoundaryCapsule(), BoundaryCubic::BoundaryCubic(), BoundarySpherical(), BoundaryCubic::distance(), distance(), BoundaryCapsule::distance(), BoundaryCubic::move(), BoundaryCubic::normal(), normal(), BoundaryCubic::within(), within(), and BoundaryCapsule::within().
_move
BoundaryMove Boundary::_move protected inherited
Movement of boundary.
Definition at line 45 of file Boundary.h.
Referenced by BoundaryCubic::move().
_nDim
short Boundary::_nDim protected inherited
Dimensionality.
Definition at line 47 of file Boundary.h.
_shape
BoundaryShape Boundary::_shape protected inherited
Shape of boundary.
Definition at line 44 of file Boundary.h.
_subSystem
SubSystem* Boundary::_subSystem protected inherited
SubSystem ptr.
Definition at line 39 of file Boundary.h.
The documentation for this class was generated from the following files:
src/Structure/BoundaryImpl.h
src/Structure/BoundaryImpl.cpp