MEDYAN: Bead Class Reference
Bead Class Reference
Represents a single coordinate between Cylinders, and holds forces needed for mechanical equilibration.
#include <Bead.h>
Public Member Functions
Bead (vector< double > v, Composite *parent, int position)
Main constructor.
Bead (Composite *parent, int position)
Default constructor.
Compartment * getCompartment ()
Get Compartment.
int getPosition ()
Get position.
float getBirthTime ()
Get the birth time.
void addAsPinned ()
Add this bead as a pinned bead.
void removeAsPinned ()
Remove this bead as pinned.
bool isPinned ()
virtual void updatePosition ()
Update the position, inherited from Movable.
virtual void printSelf ()
Prints information about this node. Useful for debugging.
virtual int getType ()
Return the type of this element as an integer index.
int getID ()
bool getstaticstate ()
void setstaticstate (bool index)
double getLoadForcesP ()
Helper functions for load forces.
void printLoadForcesP ()
double getLoadForcesM ()
void printLoadForcesM ()
virtual bool apply (Visitor &v)
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
virtual bool apply (SpeciesVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual size_t numberOfChildren () const
Returns the number of children of this node.
virtual bool isComposite () const
Returns true if this node is a Composite node.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
virtual size_t numberOfSpecies () const
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t numberOfReactions () const
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual string getFullName () const
Return a string indicating the full name of this node (presumably used mainly for debugging)
virtual size_t countDescendents () const
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const
Return the number of Species contained under this node's hieararchy.
virtual size_t countReactions () const
Return the number of ReactionBase objects contained under this node's hieararchy.
virtual void addToSubSystem ()
SubSystem management, inherited from Trackable.
virtual void removeFromSubSystem ()
SubSystem management, inherited from Trackable.
double FDotF ()
Auxiliary method for CG minimization.
double FDotFA ()
Auxiliary method for CG minimization.
double FADotFA ()
Auxiliary method for CG minimization.
double FADotFAP ()
Auxiliary method for CG minimization.
Static Public Member Functions
static const vector< Bead * > & getBeads ()
Get all instances of this class from the SubSystem.
static const vector< Bead * > & getPinnedBeads ()
Get all pinned beads from subsystem.
static int numBeads ()
Get the number of beads in this system.
Public Attributes
vector< double > coordinate
Coordinates of the bead.
vector< double > coordinateP
Prev coordinates of bead in CG minimization.
vector< double > coordinateB
Prev coordinate of bead before CG minimization.
int _ID
Bead IDs.
vector< double > force
Forces based on curent coordinates.
vector< double > forceAux
An auxiliary field needed during CG minimization.
vector< double > forceAuxP
An auxiliary field needed during CG minimization.
vector< double > loadForcesP
vector< double > loadForcesM
The force on this bead due to an external load This is not a vector (x,y,z) value, but a list of force magnitudes in the direction of polymerization with monomer increments (future values).
short lfip = 0
short lfim = 0
Index which saves which load force to use.
vector< double > pinnedPosition
The bead can be pinned to a certain position in the simulation volume.
bool isStatic = false
Protected Attributes
bool _movable
Object type.
bool _reactable
Object type.
bool _dneighbor
Object type.
bool _neighbor
Object type.
Static Protected Attributes
static SubSystem * _subSystem = 0
A subsystem pointer for every trackable.
Private Attributes
Compartment * _compartment = nullptr
Pointer to the compartment that this bead is in.
int _position
Position on structure.
float _birthTime
Time of birth.
bool _isPinned = false
Static Private Attributes
static Database< Bead * > _beads
Collection of beads in SubSystem.
static Database< Bead * > _pinnedBeads
Collection of pinned beads in SubSystem (attached to some element in SubSystem)
Detailed Description
Represents a single coordinate between Cylinders, and holds forces needed for mechanical equilibration.
Beads are the "hinges" between Cylinders. In the minimization algorithms, beads are moved corresponding to external forces, for example, Filament stretching and bending. The bead class contains currernt coordinates and forces, and has functions to calculate dot products for the minimization algorithms.
Extending the Movable class, the positions of all instances can be updated by the SubSystem.
Extending the DynamicNeighbor class, all instances can be kept in NeighborLists.
Definition at line 49 of file Bead.h.
Constructor & Destructor Documentation
Bead() [1/2]
Bead::Bead (vector< double > v, Composite * parent, int position)
Main constructor.
Definition at line 28 of file Bead.cpp.
References _compartment, Composite::addChild(), GeoParams::cylinderNumMon, SysParams::Geometry(), GController::getCompartment(), Component::getParent(), getType(), loadForcesM, loadForcesP, Component::printSelf(), and printSelf().
Bead() [2/2]
Bead::Bead (Composite * parent, int position)
Default constructor.
Definition at line 56 of file Bead.cpp.
References Composite::addChild().
Member Function Documentation
addAsPinned()
void Bead::addAsPinned () inline
Add this bead as a pinned bead.
Definition at line 112 of file Bead.h.
References _isPinned, _pinnedBeads, and Database< T >::addElement().
addToSubSystem()
virtual void Bead::addToSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 99 of file Bead.h.
Referenced by getBirthTime().
apply() [1/3]
bool Component::apply (Visitor & v) virtual inherited
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
However, the ConditionalVisitor allows the visit() function to be applied only selectively to nodes that conform to specific criteria.
Reimplemented in Composite.
Definition at line 26 of file Component.cpp.
References Visitor::visit().
Referenced by Component::~Component().
apply() [2/3]
virtual bool Component::apply (SpeciesVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented in Composite.
Definition at line 61 of file Component.h.
References Component::apply_impl().
apply() [3/3]
virtual bool Component::apply (ReactionVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented in Composite.
Definition at line 69 of file Component.h.
References Component::apply_impl().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
countDescendents()
virtual size_t Component::countDescendents () const inline virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 118 of file Component.h.
countReactions()
virtual size_t Component::countReactions () const inline virtual inherited
Return the number of ReactionBase objects contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 126 of file Component.h.
References Component::getType(), and Component::printSelf().
countSpecies()
virtual size_t Component::countSpecies () const inline virtual inherited
Return the number of Species contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 122 of file Component.h.
Referenced by Linker::getLifetimes(), MotorGhost::getWalkLengths(), BranchingPoint::numBranchingPoints(), and Chemistry::print().
FADotFA()
double Bead::FADotFA () inline
Auxiliary method for CG minimization.
Definition at line 165 of file Bead.h.
Referenced by CGMethod::maxBead().
FADotFAP()
double Bead::FADotFAP () inline
Auxiliary method for CG minimization.
Definition at line 171 of file Bead.h.
References getLoadForcesP().
FDotF()
double Bead::FDotF () inline
Auxiliary method for CG minimization.
Definition at line 154 of file Bead.h.
Referenced by setstaticstate().
FDotFA()
double Bead::FDotFA () inline
Auxiliary method for CG minimization.
Definition at line 159 of file Bead.h.
getBeads()
static const vector<Bead*>& Bead::getBeads () inline static
Get all instances of this class from the SubSystem.
Definition at line 107 of file Bead.h.
References _beads, and Database< T >::getElements().
Referenced by CGMethod::allFADotFA(), CGMethod::allFADotFAP(), CGMethod::allFDotF(), CGMethod::allFDotFA(), ForceFieldManager::computeForces(), ForceFieldManager::computeForcesAuxP(), ForceFieldManager::computeLoadForces(), CGMethod::maxBead(), CGMethod::maxF(), CGMethod::moveBeads(), Controller::pinBoundaryFilaments(), CGMethod::printForces(), CGMethod::resetBeads(), ForceFieldManager::resetForces(), ForceFieldManager::resetForcesAux(), CGMethod::setBeads(), Restart::settorestartphase(), CGMethod::shiftGradient(), and CGMethod::startMinimization().
getBirthTime()
float Bead::getBirthTime () inline
Get the birth time.
Definition at line 95 of file Bead.h.
References _beads, _birthTime, Database< T >::addElement(), and addToSubSystem().
getCompartment()
Compartment* Bead::getCompartment () inline
Get Compartment.
Definition at line 89 of file Bead.h.
References _compartment.
getFullName()
virtual string Component::getFullName () const inline virtual inherited
Return a string indicating the full name of this node (presumably used mainly for debugging)
Reimplemented in Compartment, CompartmentGrid, and Composite.
Definition at line 114 of file Component.h.
getID()
int Bead::getID () inline
Definition at line 147 of file Bead.h.
References _ID.
getLoadForcesM()
double Bead::getLoadForcesM ()
Definition at line 111 of file Bead.cpp.
References GeoParams::cylinderNumMon, SysParams::Geometry(), getType(), lfim, and loadForcesM.
Referenced by printLoadForcesP(), and Cylinder::updatePosition().
getLoadForcesP()
double Bead::getLoadForcesP ()
Helper functions for load forces.
Definition at line 100 of file Bead.cpp.
References GeoParams::cylinderNumMon, SysParams::Geometry(), getType(), lfip, and loadForcesP.
Referenced by FADotFAP(), and Cylinder::updatePosition().
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead(), Component::getRoot(), getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getPinnedBeads()
static const vector<Bead*>& Bead::getPinnedBeads () inline static
Get all pinned beads from subsystem.
Definition at line 127 of file Bead.h.
References _pinnedBeads, and Database< T >::getElements().
Referenced by BoundaryCylinderAttachment< BAttachmentInteractionType >::computeEnergy(), BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForces(), BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForcesAux(), and Controller::pinBoundaryFilaments().
getPosition()
int Bead::getPosition () inline
Get position.
Definition at line 92 of file Bead.h.
References _position.
Referenced by BranchingDihedral< BDihedralInteractionType >::computeEnergy(), BranchingPosition< BStretchingInteractionType >::computeEnergy(), BranchingStretching< BStretchingInteractionType >::computeEnergy(), BranchingDihedral< BDihedralInteractionType >::computeForces(), BranchingStretching< BStretchingInteractionType >::computeForces(), BranchingPosition< BStretchingInteractionType >::computeForces(), BranchingDihedral< BDihedralInteractionType >::computeForcesAux(), BranchingStretching< BStretchingInteractionType >::computeForcesAux(), BranchingPosition< BStretchingInteractionType >::computeForcesAux(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), and Filament::retractMinusEnd().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getstaticstate()
bool Bead::getstaticstate () inline
Definition at line 149 of file Bead.h.
References isStatic.
getType()
virtual int Bead::getType () inline virtual
Return the type of this element as an integer index.
Implements Component.
Definition at line 145 of file Bead.h.
References Component::getParent(), and Component::getType().
Referenced by Bead(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), getLoadForcesM(), and getLoadForcesP().
isComposite()
virtual bool Component::isComposite () const inline virtual inherited
Returns true if this node is a Composite node.
Reimplemented in Composite.
Definition at line 95 of file Component.h.
isPinned()
bool Bead::isPinned () inline
Definition at line 132 of file Bead.h.
References _isPinned.
Referenced by WallTensions::print().
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
numBeads()
static int Bead::numBeads () inline static
Get the number of beads in this system.
Definition at line 135 of file Bead.h.
References _beads, Database< T >::countElements(), printSelf(), and updatePosition().
Referenced by FletcherRieves::minimize(), SteepestDescent::minimize(), and PolakRibiere::minimize().
numberOfChildren()
virtual size_t Component::numberOfChildren () const inline virtual inherited
Returns the number of children of this node.
Note
Species and ReactionBase objects are not counted.
Reimplemented in Composite.
Definition at line 92 of file Component.h.
numberOfReactions()
virtual size_t Component::numberOfReactions () const inline virtual inherited
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 110 of file Component.h.
numberOfSpecies()
virtual size_t Component::numberOfSpecies () const inline virtual inherited
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 106 of file Component.h.
printLoadForcesM()
void Bead::printLoadForcesM () inline
Definition at line 196 of file Bead.h.
printLoadForcesP()
void Bead::printLoadForcesP () inline
Definition at line 182 of file Bead.h.
References getLoadForcesM().
printSelf()
void Bead::printSelf () virtual
Prints information about this node. Useful for debugging.
Implements Component.
Definition at line 83 of file Bead.cpp.
References _birthTime, _position, coordinate, coordinateB, coordinateP, force, and forceAux.
Referenced by Bead(), numBeads(), Bubble::printSelf(), updatePosition(), and Cylinder::updatePosition().
removeAsPinned()
void Bead::removeAsPinned () inline
Remove this bead as pinned.
Will remove from pinnedBeads DB
Note
- only usually called upon the destruction of a Bead.
Definition at line 119 of file Bead.h.
References _isPinned, _pinnedBeads, and Database< T >::removeElement().
Referenced by removeFromSubSystem().
removeFromSubSystem()
virtual void Bead::removeFromSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 100 of file Bead.h.
References _beads, _isPinned, removeAsPinned(), and Database< T >::removeElement().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
setstaticstate()
void Bead::setstaticstate (bool index) inline
Definition at line 151 of file Bead.h.
References FDotF().
updatePosition()
void Bead::updatePosition () virtual
Update the position, inherited from Movable.
Implements Movable.
Definition at line 65 of file Bead.cpp.
References coordinate, GController::getCompartment(), Component::getParent(), Component::printSelf(), and printSelf().
Referenced by numBeads().
Member Data Documentation
_beads
Database< Bead * > Bead::_beads static private
Collection of beads in SubSystem.
Definition at line 216 of file Bead.h.
Referenced by getBeads(), getBirthTime(), numBeads(), and removeFromSubSystem().
_birthTime
float Bead::_birthTime private
Time of birth.
Definition at line 212 of file Bead.h.
Referenced by getBirthTime(), and printSelf().
_compartment
Compartment* Bead::_compartment = nullptr private
Pointer to the compartment that this bead is in.
Definition at line 209 of file Bead.h.
Referenced by Bead(), and getCompartment().
_dneighbor
bool Trackable::_dneighbor protected inherited
Object type.
Definition at line 54 of file Trackable.h.
_ID
int Bead::_ID
Bead IDs.
Definition at line 57 of file Bead.h.
Referenced by getID().
_isPinned
bool Bead::_isPinned = false private
Definition at line 214 of file Bead.h.
Referenced by addAsPinned(), isPinned(), removeAsPinned(), and removeFromSubSystem().
_movable
bool Trackable::_movable protected inherited
Object type.
Definition at line 52 of file Trackable.h.
_neighbor
bool Trackable::_neighbor protected inherited
Object type.
Definition at line 55 of file Trackable.h.
_pinnedBeads
Database< Bead * > Bead::_pinnedBeads static private
Collection of pinned beads in SubSystem (attached to some element in SubSystem)
Definition at line 217 of file Bead.h.
Referenced by addAsPinned(), getPinnedBeads(), and removeAsPinned().
_position
int Bead::_position private
Position on structure.
Definition at line 211 of file Bead.h.
Referenced by getPosition(), and printSelf().
_reactable
bool Trackable::_reactable protected inherited
Object type.
Definition at line 53 of file Trackable.h.
_subSystem
SubSystem * Trackable::_subSystem = 0 static protected inherited
A subsystem pointer for every trackable.
Definition at line 46 of file Trackable.h.
Referenced by Controller::Controller(), and BranchingPoint::~BranchingPoint().
coordinate
vector<double> Bead::coordinate
Coordinates of the bead.
Note
- all vectors are in x,y,z coordinates.
Definition at line 54 of file Bead.h.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForces(), BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), Cylinder::Cylinder(), Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), BranchingDihedralCosine::energy(), MTOCAttachmentHarmonic::energy(), FilamentBendingCosine::energy(), BranchingPositionCosine::energy(), FilamentBendingHarmonic::energy(), FilamentStretchingHarmonic::energy(), LinkerStretchingHarmonic::energy(), MotorGhostStretchingHarmonic::energy(), BranchingBendingCosine::energy(), BranchingStretchingHarmonic::energy(), CylinderExclVolRepulsion::energy(), BubbleBubbleRepulsionExp::energy(), BoundaryCylinderAttachmentHarmonic::energy(), BubbleCylinderRepulsionExp::energy(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), MTOCAttachmentHarmonic::forces(), BranchingDihedralCosine::forces(), FilamentBendingCosine::forces(), FilamentBendingHarmonic::forces(), BranchingPositionCosine::forces(), FilamentStretchingHarmonic::forces(), BranchingBendingCosine::forces(), CylinderExclVolRepulsion::forces(), BoundaryCylinderAttachmentHarmonic::forces(), BubbleCylinderRepulsionExp::forces(), BranchingStretchingHarmonic::forces(), BubbleBubbleRepulsionExp::forces(), LinkerStretchingHarmonic::forces(), MotorGhostStretchingHarmonic::forces(), FilamentBendingCosine::forcesAux(), BranchingBendingCosine::forcesAux(), MTOCAttachmentHarmonic::forcesAux(), BranchingDihedralCosine::forcesAux(), FilamentBendingHarmonic::forcesAux(), BranchingPositionCosine::forcesAux(), FilamentStretchingHarmonic::forcesAux(), CylinderExclVolRepulsion::forcesAux(), BubbleCylinderRepulsionExp::forcesAux(), BoundaryCylinderAttachmentHarmonic::forcesAux(), BubbleBubbleRepulsionExp::forcesAux(), BranchingStretchingHarmonic::forcesAux(), LinkerStretchingHarmonic::forcesAux(), MotorGhostStretchingHarmonic::forcesAux(), Linker::Linker(), BubbleCylinderRepulsionExp::loadForces(), MotorGhost::MotorGhost(), Filament::polymerizeMinusEnd(), Filament::polymerizePlusEnd(), WallTensions::print(), printSelf(), Filament::sever(), Bubble::updatePosition(), updatePosition(), Linker::updatePosition(), Cylinder::updatePosition(), MotorGhost::updatePosition(), MotorGhost::updateReactionRates(), and BranchingPoint::~BranchingPoint().
coordinateB
vector<double> Bead::coordinateB
Prev coordinate of bead before CG minimization.
Definition at line 56 of file Bead.h.
Referenced by printSelf().
coordinateP
vector<double> Bead::coordinateP
Prev coordinates of bead in CG minimization.
Definition at line 55 of file Bead.h.
Referenced by printSelf().
force
vector<double> Bead::force
Forces based on curent coordinates.
Forces should always correspond to current coordinates.
Definition at line 58 of file Bead.h.
Referenced by BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeEnergy(), BranchingDihedralCosine::energy(), BranchingPositionCosine::energy(), MTOCAttachmentHarmonic::energy(), FilamentBendingCosine::energy(), BranchingBendingCosine::energy(), FilamentBendingHarmonic::energy(), FilamentStretchingHarmonic::energy(), CylinderExclVolRepulsion::energy(), BranchingStretchingHarmonic::energy(), LinkerStretchingHarmonic::energy(), MotorGhostStretchingHarmonic::energy(), BubbleBubbleRepulsionExp::energy(), BubbleCylinderRepulsionExp::energy(), BoundaryCylinderAttachmentHarmonic::energy(), BranchingPositionCosine::forces(), BranchingBendingCosine::forces(), MTOCAttachmentHarmonic::forces(), BranchingDihedralCosine::forces(), FilamentStretchingHarmonic::forces(), FilamentBendingCosine::forces(), FilamentBendingHarmonic::forces(), CylinderExclVolRepulsion::forces(), BoundaryBubbleRepulsionExp::forces(), BoundaryCylinderRepulsionExp::forces(), BoundaryCylinderAttachmentHarmonic::forces(), BubbleBubbleRepulsionExp::forces(), BubbleCylinderRepulsionExp::forces(), BranchingStretchingHarmonic::forces(), MotorGhostStretchingHarmonic::forces(), LinkerStretchingHarmonic::forces(), BubbleBubbleRepulsionExp::forcesAux(), BubbleCylinderRepulsionExp::forcesAux(), and printSelf().
forceAux
vector<double> Bead::forceAux
An auxiliary field needed during CG minimization.
Definition at line 60 of file Bead.h.
Referenced by BranchingBendingCosine::forcesAux(), BranchingDihedralCosine::forcesAux(), MTOCAttachmentHarmonic::forcesAux(), FilamentBendingCosine::forcesAux(), FilamentBendingHarmonic::forcesAux(), FilamentStretchingHarmonic::forcesAux(), BranchingPositionCosine::forcesAux(), BoundaryBubbleRepulsionExp::forcesAux(), BoundaryCylinderRepulsionExp::forcesAux(), CylinderExclVolRepulsion::forcesAux(), BoundaryCylinderAttachmentHarmonic::forcesAux(), BranchingStretchingHarmonic::forcesAux(), MotorGhostStretchingHarmonic::forcesAux(), LinkerStretchingHarmonic::forcesAux(), and printSelf().
forceAuxP
vector<double> Bead::forceAuxP
An auxiliary field needed during CG minimization.
Definition at line 61 of file Bead.h.
isStatic
bool Bead::isStatic = false
Definition at line 80 of file Bead.h.
Referenced by getstaticstate().
lfim
short Bead::lfim = 0
Index which saves which load force to use.
Definition at line 73 of file Bead.h.
Referenced by BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), Filament::depolymerizeMinusEnd(), Filament::extendMinusEnd(), getLoadForcesM(), Filament::polymerizeMinusEnd(), and Filament::retractMinusEnd().
lfip
short Bead::lfip = 0
Definition at line 72 of file Bead.h.
Referenced by BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), Filament::depolymerizePlusEnd(), Filament::extendPlusEnd(), getLoadForcesP(), Filament::polymerizePlusEnd(), and Filament::retractPlusEnd().
loadForcesM
vector<double> Bead::loadForcesM
The force on this bead due to an external load This is not a vector (x,y,z) value, but a list of force magnitudes in the direction of polymerization with monomer increments (future values).
These are then used to propagate load forces in between mechanical force calculations.
Definition at line 64 of file Bead.h.
Referenced by Bead(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), Filament::extendMinusEnd(), getLoadForcesM(), and Filament::retractMinusEnd().
loadForcesP
vector<double> Bead::loadForcesP
Definition at line 63 of file Bead.h.
Referenced by Bead(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), Filament::extendPlusEnd(), getLoadForcesP(), and Filament::retractPlusEnd().
pinnedPosition
vector<double> Bead::pinnedPosition
The bead can be pinned to a certain position in the simulation volume.
These parameters describe the pinning. Adding the Bead to the list of pinned Beads is done by a corresponding special protocol. (see executeSpecialProtocols() in Controller)
Definition at line 78 of file Bead.h.
Referenced by BoundaryCylinderAttachmentHarmonic::energy(), BoundaryCylinderAttachmentHarmonic::forces(), BoundaryCylinderAttachmentHarmonic::forcesAux(), and WallTensions::print().
The documentation for this class was generated from the following files:
src/Structure/Bead.h
src/Structure/Bead.cpp