M3Sym: BoundaryElementNLContainer Class Reference
BoundaryElementNLContainer Class Reference
Holds a BoundaryElementNeighborList.
#include <NeighborListContainer.h>
Public Member Functions
BoundaryElementNLContainer (float rMax=0.0, float rMin=0.0)
Constructor, adds a cylinder neighbor list to the database.
~BoundaryElementNLContainer ()
Destructor, removes boundary element neighbor list from the database.
BoundaryElementNeighborList * getNeighborList ()
Get neighbor list.
Private Attributes
BoundaryElementNeighborList * _neighborList
Detailed Description
Holds a BoundaryElementNeighborList.
Definition at line 46 of file NeighborListContainer.h.
Constructor & Destructor Documentation
BoundaryElementNLContainer::BoundaryElementNLContainer (float rMax = 0.0, float rMin = 0.0) inline
Constructor, adds a cylinder neighbor list to the database.
Definition at line 53 of file NeighborListContainer.h.
References _neighborList, NeighborListDB::addNeighborList(), and NeighborListDB::instance().
BoundaryElementNLContainer::~BoundaryElementNLContainer () inline
Destructor, removes boundary element neighbor list from the database.
Definition at line 59 of file NeighborListContainer.h.
References _neighborList, NeighborListDB::instance(), and NeighborListDB::removeNeighborList().
Member Function Documentation
BoundaryElementNeighborList* BoundaryElementNLContainer::getNeighborList () inline
Get neighbor list.
Definition at line 65 of file NeighborListContainer.h.
References _neighborList.
Member Data Documentation
BoundaryElementNeighborList* BoundaryElementNLContainer::_neighborList private
Definition at line 49 of file NeighborListContainer.h.
Referenced by BoundaryElementNLContainer(), getNeighborList(), and ~BoundaryElementNLContainer().
The documentation for this class was generated from the following file:
M3SYM/Structure/NeighborListContainer.h