M3Sym: FilamentDB Class Reference
FilamentDB Class Reference
A database for all Filaments in the system.
#include <FilamentDB.h>
Public Member Functions
FilamentDB (const FilamentDB &rhs)=delete
Copying is not allowed.
FilamentDB & operator= (FilamentDB &rhs)=delete
Assignment is not allowed.
void addFilament (Filament *f)
Add a filament.
void removeFilament (Filament *f)
Remove a filament.
int getFilamentID ()
Get current filament ID, and update the ID counter.
Static Public Member Functions
static FilamentDB * instance ()
Get singleton instance.
Private Types
typedef list< Filament * > fdb
Private Member Functions
FilamentDB ()
Private Attributes
T elements
STL member.
Static Private Attributes
static int _currentFilamentID = 0
To assign filament ids.
static FilamentDB * _instance = 0
Singleton instance.
Detailed Description
A database for all Filaments in the system.
This FilamentDB inherits from list and manage all creations and removing of Filaments objects, as well as some standard list functions and iterators.
Definition at line 29 of file FilamentDB.h.
Member Typedef Documentation
typedef list<Filament*> FilamentDB::fdb private
Definition at line 30 of file FilamentDB.h.
Constructor & Destructor Documentation
FilamentDB::FilamentDB (const FilamentDB & rhs) delete
Copying is not allowed.
FilamentDB::FilamentDB () inline private
Definition at line 58 of file FilamentDB.h.
Referenced by instance().
Member Function Documentation
void FilamentDB::addFilament (Filament * f) inline
Add a filament.
Definition at line 47 of file FilamentDB.h.
Referenced by Filament::Filament().
int FilamentDB::getFilamentID () inline
Get current filament ID, and update the ID counter.
Definition at line 52 of file FilamentDB.h.
References _currentFilamentID.
Referenced by Filament::Filament().
FilamentDB * FilamentDB::instance () static
Get singleton instance.
Definition at line 19 of file FilamentDB.cpp.
References _instance, and FilamentDB().
Referenced by FilamentFF::computeEnergy(), FilamentFF::computeForces(), FilamentFF::computeForcesAux(), Filament::Filament(), Output::printBasicSnapshot(), Output::printBirthTimes(), Output::printForces(), Output::printSnapshot(), and Controller::updateSystem().
FilamentDB& FilamentDB::operator= (FilamentDB & rhs) delete
Assignment is not allowed.
void FilamentDB::removeFilament (Filament * f) inline
Remove a filament.
Definition at line 49 of file FilamentDB.h.
Member Data Documentation
int FilamentDB::_currentFilamentID = 0 static private
To assign filament ids.
Definition at line 55 of file FilamentDB.h.
Referenced by getFilamentID().
FilamentDB * FilamentDB::_instance = 0 static private
Singleton instance.
Definition at line 57 of file FilamentDB.h.
Referenced by instance().
T std::list< T >::elements inherited
STL member.
The documentation for this class was generated from the following files:
M3SYM/Structure/FilamentDB.h
M3SYM/Structure/FilamentDB.cpp