M3Sym: MotorGhostStretching< MStretchingInteractionType > Class Template Reference
MotorGhostStretching< MStretchingInteractionType > Class Template Reference
Represents a MotorGhost stretching interaction.
#include <MotorGhostStretching.h>
Public Member Functions
virtual double computeEnergy (MotorGhost *, double d)
Template specializations.
virtual void computeForces (MotorGhost *)
Compute the forces of this interaction.
virtual void computeForcesAux (MotorGhost *)
Compute the auxiliary forces of this interaction.
const string & getName ()
Get name of this interaction.
Private Attributes
MStretchingInteractionType _FFType
Detailed Description
template<class MStretchingInteractionType>
class MotorGhostStretching< MStretchingInteractionType >
Represents a MotorGhost stretching interaction.
Definition at line 26 of file MotorGhostStretching.h.
Member Function Documentation
template<class MStretchingInteractionType > template double MotorGhostStretching< MStretchingInteractionType >::computeEnergy (MotorGhost * , double d) virtual
Template specializations.
Implements MotorGhostInteractions.
Definition at line 23 of file MotorGhostStretching.cpp.
References MMotorGhost::getEqLength(), Cylinder::getFirstBead(), MotorGhost::getFirstCylinder(), MotorGhost::getFirstPosition(), MotorGhost::getMMotorGhost(), Cylinder::getSecondBead(), MotorGhost::getSecondCylinder(), MotorGhost::getSecondPosition(), and MMotorGhost::getStretchingConstant().
template<class MStretchingInteractionType > template void MotorGhostStretching< MStretchingInteractionType >::computeForces (MotorGhost *) virtual
Compute the forces of this interaction.
Implements MotorGhostInteractions.
Definition at line 43 of file MotorGhostStretching.cpp.
References MMotorGhost::getEqLength(), Cylinder::getFirstBead(), MotorGhost::getFirstCylinder(), MotorGhost::getFirstPosition(), MotorGhost::getMMotorGhost(), Cylinder::getSecondBead(), MotorGhost::getSecondCylinder(), MotorGhost::getSecondPosition(), and MMotorGhost::getStretchingConstant().
template<class MStretchingInteractionType > template void MotorGhostStretching< MStretchingInteractionType >::computeForcesAux (MotorGhost *) virtual
Compute the auxiliary forces of this interaction.
Implements MotorGhostInteractions.
Definition at line 61 of file MotorGhostStretching.cpp.
References MMotorGhost::getEqLength(), Cylinder::getFirstBead(), MotorGhost::getFirstCylinder(), MotorGhost::getFirstPosition(), MotorGhost::getMMotorGhost(), Cylinder::getSecondBead(), MotorGhost::getSecondCylinder(), MotorGhost::getSecondPosition(), and MMotorGhost::getStretchingConstant().
const string& MotorGhostInteractions::getName () inline inherited
Get name of this interaction.
Definition at line 37 of file MotorGhostInteractions.h.
References MotorGhostInteractions::_name.
Member Data Documentation
template<class MStretchingInteractionType > MStretchingInteractionType MotorGhostStretching< MStretchingInteractionType >::_FFType private
Definition at line 29 of file MotorGhostStretching.h.
The documentation for this class was generated from the following files:
M3SYM/Mechanics/ForceField/MotorGhostStretching.h
M3SYM/Mechanics/ForceField/MotorGhostStretching.cpp