M3Sym: SpeciesVisitorLambda Class Reference
SpeciesVisitorLambda Class Reference
Allows using C++11 lambda expressions to set the action to be performed on each Species of the node and its descendent nodes.
#include <Visitor.h>
Public Member Functions
void setLambda (std::function< bool(Species *)> g)
Sets the action to be perfomed on each node as std::function<bool (Component*)> g.
void setLambdaPred (std::function< bool(Species *)> pred)
Sets the predicate which checks whether the node should be evaluated as std::function<bool (Component*)> g.
bool visit (Species *s)
When this Visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(s), for each of the Species *s of that node.
Protected Member Functions
virtual bool visitImpl (Species *s) override
Implementation of the visit(...) method.
virtual bool predImpl (Species *s) override
Implementation of the pred(...) method.
Protected Attributes
std::function< bool(Species *)> _f
The function to be perfomed on each node.
std::function< bool(Species *)> _pred =[](Species *){return true;}
The predicate which checks whether the Species should be evaluated.
Detailed Description
Allows using C++11 lambda expressions to set the action to be performed on each Species of the node and its descendent nodes.
Definition at line 128 of file Visitor.h.
Member Function Documentation
virtual bool SpeciesVisitorLambda::predImpl (Species * s) inline override protected virtual
Implementation of the pred(...) method.
Reimplemented from SpeciesVisitor.
Definition at line 143 of file Visitor.h.
References _pred.
void SpeciesVisitorLambda::setLambda (std::function< bool(Species *)> g) inline
Sets the action to be perfomed on each node as std::function<bool (Component*)> g.
Definition at line 131 of file Visitor.h.
References _f.
Referenced by main().
void SpeciesVisitorLambda::setLambdaPred (std::function< bool(Species *)> pred) inline
Sets the predicate which checks whether the node should be evaluated as std::function<bool (Component*)> g.
Definition at line 134 of file Visitor.h.
References _pred.
Referenced by main().
bool SpeciesVisitor::visit (Species * s) inline inherited
When this Visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(s), for each of the Species *s of that node.
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Definition at line 108 of file Visitor.h.
References SpeciesVisitor::predImpl(), and SpeciesVisitor::visitImpl().
Referenced by Compartment::apply_impl().
virtual bool SpeciesVisitorLambda::visitImpl (Species * s) inline override protected virtual
Implementation of the visit(...) method.
Implements SpeciesVisitor.
Definition at line 140 of file Visitor.h.
References _f.
Member Data Documentation
std::function<bool (Species *)> SpeciesVisitorLambda::_f protected
The function to be perfomed on each node.
Definition at line 136 of file Visitor.h.
Referenced by setLambda(), and visitImpl().
std::function<bool (Species *)> SpeciesVisitorLambda::_pred =[](Species *){return true;} protected
The predicate which checks whether the Species should be evaluated.
Definition at line 137 of file Visitor.h.
Referenced by predImpl(), and setLambdaPred().
The documentation for this class was generated from the following file:
M3SYM/Visitor.h