MEDYAN: Histogram Class Reference
Histogram Class Reference
A class to hold frequency of occurences in a general set of data.
#include <Histogram.h>
Public Member Functions
Histogram (int numBins, double histMin=0, double histMax=0)
void addValue (double value)
Adds a value to the histogram by updating the correct bin.
void clearValues ()
Clears all values from histogram.
void print (ofstream &outputFile)
Print the histogram.
double getMin ()
double getMax ()
Private Attributes
int _numBins
Number of bins in histogram.
double _histMin
Minimum histogram value.
double _histMax
Maximum histogram value.
double _range
range of bin
vector< int > _frequencies
The histogram data.
Detailed Description
A class to hold frequency of occurences in a general set of data.
The Histogram class holds frequencies of events in certain ranges (bins). It contains functions to increment and store frequencies in a data structure.
Definition at line 30 of file Histogram.h.
Constructor & Destructor Documentation
Histogram()
Histogram::Histogram (int numBins, double histMin = 0, double histMax = 0) inline
Definition at line 43 of file Histogram.h.
References _histMin.
Member Function Documentation
addValue()
void Histogram::addValue (double value) inline
Adds a value to the histogram by updating the correct bin.
Definition at line 52 of file Histogram.h.
Referenced by Linker::~Linker(), and MotorGhost::~MotorGhost().
clearValues()
void Histogram::clearValues () inline
Clears all values from histogram.
Definition at line 61 of file Histogram.h.
Referenced by MotorLifetimes::print(), MotorWalkLengths::print(), and LinkerLifetimes::print().
getMax()
double Histogram::getMax () inline
Definition at line 80 of file Histogram.h.
References _histMax.
Referenced by Linker::~Linker(), and MotorGhost::~MotorGhost().
getMin()
double Histogram::getMin () inline
Definition at line 79 of file Histogram.h.
References _histMin.
Referenced by Linker::~Linker(), and MotorGhost::~MotorGhost().
print()
void Histogram::print (ofstream & outputFile) inline
Print the histogram.
Definition at line 66 of file Histogram.h.
References _range.
Referenced by MotorLifetimes::print(), MotorWalkLengths::print(), LinkerLifetimes::print(), and FilamentTurnoverTimes::print().
Member Data Documentation
_frequencies
vector<int> Histogram::_frequencies private
The histogram data.
Definition at line 40 of file Histogram.h.
_histMax
double Histogram::_histMax private
Maximum histogram value.
Definition at line 36 of file Histogram.h.
Referenced by getMax().
_histMin
double Histogram::_histMin private
Minimum histogram value.
Definition at line 35 of file Histogram.h.
Referenced by getMin(), and Histogram().
_numBins
int Histogram::_numBins private
Number of bins in histogram.
Definition at line 33 of file Histogram.h.
_range
double Histogram::_range private
range of bin
Definition at line 38 of file Histogram.h.
Referenced by print().
The documentation for this class was generated from the following file:
src/Histogram.h