M3Sym: Output Class Reference
Output Class Reference
To print a specified output into a file.
#include <Output.h>
Public Member Functions
Output (string outputFileName)
Constructor, which opens the output file.
~Output ()
Destructor, which closes the output file.
void printBasicSnapshot (int step)
Print basic information about filaments, linkers, motors (DEPRECATED)
void printSnapshot (int step)
New snapshot output.
void printBirthTimes (int step)
Print birth times of beads for each filament.
void printForces (int step)
Print forces on beads for each filament.
void printStresses (int step)
Print stresses on beads for each filament.
Private Attributes
ofstream _outputFile
The output file being used.
Detailed Description
To print a specified output into a file.
An output object, initialized by the Controller, can print a number of specific output formats, including current snapshot, forces, stresses, and birth times. Upon destruction, the output file is closed.
Definition at line 27 of file Output.h.
Constructor & Destructor Documentation
Output::Output (string outputFileName) inline
Constructor, which opens the output file.
Definition at line 34 of file Output.h.
References _outputFile.
Output::~Output () inline
Destructor, which closes the output file.
Definition at line 43 of file Output.h.
References _outputFile.
Member Function Documentation
void Output::printBasicSnapshot (int step)
Print basic information about filaments, linkers, motors (DEPRECATED)
Definition at line 26 of file Output.cpp.
References FilamentDB::instance(), MotorGhostDB::instance(), LinkerDB::instance(), mathfunc::MidPointCoordinate(), and tau().
Referenced by Controller::run().
void Output::printBirthTimes (int step)
Print birth times of beads for each filament.
Definition at line 133 of file Output.cpp.
References FilamentDB::instance(), and tau().
void Output::printForces (int step)
Print forces on beads for each filament.
Definition at line 161 of file Output.cpp.
References FilamentDB::instance(), and tau().
void Output::printSnapshot (int step)
New snapshot output.
Definition at line 102 of file Output.cpp.
References FilamentDB::instance(), and tau().
void Output::printStresses (int step)
Print stresses on beads for each filament.
Definition at line 189 of file Output.cpp.
Member Data Documentation
ofstream Output::_outputFile private
The output file being used.
Definition at line 30 of file Output.h.
Referenced by Output(), and ~Output().
The documentation for this class was generated from the following files:
M3SYM/Output.h
M3SYM/Output.cpp