MEDYAN: BoundaryBubbleNL Class Reference
BoundaryBubbleNL Class Reference
An implementation of NeighborList for BoundaryElement-Bubble interactions.
#include <NeighborListImpl.h>
Public Member Functions
BoundaryBubbleNL (float rMax)
virtual void addNeighbor (Neighbor *n)
Add neighbor.
virtual void removeNeighbor (Neighbor *n)
Remove a neighbor if possible.
virtual void addDynamicNeighbor (DynamicNeighbor *n)
Add a dynamic neighbor to the system.
virtual void removeDynamicNeighbor (DynamicNeighbor *n)
Remove a dynamic neighbor from the system.
virtual void reset ()
Re-initialize the neighborlist.
vector< Bubble * > getNeighbors (BoundaryElement *be)
Get all Bubble neighbors of a boundary element.
Protected Attributes
float _rMax
max distance cutoff
float _rMin
min distance cutoff
Private Member Functions
void updateNeighbors (BoundaryElement *be)
Helper function to update neighbors.
Private Attributes
unordered_map< BoundaryElement *, vector< Bubble * > > _list
The neighbors list, as a hash map.
Detailed Description
An implementation of NeighborList for BoundaryElement-Bubble interactions.
Definition at line 94 of file NeighborListImpl.h.
Constructor & Destructor Documentation
BoundaryBubbleNL()
BoundaryBubbleNL::BoundaryBubbleNL (float rMax) inline
Definition at line 104 of file NeighborListImpl.h.
References CylinderCylinderNL::addDynamicNeighbor(), CylinderCylinderNL::addNeighbor(), CylinderCylinderNL::getNeighbors(), CylinderCylinderNL::removeDynamicNeighbor(), CylinderCylinderNL::removeNeighbor(), and CylinderCylinderNL::reset().
Member Function Documentation
addDynamicNeighbor()
void BoundaryBubbleNL::addDynamicNeighbor (DynamicNeighbor * n) virtual
Add a dynamic neighbor to the system.
For BoundaryElementNeighborList list, this will be Bead. For CylinderNeighborList, all elements in neighbors list are dynamic.
Implements NeighborList.
Definition at line 226 of file NeighborListImpl.cpp.
References Bubble::coordinate.
addNeighbor()
void BoundaryBubbleNL::addNeighbor (Neighbor * n) virtual
Add neighbor.
Implements NeighborList.
Definition at line 208 of file NeighborListImpl.cpp.
getNeighbors()
vector< Bubble * > BoundaryBubbleNL::getNeighbors (BoundaryElement * be)
Get all Bubble neighbors of a boundary element.
Definition at line 265 of file NeighborListImpl.cpp.
removeDynamicNeighbor()
void BoundaryBubbleNL::removeDynamicNeighbor (DynamicNeighbor * n) virtual
Remove a dynamic neighbor from the system.
For BoundaryElementNeighborList list, this will be Bead. For CylinderNeighborList, all elements in neighbors list are dynamic.
Implements NeighborList.
Definition at line 241 of file NeighborListImpl.cpp.
removeNeighbor()
void BoundaryBubbleNL::removeNeighbor (Neighbor * n) virtual
Remove a neighbor if possible.
Implements NeighborList.
Definition at line 218 of file NeighborListImpl.cpp.
reset()
void BoundaryBubbleNL::reset () virtual
Re-initialize the neighborlist.
Implements NeighborList.
Definition at line 255 of file NeighborListImpl.cpp.
References BoundaryElement::getBoundaryElements().
updateNeighbors()
void BoundaryBubbleNL::updateNeighbors (BoundaryElement * be) private
Helper function to update neighbors.
Definition at line 194 of file NeighborListImpl.cpp.
References BoundaryElement::distance(), and Bubble::getBubbles().
Member Data Documentation
_list
unordered_map<BoundaryElement*, vector<Bubble*> > BoundaryBubbleNL::_list private
The neighbors list, as a hash map.
Definition at line 97 of file NeighborListImpl.h.
_rMax
float NeighborList::_rMax protected inherited
max distance cutoff
Definition at line 36 of file NeighborList.h.
_rMin
float NeighborList::_rMin protected inherited
min distance cutoff
Definition at line 37 of file NeighborList.h.
The documentation for this class was generated from the following files:
src/Structure/NeighborListImpl.h
src/Structure/NeighborListImpl.cpp