MEDYAN: CBound Class Reference
CBound Class Reference abstract
Represents a chemical object that is bound to a Filament.
#include <CBound.h>
Public Member Functions
CBound (short filamentType, Compartment *c, CCylinder *cc1, CCylinder *cc2, short position1, short position2)
Constructor, just sets species.
virtual ~CBound () noexcept
Virtual destructor.
void setFirstSpecies (SpeciesBound *species)
Set first species.
SpeciesBound * getFirstSpecies ()
Get first species.
void setSecondSpecies (SpeciesBound *species)
Set second species.
SpeciesBound * getSecondSpecies ()
Get second species.
void setFirstCCylinder (CCylinder *cc)
Set first CCylinder.
CCylinder * getFirstCCylinder ()
Get first CCylinder.
void setSecondCCylinder (CCylinder *cc)
Set second CCylinder.
CCylinder * getSecondCCylinder ()
Get first CCylinder.
Compartment * getCompartment ()
Get compartment that this CBound is in.
void setRates (float onRate, float offRate)
Set all rates at once.
short getFirstPosition ()
Position getters.
short getSecondPosition ()
Position getters.
void setOnRate (float rate)
On rate management.
double getOnRate ()
On rate management.
void setOffRate (float rate)
Off rate management.
double getOffRate ()
Off rate management.
virtual void createOffReaction (ReactionBase *onRxn, SubSystem *ps)=0
Off reaction management.
void setOffReaction (ReactionBase *offRxn)
Off reaction management.
ReactionBase * getOffReaction ()
Off reaction management.
Protected Attributes
short _filamentType
The filament type that this CBound binds to.
SpeciesBound * _firstSpecies = nullptr
Corresponding first species on Filament.
SpeciesBound * _secondSpecies = nullptr
Corresponding second species on Filament.
Compartment * _compartment
Compartment this CBound is in.
CCylinder * _cc1 = nullptr
Pointer to first CCylinder.
CCylinder * _cc2 = nullptr
Pointer to second CCylinder.
short _position1
position of first head
short _position2 = 0
position of second head
ReactionBase * _offRxn
The off reaction for this bound object.
float _onRate = 0.0
Reaction rates.
float _offRate = 0.0
Reaction rates.
Detailed Description
Represents a chemical object that is bound to a Filament.
The CBound class is an abstract representation of a chemically bound object to a Filament (Could be a Linker, MotorGhost, BranchingPoint, etc). Each CBound object has a pointer to the corresponding SpeciesBounds on a Filament. Different implementations of CBound class will have different functions to bind, move, etc. See documentation of subclass for more details on function.]
The CBound class also controls the element's unbinding reaction, including its creation and destruction in the chemical system.
Definition at line 37 of file CBound.h.
Constructor & Destructor Documentation
CBound()
CBound::CBound (short filamentType, Compartment * c, CCylinder * cc1, CCylinder * cc2, short position1, short position2) inline
Constructor, just sets species.
Definition at line 63 of file CBound.h.
~CBound()
virtual CBound::~CBound () inline virtual noexcept
Virtual destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 74 of file CBound.h.
References SpeciesBound::removeCBound().
Member Function Documentation
createOffReaction()
virtual void CBound::createOffReaction (ReactionBase * onRxn, SubSystem * ps) pure virtual
Off reaction management.
Implemented in CMotorGhost, CBranchingPoint, and CLinker.
Referenced by setRates().
getCompartment()
Compartment* CBound::getCompartment () inline
Get compartment that this CBound is in.
Definition at line 118 of file CBound.h.
References _compartment, and setOnRate().
getFirstCCylinder()
CCylinder* CBound::getFirstCCylinder () inline
Get first CCylinder.
Definition at line 110 of file CBound.h.
References _cc1.
getFirstPosition()
short CBound::getFirstPosition () inline
Position getters.
Definition at line 103 of file CBound.h.
Referenced by getSecondSpecies().
getFirstSpecies()
SpeciesBound* CBound::getFirstSpecies () inline
Get first species.
Definition at line 88 of file CBound.h.
References _firstSpecies.
Referenced by CMonomer::CMonomer(), and CMotorGhost::moveMotorHead().
getOffRate()
double CBound::getOffRate () inline
Off rate management.
Definition at line 129 of file CBound.h.
References _offRate.
getOffReaction()
ReactionBase* CBound::getOffReaction () inline
Off reaction management.
Definition at line 146 of file CBound.h.
References _offRxn.
getOnRate()
double CBound::getOnRate () inline
On rate management.
Definition at line 123 of file CBound.h.
References _onRate, and setOffRate().
getSecondCCylinder()
CCylinder* CBound::getSecondCCylinder () inline
Get first CCylinder.
Definition at line 115 of file CBound.h.
References _cc2.
getSecondPosition()
short CBound::getSecondPosition () inline
Position getters.
Definition at line 104 of file CBound.h.
References _position2.
getSecondSpecies()
SpeciesBound* CBound::getSecondSpecies () inline
Get second species.
Definition at line 99 of file CBound.h.
References _position1, _secondSpecies, and getFirstPosition().
setFirstCCylinder()
void CBound::setFirstCCylinder (CCylinder * cc) inline
Set first CCylinder.
Definition at line 108 of file CBound.h.
Referenced by CMotorGhost::moveMotorHead().
setFirstSpecies()
void CBound::setFirstSpecies (SpeciesBound * species) inline
Set first species.
remove from old first species
Definition at line 80 of file CBound.h.
References SpeciesBound::removeCBound(), and SpeciesBound::setCBound().
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMonomer::CMonomer(), CMotorGhost::CMotorGhost(), and CMotorGhost::moveMotorHead().
setOffRate()
void CBound::setOffRate (float rate) inline
Off rate management.
Definition at line 128 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), and getOnRate().
setOffReaction()
void CBound::setOffReaction (ReactionBase * offRxn) inline
Off reaction management.
Definition at line 142 of file CBound.h.
References ReactionBase::setCBound().
Referenced by CBranchingPoint::CBranchingPoint(), CCylinder::CCylinder(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), and CMotorGhost::moveMotorHead().
setOnRate()
void CBound::setOnRate (float rate) inline
On rate management.
Definition at line 122 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), and getCompartment().
setRates()
void CBound::setRates (float onRate, float offRate) inline
Set all rates at once.
Definition at line 133 of file CBound.h.
References createOffReaction().
setSecondCCylinder()
void CBound::setSecondCCylinder (CCylinder * cc) inline
Set second CCylinder.
Definition at line 113 of file CBound.h.
Referenced by CMotorGhost::moveMotorHead().
setSecondSpecies()
void CBound::setSecondSpecies (SpeciesBound * species) inline
Set second species.
remove from old second species
Definition at line 91 of file CBound.h.
References SpeciesBound::removeCBound(), and SpeciesBound::setCBound().
Referenced by CLinker::CLinker(), CMonomer::CMonomer(), CMotorGhost::CMotorGhost(), and CMotorGhost::moveMotorHead().
Member Data Documentation
_cc1
CCylinder* CBound::_cc1 = nullptr protected
Pointer to first CCylinder.
Definition at line 47 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), getFirstCCylinder(), CMotorGhost::moveMotorHead(), CBranchingPoint::~CBranchingPoint(), CLinker::~CLinker(), and CMotorGhost::~CMotorGhost().
_cc2
CCylinder* CBound::_cc2 = nullptr protected
Pointer to second CCylinder.
Definition at line 48 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), getSecondCCylinder(), CMotorGhost::moveMotorHead(), CLinker::~CLinker(), and CMotorGhost::~CMotorGhost().
_compartment
Compartment* CBound::_compartment protected
Compartment this CBound is in.
Definition at line 45 of file CBound.h.
Referenced by getCompartment().
_filamentType
short CBound::_filamentType protected
The filament type that this CBound binds to.
Definition at line 40 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), and CMotorGhost::moveMotorHead().
_firstSpecies
SpeciesBound* CBound::_firstSpecies = nullptr protected
Corresponding first species on Filament.
Definition at line 42 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), getFirstSpecies(), and CMotorGhost::moveMotorHead().
_offRate
float CBound::_offRate = 0.0 protected
Reaction rates.
Definition at line 56 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CBranchingPoint::createOffReaction(), CMotorGhost::createOffReaction(), getOffRate(), and CMotorGhost::moveMotorHead().
_offRxn
ReactionBase* CBound::_offRxn protected
The off reaction for this bound object.
Definition at line 59 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CBranchingPoint::clone(), CLinker::clone(), CMotorGhost::clone(), CMotorGhost::CMotorGhost(), getOffReaction(), CMotorGhost::moveMotorHead(), CBranchingPoint::~CBranchingPoint(), CLinker::~CLinker(), and CMotorGhost::~CMotorGhost().
_onRate
float CBound::_onRate = 0.0 protected
Reaction rates.
Definition at line 55 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), and getOnRate().
_position1
short CBound::_position1 protected
position of first head
Definition at line 50 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CBranchingPoint::createOffReaction(), CMotorGhost::createOffReaction(), getSecondSpecies(), and CMotorGhost::moveMotorHead().
_position2
short CBound::_position2 = 0 protected
position of second head
Definition at line 51 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), getSecondPosition(), and CMotorGhost::moveMotorHead().
_secondSpecies
SpeciesBound* CBound::_secondSpecies = nullptr protected
Corresponding second species on Filament.
Definition at line 43 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), getSecondSpecies(), and CMotorGhost::moveMotorHead().
The documentation for this class was generated from the following file:
src/Structure/CBound.h