MEDYAN: RSpeciesAvg Class Reference
RSpeciesAvg Class Reference
An average RSpecies that tracks the average copy number over a number of events.
#include <RSpecies.h>
Public Member Functions
RSpeciesAvg (Species &parent, species_copy_t n=0, species_copy_t ulim=max_ulim)
Constructors.
RSpeciesAvg (const RSpeciesAvg &r)=delete
deleted copy constructor - each RSpeciesAvg is uniquely created by the parent Species
RSpeciesAvg (RSpeciesAvg &&r)=delete
deleted move constructor - each RSpeciesAvg is uniquely created by the parent Species
RSpeciesAvg & operator= (RSpeciesAvg &)=delete
deleted assignment operator - each RSpeciesAvg is uniquely created by the parent Species
bool newAverage ()
Whether we just calculated a new average.
void setNumEvents (int numEvents)
Set the number of events to use averaging.
virtual void up ()
Increase the true copy number.
virtual void down ()
Decrease the true copy number.
virtual float getN () const
Return the current average.
void setN (species_copy_t n)
Sets the copy number for this RSpecies.
void addAsReactant (ReactionBase *r)
void addAsProduct (ReactionBase *r)
void removeAsReactant (const ReactionBase *r)
void removeAsProduct (const ReactionBase *r)
void activateAssocReactantReactions ()
void activateAssocProductReactions ()
void passivateAssocReactantReactions ()
void passivateAssocProductReactions ()
Species & getSpecies ()
return parent Species as a reference
const Species & getSpecies () const
return parent Species as a const reference
string getFullName () const
Return the full name of this Species in a string format (e.g. "Arp2/3{Bulk}")
vector< ReactionBase * > & reactantReactions ()
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Reactant.
vector< ReactionBase * > & productReactions ()
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Product.
vr_iterator beginReactantReactions ()
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Reactant.
vr_iterator beginProductReactions ()
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Product.
vr_iterator endReactantReactions ()
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Reactant.
vr_iterator endProductReactions ()
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Product.
virtual species_copy_t getTrueN () const
Return the true copy number of this RSpecies.
Protected Attributes
vector< ReactionBase * > _as_reactants = {}
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
vector< ReactionBase * > _as_products = {}
a vector of Reactions where this RSpecies is a Product
Species & _species
reference to the parent Species object
species_copy_t _n
Current copy number of this RSpecies.
RSpeciesType _type
The RSpecies type.
Private Member Functions
void computeAverageN ()
Compute the time average of the currently tracked, previous copy numbers.
Private Attributes
int _numEvents
The number of events to generate an average copy number.
int _eventCount = 0
Tracking the number of events since last average.
double _localTau
The time since the last event occured.
double _firstTau
Time since an average update occured.
double _average
The current average value.
bool _newAvg = false
If we just calculated a new average.
unordered_map< species_copy_t, double > _copyNumbers
A map of copy number and time (representing the time the species has been at this copy number).
Friends
class Species
Detailed Description
An average RSpecies that tracks the average copy number over a number of events.
The RSpeciesAvg class represents a RSpecies that, while updating the true copy number of the species, also tracks the average copy number over a specified number of events. up() and down() update the true copy number while adding to a running average of copy number events. When the number of events to average (named _numEvents) is reached, the RSpecies computes the new average value and updates accordingly.
The RSpeciesAvg can only be used for SpeciesBulk or SpeciesDiffusing.
Note
- Still buggy for lower concentration averaging. Use with caution. Since this only produces speedups for larger diffusive concentrations, this choice would be sub-optimal anyway.
Definition at line 425 of file RSpecies.h.
Constructor & Destructor Documentation
RSpeciesAvg() [1/3]
RSpeciesAvg::RSpeciesAvg (Species & parent, species_copy_t n = 0, species_copy_t ulim = max_ulim) inline
Constructors.
Parameters
numEvents - the number of copy number change events to use before computing a new average. When this number is reached, a new average is created using the _copyNumbers map (time averaged) and replaces the previous average.
Definition at line 469 of file RSpecies.h.
References RSpecies::_type, AVG, RSpecies::operator=(), and tau().
RSpeciesAvg() [2/3]
RSpeciesAvg::RSpeciesAvg (const RSpeciesAvg & r) delete
deleted copy constructor - each RSpeciesAvg is uniquely created by the parent Species
RSpeciesAvg() [3/3]
RSpeciesAvg::RSpeciesAvg (RSpeciesAvg && r) delete
deleted move constructor - each RSpeciesAvg is uniquely created by the parent Species
Member Function Documentation
activateAssocProductReactions()
void RSpecies::activateAssocProductReactions () inherited
Attempts to activate previously passivated Reactions where this RSpecies is involved as a Product. Usually, the Reaction was first passivated, for example if the RSpecies copy number of one of the reactants went up to max_ulim.
Definition at line 77 of file RSpecies.cpp.
References RSpecies::_as_products.
Referenced by RSpeciesReg::down(), down(), and RSpecies::removeAsProduct().
activateAssocReactantReactions()
void RSpecies::activateAssocReactantReactions () inherited
Attempts to activate previously passivated Reactions where this RSpecies is involved as a Reactant. Usually, the Reaction was first passivated, for example if the RSpecies copy number of one of the reactants dropeed to zero. This attempt may not succeed if there are still other reactants in the same Reaction with zero copy count.
Definition at line 72 of file RSpecies.cpp.
References RSpecies::_as_reactants.
Referenced by RSpecies::removeAsProduct(), RSpeciesReg::up(), and up().
addAsProduct()
void RSpecies::addAsProduct (ReactionBase * r) inline inherited
Definition at line 138 of file RSpecies.h.
addAsReactant()
void RSpecies::addAsReactant (ReactionBase * r) inline inherited
Definition at line 134 of file RSpecies.h.
beginProductReactions()
vr_iterator RSpecies::beginProductReactions () inline inherited
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Product.
Definition at line 249 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
beginReactantReactions()
vr_iterator RSpecies::beginReactantReactions () inline inherited
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Reactant.
Definition at line 245 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
computeAverageN()
void RSpeciesAvg::computeAverageN () inline private
Compute the time average of the currently tracked, previous copy numbers.
Definition at line 447 of file RSpecies.h.
References tau().
down()
virtual void RSpeciesAvg::down () inline virtual
Decrease the true copy number.
Add the old copy number to the running copy number map. If a new average is needed, compute it and reset accordingly. If the copy number changes from 1 to 0, calls a "callback"-like method to passivate previously activated [Reactions](Reaction), where this RSpecies is a Reactant. Also emits a signal with the change in copy number if attached.
Implements RSpecies.
Definition at line 561 of file RSpecies.h.
References RSpecies::_n, RSpecies::activateAssocProductReactions(), RSpecies::passivateAssocReactantReactions(), and tau().
endProductReactions()
vr_iterator RSpecies::endProductReactions () inline inherited
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Product.
Definition at line 257 of file RSpecies.h.
References RSpecies::down(), RSpecies::getN(), and RSpecies::up().
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
endReactantReactions()
vr_iterator RSpecies::endReactantReactions () inline inherited
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Reactant.
Definition at line 253 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
getFullName()
string RSpecies::getFullName () const inherited
Return the full name of this Species in a string format (e.g. "Arp2/3{Bulk}")
Definition at line 67 of file RSpecies.cpp.
References RSpecies::_species, and Species::getFullName().
Referenced by RSpecies::getSpecies(), and operator<<().
getN()
virtual float RSpeciesAvg::getN () const inline virtual
Return the current average.
Implements RSpecies.
Definition at line 603 of file RSpecies.h.
References operator<<().
getSpecies() [1/2]
Species& RSpecies::getSpecies () inline inherited
return parent Species as a reference
Definition at line 227 of file RSpecies.h.
References RSpecies::_species.
Referenced by BranchingManager::BranchingManager(), CBranchingPoint::createOffReaction(), Reaction< 1, 1 >::is_equal(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), and CMotorGhost::moveMotorHead().
getSpecies() [2/2]
const Species& RSpecies::getSpecies () const inline inherited
return parent Species as a const reference
Definition at line 230 of file RSpecies.h.
References RSpecies::_species, and RSpecies::getFullName().
getTrueN()
virtual species_copy_t RSpecies::getTrueN () const inline virtual inherited
Return the true copy number of this RSpecies.
Definition at line 267 of file RSpecies.h.
References RSpecies::_n.
newAverage()
bool RSpeciesAvg::newAverage () inline
Whether we just calculated a new average.
Definition at line 499 of file RSpecies.h.
operator=()
RSpeciesAvg& RSpeciesAvg::operator= (RSpeciesAvg &) delete
deleted assignment operator - each RSpeciesAvg is uniquely created by the parent Species
passivateAssocProductReactions()
void RSpecies::passivateAssocProductReactions () inherited
Passivates all Reactions where this RSpecies is among the products.
Definition at line 87 of file RSpecies.cpp.
References RSpecies::_as_products.
Referenced by RSpecies::removeAsProduct(), RSpeciesReg::up(), and up().
passivateAssocReactantReactions()
void RSpecies::passivateAssocReactantReactions () inherited
Passivates all Reactions where this RSpecies is among the reactants.
Definition at line 82 of file RSpecies.cpp.
References RSpecies::_as_reactants.
Referenced by RSpeciesReg::down(), down(), and RSpecies::removeAsProduct().
productReactions()
vector<ReactionBase *>& RSpecies::productReactions () inline inherited
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Product.
Definition at line 241 of file RSpecies.h.
References RSpecies::_as_products.
reactantReactions()
vector<ReactionBase *>& RSpecies::reactantReactions () inline inherited
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Reactant.
Definition at line 237 of file RSpecies.h.
References RSpecies::_as_reactants.
Referenced by Species::activateReactantReactions(), Species::passivateReactantReactions(), Species::updateReactantPropensities(), and MotorGhost::updateReactionRates().
removeAsProduct()
void RSpecies::removeAsProduct (const ReactionBase * r) inline inherited
Definition at line 158 of file RSpecies.h.
References RSpecies::activateAssocProductReactions(), RSpecies::activateAssocReactantReactions(), RSpecies::passivateAssocProductReactions(), RSpecies::passivateAssocReactantReactions(), and RSpecies::~RSpecies().
removeAsReactant()
void RSpecies::removeAsReactant (const ReactionBase * r) inline inherited
Definition at line 142 of file RSpecies.h.
setN()
void RSpecies::setN (species_copy_t n) inline inherited
Sets the copy number for this RSpecies.
Parameters
n should be a non-negative number, but no checking is done in run time
Note
The operation does not emit any signals about the copy number change.
Definition at line 121 of file RSpecies.h.
Referenced by Species::setN().
setNumEvents()
void RSpeciesAvg::setNumEvents (int numEvents) inline
Set the number of events to use averaging.
Definition at line 502 of file RSpecies.h.
up()
virtual void RSpeciesAvg::up () inline virtual
Increase the true copy number.
Add the old copy number to the running copy number map. If a new average is needed, compute it and reset accordingly. If the copy number changes from 1 to 0, calls a "callback"-like method to passivate previously activated [Reactions](Reaction), where this RSpecies is a Reactant. Also emits a signal with the change in copy number if attached.
Implements RSpecies.
Definition at line 511 of file RSpecies.h.
References RSpecies::_n, RSpecies::activateAssocReactantReactions(), areEqual(), RSpecies::passivateAssocProductReactions(), and tau().
Friends And Related Function Documentation
Species
friend class Species friend
Definition at line 427 of file RSpecies.h.
Member Data Documentation
_as_products
vector<ReactionBase *> RSpecies::_as_products = {} protected inherited
a vector of Reactions where this RSpecies is a Product
Definition at line 73 of file RSpecies.h.
Referenced by RSpecies::activateAssocProductReactions(), RSpecies::passivateAssocProductReactions(), RSpecies::productReactions(), and RSpecies::~RSpecies().
_as_reactants
vector<ReactionBase *> RSpecies::_as_reactants = {} protected inherited
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
a vector of Reactions where this RSpecies is a Reactant
Definition at line 70 of file RSpecies.h.
Referenced by RSpecies::activateAssocReactantReactions(), RSpecies::passivateAssocReactantReactions(), RSpecies::reactantReactions(), and RSpecies::~RSpecies().
_average
double RSpeciesAvg::_average private
The current average value.
Definition at line 436 of file RSpecies.h.
_copyNumbers
unordered_map<species_copy_t, double> RSpeciesAvg::_copyNumbers private
A map of copy number and time (representing the time the species has been at this copy number).
These values will be collected until a new average is needed, and the map will be used to compute an average and then reset.
Definition at line 444 of file RSpecies.h.
_eventCount
int RSpeciesAvg::_eventCount = 0 private
Tracking the number of events since last average.
Definition at line 431 of file RSpecies.h.
_firstTau
double RSpeciesAvg::_firstTau private
Time since an average update occured.
Definition at line 434 of file RSpecies.h.
_localTau
double RSpeciesAvg::_localTau private
The time since the last event occured.
Definition at line 433 of file RSpecies.h.
_n
species_copy_t RSpecies::_n protected inherited
Current copy number of this RSpecies.
this RSpecies (usually when a single step of this Reaction occurs)
Definition at line 77 of file RSpecies.h.
Referenced by RSpeciesReg::down(), RSpeciesConst::down(), down(), RSpeciesReg::getN(), RSpecies::getTrueN(), RSpeciesReg::up(), and up().
_newAvg
bool RSpeciesAvg::_newAvg = false private
If we just calculated a new average.
Used by Reaction to mark the updating of its dependencies accordingly.
Definition at line 438 of file RSpecies.h.
_numEvents
int RSpeciesAvg::_numEvents private
The number of events to generate an average copy number.
Definition at line 430 of file RSpecies.h.
_species
Species& RSpecies::_species protected inherited
reference to the parent Species object
Definition at line 76 of file RSpecies.h.
Referenced by RSpecies::getFullName(), and RSpecies::getSpecies().
_type
RSpeciesType RSpecies::_type protected inherited
The RSpecies type.
Definition at line 88 of file RSpecies.h.
Referenced by Species::operator=(), RSpeciesAvg(), RSpeciesConst::RSpeciesConst(), RSpeciesReg::RSpeciesReg(), and Species::Species().
The documentation for this class was generated from the following file:
src/Chemistry/RSpecies.h