MEDYAN: FilamentBending< FBendingInteractionType > Class Template Reference
FilamentBending< FBendingInteractionType > Class Template Reference
Represents a Filament bending interaction.
#include <FilamentBending.h>
Public Member Functions
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
Filament * _filamentCulprit = nullptr
The filament in the case of an error.
Private Attributes
FBendingInteractionType _FFType
Detailed Description
template<class FBendingInteractionType>
class FilamentBending< FBendingInteractionType >
Represents a Filament bending interaction.
Definition at line 26 of file FilamentBending.h.
Member Function Documentation
computeEnergy()
template<class FBendingInteractionType > template double FilamentBending< FBendingInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements FilamentInteractions.
Definition at line 23 of file FilamentBending.cpp.
References Filament::getFilaments().
Referenced by FilamentBending< FBendingInteractionType >::computeForcesAux().
computeForces()
template<class FBendingInteractionType > template void FilamentBending< FBendingInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements FilamentInteractions.
Definition at line 80 of file FilamentBending.cpp.
References Filament::getFilaments().
Referenced by FilamentBending< FBendingInteractionType >::computeForcesAux().
computeForcesAux()
template<class FBendingInteractionType > template void FilamentBending< FBendingInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements FilamentInteractions.
Definition at line 102 of file FilamentBending.cpp.
References FilamentBending< FBendingInteractionType >::computeEnergy(), FilamentBending< FBendingInteractionType >::computeForces(), and Filament::getFilaments().
getName()
template<class FBendingInteractionType > virtual const string FilamentBending< FBendingInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements FilamentInteractions.
Definition at line 36 of file FilamentBending.h.
Member Data Documentation
_FFType
template<class FBendingInteractionType > FBendingInteractionType FilamentBending< FBendingInteractionType >::_FFType private
Definition at line 29 of file FilamentBending.h.
_filamentCulprit
Filament* FilamentInteractions::_filamentCulprit = nullptr protected inherited
The filament in the case of an error.
Definition at line 31 of file FilamentInteractions.h.
Referenced by FilamentFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Filament/FilamentBending.h
src/Mechanics/ForceField/Filament/FilamentBending.cpp