MEDYAN: LinkerBindingManager Class Reference
LinkerBindingManager Class Reference
Manager for Linker binding.
#include <BindingManager.h>
Public Member Functions
LinkerBindingManager (ReactionBase *reaction, Compartment *compartment, short boundInt, string boundName, short filamentType, float rMax, float rMin)
~LinkerBindingManager ()
virtual void updateAllPossibleBindings ()
update all possible binding reactions that could occur
virtual int numBindingSites ()
Get current number of binding sites.
virtual void appendpossibleBindings (tuple< CCylinder *, short > t1, tuple< CCylinder *, short > t2)
ARAVIND ADDED FEB 17 2016. append possible bindings.
virtual unordered_multimap< tuple< CCylinder *, short >, tuple< CCylinder *, short > > getpossibleBindings ()
virtual void clearpossibleBindings ()
ARAVIND ADDED FEB 18 2016. clear possible bindings.
vector< tuple< CCylinder *, short > > chooseBindingSites ()
Choose random binding sites based on current state.
virtual bool isConsistent ()
Check consistency and correctness of binding sites. Used for debugging.
short getBoundInt ()
Get the bound species integer index.
string getBoundName ()
Get the bound species name.
void setNLIndex (int index)
Set the index of this manager, for access to NeighborList.
void setMIndex (int index)
Set the index of this manager, for access to other managers.
short getfilamentType ()
get the filament that the species binds to aravind June 30, 2016.
vector< string > getrxnspecies ()
aravind, June 30,2016.
virtual void addPossibleBindings (CCylinder *cc, short bindingSite)
add possible binding reactions that could occur
virtual void addPossibleBindings (CCylinder *cc)
add possible binding reactions that could occur
virtual void removePossibleBindings (CCylinder *cc, short bindingSite)
Remove all bindings including this cylinder.
virtual void removePossibleBindings (CCylinder *cc)
Remove all bindings including this cylinder.
float getRMin ()
Getters for distances.
float getRMax ()
Getters for distances.
Protected Member Functions
void updateBindingReaction (int oldN, int newN)
helper function to update copy number and reactions
Protected Attributes
ReactionBase * _bindingReaction
The binding reaction for this compartment.
Compartment * _compartment
Compartment this is in.
short _boundInt
Integer index in CMonomer of bound chemical value.
string _boundName
String name of bound chemical value.
short _filamentType
The filament type to operate on.
Species * _bindingSpecies
The binding species that this manager tracks.
short _nlIndex = 0
Index of this manager (for access of neighbor lists)
short _mIndex = 0
Index of this manager (for access in other compartments)
Static Protected Attributes
static SubSystem * _subSystem = 0
Ptr to the SubSystem.
Private Attributes
float _rMin
Minimum reaction range.
float _rMax
Maximum reaction range.
unordered_multimap< tuple< CCylinder *, short >, tuple< CCylinder *, short > > _possibleBindings
Static Private Attributes
static vector< CylinderCylinderNL * > _neighborLists
Friends
class ChemManager
Detailed Description
Manager for Linker binding.
LinkerBindingManager controls linker binding in a compartment. Manages a multimap of possible binding sites.
Definition at line 256 of file BindingManager.h.
Constructor & Destructor Documentation
LinkerBindingManager()
LinkerBindingManager::LinkerBindingManager (ReactionBase * reaction, Compartment * compartment, short boundInt, string boundName, short filamentType, float rMax, float rMin)
Definition at line 218 of file BindingManager.cpp.
References FilamentBindingManager::_bindingSpecies, FilamentBindingManager::_compartment, Compartment::findSpeciesByName(), Species::getName(), RSpecies::getSpecies(), ML_RXN_INDEX, and ReactionBase::rspecies().
~LinkerBindingManager()
LinkerBindingManager::~LinkerBindingManager () inline
Definition at line 278 of file BindingManager.h.
References FilamentBindingManager::addPossibleBindings(), FilamentBindingManager::removePossibleBindings(), and FilamentBindingManager::updateAllPossibleBindings().
Member Function Documentation
addPossibleBindings() [1/2]
void LinkerBindingManager::addPossibleBindings (CCylinder * cc, short bindingSite) virtual
add possible binding reactions that could occur
Implements FilamentBindingManager.
Definition at line 235 of file BindingManager.cpp.
References FilamentBindingManager::_bindingSpecies, FilamentBindingManager::_compartment, FilamentBindingManager::_filamentType, FilamentBindingManager::_mIndex, _neighborLists, FilamentBindingManager::_nlIndex, _possibleBindings, _rMax, _rMin, areEqual(), ChemParams::bindingSites, SysParams::Chemistry(), Bead::coordinate, GeoParams::cylinderNumMon, SysParams::Geometry(), Cylinder::getCCylinder(), CCylinder::getCMonomer(), CCylinder::getCylinder(), Cylinder::getFirstBead(), Cylinder::getID(), Species::getN(), Component::getParent(), Cylinder::getSecondBead(), CCylinder::getType(), ChemParams::linkerBoundIndex, mathfunc::midPointCoordinate(), numBindingSites(), CMonomer::speciesBound(), mathfunc::twoPointDistance(), and FilamentBindingManager::updateBindingReaction().
Referenced by addPossibleBindings().
addPossibleBindings() [2/2]
void LinkerBindingManager::addPossibleBindings (CCylinder * cc) virtual
add possible binding reactions that could occur
Implements FilamentBindingManager.
Definition at line 322 of file BindingManager.cpp.
References FilamentBindingManager::_filamentType, addPossibleBindings(), ChemParams::bindingSites, and SysParams::Chemistry().
appendpossibleBindings()
virtual void LinkerBindingManager::appendpossibleBindings (tuple< CCylinder *, short > t1, tuple< CCylinder *, short > t2) inline virtual
ARAVIND ADDED FEB 17 2016. append possible bindings.
Implements FilamentBindingManager.
Definition at line 300 of file BindingManager.h.
References FilamentBindingManager::numBindingSites(), and FilamentBindingManager::updateBindingReaction().
chooseBindingSites()
vector<tuple<CCylinder*, short> > LinkerBindingManager::chooseBindingSites () inline
Choose random binding sites based on current state.
Definition at line 324 of file BindingManager.h.
References FilamentBindingManager::isConsistent(), and Rand::randInteger().
clearpossibleBindings()
virtual void LinkerBindingManager::clearpossibleBindings () inline virtual
ARAVIND ADDED FEB 18 2016. clear possible bindings.
Implements FilamentBindingManager.
Definition at line 312 of file BindingManager.h.
References FilamentBindingManager::numBindingSites(), and FilamentBindingManager::updateBindingReaction().
getBoundInt()
short FilamentBindingManager::getBoundInt () inline inherited
Get the bound species integer index.
Definition at line 149 of file BindingManager.h.
References FilamentBindingManager::_boundInt.
getBoundName()
string FilamentBindingManager::getBoundName () inline inherited
Get the bound species name.
Definition at line 151 of file BindingManager.h.
References FilamentBindingManager::_boundName.
getfilamentType()
short FilamentBindingManager::getfilamentType () inline inherited
get the filament that the species binds to aravind June 30, 2016.
Definition at line 163 of file BindingManager.h.
References FilamentBindingManager::_filamentType, and FilamentBindingManager::appendpossibleBindings().
getpossibleBindings()
virtual unordered_multimap<tuple<CCylinder*, short>, tuple<CCylinder*, short> > LinkerBindingManager::getpossibleBindings () inline virtual
Definition at line 307 of file BindingManager.h.
getRMax()
float LinkerBindingManager::getRMax () inline
Getters for distances.
Definition at line 320 of file BindingManager.h.
Referenced by ChemManager::genFilBindingReactions().
getRMin()
float LinkerBindingManager::getRMin () inline
Getters for distances.
Definition at line 319 of file BindingManager.h.
Referenced by ChemManager::genFilBindingReactions().
getrxnspecies()
vector<string> FilamentBindingManager::getrxnspecies () inline inherited
aravind, June 30,2016.
Definition at line 168 of file BindingManager.h.
References FilamentBindingManager::clearpossibleBindings(), and ReactionBase::getreactantspecies().
isConsistent()
bool LinkerBindingManager::isConsistent () virtual
Check consistency and correctness of binding sites. Used for debugging.
Implements FilamentBindingManager.
Definition at line 463 of file BindingManager.cpp.
References FilamentBindingManager::_filamentType, _possibleBindings, areEqual(), SysParams::Chemistry(), CCylinder::getCMonomer(), CCylinder::getCylinder(), Species::getN(), Cylinder::printSelf(), and CMonomer::speciesBound().
numBindingSites()
virtual int LinkerBindingManager::numBindingSites () inline virtual
Get current number of binding sites.
Implements FilamentBindingManager.
Definition at line 295 of file BindingManager.h.
Referenced by addPossibleBindings(), removePossibleBindings(), and updateAllPossibleBindings().
removePossibleBindings() [1/2]
void LinkerBindingManager::removePossibleBindings (CCylinder * cc, short bindingSite) virtual
Remove all bindings including this cylinder.
Implements FilamentBindingManager.
Definition at line 331 of file BindingManager.cpp.
References FilamentBindingManager::_bindingSpecies, FilamentBindingManager::_compartment, FilamentBindingManager::_filamentType, FilamentBindingManager::_mIndex, _neighborLists, FilamentBindingManager::_nlIndex, _possibleBindings, Species::getN(), CCylinder::getType(), numBindingSites(), and FilamentBindingManager::updateBindingReaction().
Referenced by removePossibleBindings().
removePossibleBindings() [2/2]
void LinkerBindingManager::removePossibleBindings (CCylinder * cc) virtual
Remove all bindings including this cylinder.
Implements FilamentBindingManager.
Definition at line 389 of file BindingManager.cpp.
References FilamentBindingManager::_filamentType, ChemParams::bindingSites, SysParams::Chemistry(), and removePossibleBindings().
setMIndex()
void FilamentBindingManager::setMIndex (int index) inline inherited
Set the index of this manager, for access to other managers.
Definition at line 157 of file BindingManager.h.
References FilamentBindingManager::isConsistent().
Referenced by ChemManager::genFilBindingReactions().
setNLIndex()
void FilamentBindingManager::setNLIndex (int index) inline inherited
Set the index of this manager, for access to NeighborList.
Definition at line 154 of file BindingManager.h.
Referenced by ChemManager::genFilBindingReactions().
updateAllPossibleBindings()
void LinkerBindingManager::updateAllPossibleBindings () virtual
update all possible binding reactions that could occur
Implements FilamentBindingManager.
Definition at line 397 of file BindingManager.cpp.
References FilamentBindingManager::_bindingSpecies, FilamentBindingManager::_compartment, FilamentBindingManager::_filamentType, _neighborLists, FilamentBindingManager::_nlIndex, _possibleBindings, _rMax, _rMin, areEqual(), ChemParams::bindingSites, SysParams::Chemistry(), GeoParams::cylinderNumMon, SysParams::Geometry(), Compartment::getCylinders(), Species::getN(), ChemParams::linkerBoundIndex, mathfunc::midPointCoordinate(), numBindingSites(), mathfunc::twoPointDistance(), and FilamentBindingManager::updateBindingReaction().
updateBindingReaction()
void FilamentBindingManager::updateBindingReaction (int oldN, int newN) inline protected inherited
helper function to update copy number and reactions
Definition at line 85 of file BindingManager.h.
References Species::down(), Species::getN(), FilamentBindingManager::numBindingSites(), Species::up(), and ReactionBase::updatePropensity().
Referenced by BranchingManager::addPossibleBindings(), addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingManager::appendpossibleBindings(), appendpossibleBindings(), MotorBindingManager::appendpossibleBindings(), BranchingManager::clearpossibleBindings(), clearpossibleBindings(), MotorBindingManager::clearpossibleBindings(), BranchingManager::removePossibleBindings(), removePossibleBindings(), MotorBindingManager::removePossibleBindings(), BranchingManager::updateAllPossibleBindings(), updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
Friends And Related Function Documentation
ChemManager
friend class ChemManager friend
Definition at line 258 of file BindingManager.h.
Member Data Documentation
_bindingReaction
ReactionBase* FilamentBindingManager::_bindingReaction protected inherited
The binding reaction for this compartment.
Definition at line 65 of file BindingManager.h.
_bindingSpecies
Species* FilamentBindingManager::_bindingSpecies protected inherited
The binding species that this manager tracks.
Resposible for all copy number changes
Definition at line 76 of file BindingManager.h.
Referenced by BranchingManager::addPossibleBindings(), addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingManager::BranchingManager(), LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), BranchingManager::removePossibleBindings(), removePossibleBindings(), MotorBindingManager::removePossibleBindings(), BranchingManager::updateAllPossibleBindings(), updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_boundInt
short FilamentBindingManager::_boundInt protected inherited
Integer index in CMonomer of bound chemical value.
Note
- THIS ALSO REPRESENTS THE SPECIES TYPE THAT IS MANAGED.
Definition at line 69 of file BindingManager.h.
Referenced by FilamentBindingManager::getBoundInt().
_boundName
string FilamentBindingManager::_boundName protected inherited
String name of bound chemical value.
Definition at line 72 of file BindingManager.h.
Referenced by FilamentBindingManager::getBoundName().
_compartment
Compartment* FilamentBindingManager::_compartment protected inherited
Compartment this is in.
Definition at line 67 of file BindingManager.h.
Referenced by addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingManager::BranchingManager(), LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), removePossibleBindings(), MotorBindingManager::removePossibleBindings(), BranchingManager::updateAllPossibleBindings(), updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_filamentType
short FilamentBindingManager::_filamentType protected inherited
The filament type to operate on.
Definition at line 74 of file BindingManager.h.
Referenced by BranchingManager::addPossibleBindings(), addPossibleBindings(), MotorBindingManager::addPossibleBindings(), FilamentBindingManager::getfilamentType(), BranchingManager::isConsistent(), isConsistent(), MotorBindingManager::isConsistent(), BranchingManager::removePossibleBindings(), removePossibleBindings(), MotorBindingManager::removePossibleBindings(), BranchingManager::updateAllPossibleBindings(), updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_mIndex
short FilamentBindingManager::_mIndex = 0 protected inherited
Index of this manager (for access in other compartments)
Definition at line 80 of file BindingManager.h.
Referenced by addPossibleBindings(), MotorBindingManager::addPossibleBindings(), removePossibleBindings(), and MotorBindingManager::removePossibleBindings().
_neighborLists
vector< CylinderCylinderNL * > LinkerBindingManager::_neighborLists static private
Definition at line 268 of file BindingManager.h.
Referenced by addPossibleBindings(), ChemManager::genFilBindingReactions(), MotorBindingManager::isConsistent(), removePossibleBindings(), and updateAllPossibleBindings().
_nlIndex
short FilamentBindingManager::_nlIndex = 0 protected inherited
Index of this manager (for access of neighbor lists)
Definition at line 79 of file BindingManager.h.
Referenced by addPossibleBindings(), MotorBindingManager::addPossibleBindings(), MotorBindingManager::isConsistent(), removePossibleBindings(), MotorBindingManager::removePossibleBindings(), updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_possibleBindings
unordered_multimap<tuple<CCylinder*, short>, tuple<CCylinder*, short> > LinkerBindingManager::_possibleBindings private
Definition at line 265 of file BindingManager.h.
Referenced by addPossibleBindings(), isConsistent(), removePossibleBindings(), and updateAllPossibleBindings().
_rMax
float LinkerBindingManager::_rMax private
Maximum reaction range.
Definition at line 262 of file BindingManager.h.
Referenced by addPossibleBindings(), and updateAllPossibleBindings().
_rMin
float LinkerBindingManager::_rMin private
Minimum reaction range.
Definition at line 261 of file BindingManager.h.
Referenced by addPossibleBindings(), and updateAllPossibleBindings().
_subSystem
SubSystem * FilamentBindingManager::_subSystem = 0 static protected inherited
Ptr to the SubSystem.
Definition at line 82 of file BindingManager.h.
Referenced by BranchingManager::addPossibleBindings(), ChemManager::genFilBindingReactions(), MotorBindingManager::isConsistent(), and BranchingManager::updateAllPossibleBindings().
The documentation for this class was generated from the following files:
src/Chemistry/BindingManager.h
src/Chemistry/BindingManager.cpp