MEDYAN: BubbleBubbleRepulsion< BRepulsionInteractionType > Class Template Reference
BubbleBubbleRepulsion< BRepulsionInteractionType > Class Template Reference
Represents a repulsive interaction between two Bubbles.
#include <BubbleBubbleRepulsion.h>
Public Member Functions
BubbleBubbleRepulsion ()
Constructor.
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual void computeLoadForces ()
Compute the load forces on beads from this interaction.
virtual NeighborList * getNeighborList ()
Get the neighbor list for this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
Bubble * _bubbleCulprit = nullptr
In the case of an error.
Component * _otherCulprit = nullptr
In the case of an error.
Private Attributes
BRepulsionInteractionType _FFType
BubbleBubbleNL * _neighborList
Neighbor list of Bubble-Bubble.
Detailed Description
template<class BRepulsionInteractionType>
class BubbleBubbleRepulsion< BRepulsionInteractionType >
Represents a repulsive interaction between two Bubbles.
Definition at line 31 of file BubbleBubbleRepulsion.h.
Constructor & Destructor Documentation
BubbleBubbleRepulsion()
template<class BRepulsionInteractionType > BubbleBubbleRepulsion< BRepulsionInteractionType >::BubbleBubbleRepulsion () inline
Constructor.
Definition at line 39 of file BubbleBubbleRepulsion.h.
References BubbleBubbleRepulsion< BRepulsionInteractionType >::computeEnergy(), BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForces(), BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux(), and SysParams::Mechanics().
Member Function Documentation
computeEnergy()
template<class BRepulsionInteractionType > template double BubbleBubbleRepulsion< BRepulsionInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BubbleInteractions.
Definition at line 22 of file BubbleBubbleRepulsion.cpp.
References Bubble::getBubbles().
Referenced by BubbleBubbleRepulsion< BRepulsionInteractionType >::BubbleBubbleRepulsion(), and BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux().
computeForces()
template<class BRepulsionInteractionType > template void BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements BubbleInteractions.
Definition at line 65 of file BubbleBubbleRepulsion.cpp.
References Bubble::getBubbles().
Referenced by BubbleBubbleRepulsion< BRepulsionInteractionType >::BubbleBubbleRepulsion(), and BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux().
computeForcesAux()
template<class BRepulsionInteractionType > template void BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements BubbleInteractions.
Definition at line 88 of file BubbleBubbleRepulsion.cpp.
References BubbleBubbleRepulsion< BRepulsionInteractionType >::computeEnergy(), BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForces(), and Bubble::getBubbles().
Referenced by BubbleBubbleRepulsion< BRepulsionInteractionType >::BubbleBubbleRepulsion().
computeLoadForces()
template<class BRepulsionInteractionType > virtual void BubbleBubbleRepulsion< BRepulsionInteractionType >::computeLoadForces () inline virtual
Compute the load forces on beads from this interaction.
Implements BubbleInteractions.
Definition at line 48 of file BubbleBubbleRepulsion.h.
getName()
template<class BRepulsionInteractionType > virtual const string BubbleBubbleRepulsion< BRepulsionInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BubbleInteractions.
Definition at line 53 of file BubbleBubbleRepulsion.h.
getNeighborList()
template<class BRepulsionInteractionType > virtual NeighborList* BubbleBubbleRepulsion< BRepulsionInteractionType >::getNeighborList () inline virtual
Get the neighbor list for this interaction.
Implements BubbleInteractions.
Definition at line 51 of file BubbleBubbleRepulsion.h.
References BubbleBubbleRepulsion< BRepulsionInteractionType >::_neighborList.
Member Data Documentation
_bubbleCulprit
Bubble* BubbleInteractions::_bubbleCulprit = nullptr protected inherited
In the case of an error.
Definition at line 32 of file BubbleInteractions.h.
Referenced by BubbleFF::whoIsCulprit().
_FFType
template<class BRepulsionInteractionType > BRepulsionInteractionType BubbleBubbleRepulsion< BRepulsionInteractionType >::_FFType private
Definition at line 34 of file BubbleBubbleRepulsion.h.
_neighborList
template<class BRepulsionInteractionType > BubbleBubbleNL* BubbleBubbleRepulsion< BRepulsionInteractionType >::_neighborList private
Neighbor list of Bubble-Bubble.
Definition at line 35 of file BubbleBubbleRepulsion.h.
Referenced by BubbleBubbleRepulsion< BRepulsionInteractionType >::getNeighborList().
_otherCulprit
Component* BubbleInteractions::_otherCulprit = nullptr protected inherited
In the case of an error.
Definition at line 33 of file BubbleInteractions.h.
Referenced by BubbleFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Bubble/BubbleBubbleRepulsion.h
src/Mechanics/ForceField/Bubble/BubbleBubbleRepulsion.cpp