M3Sym: CLinker Class Reference
CLinker Class Reference
To represent the chemical component of a Linker.
#include <CLinker.h>
Public Member Functions
CLinker (Compartment *c)
~CLinker ()
CLinker (const CLinker &rhs, Compartment *c)
Copy constructor, standard.
CLinker & operator= (CLinker &rhs)=delete
Assignment is not allowed.
virtual CLinker * clone (Compartment *c)
Clone, calls copy constructor.
void setLinker (Linker *linker)
Set parent.
Linker * getLinker ()
Get parent.
void setFirstSpecies (SpeciesBound *species)
Set first species.
SpeciesBound * getFirstSpecies ()
Get first species.
void setSecondSpecies (SpeciesBound *species)
Set second species.
SpeciesBound * getSecondSpecies ()
Get second species.
Compartment * getCompartment ()
Get compartment that this CBound is in.
Protected Attributes
SpeciesBound * _firstSpecies = nullptr
Corresponding first species on Filament.
SpeciesBound * _secondSpecies = nullptr
Corresponding second species on Filament.
Compartment * _compartment
Compartment this CBound is in.
Private Attributes
Linker * _pLinker
Pointer to parent.
Detailed Description
To represent the chemical component of a Linker.
The CLinker class contains chemical info of the parent Linker.
Definition at line 30 of file CLinker.h.
Constructor & Destructor Documentation
CLinker::CLinker (Compartment * c) inline
Definition at line 36 of file CLinker.h.
Referenced by clone().
CLinker::~CLinker () inline
Definition at line 37 of file CLinker.h.
CLinker::CLinker (const CLinker & rhs, Compartment * c) inline
Copy constructor, standard.
Definition at line 40 of file CLinker.h.
References CBound::_firstSpecies, CBound::_secondSpecies, CBound::setFirstSpecies(), and CBound::setSecondSpecies().
Member Function Documentation
virtual CLinker* CLinker::clone (Compartment * c) inline virtual
Clone, calls copy constructor.
Definition at line 50 of file CLinker.h.
References CLinker().
Compartment* CBound::getCompartment () inline inherited
Get compartment that this CBound is in.
Definition at line 75 of file CBound.h.
References CBound::_compartment.
SpeciesBound* CBound::getFirstSpecies () inline inherited
Get first species.
Definition at line 61 of file CBound.h.
References CBound::_firstSpecies.
Referenced by CMonomer::CMonomer(), MotorWalkingForwardCallback::operator()(), MotorWalkingBackwardCallback::operator()(), MotorMovingCylinderForwardCallback::operator()(), and MotorMovingCylinderBackwardCallback::operator()().
Linker* CLinker::getLinker () inline
Get parent.
Definition at line 57 of file CLinker.h.
References _pLinker.
SpeciesBound* CBound::getSecondSpecies () inline inherited
Get second species.
Definition at line 72 of file CBound.h.
References CBound::_secondSpecies.
CLinker& CLinker::operator= (CLinker & rhs) delete
Assignment is not allowed.
void CBound::setFirstSpecies (SpeciesBound * species) inline inherited
Set first species.
remove from old first species
Definition at line 53 of file CBound.h.
References CBound::_firstSpecies, SpeciesBound::removeCBound(), and SpeciesBound::setCBound().
Referenced by CLinker(), CMonomer::CMonomer(), CMotorGhost::CMotorGhost(), MotorWalkingForwardCallback::operator()(), MotorWalkingBackwardCallback::operator()(), MotorMovingCylinderForwardCallback::operator()(), MotorMovingCylinderBackwardCallback::operator()(), Linker::updatePosition(), and MotorGhost::updatePosition().
void CLinker::setLinker (Linker * linker) inline
Set parent.
Definition at line 55 of file CLinker.h.
References _pLinker.
void CBound::setSecondSpecies (SpeciesBound * species) inline inherited
Set second species.
remove from old second species
Definition at line 64 of file CBound.h.
References CBound::_secondSpecies, SpeciesBound::removeCBound(), and SpeciesBound::setCBound().
Referenced by CLinker(), CMonomer::CMonomer(), CMotorGhost::CMotorGhost(), MotorWalkingForwardCallback::operator()(), MotorWalkingBackwardCallback::operator()(), MotorMovingCylinderForwardCallback::operator()(), MotorMovingCylinderBackwardCallback::operator()(), Linker::updatePosition(), and MotorGhost::updatePosition().
Member Data Documentation
Compartment* CBound::_compartment protected inherited
Compartment this CBound is in.
Definition at line 37 of file CBound.h.
Referenced by CBound::getCompartment().
SpeciesBound* CBound::_firstSpecies = nullptr protected inherited
Corresponding first species on Filament.
Definition at line 34 of file CBound.h.
Referenced by CLinker(), CMotorGhost::CMotorGhost(), CBound::getFirstSpecies(), CBound::setFirstSpecies(), and CBound::~CBound().
Linker* CLinker::_pLinker private
Pointer to parent.
Definition at line 33 of file CLinker.h.
Referenced by getLinker(), and setLinker().
SpeciesBound* CBound::_secondSpecies = nullptr protected inherited
Corresponding second species on Filament.
Definition at line 35 of file CBound.h.
Referenced by CLinker(), CMotorGhost::CMotorGhost(), CBound::getSecondSpecies(), CBound::setSecondSpecies(), and CBound::~CBound().
The documentation for this class was generated from the following file:
M3SYM/Structure/CLinker.h