MEDYAN: BubbleBubbleNL Class Reference
BubbleBubbleNL Class Reference
An implementation of NeighborList for Bubble-Bubble interactions.
#include <NeighborListImpl.h>
Public Member Functions
BubbleBubbleNL (float rMax)
virtual void addNeighbor (Neighbor *n)
Add neighbor.
virtual void removeNeighbor (Neighbor *n)
Remove a neighbor if possible.
virtual void reset ()
Re-initialize the neighborlist.
vector< Bubble * > getNeighbors (Bubble *bb)
Get all Bubble neighbors of a bubble.
virtual void addDynamicNeighbor (DynamicNeighbor *n)
The implementation of these functions calls the static version, all Bubbles are dynamic.
virtual void removeDynamicNeighbor (DynamicNeighbor *n)
The implementation of these functions calls the static version, all Bubbles are dynamic.
Protected Attributes
float _rMax
max distance cutoff
float _rMin
min distance cutoff
Private Member Functions
void updateNeighbors (Bubble *bb)
Helper function to update neighbors.
Private Attributes
unordered_map< Bubble *, vector< Bubble * > > _list
The neighbors list, as a hash map.
Detailed Description
An implementation of NeighborList for Bubble-Bubble interactions.
Note
- This is currently implemented as a half list only
Definition at line 120 of file NeighborListImpl.h.
Constructor & Destructor Documentation
BubbleBubbleNL()
BubbleBubbleNL::BubbleBubbleNL (float rMax) inline
Definition at line 130 of file NeighborListImpl.h.
References CylinderCylinderNL::addDynamicNeighbor(), CylinderCylinderNL::addNeighbor(), and CylinderCylinderNL::removeNeighbor().
Member Function Documentation
addDynamicNeighbor()
virtual void BubbleBubbleNL::addDynamicNeighbor (DynamicNeighbor * n) inline virtual
The implementation of these functions calls the static version, all Bubbles are dynamic.
Implements NeighborList.
Definition at line 138 of file NeighborListImpl.h.
addNeighbor()
void BubbleBubbleNL::addNeighbor (Neighbor * n) virtual
Add neighbor.
Implements NeighborList.
Definition at line 289 of file NeighborListImpl.cpp.
getNeighbors()
vector< Bubble * > BubbleBubbleNL::getNeighbors (Bubble * bb)
Get all Bubble neighbors of a bubble.
Definition at line 323 of file NeighborListImpl.cpp.
removeDynamicNeighbor()
virtual void BubbleBubbleNL::removeDynamicNeighbor (DynamicNeighbor * n) inline virtual
The implementation of these functions calls the static version, all Bubbles are dynamic.
Implements NeighborList.
Definition at line 139 of file NeighborListImpl.h.
References CylinderCylinderNL::getNeighbors(), CylinderCylinderNL::removeNeighbor(), and CylinderCylinderNL::reset().
removeNeighbor()
void BubbleBubbleNL::removeNeighbor (Neighbor * n) virtual
Remove a neighbor if possible.
Implements NeighborList.
Definition at line 299 of file NeighborListImpl.cpp.
reset()
void BubbleBubbleNL::reset () virtual
Re-initialize the neighborlist.
Implements NeighborList.
Definition at line 314 of file NeighborListImpl.cpp.
References Bubble::getBubbles().
updateNeighbors()
void BubbleBubbleNL::updateNeighbors (Bubble * bb) private
Helper function to update neighbors.
Definition at line 272 of file NeighborListImpl.cpp.
References Bubble::coordinate, Bubble::getBubbles(), Bubble::getID(), and mathfunc::twoPointDistance().
Member Data Documentation
_list
unordered_map<Bubble*, vector<Bubble*> > BubbleBubbleNL::_list private
The neighbors list, as a hash map.
Definition at line 123 of file NeighborListImpl.h.
_rMax
float NeighborList::_rMax protected inherited
max distance cutoff
Definition at line 36 of file NeighborList.h.
_rMin
float NeighborList::_rMin protected inherited
min distance cutoff
Definition at line 37 of file NeighborList.h.
The documentation for this class was generated from the following files:
src/Structure/NeighborListImpl.h
src/Structure/NeighborListImpl.cpp