MEDYAN: CylinderVolumeFF Class Reference
CylinderVolumeFF Class Reference
An implementation of the ForceField class that calculates Cylinder volume interactions.
#include <CylinderVolumeFF.h>
Public Member Functions
CylinderVolumeFF (string &interaction)
Initialize the volume forcefields.
virtual string getName ()
Get the name of this forcefield.
virtual void whoIsCulprit ()
In the case of a calculation error, print the culprit of the FF error.
virtual double computeEnergy (double d)
Compute total energy of this forcefield in the system.
virtual void computeForces ()
Compute forces of this forcefield in the system.
virtual void computeForcesAux ()
Compute auxiliary forces of this forcefield in the system.
virtual void computeLoadForces ()
Compute all load forces on beads in this system.
virtual vector< NeighborList * > getNeighborLists ()
Get all neighbor lists associated with a ForceField.
Private Attributes
vector< unique_ptr< CylinderVolumeInteractions > > _cylinderVolInteractionVector
Vector of initialized volume interactions.
CylinderVolumeInteractions * _culpritInteraction
Culprit in case of error.
Detailed Description
An implementation of the ForceField class that calculates Cylinder volume interactions.
Definition at line 29 of file CylinderVolumeFF.h.
Constructor & Destructor Documentation
CylinderVolumeFF()
CylinderVolumeFF::CylinderVolumeFF (string & interaction)
Initialize the volume forcefields.
Definition at line 21 of file CylinderVolumeFF.cpp.
References _cylinderVolInteractionVector.
Member Function Documentation
computeEnergy()
double CylinderVolumeFF::computeEnergy (double d) virtual
Compute total energy of this forcefield in the system.
Returns
the energy value if valid. If an inf or NaN value has been calculated, return -1.
Implements ForceField.
Definition at line 45 of file CylinderVolumeFF.cpp.
References _culpritInteraction, and _cylinderVolInteractionVector.
Referenced by getName().
computeForces()
void CylinderVolumeFF::computeForces () virtual
Compute forces of this forcefield in the system.
Update Bead forces accordingly.
Implements ForceField.
Definition at line 65 of file CylinderVolumeFF.cpp.
References _cylinderVolInteractionVector.
Referenced by getName().
computeForcesAux()
void CylinderVolumeFF::computeForcesAux () virtual
Compute auxiliary forces of this forcefield in the system.
Update Bead auxiliary forces accordingly.
Implements ForceField.
Definition at line 71 of file CylinderVolumeFF.cpp.
References _cylinderVolInteractionVector.
Referenced by getName().
computeLoadForces()
virtual void CylinderVolumeFF::computeLoadForces () inline virtual
Compute all load forces on beads in this system.
Updates all Bead's load force components for Reaction updating.
Implements ForceField.
Definition at line 47 of file CylinderVolumeFF.h.
References getNeighborLists().
getName()
virtual string CylinderVolumeFF::getName () inline virtual
Get the name of this forcefield.
Implements ForceField.
Definition at line 40 of file CylinderVolumeFF.h.
References computeEnergy(), computeForces(), computeForcesAux(), and whoIsCulprit().
getNeighborLists()
vector< NeighborList * > CylinderVolumeFF::getNeighborLists () virtual
Get all neighbor lists associated with a ForceField.
Implements ForceField.
Definition at line 77 of file CylinderVolumeFF.cpp.
References _cylinderVolInteractionVector.
Referenced by computeLoadForces().
whoIsCulprit()
void CylinderVolumeFF::whoIsCulprit () virtual
In the case of a calculation error, print the culprit of the FF error.
Typically, will just print the Trackable element where the error came from.
Implements ForceField.
Definition at line 32 of file CylinderVolumeFF.cpp.
References _culpritInteraction, CylinderVolumeInteractions::_cylinderCulprit1, CylinderVolumeInteractions::_cylinderCulprit2, CylinderVolumeInteractions::getName(), and Cylinder::printSelf().
Referenced by getName().
Member Data Documentation
_culpritInteraction
CylinderVolumeInteractions* CylinderVolumeFF::_culpritInteraction private
Culprit in case of error.
Definition at line 35 of file CylinderVolumeFF.h.
Referenced by computeEnergy(), and whoIsCulprit().
_cylinderVolInteractionVector
vector<unique_ptr<CylinderVolumeInteractions> > CylinderVolumeFF::_cylinderVolInteractionVector private
Vector of initialized volume interactions.
Definition at line 33 of file CylinderVolumeFF.h.
Referenced by computeEnergy(), computeForces(), computeForcesAux(), CylinderVolumeFF(), and getNeighborLists().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Volume/CylinderVolumeFF.h
src/Mechanics/ForceField/Volume/CylinderVolumeFF.cpp