M3Sym: SpeciesBound Class Reference
SpeciesBound Class Reference
Used for species that can be bound to a filament.
#include <Species.h>
Public Member Functions
SpeciesBound ()
Default constructor.
SpeciesBound (const string &name, species_copy_t n=0, species_copy_t ulim=1)
The main constructor.
SpeciesBound (const SpeciesBound &rhs)
Copy constructor.
SpeciesBound (SpeciesBound &&rhs) noexcept
Move constructor.
SpeciesBound & operator= (const SpeciesBound &rhs)
Regular Assignment.
SpeciesBound & operator= (SpeciesBound &&rhs)
Move assignment.
virtual SpeciesBound * clone ()
virtual string getFullName () const
Return the full name of this Species in a string format (e.g. "Arp2/3{Bound}".
~SpeciesBound () noexcept
Default destructor.
void setCBound (CBound *cBound)
Setter and getter for CBound.
CBound * getCBound ()
void removeCBound ()
remove cBound ptr
Composite * getParent ()
void setParent (Composite *other)
bool hasParent () const
Composite * getRoot ()
RSpecies & getRSpecies ()
Return a reference to RSpecies.
const RSpecies & getRSpecies () const
Return a constant reference to RSpecies.
void setN (species_copy_t n)
Sets the copy number for this Species.
species_copy_t getN () const
Return the current copy number of this Species.
string getName () const
Return this Species' name.
int getMolecule () const
Return the molecule index associated with this Species' (as int)
virtual size_t countSpecies () const
Protected Attributes
CBound * _cBound = nullptr
CBound object.
Detailed Description
Used for species that can be bound to a filament.
These species can not move cross-compartment. Contains a pointer to a CBound object that this represents.
Definition at line 430 of file Species.h.
Constructor & Destructor Documentation
SpeciesBound::SpeciesBound () inline
Default constructor.
Definition at line 437 of file Species.h.
Referenced by clone().
SpeciesBound::SpeciesBound (const string & name, species_copy_t n = 0, species_copy_t ulim = 1) inline
The main constructor.
Parameters
name - Example, "G-Actin" or "Arp2/3"
n - copy number
Definition at line 442 of file Species.h.
SpeciesBound::SpeciesBound (const SpeciesBound & rhs) inline
Copy constructor.
Definition at line 446 of file Species.h.
SpeciesBound::SpeciesBound (SpeciesBound && rhs) inline noexcept
Move constructor.
Definition at line 449 of file Species.h.
SpeciesBound::~SpeciesBound () inline noexcept
Default destructor.
Definition at line 474 of file Species.h.
Member Function Documentation
virtual SpeciesBound* SpeciesBound::clone () inline virtual
Reimplemented from Species.
Reimplemented in SpeciesMotor, and SpeciesLinker.
Definition at line 466 of file Species.h.
References SpeciesBound().
Referenced by CMonomer::CMonomer().
virtual size_t Species::countSpecies () const inline virtual inherited
Definition at line 295 of file Species.h.
CBound* SpeciesBound::getCBound () inline
Definition at line 478 of file Species.h.
References _cBound.
Referenced by CMonomer::CMonomer(), UnbindingCallback::operator()(), MotorWalkingForwardCallback::operator()(), MotorWalkingBackwardCallback::operator()(), MotorMovingCylinderForwardCallback::operator()(), and MotorMovingCylinderBackwardCallback::operator()().
virtual string SpeciesBound::getFullName () const inline virtual
Return the full name of this Species in a string format (e.g. "Arp2/3{Bound}".
Reimplemented from Species.
Reimplemented in SpeciesMotor, and SpeciesLinker.
Definition at line 471 of file Species.h.
References Species::getName().
int Species::getMolecule () const inline inherited
Return the molecule index associated with this Species' (as int)
Definition at line 241 of file Species.h.
References Species::_molecule.
Referenced by Compartment::addSpeciesBound(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPlusEnd(), Compartment::addSpeciesUnique(), and Compartment::setDiffusionRate().
species_copy_t Species::getN () const inline inherited
Return the current copy number of this Species.
Definition at line 230 of file Species.h.
References Species::_rspecies, and RSpecies::getN().
Referenced by Linker::Linker(), main(), MotorGhost::MotorGhost(), operator<<(), Species::operator=(), CMonomer::print(), Species::Species(), Linker::~Linker(), and MotorGhost::~MotorGhost().
string Species::getName () const inline inherited
Return this Species' name.
Definition at line 238 of file Species.h.
References Species::_molecule, SpeciesNamesDB::Instance(), and SpeciesNamesDB::intToString().
Referenced by Species::getFullName(), SpeciesBulk::getFullName(), SpeciesDiffusing::getFullName(), SpeciesFilament::getFullName(), getFullName(), SpeciesLinker::getFullName(), SpeciesMotor::getFullName(), SpeciesPlusEnd::getFullName(), SpeciesMinusEnd::getFullName(), and CMonomer::print().
Composite* Species::getParent () inline inherited
Definition at line 209 of file Species.h.
References Species::_parent.
Referenced by Species::getRoot(), and main().
Composite * Species::getRoot () inherited
Definition at line 36 of file Species.cpp.
References Species::getParent(), Component::getRoot(), and Species::hasParent().
RSpecies& Species::getRSpecies () inline inherited
Return a reference to RSpecies.
Notice that value copying won't be allowed because RSpecies is not copyable.
Definition at line 219 of file Species.h.
References Species::_rspecies.
Referenced by ChemSignal::connect(), SimpleManagerImpl::initializeCCylinder(), Linker::Linker(), main(), MotorGhost::MotorGhost(), Linker::~Linker(), and MotorGhost::~MotorGhost().
const RSpecies& Species::getRSpecies () const inline inherited
Return a constant reference to RSpecies.
Definition at line 222 of file Species.h.
References Species::_rspecies.
bool Species::hasParent () const inline inherited
Definition at line 213 of file Species.h.
References Species::_parent.
Referenced by Species::getRoot().
SpeciesBound& SpeciesBound::operator= (const SpeciesBound & rhs) inline
Regular Assignment.
Definition at line 453 of file Species.h.
References _cBound, and Species::operator=().
Referenced by SpeciesLinker::operator=(), and SpeciesMotor::operator=().
SpeciesBound& SpeciesBound::operator= (SpeciesBound && rhs) inline
Move assignment.
Definition at line 460 of file Species.h.
References Species::operator=().
void SpeciesBound::removeCBound () inline
remove cBound ptr
Definition at line 481 of file Species.h.
References _cBound.
Referenced by CBound::setFirstSpecies(), CBound::setSecondSpecies(), and CBound::~CBound().
void SpeciesBound::setCBound (CBound * cBound) inline
Setter and getter for CBound.
Definition at line 477 of file Species.h.
References _cBound.
Referenced by CBound::setFirstSpecies(), and CBound::setSecondSpecies().
void Species::setN (species_copy_t n) inline inherited
Sets the copy number for this Species.
Parameters
n should be a non-negative number, but no checking is done in run time
Note
The operation does not emit any signals about the copy number change.
Definition at line 227 of file Species.h.
References Species::_rspecies, and RSpecies::setN().
void Species::setParent (Composite * other) inline inherited
Definition at line 211 of file Species.h.
References Species::_parent.
Referenced by Compartment::addSpeciesBound(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPlusEnd(), and Compartment::addSpeciesUnique().
Member Data Documentation
CBound* SpeciesBound::_cBound = nullptr protected
CBound object.
Definition at line 433 of file Species.h.
Referenced by getCBound(), operator=(), removeCBound(), and setCBound().
The documentation for this class was generated from the following file:
M3SYM/Structure/Species.h