MEDYAN: LinkerStretchingHarmonic Class Reference
LinkerStretchingHarmonic Class Reference
A harmonic potential used by the LinkerStretching template.
#include <LinkerStretchingHarmonic.h>
Public Member Functions
double energy (Bead *, Bead *, Bead *, Bead *, double position1, double position2, double kStretch, double eqLength)
double energy (Bead *, Bead *, Bead *, Bead *, double position1, double position2, double kStretch, double eqLength, double d)
double forces (Bead *, Bead *, Bead *, Bead *, double position1, double position2, double kStretch, double eqLength)
double forcesAux (Bead *, Bead *, Bead *, Bead *, double position1, double position2, double kStretch, double eqLength)
Detailed Description
A harmonic potential used by the LinkerStretching template.
Definition at line 23 of file LinkerStretchingHarmonic.h.
Member Function Documentation
energy() [1/2]
double LinkerStretchingHarmonic::energy (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double position1, double position2, double kStretch, double eqLength)
Definition at line 22 of file LinkerStretchingHarmonic.cpp.
References Bead::coordinate, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
energy() [2/2]
double LinkerStretchingHarmonic::energy (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double position1, double position2, double kStretch, double eqLength, double d)
Definition at line 33 of file LinkerStretchingHarmonic.cpp.
References Bead::coordinate, Bead::force, mathfunc::midPointCoordinateStretched(), and mathfunc::twoPointDistance().
forces()
double LinkerStretchingHarmonic::forces (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double position1, double position2, double kStretch, double eqLength)
Definition at line 46 of file LinkerStretchingHarmonic.cpp.
References Bead::coordinate, Bead::force, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
forcesAux()
double LinkerStretchingHarmonic::forcesAux (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double position1, double position2, double kStretch, double eqLength)
Definition at line 82 of file LinkerStretchingHarmonic.cpp.
References Bead::coordinate, Bead::forceAux, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Linker/LinkerStretchingHarmonic.h
src/Mechanics/ForceField/Linker/LinkerStretchingHarmonic.cpp