MEDYAN: MTOCFilamentDist Class Reference
MTOCFilamentDist Class Reference
An implementation of FilamentInitialzer that creates a random MTOC configuration.
#include <FilamentInitializer.h>
Public Member Functions
MTOCFilamentDist (vector< double > coord, double radius)
Constructor sets parameters of MTOC.
FilamentData createFilaments (Boundary *b, int numFilaments, int filamentType, int lenFilaments)
Returns a vector of tuples representing the Filament type and beginning and end coordinates, similar to the structure of manual parsing.
Private Attributes
vector< double > _coordMTOC
Coordinates of the MTOC to make filaments around.
double _radius
Radius of MTOC.
Detailed Description
An implementation of FilamentInitialzer that creates a random MTOC configuration.
Definition at line 69 of file FilamentInitializer.h.
Constructor & Destructor Documentation
MTOCFilamentDist()
MTOCFilamentDist::MTOCFilamentDist (vector< double > coord, double radius) inline
Constructor sets parameters of MTOC.
Definition at line 77 of file FilamentInitializer.h.
References FilamentInitializer::createFilaments().
Member Function Documentation
createFilaments()
FilamentData MTOCFilamentDist::createFilaments (Boundary * b, int numFilaments, int filamentType, int lenFilaments) virtual
Returns a vector of tuples representing the Filament type and beginning and end coordinates, similar to the structure of manual parsing.
Implements FilamentInitializer.
Definition at line 166 of file FilamentInitializer.cpp.
References SysParams::Geometry(), mathfunc::nextPointProjection(), mathfunc::normalizedVector(), Rand::randDouble(), and mathfunc::twoPointDirection().
Member Data Documentation
_coordMTOC
vector<double> MTOCFilamentDist::_coordMTOC private
Coordinates of the MTOC to make filaments around.
Definition at line 72 of file FilamentInitializer.h.
_radius
double MTOCFilamentDist::_radius private
Radius of MTOC.
Definition at line 73 of file FilamentInitializer.h.
The documentation for this class was generated from the following files:
src/FilamentInitializer.h
src/FilamentInitializer.cpp