MEDYAN: LinkerFF Class Reference
LinkerFF Class Reference
An implementation of the ForceField class that calculates Linker stretching, bending, and twisting.
#include <LinkerFF.h>
Public Member Functions
LinkerFF (string &stretching, string &bending, string &twisting)
Constructor, intializes stretching, bending, and twisting forces.
virtual string getName ()
Get the name of this forcefield.
virtual void whoIsCulprit ()
In the case of a calculation error, print the culprit of the FF error.
virtual double computeEnergy (double d)
Compute total energy of this forcefield in the system.
virtual void computeForces ()
Compute forces of this forcefield in the system.
virtual void computeForcesAux ()
Compute auxiliary forces of this forcefield in the system.
virtual void computeLoadForces ()
Compute all load forces on beads in this system.
virtual vector< NeighborList * > getNeighborLists ()
Get all neighbor lists associated with a ForceField.
Private Attributes
vector< unique_ptr< LinkerInteractions > > _linkerInteractionVector
Vector of initialized linker interactions.
LinkerInteractions * _culpritInteraction
The culprit in the case of an error.
Detailed Description
An implementation of the ForceField class that calculates Linker stretching, bending, and twisting.
Definition at line 29 of file LinkerFF.h.
Constructor & Destructor Documentation
LinkerFF()
LinkerFF::LinkerFF (string & stretching, string & bending, string & twisting)
Constructor, intializes stretching, bending, and twisting forces.
Definition at line 21 of file LinkerFF.cpp.
References _linkerInteractionVector.
Member Function Documentation
computeEnergy()
double LinkerFF::computeEnergy (double d) virtual
Compute total energy of this forcefield in the system.
Returns
the energy value if valid. If an inf or NaN value has been calculated, return -1.
Implements ForceField.
Definition at line 45 of file LinkerFF.cpp.
References _culpritInteraction, and _linkerInteractionVector.
Referenced by getName().
computeForces()
void LinkerFF::computeForces () virtual
Compute forces of this forcefield in the system.
Update Bead forces accordingly.
Implements ForceField.
Definition at line 65 of file LinkerFF.cpp.
References _linkerInteractionVector.
Referenced by getName().
computeForcesAux()
void LinkerFF::computeForcesAux () virtual
Compute auxiliary forces of this forcefield in the system.
Update Bead auxiliary forces accordingly.
Implements ForceField.
Definition at line 71 of file LinkerFF.cpp.
References _linkerInteractionVector.
Referenced by getName().
computeLoadForces()
virtual void LinkerFF::computeLoadForces () inline virtual
Compute all load forces on beads in this system.
Updates all Bead's load force components for Reaction updating.
Implements ForceField.
Definition at line 49 of file LinkerFF.h.
getName()
virtual string LinkerFF::getName () inline virtual
Get the name of this forcefield.
Implements ForceField.
Definition at line 42 of file LinkerFF.h.
References computeEnergy(), computeForces(), computeForcesAux(), and whoIsCulprit().
getNeighborLists()
virtual vector<NeighborList*> LinkerFF::getNeighborLists () inline virtual
Get all neighbor lists associated with a ForceField.
Implements ForceField.
Definition at line 51 of file LinkerFF.h.
whoIsCulprit()
void LinkerFF::whoIsCulprit () virtual
In the case of a calculation error, print the culprit of the FF error.
Typically, will just print the Trackable element where the error came from.
Implements ForceField.
Definition at line 33 of file LinkerFF.cpp.
References _culpritInteraction, LinkerInteractions::_linkerCulprit, LinkerInteractions::getName(), and Linker::printSelf().
Referenced by getName().
Member Data Documentation
_culpritInteraction
LinkerInteractions* LinkerFF::_culpritInteraction private
The culprit in the case of an error.
Definition at line 36 of file LinkerFF.h.
Referenced by computeEnergy(), and whoIsCulprit().
_linkerInteractionVector
vector<unique_ptr<LinkerInteractions> > LinkerFF::_linkerInteractionVector private
Vector of initialized linker interactions.
Definition at line 33 of file LinkerFF.h.
Referenced by computeEnergy(), computeForces(), computeForcesAux(), and LinkerFF().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Linker/LinkerFF.h
src/Mechanics/ForceField/Linker/LinkerFF.cpp