MEDYAN: LinkerStretching< LStretchingInteractionType > Class Template Reference
LinkerStretching< LStretchingInteractionType > Class Template Reference
Represents a Linker stretching interaction.
#include <LinkerStretching.h>
Public Member Functions
virtual double computeEnergy (double d)
Temlate specializations.
virtual void computeForces ()
Compute the forces of this interaction.
virtual void computeForcesAux ()
Compute the auxiliary forces of this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
Linker * _linkerCulprit = nullptr
The linker in the case of an error.
Private Attributes
LStretchingInteractionType _FFType
Detailed Description
template<class LStretchingInteractionType>
class LinkerStretching< LStretchingInteractionType >
Represents a Linker stretching interaction.
Definition at line 26 of file LinkerStretching.h.
Member Function Documentation
computeEnergy()
template<class LStretchingInteractionType > template double LinkerStretching< LStretchingInteractionType >::computeEnergy (double d) virtual
Temlate specializations.
Implements LinkerInteractions.
Definition at line 23 of file LinkerStretching.cpp.
References Linker::getLinkers().
Referenced by LinkerStretching< LStretchingInteractionType >::computeForcesAux().
computeForces()
template<class LStretchingInteractionType > template void LinkerStretching< LStretchingInteractionType >::computeForces () virtual
Compute the forces of this interaction.
Implements LinkerInteractions.
Definition at line 59 of file LinkerStretching.cpp.
References Linker::getLinkers().
Referenced by LinkerStretching< LStretchingInteractionType >::computeForcesAux().
computeForcesAux()
template<class LStretchingInteractionType > template void LinkerStretching< LStretchingInteractionType >::computeForcesAux () virtual
Compute the auxiliary forces of this interaction.
Implements LinkerInteractions.
Definition at line 80 of file LinkerStretching.cpp.
References LinkerStretching< LStretchingInteractionType >::computeEnergy(), LinkerStretching< LStretchingInteractionType >::computeForces(), and Linker::getLinkers().
getName()
template<class LStretchingInteractionType > virtual const string LinkerStretching< LStretchingInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements LinkerInteractions.
Definition at line 36 of file LinkerStretching.h.
Member Data Documentation
_FFType
template<class LStretchingInteractionType > LStretchingInteractionType LinkerStretching< LStretchingInteractionType >::_FFType private
Definition at line 29 of file LinkerStretching.h.
_linkerCulprit
Linker* LinkerInteractions::_linkerCulprit = nullptr protected inherited
The linker in the case of an error.
Definition at line 29 of file LinkerInteractions.h.
Referenced by LinkerFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Linker/LinkerStretching.h
src/Mechanics/ForceField/Linker/LinkerStretching.cpp