MEDYAN: HalfSphereZBoundaryElement Class Reference
HalfSphereZBoundaryElement Class Reference
A half-sphere implementation of a BoundaryElement.
#include <BoundaryElementImpl.h>
Public Member Functions
HalfSphereZBoundaryElement (vector< double > coords, double radius, bool up, double repulsConst, double screenLength)
Constructor, sets parameters of equation.
virtual double distance (const vector< double > &point)
Implement for all boundary elements Returns the distance from a given point to this boundary element.
virtual double stretchedDistance (const vector< double > &point, const vector< double > &force, double d)
Returns stretched distance, similar to distance above.
virtual const vector< double > normal (const vector< double > &point)
Returns normal vector of point to plane.
virtual void updateCoords (const vector< double > newCoords)
update the coordinates of the boundary element
const vector< double > & getCoords ()
return coordinates of boundary element
virtual void printSelf ()
Prints information about this node. Useful for debugging.
virtual int getType ()
Return the type of this element as an integer index.
virtual bool apply (Visitor &v)
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
virtual bool apply (SpeciesVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual size_t numberOfChildren () const
Returns the number of children of this node.
virtual bool isComposite () const
Returns true if this node is a Composite node.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
virtual size_t numberOfSpecies () const
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t numberOfReactions () const
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual string getFullName () const
Return a string indicating the full name of this node (presumably used mainly for debugging)
virtual size_t countDescendents () const
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const
Return the number of Species contained under this node's hieararchy.
virtual size_t countReactions () const
Return the number of ReactionBase objects contained under this node's hieararchy.
virtual double getRepulsionConst ()
Getter for mechanical parameters.
virtual double getScreeningLength ()
Getter for mechanical parameters.
virtual void addToSubSystem ()
SubSystem management, inherited from Trackable.
virtual void removeFromSubSystem ()
SubSystem management, inherited from Trackable.
Static Public Member Functions
static const vector< BoundaryElement * > & getBoundaryElements ()
Get all instances of this class from the SubSystem.
static int numBoundaryElements ()
Get the number of boundary elements in this system.
Protected Attributes
vector< double > _coords
coordinates
double _kRep
Repulsion constant.
double _r0
Screening length.
bool _movable
Object type.
bool _reactable
Object type.
bool _dneighbor
Object type.
bool _neighbor
Object type.
Static Protected Attributes
static SubSystem * _subSystem = 0
A subsystem pointer for every trackable.
Private Attributes
double _radius
Radius of half sphere.
bool _up
Whether the half sphere faces up or down.
Friends
class BoundaryCapsule
Detailed Description
A half-sphere implementation of a BoundaryElement.
Definition at line 192 of file BoundaryElementImpl.h.
Constructor & Destructor Documentation
HalfSphereZBoundaryElement()
HalfSphereZBoundaryElement::HalfSphereZBoundaryElement (vector< double > coords, double radius, bool up, double repulsConst, double screenLength) inline
Constructor, sets parameters of equation.
Definition at line 202 of file BoundaryElementImpl.h.
Member Function Documentation
addToSubSystem()
virtual void BoundaryElement::addToSubSystem () inline virtual inherited
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 100 of file BoundaryElement.h.
Referenced by BoundaryElement::getScreeningLength().
apply() [1/3]
bool Component::apply (Visitor & v) virtual inherited
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
However, the ConditionalVisitor allows the visit() function to be applied only selectively to nodes that conform to specific criteria.
Reimplemented in Composite.
Definition at line 26 of file Component.cpp.
References Visitor::visit().
Referenced by Component::~Component().
apply() [2/3]
virtual bool Component::apply (SpeciesVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented in Composite.
Definition at line 61 of file Component.h.
References Component::apply_impl().
apply() [3/3]
virtual bool Component::apply (ReactionVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented in Composite.
Definition at line 69 of file Component.h.
References Component::apply_impl().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
countDescendents()
virtual size_t Component::countDescendents () const inline virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 118 of file Component.h.
countReactions()
virtual size_t Component::countReactions () const inline virtual inherited
Return the number of ReactionBase objects contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 126 of file Component.h.
References Component::getType(), and Component::printSelf().
countSpecies()
virtual size_t Component::countSpecies () const inline virtual inherited
Return the number of Species contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 122 of file Component.h.
Referenced by Linker::getLifetimes(), MotorGhost::getWalkLengths(), BranchingPoint::numBranchingPoints(), and Chemistry::print().
distance()
virtual double HalfSphereZBoundaryElement::distance (const vector< double > & point) inline virtual
Implement for all boundary elements Returns the distance from a given point to this boundary element.
Returns
- 1) positive number if point is within boundary element 2) Negative number if point is outside boundary element 3) Infinity if point is not in domain of this boundary element
Implements BoundaryElement.
Definition at line 210 of file BoundaryElementImpl.h.
References mathfunc::twoPointDistance().
getBoundaryElements()
static const vector<BoundaryElement*>& BoundaryElement::getBoundaryElements () inline static inherited
Get all instances of this class from the SubSystem.
Definition at line 105 of file BoundaryElement.h.
References Database< T >::getElements().
Referenced by BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForces(), BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderNL::reset(), and BoundaryBubbleNL::reset().
getCoords()
const vector<double>& BoundaryElement::getCoords () inline inherited
return coordinates of boundary element
Definition at line 73 of file BoundaryElement.h.
References BoundaryElement::_coords, BoundaryElement::_kRep, BoundaryElement::distance(), BoundaryElement::getRepulsionConst(), BoundaryElement::normal(), BoundaryElement::stretchedDistance(), and BoundaryElement::updateCoords().
getFullName()
virtual string Component::getFullName () const inline virtual inherited
Return a string indicating the full name of this node (presumably used mainly for debugging)
Reimplemented in Compartment, CompartmentGrid, and Composite.
Definition at line 114 of file Component.h.
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getRepulsionConst()
virtual double BoundaryElement::getRepulsionConst () inline virtual inherited
Getter for mechanical parameters.
Definition at line 94 of file BoundaryElement.h.
Referenced by BoundaryElement::getCoords().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getScreeningLength()
virtual double BoundaryElement::getScreeningLength () inline virtual inherited
Getter for mechanical parameters.
Definition at line 95 of file BoundaryElement.h.
References BoundaryElement::_r0, Database< T >::addElement(), and BoundaryElement::addToSubSystem().
getType()
virtual int BoundaryElement::getType () inline virtual inherited
Return the type of this element as an integer index.
Implements Component.
Definition at line 116 of file BoundaryElement.h.
isComposite()
virtual bool Component::isComposite () const inline virtual inherited
Returns true if this node is a Composite node.
Reimplemented in Composite.
Definition at line 95 of file Component.h.
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
normal()
virtual const vector<double> HalfSphereZBoundaryElement::normal (const vector< double > & point) inline virtual
Returns normal vector of point to plane.
Implements BoundaryElement.
Definition at line 237 of file BoundaryElementImpl.h.
References mathfunc::twoPointDirection().
numberOfChildren()
virtual size_t Component::numberOfChildren () const inline virtual inherited
Returns the number of children of this node.
Note
Species and ReactionBase objects are not counted.
Reimplemented in Composite.
Definition at line 92 of file Component.h.
numberOfReactions()
virtual size_t Component::numberOfReactions () const inline virtual inherited
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 110 of file Component.h.
numberOfSpecies()
virtual size_t Component::numberOfSpecies () const inline virtual inherited
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 106 of file Component.h.
numBoundaryElements()
static int BoundaryElement::numBoundaryElements () inline static inherited
Get the number of boundary elements in this system.
Definition at line 109 of file BoundaryElement.h.
References Database< T >::countElements(), and BoundaryElement::printSelf().
printSelf()
void BoundaryElement::printSelf () virtual inherited
Prints information about this node. Useful for debugging.
Implements Component.
Definition at line 19 of file BoundaryElement.cpp.
References BoundaryElement::_coords.
Referenced by BoundaryElement::numBoundaryElements(), and BoundaryFF::whoIsCulprit().
removeFromSubSystem()
virtual void BoundaryElement::removeFromSubSystem () inline virtual inherited
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 101 of file BoundaryElement.h.
References Database< T >::removeElement().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
stretchedDistance()
virtual double HalfSphereZBoundaryElement::stretchedDistance (const vector< double > & point, const vector< double > & force, double d) inline virtual
Returns stretched distance, similar to distance above.
Implements BoundaryElement.
Definition at line 220 of file BoundaryElementImpl.h.
References BoundaryCapsule::distance().
updateCoords()
virtual void HalfSphereZBoundaryElement::updateCoords (const vector< double > newCoords) inline virtual
update the coordinates of the boundary element
Implements BoundaryElement.
Definition at line 242 of file BoundaryElementImpl.h.
Friends And Related Function Documentation
BoundaryCapsule
friend class BoundaryCapsule friend
Definition at line 194 of file BoundaryElementImpl.h.
Member Data Documentation
_coords
vector<double> BoundaryElement::_coords protected inherited
coordinates
Definition at line 53 of file BoundaryElement.h.
Referenced by BoundaryElement::getCoords(), and BoundaryElement::printSelf().
_dneighbor
bool Trackable::_dneighbor protected inherited
Object type.
Definition at line 54 of file Trackable.h.
_kRep
double BoundaryElement::_kRep protected inherited
Repulsion constant.
Definition at line 55 of file BoundaryElement.h.
Referenced by BoundaryElement::getCoords().
_movable
bool Trackable::_movable protected inherited
Object type.
Definition at line 52 of file Trackable.h.
_neighbor
bool Trackable::_neighbor protected inherited
Object type.
Definition at line 55 of file Trackable.h.
_r0
double BoundaryElement::_r0 protected inherited
Screening length.
Definition at line 56 of file BoundaryElement.h.
Referenced by BoundaryElement::getScreeningLength().
_radius
double HalfSphereZBoundaryElement::_radius private
Radius of half sphere.
Definition at line 197 of file BoundaryElementImpl.h.
_reactable
bool Trackable::_reactable protected inherited
Object type.
Definition at line 53 of file Trackable.h.
_subSystem
SubSystem * Trackable::_subSystem = 0 static protected inherited
A subsystem pointer for every trackable.
Definition at line 46 of file Trackable.h.
Referenced by Controller::Controller(), and BranchingPoint::~BranchingPoint().
_up
bool HalfSphereZBoundaryElement::_up private
Whether the half sphere faces up or down.
Definition at line 198 of file BoundaryElementImpl.h.
The documentation for this class was generated from the following file:
src/Structure/BoundaryElementImpl.h