M3Sym: CylinderDB Class Reference
CylinderDB Class Reference
A database for all Cylinders in the system.
#include <CylinderDB.h>
Public Member Functions
CylinderDB (const CylinderDB &rhs)=delete
Copying is not allowed.
CylinderDB & operator= (CylinderDB &rhs)=delete
Assignment is not allowed.
void addCylinder (Cylinder *c)
Add a cylinder.
void removeCylinder (Cylinder *c)
Remove cylinder.
int getCylinderID ()
Get current cylinder ID, and update the ID counter.
Static Public Member Functions
static CylinderDB * instance ()
Get the instance of this singleton.
Private Types
typedef list< Cylinder * > cdb
Private Member Functions
CylinderDB ()
Private Attributes
T elements
STL member.
Static Private Attributes
static int _currentCylinderID = 0
Current running cylinder ID.
static CylinderDB * _instance = 0
Singleton instance.
Detailed Description
A database for all Cylinders in the system.
This CylinderDB inherits from list and manage all creations and removing of Cylinders objects, as well as some standard list functions and iterators.
Definition at line 30 of file CylinderDB.h.
Member Typedef Documentation
typedef list<Cylinder*> CylinderDB::cdb private
Definition at line 32 of file CylinderDB.h.
Constructor & Destructor Documentation
CylinderDB::CylinderDB (const CylinderDB & rhs) delete
Copying is not allowed.
CylinderDB::CylinderDB () inline private
Definition at line 62 of file CylinderDB.h.
Referenced by instance().
Member Function Documentation
void CylinderDB::addCylinder (Cylinder * c) inline
Add a cylinder.
Definition at line 51 of file CylinderDB.h.
Referenced by Cylinder::Cylinder().
int CylinderDB::getCylinderID () inline
Get current cylinder ID, and update the ID counter.
Definition at line 56 of file CylinderDB.h.
References _currentCylinderID.
Referenced by Cylinder::Cylinder().
CylinderDB * CylinderDB::instance () static
Get the instance of this singleton.
Definition at line 19 of file CylinderDB.cpp.
References _instance, and CylinderDB().
Referenced by VolumeCylindricalFF::computeEnergy(), VolumeCylindricalFF::computeForces(), VolumeCylindricalFF::computeForcesAux(), Cylinder::Cylinder(), and Cylinder::~Cylinder().
CylinderDB& CylinderDB::operator= (CylinderDB & rhs) delete
Assignment is not allowed.
void CylinderDB::removeCylinder (Cylinder * c) inline
Remove cylinder.
Definition at line 53 of file CylinderDB.h.
Referenced by Cylinder::~Cylinder().
Member Data Documentation
int CylinderDB::_currentCylinderID = 0 static private
Current running cylinder ID.
Definition at line 59 of file CylinderDB.h.
Referenced by getCylinderID().
CylinderDB * CylinderDB::_instance = 0 static private
Singleton instance.
Definition at line 61 of file CylinderDB.h.
Referenced by instance().
T std::list< T >::elements inherited
STL member.
The documentation for this class was generated from the following files:
M3SYM/Structure/CylinderDB.h
M3SYM/Structure/CylinderDB.cpp