MEDYAN: CBranchingPoint Class Reference
CBranchingPoint Class Reference
A class to represent the chemical component of a BranchingPoint.
#include <CBranchingPoint.h>
Public Member Functions
CBranchingPoint (short branchType, Compartment *c, CCylinder *cc1, CCylinder *cc2, int position)
Default constructor and destructor.
~CBranchingPoint ()
Destructor, removes off reaction from system.
CBranchingPoint (const CBranchingPoint &rhs, Compartment *c)
Copy constructor, standard.
CBranchingPoint & operator= (CBranchingPoint &rhs)=delete
Assignment is not allowed.
virtual CBranchingPoint * clone (Compartment *c)
Clone, calls copy constructor.
void setBranchingPoint (BranchingPoint *BranchingPoint)
Set parent.
BranchingPoint * getBranchingPoint ()
Get parent.
virtual void createOffReaction (ReactionBase *onRxn, SubSystem *ps)
Off reaction management.
void setFirstSpecies (SpeciesBound *species)
Set first species.
SpeciesBound * getFirstSpecies ()
Get first species.
void setSecondSpecies (SpeciesBound *species)
Set second species.
SpeciesBound * getSecondSpecies ()
Get second species.
void setFirstCCylinder (CCylinder *cc)
Set first CCylinder.
CCylinder * getFirstCCylinder ()
Get first CCylinder.
void setSecondCCylinder (CCylinder *cc)
Set second CCylinder.
CCylinder * getSecondCCylinder ()
Get first CCylinder.
Compartment * getCompartment ()
Get compartment that this CBound is in.
void setRates (float onRate, float offRate)
Set all rates at once.
short getFirstPosition ()
Position getters.
short getSecondPosition ()
Position getters.
void setOnRate (float rate)
On rate management.
double getOnRate ()
On rate management.
void setOffRate (float rate)
Off rate management.
double getOffRate ()
Off rate management.
void setOffReaction (ReactionBase *offRxn)
Off reaction management.
ReactionBase * getOffReaction ()
Off reaction management.
Protected Attributes
short _filamentType
The filament type that this CBound binds to.
SpeciesBound * _firstSpecies = nullptr
Corresponding first species on Filament.
SpeciesBound * _secondSpecies = nullptr
Corresponding second species on Filament.
Compartment * _compartment
Compartment this CBound is in.
CCylinder * _cc1 = nullptr
Pointer to first CCylinder.
CCylinder * _cc2 = nullptr
Pointer to second CCylinder.
short _position1
position of first head
short _position2 = 0
position of second head
ReactionBase * _offRxn
The off reaction for this bound object.
float _onRate = 0.0
Reaction rates.
float _offRate = 0.0
Reaction rates.
Private Attributes
BranchingPoint * _pBranchingPoint
Pointer to parent.
short _branchType
Branching point type.
Detailed Description
A class to represent the chemical component of a BranchingPoint.
The CBranchingPoint class contains chemical info of the parent BranchingPoint.
Extending CBound, this class tracks its corresponding Species and unbinding Reaction.
Definition at line 34 of file CBranchingPoint.h.
Constructor & Destructor Documentation
CBranchingPoint() [1/2]
CBranchingPoint::CBranchingPoint (short branchType, Compartment * c, CCylinder * cc1, CCylinder * cc2, int position)
Default constructor and destructor.
Parameters
pos - monomer index on first cylinder
Definition at line 21 of file CBranchingPoint.cpp.
References CBound::_cc1, CBound::_filamentType, CBound::_position1, areEqual(), SysParams::Chemistry(), Species::down(), CCylinder::getCMonomer(), Species::getN(), CBound::setFirstSpecies(), CMonomer::speciesBound(), CMonomer::speciesBrancher(), and Species::up().
Referenced by clone().
~CBranchingPoint()
CBranchingPoint::~CBranchingPoint ()
Destructor, removes off reaction from system.
Definition at line 41 of file CBranchingPoint.cpp.
References CBound::_cc1, CBound::_offRxn, and CCylinder::removeInternalReaction().
CBranchingPoint() [2/2]
CBranchingPoint::CBranchingPoint (const CBranchingPoint & rhs, Compartment * c) inline
Copy constructor, standard.
Definition at line 50 of file CBranchingPoint.h.
References CBound::_firstSpecies, CBound::_offRate, CBound::_offRxn, CBound::_onRate, operator=(), CBound::setFirstSpecies(), CBound::setOffRate(), CBound::setOffReaction(), and CBound::setOnRate().
Member Function Documentation
clone()
virtual CBranchingPoint* CBranchingPoint::clone (Compartment * c) inline virtual
Clone, calls copy constructor.
Definition at line 69 of file CBranchingPoint.h.
References CBound::_offRxn, and CBranchingPoint().
createOffReaction()
void CBranchingPoint::createOffReaction (ReactionBase * onRxn, SubSystem * ps) virtual
Off reaction management.
Implements CBound.
Definition at line 48 of file CBranchingPoint.cpp.
References _branchType, CBound::_cc1, CBound::_filamentType, CBound::_offRate, _pBranchingPoint, CBound::_position1, CCylinder::addInternalReaction(), BRANCHUNBINDING, SysParams::Chemistry(), CCylinder::getCMonomer(), RSpecies::getSpecies(), ReactionBase::rspecies(), CBound::setOffReaction(), ReactionBase::setReactionType(), SPECIESB_BINDING_INDEX, CMonomer::speciesBound(), and CMonomer::speciesBrancher().
Referenced by getBranchingPoint().
getBranchingPoint()
BranchingPoint* CBranchingPoint::getBranchingPoint () inline
Get parent.
Definition at line 80 of file CBranchingPoint.h.
References _pBranchingPoint, and createOffReaction().
getCompartment()
Compartment* CBound::getCompartment () inline inherited
Get compartment that this CBound is in.
Definition at line 118 of file CBound.h.
References CBound::_compartment, and CBound::setOnRate().
getFirstCCylinder()
CCylinder* CBound::getFirstCCylinder () inline inherited
Get first CCylinder.
Definition at line 110 of file CBound.h.
References CBound::_cc1.
getFirstPosition()
short CBound::getFirstPosition () inline inherited
Position getters.
Definition at line 103 of file CBound.h.
Referenced by CBound::getSecondSpecies().
getFirstSpecies()
SpeciesBound* CBound::getFirstSpecies () inline inherited
Get first species.
Definition at line 88 of file CBound.h.
References CBound::_firstSpecies.
Referenced by CMonomer::CMonomer(), and CMotorGhost::moveMotorHead().
getOffRate()
double CBound::getOffRate () inline inherited
Off rate management.
Definition at line 129 of file CBound.h.
References CBound::_offRate.
getOffReaction()
ReactionBase* CBound::getOffReaction () inline inherited
Off reaction management.
Definition at line 146 of file CBound.h.
References CBound::_offRxn.
getOnRate()
double CBound::getOnRate () inline inherited
On rate management.
Definition at line 123 of file CBound.h.
References CBound::_onRate, and CBound::setOffRate().
getSecondCCylinder()
CCylinder* CBound::getSecondCCylinder () inline inherited
Get first CCylinder.
Definition at line 115 of file CBound.h.
References CBound::_cc2.
getSecondPosition()
short CBound::getSecondPosition () inline inherited
Position getters.
Definition at line 104 of file CBound.h.
References CBound::_position2.
getSecondSpecies()
SpeciesBound* CBound::getSecondSpecies () inline inherited
Get second species.
Definition at line 99 of file CBound.h.
References CBound::_position1, CBound::_secondSpecies, and CBound::getFirstPosition().
operator=()
CBranchingPoint& CBranchingPoint::operator= (CBranchingPoint & rhs) delete
Assignment is not allowed.
Referenced by CBranchingPoint().
setBranchingPoint()
void CBranchingPoint::setBranchingPoint (BranchingPoint * BranchingPoint) inline
Set parent.
Definition at line 76 of file CBranchingPoint.h.
setFirstCCylinder()
void CBound::setFirstCCylinder (CCylinder * cc) inline inherited
Set first CCylinder.
Definition at line 108 of file CBound.h.
Referenced by CMotorGhost::moveMotorHead().
setFirstSpecies()
void CBound::setFirstSpecies (SpeciesBound * species) inline inherited
Set first species.
remove from old first species
Definition at line 80 of file CBound.h.
References SpeciesBound::removeCBound(), and SpeciesBound::setCBound().
Referenced by CBranchingPoint(), CLinker::CLinker(), CMonomer::CMonomer(), CMotorGhost::CMotorGhost(), and CMotorGhost::moveMotorHead().
setOffRate()
void CBound::setOffRate (float rate) inline inherited
Off rate management.
Definition at line 128 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), and CBound::getOnRate().
setOffReaction()
void CBound::setOffReaction (ReactionBase * offRxn) inline inherited
Off reaction management.
Definition at line 142 of file CBound.h.
References ReactionBase::setCBound().
Referenced by CBranchingPoint(), CCylinder::CCylinder(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), and CMotorGhost::moveMotorHead().
setOnRate()
void CBound::setOnRate (float rate) inline inherited
On rate management.
Definition at line 122 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), and CBound::getCompartment().
setRates()
void CBound::setRates (float onRate, float offRate) inline inherited
Set all rates at once.
Definition at line 133 of file CBound.h.
References CBound::createOffReaction().
setSecondCCylinder()
void CBound::setSecondCCylinder (CCylinder * cc) inline inherited
Set second CCylinder.
Definition at line 113 of file CBound.h.
Referenced by CMotorGhost::moveMotorHead().
setSecondSpecies()
void CBound::setSecondSpecies (SpeciesBound * species) inline inherited
Set second species.
remove from old second species
Definition at line 91 of file CBound.h.
References SpeciesBound::removeCBound(), and SpeciesBound::setCBound().
Referenced by CLinker::CLinker(), CMonomer::CMonomer(), CMotorGhost::CMotorGhost(), and CMotorGhost::moveMotorHead().
Member Data Documentation
_branchType
short CBranchingPoint::_branchType private
Branching point type.
Definition at line 39 of file CBranchingPoint.h.
Referenced by createOffReaction().
_cc1
CCylinder* CBound::_cc1 = nullptr protected inherited
Pointer to first CCylinder.
Definition at line 47 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), CBound::getFirstCCylinder(), CMotorGhost::moveMotorHead(), ~CBranchingPoint(), CLinker::~CLinker(), and CMotorGhost::~CMotorGhost().
_cc2
CCylinder* CBound::_cc2 = nullptr protected inherited
Pointer to second CCylinder.
Definition at line 48 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), CBound::getSecondCCylinder(), CMotorGhost::moveMotorHead(), CLinker::~CLinker(), and CMotorGhost::~CMotorGhost().
_compartment
Compartment* CBound::_compartment protected inherited
Compartment this CBound is in.
Definition at line 45 of file CBound.h.
Referenced by CBound::getCompartment().
_filamentType
short CBound::_filamentType protected inherited
The filament type that this CBound binds to.
Definition at line 40 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), createOffReaction(), CMotorGhost::createOffReaction(), and CMotorGhost::moveMotorHead().
_firstSpecies
SpeciesBound* CBound::_firstSpecies = nullptr protected inherited
Corresponding first species on Filament.
Definition at line 42 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), CBound::getFirstSpecies(), and CMotorGhost::moveMotorHead().
_offRate
float CBound::_offRate = 0.0 protected inherited
Reaction rates.
Definition at line 56 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), createOffReaction(), CMotorGhost::createOffReaction(), CBound::getOffRate(), and CMotorGhost::moveMotorHead().
_offRxn
ReactionBase* CBound::_offRxn protected inherited
The off reaction for this bound object.
Definition at line 59 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), clone(), CLinker::clone(), CMotorGhost::clone(), CMotorGhost::CMotorGhost(), CBound::getOffReaction(), CMotorGhost::moveMotorHead(), ~CBranchingPoint(), CLinker::~CLinker(), and CMotorGhost::~CMotorGhost().
_onRate
float CBound::_onRate = 0.0 protected inherited
Reaction rates.
Definition at line 55 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), and CBound::getOnRate().
_pBranchingPoint
BranchingPoint* CBranchingPoint::_pBranchingPoint private
Pointer to parent.
Definition at line 37 of file CBranchingPoint.h.
Referenced by createOffReaction(), and getBranchingPoint().
_position1
short CBound::_position1 protected inherited
position of first head
Definition at line 50 of file CBound.h.
Referenced by CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), createOffReaction(), CMotorGhost::createOffReaction(), CBound::getSecondSpecies(), and CMotorGhost::moveMotorHead().
_position2
short CBound::_position2 = 0 protected inherited
position of second head
Definition at line 51 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), CBound::getSecondPosition(), and CMotorGhost::moveMotorHead().
_secondSpecies
SpeciesBound* CBound::_secondSpecies = nullptr protected inherited
Corresponding second species on Filament.
Definition at line 43 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost::CMotorGhost(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), CBound::getSecondSpecies(), and CMotorGhost::moveMotorHead().
The documentation for this class was generated from the following files:
src/Structure/CBranchingPoint.h
src/Structure/CBranchingPoint.cpp