M3Sym: BeadDB Class Reference
BeadDB Class Reference
A database for all Beads in the system.
#include <BeadDB.h>
Public Member Functions
BeadDB (const BeadDB &rhs)=delete
Copying is not allowed.
BeadDB & operator= (BeadDB &rhs)=delete
Assignment is not allowed.
void addBead (Bead *b)
Add a bead.
void removeBead (Bead *b)
Remove a bead.
Static Public Member Functions
static BeadDB * instance ()
Get the instance of this singleton.
Private Types
typedef list< Bead * > bdb
Private Member Functions
BeadDB ()
Private Attributes
T elements
STL member.
Static Private Attributes
static BeadDB * _instance = 0
Singleton instance.
Detailed Description
A database for all Beads in the system.
This BeadDB inherits from list and manage all creations and removing of Bead objects, as well as some standard list functions and iterators.
Definition at line 30 of file BeadDB.h.
Member Typedef Documentation
typedef list<Bead*> BeadDB::bdb private
Definition at line 32 of file BeadDB.h.
Constructor & Destructor Documentation
BeadDB::BeadDB (const BeadDB & rhs) delete
Copying is not allowed.
BeadDB::BeadDB () inline private
Definition at line 57 of file BeadDB.h.
Referenced by instance().
Member Function Documentation
void BeadDB::addBead (Bead * b) inline
Add a bead.
Definition at line 51 of file BeadDB.h.
Referenced by Bead::Bead().
BeadDB * BeadDB::instance () static
Get the instance of this singleton.
Definition at line 18 of file BeadDB.cpp.
References _instance, and BeadDB().
Referenced by CGMethod::backtrackingLineSearch(), Bead::Bead(), CGMethod::gradAuxSquare(), CGMethod::gradDotProduct(), CGMethod::gradSquare(), FletcherRieves::minimize(), PolakRibiere::minimize(), CGMethod::moveBeads(), CGMethod::moveBeadsAux(), CGMethod::printForces(), CGMethod::quadraticLineSearch(), ForceFieldManager::resetForces(), ForceFieldManager::resetForcesAux(), CGMethod::shiftGradient(), BoundaryElementNeighborList::updateNeighbors(), and Bead::~Bead().
BeadDB& BeadDB::operator= (BeadDB & rhs) delete
Assignment is not allowed.
void BeadDB::removeBead (Bead * b) inline
Remove a bead.
Definition at line 53 of file BeadDB.h.
Referenced by Bead::~Bead().
Member Data Documentation
BeadDB * BeadDB::_instance = 0 static private
Singleton instance.
Definition at line 56 of file BeadDB.h.
Referenced by instance().
T std::list< T >::elements inherited
STL member.
The documentation for this class was generated from the following files:
M3SYM/Structure/BeadDB.h
M3SYM/Structure/BeadDB.cpp