M3Sym: BoundaryElement Class Reference
BoundaryElement Class Reference abstract
Represents an element of a boundary surface.
#include <BoundaryElement.h>
Public Member Functions
BoundaryElement (vector< double > coords)
Default constructor.
virtual ~BoundaryElement () noexcept
Destructor.
const vector< double > & getCoords ()
return coordinates of boundary element
virtual double distance (const vector< double > &point)=0
Implement for all boundary elements Returns the distance from a given point to this boundary element.
virtual double stretchedDistance (const vector< double > &point, const vector< double > &force, double d)=0
Returns stretched distance, similar to distance above.
virtual const vector< double > normal (const vector< double > &point)=0
Returns normal vector of point to plane.
virtual double getRepulsionConst ()=0
Getter for parameters.
virtual double getScreeningLength ()=0
Getter for parameters.
Protected Attributes
vector< double > _coords
coordinates
Detailed Description
Represents an element of a boundary surface.
The BoundaryElement class is a representation of a BoundarySurface element, which can interact with other elements in the system, including other BoundaryElements as well as Beads in Filaments. Together, a collection of boundary elements make up a BoundarySurface.
Definition at line 37 of file BoundaryElement.h.
Constructor & Destructor Documentation
BoundaryElement::BoundaryElement (vector< double > coords) inline
Default constructor.
Definition at line 44 of file BoundaryElement.h.
References BoundaryElementDB::addBoundaryElement(), NeighborListDB::addNeighbor(), BoundaryElementDB::instance(), and NeighborListDB::instance().
virtual BoundaryElement::~BoundaryElement () inline virtual noexcept
Destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
remove from neighbor lists
Definition at line 56 of file BoundaryElement.h.
References BoundaryElementDB::instance(), NeighborListDB::instance(), BoundaryElementDB::removeBoundaryElement(), and NeighborListDB::removeNeighbor().
Member Function Documentation
virtual double BoundaryElement::distance (const vector< double > & point) pure virtual
Implement for all boundary elements Returns the distance from a given point to this boundary element.
Returns
- 1) positive number if point is within boundary element 2) Negative number if point is outside boundary element 3) Infinity if point is not in domain of this boundary element
Implemented in HalfSphereZBoundaryElement, CylindricalZBoundaryElement, SphereBoundaryElement, and PlaneBoundaryElement.
Referenced by BoundaryRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryRepulsion< BRepulsionInteractionType >::computeForces(), BoundaryRepulsion< BRepulsionInteractionType >::computeForcesAux(), BoundarySpherical::within(), and BoundaryCapsule::within().
const vector<double>& BoundaryElement::getCoords () inline
return coordinates of boundary element
Definition at line 66 of file BoundaryElement.h.
References _coords.
virtual double BoundaryElement::getRepulsionConst () pure virtual
Getter for parameters.
Implemented in HalfSphereZBoundaryElement, CylindricalZBoundaryElement, SphereBoundaryElement, and PlaneBoundaryElement.
Referenced by BoundaryRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryRepulsion< BRepulsionInteractionType >::computeForces(), and BoundaryRepulsion< BRepulsionInteractionType >::computeForcesAux().
virtual double BoundaryElement::getScreeningLength () pure virtual
Getter for parameters.
Implemented in HalfSphereZBoundaryElement, CylindricalZBoundaryElement, SphereBoundaryElement, and PlaneBoundaryElement.
Referenced by BoundaryRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryRepulsion< BRepulsionInteractionType >::computeForces(), and BoundaryRepulsion< BRepulsionInteractionType >::computeForcesAux().
virtual const vector<double> BoundaryElement::normal (const vector< double > & point) pure virtual
Returns normal vector of point to plane.
Implemented in HalfSphereZBoundaryElement, CylindricalZBoundaryElement, SphereBoundaryElement, and PlaneBoundaryElement.
Referenced by BoundaryRepulsion< BRepulsionInteractionType >::computeForces(), and BoundaryRepulsion< BRepulsionInteractionType >::computeForcesAux().
virtual double BoundaryElement::stretchedDistance (const vector< double > & point, const vector< double > & force, double d) pure virtual
Returns stretched distance, similar to distance above.
Implemented in HalfSphereZBoundaryElement, CylindricalZBoundaryElement, SphereBoundaryElement, and PlaneBoundaryElement.
Referenced by BoundaryRepulsion< BRepulsionInteractionType >::computeEnergy().
Member Data Documentation
vector<double> BoundaryElement::_coords protected
coordinates
Definition at line 40 of file BoundaryElement.h.
Referenced by SphereBoundaryElement::distance(), CylindricalZBoundaryElement::distance(), HalfSphereZBoundaryElement::distance(), getCoords(), SphereBoundaryElement::normal(), CylindricalZBoundaryElement::normal(), HalfSphereZBoundaryElement::normal(), PlaneBoundaryElement::PlaneBoundaryElement(), SphereBoundaryElement::stretchedDistance(), CylindricalZBoundaryElement::stretchedDistance(), and HalfSphereZBoundaryElement::stretchedDistance().
The documentation for this class was generated from the following file:
M3SYM/Structure/BoundaryElement.h