MEDYAN: BranchingManager Class Reference
BranchingManager Class Reference
Manager for Filament and BranchingPoint creation.
#include <BindingManager.h>
Public Member Functions
BranchingManager (ReactionBase *reaction, Compartment *compartment, short boundInt, string boundName, short filamentType, NucleationZoneType zone=NucleationZoneType::ALL, double nucleationDistance=numeric_limits< double >::infinity())
~BranchingManager ()
virtual void updateAllPossibleBindings ()
update all possible binding reactions that could occur
virtual int numBindingSites ()
Get current number of binding sites.
tuple< CCylinder *, short > chooseBindingSite ()
Choose a random binding site based on current state.
virtual bool isConsistent ()
Check consistency and correctness of binding sites. Used for debugging.
virtual void appendpossibleBindings (tuple< CCylinder *, short > t1, tuple< CCylinder *, short > t2)
ARAVIND ADDED FEB 17 2016. append possible bindings.
virtual void clearpossibleBindings ()
vector< tuple< tuple< CCylinder *, short >, tuple< CCylinder *, short > > > getbtuple ()
short getBoundInt ()
Get the bound species integer index.
string getBoundName ()
Get the bound species name.
void setNLIndex (int index)
Set the index of this manager, for access to NeighborList.
void setMIndex (int index)
Set the index of this manager, for access to other managers.
short getfilamentType ()
get the filament that the species binds to aravind June 30, 2016.
vector< string > getrxnspecies ()
aravind, June 30,2016.
virtual void addPossibleBindings (CCylinder *cc, short bindingSite)
add possible binding reactions that could occur
virtual void addPossibleBindings (CCylinder *cc)
add possible binding reactions that could occur
virtual void removePossibleBindings (CCylinder *cc, short bindingSite)
Remove all bindings including this cylinder.
virtual void removePossibleBindings (CCylinder *cc)
Remove all bindings including this cylinder.
Protected Member Functions
void updateBindingReaction (int oldN, int newN)
helper function to update copy number and reactions
Protected Attributes
ReactionBase * _bindingReaction
The binding reaction for this compartment.
Compartment * _compartment
Compartment this is in.
short _boundInt
Integer index in CMonomer of bound chemical value.
string _boundName
String name of bound chemical value.
short _filamentType
The filament type to operate on.
Species * _bindingSpecies
The binding species that this manager tracks.
short _nlIndex = 0
Index of this manager (for access of neighbor lists)
short _mIndex = 0
Index of this manager (for access in other compartments)
Static Protected Attributes
static SubSystem * _subSystem = 0
Ptr to the SubSystem.
Private Attributes
NucleationZoneType _nucleationZone
Nucleation zone type, to define where nucleation should occur.
double _nucleationDistance
If using a nucleation zone, nucleating distance from the boundary.
unordered_set< tuple< CCylinder *, short > > _possibleBindings
possible bindings at current state
vector< tuple< tuple< CCylinder *, short >, tuple< CCylinder *, short > > > _branchrestarttuple
Friends
class ChemManager
Detailed Description
Manager for Filament and BranchingPoint creation.
Definition at line 174 of file BindingManager.h.
Constructor & Destructor Documentation
BranchingManager()
BranchingManager::BranchingManager (ReactionBase * reaction, Compartment * compartment, short boundInt, string boundName, short filamentType, NucleationZoneType zone = NucleationZoneType::ALL, double nucleationDistance = numeric_limits<double>::infinity())
Definition at line 36 of file BindingManager.cpp.
References FilamentBindingManager::_bindingSpecies, FilamentBindingManager::_compartment, B_RXN_INDEX, Compartment::findSpeciesByName(), Species::getName(), RSpecies::getSpecies(), and ReactionBase::rspecies().
~BranchingManager()
BranchingManager::~BranchingManager () inline
Definition at line 195 of file BindingManager.h.
References FilamentBindingManager::addPossibleBindings(), FilamentBindingManager::removePossibleBindings(), and FilamentBindingManager::updateAllPossibleBindings().
Member Function Documentation
addPossibleBindings() [1/2]
void BranchingManager::addPossibleBindings (CCylinder * cc, short bindingSite) virtual
add possible binding reactions that could occur
Implements FilamentBindingManager.
Definition at line 52 of file BindingManager.cpp.
References FilamentBindingManager::_bindingSpecies, FilamentBindingManager::_filamentType, _nucleationDistance, _nucleationZone, _possibleBindings, FilamentBindingManager::_subSystem, ALL, areEqual(), SysParams::Chemistry(), Bead::coordinate, GeoParams::cylinderNumMon, Boundary::distance(), SysParams::Geometry(), SubSystem::getBoundary(), GController::getCenter(), CCylinder::getCMonomer(), CCylinder::getCylinder(), Cylinder::getFirstBead(), Species::getN(), Cylinder::getSecondBead(), CCylinder::getType(), mathfunc::midPointCoordinate(), numBindingSites(), CMonomer::speciesBound(), TOPBOUNDARY, and FilamentBindingManager::updateBindingReaction().
Referenced by addPossibleBindings().
addPossibleBindings() [2/2]
void BranchingManager::addPossibleBindings (CCylinder * cc) virtual
add possible binding reactions that could occur
Implements FilamentBindingManager.
Definition at line 98 of file BindingManager.cpp.
References FilamentBindingManager::_filamentType, addPossibleBindings(), ChemParams::bindingSites, and SysParams::Chemistry().
appendpossibleBindings()
virtual void BranchingManager::appendpossibleBindings (tuple< CCylinder *, short > t1, tuple< CCylinder *, short > t2) inline virtual
ARAVIND ADDED FEB 17 2016. append possible bindings.
Implements FilamentBindingManager.
Definition at line 234 of file BindingManager.h.
References FilamentBindingManager::numBindingSites(), and FilamentBindingManager::updateBindingReaction().
chooseBindingSite()
tuple<CCylinder*, short> BranchingManager::chooseBindingSite () inline
Choose a random binding site based on current state.
Definition at line 218 of file BindingManager.h.
References FilamentBindingManager::isConsistent(), and Rand::randInteger().
clearpossibleBindings()
virtual void BranchingManager::clearpossibleBindings () inline virtual
Implements FilamentBindingManager.
Definition at line 241 of file BindingManager.h.
References FilamentBindingManager::numBindingSites(), and FilamentBindingManager::updateBindingReaction().
getBoundInt()
short FilamentBindingManager::getBoundInt () inline inherited
Get the bound species integer index.
Definition at line 149 of file BindingManager.h.
References FilamentBindingManager::_boundInt.
getBoundName()
string FilamentBindingManager::getBoundName () inline inherited
Get the bound species name.
Definition at line 151 of file BindingManager.h.
References FilamentBindingManager::_boundName.
getbtuple()
vector<tuple<tuple<CCylinder*, short>, tuple<CCylinder*, short> > > BranchingManager::getbtuple () inline
Definition at line 246 of file BindingManager.h.
getfilamentType()
short FilamentBindingManager::getfilamentType () inline inherited
get the filament that the species binds to aravind June 30, 2016.
Definition at line 163 of file BindingManager.h.
References FilamentBindingManager::_filamentType, and FilamentBindingManager::appendpossibleBindings().
getrxnspecies()
vector<string> FilamentBindingManager::getrxnspecies () inline inherited
aravind, June 30,2016.
Definition at line 168 of file BindingManager.h.
References FilamentBindingManager::clearpossibleBindings(), and ReactionBase::getreactantspecies().
isConsistent()
bool BranchingManager::isConsistent () virtual
Check consistency and correctness of binding sites. Used for debugging.
Implements FilamentBindingManager.
Definition at line 187 of file BindingManager.cpp.
References FilamentBindingManager::_filamentType, _possibleBindings, areEqual(), SysParams::Chemistry(), CCylinder::getCMonomer(), CCylinder::getCylinder(), Species::getN(), Cylinder::printSelf(), and CMonomer::speciesBound().
numBindingSites()
virtual int BranchingManager::numBindingSites () inline virtual
Get current number of binding sites.
Implements FilamentBindingManager.
Definition at line 212 of file BindingManager.h.
Referenced by addPossibleBindings(), removePossibleBindings(), and updateAllPossibleBindings().
removePossibleBindings() [1/2]
void BranchingManager::removePossibleBindings (CCylinder * cc, short bindingSite) virtual
Remove all bindings including this cylinder.
Implements FilamentBindingManager.
Definition at line 107 of file BindingManager.cpp.
References FilamentBindingManager::_bindingSpecies, FilamentBindingManager::_filamentType, _possibleBindings, Species::getN(), CCylinder::getType(), numBindingSites(), and FilamentBindingManager::updateBindingReaction().
Referenced by removePossibleBindings().
removePossibleBindings() [2/2]
void BranchingManager::removePossibleBindings (CCylinder * cc) virtual
Remove all bindings including this cylinder.
Implements FilamentBindingManager.
Definition at line 121 of file BindingManager.cpp.
References FilamentBindingManager::_filamentType, ChemParams::bindingSites, SysParams::Chemistry(), and removePossibleBindings().
setMIndex()
void FilamentBindingManager::setMIndex (int index) inline inherited
Set the index of this manager, for access to other managers.
Definition at line 157 of file BindingManager.h.
References FilamentBindingManager::isConsistent().
Referenced by ChemManager::genFilBindingReactions().
setNLIndex()
void FilamentBindingManager::setNLIndex (int index) inline inherited
Set the index of this manager, for access to NeighborList.
Definition at line 154 of file BindingManager.h.
Referenced by ChemManager::genFilBindingReactions().
updateAllPossibleBindings()
void BranchingManager::updateAllPossibleBindings () virtual
update all possible binding reactions that could occur
Implements FilamentBindingManager.
Definition at line 130 of file BindingManager.cpp.
References FilamentBindingManager::_bindingSpecies, FilamentBindingManager::_compartment, FilamentBindingManager::_filamentType, _nucleationDistance, _nucleationZone, _possibleBindings, FilamentBindingManager::_subSystem, ALL, areEqual(), ChemParams::bindingSites, ChemParams::brancherBoundIndex, SysParams::Chemistry(), GeoParams::cylinderNumMon, Boundary::distance(), SysParams::Geometry(), SubSystem::getBoundary(), GController::getCenter(), Compartment::getCylinders(), Species::getN(), mathfunc::midPointCoordinate(), numBindingSites(), TOPBOUNDARY, and FilamentBindingManager::updateBindingReaction().
updateBindingReaction()
void FilamentBindingManager::updateBindingReaction (int oldN, int newN) inline protected inherited
helper function to update copy number and reactions
Definition at line 85 of file BindingManager.h.
References Species::down(), Species::getN(), FilamentBindingManager::numBindingSites(), Species::up(), and ReactionBase::updatePropensity().
Referenced by addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), appendpossibleBindings(), LinkerBindingManager::appendpossibleBindings(), MotorBindingManager::appendpossibleBindings(), clearpossibleBindings(), LinkerBindingManager::clearpossibleBindings(), MotorBindingManager::clearpossibleBindings(), removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
Friends And Related Function Documentation
ChemManager
friend class ChemManager friend
Definition at line 176 of file BindingManager.h.
Member Data Documentation
_bindingReaction
ReactionBase* FilamentBindingManager::_bindingReaction protected inherited
The binding reaction for this compartment.
Definition at line 65 of file BindingManager.h.
_bindingSpecies
Species* FilamentBindingManager::_bindingSpecies protected inherited
The binding species that this manager tracks.
Resposible for all copy number changes
Definition at line 76 of file BindingManager.h.
Referenced by addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingManager(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_boundInt
short FilamentBindingManager::_boundInt protected inherited
Integer index in CMonomer of bound chemical value.
Note
- THIS ALSO REPRESENTS THE SPECIES TYPE THAT IS MANAGED.
Definition at line 69 of file BindingManager.h.
Referenced by FilamentBindingManager::getBoundInt().
_boundName
string FilamentBindingManager::_boundName protected inherited
String name of bound chemical value.
Definition at line 72 of file BindingManager.h.
Referenced by FilamentBindingManager::getBoundName().
_branchrestarttuple
vector<tuple<tuple<CCylinder*, short>, tuple<CCylinder*, short> > > BranchingManager::_branchrestarttuple private
Definition at line 187 of file BindingManager.h.
_compartment
Compartment* FilamentBindingManager::_compartment protected inherited
Compartment this is in.
Definition at line 67 of file BindingManager.h.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingManager(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_filamentType
short FilamentBindingManager::_filamentType protected inherited
The filament type to operate on.
Definition at line 74 of file BindingManager.h.
Referenced by addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), FilamentBindingManager::getfilamentType(), isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_mIndex
short FilamentBindingManager::_mIndex = 0 protected inherited
Index of this manager (for access in other compartments)
Definition at line 80 of file BindingManager.h.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), LinkerBindingManager::removePossibleBindings(), and MotorBindingManager::removePossibleBindings().
_nlIndex
short FilamentBindingManager::_nlIndex = 0 protected inherited
Index of this manager (for access of neighbor lists)
Definition at line 79 of file BindingManager.h.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), MotorBindingManager::isConsistent(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_nucleationDistance
double BranchingManager::_nucleationDistance private
If using a nucleation zone, nucleating distance from the boundary.
Definition at line 183 of file BindingManager.h.
Referenced by addPossibleBindings(), and updateAllPossibleBindings().
_nucleationZone
NucleationZoneType BranchingManager::_nucleationZone private
Nucleation zone type, to define where nucleation should occur.
Definition at line 180 of file BindingManager.h.
Referenced by addPossibleBindings(), and updateAllPossibleBindings().
_possibleBindings
unordered_set<tuple<CCylinder*, short> > BranchingManager::_possibleBindings private
possible bindings at current state
Definition at line 186 of file BindingManager.h.
Referenced by addPossibleBindings(), isConsistent(), removePossibleBindings(), and updateAllPossibleBindings().
_subSystem
SubSystem * FilamentBindingManager::_subSystem = 0 static protected inherited
Ptr to the SubSystem.
Definition at line 82 of file BindingManager.h.
Referenced by addPossibleBindings(), ChemManager::genFilBindingReactions(), MotorBindingManager::isConsistent(), and updateAllPossibleBindings().
The documentation for this class was generated from the following files:
src/Chemistry/BindingManager.h
src/Chemistry/BindingManager.cpp