MEDYAN: FilamentStretching< FStretchingInteractionType > Class Template Reference
FilamentStretching< FStretchingInteractionType > Class Template Reference
Represents a Filament stretching interaction.
#include <FilamentStretching.h>
Public Member Functions
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
Filament * _filamentCulprit = nullptr
The filament in the case of an error.
Private Attributes
FStretchingInteractionType _FFType
Detailed Description
template<class FStretchingInteractionType>
class FilamentStretching< FStretchingInteractionType >
Represents a Filament stretching interaction.
Definition at line 23 of file FilamentStretching.h.
Member Function Documentation
computeEnergy()
template<class FStretchingInteractionType > template double FilamentStretching< FStretchingInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements FilamentInteractions.
Definition at line 21 of file FilamentStretching.cpp.
References Filament::getFilaments().
Referenced by FilamentStretching< FStretchingInteractionType >::computeForcesAux().
computeForces()
template<class FStretchingInteractionType > template void FilamentStretching< FStretchingInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements FilamentInteractions.
Definition at line 68 of file FilamentStretching.cpp.
References Filament::getFilaments().
Referenced by FilamentStretching< FStretchingInteractionType >::computeForcesAux().
computeForcesAux()
template<class FStretchingInteractionType > template void FilamentStretching< FStretchingInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements FilamentInteractions.
Definition at line 86 of file FilamentStretching.cpp.
References FilamentStretching< FStretchingInteractionType >::computeEnergy(), FilamentStretching< FStretchingInteractionType >::computeForces(), and Filament::getFilaments().
getName()
template<class FStretchingInteractionType > virtual const string FilamentStretching< FStretchingInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements FilamentInteractions.
Definition at line 33 of file FilamentStretching.h.
Member Data Documentation
_FFType
template<class FStretchingInteractionType > FStretchingInteractionType FilamentStretching< FStretchingInteractionType >::_FFType private
Definition at line 26 of file FilamentStretching.h.
_filamentCulprit
Filament* FilamentInteractions::_filamentCulprit = nullptr protected inherited
The filament in the case of an error.
Definition at line 31 of file FilamentInteractions.h.
Referenced by FilamentFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Filament/FilamentStretching.h
src/Mechanics/ForceField/Filament/FilamentStretching.cpp