MEDYAN: RandomBubbleDist Class Reference
RandomBubbleDist Class Reference
An implementation of BubbleInitialzer that creates a completely random Bubble distribution.
#include <BubbleInitializer.h>
Public Member Functions
BubbleData createBubbles (Boundary *b, int numBubbles, int bubbleType)
Returns a vector of tuples representing the Bubble type and beginning and end coordinates, similar to the structure of manual parsing.
Detailed Description
An implementation of BubbleInitialzer that creates a completely random Bubble distribution.
Definition at line 49 of file BubbleInitializer.h.
Member Function Documentation
createBubbles()
BubbleData RandomBubbleDist::createBubbles (Boundary * b, int numBubbles, int bubbleType) virtual
Returns a vector of tuples representing the Bubble type and beginning and end coordinates, similar to the structure of manual parsing.
Implements BubbleInitializer.
Definition at line 22 of file BubbleInitializer.cpp.
References MechParams::BubbleRadius, Boundary::distance(), GController::getRandomCoordinates(), SysParams::Mechanics(), and Boundary::within().
The documentation for this class was generated from the following files:
src/BubbleInitializer.h
src/BubbleInitializer.cpp