MEDYAN: CylinderExclVolume< CVolumeInteractionType > Class Template Reference
CylinderExclVolume< CVolumeInteractionType > Class Template Reference
Represents an excuded volume interaction between two Cylinders.
#include <CylinderExclVolume.h>
Public Member Functions
CylinderExclVolume ()
Constructor.
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute the forces of this interaction.
virtual void computeForcesAux ()
Compute the auxiliary forces of this interaction.
virtual NeighborList * getNeighborList ()
Get the neighbor list for this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
Cylinder * _cylinderCulprit1 = nullptr
The cylinder culprits in the case of an error.
Cylinder * _cylinderCulprit2 = nullptr
The cylinder culprits in the case of an error.
Private Attributes
CVolumeInteractionType _FFType
CylinderCylinderNL * _neighborList
Neighbor list of cylinders.
Detailed Description
template<class CVolumeInteractionType>
class CylinderExclVolume< CVolumeInteractionType >
Represents an excuded volume interaction between two Cylinders.
Definition at line 29 of file CylinderExclVolume.h.
Constructor & Destructor Documentation
CylinderExclVolume()
template<class CVolumeInteractionType > CylinderExclVolume< CVolumeInteractionType >::CylinderExclVolume () inline
Constructor.
Definition at line 37 of file CylinderExclVolume.h.
References CylinderExclVolume< CVolumeInteractionType >::computeEnergy(), CylinderExclVolume< CVolumeInteractionType >::computeForces(), CylinderExclVolume< CVolumeInteractionType >::computeForcesAux(), and SysParams::Mechanics().
Member Function Documentation
computeEnergy()
template<class CVolumeInteractionType > template double CylinderExclVolume< CVolumeInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements CylinderVolumeInteractions.
Definition at line 22 of file CylinderExclVolume.cpp.
References Cylinder::getCylinders().
Referenced by CylinderExclVolume< CVolumeInteractionType >::computeForcesAux(), and CylinderExclVolume< CVolumeInteractionType >::CylinderExclVolume().
computeForces()
template<class CVolumeInteractionType > template void CylinderExclVolume< CVolumeInteractionType >::computeForces () virtual
Compute the forces of this interaction.
Implements CylinderVolumeInteractions.
Definition at line 67 of file CylinderExclVolume.cpp.
References Cylinder::getCylinders().
Referenced by CylinderExclVolume< CVolumeInteractionType >::computeForcesAux(), and CylinderExclVolume< CVolumeInteractionType >::CylinderExclVolume().
computeForcesAux()
template<class CVolumeInteractionType > template void CylinderExclVolume< CVolumeInteractionType >::computeForcesAux () virtual
Compute the auxiliary forces of this interaction.
Implements CylinderVolumeInteractions.
Definition at line 93 of file CylinderExclVolume.cpp.
References CylinderExclVolume< CVolumeInteractionType >::computeEnergy(), CylinderExclVolume< CVolumeInteractionType >::computeForces(), and Cylinder::getCylinders().
Referenced by CylinderExclVolume< CVolumeInteractionType >::CylinderExclVolume().
getName()
template<class CVolumeInteractionType > virtual const string CylinderExclVolume< CVolumeInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements CylinderVolumeInteractions.
Definition at line 48 of file CylinderExclVolume.h.
getNeighborList()
template<class CVolumeInteractionType > virtual NeighborList* CylinderExclVolume< CVolumeInteractionType >::getNeighborList () inline virtual
Get the neighbor list for this interaction.
Implements CylinderVolumeInteractions.
Definition at line 46 of file CylinderExclVolume.h.
References CylinderExclVolume< CVolumeInteractionType >::_neighborList.
Member Data Documentation
_cylinderCulprit1
Cylinder* CylinderVolumeInteractions::_cylinderCulprit1 = nullptr protected inherited
The cylinder culprits in the case of an error.
Definition at line 31 of file CylinderVolumeInteractions.h.
Referenced by CylinderVolumeFF::whoIsCulprit().
_cylinderCulprit2
Cylinder* CylinderVolumeInteractions::_cylinderCulprit2 = nullptr protected inherited
The cylinder culprits in the case of an error.
Definition at line 32 of file CylinderVolumeInteractions.h.
Referenced by CylinderVolumeFF::whoIsCulprit().
_FFType
template<class CVolumeInteractionType > CVolumeInteractionType CylinderExclVolume< CVolumeInteractionType >::_FFType private
Definition at line 32 of file CylinderExclVolume.h.
_neighborList
template<class CVolumeInteractionType > CylinderCylinderNL* CylinderExclVolume< CVolumeInteractionType >::_neighborList private
Neighbor list of cylinders.
Definition at line 33 of file CylinderExclVolume.h.
Referenced by CylinderExclVolume< CVolumeInteractionType >::getNeighborList().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Volume/CylinderExclVolume.h
src/Mechanics/ForceField/Volume/CylinderExclVolume.cpp