M3Sym: SystemParameters Class Reference
SystemParameters Class Reference
Static class that holds all simulation parameters, initialized by the SystemParser.
#include <SystemParameters.h>
Static Public Member Functions
static const MechanicsParameters & Mechanics ()
Const getter.
static const ChemistryParameters & Chemistry ()
static const GeometryParameters & Geometry ()
static const BoundaryParameters & Boundaries ()
Static Public Attributes
static MechanicsParameters MParams
Public access if testing only.
static ChemistryParameters CParams
The chemistry parameters.
static GeometryParameters GParams
The geometry parameters.
static BoundaryParameters BParams
The boundary parameters.
Friends
class SystemParser
Detailed Description
Static class that holds all simulation parameters, initialized by the SystemParser.
Definition at line 114 of file SystemParameters.h.
Member Function Documentation
static const BoundaryParameters& SystemParameters::Boundaries () inline static
Definition at line 131 of file SystemParameters.h.
References BParams.
Referenced by CylinderZ::CylinderZ(), HalfSphereZ::HalfSphereZ(), Controller::initialize(), Plane::Plane(), and Sphere::Sphere().
static const ChemistryParameters& SystemParameters::Chemistry () inline static
Definition at line 129 of file SystemParameters.h.
References CParams.
Referenced by CMonomer::addSpeciesBound(), CMonomer::addSpeciesFilament(), CMonomer::addSpeciesLinker(), CMonomer::addSpeciesMinusEnd(), CMonomer::addSpeciesMotor(), CMonomer::addSpeciesPlusEnd(), CMonomer::CMonomer(), CMonomer::print(), and CCylinder::~CCylinder().
static const GeometryParameters& SystemParameters::Geometry () inline static
Definition at line 130 of file SystemParameters.h.
References GParams.
Referenced by SubSystem::addNewFilament(), SubSystem::addNewFilaments(), LinkerBindingManager::addReaction(), MotorBindingManager::addReaction(), BoundaryCapsule::BoundaryCapsule(), BoundaryCubic::BoundaryCubic(), BoundarySpherical::BoundarySpherical(), Cylinder::Cylinder(), Filament::depolymerizeBack(), Filament::depolymerizeFront(), Filament::extendBack(), Filament::extendFront(), Filament::Filament(), Controller::initialize(), GController::initializeGrid(), Linker::Linker(), MotorGhost::MotorGhost(), LinkerBindingCallback::operator()(), MotorBindingCallback::operator()(), MotorWalkingForwardCallback::operator()(), MotorWalkingBackwardCallback::operator()(), MotorMovingCylinderBackwardCallback::operator()(), Filament::polymerizeBack(), Filament::polymerizeFront(), SystemParser::readBoundaryParameters(), MCylinder::setEqLength(), Filament::straightFilamentProjection(), CylinderNeighborList::updateNeighbors(), Filament::zigZagFilamentProjection(), Linker::~Linker(), and MotorGhost::~MotorGhost().
static const MechanicsParameters& SystemParameters::Mechanics () inline static
Const getter.
Definition at line 128 of file SystemParameters.h.
Referenced by Linker::Linker(), MCylinder::MCylinder(), MotorGhost::MotorGhost(), and MCylinder::setEqLength().
Friends And Related Function Documentation
friend class SystemParser friend
Definition at line 115 of file SystemParameters.h.
Member Data Documentation
BoundaryParameters SystemParameters::BParams static
The boundary parameters.
Definition at line 123 of file SystemParameters.h.
Referenced by Boundaries(), and SystemParser::readBoundaryParameters().
ChemistryParameters SystemParameters::CParams static
The chemistry parameters.
Definition at line 121 of file SystemParameters.h.
Referenced by Chemistry(), and SystemParser::readChemistryParameters().
GeometryParameters SystemParameters::GParams static
The geometry parameters.
Definition at line 122 of file SystemParameters.h.
Referenced by Geometry(), and SystemParser::readGeometryParameters().
MechanicsParameters SystemParameters::MParams static
Public access if testing only.
The mechanical parameters
Definition at line 120 of file SystemParameters.h.
Referenced by SystemParser::readMechanicsParameters().
The documentation for this class was generated from the following files:
M3SYM/SystemParameters.h
M3SYM/SystemParameters.cpp