MEDYAN: Database< T > Class Template Reference
Database< T > Class Template Reference
A collection class to hold instances of a given class.
#include <Database.h>
Public Member Functions
void addElement (T elem)
Add an element to the collection.
void removeElement (T elem)
Remove an element from the collection.
void clearElements ()
Clear the contents of the database.
vector< T > & getElements ()
Get all items in database.
int countElements ()
Count the number of objects in the collection.
int getID ()
Return a unique id.
int deleteID ()
Used for a deletion of ID.
Protected Attributes
vector< T > _elems
The elements in the collection.
int _ID = 0
Running unique index of each element.
Detailed Description
template<class T>
class Database< T >
A collection class to hold instances of a given class.
The Database class is a template for holding a collection of objects It is used by all elements in the SubSystem to track instances of the given class. The databases are then used in various ways, i.e. mechanical minimization uses all beads for its Minimizer methods, ForceField uses the collections to calculate forces and energy, etc.
The Database also contains a holder for a transfer ID of any species. This is used when diffusing species ID's must be tracked, and these ID's are accessed by the respective binding managers.
Parameters
T - class to hold
Definition at line 38 of file Database.h.
Member Function Documentation
addElement()
template<class T> void Database< T >::addElement (T elem) inline
Add an element to the collection.
Definition at line 52 of file Database.h.
Referenced by Bead::addAsPinned(), SubSystem::addNeighborList(), Bead::getBirthTime(), BranchingPoint::getBirthTime(), Linker::getBirthTime(), MotorGhost::getBirthTime(), MTOC::getFilaments(), Filament::getPlusEndCylinder(), Cylinder::getPosition(), BoundaryElement::getScreeningLength(), and Bubble::isMTOC().
clearElements()
template<class T> void Database< T >::clearElements () inline
Clear the contents of the database.
Definition at line 66 of file Database.h.
countElements()
template<class T> int Database< T >::countElements () inline
Count the number of objects in the collection.
Definition at line 72 of file Database.h.
Referenced by Bead::numBeads(), BoundaryElement::numBoundaryElements(), BranchingPoint::numBranchingPoints(), Bubble::numBubbles(), Cylinder::numCylinders(), Filament::numFilaments(), Linker::numLinkers(), MotorGhost::numMotorGhosts(), and MTOC::numMTOCs().
deleteID()
template<class T> int Database< T >::deleteID () inline
Used for a deletion of ID.
Definition at line 78 of file Database.h.
getElements()
template<class T> vector<T>& Database< T >::getElements () inline
Get all items in database.
Definition at line 69 of file Database.h.
Referenced by SubSystem::addTrackable(), BranchingPoint::countSpecies(), Linker::countSpecies(), MotorGhost::countSpecies(), Filament::countSpecies(), Bead::getBeads(), BoundaryElement::getBoundaryElements(), BranchingPoint::getBranchingPoints(), Bubble::getBubbles(), Cylinder::getCylinders(), Filament::getFilaments(), Linker::getLinkers(), MotorGhost::getMotorGhosts(), MTOC::getMTOCs(), Bead::getPinnedBeads(), SubSystem::removeTrackable(), and SubSystem::resetNeighborLists().
getID()
template<class T> int Database< T >::getID () inline
Return a unique id.
Definition at line 75 of file Database.h.
Referenced by Filament::Filament().
removeElement()
template<class T> void Database< T >::removeElement (T elem) inline
Remove an element from the collection.
Definition at line 58 of file Database.h.
Referenced by Bead::removeAsPinned(), MTOC::removeFromSubSystem(), Bubble::removeFromSubSystem(), Bead::removeFromSubSystem(), BoundaryElement::removeFromSubSystem(), BranchingPoint::removeFromSubSystem(), Linker::removeFromSubSystem(), Cylinder::removeFromSubSystem(), MotorGhost::removeFromSubSystem(), and Filament::removeFromSubSystem().
Member Data Documentation
_elems
template<class T> vector<T> Database< T >::_elems protected
The elements in the collection.
Definition at line 41 of file Database.h.
Referenced by Database< Bead *>::getElements().
_ID
template<class T> int Database< T >::_ID = 0 protected
Running unique index of each element.
Definition at line 43 of file Database.h.
Referenced by Database< Bead *>::deleteID().
The documentation for this class was generated from the following file:
src/Structure/Database.h