MEDYAN: BoundaryCubic Class Reference
BoundaryCubic Class Reference
A cubic Boundary implementation.
#include <BoundaryImpl.h>
Public Member Functions
BoundaryCubic (SubSystem *s, BoundaryMove move)
Default constructor, this will create a cube with given corners at edges of current CompartmentGrid.
virtual bool within (Compartment *C)
Check if a compartment is within boundary.
virtual bool within (const vector< double > &coordinates)
Check if coordinates are within boundary.
virtual double distance (const vector< double > &coordinates)
Get the distance from the boundary.
virtual void move (double dist)
Move a given part of a boundary a given distance.
virtual vector< double > normal (vector< double > &coordinates)
Returns the normal inward at this coordinate.
BoundaryShape getShape ()
Get shape of this boundary.
const vector< unique_ptr< BoundarySurface > > & getBoundarySurfaces ()
Get boundary surfaces.
Protected Attributes
SubSystem * _subSystem
SubSystem ptr.
vector< unique_ptr< BoundarySurface > > _boundarySurfaces
Vector of boundarysurfaces (could be different implementations)
BoundaryShape _shape
Shape of boundary.
BoundaryMove _move
Movement of boundary.
short _nDim
Dimensionality.
Detailed Description
A cubic Boundary implementation.
Definition at line 27 of file BoundaryImpl.h.
Constructor & Destructor Documentation
BoundaryCubic()
BoundaryCubic::BoundaryCubic (SubSystem * s, BoundaryMove move)
Default constructor, this will create a cube with given corners at edges of current CompartmentGrid.
Definition at line 24 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces, and GController::getSize().
Member Function Documentation
distance()
double BoundaryCubic::distance (const vector< double > & coordinates) virtual
Get the distance from the boundary.
Returns the distance from closest boundary element in the boundary. Will return infinity if outside of the boundary.
Implements Boundary.
Definition at line 95 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces.
Referenced by PlaneBoundaryElement::stretchedDistance().
getBoundarySurfaces()
const vector<unique_ptr<BoundarySurface> >& Boundary::getBoundarySurfaces () inline inherited
Get boundary surfaces.
Definition at line 59 of file Boundary.h.
getShape()
BoundaryShape Boundary::getShape () inline inherited
Get shape of this boundary.
Definition at line 56 of file Boundary.h.
move()
void BoundaryCubic::move (double dist) virtual
Move a given part of a boundary a given distance.
Note
a negative distance denotes movement towards the center of the grid.
Implements Boundary.
Definition at line 136 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces, Boundary::_move, All, None, and Top.
normal()
vector< double > BoundaryCubic::normal (vector< double > & coordinates) virtual
Returns the normal inward at this coordinate.
Implements Boundary.
Definition at line 113 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces, and BoundaryElement::normal().
Referenced by BoundarySpherical::move(), and within().
within() [1/2]
bool BoundaryCubic::within (Compartment * C) virtual
Check if a compartment is within boundary.
Note
- this checks if ANY part of the compartment volume is within the boundary.
Implements Boundary.
Definition at line 52 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces, GeoParams::compartmentSizeX, GeoParams::compartmentSizeY, GeoParams::compartmentSizeZ, Compartment::coordinates(), SysParams::Geometry(), and normal().
within() [2/2]
bool BoundaryCubic::within (const vector< double > & coordinates) virtual
Check if coordinates are within boundary.
Implements Boundary.
Definition at line 81 of file BoundaryImpl.cpp.
References Boundary::_boundarySurfaces.
Member Data Documentation
_boundarySurfaces
vector<unique_ptr<BoundarySurface> > Boundary::_boundarySurfaces protected inherited
Vector of boundarysurfaces (could be different implementations)
Definition at line 42 of file Boundary.h.
Referenced by BoundaryCapsule::BoundaryCapsule(), BoundaryCubic(), BoundarySpherical::BoundarySpherical(), distance(), BoundarySpherical::distance(), BoundaryCapsule::distance(), move(), normal(), BoundarySpherical::normal(), within(), BoundarySpherical::within(), and BoundaryCapsule::within().
_move
BoundaryMove Boundary::_move protected inherited
Movement of boundary.
Definition at line 45 of file Boundary.h.
Referenced by move().
_nDim
short Boundary::_nDim protected inherited
Dimensionality.
Definition at line 47 of file Boundary.h.
_shape
BoundaryShape Boundary::_shape protected inherited
Shape of boundary.
Definition at line 44 of file Boundary.h.
_subSystem
SubSystem* Boundary::_subSystem protected inherited
SubSystem ptr.
Definition at line 39 of file Boundary.h.
The documentation for this class was generated from the following files:
src/Structure/BoundaryImpl.h
src/Structure/BoundaryImpl.cpp