MEDYAN: BoundaryCylinderNL Class Reference
BoundaryCylinderNL Class Reference
An implementation of NeighborList for BoundaryElement-Cylinder interactions.
#include <NeighborListImpl.h>
Public Member Functions
BoundaryCylinderNL (float rMax)
virtual void addNeighbor (Neighbor *n)
Add neighbor.
virtual void removeNeighbor (Neighbor *n)
Remove a neighbor if possible.
virtual void addDynamicNeighbor (DynamicNeighbor *n)
Add a dynamic neighbor to the system.
virtual void removeDynamicNeighbor (DynamicNeighbor *n)
Remove a dynamic neighbor from the system.
virtual void reset ()
Re-initialize the neighborlist.
vector< Cylinder * > getNeighbors (BoundaryElement *be)
Get all Cylinder neighbors of a boundary element.
Protected Attributes
float _rMax
max distance cutoff
float _rMin
min distance cutoff
Private Member Functions
void updateNeighbors (BoundaryElement *be)
Helper function to update neighbors.
Private Attributes
unordered_map< BoundaryElement *, vector< Cylinder * > > _list
The neighbors list, as a hash map.
Detailed Description
An implementation of NeighborList for BoundaryElement-Cylinder interactions.
Definition at line 68 of file NeighborListImpl.h.
Constructor & Destructor Documentation
BoundaryCylinderNL()
BoundaryCylinderNL::BoundaryCylinderNL (float rMax) inline
Definition at line 78 of file NeighborListImpl.h.
References CylinderCylinderNL::addDynamicNeighbor(), CylinderCylinderNL::addNeighbor(), CylinderCylinderNL::getNeighbors(), CylinderCylinderNL::removeDynamicNeighbor(), CylinderCylinderNL::removeNeighbor(), and CylinderCylinderNL::reset().
Member Function Documentation
addDynamicNeighbor()
void BoundaryCylinderNL::addDynamicNeighbor (DynamicNeighbor * n) virtual
Add a dynamic neighbor to the system.
For BoundaryElementNeighborList list, this will be Bead. For CylinderNeighborList, all elements in neighbors list are dynamic.
Implements NeighborList.
Definition at line 148 of file NeighborListImpl.cpp.
References Cylinder::coordinate.
addNeighbor()
void BoundaryCylinderNL::addNeighbor (Neighbor * n) virtual
Add neighbor.
Implements NeighborList.
Definition at line 130 of file NeighborListImpl.cpp.
getNeighbors()
vector< Cylinder * > BoundaryCylinderNL::getNeighbors (BoundaryElement * be)
Get all Cylinder neighbors of a boundary element.
Definition at line 187 of file NeighborListImpl.cpp.
removeDynamicNeighbor()
void BoundaryCylinderNL::removeDynamicNeighbor (DynamicNeighbor * n) virtual
Remove a dynamic neighbor from the system.
For BoundaryElementNeighborList list, this will be Bead. For CylinderNeighborList, all elements in neighbors list are dynamic.
Implements NeighborList.
Definition at line 163 of file NeighborListImpl.cpp.
removeNeighbor()
void BoundaryCylinderNL::removeNeighbor (Neighbor * n) virtual
Remove a neighbor if possible.
Implements NeighborList.
Definition at line 140 of file NeighborListImpl.cpp.
reset()
void BoundaryCylinderNL::reset () virtual
Re-initialize the neighborlist.
Implements NeighborList.
Definition at line 177 of file NeighborListImpl.cpp.
References BoundaryElement::getBoundaryElements().
updateNeighbors()
void BoundaryCylinderNL::updateNeighbors (BoundaryElement * be) private
Helper function to update neighbors.
Definition at line 116 of file NeighborListImpl.cpp.
References BoundaryElement::distance(), and Cylinder::getCylinders().
Member Data Documentation
_list
unordered_map<BoundaryElement*, vector<Cylinder*> > BoundaryCylinderNL::_list private
The neighbors list, as a hash map.
Definition at line 71 of file NeighborListImpl.h.
_rMax
float NeighborList::_rMax protected inherited
max distance cutoff
Definition at line 36 of file NeighborList.h.
_rMin
float NeighborList::_rMin protected inherited
min distance cutoff
Definition at line 37 of file NeighborList.h.
The documentation for this class was generated from the following files:
src/Structure/NeighborListImpl.h
src/Structure/NeighborListImpl.cpp