M3Sym: BoundaryRepulsion< BRepulsionInteractionType > Class Template Reference
BoundaryRepulsion< BRepulsionInteractionType > Class Template Reference
Represents a repulsive interaction between a BoundaryElement and Bead.
#include <BoundaryRepulsion.h>
Public Member Functions
virtual double computeEnergy (BoundaryElement *, Bead *, double d)
Template specializations.
virtual void computeForces (BoundaryElement *, Bead *)
Compute forces of this interaction.
virtual void computeForcesAux (BoundaryElement *, Bead *)
Compute auxiliary forces of this interaction.
string getName ()
Get name of interaction.
BoundaryElementNeighborList * getNeighborList ()
Get neighbor list.
Private Attributes
BRepulsionInteractionType _FFType
Detailed Description
template<class BRepulsionInteractionType>
class BoundaryRepulsion< BRepulsionInteractionType >
Represents a repulsive interaction between a BoundaryElement and Bead.
Definition at line 29 of file BoundaryRepulsion.h.
Member Function Documentation
template<class BRepulsionInteractionType > template double BoundaryRepulsion< BRepulsionInteractionType >::computeEnergy (BoundaryElement * , Bead * , double d) virtual
Template specializations.
Implements BoundaryInteractions.
Definition at line 23 of file BoundaryRepulsion.cpp.
References Bead::coordinate, BoundaryElement::distance(), Bead::force, BoundaryElement::getRepulsionConst(), BoundaryElement::getScreeningLength(), and BoundaryElement::stretchedDistance().
template<class BRepulsionInteractionType > template void BoundaryRepulsion< BRepulsionInteractionType >::computeForces (BoundaryElement * , Bead *) virtual
Compute forces of this interaction.
Implements BoundaryInteractions.
Definition at line 37 of file BoundaryRepulsion.cpp.
References Bead::coordinate, BoundaryElement::distance(), BoundaryElement::getRepulsionConst(), BoundaryElement::getScreeningLength(), and BoundaryElement::normal().
template<class BRepulsionInteractionType > template void BoundaryRepulsion< BRepulsionInteractionType >::computeForcesAux (BoundaryElement * , Bead *) virtual
Compute auxiliary forces of this interaction.
Implements BoundaryInteractions.
Definition at line 49 of file BoundaryRepulsion.cpp.
References Bead::coordinateAux, BoundaryElement::distance(), BoundaryElement::getRepulsionConst(), BoundaryElement::getScreeningLength(), and BoundaryElement::normal().
string BoundaryInteractions::getName () inline inherited
Get name of interaction.
Definition at line 43 of file BoundaryInteractions.h.
References BoundaryInteractions::_name.
BoundaryElementNeighborList* BoundaryElementNLContainer::getNeighborList () inline inherited
Get neighbor list.
Definition at line 65 of file NeighborListContainer.h.
References BoundaryElementNLContainer::_neighborList.
Member Data Documentation
template<class BRepulsionInteractionType > BRepulsionInteractionType BoundaryRepulsion< BRepulsionInteractionType >::_FFType private
Definition at line 32 of file BoundaryRepulsion.h.
The documentation for this class was generated from the following files:
M3SYM/Mechanics/ForceField/BoundaryRepulsion.h
M3SYM/Mechanics/ForceField/BoundaryRepulsion.cpp