MEDYAN: BirthTimes Class Reference
BirthTimes Class Reference
Print birth times of beads for each Filament, Linker, MotorGhost, and BranchingPoint.
#include <Output.h>
Public Member Functions
BirthTimes (string outputFileName, SubSystem *s)
~BirthTimes ()
virtual void print (int snapshot)
To be implemented in sub classes.
Protected Attributes
ofstream _outputFile
The output file being used.
SubSystem * _subSystem = nullptr
Detailed Description
Print birth times of beads for each Filament, Linker, MotorGhost, and BranchingPoint.
Definition at line 73 of file Output.h.
Constructor & Destructor Documentation
BirthTimes()
BirthTimes::BirthTimes (string outputFileName, SubSystem * s) inline
Definition at line 76 of file Output.h.
~BirthTimes()
BirthTimes::~BirthTimes () inline
Definition at line 77 of file Output.h.
References Output::print().
Member Function Documentation
print()
void BirthTimes::print (int snapshot) virtual
To be implemented in sub classes.
Implements Output.
Definition at line 164 of file Output.cpp.
References BranchingPoint::getBranchingPoints(), Bubble::getBubbles(), Filament::getFilaments(), Linker::getLinkers(), MotorGhost::getMotorGhosts(), BranchingPoint::numBranchingPoints(), Bubble::numBubbles(), Filament::numFilaments(), Linker::numLinkers(), MotorGhost::numMotorGhosts(), and tau().
Member Data Documentation
_outputFile
ofstream Output::_outputFile protected inherited
The output file being used.
Definition at line 36 of file Output.h.
_subSystem
SubSystem* Output::_subSystem = nullptr protected inherited
Definition at line 38 of file Output.h.
Referenced by GController::getSubSystem().
The documentation for this class was generated from the following files:
src/Output.h
src/Output.cpp