MEDYAN: BranchingBendingCosine Class Reference
BranchingBendingCosine Class Reference
A cosine potential used by the BranchingBending template.
#include <BranchingBendingCosine.h>
Public Member Functions
double energy (Bead *, Bead *, Bead *, Bead *, double, double)
double energy (Bead *, Bead *, Bead *, Bead *, double, double, double)
void forces (Bead *, Bead *, Bead *, Bead *, double, double)
void forcesAux (Bead *, Bead *, Bead *, Bead *, double, double)
Detailed Description
A cosine potential used by the BranchingBending template.
Definition at line 23 of file BranchingBendingCosine.h.
Member Function Documentation
energy() [1/2]
double BranchingBendingCosine::energy (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double kBend, double eqTheta)
Definition at line 24 of file BranchingBendingCosine.cpp.
References Bead::coordinate, safeacos(), and mathfunc::scalarProduct().
energy() [2/2]
double BranchingBendingCosine::energy (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double kBend, double eqTheta, double d)
Definition at line 46 of file BranchingBendingCosine.cpp.
References Bead::coordinate, Bead::force, safeacos(), and mathfunc::scalarProductStretched().
forces()
void BranchingBendingCosine::forces (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double kBend, double eqTheta)
Definition at line 73 of file BranchingBendingCosine.cpp.
References Bead::coordinate, Bead::force, safeacos(), and mathfunc::scalarProduct().
forcesAux()
void BranchingBendingCosine::forcesAux (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double kBend, double eqTheta)
Definition at line 145 of file BranchingBendingCosine.cpp.
References Bead::coordinate, Bead::forceAux, safeacos(), and mathfunc::scalarProduct().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Branching/BranchingBendingCosine.h
src/Mechanics/ForceField/Branching/BranchingBendingCosine.cpp