MEDYAN: Composite Class Reference
Composite Class Reference abstract
The aggregating class for the Composite pattern.
#include <Composite.h>
Public Member Functions
Composite ()
Default Constructor does nothing.
virtual ~Composite () noexcept
Virtual Destructor does nothing.
virtual bool apply (Visitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
virtual bool apply (SpeciesVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool isComposite () const override
Returns true.
virtual string getFullName () const override
Returns the full name of this node.
virtual void addChild (unique_ptr< Component > &&child)
Adds a Component child to this Composite node.
virtual void removeChild (Component *child)
Remove *child from this node's children.
virtual size_t numberOfChildren () const override
Returns the number of immediate children of this node.
virtual size_t numberOfSpecies () const override
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t countDescendents () const override
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const override
Returns the number of Species being managed by this node and its descendent nodes.
virtual size_t numberOfReactions () const override
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual size_t countReactions () const override
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
virtual vector< unique_ptr< Component > > & children ()
Returns a reference to the container of Component children of this node.
virtual const vector< unique_ptr< Component > > & children () const
Returns a const reference to the container of Component children of this node.
virtual Component * children (size_t i)
Returns a pointer to the i-th Component child of this node.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
virtual void printSelf ()=0
Prints information about this node. Useful for debugging.
virtual int getType ()=0
Return the type of this element as an integer index.
Private Attributes
vector< unique_ptr< Component > > _children
Child node pointers of this composite node.
Detailed Description
The aggregating class for the Composite pattern.
The Composite pattern allows building of complex hieararchical objects, with convenient methods for applying a function to all nodes (i.e. the Visitor pattern). Each node in the hieararchy may have a parent and may contain several children nodes. A class that is derived from Composite can contain children Component objects.
Note
Composite objects may contain other collections, however, this is treated seperately from the Composite pattern (i.e. separate methods exist for the corresponding access to elements, changes, etc.)
Definition at line 42 of file Composite.h.
Constructor & Destructor Documentation
Composite()
Composite::Composite () inline
Default Constructor does nothing.
Definition at line 49 of file Composite.h.
~Composite()
virtual Composite::~Composite () inline virtual noexcept
Virtual Destructor does nothing.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 56 of file Composite.h.
References apply().
Member Function Documentation
addChild()
virtual void Composite::addChild (unique_ptr< Component > && child) inline virtual
Adds a Component child to this Composite node.
Parameters
child - is a unique_ptr<Component>, hence, this node takes the memory ownership of the corresponding child pointer.
Note
the rvalue semantics - the unique_ptr<...> cannot be copied, but only can be moved
Definition at line 81 of file Composite.h.
Referenced by Bead::Bead(), CompartmentGrid::CompartmentGrid(), Cylinder::Cylinder(), MTOC::setBubble(), and Filament::sever().
apply() [1/3]
bool Composite::apply (Visitor & v) override virtual
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
Reimplemented from Component.
Definition at line 18 of file Composite.cpp.
References children(), and Visitor::visit().
Referenced by ~Composite().
apply() [2/3]
bool Composite::apply (SpeciesVisitor & v) override virtual
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented from Component.
Definition at line 31 of file Composite.cpp.
References Component::apply_impl(), and children().
apply() [3/3]
bool Composite::apply (ReactionVisitor & v) override virtual
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented from Component.
Definition at line 43 of file Composite.cpp.
References Component::apply_impl(), and children().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
children() [1/3]
virtual vector<unique_ptr<Component> >& Composite::children () inline virtual
Returns a reference to the container of Component children of this node.
Definition at line 145 of file Composite.h.
References _children.
Referenced by apply(), countDescendents(), countReactions(), countSpecies(), CompartmentGrid::getCompartment(), CompartmentGrid::getCompartments(), numberOfChildren(), and CompartmentGrid::printSelf().
children() [2/3]
virtual const vector<unique_ptr<Component> >& Composite::children () const inline virtual
Returns a const reference to the container of Component children of this node.
Definition at line 148 of file Composite.h.
References _children.
children() [3/3]
virtual Component* Composite::children (size_t i) inline virtual
Returns a pointer to the i-th Component child of this node.
Definition at line 151 of file Composite.h.
countDescendents()
virtual size_t Composite::countDescendents () const inline override virtual
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented from Component.
Definition at line 110 of file Composite.h.
References children(), numberOfChildren(), and std::sum().
countReactions()
virtual size_t Composite::countReactions () const inline override virtual
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 135 of file Composite.h.
References children(), Component::isReactionsContainer(), numberOfReactions(), and std::sum().
countSpecies()
virtual size_t Composite::countSpecies () const inline override virtual
Returns the number of Species being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 120 of file Composite.h.
References children(), Component::isSpeciesContainer(), numberOfSpecies(), and std::sum().
Referenced by Filament::getTurnoverTimes(), and Chemistry::print().
getFullName()
virtual string Composite::getFullName () const inline override virtual
Returns the full name of this node.
Reimplemented from Component.
Reimplemented in Compartment, and CompartmentGrid.
Definition at line 74 of file Composite.h.
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getType()
virtual int Component::getType () pure virtual inherited
Return the type of this element as an integer index.
Implemented in Compartment, Filament, CompartmentGrid, MotorGhost, Bead, BoundaryElement, Linker, Cylinder, BranchingPoint, MTOC, and Bubble.
Referenced by Component::countReactions(), and Bead::getType().
isComposite()
virtual bool Composite::isComposite () const inline override virtual
Returns true.
Reimplemented from Component.
Definition at line 71 of file Composite.h.
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by countSpecies().
numberOfChildren()
virtual size_t Composite::numberOfChildren () const inline override virtual
Returns the number of immediate children of this node.
Note
Species and reactions and not included in this tally
Reimplemented from Component.
Definition at line 102 of file Composite.h.
References children().
Referenced by countDescendents(), and CompartmentGrid::printSelf().
numberOfReactions()
virtual size_t Composite::numberOfReactions () const inline override virtual
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented from Component.
Reimplemented in Compartment.
Definition at line 131 of file Composite.h.
Referenced by countReactions().
numberOfSpecies()
virtual size_t Composite::numberOfSpecies () const inline override virtual
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.)
Reimplemented from Component.
Reimplemented in Compartment.
Definition at line 106 of file Composite.h.
Referenced by countSpecies().
printSelf()
virtual void Component::printSelf () pure virtual inherited
Prints information about this node. Useful for debugging.
Implemented in Compartment, Filament, MotorGhost, Cylinder, Linker, Bead, BranchingPoint, BoundaryElement, CompartmentGrid, Bubble, and MTOC.
Referenced by Bead::Bead(), Component::countReactions(), Bead::updatePosition(), BubbleFF::whoIsCulprit(), and BoundaryFF::whoIsCulprit().
removeChild()
virtual void Composite::removeChild (Component * child) inline virtual
Remove *child from this node's children.
The child's destructor will be called and the memory will be freed.
Definition at line 89 of file Composite.h.
Referenced by Filament::retractMinusEnd(), and Filament::retractPlusEnd().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
Member Data Documentation
_children
vector<unique_ptr<Component> > Composite::_children private
Child node pointers of this composite node.
Definition at line 44 of file Composite.h.
Referenced by children().
The documentation for this class was generated from the following files:
src/Composite.h
src/Composite.cpp