MEDYAN: BranchingDihedral< BDihedralInteractionType > Class Template Reference
BranchingDihedral< BDihedralInteractionType > Class Template Reference
Represents an interaction keeping BranchingPoint in dihedral plane.
#include <BranchingDihedral.h>
Public Member Functions
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
BranchingPoint * _branchingCulprit = nullptr
The branching point in the case of an error.
Private Attributes
BDihedralInteractionType _FFType
Detailed Description
template<class BDihedralInteractionType>
class BranchingDihedral< BDihedralInteractionType >
Represents an interaction keeping BranchingPoint in dihedral plane.
Definition at line 26 of file BranchingDihedral.h.
Member Function Documentation
computeEnergy()
template<class BDihedralInteractionType > template double BranchingDihedral< BDihedralInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BranchingInteractions.
Definition at line 23 of file BranchingDihedral.cpp.
References BranchingPoint::getBranchingPoints(), and Bead::getPosition().
Referenced by BranchingDihedral< BDihedralInteractionType >::computeForcesAux().
computeForces()
template<class BDihedralInteractionType > template void BranchingDihedral< BDihedralInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements BranchingInteractions.
Definition at line 60 of file BranchingDihedral.cpp.
References BranchingPoint::getBranchingPoints(), and Bead::getPosition().
Referenced by BranchingDihedral< BDihedralInteractionType >::computeForcesAux().
computeForcesAux()
template<class BDihedralInteractionType > template void BranchingDihedral< BDihedralInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements BranchingInteractions.
Definition at line 77 of file BranchingDihedral.cpp.
References BranchingDihedral< BDihedralInteractionType >::computeEnergy(), BranchingDihedral< BDihedralInteractionType >::computeForces(), BranchingPoint::getBranchingPoints(), and Bead::getPosition().
getName()
template<class BDihedralInteractionType > virtual const string BranchingDihedral< BDihedralInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BranchingInteractions.
Definition at line 36 of file BranchingDihedral.h.
Member Data Documentation
_branchingCulprit
BranchingPoint* BranchingInteractions::_branchingCulprit = nullptr protected inherited
The branching point in the case of an error.
Definition at line 31 of file BranchingInteractions.h.
Referenced by BranchingFF::whoIsCulprit().
_FFType
template<class BDihedralInteractionType > BDihedralInteractionType BranchingDihedral< BDihedralInteractionType >::_FFType private
Definition at line 29 of file BranchingDihedral.h.
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Branching/BranchingDihedral.h
src/Mechanics/ForceField/Branching/BranchingDihedral.cpp