MEDYAN: MTOC Class Reference
MTOC Class Reference
A class to represent the structure of a microtubule organizing center (MTOC)
#include <MTOC.h>
Public Member Functions
MTOC ()
Constructor.
virtual void printSelf ()
Prints information about this node. Useful for debugging.
virtual int getType ()
Return the type of this element as an integer index.
virtual bool apply (Visitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
virtual bool apply (SpeciesVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool isComposite () const override
Returns true.
virtual string getFullName () const override
Returns the full name of this node.
virtual void addChild (unique_ptr< Component > &&child)
Adds a Component child to this Composite node.
virtual void removeChild (Component *child)
Remove *child from this node's children.
virtual size_t numberOfChildren () const override
Returns the number of immediate children of this node.
virtual size_t numberOfSpecies () const override
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t countDescendents () const override
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const override
Returns the number of Species being managed by this node and its descendent nodes.
virtual size_t numberOfReactions () const override
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual size_t countReactions () const override
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
virtual vector< unique_ptr< Component > > & children ()
Returns a reference to the container of Component children of this node.
virtual const vector< unique_ptr< Component > > & children () const
Returns a const reference to the container of Component children of this node.
virtual Component * children (size_t i)
Returns a pointer to the i-th Component child of this node.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
void setBubble (Bubble *b)
Setters.
void addFilament (Filament *f)
Setters.
Bubble * getBubble ()
Getters.
const vector< Filament * > & getFilaments ()
Getters.
virtual void addToSubSystem ()
SubSystem management, inherited from Trackable.
virtual void removeFromSubSystem ()
SubSystem management, inherited from Trackable.
Static Public Member Functions
static const vector< MTOC * > & getMTOCs ()
Get all instances of this class from the SubSystem.
static int numMTOCs ()
Get the number of MTOCs in this system.
Protected Attributes
bool _movable
Object type.
bool _reactable
Object type.
bool _dneighbor
Object type.
bool _neighbor
Object type.
Static Protected Attributes
static SubSystem * _subSystem = 0
A subsystem pointer for every trackable.
Private Attributes
Bubble * _bubble
A bubble that physically represents the MTOC.
vector< Filament * > _filaments
An ordered vector of filaments in the MTOC.
int _ID
Unique identifier.
Static Private Attributes
static Database< MTOC * > _mtocs
Collection of beads in SubSystem.
Detailed Description
A class to represent the structure of a microtubule organizing center (MTOC)
The MTOC class provides a base structure for a mechanical MTOC, which includes a Bubble representing the MTOC and Filaments which are attached to it at the minus end by some sort of potential.
This class only has functions to set and get the constituent Bubble and Filament and is only mechanically relevant for now, but may be extended to have chemical properties in the future.
Definition at line 37 of file MTOC.h.
Constructor & Destructor Documentation
MTOC()
MTOC::MTOC () inline
Constructor.
Definition at line 48 of file MTOC.h.
References setBubble().
Member Function Documentation
addChild()
virtual void Composite::addChild (unique_ptr< Component > && child) inline virtual inherited
Adds a Component child to this Composite node.
Parameters
child - is a unique_ptr<Component>, hence, this node takes the memory ownership of the corresponding child pointer.
Note
the rvalue semantics - the unique_ptr<...> cannot be copied, but only can be moved
Definition at line 81 of file Composite.h.
Referenced by Bead::Bead(), CompartmentGrid::CompartmentGrid(), Cylinder::Cylinder(), setBubble(), and Filament::sever().
addFilament()
void MTOC::addFilament (Filament * f) inline
Setters.
Definition at line 54 of file MTOC.h.
References _bubble, and getBubble().
Referenced by Controller::setupSpecialStructures().
addToSubSystem()
virtual void MTOC::addToSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 65 of file MTOC.h.
Referenced by getFilaments().
apply() [1/3]
bool Composite::apply (Visitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
Reimplemented from Component.
Definition at line 18 of file Composite.cpp.
References Composite::children(), and Visitor::visit().
Referenced by Composite::~Composite().
apply() [2/3]
bool Composite::apply (SpeciesVisitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented from Component.
Definition at line 31 of file Composite.cpp.
References Component::apply_impl(), and Composite::children().
apply() [3/3]
bool Composite::apply (ReactionVisitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented from Component.
Definition at line 43 of file Composite.cpp.
References Component::apply_impl(), and Composite::children().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
children() [1/3]
virtual vector<unique_ptr<Component> >& Composite::children () inline virtual inherited
Returns a reference to the container of Component children of this node.
Definition at line 145 of file Composite.h.
References Composite::_children.
Referenced by Composite::apply(), Composite::countDescendents(), Composite::countReactions(), Composite::countSpecies(), CompartmentGrid::getCompartment(), CompartmentGrid::getCompartments(), Composite::numberOfChildren(), and CompartmentGrid::printSelf().
children() [2/3]
virtual const vector<unique_ptr<Component> >& Composite::children () const inline virtual inherited
Returns a const reference to the container of Component children of this node.
Definition at line 148 of file Composite.h.
References Composite::_children.
children() [3/3]
virtual Component* Composite::children (size_t i) inline virtual inherited
Returns a pointer to the i-th Component child of this node.
Definition at line 151 of file Composite.h.
countDescendents()
virtual size_t Composite::countDescendents () const inline override virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented from Component.
Definition at line 110 of file Composite.h.
References Composite::children(), Composite::numberOfChildren(), and std::sum().
countReactions()
virtual size_t Composite::countReactions () const inline override virtual inherited
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 135 of file Composite.h.
References Composite::children(), Component::isReactionsContainer(), Composite::numberOfReactions(), and std::sum().
countSpecies()
virtual size_t Composite::countSpecies () const inline override virtual inherited
Returns the number of Species being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 120 of file Composite.h.
References Composite::children(), Component::isSpeciesContainer(), Composite::numberOfSpecies(), and std::sum().
Referenced by Filament::getTurnoverTimes(), and Chemistry::print().
getBubble()
Bubble* MTOC::getBubble () inline
Getters.
Definition at line 59 of file MTOC.h.
Referenced by addFilament().
getFilaments()
const vector<Filament*>& MTOC::getFilaments () inline
Getters.
Definition at line 60 of file MTOC.h.
References _filaments, Database< T >::addElement(), and addToSubSystem().
getFullName()
virtual string Composite::getFullName () const inline override virtual inherited
Returns the full name of this node.
Reimplemented from Component.
Reimplemented in Compartment, and CompartmentGrid.
Definition at line 74 of file Composite.h.
getMTOCs()
static const vector<MTOC*>& MTOC::getMTOCs () inline static
Get all instances of this class from the SubSystem.
Definition at line 70 of file MTOC.h.
References Database< T >::getElements().
Referenced by MTOCAttachment< MTOCInteractionType >::computeEnergy(), MTOCAttachment< MTOCInteractionType >::computeForces(), and MTOCAttachment< MTOCInteractionType >::computeForcesAux().
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getType()
virtual int MTOC::getType () inline virtual
Return the type of this element as an integer index.
Implements Component.
Definition at line 81 of file MTOC.h.
isComposite()
virtual bool Composite::isComposite () const inline override virtual inherited
Returns true.
Reimplemented from Component.
Definition at line 71 of file Composite.h.
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
numberOfChildren()
virtual size_t Composite::numberOfChildren () const inline override virtual inherited
Returns the number of immediate children of this node.
Note
Species and reactions and not included in this tally
Reimplemented from Component.
Definition at line 102 of file Composite.h.
References Composite::children().
Referenced by Composite::countDescendents(), and CompartmentGrid::printSelf().
numberOfReactions()
virtual size_t Composite::numberOfReactions () const inline override virtual inherited
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented from Component.
Reimplemented in Compartment.
Definition at line 131 of file Composite.h.
Referenced by Composite::countReactions().
numberOfSpecies()
virtual size_t Composite::numberOfSpecies () const inline override virtual inherited
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.)
Reimplemented from Component.
Reimplemented in Compartment.
Definition at line 106 of file Composite.h.
Referenced by Composite::countSpecies().
numMTOCs()
static int MTOC::numMTOCs () inline static
Get the number of MTOCs in this system.
Definition at line 74 of file MTOC.h.
References Database< T >::countElements(), and printSelf().
printSelf()
void MTOC::printSelf () virtual
Prints information about this node. Useful for debugging.
Implements Component.
Definition at line 29 of file MTOC.cpp.
References _bubble, _ID, _mtocs, and Bubble::printSelf().
Referenced by numMTOCs().
removeChild()
virtual void Composite::removeChild (Component * child) inline virtual inherited
Remove *child from this node's children.
The child's destructor will be called and the memory will be freed.
Definition at line 89 of file Composite.h.
Referenced by Filament::retractMinusEnd(), and Filament::retractPlusEnd().
removeFromSubSystem()
virtual void MTOC::removeFromSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 66 of file MTOC.h.
References Database< T >::removeElement().
setBubble()
void MTOC::setBubble (Bubble * b)
Setters.
Definition at line 21 of file MTOC.cpp.
References _bubble, Composite::addChild(), and Bubble::setAsMTOC().
Referenced by MTOC(), and Controller::setupSpecialStructures().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
Member Data Documentation
_bubble
Bubble* MTOC::_bubble private
A bubble that physically represents the MTOC.
Definition at line 40 of file MTOC.h.
Referenced by addFilament(), printSelf(), and setBubble().
_dneighbor
bool Trackable::_dneighbor protected inherited
Object type.
Definition at line 54 of file Trackable.h.
_filaments
vector<Filament*> MTOC::_filaments private
An ordered vector of filaments in the MTOC.
Definition at line 41 of file MTOC.h.
Referenced by getFilaments().
_ID
int MTOC::_ID private
Unique identifier.
Definition at line 43 of file MTOC.h.
Referenced by printSelf().
_movable
bool Trackable::_movable protected inherited
Object type.
Definition at line 52 of file Trackable.h.
_mtocs
Database< MTOC * > MTOC::_mtocs static private
Collection of beads in SubSystem.
Definition at line 45 of file MTOC.h.
Referenced by printSelf().
_neighbor
bool Trackable::_neighbor protected inherited
Object type.
Definition at line 55 of file Trackable.h.
_reactable
bool Trackable::_reactable protected inherited
Object type.
Definition at line 53 of file Trackable.h.
_subSystem
SubSystem * Trackable::_subSystem = 0 static protected inherited
A subsystem pointer for every trackable.
Definition at line 46 of file Trackable.h.
Referenced by Controller::Controller(), and BranchingPoint::~BranchingPoint().
The documentation for this class was generated from the following files:
src/Structure/Special/MTOC.h
src/Structure/Special/MTOC.cpp