M3Sym: SpeciesVisitor Class Reference
SpeciesVisitor Class Reference abstract
The Visitor pattern allows a functor to visit each node of the Composite pattern.
#include <Visitor.h>
Public Member Functions
bool visit (Species *s)
When this Visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(s), for each of the Species *s of that node.
virtual ~SpeciesVisitor ()
Virtual destructor.
Protected Member Functions
virtual bool visitImpl (Species *s)=0
When this Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
virtual bool predImpl (Species *s)
Return true if the Species *s satisfies the desired predicate.
Detailed Description
The Visitor pattern allows a functor to visit each node of the Composite pattern.
Concrete classes derived from Visitor must implement the visit(Component *c) method.
Definition at line 101 of file Visitor.h.
Constructor & Destructor Documentation
virtual SpeciesVisitor::~SpeciesVisitor () inline virtual
Virtual destructor.
Definition at line 114 of file Visitor.h.
Member Function Documentation
virtual bool SpeciesVisitor::predImpl (Species * s) inline protected virtual
Return true if the Species *s satisfies the desired predicate.
Reimplemented in SpeciesVisitorLambda.
Definition at line 123 of file Visitor.h.
Referenced by visit().
bool SpeciesVisitor::visit (Species * s) inline
When this Visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(s), for each of the Species *s of that node.
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Definition at line 108 of file Visitor.h.
References predImpl(), and visitImpl().
Referenced by Compartment::apply_impl().
virtual bool SpeciesVisitor::visitImpl (Species * s) protected pure virtual
When this Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Implemented in SpeciesVisitorLambda.
Referenced by visit().
The documentation for this class was generated from the following file:
M3SYM/Visitor.h