MEDYAN: SpeciesNamesDB Class Reference
SpeciesNamesDB Class Reference
Used to associate unique integers with character based names of Species.
#include <Species.h>
Static Public Member Functions
static string intToString (unsigned int i)
Given an integer "i", returns the string associated with that integer.
static int stringToInt (string name)
Given a string "name", returns the unique integer associated with that string.
static string genUniqueFilName (string name)
Generate a unique name based on a seed name (just adds integer value to end of string with a -)
static string removeUniqueFilName (string name)
Remove the unique integer value identifier with this filament species name.
static string genBindingName (string binding, string bound)
Generate a single or pair binding name based on two strings: one string being the binding species and the other being the bound species on the filament.
static void clear ()
Clear the contents of the database.
Static Private Attributes
static unordered_map< string, int > _map_string_int
static vector< string > _vec_int_string
static unsigned long _num = 0
used to generate unique names
Detailed Description
Used to associate unique integers with character based names of Species.
Often Species of the same type, let's say "Arp2/3" can be found in different forms, for example in cytosol vs bound to a filament. The corresponding specific Species will be distinct, however, they will share the same name, as returned by Species::getName(). This, in turn, helps to match "Arp2/3" bound to filaments with diffusing "Arp2/3". SpeciesNamesDB associates a unique integer with Species of the same type (e.g. "Arp2/3", regardless whether it is bound or not), and provides conversion functions fron integer to string (SpeciesNamesDB::intToString(int i)) and vice versa (SpeciesNamesDB::stringToInt (string name)).
SpeciesNamesDB has a function to generate a unique filament name given a string seed. This is particularly useful for when a filament species needs a unique name, say with the seed "Actin". This unique filament name can be added or removed to match the corresponding bulk or diffusing species in the system.
SpeciesNamesDB also has a function to generate a SpeciesSingleBinding or SpeciesPairBinding name for a Compartment by concatenating two species names, a SpeciesDiffusing/SpeciesBulk with a SpeciesBound, with a "-". This name can then be broken up into its counterparts when needed.
Definition at line 58 of file Species.h.
Member Function Documentation
clear()
static void SpeciesNamesDB::clear () inline static
Clear the contents of the database.
Definition at line 143 of file Species.h.
genBindingName()
static string SpeciesNamesDB::genBindingName (string binding, string bound) inline static
Generate a single or pair binding name based on two strings: one string being the binding species and the other being the bound species on the filament.
Definition at line 132 of file Species.h.
Referenced by ChemManager::genFilBindingReactions(), and ChemManager::genSpecies().
genUniqueFilName()
static string SpeciesNamesDB::genUniqueFilName (string name) inline static
Generate a unique name based on a seed name (just adds integer value to end of string with a -)
Note
- used only for filament species.
Definition at line 99 of file Species.h.
Referenced by ChemManager::initCMonomer().
intToString()
static string SpeciesNamesDB::intToString (unsigned int i) inline static
Given an integer "i", returns the string associated with that integer.
Throws an out of range exception.
Definition at line 69 of file Species.h.
Referenced by Species::getName().
removeUniqueFilName()
static string SpeciesNamesDB::removeUniqueFilName (string name) inline static
Remove the unique integer value identifier with this filament species name.
Returns
The name without the integer ending.
Definition at line 115 of file Species.h.
Referenced by BranchingPoint::countSpecies(), Linker::countSpecies(), MotorGhost::countSpecies(), Filament::countSpecies(), and BranchingPoint::~BranchingPoint().
stringToInt()
static int SpeciesNamesDB::stringToInt (string name) inline static
Given a string "name", returns the unique integer associated with that string.
If the string does not exist yet, it is created.
Definition at line 82 of file Species.h.
Referenced by ChemManager::genFilReactionTemplates(), Compartment::getDiffusionRate(), Compartment::setDiffusionRate(), and Species::Species().
Member Data Documentation
_map_string_int
unordered_map< string, int > SpeciesNamesDB::_map_string_int static private
Definition at line 61 of file Species.h.
Referenced by Species::passivateReactantReactions().
_num
unsigned long SpeciesNamesDB::_num = 0 static private
used to generate unique names
Definition at line 64 of file Species.h.
Referenced by Species::passivateReactantReactions().
_vec_int_string
vector< string > SpeciesNamesDB::_vec_int_string static private
Definition at line 62 of file Species.h.
Referenced by Species::passivateReactantReactions().
The documentation for this class was generated from the following files:
src/Chemistry/Species.h
src/Chemistry/Species.cpp