MEDYAN: MotorGhostStretchingHarmonic Class Reference
MotorGhostStretchingHarmonic Class Reference
A harmonic potential used by the MotorGhostStretching template.
#include <MotorGhostStretchingHarmonic.h>
Public Member Functions
double energy (Bead *, Bead *, Bead *, Bead *, double position1, double position2, double kStretch, double eqLength)
double energy (Bead *, Bead *, Bead *, Bead *, double position1, double position2, double kStretch, double eqLength, double d)
double forces (Bead *, Bead *, Bead *, Bead *, double position1, double position2, double kStretch, double eqLength)
double forcesAux (Bead *, Bead *, Bead *, Bead *, double position1, double position2, double kStretch, double eqLength)
Detailed Description
A harmonic potential used by the MotorGhostStretching template.
Definition at line 23 of file MotorGhostStretchingHarmonic.h.
Member Function Documentation
energy() [1/2]
double MotorGhostStretchingHarmonic::energy (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double position1, double position2, double kStretch, double eqLength)
Definition at line 22 of file MotorGhostStretchingHarmonic.cpp.
References Bead::coordinate, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
energy() [2/2]
double MotorGhostStretchingHarmonic::energy (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double position1, double position2, double kStretch, double eqLength, double d)
Definition at line 33 of file MotorGhostStretchingHarmonic.cpp.
References Bead::coordinate, Bead::force, mathfunc::midPointCoordinateStretched(), and mathfunc::twoPointDistance().
forces()
double MotorGhostStretchingHarmonic::forces (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double position1, double position2, double kStretch, double eqLength)
Definition at line 46 of file MotorGhostStretchingHarmonic.cpp.
References Bead::coordinate, Bead::force, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
forcesAux()
double MotorGhostStretchingHarmonic::forcesAux (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double position1, double position2, double kStretch, double eqLength)
Definition at line 81 of file MotorGhostStretchingHarmonic.cpp.
References Bead::coordinate, Bead::forceAux, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/MotorGhost/MotorGhostStretchingHarmonic.h
src/Mechanics/ForceField/MotorGhost/MotorGhostStretchingHarmonic.cpp