MEDYAN: CMotorGhost Class Reference
CMotorGhost Class Reference
A class to represent the chemical component of a MotorGhost.
#include <CMotorGhost.h>
Public Member Functions
CMotorGhost (short motorType, Compartment *c, CCylinder *cc1, CCylinder *cc2, int position1, int position2)
Constructor.
~CMotorGhost ()
Destructor, removes off reaction from system.
CMotorGhost (const CMotorGhost &rhs, Compartment *c)
Copy constructor, standard.
CMotorGhost & operator= (CMotorGhost &rhs)=delete
Assignment is not allowed.
virtual CMotorGhost * clone (Compartment *c)
Clone, calls copy constructor.
void setMotorGhost (MotorGhost *MotorGhost)
Set parent.
MotorGhost * getMotorGhost ()
Get parent.
virtual void createOffReaction (ReactionBase *onRxn, SubSystem *ps)
Create the off reaction for this MotorGhost.
void moveMotorHead (CCylinder *cc, short oldPosition, short newPosition, short motorType, short boundType, SubSystem *ps)
Move the motor head to a new position chemically.
void moveMotorHead (CCylinder *oldCC, CCylinder *newCC, short oldPosition, short newPosition, short motorType, short boundType, SubSystem *ps)
Move the motor head to a new CCylinder chemically.
void setFirstSpecies (SpeciesBound *species)
Set first species.
SpeciesBound * getFirstSpecies ()
Get first species.
void setSecondSpecies (SpeciesBound *species)
Set second species.
SpeciesBound * getSecondSpecies ()
Get second species.
void setFirstCCylinder (CCylinder *cc)
Set first CCylinder.
CCylinder * getFirstCCylinder ()
Get first CCylinder.
void setSecondCCylinder (CCylinder *cc)
Set second CCylinder.
CCylinder * getSecondCCylinder ()
Get first CCylinder.
Compartment * getCompartment ()
Get compartment that this CBound is in.
void setRates (float onRate, float offRate)
Set all rates at once.
short getFirstPosition ()
Position getters.
short getSecondPosition ()
Position getters.
void setOnRate (float rate)
On rate management.
double getOnRate ()
On rate management.
void setOffRate (float rate)
Off rate management.
double getOffRate ()
Off rate management.
void setOffReaction (ReactionBase *offRxn)
Off reaction management.
ReactionBase * getOffReaction ()
Off reaction management.
Protected Attributes
short _filamentType
The filament type that this CBound binds to.
SpeciesBound * _firstSpecies = nullptr
Corresponding first species on Filament.
SpeciesBound * _secondSpecies = nullptr
Corresponding second species on Filament.
Compartment * _compartment
Compartment this CBound is in.
CCylinder * _cc1 = nullptr
Pointer to first CCylinder.
CCylinder * _cc2 = nullptr
Pointer to second CCylinder.
short _position1
position of first head
short _position2 = 0
position of second head
ReactionBase * _offRxn
The off reaction for this bound object.
float _onRate = 0.0
Reaction rates.
float _offRate = 0.0
Reaction rates.
Private Attributes
MotorGhost * _pMotorGhost
Pointer to parent.
Detailed Description
A class to represent the chemical component of a MotorGhost.
The CMotorGhost class contains chemical info of the parent MotorGhost.
Extending CBound, this class tracks its corresponding Species and unbinding Reaction.
Definition at line 36 of file CMotorGhost.h.
Constructor & Destructor Documentation
CMotorGhost() [1/2]
CMotorGhost::CMotorGhost (short motorType, Compartment * c, CCylinder * cc1, CCylinder * cc2, int position1, int position2)
Constructor.
Parameters
pos1 - monomer index on first cylinder
pos2 - monomer index on second cylinder
Definition at line 19 of file CMotorGhost.cpp.
References CBound::_cc1, CBound::_cc2, CBound::_filamentType, CBound::_position1, CBound::_position2, areEqual(), SysParams::Chemistry(), Species::down(), CCylinder::getCMonomer(), Species::getN(), CBound::setFirstSpecies(), CBound::setSecondSpecies(), CMonomer::speciesBound(), CMonomer::speciesMotor(), and Species::up().
Referenced by clone().
~CMotorGhost()
CMotorGhost::~CMotorGhost ()
Destructor, removes off reaction from system.
Definition at line 46 of file CMotorGhost.cpp.
References CBound::_cc1, CBound::_cc2, CBound::_offRxn, and CCylinder::removeCrossCylinderReaction().
CMotorGhost() [2/2]
CMotorGhost::CMotorGhost (const CMotorGhost & rhs, Compartment * c) inline
Copy constructor, standard.
Definition at line 52 of file CMotorGhost.h.
References CBound::_firstSpecies, CBound::_offRate, CBound::_offRxn, CBound::_onRate, CBound::_secondSpecies, operator=(), CBound::setFirstSpecies(), CBound::setOffRate(), CBound::setOffReaction(), CBound::setOnRate(), and CBound::setSecondSpecies().
Member Function Documentation
clone()
virtual CMotorGhost* CMotorGhost::clone (Compartment * c) inline virtual
Clone, calls copy constructor.
Definition at line 74 of file CMotorGhost.h.
References CBound::_offRxn, and CMotorGhost().
createOffReaction()
void CMotorGhost::createOffReaction (ReactionBase * onRxn, SubSystem * ps) virtual
Create the off reaction for this MotorGhost.
Implements CBound.
Definition at line 53 of file CMotorGhost.cpp.
References CBound::_cc1, CBound::_cc2, CBound::_filamentType, CBound::_firstSpecies, CBound::_offRate, _pMotorGhost, CBound::_position1, CBound::_position2, CBound::_secondSpecies, CCylinder::addCrossCylinderReaction(), SysParams::Chemistry(), CCylinder::getCMonomer(), MOTORUNBINDING, ReactionBase::rspecies(), CBound::setOffReaction(), ReactionBase::setReactionType(), CMonomer::speciesBound(), and SPECIESM_BINDING_INDEX.
Referenced by getMotorGhost().
getCompartment()
Compartment* CBound::getCompartment () inline inherited
Get compartment that this CBound is in.
Definition at line 118 of file CBound.h.
References CBound::_compartment, and CBound::setOnRate().
getFirstCCylinder()
CCylinder* CBound::getFirstCCylinder () inline inherited
Get first CCylinder.
Definition at line 110 of file CBound.h.
References CBound::_cc1.
getFirstPosition()
short CBound::getFirstPosition () inline inherited
Position getters.
Definition at line 103 of file CBound.h.
Referenced by CBound::getSecondSpecies().
getFirstSpecies()
SpeciesBound* CBound::getFirstSpecies () inline inherited
Get first species.
Definition at line 88 of file CBound.h.
References CBound::_firstSpecies.
Referenced by CMonomer::CMonomer(), and moveMotorHead().
getMotorGhost()
MotorGhost* CMotorGhost::getMotorGhost () inline
Get parent.
Definition at line 82 of file CMotorGhost.h.
References _pMotorGhost, createOffReaction(), and moveMotorHead().
getOffRate()
double CBound::getOffRate () inline inherited
Off rate management.
Definition at line 129 of file CBound.h.
References CBound::_offRate.
getOffReaction()
ReactionBase* CBound::getOffReaction () inline inherited
Off reaction management.
Definition at line 146 of file CBound.h.
References CBound::_offRxn.
getOnRate()
double CBound::getOnRate () inline inherited
On rate management.
Definition at line 123 of file CBound.h.
References CBound::_onRate, and CBound::setOffRate().
getSecondCCylinder()
CCylinder* CBound::getSecondCCylinder () inline inherited
Get first CCylinder.
Definition at line 115 of file CBound.h.
References CBound::_cc2.
getSecondPosition()
short CBound::getSecondPosition () inline inherited
Position getters.
Definition at line 104 of file CBound.h.
References CBound::_position2.
getSecondSpecies()
SpeciesBound* CBound::getSecondSpecies () inline inherited
Get second species.
Definition at line 99 of file CBound.h.
References CBound::_position1, CBound::_secondSpecies, and CBound::getFirstPosition().
moveMotorHead() [1/2]
void CMotorGhost::moveMotorHead (CCylinder * cc, short oldPosition, short newPosition, short motorType, short boundType, SubSystem * ps)
Move the motor head to a new position chemically.
Definition at line 84 of file CMotorGhost.cpp.
References CBound::_cc1, CBound::_cc2, CBound::_filamentType, CBound::_firstSpecies, CBound::_offRate, CBound::_offRxn, _pMotorGhost, CBound::_position1, CBound::_position2, CBound::_secondSpecies, CCylinder::addCrossCylinderReaction(), SysParams::Chemistry(), CCylinder::getCMonomer(), CBound::getFirstSpecies(), RSpecies::getSpecies(), MOTORUNBINDING, CCylinder::removeCrossCylinderReaction(), ReactionBase::rspecies(), CBound::setFirstSpecies(), CBound::setOffReaction(), ReactionBase::setReactionType(), CBound::setSecondSpecies(), CMonomer::speciesBound(), SPECIESM_UNBINDING_INDEX, and CMonomer::speciesMotor().
Referenced by getMotorGhost().
moveMotorHead() [2/2]
void CMotorGhost::moveMotorHead (CCylinder * oldCC, CCylinder * newCC, short oldPosition, short newPosition, short motorType, short boundType, SubSystem * ps)
Move the motor head to a new CCylinder chemically.
Definition at line 147 of file CMotorGhost.cpp.
References CBound::_cc1, CBound::_cc2, CBound::_filamentType, CBound::_firstSpecies, CBound::_offRate, CBound::_offRxn, _pMotorGhost, CBound::_position1, CBound::_position2, CBound::_secondSpecies, CCylinder::addCrossCylinderReaction(), SysParams::Chemistry(), CCylinder::getCMonomer(), CBound::getFirstSpecies(), RSpecies::getSpecies(), MOTORUNBINDING, CCylinder::removeCrossCylinderReaction(), ReactionBase::rspecies(), CBound::setFirstCCylinder(), CBound::setFirstSpecies(), CBound::setOffReaction(), ReactionBase::setReactionType(), CBound::setSecondCCylinder(), CBound::setSecondSpecies(), CMonomer::speciesBound(), SPECIESM_UNBINDING_INDEX, and CMonomer::speciesMotor().
operator=()
CMotorGhost& CMotorGhost::operator= (CMotorGhost & rhs) delete
Assignment is not allowed.
Referenced by CMotorGhost().
setFirstCCylinder()
void CBound::setFirstCCylinder (CCylinder * cc) inline inherited
Set first CCylinder.
Definition at line 108 of file CBound.h.
Referenced by moveMotorHead().
setFirstSpecies()
void CBound::setFirstSpecies (SpeciesBound * species) inline inherited
Set first species.
remove from old first species
Definition at line 80 of file CBound.h.
References SpeciesBound::removeCBound(), and SpeciesBound::setCBound().
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMonomer::CMonomer(), CMotorGhost(), and moveMotorHead().
setMotorGhost()
void CMotorGhost::setMotorGhost (MotorGhost * MotorGhost) inline
Set parent.
Definition at line 80 of file CMotorGhost.h.
setOffRate()
void CBound::setOffRate (float rate) inline inherited
Off rate management.
Definition at line 128 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost(), and CBound::getOnRate().
setOffReaction()
void CBound::setOffReaction (ReactionBase * offRxn) inline inherited
Off reaction management.
Definition at line 142 of file CBound.h.
References ReactionBase::setCBound().
Referenced by CBranchingPoint::CBranchingPoint(), CCylinder::CCylinder(), CLinker::CLinker(), CMotorGhost(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), createOffReaction(), and moveMotorHead().
setOnRate()
void CBound::setOnRate (float rate) inline inherited
On rate management.
Definition at line 122 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost(), and CBound::getCompartment().
setRates()
void CBound::setRates (float onRate, float offRate) inline inherited
Set all rates at once.
Definition at line 133 of file CBound.h.
References CBound::createOffReaction().
setSecondCCylinder()
void CBound::setSecondCCylinder (CCylinder * cc) inline inherited
Set second CCylinder.
Definition at line 113 of file CBound.h.
Referenced by moveMotorHead().
setSecondSpecies()
void CBound::setSecondSpecies (SpeciesBound * species) inline inherited
Set second species.
remove from old second species
Definition at line 91 of file CBound.h.
References SpeciesBound::removeCBound(), and SpeciesBound::setCBound().
Referenced by CLinker::CLinker(), CMonomer::CMonomer(), CMotorGhost(), and moveMotorHead().
Member Data Documentation
_cc1
CCylinder* CBound::_cc1 = nullptr protected inherited
Pointer to first CCylinder.
Definition at line 47 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), createOffReaction(), CBound::getFirstCCylinder(), moveMotorHead(), CBranchingPoint::~CBranchingPoint(), CLinker::~CLinker(), and ~CMotorGhost().
_cc2
CCylinder* CBound::_cc2 = nullptr protected inherited
Pointer to second CCylinder.
Definition at line 48 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost(), CLinker::createOffReaction(), createOffReaction(), CBound::getSecondCCylinder(), moveMotorHead(), CLinker::~CLinker(), and ~CMotorGhost().
_compartment
Compartment* CBound::_compartment protected inherited
Compartment this CBound is in.
Definition at line 45 of file CBound.h.
Referenced by CBound::getCompartment().
_filamentType
short CBound::_filamentType protected inherited
The filament type that this CBound binds to.
Definition at line 40 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost(), CLinker::createOffReaction(), CBranchingPoint::createOffReaction(), createOffReaction(), and moveMotorHead().
_firstSpecies
SpeciesBound* CBound::_firstSpecies = nullptr protected inherited
Corresponding first species on Filament.
Definition at line 42 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost(), CLinker::createOffReaction(), createOffReaction(), CBound::getFirstSpecies(), and moveMotorHead().
_offRate
float CBound::_offRate = 0.0 protected inherited
Reaction rates.
Definition at line 56 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost(), CLinker::createOffReaction(), CBranchingPoint::createOffReaction(), createOffReaction(), CBound::getOffRate(), and moveMotorHead().
_offRxn
ReactionBase* CBound::_offRxn protected inherited
The off reaction for this bound object.
Definition at line 59 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CBranchingPoint::clone(), CLinker::clone(), clone(), CMotorGhost(), CBound::getOffReaction(), moveMotorHead(), CBranchingPoint::~CBranchingPoint(), CLinker::~CLinker(), and ~CMotorGhost().
_onRate
float CBound::_onRate = 0.0 protected inherited
Reaction rates.
Definition at line 55 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost(), and CBound::getOnRate().
_pMotorGhost
MotorGhost* CMotorGhost::_pMotorGhost private
Pointer to parent.
Definition at line 39 of file CMotorGhost.h.
Referenced by createOffReaction(), getMotorGhost(), and moveMotorHead().
_position1
short CBound::_position1 protected inherited
position of first head
Definition at line 50 of file CBound.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost(), CLinker::createOffReaction(), CBranchingPoint::createOffReaction(), createOffReaction(), CBound::getSecondSpecies(), and moveMotorHead().
_position2
short CBound::_position2 = 0 protected inherited
position of second head
Definition at line 51 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost(), CLinker::createOffReaction(), createOffReaction(), CBound::getSecondPosition(), and moveMotorHead().
_secondSpecies
SpeciesBound* CBound::_secondSpecies = nullptr protected inherited
Corresponding second species on Filament.
Definition at line 43 of file CBound.h.
Referenced by CLinker::CLinker(), CMotorGhost(), CLinker::createOffReaction(), createOffReaction(), CBound::getSecondSpecies(), and moveMotorHead().
The documentation for this class was generated from the following files:
src/Structure/CMotorGhost.h
src/Structure/CMotorGhost.cpp