MEDYAN: BrownianRatchet Class Reference
BrownianRatchet Class Reference
A brownian ratchet implementation of the FilamentRateChanger.
#include <RateChangerImpl.h>
Public Member Functions
BrownianRatchet (double charLength)
virtual float changeRate (float bareRate, double force)
Change the reaction rate based on a bare rate and given force.
Private Attributes
double _x
The characteristic length for this function.
const double _max_f = 100
100pN ceiling
Detailed Description
A brownian ratchet implementation of the FilamentRateChanger.
Used for filament polymerization when under load force.
Note
- This function updates polymerization rates based on the Elastic Brownian Ratchet Model (by Peskin et al, Biophys J 1993):
            k = k_0 * exp(-f * x / kT)
- We note that we have implemented a load force ceiling of 100pN such that recalculated reaction rates are not excessively small. This would produce problems in the chemical simulation algorithm. A 100pN load force ensures that the polymerization rate produced will be small enough such that polymerization events are VERY rare (factor = 1E-29).
Definition at line 37 of file RateChangerImpl.h.
Constructor & Destructor Documentation
BrownianRatchet()
BrownianRatchet::BrownianRatchet (double charLength) inline
Definition at line 44 of file RateChangerImpl.h.
References changeRate().
Member Function Documentation
changeRate()
float BrownianRatchet::changeRate (float bareRate, double force) virtual
Change the reaction rate based on a bare rate and given force.
Implements FilamentRateChanger.
Definition at line 21 of file RateChangerImpl.cpp.
References _x, and kT.
Referenced by BrownianRatchet(), LinkerCatchSlip::LinkerCatchSlip(), LinkerSlip::LinkerSlip(), MotorCatch::MotorCatch(), and MotorStall::numBoundHeads().
Member Data Documentation
_max_f
const double BrownianRatchet::_max_f = 100 private
100pN ceiling
Definition at line 41 of file RateChangerImpl.h.
_x
double BrownianRatchet::_x private
The characteristic length for this function.
Definition at line 40 of file RateChangerImpl.h.
Referenced by changeRate(), and LinkerSlip::changeRate().
The documentation for this class was generated from the following files:
src/RateChangerImpl.h
src/RateChangerImpl.cpp