MEDYAN: CompartmentGrid Class Reference
CompartmentGrid Class Reference
A simple n-dimensional grid of Compartment objects.
#include <CompartmentGrid.h>
Public Member Functions
CompartmentGrid (int numCompartments)
Constructor, creates a number of Compartment instances.
vector< Compartment * > getCompartments ()
Get compartments that this grid holds.
Compartment * getCompartment (int index)
Get a compartment at certain index.
void setAllAsActive ()
Set all compartments as active. Used at initialization.
virtual string getFullName () const
Get name of this compartment grid.
Compartment & getProtoCompartment ()
Get the protocompartment from this grid, in order to configure and then initialize.
const Compartment & getProtoCompartment () const
virtual void addChemSimReactions (ChemSim *chem)
Add reactions to all compartments in the grid.
virtual void printSelf ()
Print properties of this grid.
template<typename ... Args>
SpeciesBulk * addSpeciesBulk (Args &&...args)
Add a bulk species to this grid.
void removeSpeciesBulk (const string &name)
Remove bulk species.
SpeciesBulk * findSpeciesBulkByName (const string &name)
Bulk species finder functions.
SpeciesBulk * findSpeciesBulkByMolecule (int molecule)
template<unsigned short M, unsigned short N, typename ... Args>
ReactionBase * addBulkReaction (Args &&...args)
Add a bulk reaction to this compartment grid.
template<template< unsigned short M, unsigned short N > class RXN, unsigned short M, unsigned short N>
ReactionBase * addBulk (initializer_list< Species *> species, float rate)
Add an bulk reaction to this compartment grid.
ReactionBase * addBulkReactionUnique (unique_ptr< ReactionBase > &&reaction)
Add a unique bulk reaction pointer to this compartment.
virtual void removeBulkReactions (Species *s)
Remove all bulk reactions that have a given species.
virtual void removeBulkReaction (ReactionBase *r)
Remove a bulk reaction.
species_copy_t countDiffusingSpecies (const string &name)
Count the number of diffusing species with a given name.
species_copy_t countBulkSpecies (const string &name)
Count the number of bulk species with a given name.
virtual int getType ()
GetType implementation just returns zero (no CompartmentGrid types yet)
vector< tuple< int, int, vector< double >, vector< double > > > getDiffusingMotors ()
This function gets all diffusing motor species and creates a virtual position within the simulation volume (dependent on the compartment).
virtual bool apply (Visitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
virtual bool apply (SpeciesVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool isComposite () const override
Returns true.
virtual void addChild (unique_ptr< Component > &&child)
Adds a Component child to this Composite node.
virtual void removeChild (Component *child)
Remove *child from this node's children.
virtual size_t numberOfChildren () const override
Returns the number of immediate children of this node.
virtual size_t numberOfSpecies () const override
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t countDescendents () const override
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const override
Returns the number of Species being managed by this node and its descendent nodes.
virtual size_t numberOfReactions () const override
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual size_t countReactions () const override
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
virtual vector< unique_ptr< Component > > & children ()
Returns a reference to the container of Component children of this node.
virtual const vector< unique_ptr< Component > > & children () const
Returns a const reference to the container of Component children of this node.
virtual Component * children (size_t i)
Returns a pointer to the i-th Component child of this node.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
Private Attributes
Compartment _prototype_compartment
Prototype compartment, to be configured before initialization.
SpeciesPtrContainerVector _bulkSpecies
Bulk species in this grid.
ReactionPtrContainerVector _bulkReactions
Bulk reactions in this grid.
Detailed Description
A simple n-dimensional grid of Compartment objects.
The CompartmentGrid class is a singleton grid of Compartment objects, each of them seperately holding internal and diffusion reactions, species information, as well as spatial information. This class is n-dimensional, and the dimension is specified at runtime. All compartments within CompartmentGrid are indexed by the GController, and this class is responsible for assignment of compartment neighbors upon initialization. All initialization of the CompartmentGrid should be done through GController.initializeGrid().
The _prototype_compartment is used such that all reactions and species can be added to the prototype, and this configuration can be copied to all compartments in the grid.
Definition at line 39 of file CompartmentGrid.h.
Constructor & Destructor Documentation
CompartmentGrid()
CompartmentGrid::CompartmentGrid (int numCompartments) inline
Constructor, creates a number of Compartment instances.
Definition at line 49 of file CompartmentGrid.h.
References Composite::addChild().
Member Function Documentation
addBulk()
template<template< unsigned short M, unsigned short N > class RXN, unsigned short M, unsigned short N> ReactionBase* CompartmentGrid::addBulk (initializer_list< Species *> species, float rate) inline
Add an bulk reaction to this compartment grid.
Parameters
species,rate - specifying the species and rate that should be assigned
Definition at line 127 of file CompartmentGrid.h.
References ReactionPtrContainerVector::add(), and ReactionBase::setParent().
addBulkReaction()
template<unsigned short M, unsigned short N, typename ... Args> ReactionBase* CompartmentGrid::addBulkReaction (Args &&... args) inline
Add a bulk reaction to this compartment grid.
Definition at line 117 of file CompartmentGrid.h.
References ReactionPtrContainerVector::addReaction(), and ReactionBase::setParent().
addBulkReactionUnique()
ReactionBase* CompartmentGrid::addBulkReactionUnique (unique_ptr< ReactionBase > && reaction) inline
Add a unique bulk reaction pointer to this compartment.
Definition at line 134 of file CompartmentGrid.h.
References ReactionPtrContainerVector::addReactionUnique(), and ReactionBase::setParent().
addChemSimReactions()
void CompartmentGrid::addChemSimReactions (ChemSim * chem) virtual
Add reactions to all compartments in the grid.
Parameters
- chem, a ChemSim object that controls the reaction algorithm
Definition at line 23 of file CompartmentGrid.cpp.
References ChemSim::addReaction().
Referenced by getProtoCompartment().
addChild()
virtual void Composite::addChild (unique_ptr< Component > && child) inline virtual inherited
Adds a Component child to this Composite node.
Parameters
child - is a unique_ptr<Component>, hence, this node takes the memory ownership of the corresponding child pointer.
Note
the rvalue semantics - the unique_ptr<...> cannot be copied, but only can be moved
Definition at line 81 of file Composite.h.
Referenced by Bead::Bead(), CompartmentGrid(), Cylinder::Cylinder(), MTOC::setBubble(), and Filament::sever().
addSpeciesBulk()
template<typename ... Args> SpeciesBulk* CompartmentGrid::addSpeciesBulk (Args &&... args) inline
Add a bulk species to this grid.
Definition at line 99 of file CompartmentGrid.h.
References SpeciesPtrContainerVector::addSpecies(), SpeciesPtrContainerVector::findSpeciesByIndex(), and SpeciesPtrContainerVector::size().
apply() [1/3]
bool Composite::apply (Visitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
Reimplemented from Component.
Definition at line 18 of file Composite.cpp.
References Composite::children(), and Visitor::visit().
Referenced by Composite::~Composite().
apply() [2/3]
bool Composite::apply (SpeciesVisitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented from Component.
Definition at line 31 of file Composite.cpp.
References Component::apply_impl(), and Composite::children().
apply() [3/3]
bool Composite::apply (ReactionVisitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented from Component.
Definition at line 43 of file Composite.cpp.
References Component::apply_impl(), and Composite::children().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
children() [1/3]
virtual vector<unique_ptr<Component> >& Composite::children () inline virtual inherited
Returns a reference to the container of Component children of this node.
Definition at line 145 of file Composite.h.
References Composite::_children.
Referenced by Composite::apply(), Composite::countDescendents(), Composite::countReactions(), Composite::countSpecies(), getCompartment(), getCompartments(), Composite::numberOfChildren(), and printSelf().
children() [2/3]
virtual const vector<unique_ptr<Component> >& Composite::children () const inline virtual inherited
Returns a const reference to the container of Component children of this node.
Definition at line 148 of file Composite.h.
References Composite::_children.
children() [3/3]
virtual Component* Composite::children (size_t i) inline virtual inherited
Returns a pointer to the i-th Component child of this node.
Definition at line 151 of file Composite.h.
countBulkSpecies()
species_copy_t CompartmentGrid::countBulkSpecies (const string & name)
Count the number of bulk species with a given name.
Definition at line 48 of file CompartmentGrid.cpp.
Referenced by removeBulkReaction().
countDescendents()
virtual size_t Composite::countDescendents () const inline override virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented from Component.
Definition at line 110 of file Composite.h.
References Composite::children(), Composite::numberOfChildren(), and std::sum().
countDiffusingSpecies()
species_copy_t CompartmentGrid::countDiffusingSpecies (const string & name)
Count the number of diffusing species with a given name.
Definition at line 33 of file CompartmentGrid.cpp.
Referenced by removeBulkReaction(), and Restart::settorestartphase().
countReactions()
virtual size_t Composite::countReactions () const inline override virtual inherited
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 135 of file Composite.h.
References Composite::children(), Component::isReactionsContainer(), Composite::numberOfReactions(), and std::sum().
countSpecies()
virtual size_t Composite::countSpecies () const inline override virtual inherited
Returns the number of Species being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 120 of file Composite.h.
References Composite::children(), Component::isSpeciesContainer(), Composite::numberOfSpecies(), and std::sum().
Referenced by Filament::getTurnoverTimes(), and Chemistry::print().
findSpeciesBulkByMolecule()
SpeciesBulk* CompartmentGrid::findSpeciesBulkByMolecule (int molecule) inline
Definition at line 111 of file CompartmentGrid.h.
References SpeciesPtrContainerVector::findSpeciesByMolecule().
findSpeciesBulkByName()
SpeciesBulk* CompartmentGrid::findSpeciesBulkByName (const string & name) inline
Bulk species finder functions.
Definition at line 108 of file CompartmentGrid.h.
References SpeciesPtrContainerVector::findSpeciesByName().
getCompartment()
Compartment* CompartmentGrid::getCompartment (int index) inline
Get a compartment at certain index.
Definition at line 68 of file CompartmentGrid.h.
References Composite::children().
getCompartments()
vector<Compartment*> CompartmentGrid::getCompartments () inline
Get compartments that this grid holds.
Definition at line 57 of file CompartmentGrid.h.
References Composite::children().
Referenced by Restart::addtoHeapbranchers(), Restart::addtoHeaplinkermotor(), Controller::moveBoundary(), Restart::redistributediffusingspecies(), Controller::run(), setAllAsActive(), Restart::settorestartphase(), and SubSystem::updateBindingManagers().
getDiffusingMotors()
vector<tuple<int, int, vector<double>, vector<double> > > CompartmentGrid::getDiffusingMotors ()
This function gets all diffusing motor species and creates a virtual position within the simulation volume (dependent on the compartment).
This is used for analyzing motor gradients when species can either be bound or unbound.
Returns
- a tuple of the motor ID, the type, and two coordinates defining its end positions
Referenced by getType().
getFullName()
virtual string CompartmentGrid::getFullName () const inline virtual
Get name of this compartment grid.
Reimplemented from Composite.
Definition at line 79 of file CompartmentGrid.h.
Referenced by printSelf().
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getProtoCompartment() [1/2]
Compartment& CompartmentGrid::getProtoCompartment () inline
Get the protocompartment from this grid, in order to configure and then initialize.
Definition at line 82 of file CompartmentGrid.h.
References _prototype_compartment.
getProtoCompartment() [2/2]
const Compartment& CompartmentGrid::getProtoCompartment () const inline
Definition at line 83 of file CompartmentGrid.h.
References _prototype_compartment, and addChemSimReactions().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getType()
virtual int CompartmentGrid::getType () inline virtual
GetType implementation just returns zero (no CompartmentGrid types yet)
Implements Component.
Definition at line 154 of file CompartmentGrid.h.
References getDiffusingMotors().
isComposite()
virtual bool Composite::isComposite () const inline override virtual inherited
Returns true.
Reimplemented from Component.
Definition at line 71 of file Composite.h.
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
numberOfChildren()
virtual size_t Composite::numberOfChildren () const inline override virtual inherited
Returns the number of immediate children of this node.
Note
Species and reactions and not included in this tally
Reimplemented from Component.
Definition at line 102 of file Composite.h.
References Composite::children().
Referenced by Composite::countDescendents(), and printSelf().
numberOfReactions()
virtual size_t Composite::numberOfReactions () const inline override virtual inherited
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented from Component.
Reimplemented in Compartment.
Definition at line 131 of file Composite.h.
Referenced by Composite::countReactions().
numberOfSpecies()
virtual size_t Composite::numberOfSpecies () const inline override virtual inherited
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.)
Reimplemented from Component.
Reimplemented in Compartment.
Definition at line 106 of file Composite.h.
Referenced by Composite::countSpecies().
printSelf()
virtual void CompartmentGrid::printSelf () inline virtual
Print properties of this grid.
Implements Component.
Definition at line 90 of file CompartmentGrid.h.
References Composite::children(), getFullName(), and Composite::numberOfChildren().
removeBulkReaction()
virtual void CompartmentGrid::removeBulkReaction (ReactionBase * r) inline virtual
Remove a bulk reaction.
Definition at line 145 of file CompartmentGrid.h.
References countBulkSpecies(), countDiffusingSpecies(), and ReactionPtrContainerVector::removeReaction().
removeBulkReactions()
virtual void CompartmentGrid::removeBulkReactions (Species * s) inline virtual
Remove all bulk reactions that have a given species.
Parameters
s - species whose reactions should be removed
Definition at line 142 of file CompartmentGrid.h.
References ReactionPtrContainerVector::removeReactions().
removeChild()
virtual void Composite::removeChild (Component * child) inline virtual inherited
Remove *child from this node's children.
The child's destructor will be called and the memory will be freed.
Definition at line 89 of file Composite.h.
Referenced by Filament::retractMinusEnd(), and Filament::retractPlusEnd().
removeSpeciesBulk()
void CompartmentGrid::removeSpeciesBulk (const string & name) inline
Remove bulk species.
Definition at line 105 of file CompartmentGrid.h.
References SpeciesPtrContainerVector::removeSpecies().
setAllAsActive()
void CompartmentGrid::setAllAsActive () inline
Set all compartments as active. Used at initialization.
Definition at line 74 of file CompartmentGrid.h.
References getCompartments().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
Member Data Documentation
_bulkReactions
ReactionPtrContainerVector CompartmentGrid::_bulkReactions private
Bulk reactions in this grid.
Definition at line 45 of file CompartmentGrid.h.
_bulkSpecies
SpeciesPtrContainerVector CompartmentGrid::_bulkSpecies private
Bulk species in this grid.
Definition at line 44 of file CompartmentGrid.h.
_prototype_compartment
Compartment CompartmentGrid::_prototype_compartment private
Prototype compartment, to be configured before initialization.
Definition at line 41 of file CompartmentGrid.h.
Referenced by getProtoCompartment().
The documentation for this class was generated from the following files:
src/Structure/CompartmentGrid.h
src/Structure/CompartmentGrid.cpp