M3Sym: Visitor Class Reference
Visitor Class Reference abstract
An abstract interface to traverse those nodes in the Composite pattern which fulfill a certain predicate.
#include <Visitor.h>
Public Member Functions
bool visit (Component *c)
When this conditional Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
virtual ~Visitor ()
Virtual destructor.
Protected Member Functions
virtual bool visitImpl (Component *c)=0
When this Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
virtual bool predImpl (Component *c)
Return true if the Component *c satisfies the desired predicate.
Detailed Description
An abstract interface to traverse those nodes in the Composite pattern which fulfill a certain predicate.
The Visitor pattern allows a functor to visit each node of the Composite pattern. Concrete classes derived from Visitor must implement the visit(Component *c) method. Visitor, v, allows a predicate to be applied at each node, *c, and cv->visit(c) is called only if that node satisfies the predicate. For example, this can be used to visit only filaments in the hieararchy.
Definition at line 34 of file Visitor.h.
Constructor & Destructor Documentation
virtual Visitor::~Visitor () inline virtual
Virtual destructor.
Definition at line 49 of file Visitor.h.
Member Function Documentation
virtual bool Visitor::predImpl (Component * c) inline protected virtual
Return true if the Component *c satisfies the desired predicate.
Reimplemented in TypeVisitorLambda< ComponentType >, TypeVisitor< ComponentType >, and VisitorLambda.
Definition at line 59 of file Visitor.h.
Referenced by visit().
bool Visitor::visit (Component * c) inline
When this conditional Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
If v->visit(c) returns a false value, then the further propagation of the tree is terminated.
Definition at line 39 of file Visitor.h.
References predImpl(), and visitImpl().
Referenced by Component::apply(), and Composite::apply().
virtual bool Visitor::visitImpl (Component * c) protected pure virtual
When this Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Implemented in VisitorLambda.
Referenced by visit().
The documentation for this class was generated from the following file:
M3SYM/Visitor.h