M3Sym: MotorGhostDB Class Reference
MotorGhostDB Class Reference
A database for all MotorGhosts in the system.
#include <MotorGhostDB.h>
Public Member Functions
MotorGhostDB (const MotorGhostDB &rhs)=delete
Copying is not allowed.
MotorGhostDB & operator= (MotorGhostDB &rhs)=delete
Assignment is not allowed.
void addMotorGhost (MotorGhost *mg)
Add a motor ghost.
void removeMotorGhost (MotorGhost *mg)
Remove a motor ghost.
int getMotorID ()
Get current motor ID, and update the ID counter.
Static Public Member Functions
static MotorGhostDB * instance ()
Get instance.
Private Types
typedef list< MotorGhost * > mgdb
Private Member Functions
MotorGhostDB ()
Private Attributes
T elements
STL member.
Static Private Attributes
static int _currentMotorID = 0
To assign motor IDs.
static MotorGhostDB * _instance = 0
Singleton instance.
Detailed Description
A database for all MotorGhosts in the system.
This MotorGhostDB inherits from list and manage all creations and removing of MotorGhosts objects, as well as some standard list functions and iterators.
Definition at line 29 of file MotorGhostDB.h.
Member Typedef Documentation
typedef list<MotorGhost*> MotorGhostDB::mgdb private
Definition at line 31 of file MotorGhostDB.h.
Constructor & Destructor Documentation
MotorGhostDB::MotorGhostDB (const MotorGhostDB & rhs) delete
Copying is not allowed.
MotorGhostDB::MotorGhostDB () inline private
Definition at line 60 of file MotorGhostDB.h.
Referenced by instance().
Member Function Documentation
void MotorGhostDB::addMotorGhost (MotorGhost * mg) inline
Add a motor ghost.
Definition at line 49 of file MotorGhostDB.h.
Referenced by MotorGhost::MotorGhost().
int MotorGhostDB::getMotorID () inline
Get current motor ID, and update the ID counter.
Definition at line 54 of file MotorGhostDB.h.
References _currentMotorID.
Referenced by MotorGhost::MotorGhost().
MotorGhostDB * MotorGhostDB::instance () static
Get instance.
Definition at line 19 of file MotorGhostDB.cpp.
References _instance, and MotorGhostDB().
Referenced by MotorGhostFF::computeEnergy(), MotorGhostFF::computeForces(), MotorGhostFF::computeForcesAux(), MotorGhost::MotorGhost(), Output::printBasicSnapshot(), Controller::updateSystem(), and MotorGhost::~MotorGhost().
MotorGhostDB& MotorGhostDB::operator= (MotorGhostDB & rhs) delete
Assignment is not allowed.
void MotorGhostDB::removeMotorGhost (MotorGhost * mg) inline
Remove a motor ghost.
Definition at line 51 of file MotorGhostDB.h.
Referenced by MotorGhost::~MotorGhost().
Member Data Documentation
int MotorGhostDB::_currentMotorID = 0 static private
To assign motor IDs.
Definition at line 57 of file MotorGhostDB.h.
Referenced by getMotorID().
MotorGhostDB * MotorGhostDB::_instance = 0 static private
Singleton instance.
Definition at line 59 of file MotorGhostDB.h.
Referenced by instance().
T std::list< T >::elements inherited
STL member.
The documentation for this class was generated from the following files:
M3SYM/Structure/MotorGhostDB.h
M3SYM/Structure/MotorGhostDB.cpp