MEDYAN: ChemManager Class Reference
ChemManager Class Reference
For initailizing chemical reactions based on a specific system.
#include <ChemManager.h>
Public Member Functions
ChemManager (SubSystem *subSystem, ChemistryData chem)
Constructor sets subsystem pointer, and loads chem data.
virtual void initializeSystem (ChemSim *chem)
Initialize the system, based on the given simulation Adds all necessary reactions to the ChemSim object.
virtual void initializeCCylinder (CCylinder *cc, bool extensionFront, bool extensionBack, bool initialization)
Initializer for chem cylinders, based on the given simulation.
virtual void updateCopyNumbers ()
Update the copy numbers of all species in the chemical network.
Private Member Functions
void setupBindingSites ()
Helper functions. Names are pretty self-explanatory.
void configCMonomer ()
Helper functions. Names are pretty self-explanatory.
void initCMonomer (CMonomer *m, short filamentType, Compartment *c)
Helper functions. Names are pretty self-explanatory.
void genSpecies (Compartment &protoCompartment)
Helper functions. Names are pretty self-explanatory.
void genGeneralReactions (Compartment &protoCompartment)
Helper functions. Names are pretty self-explanatory.
void genBulkReactions ()
Helper functions. Names are pretty self-explanatory.
void genNucleationReactions ()
Helper functions. Names are pretty self-explanatory.
void genFilBindingReactions ()
void genFilReactionTemplates ()
Private Attributes
SubSystem * _subSystem
A pointer to subsytem for creation of callbacks, etc.
ChemistryData _chemData
The chemistry data for the system.
vector< vector< unique_ptr< FilamentReactionTemplate > > > _filRxnTemplates
A list of reactions to add to every new CCylinder.
Detailed Description
For initailizing chemical reactions based on a specific system.
ChemManager is used for initailizing all chemistry in the system. Initialized by the CController, ChemManager initializes the chemical components of the CompartmentGrid. The ChemManager can also update chemical components of a CCylinder using its stored collection of FilamentReactionTemplate, which is initialized at startup.
Definition at line 39 of file ChemManager.h.
Constructor & Destructor Documentation
ChemManager()
ChemManager::ChemManager (SubSystem * subSystem, ChemistryData chem) inline
Constructor sets subsystem pointer, and loads chem data.
Definition at line 62 of file ChemManager.h.
References initializeCCylinder(), initializeSystem(), and updateCopyNumbers().
Member Function Documentation
configCMonomer()
void ChemManager::configCMonomer () private
Helper functions. Names are pretty self-explanatory.
Definition at line 97 of file ChemManager.cpp.
References CMonomer::_numBSpecies, CMonomer::_numFSpecies, CMonomer::_speciesBoundIndex, CMonomer::_speciesFilamentIndex, SysParams::Chemistry(), and ChemParams::numFilaments.
genBulkReactions()
void ChemManager::genBulkReactions () private
Helper functions. Names are pretty self-explanatory.
Definition at line 2259 of file ChemManager.cpp.
References REGULAR, and ReactionBase::setReactionType().
genFilBindingReactions()
void ChemManager::genFilBindingReactions () private
CHANGED
Definition at line 1108 of file ChemManager.cpp.
References LinkerBindingManager::_neighborLists, MotorBindingManager::_neighborLists, FilamentBindingManager::_subSystem, ALL, BOUNDARY, BRANCHING, BRANCHINGPRODUCTS, BRANCHINGREACTANTS, SysParams::BUBBareRate, SysParams::Chemistry(), SysParams::CParams, GeoParams::cylinderSize, SpeciesNamesDB::genBindingName(), SysParams::Geometry(), LinkerBindingManager::getRMax(), MotorBindingManager::getRMax(), LinkerBindingManager::getRMin(), MotorBindingManager::getRMin(), LINKERBINDING, LMBINDINGPRODUCTS, LMBINDINGREACTANTS, SysParams::LUBBareRate, MOTORBINDING, SysParams::MUBBareRate, ChemParams::numFilaments, FilamentBindingManager::setMIndex(), FilamentBindingManager::setNLIndex(), ReactionBase::setReactionType(), and TOPBOUNDARY.
genFilReactionTemplates()
void ChemManager::genFilReactionTemplates () private
ALL PRODUCTS MUST BE BULK OR DIFFUSING
Definition at line 183 of file ChemManager.cpp.
References AGINGPRODUCTS, AGINGREACTANTS, BACKWARD, BOUND, BULK, SysParams::Chemistry(), SysParams::CParams, DEPOLYPRODUCTS, DEPOLYREACTANTS, DESTRUCTIONPRODUCTS, DESTRUCTIONREACTANTS, DIFFUSING, FILAMENT, FORWARD, MINUSEND, MOTOR, MOTORWALKINGBACKWARD, MOTORWALKINGFORWARD, MWALKINGPRODUCTS, MWALKINGREACTANTS, ChemParams::numFilaments, PLUSEND, POLYPRODUCTS, POLYREACTANTS, and SpeciesNamesDB::stringToInt().
genGeneralReactions()
void ChemManager::genGeneralReactions (Compartment & protoCompartment) private
Helper functions. Names are pretty self-explanatory.
Definition at line 2117 of file ChemManager.cpp.
References Compartment::addInternalReaction(), Compartment::findSpeciesByName(), REGULAR, and ReactionBase::setReactionType().
genNucleationReactions()
void ChemManager::genNucleationReactions () private
Helper functions. Names are pretty self-explanatory.
Definition at line 2364 of file ChemManager.cpp.
References SysParams::Chemistry(), FILAMENTCREATION, GController::getRandomCompartment(), NUCLEATIONPRODUCTS, NUCLEATIONREACTANTS, ChemParams::numFilaments, and ReactionBase::setReactionType().
genSpecies()
void ChemManager::genSpecies (Compartment & protoCompartment) private
Helper functions. Names are pretty self-explanatory.
Definition at line 1862 of file ChemManager.cpp.
References Compartment::addSpeciesDiffusing(), Compartment::addSpeciesPairBinding(), Compartment::addSpeciesSingleBinding(), AVG, BRANCHINGPRODUCTS, BRANCHINGREACTANTS, SysParams::Chemistry(), CONST, SpeciesNamesDB::genBindingName(), Species::getRSpecies(), LMBINDINGPRODUCTS, LMBINDINGREACTANTS, max_ulim, ChemParams::numFilaments, REG, and Compartment::setDiffusionRate().
initCMonomer()
void ChemManager::initCMonomer (CMonomer * m, short filamentType, Compartment * c) private
Helper functions. Names are pretty self-explanatory.
Definition at line 129 of file ChemManager.cpp.
References CMonomer::_speciesBound, CMonomer::_speciesFilament, Compartment::addSpeciesBound(), Compartment::addSpeciesBrancher(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPlusEnd(), and SpeciesNamesDB::genUniqueFilName().
initializeCCylinder()
void ChemManager::initializeCCylinder (CCylinder * cc, bool extensionFront, bool extensionBack, bool initialization) virtual
Initializer for chem cylinders, based on the given simulation.
Definition at line 2585 of file ChemManager.cpp.
References CCylinder::addCMonomer(), SysParams::Chemistry(), SysParams::CParams, Species::down(), CCylinder::getCMonomer(), CCylinder::getCompartment(), CCylinder::getCylinder(), Filament::getCylinderVector(), Component::getParent(), CCylinder::getSize(), Filament::getType(), CMonomer::speciesBound(), CMonomer::speciesFilament(), CMonomer::speciesMinusEnd(), CMonomer::speciesPlusEnd(), and Species::up().
Referenced by ChemManager(), and Cylinder::Cylinder().
initializeSystem()
void ChemManager::initializeSystem (ChemSim * chem) virtual
Initialize the system, based on the given simulation Adds all necessary reactions to the ChemSim object.
Definition at line 2549 of file ChemManager.cpp.
References Compartment::generateAllDiffusionReactions().
Referenced by ChemManager(), and CController::initialize().
setupBindingSites()
void ChemManager::setupBindingSites () private
Helper functions. Names are pretty self-explanatory.
Definition at line 28 of file ChemManager.cpp.
References ChemParams::bindingIndices, ChemParams::brancherBoundIndex, SysParams::Chemistry(), SysParams::CParams, ChemParams::linkerBoundIndex, ChemParams::motorBoundIndex, and ChemParams::numFilaments.
updateCopyNumbers()
void ChemManager::updateCopyNumbers () virtual
Update the copy numbers of all species in the chemical network.
Note
- this only sets the copy number if the simulation time tau has passed the release time of the molecule. This function is called at every set of chemical steps to check if molecules should be released at the current time.
remove species from all compartments
set as removed by marking copy number to -1
set as removed by marking copy number to -1
Definition at line 2029 of file ChemManager.cpp.
References Species::activateReactantReactions(), areEqual(), Species::down(), Compartment::findSpeciesByName(), Species::getN(), GController::getRandomCompartment(), Compartment::isActivated(), Species::passivateReactantReactions(), Species::setN(), tau(), Species::up(), and Species::updateReactantPropensities().
Referenced by ChemManager(), CController::run(), and CController::runSteps().
Member Data Documentation
_chemData
ChemistryData ChemManager::_chemData private
The chemistry data for the system.
Definition at line 85 of file ChemManager.h.
_filRxnTemplates
vector<vector<unique_ptr<FilamentReactionTemplate> > > ChemManager::_filRxnTemplates private
Initial value:
=
    vector<vector<unique_ptr<FilamentReactionTemplate>>>(MAX_FILAMENT_TYPES)
A list of reactions to add to every new CCylinder.
Note
- is a 2D vector corresponding to different filament types
Definition at line 89 of file ChemManager.h.
_subSystem
SubSystem* ChemManager::_subSystem private
A pointer to subsytem for creation of callbacks, etc.
Definition at line 84 of file ChemManager.h.
The documentation for this class was generated from the following files:
src/Chemistry/ChemManager.h
src/Chemistry/ChemManager.cpp