MEDYAN: Rand Class Reference
Rand Class Reference
A random number generator class.
#include <Rand.h>
Static Public Member Functions
static double randDouble (double low, double high)
Get a random double between low and high.
static int randInteger (int low, int high)
Get a random integer between low and high.
Static Private Attributes
static mt19937 _eng
static uniform_int_distribution< int > _int_distr
Detailed Description
A random number generator class.
Definition at line 23 of file Rand.h.
Member Function Documentation
randDouble()
static double Rand::randDouble (double low, double high) inline static
Get a random double between low and high.
Definition at line 31 of file Rand.h.
References _int_distr.
Referenced by mathfunc::branchProjection(), RandomFilamentDist::createFilaments(), ConnectedFilamentDist::createFilaments(), MTOCFilamentDist::createFilaments(), GController::getRandomCompartment(), GController::getRandomCoordinates(), marsagila(), Filament::sever(), and BranchingPoint::~BranchingPoint().
randInteger()
static int Rand::randInteger (int low, int high) inline static
Get a random integer between low and high.
Definition at line 35 of file Rand.h.
References _int_distr.
Referenced by BranchingManager::chooseBindingSite(), LinkerBindingManager::chooseBindingSites(), MotorBindingManager::chooseBindingSites(), MotorGhost::MotorGhost(), Filament::sever(), and BranchingPoint::~BranchingPoint().
Member Data Documentation
_eng
mt19937 Rand::_eng static private
Definition at line 26 of file Rand.h.
_int_distr
uniform_int_distribution< int > Rand::_int_distr static private
Definition at line 27 of file Rand.h.
Referenced by randDouble(), and randInteger().
The documentation for this class was generated from the following files:
src/Rand.h
src/Rand.cpp