MEDYAN: MTOCAttachment< MTOCInteractionType > Class Template Reference
MTOCAttachment< MTOCInteractionType > Class Template Reference
Represents an attachment potential of a MTOC.
#include <MTOCAttachment.h>
Public Member Functions
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual void computeLoadForces ()
Compute the load forces on beads from this interaction.
virtual NeighborList * getNeighborList ()
Get the neighbor list for this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
Bubble * _bubbleCulprit = nullptr
In the case of an error.
Component * _otherCulprit = nullptr
In the case of an error.
Private Attributes
MTOCInteractionType _FFType
Detailed Description
template<class MTOCInteractionType>
class MTOCAttachment< MTOCInteractionType >
Represents an attachment potential of a MTOC.
Definition at line 31 of file MTOCAttachment.h.
Member Function Documentation
computeEnergy()
template<class MTOCInteractionType > template double MTOCAttachment< MTOCInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BubbleInteractions.
Definition at line 25 of file MTOCAttachment.cpp.
References Filament::getFilaments(), Cylinder::getFirstBead(), Cylinder::getMCylinder(), Filament::getMinusEndCylinder(), MTOC::getMTOCs(), and MCylinder::getStretchingConst().
Referenced by MTOCAttachment< MTOCInteractionType >::computeForcesAux().
computeForces()
template<class MTOCInteractionType > template void MTOCAttachment< MTOCInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements BubbleInteractions.
Definition at line 66 of file MTOCAttachment.cpp.
References Filament::getFilaments(), Cylinder::getFirstBead(), Cylinder::getMCylinder(), Filament::getMinusEndCylinder(), MTOC::getMTOCs(), and MCylinder::getStretchingConst().
Referenced by MTOCAttachment< MTOCInteractionType >::computeForcesAux().
computeForcesAux()
template<class MTOCInteractionType > template void MTOCAttachment< MTOCInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements BubbleInteractions.
Definition at line 89 of file MTOCAttachment.cpp.
References MTOCAttachment< MTOCInteractionType >::computeEnergy(), MTOCAttachment< MTOCInteractionType >::computeForces(), Filament::getFilaments(), Cylinder::getFirstBead(), Cylinder::getMCylinder(), Filament::getMinusEndCylinder(), MTOC::getMTOCs(), and MCylinder::getStretchingConst().
computeLoadForces()
template<class MTOCInteractionType > virtual void MTOCAttachment< MTOCInteractionType >::computeLoadForces () inline virtual
Compute the load forces on beads from this interaction.
Implements BubbleInteractions.
Definition at line 41 of file MTOCAttachment.h.
getName()
template<class MTOCInteractionType > virtual const string MTOCAttachment< MTOCInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BubbleInteractions.
Definition at line 46 of file MTOCAttachment.h.
getNeighborList()
template<class MTOCInteractionType > virtual NeighborList* MTOCAttachment< MTOCInteractionType >::getNeighborList () inline virtual
Get the neighbor list for this interaction.
Implements BubbleInteractions.
Definition at line 44 of file MTOCAttachment.h.
Member Data Documentation
_bubbleCulprit
Bubble* BubbleInteractions::_bubbleCulprit = nullptr protected inherited
In the case of an error.
Definition at line 32 of file BubbleInteractions.h.
Referenced by BubbleFF::whoIsCulprit().
_FFType
template<class MTOCInteractionType > MTOCInteractionType MTOCAttachment< MTOCInteractionType >::_FFType private
Definition at line 34 of file MTOCAttachment.h.
_otherCulprit
Component* BubbleInteractions::_otherCulprit = nullptr protected inherited
In the case of an error.
Definition at line 33 of file BubbleInteractions.h.
Referenced by BubbleFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Bubble/MTOCAttachment.h
src/Mechanics/ForceField/Bubble/MTOCAttachment.cpp