MEDYAN: Compartment Class Reference
Compartment Class Reference
A container or holding Species and Reactions.
#include <Compartment.h>
Public Member Functions
Compartment ()
Default constructor, only takes in number of dimensions.
Compartment (const Compartment &C)
Constructor which clones another compartment.
Compartment & operator= (const Compartment &other)
Assignment operator.
virtual ~Compartment () noexcept
Destructor.
virtual bool apply_impl (SpeciesVisitor &v) override
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v) override
Applies ReactionVisitor v to every ReactionBase* object directly owned by this node.
virtual void setAsActive ()
Set a compartment as active. Used at initialization.
virtual void activate (ChemSim *chem)
Activate a compartment.
virtual void deactivate (ChemSim *chem)
Deactivate a compartment.
virtual bool isActivated ()
Check if compartment is activated.
virtual void setCoordinates (vector< double > coords)
Setter and getter for coordinates.
virtual const vector< double > & coordinates ()
virtual void transferSpecies ()
Transfer all species copy numbers from this compartment to neighboring active compartments.
virtual void clearReactions ()
Removes all reactions from this compartment, diffusing and internal.
virtual void clearSpecies ()
Clear all species from this compartment.
virtual void clearNeighbouringReactions ()
Remove diffusion reactions between this compartment and its neighbors.
virtual void removeFromNeighboursList ()
Remove this compartment from the neighbor list.
virtual bool isSpeciesContainer () const override
This is a species container.
virtual bool isReactionsContainer () const override
This is a reaction container.
virtual string getFullName () const override
Returns compartment name.
size_t numberOfSpecies () const override
Returns the number of species in this compartment.
size_t numberOfInternalReactions () const
Returns the number of internal reactions in this compartment.
size_t numberOfReactions () const override
Returns the total number of reactions in this compartment, diffusing and internal.
size_t removeSpecies (Species *species)
Remove species from this compartment.
ReactionBase * findSimilarInternalReaction (const ReactionBase &r)
Finds a similar internal reaction, see ReactionBase function.
ReactionBase * findSimilarDiffusionReaction (const ReactionBase &r)
Finds a similar diffusion reaction, see ReactionBase function.
virtual void removeDiffusionReactions (Species *s)
Remove all diffusion reactions that have a given species.
virtual void removeInternalReactions (Species *s)
Remove all internal reactions that have a given species.
virtual void removeDiffusionReaction (ReactionBase *r)
Remove a diffusion reaction.
virtual void removeInternalReaction (ReactionBase *r)
Remove an internal reaction.
Species * addSpeciesUnique (unique_ptr< Species > &&species, float diff_rate=-1.0)
Add a unique species pointer to this compartment.
ReactionBase * addInternalReactionUnique (unique_ptr< ReactionBase > &&reaction)
Add a unique internal reaction pointer to this compartment.
ReactionBase * addDiffusionReactionUnique (unique_ptr< ReactionBase > &&reaction)
Add a unique diffusing reaction pointer to this compartment.
ReactionBase * addInternalReaction (ReactionBase *r)
Add an internal reaction pointer to this compartment. Make unique.
ReactionBase * addDiffusionReaction (ReactionBase *r)
Add a diffusion reaciton pointer to this compartment. Make unique.
template<typename ... Args>
SpeciesDiffusing * addSpeciesDiffusing (Args &&...args)
Add a diffusing species to this compartment.
template<typename ... Args>
SpeciesFilament * addSpeciesFilament (Args &&...args)
Add a filament species to this compartment.
template<typename ... Args>
SpeciesPlusEnd * addSpeciesPlusEnd (Args &&...args)
Add a plus end species to this compartment.
template<typename ... Args>
SpeciesMinusEnd * addSpeciesMinusEnd (Args &&...args)
Add a minus end species to this compartment.
template<typename ... Args>
SpeciesBound * addSpeciesBound (Args &&...args)
Add a bound species to this compartment.
template<typename ... Args>
SpeciesLinker * addSpeciesLinker (Args &&...args)
Add a linker species to this compartment.
template<typename ... Args>
SpeciesMotor * addSpeciesMotor (Args &&...args)
Add a motor species to this compartment.
template<typename ... Args>
SpeciesBrancher * addSpeciesBrancher (Args &&...args)
Add a brancher species to this compartment.
template<typename ... Args>
SpeciesSingleBinding * addSpeciesSingleBinding (Args &&...args)
Add a single binding species to this compartment.
template<typename ... Args>
SpeciesPairBinding * addSpeciesPairBinding (Args &&...args)
Add a pair binding species to this compartment.
template<unsigned short M, unsigned short N, typename ... Args>
ReactionBase * addInternalReaction (Args &&...args)
Add an internal reaction to this compartment.
template<template< unsigned short M, unsigned short N > class RXN, unsigned short M, unsigned short N>
ReactionBase * addInternal (initializer_list< Species *> species, float rate)
Add an internal reaction to this compartment.
template<typename ... Args>
ReactionBase * addDiffusionReaction (Args &&...args)
Add a diffusion reaction to this compartment.
void addFilamentBindingManager (FilamentBindingManager *m)
Add a binding manager to this compartment.
vector< unique_ptr< FilamentBindingManager > > & getFilamentBindingManagers ()
Get binding managers for this compartment.
MotorBindingManager * getMotorBindingManager (int motorType)
Get a specific motor binding manager from this compartment.
void addBoundaryElement (BoundaryElement *be)
Add a boundary element to this compartment.
void removeBoundaryElement (BoundaryElement *be)
Remove a boundary element from this compartment.
bool hasBoundaryElement (BoundaryElement *be)
Check if boundary element is in this container.
unordered_set< BoundaryElement * > & getBoundaryElements ()
get the boundary elements in this compartment
void addCylinder (Cylinder *c)
Add a cylinder to this compartment.
void removeCylinder (Cylinder *c)
Remove a cylinder from this compartment.
unordered_set< Cylinder * > & getCylinders ()
get the cylinders in this compartment
float getDiffusionRate (string species_name)
Get the diffusion rate of a species.
void setDiffusionRate (Species *sp, float diff_rate)
Set the diffusion rate of a species in the compartment.
void setDiffusionRate (int molecule, float diff_rate)
Set the diffusion rate of a species in the compartment.
void setDiffusionRate (string species_name, float diff_rate)
Set the diffusion rate of a species in the compartment.
void addNeighbour (Compartment *comp)
Add a neighboring compartment to this compartments list of neighbors.
void removeNeighbour (Compartment *comp)
Remove a neighboring compartment.
void cloneSpecies (Compartment *target) const
Clone the species values of another compartment into this one.
void cloneReactions (Compartment *target) const
Clone the reaction values of another compartment into this one.
void cloneSpeciesReactions (Compartment *C)
Clone both the species and compartments into this compartment.
virtual Compartment * clone ()
Clone a compartment.
vector< ReactionBase * > generateDiffusionReactions (Compartment *C)
Generate diffusion reactions between this compartment and another.
vector< ReactionBase * > generateAllDiffusionReactions ()
Generate all diffusion reactions for this compartment and its neighbors.
void removeDiffusionReactions (ChemSim *chem, Compartment *C)
Remove diffusion reactions between this compartment and another.
void removeAllDiffusionReactions (ChemSim *chem)
Remove all diffusion reactions for this compartment and its neighbors.
size_t numberOfNeighbours () const
Gives the number of neighbors to this compartment.
SpeciesPtrContainerVector & getSpeciesContainer ()
Get the species container vector.
const SpeciesPtrContainerVector & getSpeciesContainer () const
ReactionPtrContainerVector & getInternalReactionContainer ()
Get the internal reaction container vector.
const ReactionPtrContainerVector & getInternalReactionContainer () const
ReactionPtrContainerVector & getDiffusionReactionContainer ()
Get the diffusion reaction container vector.
const ReactionPtrContainerVector & getDiffusionReactionContainer () const
vector< Compartment * > & getNeighbours ()
Get the vector list of neighbors to this compartment.
const vector< Compartment * > & getNeighbours () const
void printSpecies ()
Print the species in this compartment.
void printReactions ()
Print the reactions in this compartment.
bool areAllSpeciesUnique ()
Check if all species are unique pointers.
virtual void addChemSimReactions (ChemSim *chem)
Adds the reactions of this compartment to the ChemSim object.
virtual void printSelf () override
Print properties of this compartment.
virtual int getType () override
Return the type of this element as an integer index.
virtual bool apply (Visitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
virtual bool apply (SpeciesVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool isComposite () const override
Returns true.
virtual void addChild (unique_ptr< Component > &&child)
Adds a Component child to this Composite node.
virtual void removeChild (Component *child)
Remove *child from this node's children.
virtual size_t numberOfChildren () const override
Returns the number of immediate children of this node.
virtual size_t countDescendents () const override
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const override
Returns the number of Species being managed by this node and its descendent nodes.
virtual size_t countReactions () const override
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
virtual vector< unique_ptr< Component > > & children ()
Returns a reference to the container of Component children of this node.
virtual const vector< unique_ptr< Component > > & children () const
Returns a const reference to the container of Component children of this node.
virtual Component * children (size_t i)
Returns a pointer to the i-th Component child of this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
Species * findSpeciesByName (const string &name)
Species finder functions.
Species * findSpeciesByIndex (size_t index)
Species finder functions.
Species * findSpeciesByMolecule (int molecule)
Species finder functions.
Species * findSimilarSpecies (const Species &s)
Species finder functions.
Protected Attributes
SpeciesPtrContainerVector _species
CHEMICAL CONTAINERS.
ReactionPtrContainerVector _internal_reactions
Container with all internal reactions in compartment.
ReactionPtrContainerVector _diffusion_reactions
Container with all diffusion reactions in compartment.
unordered_map< int, float > _diffusion_rates
Diffusion rates of Species in compartment.
vector< unique_ptr< FilamentBindingManager > > _bindingManagers
All binding managers for this compartment.
unordered_set< BoundaryElement * > _boundaryElements
ELEMENT CONTAINERS.
unordered_set< Bead * > _beads
Set of beads that are in this compartment.
unordered_set< Cylinder * > _cylinders
Set of cylinders that are in this compartment.
vector< Compartment * > _neighbours
Neighbors of the compartment.
vector< double > _coords
OTHER COMPARTMENT PROPERTIES.
bool _activated = false
The compartment is activated for diffusion.
Friends
bool operator== (const Compartment &a, const Compartment &b)
Returns true if two Compartment objects are equal.
bool operator!= (const Compartment &a, const Compartment &b)
Return true if two Compartment are not equal.
Detailed Description
A container or holding Species and Reactions.
The Compartment class is a container for Species, internal Reactions, and diffusion Reactions that can occur. A Compartment object keeps track of the above while also holding pointers to its neighbors in order to generate diffusion Reactions and control other interactions.
The Compartment also keeps Trackable elements in the SubSystem that are in its space, including Beads, Cylinders, and BoundaryElements.
Lastly, the Compartment holds a container of FilamentBindingManager for updating binding reactions local to this compartment space only.
Definition at line 49 of file Compartment.h.
Constructor & Destructor Documentation
Compartment() [1/2]
Compartment::Compartment () inline
Default constructor, only takes in number of dimensions.
Definition at line 82 of file Compartment.h.
Referenced by clone().
Compartment() [2/2]
Compartment::Compartment (const Compartment & C) inline
Constructor which clones another compartment.
Definition at line 86 of file Compartment.h.
References _activated, _diffusion_rates, cloneReactions(), cloneSpecies(), and operator=().
~Compartment()
virtual Compartment::~Compartment () inline virtual noexcept
Destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 104 of file Compartment.h.
References apply_impl(), clearNeighbouringReactions(), clearReactions(), clearSpecies(), and removeFromNeighboursList().
Member Function Documentation
activate()
void Compartment::activate (ChemSim * chem) virtual
Activate a compartment.
Has the following side effects: 1) Adds diffusion reactions between this compartment's diffusing species and its neighboring active compartments
Definition at line 167 of file Compartment.cpp.
References _activated, ChemSim::addReaction(), and generateAllDiffusionReactions().
Referenced by CController::activate(), and setAsActive().
addBoundaryElement()
void Compartment::addBoundaryElement (BoundaryElement * be) inline
Add a boundary element to this compartment.
Definition at line 469 of file Compartment.h.
addChemSimReactions()
virtual void Compartment::addChemSimReactions (ChemSim * chem) inline virtual
Adds the reactions of this compartment to the ChemSim object.
Parameters
- chem, a ChemSim object that runs the reaction-diffusion algorithm
Definition at line 625 of file Compartment.h.
References ChemSim::addReaction(), and ReactionPtrContainerVector::reactions().
addChild()
virtual void Composite::addChild (unique_ptr< Component > && child) inline virtual inherited
Adds a Component child to this Composite node.
Parameters
child - is a unique_ptr<Component>, hence, this node takes the memory ownership of the corresponding child pointer.
Note
the rvalue semantics - the unique_ptr<...> cannot be copied, but only can be moved
Definition at line 81 of file Composite.h.
Referenced by Bead::Bead(), CompartmentGrid::CompartmentGrid(), Cylinder::Cylinder(), MTOC::setBubble(), and Filament::sever().
addCylinder()
void Compartment::addCylinder (Cylinder * c) inline
Add a cylinder to this compartment.
Definition at line 486 of file Compartment.h.
Referenced by Cylinder::Cylinder(), and Cylinder::updatePosition().
addDiffusionReaction() [1/2]
ReactionBase* Compartment::addDiffusionReaction (ReactionBase * r) inline
Add a diffusion reaciton pointer to this compartment. Make unique.
Definition at line 301 of file Compartment.h.
References ReactionPtrContainerVector::addReactionUnique(), and ReactionBase::setParent().
Referenced by generateDiffusionReactions().
addDiffusionReaction() [2/2]
template<typename ... Args> ReactionBase* Compartment::addDiffusionReaction (Args &&... args) inline
Add a diffusion reaction to this compartment.
Definition at line 436 of file Compartment.h.
References ReactionPtrContainerVector::addReaction(), and ReactionBase::setParent().
addDiffusionReactionUnique()
ReactionBase* Compartment::addDiffusionReactionUnique (unique_ptr< ReactionBase > && reaction) inline
Add a unique diffusing reaction pointer to this compartment.
Definition at line 287 of file Compartment.h.
References ReactionPtrContainerVector::addReactionUnique(), and ReactionBase::setParent().
addFilamentBindingManager()
void Compartment::addFilamentBindingManager (FilamentBindingManager * m) inline
Add a binding manager to this compartment.
Definition at line 443 of file Compartment.h.
addInternal()
template<template< unsigned short M, unsigned short N > class RXN, unsigned short M, unsigned short N> ReactionBase* Compartment::addInternal (initializer_list< Species *> species, float rate) inline
Add an internal reaction to this compartment.
Parameters
species,rate - specifying the species and rate that should be assigned
Definition at line 428 of file Compartment.h.
References ReactionPtrContainerVector::add(), and ReactionBase::setParent().
addInternalReaction() [1/2]
ReactionBase* Compartment::addInternalReaction (ReactionBase * r) inline
Add an internal reaction pointer to this compartment. Make unique.
Definition at line 294 of file Compartment.h.
References ReactionPtrContainerVector::addReactionUnique(), and ReactionBase::setParent().
Referenced by CCylinder::addCrossCylinderReaction(), CCylinder::addInternalReaction(), cloneReactions(), and ChemManager::genGeneralReactions().
addInternalReaction() [2/2]
template<unsigned short M, unsigned short N, typename ... Args> ReactionBase* Compartment::addInternalReaction (Args &&... args) inline
Add an internal reaction to this compartment.
Definition at line 419 of file Compartment.h.
References ReactionPtrContainerVector::addReaction(), and ReactionBase::setParent().
addInternalReactionUnique()
ReactionBase* Compartment::addInternalReactionUnique (unique_ptr< ReactionBase > && reaction) inline
Add a unique internal reaction pointer to this compartment.
Definition at line 280 of file Compartment.h.
References ReactionPtrContainerVector::addReactionUnique(), and ReactionBase::setParent().
addNeighbour()
void Compartment::addNeighbour (Compartment * comp) inline
Add a neighboring compartment to this compartments list of neighbors.
Definition at line 524 of file Compartment.h.
Referenced by GController::generateConnections().
addSpeciesBound()
template<typename ... Args> SpeciesBound* Compartment::addSpeciesBound (Args &&... args) inline
Add a bound species to this compartment.
Parameters
args - any number of SpeciesBound objects
Definition at line 354 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::initCMonomer().
addSpeciesBrancher()
template<typename ... Args> SpeciesBrancher* Compartment::addSpeciesBrancher (Args &&... args) inline
Add a brancher species to this compartment.
Parameters
args - any number of SpeciesBrancher objects
Definition at line 387 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::initCMonomer().
addSpeciesDiffusing()
template<typename ... Args> SpeciesDiffusing* Compartment::addSpeciesDiffusing (Args &&... args) inline
Add a diffusing species to this compartment.
Parameters
args - any number of SpeciesDiffusing objects
Definition at line 310 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::genSpecies().
addSpeciesFilament()
template<typename ... Args> SpeciesFilament* Compartment::addSpeciesFilament (Args &&... args) inline
Add a filament species to this compartment.
Parameters
args - any number of SpeciesFilament objects
Definition at line 321 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::initCMonomer().
addSpeciesLinker()
template<typename ... Args> SpeciesLinker* Compartment::addSpeciesLinker (Args &&... args) inline
Add a linker species to this compartment.
Parameters
args - any number of SpeciesLinker objects
Definition at line 365 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::initCMonomer().
addSpeciesMinusEnd()
template<typename ... Args> SpeciesMinusEnd* Compartment::addSpeciesMinusEnd (Args &&... args) inline
Add a minus end species to this compartment.
Parameters
args - any number of SpeciesBound objects
Definition at line 343 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::initCMonomer().
addSpeciesMotor()
template<typename ... Args> SpeciesMotor* Compartment::addSpeciesMotor (Args &&... args) inline
Add a motor species to this compartment.
Parameters
args - any number of SpeciesMotor objects
Definition at line 376 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::initCMonomer().
addSpeciesPairBinding()
template<typename ... Args> SpeciesPairBinding* Compartment::addSpeciesPairBinding (Args &&... args) inline
Add a pair binding species to this compartment.
Parameters
args - any number of SpeciesPairBinding objects
Definition at line 409 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::genSpecies().
addSpeciesPlusEnd()
template<typename ... Args> SpeciesPlusEnd* Compartment::addSpeciesPlusEnd (Args &&... args) inline
Add a plus end species to this compartment.
Parameters
args - any number of SpeciesBound objects
Definition at line 332 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::initCMonomer().
addSpeciesSingleBinding()
template<typename ... Args> SpeciesSingleBinding* Compartment::addSpeciesSingleBinding (Args &&... args) inline
Add a single binding species to this compartment.
Parameters
args - any number of SpeciesSingleBinding objects
Definition at line 398 of file Compartment.h.
References SpeciesPtrContainerVector::addSpecies(), Species::getMolecule(), and Species::setParent().
Referenced by ChemManager::genSpecies().
addSpeciesUnique()
Species* Compartment::addSpeciesUnique (unique_ptr< Species > && species, float diff_rate = -1.0) inline
Add a unique species pointer to this compartment.
Definition at line 272 of file Compartment.h.
References SpeciesPtrContainerVector::addSpeciesUnique(), Species::getMolecule(), and Species::setParent().
Referenced by cloneSpecies(), and CMonomer::CMonomer().
apply() [1/3]
bool Composite::apply (Visitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
Reimplemented from Component.
Definition at line 18 of file Composite.cpp.
References Composite::children(), and Visitor::visit().
Referenced by Composite::~Composite().
apply() [2/3]
bool Composite::apply (SpeciesVisitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented from Component.
Definition at line 31 of file Composite.cpp.
References Component::apply_impl(), and Composite::children().
apply() [3/3]
bool Composite::apply (ReactionVisitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented from Component.
Definition at line 43 of file Composite.cpp.
References Component::apply_impl(), and Composite::children().
apply_impl() [1/2]
bool Compartment::apply_impl (SpeciesVisitor & v) override virtual
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented from Component.
Definition at line 31 of file Compartment.cpp.
References _species, SpeciesPtrContainerVector::species(), and SpeciesVisitor::visit().
Referenced by ~Compartment().
apply_impl() [2/2]
bool Compartment::apply_impl (ReactionVisitor & v) override virtual
Applies ReactionVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented from Component.
Definition at line 38 of file Compartment.cpp.
References _internal_reactions, ReactionPtrContainerVector::reactions(), and ReactionVisitor::visit().
areAllSpeciesUnique()
bool Compartment::areAllSpeciesUnique () inline
Check if all species are unique pointers.
Definition at line 621 of file Compartment.h.
References SpeciesPtrContainerVector::areAllSpeciesUnique().
children() [1/3]
virtual vector<unique_ptr<Component> >& Composite::children () inline virtual inherited
Returns a reference to the container of Component children of this node.
Definition at line 145 of file Composite.h.
References Composite::_children.
Referenced by Composite::apply(), Composite::countDescendents(), Composite::countReactions(), Composite::countSpecies(), CompartmentGrid::getCompartment(), CompartmentGrid::getCompartments(), Composite::numberOfChildren(), and CompartmentGrid::printSelf().
children() [2/3]
virtual const vector<unique_ptr<Component> >& Composite::children () const inline virtual inherited
Returns a const reference to the container of Component children of this node.
Definition at line 148 of file Composite.h.
References Composite::_children.
children() [3/3]
virtual Component* Composite::children (size_t i) inline virtual inherited
Returns a pointer to the i-th Component child of this node.
Definition at line 151 of file Composite.h.
clearNeighbouringReactions()
virtual void Compartment::clearNeighbouringReactions () inline virtual
Remove diffusion reactions between this compartment and its neighbors.
Definition at line 169 of file Compartment.h.
References SpeciesPtrContainerVector::species().
Referenced by ~Compartment().
clearReactions()
virtual void Compartment::clearReactions () inline virtual
Removes all reactions from this compartment, diffusing and internal.
Definition at line 157 of file Compartment.h.
References ReactionPtrContainerVector::reactions().
Referenced by ~Compartment().
clearSpecies()
virtual void Compartment::clearSpecies () inline virtual
Clear all species from this compartment.
Definition at line 164 of file Compartment.h.
References SpeciesPtrContainerVector::species().
Referenced by ~Compartment().
clone()
virtual Compartment* Compartment::clone () inline virtual
Clone a compartment.
Note
- this does not clone the neighbors, just reactions and species
Definition at line 569 of file Compartment.h.
References Compartment(), generateAllDiffusionReactions(), generateDiffusionReactions(), removeAllDiffusionReactions(), and removeDiffusionReactions().
cloneReactions()
void Compartment::cloneReactions (Compartment * target) const inline
Clone the reaction values of another compartment into this one.
Definition at line 550 of file Compartment.h.
References _species, addInternalReaction(), numberOfReactions(), and ReactionPtrContainerVector::reactions().
Referenced by cloneSpeciesReactions(), Compartment(), and operator=().
cloneSpecies()
void Compartment::cloneSpecies (Compartment * target) const inline
Clone the species values of another compartment into this one.
Definition at line 541 of file Compartment.h.
References addSpeciesUnique(), Species::clone(), numberOfSpecies(), and SpeciesPtrContainerVector::species().
Referenced by cloneSpeciesReactions(), Compartment(), and operator=().
cloneSpeciesReactions()
void Compartment::cloneSpeciesReactions (Compartment * C) inline
Clone both the species and compartments into this compartment.
Definition at line 560 of file Compartment.h.
References _diffusion_rates, cloneReactions(), and cloneSpecies().
coordinates()
virtual const vector<double>& Compartment::coordinates () inline virtual
Definition at line 147 of file Compartment.h.
References _coords, and transferSpecies().
Referenced by GController::findCompartments(), GController::getRandomCoordinates(), BoundaryCubic::within(), BoundarySpherical::within(), and BoundaryCapsule::within().
countDescendents()
virtual size_t Composite::countDescendents () const inline override virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented from Component.
Definition at line 110 of file Composite.h.
References Composite::children(), Composite::numberOfChildren(), and std::sum().
countReactions()
virtual size_t Composite::countReactions () const inline override virtual inherited
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 135 of file Composite.h.
References Composite::children(), Component::isReactionsContainer(), Composite::numberOfReactions(), and std::sum().
countSpecies()
virtual size_t Composite::countSpecies () const inline override virtual inherited
Returns the number of Species being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 120 of file Composite.h.
References Composite::children(), Component::isSpeciesContainer(), Composite::numberOfSpecies(), and std::sum().
Referenced by Filament::getTurnoverTimes(), and Chemistry::print().
deactivate()
void Compartment::deactivate (ChemSim * chem) virtual
Deactivate a compartment.
Has the following sid effects: 0) Initially checks that all cylinders are removed from this compartment. A compartment cannot be deactivated unless this condition is already true. 1) Transfers copy numbers of all diffusing species from this compartment and moves them to a neighboring active compartment. If there are no neighboring active compartments, an error will result. 2) Removes all diffusion reactions involving diffusing species in this compartment.
Definition at line 180 of file Compartment.cpp.
References _activated, _cylinders, removeAllDiffusionReactions(), and transferSpecies().
Referenced by CController::deactivate(), and setAsActive().
findSimilarDiffusionReaction()
ReactionBase* Compartment::findSimilarDiffusionReaction (const ReactionBase & r) inline
Finds a similar diffusion reaction, see ReactionBase function.
Definition at line 245 of file Compartment.h.
References ReactionPtrContainerVector::findSimilarReaction().
findSimilarInternalReaction()
ReactionBase* Compartment::findSimilarInternalReaction (const ReactionBase & r) inline
Finds a similar internal reaction, see ReactionBase function.
Definition at line 240 of file Compartment.h.
References ReactionPtrContainerVector::findSimilarReaction().
findSimilarSpecies()
Species* Compartment::findSimilarSpecies (const Species & s) inline
Species finder functions.
Definition at line 231 of file Compartment.h.
References SpeciesPtrContainerVector::findSimilarSpecies().
findSpeciesByIndex()
Species* Compartment::findSpeciesByIndex (size_t index) inline
Species finder functions.
Definition at line 225 of file Compartment.h.
References SpeciesPtrContainerVector::findSpeciesByIndex().
findSpeciesByMolecule()
Species* Compartment::findSpeciesByMolecule (int molecule) inline
Species finder functions.
Definition at line 228 of file Compartment.h.
References SpeciesPtrContainerVector::findSpeciesByMolecule().
Referenced by PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), and DestructionTemplate::addReaction().
findSpeciesByName()
Species* Compartment::findSpeciesByName (const string & name) inline
Species finder functions.
Definition at line 222 of file Compartment.h.
Referenced by BranchingManager::BranchingManager(), ChemManager::genGeneralReactions(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), numberOfReactions(), Restart::setdiffspeciesnumber(), ChemManager::updateCopyNumbers(), and BranchingPoint::~BranchingPoint().
generateAllDiffusionReactions()
vector< ReactionBase * > Compartment::generateAllDiffusionReactions ()
Generate all diffusion reactions for this compartment and its neighbors.
Returns
- a vector of reactionbases that was just added
Definition at line 64 of file Compartment.cpp.
References _activated, _neighbours, and generateDiffusionReactions().
Referenced by activate(), clone(), and ChemManager::initializeSystem().
generateDiffusionReactions()
vector< ReactionBase * > Compartment::generateDiffusionReactions (Compartment * C)
Generate diffusion reactions between this compartment and another.
Returns
- a vector of reactionbases that was just added
Definition at line 45 of file Compartment.cpp.
References _diffusion_rates, _species, addDiffusionReaction(), SpeciesPtrContainerVector::findSpeciesByMolecule(), isActivated(), and SpeciesPtrContainerVector::species().
Referenced by clone(), and generateAllDiffusionReactions().
getBoundaryElements()
unordered_set<BoundaryElement*>& Compartment::getBoundaryElements () inline
get the boundary elements in this compartment
Definition at line 483 of file Compartment.h.
References _boundaryElements.
getCylinders()
unordered_set<Cylinder*>& Compartment::getCylinders () inline
get the cylinders in this compartment
Definition at line 495 of file Compartment.h.
References _cylinders.
Referenced by BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
getDiffusionRate()
float Compartment::getDiffusionRate (string species_name) inline
Get the diffusion rate of a species.
Parameters
- species_name, a string
Definition at line 499 of file Compartment.h.
References SpeciesNamesDB::stringToInt().
getDiffusionReactionContainer() [1/2]
ReactionPtrContainerVector& Compartment::getDiffusionReactionContainer () inline
Get the diffusion reaction container vector.
Definition at line 605 of file Compartment.h.
References _diffusion_reactions.
Referenced by Restart::setdiffspeciesnumber().
getDiffusionReactionContainer() [2/2]
const ReactionPtrContainerVector& Compartment::getDiffusionReactionContainer () const inline
Definition at line 606 of file Compartment.h.
References _diffusion_reactions.
getFilamentBindingManagers()
vector<unique_ptr<FilamentBindingManager> >& Compartment::getFilamentBindingManagers () inline
Get binding managers for this compartment.
Definition at line 448 of file Compartment.h.
References _bindingManagers.
getFullName()
virtual string Compartment::getFullName () const inline override virtual
Returns compartment name.
Reimplemented from Composite.
Definition at line 206 of file Compartment.h.
Referenced by printSelf().
getInternalReactionContainer() [1/2]
ReactionPtrContainerVector& Compartment::getInternalReactionContainer () inline
Get the internal reaction container vector.
Definition at line 601 of file Compartment.h.
References _internal_reactions.
getInternalReactionContainer() [2/2]
const ReactionPtrContainerVector& Compartment::getInternalReactionContainer () const inline
Definition at line 602 of file Compartment.h.
References _internal_reactions.
getMotorBindingManager()
MotorBindingManager* Compartment::getMotorBindingManager (int motorType) inline
Get a specific motor binding manager from this compartment.
Definition at line 454 of file Compartment.h.
getNeighbours() [1/2]
vector<Compartment*>& Compartment::getNeighbours () inline
Get the vector list of neighbors to this compartment.
Definition at line 609 of file Compartment.h.
References _neighbours.
Referenced by GController::findCompartments().
getNeighbours() [2/2]
const vector<Compartment*>& Compartment::getNeighbours () const inline
Definition at line 610 of file Compartment.h.
References _neighbours.
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getSpeciesContainer() [1/2]
SpeciesPtrContainerVector& Compartment::getSpeciesContainer () inline
Get the species container vector.
Definition at line 597 of file Compartment.h.
References _species.
Referenced by CCylinder::CCylinder().
getSpeciesContainer() [2/2]
const SpeciesPtrContainerVector& Compartment::getSpeciesContainer () const inline
Definition at line 598 of file Compartment.h.
References _species.
getType()
virtual int Compartment::getType () inline override virtual
Return the type of this element as an integer index.
Implements Component.
Definition at line 640 of file Compartment.h.
hasBoundaryElement()
bool Compartment::hasBoundaryElement (BoundaryElement * be) inline
Check if boundary element is in this container.
Definition at line 478 of file Compartment.h.
isActivated()
virtual bool Compartment::isActivated () inline virtual
Check if compartment is activated.
Definition at line 143 of file Compartment.h.
References _activated.
Referenced by generateDiffusionReactions(), GController::getRandomCompartment(), and ChemManager::updateCopyNumbers().
isComposite()
virtual bool Composite::isComposite () const inline override virtual inherited
Returns true.
Reimplemented from Component.
Definition at line 71 of file Composite.h.
isReactionsContainer()
virtual bool Compartment::isReactionsContainer () const inline override virtual
This is a reaction container.
Reimplemented from Component.
Definition at line 204 of file Compartment.h.
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Compartment::isSpeciesContainer () const inline override virtual
This is a species container.
Reimplemented from Component.
Definition at line 202 of file Compartment.h.
numberOfChildren()
virtual size_t Composite::numberOfChildren () const inline override virtual inherited
Returns the number of immediate children of this node.
Note
Species and reactions and not included in this tally
Reimplemented from Component.
Definition at line 102 of file Composite.h.
References Composite::children().
Referenced by Composite::countDescendents(), and CompartmentGrid::printSelf().
numberOfInternalReactions()
size_t Compartment::numberOfInternalReactions () const inline
Returns the number of internal reactions in this compartment.
Definition at line 210 of file Compartment.h.
References ReactionPtrContainerVector::reactions().
Referenced by operator==().
numberOfNeighbours()
size_t Compartment::numberOfNeighbours () const inline
Gives the number of neighbors to this compartment.
Definition at line 593 of file Compartment.h.
Referenced by printSelf().
numberOfReactions()
size_t Compartment::numberOfReactions () const inline override virtual
Returns the total number of reactions in this compartment, diffusing and internal.
Reimplemented from Composite.
Definition at line 215 of file Compartment.h.
References SpeciesPtrContainerVector::findSpeciesByName(), findSpeciesByName(), and ReactionPtrContainerVector::reactions().
Referenced by cloneReactions().
numberOfSpecies()
size_t Compartment::numberOfSpecies () const inline override virtual
Returns the number of species in this compartment.
Reimplemented from Composite.
Definition at line 208 of file Compartment.h.
References SpeciesPtrContainerVector::species().
Referenced by cloneSpecies(), and operator==().
operator=()
Compartment & Compartment::operator= (const Compartment & other)
Assignment operator.
Definition at line 18 of file Compartment.cpp.
References _diffusion_rates, _diffusion_reactions, _internal_reactions, _species, ReactionPtrContainerVector::clear(), SpeciesPtrContainerVector::clear(), cloneReactions(), and cloneSpecies().
Referenced by Compartment().
printReactions()
void Compartment::printReactions () inline
Print the reactions in this compartment.
Definition at line 615 of file Compartment.h.
References ReactionPtrContainerVector::printReactions().
Referenced by printSelf().
printSelf()
virtual void Compartment::printSelf () inline override virtual
Print properties of this compartment.
Implements Component.
Definition at line 631 of file Compartment.h.
References getFullName(), numberOfNeighbours(), printReactions(), and printSpecies().
printSpecies()
void Compartment::printSpecies () inline
Print the species in this compartment.
Definition at line 613 of file Compartment.h.
References SpeciesPtrContainerVector::printSpecies().
Referenced by printSelf().
removeAllDiffusionReactions()
void Compartment::removeAllDiffusionReactions (ChemSim * chem)
Remove all diffusion reactions for this compartment and its neighbors.
Returns
- a vector of reactionbases that was just removed
Definition at line 100 of file Compartment.cpp.
References _diffusion_reactions, _neighbours, ReactionPtrContainerVector::clear(), ReactionPtrContainerVector::reactions(), removeDiffusionReactions(), and ChemSim::removeReaction().
Referenced by clone(), and deactivate().
removeBoundaryElement()
void Compartment::removeBoundaryElement (BoundaryElement * be) inline
Remove a boundary element from this compartment.
Note
does nothing if boundary element is not in compartment
Definition at line 473 of file Compartment.h.
removeChild()
virtual void Composite::removeChild (Component * child) inline virtual inherited
Remove *child from this node's children.
The child's destructor will be called and the memory will be freed.
Definition at line 89 of file Composite.h.
Referenced by Filament::retractMinusEnd(), and Filament::retractPlusEnd().
removeCylinder()
void Compartment::removeCylinder (Cylinder * c) inline
Remove a cylinder from this compartment.
Note
does nothing if cylinder is not in compartment already
Definition at line 490 of file Compartment.h.
Referenced by Cylinder::updatePosition(), and Cylinder::~Cylinder().
removeDiffusionReaction()
virtual void Compartment::removeDiffusionReaction (ReactionBase * r) inline virtual
Remove a diffusion reaction.
Definition at line 262 of file Compartment.h.
References ReactionPtrContainerVector::removeReaction().
removeDiffusionReactions() [1/2]
virtual void Compartment::removeDiffusionReactions (Species * s) inline virtual
Remove all diffusion reactions that have a given species.
Parameters
s - species whose reactions should be removed
Definition at line 251 of file Compartment.h.
References ReactionPtrContainerVector::removeReactions().
Referenced by clone(), and removeAllDiffusionReactions().
removeDiffusionReactions() [2/2]
void Compartment::removeDiffusionReactions (ChemSim * chem, Compartment * C)
Remove diffusion reactions between this compartment and another.
Returns
- a vector of reactionbases that was just removed
Definition at line 77 of file Compartment.cpp.
References _diffusion_reactions, ReactionPtrContainerVector::reactions(), ChemSim::removeReaction(), and ReactionPtrContainerVector::removeReaction().
removeFromNeighboursList()
virtual void Compartment::removeFromNeighboursList () inline virtual
Remove this compartment from the neighbor list.
Definition at line 181 of file Compartment.h.
References operator==.
Referenced by ~Compartment().
removeInternalReaction()
virtual void Compartment::removeInternalReaction (ReactionBase * r) inline virtual
Remove an internal reaction.
Definition at line 267 of file Compartment.h.
References ReactionPtrContainerVector::removeReaction().
Referenced by CCylinder::removeCrossCylinderReaction(), and CCylinder::removeInternalReaction().
removeInternalReactions()
virtual void Compartment::removeInternalReactions (Species * s) inline virtual
Remove all internal reactions that have a given species.
Parameters
s - species whose reactions should be removed
Definition at line 257 of file Compartment.h.
References ReactionPtrContainerVector::removeReactions().
removeNeighbour()
void Compartment::removeNeighbour (Compartment * comp) inline
Remove a neighboring compartment.
Definition at line 534 of file Compartment.h.
removeSpecies()
size_t Compartment::removeSpecies (Species * species) inline
Remove species from this compartment.
Definition at line 237 of file Compartment.h.
References SpeciesPtrContainerVector::removeSpecies().
Referenced by CCylinder::~CCylinder().
setAsActive()
virtual void Compartment::setAsActive () inline virtual
Set a compartment as active. Used at initialization.
Definition at line 124 of file Compartment.h.
References activate(), and deactivate().
setCoordinates()
virtual void Compartment::setCoordinates (vector< double > coords) inline virtual
Setter and getter for coordinates.
Definition at line 146 of file Compartment.h.
Referenced by GController::generateConnections().
setDiffusionRate() [1/3]
void Compartment::setDiffusionRate (Species * sp, float diff_rate) inline
Set the diffusion rate of a species in the compartment.
Definition at line 505 of file Compartment.h.
References Species::getMolecule().
Referenced by ChemManager::genSpecies().
setDiffusionRate() [2/3]
void Compartment::setDiffusionRate (int molecule, float diff_rate) inline
Set the diffusion rate of a species in the compartment.
Parameters
- molecule, an integer representing the species in the speciesDB
Definition at line 512 of file Compartment.h.
setDiffusionRate() [3/3]
void Compartment::setDiffusionRate (string species_name, float diff_rate) inline
Set the diffusion rate of a species in the compartment.
Parameters
- species_name, a string
Definition at line 518 of file Compartment.h.
References SpeciesNamesDB::stringToInt().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
transferSpecies()
void Compartment::transferSpecies () virtual
Transfer all species copy numbers from this compartment to neighboring active compartments.
If no neighboring active compartments are present, throw an error.
Definition at line 116 of file Compartment.cpp.
References _neighbours, _species, Species::getN(), and SpeciesPtrContainerVector::species().
Referenced by coordinates(), and deactivate().
Friends And Related Function Documentation
operator!=
bool operator!= (const Compartment & a, const Compartment & b) friend
Return true if two Compartment are not equal.
See also
operator ==(const Compartment& a, const Compartment& b) above
Definition at line 196 of file Compartment.h.
operator==
bool operator== (const Compartment & a, const Compartment & b) friend
Returns true if two Compartment objects are equal.
Two Compartment objects are equal if each contains analogous Species and Reaction objects, in the same order
Definition at line 195 of file Compartment.cpp.
Referenced by removeFromNeighboursList().
Member Data Documentation
_activated
bool Compartment::_activated = false protected
The compartment is activated for diffusion.
Definition at line 78 of file Compartment.h.
Referenced by activate(), Compartment(), deactivate(), generateAllDiffusionReactions(), and isActivated().
_beads
unordered_set<Bead*> Compartment::_beads protected
Set of beads that are in this compartment.
Definition at line 70 of file Compartment.h.
_bindingManagers
vector<unique_ptr<FilamentBindingManager> > Compartment::_bindingManagers protected
All binding managers for this compartment.
Definition at line 64 of file Compartment.h.
Referenced by getFilamentBindingManagers().
_boundaryElements
unordered_set<BoundaryElement*> Compartment::_boundaryElements protected
ELEMENT CONTAINERS.
Set of boundary element that are in this compartment
Definition at line 67 of file Compartment.h.
Referenced by getBoundaryElements().
_coords
vector<double> Compartment::_coords protected
OTHER COMPARTMENT PROPERTIES.
Coordinates of this compartment
Definition at line 77 of file Compartment.h.
Referenced by coordinates().
_cylinders
unordered_set<Cylinder*> Compartment::_cylinders protected
Set of cylinders that are in this compartment.
Definition at line 72 of file Compartment.h.
Referenced by deactivate(), and getCylinders().
_diffusion_rates
unordered_map<int,float> Compartment::_diffusion_rates protected
Diffusion rates of Species in compartment.
Definition at line 60 of file Compartment.h.
Referenced by cloneSpeciesReactions(), Compartment(), generateDiffusionReactions(), and operator=().
_diffusion_reactions
ReactionPtrContainerVector Compartment::_diffusion_reactions protected
Container with all diffusion reactions in compartment.
Definition at line 57 of file Compartment.h.
Referenced by getDiffusionReactionContainer(), operator=(), removeAllDiffusionReactions(), and removeDiffusionReactions().
_internal_reactions
ReactionPtrContainerVector Compartment::_internal_reactions protected
Container with all internal reactions in compartment.
Definition at line 55 of file Compartment.h.
Referenced by apply_impl(), getInternalReactionContainer(), operator=(), and operator==().
_neighbours
vector<Compartment*> Compartment::_neighbours protected
Neighbors of the compartment.
Definition at line 74 of file Compartment.h.
Referenced by generateAllDiffusionReactions(), getNeighbours(), removeAllDiffusionReactions(), and transferSpecies().
_species
SpeciesPtrContainerVector Compartment::_species protected
CHEMICAL CONTAINERS.
Container with all species in this compartment
Definition at line 53 of file Compartment.h.
Referenced by apply_impl(), cloneReactions(), generateDiffusionReactions(), getSpeciesContainer(), operator=(), operator==(), and transferSpecies().
The documentation for this class was generated from the following files:
src/Structure/Compartment.h
src/Structure/Compartment.cpp