MEDYAN: BoundaryCylinderRepulsion< BRepulsionInteractionType > Class Template Reference
BoundaryCylinderRepulsion< BRepulsionInteractionType > Class Template Reference
Represents a repulsive interaction between a BoundaryElement and Cylinder.
#include <BoundaryCylinderRepulsion.h>
Public Member Functions
BoundaryCylinderRepulsion ()
Constructor.
virtual double computeEnergy (double d)
Template specializations.
virtual NeighborList * getNeighborList ()
Get the neighbor list for this interaction.
virtual const string getName ()
Get the name of this interaction.
virtual void computeForces ()
This repulsive force calculation also updates load forces on beads within the interaction range.
virtual void computeForcesAux ()
This repulsive force calculation also updates load forces on beads within the interaction range.
virtual void computeLoadForces ()
Compute the load forces on beads from this interaction.
Protected Attributes
BoundaryElement * _boundaryElementCulprit = nullptr
In the case of an error.
Component * _otherCulprit = nullptr
In the case of an error.
Private Attributes
BRepulsionInteractionType _FFType
BoundaryCylinderNL * _neighborList
Neighbor list of BoundaryElement - Cylinder.
Detailed Description
template<class BRepulsionInteractionType>
class BoundaryCylinderRepulsion< BRepulsionInteractionType >
Represents a repulsive interaction between a BoundaryElement and Cylinder.
Definition at line 32 of file BoundaryCylinderRepulsion.h.
Constructor & Destructor Documentation
BoundaryCylinderRepulsion()
template<class BRepulsionInteractionType > BoundaryCylinderRepulsion< BRepulsionInteractionType >::BoundaryCylinderRepulsion () inline
Constructor.
Definition at line 40 of file BoundaryCylinderRepulsion.h.
References SysParams::Boundaries(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux(), and BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces().
Member Function Documentation
computeEnergy()
template<class BRepulsionInteractionType > template double BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BoundaryInteractions.
Definition at line 27 of file BoundaryCylinderRepulsion.cpp.
References Bead::coordinate, Bead::force, and BoundaryElement::getBoundaryElements().
Referenced by BoundaryCylinderRepulsion< BRepulsionInteractionType >::BoundaryCylinderRepulsion(), and BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces().
computeForces()
template<class BRepulsionInteractionType > template void BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForces () virtual
This repulsive force calculation also updates load forces on beads within the interaction range.
Implements BoundaryInteractions.
Definition at line 71 of file BoundaryCylinderRepulsion.cpp.
References Bead::coordinate, and BoundaryElement::getBoundaryElements().
Referenced by BoundaryCylinderRepulsion< BRepulsionInteractionType >::BoundaryCylinderRepulsion(), and BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces().
computeForcesAux()
template<class BRepulsionInteractionType > template void BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux () virtual
This repulsive force calculation also updates load forces on beads within the interaction range.
Implements BoundaryInteractions.
Definition at line 96 of file BoundaryCylinderRepulsion.cpp.
References Bead::coordinate, and BoundaryElement::getBoundaryElements().
Referenced by BoundaryCylinderRepulsion< BRepulsionInteractionType >::BoundaryCylinderRepulsion(), and BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces().
computeLoadForces()
template<class BRepulsionInteractionType > template void BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces () virtual
Compute the load forces on beads from this interaction.
this normal is in the direction of polymerization
this normal is in the direction of polymerization
Implements BoundaryInteractions.
Definition at line 120 of file BoundaryCylinderRepulsion.cpp.
References BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux(), Bead::coordinate, GeoParams::cylinderNumMon, SysParams::Geometry(), BoundaryElement::getBoundaryElements(), Bead::getType(), Bead::lfim, Bead::lfip, Bead::loadForcesM, Bead::loadForcesP, GeoParams::monomerSize, mathfunc::normalizedVector(), and mathfunc::twoPointDirection().
Referenced by BoundaryCylinderRepulsion< BRepulsionInteractionType >::BoundaryCylinderRepulsion().
getName()
template<class BRepulsionInteractionType > virtual const string BoundaryCylinderRepulsion< BRepulsionInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BoundaryInteractions.
Definition at line 57 of file BoundaryCylinderRepulsion.h.
getNeighborList()
template<class BRepulsionInteractionType > virtual NeighborList* BoundaryCylinderRepulsion< BRepulsionInteractionType >::getNeighborList () inline virtual
Get the neighbor list for this interaction.
Implements BoundaryInteractions.
Definition at line 55 of file BoundaryCylinderRepulsion.h.
References BoundaryCylinderRepulsion< BRepulsionInteractionType >::_neighborList.
Member Data Documentation
_boundaryElementCulprit
BoundaryElement* BoundaryInteractions::_boundaryElementCulprit = nullptr protected inherited
In the case of an error.
Definition at line 33 of file BoundaryInteractions.h.
Referenced by BoundaryFF::whoIsCulprit().
_FFType
template<class BRepulsionInteractionType > BRepulsionInteractionType BoundaryCylinderRepulsion< BRepulsionInteractionType >::_FFType private
Definition at line 35 of file BoundaryCylinderRepulsion.h.
_neighborList
template<class BRepulsionInteractionType > BoundaryCylinderNL* BoundaryCylinderRepulsion< BRepulsionInteractionType >::_neighborList private
Neighbor list of BoundaryElement - Cylinder.
Definition at line 36 of file BoundaryCylinderRepulsion.h.
Referenced by BoundaryCylinderRepulsion< BRepulsionInteractionType >::getNeighborList().
_otherCulprit
Component* BoundaryInteractions::_otherCulprit = nullptr protected inherited
In the case of an error.
Definition at line 34 of file BoundaryInteractions.h.
Referenced by BoundaryFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Boundary/BoundaryCylinderRepulsion.h
src/Mechanics/ForceField/Boundary/BoundaryCylinderRepulsion.cpp