MEDYAN: MController Class Reference
MController Class Reference
Used to initialize, control, and run the mechanical components of a simulation.
#include <MController.h>
Public Member Functions
MController (SubSystem *s)
Constructor which sets a subsystem pointer.
void initialize (MechanicsFFType forceFields, MechanicsAlgorithm Minimizers)
Initialze the force fields and minimizers used.
void run (bool steplimit=true)
Run a minimization on the system using the chosen algorithm.
Private Member Functions
void initializeFF (MechanicsFFType &forceFields)
Initialize the force-fields used in the simualtion.
void initializeMinAlgorithms (MechanicsAlgorithm &Minimizers)
Initialize the minimization algorithms used in the simulation.
Private Attributes
ForceFieldManager _FFManager
Container and methods for all force fields in system.
vector< Minimizer * > _minimizerAlgorithms
Vector with algorithms for system minimization.
SubSystem * _subSystem
A pointer to the subsystem.
Detailed Description
Used to initialize, control, and run the mechanical components of a simulation.
MechanicalController is a class used by the SubSystem to initialize ForceFields, given an initial selection of which force fields should be included. It can compute forces and energies over all force fields using the ForceFieldManager, as well as run energy Minimization algorithms.
Definition at line 37 of file MController.h.
Constructor & Destructor Documentation
MController()
MController::MController (SubSystem * s) inline
Constructor which sets a subsystem pointer.
Definition at line 55 of file MController.h.
Member Function Documentation
initialize()
void MController::initialize (MechanicsFFType forceFields, MechanicsAlgorithm Minimizers) inline
Initialze the force fields and minimizers used.
Definition at line 58 of file MController.h.
References initializeFF(), and initializeMinAlgorithms().
Referenced by Controller::initialize().
initializeFF()
void MController::initializeFF (MechanicsFFType & forceFields) private
Initialize the force-fields used in the simualtion.
Definition at line 52 of file MController.cpp.
References _FFManager, ForceFieldManager::_forceFields, _subSystem, SubSystem::addNeighborList(), MechanicsFFType::BoundaryFFType, MechanicsFFType::BrBendingType, MechanicsFFType::BrDihedralType, MechanicsFFType::BrPositionType, MechanicsFFType::BrStretchingType, MechanicsFFType::BubbleFFType, MechanicsFFType::FBendingType, MechanicsFFType::FStretchingType, MechanicsFFType::FTwistingType, MechanicsFFType::LBendingType, MechanicsFFType::LStretchingType, MechanicsFFType::LTwistingType, MechanicsFFType::MBendingType, MechanicsFFType::MStretchingType, MechanicsFFType::MTOCFFType, MechanicsFFType::MTwistingType, and MechanicsFFType::VolumeFFType.
Referenced by initialize().
initializeMinAlgorithms()
void MController::initializeMinAlgorithms (MechanicsAlgorithm & Minimizers) private
Initialize the minimization algorithms used in the simulation.
Definition at line 28 of file MController.cpp.
References _minimizerAlgorithms, MechanicsAlgorithm::ConjugateGradient, MechanicsAlgorithm::gradientTolerance, MechanicsAlgorithm::lambdaMax, and MechanicsAlgorithm::maxDistance.
Referenced by initialize().
run()
void MController::run (bool steplimit = true) inline
Run a minimization on the system using the chosen algorithm.
Definition at line 64 of file MController.h.
Referenced by Controller::run().
Member Data Documentation
_FFManager
ForceFieldManager MController::_FFManager private
Container and methods for all force fields in system.
Definition at line 40 of file MController.h.
Referenced by initializeFF().
_minimizerAlgorithms
vector<Minimizer*> MController::_minimizerAlgorithms private
Vector with algorithms for system minimization.
Definition at line 42 of file MController.h.
Referenced by initializeMinAlgorithms().
_subSystem
SubSystem* MController::_subSystem private
A pointer to the subsystem.
Definition at line 45 of file MController.h.
Referenced by initializeFF().
The documentation for this class was generated from the following files:
src/MController.h
src/MController.cpp