M3Sym: SpeciesPtrContainerVector Class Reference
SpeciesPtrContainerVector Class Reference
A concrete class implementing the SpeciesPtrContainerIFace, using vector<unique_ptr<Species>> as the container implementation.
#include <SpeciesContainer.h>
Public Member Functions
SpeciesPtrContainerVector ()=default
Default Constructir.
SpeciesPtrContainerVector (const SpeciesPtrContainerVector &)=delete
Copying is not allowed.
SpeciesPtrContainerVector & operator= (SpeciesPtrContainerVector &)=delete
The equality operator is not allowed.
virtual void clear () override
Empty the container. All memories are freed.
virtual Species * addSpecies (Species *species)
Add species to the container. The memory of species is owned by the container.
virtual Species * addSpeciesUnique (unique_ptr< Species > &&species) override
Add species to the container.
template<typename T , typename... Args>
Species * addSpecies (Args &&...args)
Add species of type T to the container, forwarding Args to the corresponding Species constructor.
virtual size_t removeSpecies (const string &name) override
Remove all species matching "name" from the container. The memories are freed.
virtual size_t removeSpecies (Species *species) override
Remove all species from the container. The memory is freed.
virtual Species * findSpeciesByName (const string &name) const override
Return a pointer to Species which has a name matching the argument.
virtual Species * findSpeciesByMolecule (int molecule) const override
Return a pointer to Species matching the molecule field of Species.
virtual Species * findSpeciesByIndex (size_t index) const override
Return a pointer to Species having specified index in the container.
virtual Species * findSimilarSpecies (const Species &s) const override
Return a pointer to Species which satisfies the equality operator with s.
vector< unique_ptr< Species > > & species ()
Return a reference to the underlying vector<unique_ptr<Species>> container.
const vector< unique_ptr
< Species > > & species () const
Return a const reference to the underlying vector<unique_ptr<Species>> container.
virtual bool areAllSpeciesUnique () const override
Returns true, if all contained Species are different from each other as determined by Species.getMolecule() method.
virtual size_t size () const override
Return the number of Species in the container.
virtual void printSpecies () const override
Print all Species contained by the container.
Protected Attributes
vector< unique_ptr< Species > > _species
Species pointers container.
Detailed Description
A concrete class implementing the SpeciesPtrContainerIFace, using vector<unique_ptr<Species>> as the container implementation.
Definition at line 65 of file SpeciesContainer.h.
Constructor & Destructor Documentation
SpeciesPtrContainerVector::SpeciesPtrContainerVector () default
Default Constructir.
SpeciesPtrContainerVector::SpeciesPtrContainerVector (const SpeciesPtrContainerVector &) delete
Copying is not allowed.
Member Function Documentation
virtual Species* SpeciesPtrContainerVector::addSpecies (Species * species) inline virtual
Add species to the container. The memory of species is owned by the container.
Implements SpeciesPtrContainerIFace.
Definition at line 82 of file SpeciesContainer.h.
References _species.
Referenced by Compartment::addSpeciesBound(), CompartmentGrid::addSpeciesBulk(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), and Compartment::addSpeciesPlusEnd().
template<typename T , typename... Args> Species* SpeciesPtrContainerVector::addSpecies (Args &&... args) inline
Add species of type T to the container, forwarding Args to the corresponding Species constructor.
Definition at line 97 of file SpeciesContainer.h.
References _species, and A_B_C_Cycle::T.
virtual Species* SpeciesPtrContainerVector::addSpeciesUnique (unique_ptr< Species > && species) inline override virtual
Add species to the container.
The memory of species is owned by the container.
Parameters
species is a unique_ptr<Species> object, which needs to be a rvalue (e.g. move(...) was used to make it so.
Implements SpeciesPtrContainerIFace.
Definition at line 90 of file SpeciesContainer.h.
References _species, and species().
Referenced by Compartment::addSpeciesUnique().
virtual bool SpeciesPtrContainerVector::areAllSpeciesUnique () const inline override virtual
Returns true, if all contained Species are different from each other as determined by Species.getMolecule() method.
Implements SpeciesPtrContainerIFace.
Definition at line 189 of file SpeciesContainer.h.
References _species.
Referenced by Compartment::areAllSpeciesUnique().
virtual void SpeciesPtrContainerVector::clear () inline override virtual
Empty the container. All memories are freed.
Implements SpeciesPtrContainerIFace.
Definition at line 79 of file SpeciesContainer.h.
References _species.
Referenced by Compartment::operator=().
virtual Species* SpeciesPtrContainerVector::findSimilarSpecies (const Species & s) const inline override virtual
Return a pointer to Species which satisfies the equality operator with s.
Otherwise, return a nullptr.
Note
The first match is returned.
Implements SpeciesPtrContainerIFace.
Definition at line 172 of file SpeciesContainer.h.
References _species.
Referenced by Compartment::findSimilarSpecies().
virtual Species* SpeciesPtrContainerVector::findSpeciesByIndex (size_t index) const inline override virtual
Return a pointer to Species having specified index in the container.
Note
Array bounds are not checked, so index must be valid.
Implements SpeciesPtrContainerIFace.
Definition at line 166 of file SpeciesContainer.h.
References _species.
Referenced by CompartmentGrid::addSpeciesBulk(), and Compartment::findSpeciesByIndex().
virtual Species* SpeciesPtrContainerVector::findSpeciesByMolecule (int molecule) const inline override virtual
Return a pointer to Species matching the molecule field of Species.
Otherwise, return a nullptr.
Note
The first match is returned.
Implements SpeciesPtrContainerIFace.
Definition at line 154 of file SpeciesContainer.h.
References _species.
Referenced by CompartmentGrid::findSpeciesBulkByMolecule(), Compartment::findSpeciesByMolecule(), and Compartment::generateDiffusionReactions().
virtual Species* SpeciesPtrContainerVector::findSpeciesByName (const string & name) const inline override virtual
Return a pointer to Species which has a name matching the argument.
Otherwise, return a nullptr.
Note
The first match is returned.
Implements SpeciesPtrContainerIFace.
Definition at line 142 of file SpeciesContainer.h.
References _species.
Referenced by CompartmentGrid::findSpeciesBulkByName(), and Compartment::findSpeciesByName().
SpeciesPtrContainerVector& SpeciesPtrContainerVector::operator= (SpeciesPtrContainerVector &) delete
The equality operator is not allowed.
virtual void SpeciesPtrContainerVector::printSpecies () const inline override virtual
Print all Species contained by the container.
Implements SpeciesPtrContainerIFace.
Definition at line 206 of file SpeciesContainer.h.
References _species.
Referenced by Compartment::printSpecies().
virtual size_t SpeciesPtrContainerVector::removeSpecies (const string & name) inline override virtual
Remove all species matching "name" from the container. The memories are freed.
Implements SpeciesPtrContainerIFace.
Definition at line 105 of file SpeciesContainer.h.
References _species.
Referenced by Compartment::removeSpecies(), and CompartmentGrid::removeSpeciesBulk().
virtual size_t SpeciesPtrContainerVector::removeSpecies (Species * species) inline override virtual
Remove all species from the container. The memory is freed.
Implements SpeciesPtrContainerIFace.
Definition at line 124 of file SpeciesContainer.h.
References _species, and species().
virtual size_t SpeciesPtrContainerVector::size () const inline override virtual
Return the number of Species in the container.
Implements SpeciesPtrContainerIFace.
Definition at line 203 of file SpeciesContainer.h.
References _species.
Referenced by CompartmentGrid::addSpeciesBulk().
vector<unique_ptr<Species> >& SpeciesPtrContainerVector::species () inline
Return a reference to the underlying vector<unique_ptr<Species>> container.
Definition at line 183 of file SpeciesContainer.h.
References _species.
Referenced by addSpeciesUnique(), Compartment::apply_impl(), Compartment::clearNeighbouringReactions(), Compartment::clearSpecies(), Reaction< M, N >::cloneImpl(), Compartment::cloneSpecies(), Compartment::generateDiffusionReactions(), Compartment::numberOfSpecies(), operator==(), and removeSpecies().
const vector<unique_ptr<Species> >& SpeciesPtrContainerVector::species () const inline
Return a const reference to the underlying vector<unique_ptr<Species>> container.
Definition at line 186 of file SpeciesContainer.h.
References _species.
Member Data Documentation
vector<unique_ptr<Species> > SpeciesPtrContainerVector::_species protected
Species pointers container.
Definition at line 67 of file SpeciesContainer.h.
Referenced by addSpecies(), addSpeciesUnique(), areAllSpeciesUnique(), clear(), findSimilarSpecies(), findSpeciesByIndex(), findSpeciesByMolecule(), findSpeciesByName(), printSpecies(), removeSpecies(), size(), and species().
The documentation for this class was generated from the following file:
M3SYM/Structure/SpeciesContainer.h