MEDYAN: FilamentInitializer Class Reference
FilamentInitializer Class Reference abstract
An interface to initialize an initial configuration of Filaments in the SubSystem.
#include <FilamentInitializer.h>
Public Member Functions
virtual ~FilamentInitializer () noexcept
Destructor.
virtual FilamentData createFilaments (Boundary *b, int numFilaments, int filamentType, int lenFilaments)=0
Returns a vector of tuples representing the Filament type and beginning and end coordinates, similar to the structure of manual parsing.
Detailed Description
An interface to initialize an initial configuration of Filaments in the SubSystem.
FilamentInitiazer class should be inherited to provide an intial scheme for filling a SubSystem with Filaments. The filaments could be completely random, directed, a certain length, etc.
Definition at line 31 of file FilamentInitializer.h.
Constructor & Destructor Documentation
~FilamentInitializer()
virtual FilamentInitializer::~FilamentInitializer () inline virtual noexcept
Destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 39 of file FilamentInitializer.h.
References createFilaments().
Member Function Documentation
createFilaments()
virtual FilamentData FilamentInitializer::createFilaments (Boundary * b, int numFilaments, int filamentType, int lenFilaments) pure virtual
Returns a vector of tuples representing the Filament type and beginning and end coordinates, similar to the structure of manual parsing.
Implemented in MTOCFilamentDist, ConnectedFilamentDist, and RandomFilamentDist.
Referenced by MTOCFilamentDist::MTOCFilamentDist(), Controller::setupSpecialStructures(), and ~FilamentInitializer().
The documentation for this class was generated from the following file:
src/FilamentInitializer.h