M3Sym: ChemGillespieImpl Class Reference
ChemGillespieImpl Class Reference
Implements a slightly optimized version of the Gillespie algorithm.
#include <ChemGillespieImpl.h>
Public Member Functions
ChemGillespieImpl ()
Ctor: Seeds the random number generator, sets global time to 0.0 and the number of reactions to 0.
ChemGillespieImpl (const ChemGillespieImpl &rhs)=delete
Copying is not allowed.
ChemGillespieImpl & operator= (ChemGillespieImpl &rhs)=delete
Assignment is not allowed.
virtual ~ChemGillespieImpl () noexcept
Dtor: The reaction network is cleared.
size_t getSize () const
Return the number of reactions in the network.
double getTime () const
Return the current global time (as defined in the Gillespie algorithm)
void resetTime ()
Sets the global time to 0.0.
void syncGlobalTime ()
Sets global time variable to ChemGillespieImpl's global time.
virtual void addReaction (ReactionBase *r)
Add ReactionBase *r to the network.
virtual void removeReaction (ReactionBase *r)
Remove ReactionBase *r from the network.
double computeTotalA ()
Unconditionally compute the total propensity associated with the network.
double generateTau (double a)
Returns a random time tau, drawn from the exponential distribution, with the propensity given by a.
double generateUniform ()
Returns a random number between 0 and 1, drawn from the uniform distribution.
virtual void initialize ()
This function iterates over all RNodeGillespie objects in the network, activating all Reaction objects and calling reset().
virtual bool run (int steps)
This method runs the Gillespie algorithm for the given number of steps.
void activateReaction (ReactionBase *r)
This method is used to track the change in the total propensity of the network as the previously passivated ReactionBase *r has become activated.
void passivateReaction (ReactionBase *r)
This method is used to track the change in the total propensity of the network as the ReactionBase *r has become passivated.
virtual void printReactions () const
Prints all RNodes in the reaction network.
Private Member Functions
bool makeStep ()
This subroutine, along with with passivateReaction() and activateReaction() implements a cached version of the Gillespie algorith.
Private Attributes
unordered_map< ReactionBase
*, unique_ptr< RNodeGillespie > > _map_rnodes
The database of RNodeGillespie objects, representing the reaction network.
mt19937 _eng
Random number generator.
exponential_distribution< double > _exp_distr
Adaptor for the exponential distribution.
uniform_real_distribution< double > _uniform_distr
double _t
global time
double _a_total
size_t _n_reacts
number of reactions in the network
Detailed Description
Implements a slightly optimized version of the Gillespie algorithm.
ChemGillespieImpl manages the Gillespie algorithm at the level of the network of reactions. Reaction objects can be added and removed from the ChemGillespieImpl instance. The propensities of all Reactions are cached, and they are recomputed only when the copy number of associated reactant species gets changed (due to the currently occurring Reaction).
Note
The algorithm used by this class relies on tracking dependent Reactions, so TRACK_DEPENDENTS must be defined. The algorithm can work both when TRACK_ZERO_COPY_N and TRACK_UPPER_COPY_N are either defined or undefined. In the former case, Reaction objects with zero propensities stop being treated as dependents until their propensities become nonzero again.
Definition at line 125 of file ChemGillespieImpl.h.
Constructor & Destructor Documentation
ChemGillespieImpl::ChemGillespieImpl () inline
Ctor: Seeds the random number generator, sets global time to 0.0 and the number of reactions to 0.
Definition at line 128 of file ChemGillespieImpl.h.
References resetTime().
ChemGillespieImpl::ChemGillespieImpl (const ChemGillespieImpl & rhs) delete
Copying is not allowed.
ChemGillespieImpl::~ChemGillespieImpl () virtual noexcept
Dtor: The reaction network is cleared.
The RNodeGillespie objects will be destructed, but Reaction objects will stay intact.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 62 of file ChemGillespieImpl.cpp.
References _map_rnodes.
Member Function Documentation
void ChemGillespieImpl::activateReaction (ReactionBase * r)
This method is used to track the change in the total propensity of the network as the previously passivated ReactionBase *r has become activated.
Definition at line 162 of file ChemGillespieImpl.cpp.
References _a_total, _map_rnodes, RNodeGillespie::getPenultStepPropensity(), RNodeGillespie::getPropensity(), and RNodeGillespie::reComputePropensity().
Referenced by RNodeGillespie::activateReaction().
void ChemGillespieImpl::addReaction (ReactionBase * r) virtual
Add ReactionBase *r to the network.
Implements ChemSimImpl.
Definition at line 145 of file ChemGillespieImpl.cpp.
References _map_rnodes, and _n_reacts.
double ChemGillespieImpl::computeTotalA ()
Unconditionally compute the total propensity associated with the network.
Definition at line 76 of file ChemGillespieImpl.cpp.
References _map_rnodes.
Referenced by initialize().
double ChemGillespieImpl::generateTau (double a)
Returns a random time tau, drawn from the exponential distribution, with the propensity given by a.
Definition at line 66 of file ChemGillespieImpl.cpp.
References _eng, and _exp_distr.
Referenced by makeStep().
double ChemGillespieImpl::generateUniform ()
Returns a random number between 0 and 1, drawn from the uniform distribution.
Definition at line 72 of file ChemGillespieImpl.cpp.
References _eng, and _uniform_distr.
Referenced by makeStep().
size_t ChemGillespieImpl::getSize () const inline
Return the number of reactions in the network.
Definition at line 146 of file ChemGillespieImpl.h.
References _map_rnodes.
double ChemGillespieImpl::getTime () const inline
Return the current global time (as defined in the Gillespie algorithm)
Definition at line 149 of file ChemGillespieImpl.h.
References _t.
void ChemGillespieImpl::initialize () virtual
This function iterates over all RNodeGillespie objects in the network, activating all Reaction objects and calling reset().
The total propentsity for the network is computed.
Note
This method needs to be called before calling run(...).
If somewhere in the middle of simulaiton initialize() is called, it will be analogous to starting the simulation from scratch, except with the Species copy numbers given at that moment in time. The global time is reset to zero again.
Implements ChemSimImpl.
Definition at line 49 of file ChemGillespieImpl.cpp.
References _a_total, _map_rnodes, computeTotalA(), and resetTime().
bool ChemGillespieImpl::makeStep () private
This subroutine, along with with passivateReaction() and activateReaction() implements a cached version of the Gillespie algorith.
Two random numbers get thrown, one for obtaining tau, the time to the next reaction event, and a uniform number to select which Reaction has occurred. Instead of computing the total propensity of the network from scratch, the cached value is being modified as Reaction events occur. Returns true if successful, and false if the heap is exchausted and there no more reactions to fire
Definition at line 87 of file ChemGillespieImpl.cpp.
References _a_total, _map_rnodes, _t, ReactionBase::dependents(), generateTau(), generateUniform(), RNodeGillespie::getPenultStepPropensity(), RNodeGillespie::getPropensity(), RNodeGillespie::getReaction(), RNodeGillespie::isPassivated(), RNodeGillespie::makeStep(), RNodeGillespie::reComputePropensity(), syncGlobalTime(), and tau().
Referenced by run().
ChemGillespieImpl& ChemGillespieImpl::operator= (ChemGillespieImpl & rhs) delete
Assignment is not allowed.
void ChemGillespieImpl::passivateReaction (ReactionBase * r)
This method is used to track the change in the total propensity of the network as the ReactionBase *r has become passivated.
Definition at line 175 of file ChemGillespieImpl.cpp.
References _a_total, _map_rnodes, RNodeGillespie::getPropensity(), RNodeGillespie::setA(), and RNodeGillespie::setPenultA().
Referenced by RNodeGillespie::passivateReaction().
void ChemGillespieImpl::printReactions () const virtual
Prints all RNodes in the reaction network.
Implements ChemSimImpl.
Definition at line 155 of file ChemGillespieImpl.cpp.
References _map_rnodes.
void ChemGillespieImpl::removeReaction (ReactionBase * r) virtual
Remove ReactionBase *r from the network.
Implements ChemSimImpl.
Definition at line 150 of file ChemGillespieImpl.cpp.
References _map_rnodes, and _n_reacts.
void ChemGillespieImpl::resetTime () inline
Sets the global time to 0.0.
Definition at line 152 of file ChemGillespieImpl.h.
References _t, and syncGlobalTime().
Referenced by ChemGillespieImpl(), and initialize().
virtual bool ChemGillespieImpl::run (int steps) inline virtual
This method runs the Gillespie algorithm for the given number of steps.
Returns
true if successful.
Implements ChemSimImpl.
Definition at line 182 of file ChemGillespieImpl.h.
References makeStep().
void ChemGillespieImpl::syncGlobalTime () inline
Sets global time variable to ChemGillespieImpl's global time.
Definition at line 155 of file ChemGillespieImpl.h.
References _t, and global_time.
Referenced by makeStep(), and resetTime().
Member Data Documentation
double ChemGillespieImpl::_a_total private
Definition at line 215 of file ChemGillespieImpl.h.
Referenced by activateReaction(), initialize(), makeStep(), and passivateReaction().
mt19937 ChemGillespieImpl::_eng private
Random number generator.
Definition at line 211 of file ChemGillespieImpl.h.
Referenced by generateTau(), and generateUniform().
exponential_distribution<double> ChemGillespieImpl::_exp_distr private
Adaptor for the exponential distribution.
Definition at line 212 of file ChemGillespieImpl.h.
Referenced by generateTau().
unordered_map<ReactionBase*, unique_ptr<RNodeGillespie> > ChemGillespieImpl::_map_rnodes private
The database of RNodeGillespie objects, representing the reaction network.
Definition at line 210 of file ChemGillespieImpl.h.
Referenced by activateReaction(), addReaction(), computeTotalA(), getSize(), initialize(), makeStep(), passivateReaction(), printReactions(), removeReaction(), and ~ChemGillespieImpl().
size_t ChemGillespieImpl::_n_reacts private
number of reactions in the network
Definition at line 216 of file ChemGillespieImpl.h.
Referenced by addReaction(), and removeReaction().
double ChemGillespieImpl::_t private
global time
Definition at line 214 of file ChemGillespieImpl.h.
Referenced by getTime(), makeStep(), resetTime(), and syncGlobalTime().
uniform_real_distribution<double> ChemGillespieImpl::_uniform_distr private
Definition at line 213 of file ChemGillespieImpl.h.
Referenced by generateUniform().
The documentation for this class was generated from the following files:
M3SYM/Chemistry/ChemGillespieImpl.h
M3SYM/Chemistry/ChemGillespieImpl.cpp