MEDYAN: MotorStall Class Reference
MotorStall Class Reference
A stall force implementation of the MotorRateChanger.
#include <RateChangerImpl.h>
Public Member Functions
MotorStall (short motorType, short filamentType, double charForce, double dutyRatio, double alpha)
virtual float numBoundHeads (float onRate, float offRate, double force, int numHeads)
Calculate the number of bound heads in the ensemble, dependent on force.
virtual float changeRate (float onRate, float offRate, double numHeads, double force)
Change the reaction rate based on an on rate, off rate, number of heads, and given force.
Protected Attributes
short _motorType
This motor type.
Private Attributes
double _F0
characteristic force
float _stepFrac = 1.0
step size of a single head relative to sim
double _dutyRatio
Constant parameters.
double _alpha
Constant parameters.
Detailed Description
A stall force implementation of the MotorRateChanger.
Used for a motor walking when under stress. Adopted from Hill et al. 1937, and Erdmann et al. 2013.
Note
- This function updates walking rates based on the Hill form:
k_eff = k_0 * (F_0 - F) / (F_0 + (F / (alpha)))
where F_0 is the characteristic force defining this stall, beta is a dimensionless parameter defining the steepness of the curve, k_0 is the walking rate under zero load, which was approximated by Erdmann et al. 2013 to be:
   k_0 = ((N_t - N_b) / N_b) * k_on
where k_on is the binding rate of a single motor, d_step is the size of a single motor step, d_total is the total step size of the ensemble in simulation, and N_t is the total number of heads.
It is noted that the true k_0 is also multipilied by a fractional step size corresponding to the step size in simulation, d_step / d_total where d_total is the total step size in simulation, based on the number of binding sites per cylinder.
N_b is the number of bound motor heads under zero load,
        N_b = p * Nt
Definition at line 204 of file RateChangerImpl.h.
Constructor & Destructor Documentation
MotorStall()
MotorStall::MotorStall (short motorType, short filamentType, double charForce, double dutyRatio, double alpha) inline
Definition at line 219 of file RateChangerImpl.h.
References SysParams::Chemistry(), GeoParams::cylinderSize, SysParams::Geometry(), ChemParams::motorStepSize, and ChemParams::numBindingSites.
Member Function Documentation
changeRate()
float MotorStall::changeRate (float onRate, float offRate, double numBoundHeads, double force) virtual
Change the reaction rate based on an on rate, off rate, number of heads, and given force.
Implements MotorRateChanger.
Definition at line 63 of file RateChangerImpl.cpp.
numBoundHeads()
virtual float MotorStall::numBoundHeads (float onRate, float offRate, double force, int numHeads) inline virtual
Calculate the number of bound heads in the ensemble, dependent on force.
Implements MotorRateChanger.
Definition at line 234 of file RateChangerImpl.h.
References BrownianRatchet::changeRate().
Member Data Documentation
_alpha
double MotorStall::_alpha private
Constant parameters.
Definition at line 214 of file RateChangerImpl.h.
_dutyRatio
double MotorStall::_dutyRatio private
Constant parameters.
Definition at line 213 of file RateChangerImpl.h.
_F0
double MotorStall::_F0 private
characteristic force
Definition at line 207 of file RateChangerImpl.h.
_motorType
short MotorRateChanger::_motorType protected inherited
This motor type.
Definition at line 63 of file RateChanger.h.
_stepFrac
float MotorStall::_stepFrac = 1.0 private
step size of a single head relative to sim
Definition at line 208 of file RateChangerImpl.h.
The documentation for this class was generated from the following files:
src/RateChangerImpl.h
src/RateChangerImpl.cpp