M3Sym: ChemSignal Class Reference
ChemSignal Class Reference
Manages callbacks for RSpecies and Reactions objects.
#include <Signaling.h>
Public Member Functions
void emitReactionSignal (ReactionBase *r) const
Broadcasts signal corresponding to ReactionBase *r.
void emitRSpeciesSignal (RSpecies *s, int delta) const
Broadcasts signal corresponding to RSpecies *s.
void addSignalingRSpecies (RSpecies *s)
Inserts a signal corresponding to RSpecies *s into the map.
void addSignalingReaction (ReactionBase *r)
Inserts a signal corresponding to ReactionBase *r into the map.
boost::signals2::connection connect (ReactionBase *r, function< void(ReactionBase *)> const &react_callback, int priority=5)
Connect the callback, react_callback to a signal corresponding to ReactionBase *r.
boost::signals2::connection connect (Species *s, function< void(RSpecies *, int)> const &RSpecies_callback, int priority=5)
Connect the callback, RSpecies_callback to a signal corresponding to RSpecies *s.
void disconnect (ReactionBase *r)
Destroy signal corresponding to Reaction r.
void disconnect (RSpecies *s)
Destroy signal corresponding to Reaction r.
Private Member Functions
unordered_map< ReactionBase
*, unique_ptr
< ReactionEventSignal >
>::const_iterator findSignal (ReactionBase *r) const
Search the map for a signal corresponding to parameter, ReactionBase *r. Throw out_of_range exception if not found.
unordered_map< RSpecies
*, unique_ptr
< RSpeciesCopyNChangedSignal >
>::const_iterator findSignal (RSpecies *s) const
Search the map for a signal corresponding to parameter, RSpecies *s. Throw out_of_range exception if not found.
void assertSignalDoesNotExist (ReactionBase *r)
Assert that a signal corresponding to ReactionBase *r does not exist or throw runtime_error.
void assertSignalDoesNotExist (RSpecies *s)
Assert that a signal corresponding to RSpecies *s does not exist or throw runtime_error.
Private Attributes
unordered_map< RSpecies
*, unique_ptr
< RSpeciesCopyNChangedSignal > > _map_RSpecies_signal
Keep track of signals corresponding to various rspecies.
unordered_map< ReactionBase
*, unique_ptr
< ReactionEventSignal > > _map_reaction_signal
Keep track of signals corresponding to various reactions.
Detailed Description
Manages callbacks for RSpecies and Reactions objects.
One ChemSignal should be instantiated per chemical network. RSpecies and Reactions that need to be monitored can be made to signal, based on the boost:signal2 library. Multiple receiving slots can be connected to signals.
Slots can be temporarily blocked or completely disconnected. Signals can be destroyed. Here is an example of usage:
 ...
 Species* A1 = ...
 ...
 ChemSignal sm;
 A1->makeSignaling(sm);
 PrintRSpecies ps;
 ...
 function<void (RSpecies *, int)> psf(ps);
 boost::signals2::shared_connection_block conn_a1(sm.connect(A1, [](RSpecies *s, int i){s->printSelf();}), true);
 // or   sm.connect(A1, print_RSpecies);
 // or  sm.connect(A1, PrintRSpecies());
 // or   boost::signals2::shared_connection_block conn_a1(sm.connect(A1,psf), false);
...
// run simulation for some time
 ...
 conn_a1.block(); // this temporarily stops slots from being called.
...
 conn_a1.disconnect(); // this permanently disconnects the slot
...
 A1->stopSignaling(sm); // this destroys the Signal itself (with associated multiple slots)
...
Definition at line 71 of file Signaling.h.
Member Function Documentation
void ChemSignal::addSignalingReaction (ReactionBase * r) inline
Inserts a signal corresponding to ReactionBase *r into the map.
Should only be called by the Reaction class.
Note
other classes should instead call void Reaction::makeSignaling(ChemSignal &sm);
Definition at line 133 of file Signaling.h.
References _map_reaction_signal, and assertSignalDoesNotExist().
void ChemSignal::addSignalingRSpecies (RSpecies * s) inline
Inserts a signal corresponding to RSpecies *s into the map.
Should only be called by the RSpecies class.
Note
other classes should instead call void RSpecies::makeSignaling(ChemSignal &sm);
Definition at line 125 of file Signaling.h.
References _map_RSpecies_signal, and assertSignalDoesNotExist().
void ChemSignal::assertSignalDoesNotExist (ReactionBase * r) inline private
Assert that a signal corresponding to ReactionBase *r does not exist or throw runtime_error.
Definition at line 95 of file Signaling.h.
References _map_reaction_signal.
Referenced by addSignalingReaction(), and addSignalingRSpecies().
void ChemSignal::assertSignalDoesNotExist (RSpecies * s) inline private
Assert that a signal corresponding to RSpecies *s does not exist or throw runtime_error.
Definition at line 102 of file Signaling.h.
References _map_RSpecies_signal.
boost::signals2::connection ChemSignal::connect (ReactionBase * r, function< void(ReactionBase *)> const & react_callback, int priority = 5) inline
Connect the callback, react_callback to a signal corresponding to ReactionBase *r.
Parameters
r - the signal will correspond to this Reaction
react_callback - a function object to be called (a slot)
priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Definition at line 143 of file Signaling.h.
References findSignal().
boost::signals2::connection ChemSignal::connect (Species * s, function< void(RSpecies *, int)> const & RSpecies_callback, int priority = 5) inline
Connect the callback, RSpecies_callback to a signal corresponding to RSpecies *s.
Parameters
s - the signal will correspond to this RSpecies
RSpecies_callback - a function object to be called (a slot). int here corresponds to delta, the change in copy number of the RSpecies (for which the signal was emitted)
priority - lower priority slots will be called first. Default is 5 Do not use priorities 1 and 2 unless absolutely essential.
Definition at line 154 of file Signaling.h.
References findSignal(), and Species::getRSpecies().
void ChemSignal::disconnect (ReactionBase * r) inline
Destroy signal corresponding to Reaction r.
Should only be used by the Reaction class.
Note
- Other classes should instead call void Reaction::stopSignaling (ChemSignal &sm);
Definition at line 162 of file Signaling.h.
References _map_reaction_signal, and findSignal().
void ChemSignal::disconnect (RSpecies * s) inline
Destroy signal corresponding to Reaction r.
Should only be used by the RSpecies class.
Note
- Other classes should instead call void RSpecies::stopSignaling (ChemSignal &sm);
Definition at line 169 of file Signaling.h.
References _map_RSpecies_signal, and findSignal().
void ChemSignal::emitReactionSignal (ReactionBase * r) const inline
Broadcasts signal corresponding to ReactionBase *r.
If the Reaction is not found, out_of_range exception will be thrown. This method is usally only called by the Gillespie-like algorithm, and not the outside code.
Definition at line 111 of file Signaling.h.
References findSignal().
void ChemSignal::emitRSpeciesSignal (RSpecies * s, int delta) const inline
Broadcasts signal corresponding to RSpecies *s.
If the Specis is not found, out_of_range exception will be thrown. This method is usally only called by the Gillespie-like algorithm, and not the outside code.
Definition at line 118 of file Signaling.h.
References findSignal().
unordered_map<ReactionBase *, unique_ptr<ReactionEventSignal> >::const_iterator ChemSignal::findSignal (ReactionBase * r) const inline private
Search the map for a signal corresponding to parameter, ReactionBase *r. Throw out_of_range exception if not found.
Definition at line 78 of file Signaling.h.
References _map_reaction_signal.
Referenced by connect(), disconnect(), emitReactionSignal(), and emitRSpeciesSignal().
unordered_map<RSpecies *, unique_ptr<RSpeciesCopyNChangedSignal> >::const_iterator ChemSignal::findSignal (RSpecies * s) const inline private
Search the map for a signal corresponding to parameter, RSpecies *s. Throw out_of_range exception if not found.
Definition at line 87 of file Signaling.h.
References _map_RSpecies_signal.
Member Data Documentation
unordered_map<ReactionBase *, unique_ptr<ReactionEventSignal> > ChemSignal::_map_reaction_signal private
Keep track of signals corresponding to various reactions.
Definition at line 74 of file Signaling.h.
Referenced by addSignalingReaction(), assertSignalDoesNotExist(), disconnect(), and findSignal().
unordered_map<RSpecies *, unique_ptr<RSpeciesCopyNChangedSignal> > ChemSignal::_map_RSpecies_signal private
Keep track of signals corresponding to various rspecies.
Definition at line 73 of file Signaling.h.
Referenced by addSignalingRSpecies(), assertSignalDoesNotExist(), disconnect(), and findSignal().
The documentation for this class was generated from the following file:
M3SYM/Signaling.h