MEDYAN: RNodeNRM Class Reference
RNodeNRM Class Reference
Reaction Node for the Next Reaction Method.
#include <ChemNRMImpl.h>
Public Member Functions
RNodeNRM (ReactionBase *r, ChemNRMImpl &chem_nrm)
Ctor:
RNodeNRM (const RNodeNRM &rhs)=delete
Copying is not allowed.
RNodeNRM & operator= (RNodeNRM &rhs)=delete
Assignment is not allowed.
virtual ~RNodeNRM () noexcept
Dtor: 1) Erases the corresponding PQNode element in the heap via the handle; 2) The RNode pointer of the tracked Reaction object is set to nullptr.
void generateNewRandTau ()
This methods recomputes the reaction propensity based on current coefficients and the rate, and then obtains a corresponding new tau drawn from an exponential distribution.
void generateNewTau ()
This method reuses a previous tau to generate a new tau based on a change in reaction propensity.
ReactionBase * getReaction () const
Returns a pointer to the Reaction which corresponds to this RNodeNRM.
void updateHeap ()
The heap is updated only with respect to the specific PQNode element which presumably was modified (e.g.
double getTau () const
Returns the tau from the the associated PQNode element.
void setTau (double tau)
Sets the tau of the the associated PQNode element. Does not update the heap.
handle_t & getHandle ()
Returns a handle to the associated PQNode element, which can be used to access tau, for example.
double getPropensity () const
Return the currently stored propensity, "a", for this Reaction.
double reComputePropensity ()
(Re)Compute and return the propensity associated with this Reaction.
int getProductOfReactants ()
Compute and return the product of reactant copy numbers.
void makeStep ()
This method calls the corresponding Reaction::makeStep() method of the underyling Reaction object.
virtual void activateReaction ()
When this method is called, a new tau is computed and the corresponding PQNode element is updated in the heap.
virtual void passivateReaction ()
When this method is called, reaction's tau is set to infinity, the propensity is set to 0, and the corresponding PQNode element is updated in the heap.
bool isPassivated () const
Return true if the Reaction is currently passivated.
void printSelf () const
Print information about this RNodeNRM such as tau, a and the Reaction which this RNodeNRM tracks.
void printDependents () const
Print the RNode objects which are dependents of this RNode (via the tracked Reaction object dependencies)
Private Attributes
ChemNRMImpl & _chem_nrm
A reference to the ChemNRMImpl which containts the heap, random number generators, etc.
handle_t _handle
The handle to the associated PQNode element in the heap.
ReactionBase * _react
The pointer to the associated Reaction object.
double _a
The propensity associated with the Reaction.
Detailed Description
Reaction Node for the Next Reaction Method.
RNodeNRM manages a single chemical reaction within the NRM algorithm. It has a pointer to the PQ element containing the Reaction via a handle_t object (and hence can modify both the corresponding PQNode, such as PQNode's tau or the underlying Reaction instance). RNodeNRM can recompute tau if needed and has auxiliary method for computing reaction's propensity. When the propensity drops to zero, the RNodeNRM can execute the passivateReaction() method. Alternatively, passivated RNodeNRM can be activated via activateReaction(). The main part of the NRM algoritm is implemented in the makeStep() method.
Definition at line 124 of file ChemNRMImpl.h.
Constructor & Destructor Documentation
RNodeNRM() [1/2]
RNodeNRM::RNodeNRM (ReactionBase * r, ChemNRMImpl & chem_nrm)
Ctor:
Parameters
*r is the Reaction object corresponding to this RNodeNRM
&chem_nrm is a refernce to ChemNRMImpl object, which does the overall management of the NRM scheme (e.g. it gives acces to the heap itself, random distribution generators, etc.)
Definition at line 58 of file ChemNRMImpl.cpp.
References _a, _chem_nrm, _handle, _react, ReactionBase::computePropensity(), ChemNRMImpl::getHeap(), and ReactionBase::setRnode().
RNodeNRM() [2/2]
RNodeNRM::RNodeNRM (const RNodeNRM & rhs) delete
Copying is not allowed.
~RNodeNRM()
RNodeNRM::~RNodeNRM () virtual noexcept
Dtor: 1) Erases the corresponding PQNode element in the heap via the handle; 2) The RNode pointer of the tracked Reaction object is set to nullptr.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 66 of file ChemNRMImpl.cpp.
References _chem_nrm, _handle, _react, ChemNRMImpl::getHeap(), and ReactionBase::setRnode().
Member Function Documentation
activateReaction()
void RNodeNRM::activateReaction () virtual
When this method is called, a new tau is computed and the corresponding PQNode element is updated in the heap.
Note
This method does not activate the Reaction itself, but instead only deals with the activation process related to the corresponding PQNode element.
Implements RNode.
Definition at line 109 of file ChemNRMImpl.cpp.
References generateNewRandTau(), and updateHeap().
generateNewRandTau()
void RNodeNRM::generateNewRandTau ()
This methods recomputes the reaction propensity based on current coefficients and the rate, and then obtains a corresponding new tau drawn from an exponential distribution.
Note
This methods modifies tau which is stored in the associated PQNode object. However, it does not update the heap - this needs to be done seprately.
Definition at line 94 of file ChemNRMImpl.cpp.
References _a, _chem_nrm, ChemNRMImpl::generateTau(), ChemNRMImpl::getTime(), reComputePropensity(), and setTau().
Referenced by activateReaction(), and ChemNRMImpl::makeStep().
generateNewTau()
void RNodeNRM::generateNewTau ()
This method reuses a previous tau to generate a new tau based on a change in reaction propensity.
Note
This methods modifies tau which is stored in the associated PQNode object. However, it does not update the heap - this needs to be done seperately.
getHandle()
handle_t& RNodeNRM::getHandle () inline
Returns a handle to the associated PQNode element, which can be used to access tau, for example.
Definition at line 175 of file ChemNRMImpl.h.
getProductOfReactants()
int RNodeNRM::getProductOfReactants () inline
Compute and return the product of reactant copy numbers.
This method can be used to quickly check whether this reaction needs to be passivated, if the returned result is zero.
Definition at line 188 of file ChemNRMImpl.h.
getPropensity()
double RNodeNRM::getPropensity () const inline
Return the currently stored propensity, "a", for this Reaction.
Note
The propensity is not recomputed in this method, so it potentially can be out of sync.
Definition at line 180 of file ChemNRMImpl.h.
Referenced by ChemNRMImpl::makeStep().
getReaction()
ReactionBase* RNodeNRM::getReaction () const inline
Returns a pointer to the Reaction which corresponds to this RNodeNRM.
Definition at line 161 of file ChemNRMImpl.h.
Referenced by ChemNRMImpl::makeStep().
getTau()
double RNodeNRM::getTau () const inline
Returns the tau from the the associated PQNode element.
Definition at line 168 of file ChemNRMImpl.h.
Referenced by ChemNRMImpl::makeStep(), and printSelf().
isPassivated()
bool RNodeNRM::isPassivated () const inline virtual
Return true if the Reaction is currently passivated.
Implements RNode.
Definition at line 207 of file ChemNRMImpl.h.
Referenced by ChemNRMImpl::makeStep().
makeStep()
void RNodeNRM::makeStep () inline
This method calls the corresponding Reaction::makeStep() method of the underyling Reaction object.
Definition at line 192 of file ChemNRMImpl.h.
Referenced by ChemNRMImpl::makeStep().
operator=()
RNodeNRM& RNodeNRM::operator= (RNodeNRM & rhs) delete
Assignment is not allowed.
passivateReaction()
void RNodeNRM::passivateReaction () virtual
When this method is called, reaction's tau is set to infinity, the propensity is set to 0, and the corresponding PQNode element is updated in the heap.
Note
This method does not passivate the Reaction itself, but instead only deals with the activation process related to the corresponding PQNode element.
Implements RNode.
Definition at line 114 of file ChemNRMImpl.cpp.
References _a, setTau(), tau(), and updateHeap().
printDependents()
void RNodeNRM::printDependents () const
Print the RNode objects which are dependents of this RNode (via the tracked Reaction object dependencies)
Definition at line 78 of file ChemNRMImpl.cpp.
References _react, ReactionBase::dependents(), and printSelf().
printSelf()
void RNodeNRM::printSelf () const
Print information about this RNodeNRM such as tau, a and the Reaction which this RNodeNRM tracks.
Definition at line 72 of file ChemNRMImpl.cpp.
References _a, and getTau().
Referenced by ChemNRMImpl::makeStep(), and printDependents().
reComputePropensity()
double RNodeNRM::reComputePropensity () inline
(Re)Compute and return the propensity associated with this Reaction.
Definition at line 183 of file ChemNRMImpl.h.
Referenced by generateNewRandTau(), and ChemNRMImpl::makeStep().
setTau()
void RNodeNRM::setTau (double tau) inline
Sets the tau of the the associated PQNode element. Does not update the heap.
Definition at line 171 of file ChemNRMImpl.h.
References tau().
Referenced by generateNewRandTau(), ChemNRMImpl::makeStep(), and passivateReaction().
updateHeap()
void RNodeNRM::updateHeap ()
The heap is updated only with respect to the specific PQNode element which presumably was modified (e.g.
via generateNewRandTau()).
Definition at line 89 of file ChemNRMImpl.cpp.
References _chem_nrm, _handle, and ChemNRMImpl::getHeap().
Referenced by activateReaction(), ChemNRMImpl::makeStep(), and passivateReaction().
Member Data Documentation
_a
double RNodeNRM::_a private
The propensity associated with the Reaction.
It may be outdated and may need to be recomputed if needed.
Definition at line 231 of file ChemNRMImpl.h.
Referenced by generateNewRandTau(), passivateReaction(), printSelf(), and RNodeNRM().
_chem_nrm
ChemNRMImpl& RNodeNRM::_chem_nrm private
A reference to the ChemNRMImpl which containts the heap, random number generators, etc.
Definition at line 226 of file ChemNRMImpl.h.
Referenced by generateNewRandTau(), RNodeNRM(), updateHeap(), and ~RNodeNRM().
_handle
handle_t RNodeNRM::_handle private
The handle to the associated PQNode element in the heap.
Definition at line 228 of file ChemNRMImpl.h.
Referenced by RNodeNRM(), updateHeap(), and ~RNodeNRM().
_react
ReactionBase* RNodeNRM::_react private
The pointer to the associated Reaction object.
The corresponding memory is not managed by RNodeNRM.
Definition at line 229 of file ChemNRMImpl.h.
Referenced by printDependents(), RNodeNRM(), and ~RNodeNRM().
The documentation for this class was generated from the following files:
src/Chemistry/ChemNRMImpl.h
src/Chemistry/ChemNRMImpl.cpp