MEDYAN: FilamentStretchingHarmonic Class Reference
FilamentStretchingHarmonic Class Reference
A harmonic potential used by the FilamentStretching and MTOCAttachment template.
#include <FilamentStretchingHarmonic.h>
Public Member Functions
double energy (Bead *, Bead *, double, double)
double energy (Bead *, Bead *, double, double, double)
void forces (Bead *, Bead *, double, double)
void forcesAux (Bead *, Bead *, double, double)
Detailed Description
A harmonic potential used by the FilamentStretching and MTOCAttachment template.
Definition at line 23 of file FilamentStretchingHarmonic.h.
Member Function Documentation
energy() [1/2]
double FilamentStretchingHarmonic::energy (Bead * b1, Bead * b2, double kStretch, double eqLength)
Definition at line 22 of file FilamentStretchingHarmonic.cpp.
References Bead::coordinate, and mathfunc::twoPointDistance().
energy() [2/2]
double FilamentStretchingHarmonic::energy (Bead * b1, Bead * b2, double kStretch, double eqLength, double d)
Definition at line 30 of file FilamentStretchingHarmonic.cpp.
References Bead::coordinate, Bead::force, and mathfunc::twoPointDistanceStretched().
forces()
void FilamentStretchingHarmonic::forces (Bead * b1, Bead * b2, double kStretch, double eqLength)
Definition at line 39 of file FilamentStretchingHarmonic.cpp.
References Bead::coordinate, Bead::force, and mathfunc::twoPointDistance().
forcesAux()
void FilamentStretchingHarmonic::forcesAux (Bead * b1, Bead * b2, double kStretch, double eqLength)
Definition at line 58 of file FilamentStretchingHarmonic.cpp.
References Bead::coordinate, Bead::forceAux, and mathfunc::twoPointDistance().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Filament/FilamentStretchingHarmonic.h
src/Mechanics/ForceField/Filament/FilamentStretchingHarmonic.cpp