M3Sym: ChemNRMImpl Class Reference
ChemNRMImpl Class Reference
The chemical Next Reaction Method Implementation.
#include <ChemNRMImpl.h>
Public Member Functions
ChemNRMImpl ()
Ctor: Seeds the random number generator, sets global time to 0.0 and the number of reactions to 0.
ChemNRMImpl (const ChemNRMImpl &rhs)=delete
Copying is not allowed.
ChemNRMImpl & operator= (ChemNRMImpl &rhs)=delete
Assignment is not allowed.
virtual ~ChemNRMImpl ()
Dtor: The reaction network is cleared.
size_t getSize () const
Return the number of reactions in the network.
double getTime () const
Return the current global time (as defined in the NRM algorithm)
void resetTime ()
Sets global time to 0.0.
void syncGlobalTime ()
Sets global time variable to ChemNRMImpl's global time.
boost_heap * getHeap ()
Return a pointer to the heap.
virtual void addReaction (ReactionBase *r)
Add Reaction *r to the network.
virtual void removeReaction (ReactionBase *r)
Remove Reaction *r from the network.
double generateTau (double a)
A pure function (without sideeffects), which returns a random time tau, drawn from the exponential distribution, with the propensity given by a.
virtual void initialize ()
This function iterates over all RNodeNRM objects in the network, generating new tau-s for each case and subsequently updating the heap.
virtual bool run (int steps)
This method runs the NRM algorithm for the given number of steps.
virtual void printReactions () const
Prints all RNodes in the reaction network.
Private Member Functions
bool makeStep ()
This is a somewhat complex subroutine which implements the main part of the Gibson-Bruck NRM algoritm.
Private Attributes
unordered_map< ReactionBase
*, unique_ptr< RNodeNRM > > _map_rnodes
The database of RNodeNRM objects, representing the reaction network.
boost_heap _heap
A priority queue for the NRM algorithm, containing PQNode elements.
mt19937 _eng
Random number generator.
exponential_distribution< double > _exp_distr
Adaptor for the exponential distribution.
double _t
global time
size_t _n_reacts
number of reactions in the network
Detailed Description
The chemical Next Reaction Method Implementation.
ChemNRMImpl manages the NRM algorithm at the level of the network of reactions. In particular, this class contains the NRM heap and the exponential random number generator. Reaction objects can be added and removed from the ChemNRMImpl instance.
Definition at line 211 of file ChemNRMImpl.h.
Constructor & Destructor Documentation
ChemNRMImpl::ChemNRMImpl () inline
Ctor: Seeds the random number generator, sets global time to 0.0 and the number of reactions to 0.
Definition at line 214 of file ChemNRMImpl.h.
References resetTime().
ChemNRMImpl::ChemNRMImpl (const ChemNRMImpl & rhs) delete
Copying is not allowed.
ChemNRMImpl::~ChemNRMImpl () virtual
Dtor: The reaction network is cleared.
The RNodeNRM objects will be destructed, but Reaction objects will stay intact. When the RNodeNRM objects are destructed, they in turn destruct the corresponding PQNode element, setting the RNode pointer of the Reaction object to null. At the end, the heap itself will go out of scope.
Definition at line 130 of file ChemNRMImpl.cpp.
References _map_rnodes.
Member Function Documentation
void ChemNRMImpl::addReaction (ReactionBase * r) virtual
Add Reaction *r to the network.
Implements ChemSimImpl.
Definition at line 198 of file ChemNRMImpl.cpp.
References _map_rnodes, and _n_reacts.
double ChemNRMImpl::generateTau (double a)
A pure function (without sideeffects), which returns a random time tau, drawn from the exponential distribution, with the propensity given by a.
Definition at line 134 of file ChemNRMImpl.cpp.
References _eng, and _exp_distr.
Referenced by RNodeNRM::generateNewRandTau().
boost_heap* ChemNRMImpl::getHeap () inline
Return a pointer to the heap.
Definition at line 243 of file ChemNRMImpl.h.
References _heap.
Referenced by RNodeNRM::RNodeNRM(), RNodeNRM::updateHeap(), and RNodeNRM::~RNodeNRM().
size_t ChemNRMImpl::getSize () const inline
Return the number of reactions in the network.
Definition at line 231 of file ChemNRMImpl.h.
References _n_reacts.
double ChemNRMImpl::getTime () const inline
Return the current global time (as defined in the NRM algorithm)
Definition at line 234 of file ChemNRMImpl.h.
References _t.
Referenced by RNodeNRM::generateNewRandTau().
void ChemNRMImpl::initialize () virtual
This function iterates over all RNodeNRM objects in the network, generating new tau-s for each case and subsequently updating the heap.
It needs to be called before calling run(...).
Note
If somewhere in the middle of simulaiton initialize() is called, it will be analogous to starting the simulation from scratch, except with the Species copy numbers given at that moment in time. The global time is reset to zero again.
Implements ChemSimImpl.
Definition at line 121 of file ChemNRMImpl.cpp.
References _map_rnodes, and resetTime().
bool ChemNRMImpl::makeStep () private
This is a somewhat complex subroutine which implements the main part of the Gibson-Bruck NRM algoritm.
See the implementation for details. After this method returns, roughly the following will have happened: 1) The Reaction corresponding to the lowest tau RNodeNRM is executed and the corresponding Species copy numbers are changed 2) A new tau is computed from this Reaction and the corresponding PQNode element is updated in the heap 3) The other affected Reaction objects are found, their taus are recomputed and corresponding PQNode elements are updated in the heap. 4) For the Reaction and associated Species signals are emitted, if these objects broadcast signals upon change. Returns true if successful, and false if the heap is exchausted and there no more reactions to fire
Definition at line 140 of file ChemNRMImpl.cpp.
References _heap, _t, ReactionBase::dependents(), RNodeNRM::generateNewRandTau(), RNodeNRM::getPropensity(), RNodeNRM::getReaction(), RNodeNRM::getTau(), RNodeNRM::isPassivated(), RNodeNRM::makeStep(), RNodeNRM::reComputePropensity(), RNodeNRM::setTau(), syncGlobalTime(), and RNodeNRM::updateHeap().
Referenced by run().
ChemNRMImpl& ChemNRMImpl::operator= (ChemNRMImpl & rhs) delete
Assignment is not allowed.
void ChemNRMImpl::printReactions () const virtual
Prints all RNodes in the reaction network.
Implements ChemSimImpl.
Definition at line 208 of file ChemNRMImpl.cpp.
References _map_rnodes.
void ChemNRMImpl::removeReaction (ReactionBase * r) virtual
Remove Reaction *r from the network.
Implements ChemSimImpl.
Definition at line 203 of file ChemNRMImpl.cpp.
References _map_rnodes, and _n_reacts.
void ChemNRMImpl::resetTime () inline
Sets global time to 0.0.
Definition at line 237 of file ChemNRMImpl.h.
References _t, and syncGlobalTime().
Referenced by ChemNRMImpl(), and initialize().
virtual bool ChemNRMImpl::run (int steps) inline virtual
This method runs the NRM algorithm for the given number of steps.
Implements ChemSimImpl.
Definition at line 263 of file ChemNRMImpl.h.
References makeStep().
void ChemNRMImpl::syncGlobalTime () inline
Sets global time variable to ChemNRMImpl's global time.
Definition at line 240 of file ChemNRMImpl.h.
References _t, and global_time.
Referenced by makeStep(), and resetTime().
Member Data Documentation
mt19937 ChemNRMImpl::_eng private
Random number generator.
Definition at line 288 of file ChemNRMImpl.h.
Referenced by generateTau().
exponential_distribution<double> ChemNRMImpl::_exp_distr private
Adaptor for the exponential distribution.
Definition at line 289 of file ChemNRMImpl.h.
Referenced by generateTau().
boost_heap ChemNRMImpl::_heap private
A priority queue for the NRM algorithm, containing PQNode elements.
Definition at line 287 of file ChemNRMImpl.h.
Referenced by getHeap(), and makeStep().
unordered_map<ReactionBase*, unique_ptr<RNodeNRM> > ChemNRMImpl::_map_rnodes private
The database of RNodeNRM objects, representing the reaction network.
Definition at line 286 of file ChemNRMImpl.h.
Referenced by addReaction(), initialize(), printReactions(), removeReaction(), and ~ChemNRMImpl().
size_t ChemNRMImpl::_n_reacts private
number of reactions in the network
Definition at line 291 of file ChemNRMImpl.h.
Referenced by addReaction(), getSize(), and removeReaction().
double ChemNRMImpl::_t private
global time
Definition at line 290 of file ChemNRMImpl.h.
Referenced by getTime(), makeStep(), resetTime(), and syncGlobalTime().
The documentation for this class was generated from the following files:
M3SYM/Chemistry/ChemNRMImpl.h
M3SYM/Chemistry/ChemNRMImpl.cpp