MEDYAN: BranchingStretching< BStretchingInteractionType > Class Template Reference
BranchingStretching< BStretchingInteractionType > Class Template Reference
Represents an interaction fixing a Cylinder anchored by a BranchingPoint on the parent.
#include <BranchingStretching.h>
Public Member Functions
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
BranchingPoint * _branchingCulprit = nullptr
The branching point in the case of an error.
Private Attributes
BStretchingInteractionType _FFType
Detailed Description
template<class BStretchingInteractionType>
class BranchingStretching< BStretchingInteractionType >
Represents an interaction fixing a Cylinder anchored by a BranchingPoint on the parent.
Definition at line 26 of file BranchingStretching.h.
Member Function Documentation
computeEnergy()
template<class BStretchingInteractionType > template double BranchingStretching< BStretchingInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BranchingInteractions.
Definition at line 23 of file BranchingStretching.cpp.
References BranchingPoint::getBranchingPoints(), and Bead::getPosition().
Referenced by BranchingStretching< BStretchingInteractionType >::computeForcesAux().
computeForces()
template<class BStretchingInteractionType > template void BranchingStretching< BStretchingInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements BranchingInteractions.
Definition at line 58 of file BranchingStretching.cpp.
References BranchingPoint::getBranchingPoints(), and Bead::getPosition().
Referenced by BranchingStretching< BStretchingInteractionType >::computeForcesAux().
computeForcesAux()
template<class BStretchingInteractionType > template void BranchingStretching< BStretchingInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements BranchingInteractions.
Definition at line 76 of file BranchingStretching.cpp.
References BranchingStretching< BStretchingInteractionType >::computeEnergy(), BranchingStretching< BStretchingInteractionType >::computeForces(), BranchingPoint::getBranchingPoints(), and Bead::getPosition().
getName()
template<class BStretchingInteractionType > virtual const string BranchingStretching< BStretchingInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BranchingInteractions.
Definition at line 36 of file BranchingStretching.h.
Member Data Documentation
_branchingCulprit
BranchingPoint* BranchingInteractions::_branchingCulprit = nullptr protected inherited
The branching point in the case of an error.
Definition at line 31 of file BranchingInteractions.h.
Referenced by BranchingFF::whoIsCulprit().
_FFType
template<class BStretchingInteractionType > BStretchingInteractionType BranchingStretching< BStretchingInteractionType >::_FFType private
Definition at line 29 of file BranchingStretching.h.
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Branching/BranchingStretching.h
src/Mechanics/ForceField/Branching/BranchingStretching.cpp