MEDYAN: NeighborList Class Reference
NeighborList Class Reference abstract
To hold an external neighbor list of general type.
#include <NeighborList.h>
Public Member Functions
NeighborList (float rMax=0.0, float rMin=0.0)
Constructor and destructor.
virtual ~NeighborList () noexcept
Destructor.
virtual void addNeighbor (Neighbor *n)=0
Add neighbor.
virtual void removeNeighbor (Neighbor *n)=0
Remove a neighbor if possible.
virtual void addDynamicNeighbor (DynamicNeighbor *n)=0
Add a dynamic neighbor to the system.
virtual void removeDynamicNeighbor (DynamicNeighbor *n)=0
Remove a dynamic neighbor from the system.
virtual void reset ()=0
Re-initialize the neighborlist.
Protected Attributes
float _rMax
max distance cutoff
float _rMin
min distance cutoff
Detailed Description
To hold an external neighbor list of general type.
This class is used to hold any neighbor list. Contains a map of neighbors as well as min and max cutoffs for generation of the list. This class is abstract and must be implemented by writing functionality to add and update a neighbor.
The neighbor list contains a function to reset, which uses the databases to clear and update the list.
Definition at line 33 of file NeighborList.h.
Constructor & Destructor Documentation
NeighborList()
NeighborList::NeighborList (float rMax = 0.0, float rMin = 0.0) inline
Constructor and destructor.
Definition at line 41 of file NeighborList.h.
~NeighborList()
virtual NeighborList::~NeighborList () inline virtual noexcept
Destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 48 of file NeighborList.h.
References addDynamicNeighbor(), addNeighbor(), removeDynamicNeighbor(), removeNeighbor(), and reset().
Member Function Documentation
addDynamicNeighbor()
virtual void NeighborList::addDynamicNeighbor (DynamicNeighbor * n) pure virtual
Add a dynamic neighbor to the system.
For BoundaryElementNeighborList list, this will be Bead. For CylinderNeighborList, all elements in neighbors list are dynamic.
Implemented in BubbleCylinderNL, BubbleBubbleNL, BoundaryBubbleNL, BoundaryCylinderNL, and CylinderCylinderNL.
Referenced by ~NeighborList().
addNeighbor()
virtual void NeighborList::addNeighbor (Neighbor * n) pure virtual
Add neighbor.
Implemented in BubbleCylinderNL, BubbleBubbleNL, BoundaryBubbleNL, BoundaryCylinderNL, and CylinderCylinderNL.
Referenced by ~NeighborList().
removeDynamicNeighbor()
virtual void NeighborList::removeDynamicNeighbor (DynamicNeighbor * n) pure virtual
Remove a dynamic neighbor from the system.
For BoundaryElementNeighborList list, this will be Bead. For CylinderNeighborList, all elements in neighbors list are dynamic.
Implemented in BubbleCylinderNL, BubbleBubbleNL, BoundaryBubbleNL, BoundaryCylinderNL, and CylinderCylinderNL.
Referenced by ~NeighborList().
removeNeighbor()
virtual void NeighborList::removeNeighbor (Neighbor * n) pure virtual
Remove a neighbor if possible.
Implemented in BubbleCylinderNL, BubbleBubbleNL, BoundaryBubbleNL, BoundaryCylinderNL, and CylinderCylinderNL.
Referenced by ~NeighborList().
reset()
virtual void NeighborList::reset () pure virtual
Re-initialize the neighborlist.
Implemented in BubbleCylinderNL, BubbleBubbleNL, BoundaryBubbleNL, BoundaryCylinderNL, and CylinderCylinderNL.
Referenced by ~NeighborList().
Member Data Documentation
_rMax
float NeighborList::_rMax protected
max distance cutoff
Definition at line 36 of file NeighborList.h.
_rMin
float NeighborList::_rMin protected
min distance cutoff
Definition at line 37 of file NeighborList.h.
The documentation for this class was generated from the following file:
src/Structure/NeighborList.h