MEDYAN: TypeVisitor< ComponentType > Class Template Reference
TypeVisitor< ComponentType > Class Template Reference abstract
#include <Visitor.h>
Public Member Functions
bool visit (Component *c)
When this conditional Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
Protected Member Functions
virtual bool predImpl (Component *c) override
Return true if the Component *c satisfies the desired predicate.
virtual bool visitImpl (Component *c)=0
When this Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
Detailed Description
template<class ComponentType>
class TypeVisitor< ComponentType >
Definition at line 90 of file Visitor.h.
Member Function Documentation
predImpl()
template<class ComponentType > virtual bool TypeVisitor< ComponentType >::predImpl (Component * c) inline override protected virtual
Return true if the Component *c satisfies the desired predicate.
Reimplemented from Visitor.
Definition at line 92 of file Visitor.h.
visit()
bool Visitor::visit (Component * c) inline inherited
When this conditional Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
If v->visit(c) returns a false value, then the further propagation of the tree is terminated.
Definition at line 41 of file Visitor.h.
References Visitor::predImpl(), and Visitor::visitImpl().
Referenced by Component::apply(), and Composite::apply().
visitImpl()
virtual bool Visitor::visitImpl (Component * c) protected pure virtual inherited
When this Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Implemented in VisitorLambda.
Referenced by Visitor::visit(), SpeciesVisitor::visit(), ReactionVisitor::visit(), ReactionVisitor::~ReactionVisitor(), SpeciesVisitor::~SpeciesVisitor(), and Visitor::~Visitor().
The documentation for this class was generated from the following file:
src/Visitor.h