MEDYAN: Bubble Class Reference
Bubble Class Reference
Represents a dummy point potential that is involved in mechanical equilibration.
#include <Bubble.h>
Public Member Functions
Bubble (SubSystem *ps, vector< double > coordinates, short type)
Main constructor, sets up bead and other properties.
void setAsMTOC ()
bool isMTOC ()
virtual void printSelf ()
Print bubble information.
virtual void updatePosition ()
Update bubble position.
virtual bool apply (Visitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
virtual bool apply (SpeciesVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v) override
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool isComposite () const override
Returns true.
virtual string getFullName () const override
Returns the full name of this node.
virtual void addChild (unique_ptr< Component > &&child)
Adds a Component child to this Composite node.
virtual void removeChild (Component *child)
Remove *child from this node's children.
virtual size_t numberOfChildren () const override
Returns the number of immediate children of this node.
virtual size_t numberOfSpecies () const override
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t countDescendents () const override
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const override
Returns the number of Species being managed by this node and its descendent nodes.
virtual size_t numberOfReactions () const override
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual size_t countReactions () const override
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
virtual vector< unique_ptr< Component > > & children ()
Returns a reference to the container of Component children of this node.
virtual const vector< unique_ptr< Component > > & children () const
Returns a const reference to the container of Component children of this node.
virtual Component * children (size_t i)
Returns a pointer to the i-th Component child of this node.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
double getRadius ()
Getters.
double getRepulsionConst ()
Getters.
double getScreeningLength ()
Getters.
Bead * getBead ()
Getters.
int getID ()
Getters.
virtual int getType ()
Getters.
virtual void addToSubSystem ()
SubSystem management, inherited from Trackable.
virtual void removeFromSubSystem ()
SubSystem management, inherited from Trackable.
Static Public Member Functions
static const vector< Bubble * > & getBubbles ()
Get all instances of this class from the SubSystem.
static int numBubbles ()
Get the number of cylinders in this system.
Public Attributes
vector< double > coordinate
Current coordinates of bubble, Updated with updatePosition()
Protected Attributes
bool _movable
Object type.
bool _reactable
Object type.
bool _dneighbor
Object type.
bool _neighbor
Object type.
Static Protected Attributes
static SubSystem * _subSystem = 0
A subsystem pointer for every trackable.
Private Attributes
Bead * _bead
The bead representing the center of the bubble.
SubSystem * _ps
The subsystem this bubble is in.
short _type
The type of bubble.
double _radius
The radius of this bubble.
double _kRepuls
Repulsion constant for bubble-bubble and bubble-cylinder interactions.
double _screenLength
Screening length for a repulsive potential.
int _ID
Identifier.
bool _isMTOC = false
If representing a MTOC.
Static Private Attributes
static Database< Bubble * > _bubbles
Collection in SubSystem.
Detailed Description
Represents a dummy point potential that is involved in mechanical equilibration.
This object has no chemical reactions or properties associated with it.
Bubbles are artificial objects in minimization to physically represent hard spheres. They contain coordinates as well as force constants for any number of potentials. A bubble contains a bead which is the center of the bubble, as well as a radius representing the physical size of the bubble.
Definition at line 39 of file Bubble.h.
Constructor & Destructor Documentation
Bubble()
Bubble::Bubble (SubSystem * ps, vector< double > coordinates, short type)
Main constructor, sets up bead and other properties.
Definition at line 21 of file Bubble.cpp.
References _bead, _kRepuls, _ps, _radius, _screenLength, _type, SubSystem::addTrackable(), MechParams::BubbleK, MechParams::BubbleRadius, MechParams::BubbleScreenLength, and SysParams::Mechanics().
Member Function Documentation
addChild()
virtual void Composite::addChild (unique_ptr< Component > && child) inline virtual inherited
Adds a Component child to this Composite node.
Parameters
child - is a unique_ptr<Component>, hence, this node takes the memory ownership of the corresponding child pointer.
Note
the rvalue semantics - the unique_ptr<...> cannot be copied, but only can be moved
Definition at line 81 of file Composite.h.
Referenced by Bead::Bead(), CompartmentGrid::CompartmentGrid(), Cylinder::Cylinder(), MTOC::setBubble(), and Filament::sever().
addToSubSystem()
virtual void Bubble::addToSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 84 of file Bubble.h.
Referenced by isMTOC().
apply() [1/3]
bool Composite::apply (Visitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children.
Reimplemented from Component.
Definition at line 18 of file Composite.cpp.
References Composite::children(), and Visitor::visit().
Referenced by Composite::~Composite().
apply() [2/3]
bool Composite::apply (SpeciesVisitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented from Component.
Definition at line 31 of file Composite.cpp.
References Component::apply_impl(), and Composite::children().
apply() [3/3]
bool Composite::apply (ReactionVisitor & v) override virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented from Component.
Definition at line 43 of file Composite.cpp.
References Component::apply_impl(), and Composite::children().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
children() [1/3]
virtual vector<unique_ptr<Component> >& Composite::children () inline virtual inherited
Returns a reference to the container of Component children of this node.
Definition at line 145 of file Composite.h.
References Composite::_children.
Referenced by Composite::apply(), Composite::countDescendents(), Composite::countReactions(), Composite::countSpecies(), CompartmentGrid::getCompartment(), CompartmentGrid::getCompartments(), Composite::numberOfChildren(), and CompartmentGrid::printSelf().
children() [2/3]
virtual const vector<unique_ptr<Component> >& Composite::children () const inline virtual inherited
Returns a const reference to the container of Component children of this node.
Definition at line 148 of file Composite.h.
References Composite::_children.
children() [3/3]
virtual Component* Composite::children (size_t i) inline virtual inherited
Returns a pointer to the i-th Component child of this node.
Definition at line 151 of file Composite.h.
countDescendents()
virtual size_t Composite::countDescendents () const inline override virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented from Component.
Definition at line 110 of file Composite.h.
References Composite::children(), Composite::numberOfChildren(), and std::sum().
countReactions()
virtual size_t Composite::countReactions () const inline override virtual inherited
Returns the number of ReactionBase objects being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 135 of file Composite.h.
References Composite::children(), Component::isReactionsContainer(), Composite::numberOfReactions(), and std::sum().
countSpecies()
virtual size_t Composite::countSpecies () const inline override virtual inherited
Returns the number of Species being managed by this node and its descendent nodes.
Reimplemented from Component.
Definition at line 120 of file Composite.h.
References Composite::children(), Component::isSpeciesContainer(), Composite::numberOfSpecies(), and std::sum().
Referenced by Filament::getTurnoverTimes(), and Chemistry::print().
getBead()
Bead* Bubble::getBead () inline
Getters.
Definition at line 70 of file Bubble.h.
References _bead.
getBubbles()
static const vector<Bubble*>& Bubble::getBubbles () inline static
Get all instances of this class from the SubSystem.
Definition at line 89 of file Bubble.h.
References Database< T >::getElements().
Referenced by BubbleBubbleRepulsion< BRepulsionInteractionType >::computeEnergy(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeEnergy(), BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForces(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeForces(), BubbleBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), RandomFilamentDist::createFilaments(), BasicSnapshot::print(), BirthTimes::print(), Forces::print(), Tensions::print(), WallTensions::print(), Types::print(), BubbleBubbleNL::reset(), BubbleCylinderNL::reset(), BoundaryBubbleNL::updateNeighbors(), and BubbleBubbleNL::updateNeighbors().
getFullName()
virtual string Composite::getFullName () const inline override virtual inherited
Returns the full name of this node.
Reimplemented from Component.
Reimplemented in Compartment, and CompartmentGrid.
Definition at line 74 of file Composite.h.
getID()
int Bubble::getID () inline
Getters.
Definition at line 72 of file Bubble.h.
References _ID.
Referenced by BubbleBubbleNL::updateNeighbors().
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getRadius()
double Bubble::getRadius () inline
Getters.
Definition at line 66 of file Bubble.h.
getRepulsionConst()
double Bubble::getRepulsionConst () inline
Getters.
Definition at line 67 of file Bubble.h.
References _kRepuls.
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getScreeningLength()
double Bubble::getScreeningLength () inline
Getters.
Definition at line 68 of file Bubble.h.
References _screenLength.
getType()
virtual int Bubble::getType () inline virtual
Getters.
Implements Component.
Definition at line 73 of file Bubble.h.
References _type.
isComposite()
virtual bool Composite::isComposite () const inline override virtual inherited
Returns true.
Reimplemented from Component.
Definition at line 71 of file Composite.h.
isMTOC()
bool Bubble::isMTOC () inline
Definition at line 77 of file Bubble.h.
References _isMTOC, Database< T >::addElement(), addToSubSystem(), and printSelf().
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
numberOfChildren()
virtual size_t Composite::numberOfChildren () const inline override virtual inherited
Returns the number of immediate children of this node.
Note
Species and reactions and not included in this tally
Reimplemented from Component.
Definition at line 102 of file Composite.h.
References Composite::children().
Referenced by Composite::countDescendents(), and CompartmentGrid::printSelf().
numberOfReactions()
virtual size_t Composite::numberOfReactions () const inline override virtual inherited
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented from Component.
Reimplemented in Compartment.
Definition at line 131 of file Composite.h.
Referenced by Composite::countReactions().
numberOfSpecies()
virtual size_t Composite::numberOfSpecies () const inline override virtual inherited
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.)
Reimplemented from Component.
Reimplemented in Compartment.
Definition at line 106 of file Composite.h.
Referenced by Composite::countSpecies().
numBubbles()
static int Bubble::numBubbles () inline static
Get the number of cylinders in this system.
Definition at line 93 of file Bubble.h.
References Database< T >::countElements(), and updatePosition().
Referenced by BasicSnapshot::print(), BirthTimes::print(), Forces::print(), Tensions::print(), WallTensions::print(), and Types::print().
printSelf()
void Bubble::printSelf () virtual
Print bubble information.
Implements Component.
Definition at line 40 of file Bubble.cpp.
References _bead, _bubbles, _ID, _radius, _type, and Bead::printSelf().
Referenced by isMTOC(), MTOC::printSelf(), and BubbleFF::whoIsCulprit().
removeChild()
virtual void Composite::removeChild (Component * child) inline virtual inherited
Remove *child from this node's children.
The child's destructor will be called and the memory will be freed.
Definition at line 89 of file Composite.h.
Referenced by Filament::retractMinusEnd(), and Filament::retractPlusEnd().
removeFromSubSystem()
virtual void Bubble::removeFromSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 85 of file Bubble.h.
References Database< T >::removeElement().
setAsMTOC()
void Bubble::setAsMTOC () inline
Definition at line 76 of file Bubble.h.
Referenced by MTOC::setBubble().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
updatePosition()
void Bubble::updatePosition () virtual
Update bubble position.
Implements Movable.
Definition at line 35 of file Bubble.cpp.
References _bead, Bead::coordinate, and coordinate.
Referenced by numBubbles().
Member Data Documentation
_bead
Bead* Bubble::_bead private
The bead representing the center of the bubble.
Definition at line 42 of file Bubble.h.
Referenced by Bubble(), getBead(), printSelf(), and updatePosition().
_bubbles
Database< Bubble * > Bubble::_bubbles static private
Collection in SubSystem.
Definition at line 53 of file Bubble.h.
Referenced by printSelf().
_dneighbor
bool Trackable::_dneighbor protected inherited
Object type.
Definition at line 54 of file Trackable.h.
_ID
int Bubble::_ID private
Identifier.
Definition at line 51 of file Bubble.h.
Referenced by getID(), and printSelf().
_isMTOC
bool Bubble::_isMTOC = false private
If representing a MTOC.
Definition at line 55 of file Bubble.h.
Referenced by isMTOC().
_kRepuls
double Bubble::_kRepuls private
Repulsion constant for bubble-bubble and bubble-cylinder interactions.
Definition at line 48 of file Bubble.h.
Referenced by Bubble(), and getRepulsionConst().
_movable
bool Trackable::_movable protected inherited
Object type.
Definition at line 52 of file Trackable.h.
_neighbor
bool Trackable::_neighbor protected inherited
Object type.
Definition at line 55 of file Trackable.h.
_ps
SubSystem* Bubble::_ps private
The subsystem this bubble is in.
Definition at line 43 of file Bubble.h.
Referenced by Bubble().
_radius
double Bubble::_radius private
The radius of this bubble.
Definition at line 47 of file Bubble.h.
Referenced by Bubble(), and printSelf().
_reactable
bool Trackable::_reactable protected inherited
Object type.
Definition at line 53 of file Trackable.h.
_screenLength
double Bubble::_screenLength private
Screening length for a repulsive potential.
Definition at line 49 of file Bubble.h.
Referenced by Bubble(), and getScreeningLength().
_subSystem
SubSystem * Trackable::_subSystem = 0 static protected inherited
A subsystem pointer for every trackable.
Definition at line 46 of file Trackable.h.
Referenced by Controller::Controller(), and BranchingPoint::~BranchingPoint().
_type
short Bubble::_type private
The type of bubble.
Definition at line 45 of file Bubble.h.
Referenced by Bubble(), getType(), and printSelf().
coordinate
vector<double> Bubble::coordinate
Current coordinates of bubble, Updated with updatePosition()
Definition at line 58 of file Bubble.h.
Referenced by BoundaryBubbleNL::addDynamicNeighbor(), BubbleBubbleNL::updateNeighbors(), BubbleCylinderNL::updateNeighbors(), and updatePosition().
The documentation for this class was generated from the following files:
src/Structure/Bubble.h
src/Structure/Bubble.cpp