MEDYAN: RandomFilamentDist Class Reference
RandomFilamentDist Class Reference
An implementation of FilamentInitialzer that creates a completely random Filament distribution within the specified boundary.
#include <FilamentInitializer.h>
Public Member Functions
FilamentData createFilaments (Boundary *b, int numFilaments, int filamentType, int lenFilaments)
Returns a vector of tuples representing the Filament type and beginning and end coordinates, similar to the structure of manual parsing.
Detailed Description
An implementation of FilamentInitialzer that creates a completely random Filament distribution within the specified boundary.
Definition at line 50 of file FilamentInitializer.h.
Member Function Documentation
createFilaments()
FilamentData RandomFilamentDist::createFilaments (Boundary * b, int numFilaments, int filamentType, int lenFilaments) virtual
Returns a vector of tuples representing the Filament type and beginning and end coordinates, similar to the structure of manual parsing.
Implements FilamentInitializer.
Definition at line 27 of file FilamentInitializer.cpp.
References SysParams::Boundaries(), BoundParams::BoundaryCutoff, Boundary::distance(), SysParams::Geometry(), Bubble::getBubbles(), GController::getRandomCoordinates(), mathfunc::nextPointProjection(), mathfunc::normalizedVector(), Rand::randDouble(), mathfunc::twoPointDistance(), and Boundary::within().
The documentation for this class was generated from the following files:
src/FilamentInitializer.h
src/FilamentInitializer.cpp