MEDYAN: DRController Class Reference
DRController Class Reference
Used to initialize the dynamic rate components of a simulation.
#include <DRController.h>
Public Member Functions
void initialize (DynamicRateType &drTypes)
Intialize all elements with corresponding DynamicRateChanger objects.
Detailed Description
Used to initialize the dynamic rate components of a simulation.
The DRController intializes all dynamic rate objects in the system, as specified in the input file. The controller's intiailize function will set Cylinders, [Linkers]() and [MotorGhosts]() with corresponding static DynamicRateChanger objects.
Definition at line 30 of file DRController.h.
Member Function Documentation
initialize()
void DRController::initialize (DynamicRateType & drTypes)
Intialize all elements with corresponding DynamicRateChanger objects.
Definition at line 23 of file DRController.cpp.
References Cylinder::_polyChanger, Linker::_unbindingChangers, MotorGhost::_unbindingChangers, MotorGhost::_walkingChangers, SysParams::Chemistry(), DyRateParams::dFilPolymerizationCharLength, DynamicRateType::dFPolymerizationType, DyRateParams::dLinkerUnbindingAmplitude, DyRateParams::dLinkerUnbindingCharLength, DynamicRateType::dLUnbindingType, DyRateParams::dMotorUnbindingCharForce, DyRateParams::dMotorWalkingCharForce, DynamicRateType::dMUnbindingType, DynamicRateType::dMWalkingType, SysParams::DynamicRates(), and std::sum().
Referenced by Controller::initialize().
The documentation for this class was generated from the following files:
src/DRController.h
src/DRController.cpp