MEDYAN: MMotorGhost Class Reference
MMotorGhost Class Reference
Represents a cross-link between Filaments that can move by way of chemical reactions.
#include <MMotorGhost.h>
Public Member Functions
MMotorGhost (int motorType, int numBoundHeads, double position1, double position2, const vector< double > &coord11, const vector< double > &coord12, const vector< double > &coord21, const vector< double > &coord22)
Main constructor.
void setStretchingConstant (int motorType, double numBoundHeads)
Reset the spring constant of the motor based on number of bound heads.
void setMotorGhost (MotorGhost *motor)
Set parent.
MotorGhost * getMotorGhost ()
Get parent.
double getStretchingConstant ()
Getter for constants.
double getEqLength ()
Getter for constants.
void setLength (double l)
Length management.
double getLength ()
Length management.
Public Attributes
double stretchForce = 0.0
Stretching force of motor at current state.
Private Attributes
double _eqLength
Equilibrium length, set at construction.
double _kStretch
Stretching parameter.
MotorGhost * _pMotorGhost
Pointer to parent.
double _currentLength
Current length of motor.
Detailed Description
Represents a cross-link between Filaments that can move by way of chemical reactions.
The class describes interaction between 4 Beads connected by a MotorGhost, and equilibrium constants. Initial length is determinated by the condition of zero initial stress, i.e., it is calculated within the constructor at initiation. A ghost motor heads positions on a segment (between two consecutive beads on a filament) determined by two numbers (0 to 1) position1 and position2 (finite number of steps before move to the next segment o–x-o- -> o—xo- -> o—ox) held in the parent MotorGhost. They can be changed as a result of chemical reaction, and we consider that as the motor making a step.
Definition at line 38 of file MMotorGhost.h.
Constructor & Destructor Documentation
MMotorGhost()
MMotorGhost::MMotorGhost (int motorType, int numBoundHeads, double position1, double position2, const vector< double > & coord11, const vector< double > & coord12, const vector< double > & coord21, const vector< double > & coord22)
Main constructor.
Parameters
position - position on cylinder 1 and 2, respectively
coord - coordinates of cylinder1's bead 1, bead 2, etc
Definition at line 21 of file MMotorGhost.cpp.
References SysParams::Mechanics(), mathfunc::midPointCoordinate(), MechParams::MStretchingK, and mathfunc::twoPointDistance().
Member Function Documentation
getEqLength()
double MMotorGhost::getEqLength () inline
Getter for constants.
Definition at line 53 of file MMotorGhost.h.
References _eqLength, and setStretchingConstant().
getLength()
double MMotorGhost::getLength () inline
Length management.
Definition at line 67 of file MMotorGhost.h.
References _currentLength.
getMotorGhost()
MotorGhost* MMotorGhost::getMotorGhost () inline
Get parent.
Definition at line 62 of file MMotorGhost.h.
References _currentLength, _pMotorGhost, and setLength().
getStretchingConstant()
double MMotorGhost::getStretchingConstant () inline
Getter for constants.
Definition at line 52 of file MMotorGhost.h.
setLength()
void MMotorGhost::setLength (double l) inline
Length management.
Definition at line 66 of file MMotorGhost.h.
Referenced by getMotorGhost().
setMotorGhost()
void MMotorGhost::setMotorGhost (MotorGhost * motor) inline
Set parent.
Definition at line 60 of file MMotorGhost.h.
References _pMotorGhost.
setStretchingConstant()
void MMotorGhost::setStretchingConstant (int motorType, double numBoundHeads)
Reset the spring constant of the motor based on number of bound heads.
Definition at line 33 of file MMotorGhost.cpp.
References SysParams::Mechanics(), and MechParams::MStretchingK.
Referenced by getEqLength().
Member Data Documentation
_currentLength
double MMotorGhost::_currentLength private
Current length of motor.
Definition at line 76 of file MMotorGhost.h.
Referenced by getLength(), and getMotorGhost().
_eqLength
double MMotorGhost::_eqLength private
Equilibrium length, set at construction.
Definition at line 71 of file MMotorGhost.h.
Referenced by getEqLength().
_kStretch
double MMotorGhost::_kStretch private
Stretching parameter.
Definition at line 72 of file MMotorGhost.h.
_pMotorGhost
MotorGhost* MMotorGhost::_pMotorGhost private
Pointer to parent.
Definition at line 74 of file MMotorGhost.h.
Referenced by getMotorGhost(), and setMotorGhost().
stretchForce
double MMotorGhost::stretchForce = 0.0
Stretching force of motor at current state.
Definition at line 41 of file MMotorGhost.h.
The documentation for this class was generated from the following files:
src/Structure/MMotorGhost.h
src/Structure/MMotorGhost.cpp