MEDYAN: BranchingPositionCosine Class Reference
BranchingPositionCosine Class Reference
A cosine potential used by the BranchingPosition template.
#include <BranchingPositionCosine.h>
Public Member Functions
double energy (Bead *, Bead *, Bead *, double, double)
double energy (Bead *, Bead *, Bead *, double, double, double)
void forces (Bead *, Bead *, Bead *, double, double)
void forcesAux (Bead *, Bead *, Bead *, double, double)
Detailed Description
A cosine potential used by the BranchingPosition template.
Definition at line 23 of file BranchingPositionCosine.h.
Member Function Documentation
energy() [1/2]
double BranchingPositionCosine::energy (Bead * b1, Bead * b2, Bead * b3, double kPosition, double position)
Definition at line 26 of file BranchingPositionCosine.cpp.
References Bead::coordinate, mathfunc::midPointCoordinate(), safeacos(), and mathfunc::scalarProduct().
energy() [2/2]
double BranchingPositionCosine::energy (Bead * b1, Bead * b2, Bead * b3, double kPosition, double position, double d)
Definition at line 53 of file BranchingPositionCosine.cpp.
References Bead::coordinate, Bead::force, mathfunc::midPointCoordinateStretched(), safeacos(), and mathfunc::scalarProductStretched().
forces()
void BranchingPositionCosine::forces (Bead * b1, Bead * b2, Bead * b3, double kPosition, double position)
Definition at line 88 of file BranchingPositionCosine.cpp.
References Bead::coordinate, Bead::force, mathfunc::midPointCoordinate(), safeacos(), and mathfunc::scalarProduct().
forcesAux()
void BranchingPositionCosine::forcesAux (Bead * b1, Bead * b2, Bead * b3, double kPosition, double position)
Definition at line 141 of file BranchingPositionCosine.cpp.
References Bead::coordinate, Bead::forceAux, mathfunc::midPointCoordinate(), safeacos(), and mathfunc::scalarProduct().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Branching/BranchingPositionCosine.h
src/Mechanics/ForceField/Branching/BranchingPositionCosine.cpp