MEDYAN: RNodeGillespie Class Reference
RNodeGillespie Class Reference
Used by ChemGillespieImpl to implement the cached version of the Gillespie algorithm.
#include <ChemGillespieImpl.h>
Public Member Functions
RNodeGillespie (ReactionBase *r, ChemGillespieImpl &chem_Gillespie)
Ctor:
RNodeGillespie (const RNodeGillespie &rhs)=delete
Copying is not allowed.
RNodeGillespie & operator= (RNodeGillespie &rhs)=delete
Assignment is not allowed.
virtual ~RNodeGillespie () noexcept
Dtor: The RNode pointer of the tracked Reaction object is set to nullptr.
ReactionBase * getReaction () const
Returns a pointer to the Reaction which corresponds to this RNodeGillespie.
double getPropensity () const
Return the currently stored propensity, "a", for this Reaction.
void setA (double a)
Set the propensity, "a", for this Reaction.
double getPenultStepPropensity () const
Return the propensity, "a", associated with the penultimate step of this Reaction.
void setPenultA (double a_prev)
Set the propensity, "a", associated with the penultimate step of this Reaction.
double reComputePropensity ()
(Re)Compute and return the propensity associated with this Reaction.
void reset ()
Set the the penultimate step propensity to zero and compute the current propensity.
void makeStep ()
This method calls the corresponding Reaction::makeStep() method of the underyling Reaction object.
virtual void activateReaction ()
Forwards the call to the similarly named method of ChemGillespieImpl.
virtual void passivateReaction ()
Forwards the call to the similarly named method of ChemGillespieImpl.
bool isPassivated () const
Forwards the call to the similarly named method of ChemGillespieImpl.
void printSelf () const
Print information about this RNodeGillespie such as "a", "a_penult" and the Reaction which this RNodeGillespie tracks.
void printDependents () const
Print the RNode objects which are dependents of this RNode (via the tracked Reaction object dependencies)
Private Attributes
ChemGillespieImpl & _chem_Gillespie
A reference to the ChemGillespieImpl which containts the heap, random number generators, etc.
ReactionBase * _react
The pointer to the associated Reaction object.
double _a
The propensity associated with the Reaction.
double _a_prev
The propensity associated with the penultimate step of this Reaction.
Detailed Description
Used by ChemGillespieImpl to implement the cached version of the Gillespie algorithm.
RNodeGillespie manages a single chemical reaction within the Gillespie algorithm. When the propensity drops to zero, the RNodeGillespie can execute the passivateReaction() method. Alternatively, passivated RNodeGillespie can be activated via activateReaction(). The main part of the Gillespie algoritm is implemented in the makeStep() method.
Definition at line 38 of file ChemGillespieImpl.h.
Constructor & Destructor Documentation
RNodeGillespie() [1/2]
RNodeGillespie::RNodeGillespie (ReactionBase * r, ChemGillespieImpl & chem_Gillespie)
Ctor:
Parameters
*r is the Reaction object corresponding to this RNodeGillespie
&chem_Gillespie is a refernce to ChemGillespieImpl object, which does the overall management of the Gillespie scheme (e.g. random distribution generators, etc.)
Definition at line 16 of file ChemGillespieImpl.cpp.
References _react, reset(), and ReactionBase::setRnode().
RNodeGillespie() [2/2]
RNodeGillespie::RNodeGillespie (const RNodeGillespie & rhs) delete
Copying is not allowed.
~RNodeGillespie()
RNodeGillespie::~RNodeGillespie () virtual noexcept
Dtor: The RNode pointer of the tracked Reaction object is set to nullptr.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 22 of file ChemGillespieImpl.cpp.
References _react, and ReactionBase::setRnode().
Member Function Documentation
activateReaction()
void RNodeGillespie::activateReaction () virtual
Forwards the call to the similarly named method of ChemGillespieImpl.
Implements RNode.
Definition at line 45 of file ChemGillespieImpl.cpp.
References _chem_Gillespie, ChemGillespieImpl::activateReaction(), and getReaction().
Referenced by makeStep(), and ChemGillespieImpl::runSteps().
getPenultStepPropensity()
double RNodeGillespie::getPenultStepPropensity () const inline
Return the propensity, "a", associated with the penultimate step of this Reaction.
Note
The propensity is not recomputed in this method, so it potentially can be out of sync.
Definition at line 75 of file ChemGillespieImpl.h.
References _a_prev.
Referenced by ChemGillespieImpl::activateReaction(), and ChemGillespieImpl::makeStep().
getPropensity()
double RNodeGillespie::getPropensity () const inline
Return the currently stored propensity, "a", for this Reaction.
Note
The propensity is not recomputed in this method, so it potentially can be out of sync.
Definition at line 66 of file ChemGillespieImpl.h.
References _a.
Referenced by ChemGillespieImpl::activateReaction(), ChemGillespieImpl::makeStep(), and ChemGillespieImpl::passivateReaction().
getReaction()
ReactionBase* RNodeGillespie::getReaction () const inline
Returns a pointer to the Reaction which corresponds to this RNodeGillespie.
Definition at line 61 of file ChemGillespieImpl.h.
References _react.
Referenced by activateReaction(), ChemGillespieImpl::makeStep(), and passivateReaction().
isPassivated()
bool RNodeGillespie::isPassivated () const inline virtual
Forwards the call to the similarly named method of ChemGillespieImpl.
Implements RNode.
Definition at line 105 of file ChemGillespieImpl.h.
References _react, ReactionBase::isPassivated(), printDependents(), and printSelf().
Referenced by ChemGillespieImpl::makeStep().
makeStep()
void RNodeGillespie::makeStep () inline
This method calls the corresponding Reaction::makeStep() method of the underyling Reaction object.
Definition at line 96 of file ChemGillespieImpl.h.
References _react, activateReaction(), ReactionBase::makeStep(), and passivateReaction().
Referenced by ChemGillespieImpl::makeStep(), ChemGillespieImpl::run(), and ChemGillespieImpl::runSteps().
operator=()
RNodeGillespie& RNodeGillespie::operator= (RNodeGillespie & rhs) delete
Assignment is not allowed.
Referenced by ChemGillespieImpl::ChemGillespieImpl().
passivateReaction()
void RNodeGillespie::passivateReaction () virtual
Forwards the call to the similarly named method of ChemGillespieImpl.
Implements RNode.
Definition at line 49 of file ChemGillespieImpl.cpp.
References _chem_Gillespie, getReaction(), and ChemGillespieImpl::passivateReaction().
Referenced by makeStep(), and ChemGillespieImpl::runSteps().
printDependents()
void RNodeGillespie::printDependents () const
Print the RNode objects which are dependents of this RNode (via the tracked Reaction object dependencies)
Definition at line 33 of file ChemGillespieImpl.cpp.
References _react, ReactionBase::dependents(), and printSelf().
Referenced by isPassivated().
printSelf()
void RNodeGillespie::printSelf () const
Print information about this RNodeGillespie such as "a", "a_penult" and the Reaction which this RNodeGillespie tracks.
Definition at line 27 of file ChemGillespieImpl.cpp.
References _a, and _a_prev.
Referenced by isPassivated(), and printDependents().
reComputePropensity()
double RNodeGillespie::reComputePropensity () inline
(Re)Compute and return the propensity associated with this Reaction.
Remembers the penultimate step propensity as well
Definition at line 82 of file ChemGillespieImpl.h.
References _a, _a_prev, _react, and ReactionBase::computePropensity().
Referenced by ChemGillespieImpl::activateReaction(), and ChemGillespieImpl::makeStep().
reset()
void RNodeGillespie::reset () inline
Set the the penultimate step propensity to zero and compute the current propensity.
Definition at line 90 of file ChemGillespieImpl.h.
References _a, _a_prev, _react, and ReactionBase::computePropensity().
Referenced by RNodeGillespie().
setA()
void RNodeGillespie::setA (double a) inline
Set the propensity, "a", for this Reaction.
Definition at line 69 of file ChemGillespieImpl.h.
References _a.
Referenced by ChemGillespieImpl::passivateReaction().
setPenultA()
void RNodeGillespie::setPenultA (double a_prev) inline
Set the propensity, "a", associated with the penultimate step of this Reaction.
Definition at line 78 of file ChemGillespieImpl.h.
References _a_prev.
Referenced by ChemGillespieImpl::passivateReaction().
Member Data Documentation
_a
double RNodeGillespie::_a private
The propensity associated with the Reaction.
It may be outdated and may need to be recomputed if needed.
Definition at line 119 of file ChemGillespieImpl.h.
Referenced by getPropensity(), printSelf(), reComputePropensity(), reset(), and setA().
_a_prev
double RNodeGillespie::_a_prev private
The propensity associated with the penultimate step of this Reaction.
Definition at line 121 of file ChemGillespieImpl.h.
Referenced by getPenultStepPropensity(), printSelf(), reComputePropensity(), reset(), and setPenultA().
_chem_Gillespie
ChemGillespieImpl& RNodeGillespie::_chem_Gillespie private
A reference to the ChemGillespieImpl which containts the heap, random number generators, etc.
Definition at line 114 of file ChemGillespieImpl.h.
Referenced by activateReaction(), and passivateReaction().
_react
ReactionBase* RNodeGillespie::_react private
The pointer to the associated Reaction object.
The corresponding memory is not managed by RNodeGillespie.
Definition at line 117 of file ChemGillespieImpl.h.
Referenced by getReaction(), isPassivated(), makeStep(), printDependents(), reComputePropensity(), reset(), RNodeGillespie(), and ~RNodeGillespie().
The documentation for this class was generated from the following files:
src/Chemistry/ChemGillespieImpl.h
src/Chemistry/ChemGillespieImpl.cpp