MEDYAN: GController Class Reference
GController Class Reference
Used to control the geometry of the CompartmentGrid, as well as the geometry of the entire system.
#include <GController.h>
Public Member Functions
GController (SubSystem *ps)
Constructor sets SubSystem.
CompartmentGrid * initializeGrid ()
Initialize and return the grid based on input parameters Used at system initialization.
Boundary * initializeBoundary (BoundaryType &BType)
Initialize and return a boundary based on input parameters Used at system initialization.
void setActiveCompartments ()
Set compartments in compartment grid as active based on boundary.
const SubSystem * getSubSystem () const
Get the SubSystem ptr.
Static Public Member Functions
static const vector< double > & getCenter ()
Get the center of the grid space.
static const vector< double > & getSize ()
static void findCompartments (const vector< double > &coords, Compartment *ccheck, double dist, vector< Compartment *> &compartments)
Get all compartments within a given range from the specified coordinate.
static Compartment * getRandomCompartment ()
Choose a random compartment from the grid (that is activated)
static vector< double > getRandomCoordinates (Compartment *c)
Get random coordinates in a given compartment.
static vector< double > getRandomCoordinates ()
Get random coordinates from entire grid.
static Compartment * getCompartment (const vector< size_t > &indices)
Get a compartment based on coordinates or indices.
static Compartment * getCompartment (const vector< double > &coords)
Get a compartment based on coordinates or indices.
Private Member Functions
void generateConnections ()
Generate all neighbors lists for each compartment in the CompartmentGrid.
Private Attributes
Boundary * _boundary
The boundary that this controls.
SubSystem * _subSystem
SubSystem ptr.
Static Private Attributes
static short _nDim = 0
Number of dimensions in the system.
static vector< int > _grid = {}
Size of each dimension, in compartment lengths.
static vector< double > _compartmentSize = {}
Compartment size in each dimension.
static vector< double > _centerGrid = {}
The center of the grid.
static vector< double > _size = {}
The size of the full grid in each dimension.
static CompartmentGrid * _compartmentGrid = 0
The compartment grid.
Friends
class Output
Detailed Description
Used to control the geometry of the CompartmentGrid, as well as the geometry of the entire system.
The GeometryController class is used by the SubSystem to control the geometry of the simulation, which includes the CompartmentGrid geometry as well as any Boundaries that are in place. It has functionality to initialize a CompartmentGrid based on the given dimensionality as well as find the correct Compartment based on a set of coordinates.
Note
- The geometry controller currently only supports three-dimensional grids.
Definition at line 56 of file GController.h.
Constructor & Destructor Documentation
GController()
GController::GController (SubSystem * ps) inline
Constructor sets SubSystem.
Definition at line 78 of file GController.h.
Member Function Documentation
findCompartments()
void GController::findCompartments (const vector< double > & coords, Compartment * ccheck, double dist, vector< Compartment *> & compartments) static
Get all compartments within a given range from the specified coordinate.
Parameters
ccheck - Compartment to check when initially calling this function
compartments - List of compartments that are within range. This will be populated by the function
Definition at line 284 of file GController.cpp.
References Compartment::coordinates(), Compartment::getNeighbours(), and mathfunc::twoPointDistance().
Referenced by CylinderCylinderNL::updateNeighbors().
generateConnections()
void GController::generateConnections () private
Generate all neighbors lists for each compartment in the CompartmentGrid.
Definition at line 106 of file GController.cpp.
References Compartment::addNeighbour(), and Compartment::setCoordinates().
getCenter()
static const vector<double>& GController::getCenter () inline static
Get the center of the grid space.
Definition at line 102 of file GController.h.
Referenced by BranchingManager::addPossibleBindings(), arcOutward(), and BranchingManager::updateAllPossibleBindings().
getCompartment() [1/2]
Compartment * GController::getCompartment (const vector< size_t > & indices) static
Get a compartment based on coordinates or indices.
Definition at line 27 of file GController.cpp.
Referenced by Bead::Bead(), BranchingPoint::BranchingPoint(), Cylinder::Cylinder(), Linker::Linker(), MotorGhost::MotorGhost(), BranchingPoint::updatePosition(), Bead::updatePosition(), Linker::updatePosition(), Cylinder::updatePosition(), and MotorGhost::updatePosition().
getCompartment() [2/2]
Compartment * GController::getCompartment (const vector< double > & coords) static
Get a compartment based on coordinates or indices.
Definition at line 66 of file GController.cpp.
getRandomCompartment()
Compartment * GController::getRandomCompartment () static
Choose a random compartment from the grid (that is activated)
Definition at line 307 of file GController.cpp.
References Compartment::isActivated(), and Rand::randDouble().
Referenced by ChemManager::genNucleationReactions(), and ChemManager::updateCopyNumbers().
getRandomCoordinates() [1/2]
vector< double > GController::getRandomCoordinates (Compartment * c) static
Get random coordinates in a given compartment.
Definition at line 323 of file GController.cpp.
References Compartment::coordinates(), and Rand::randDouble().
getRandomCoordinates() [2/2]
vector< double > GController::getRandomCoordinates () static
Get random coordinates from entire grid.
Definition at line 336 of file GController.cpp.
References _centerGrid, _compartmentGrid, _compartmentSize, _grid, _nDim, _size, and Rand::randDouble().
Referenced by RandomBubbleDist::createBubbles(), and RandomFilamentDist::createFilaments().
getSize()
static const vector<double>& GController::getSize () inline static
Definition at line 103 of file GController.h.
Referenced by BoundaryCapsule::BoundaryCapsule(), BoundaryCubic::BoundaryCubic(), BoundarySpherical::BoundarySpherical(), and Controller::setupSpecialStructures().
getSubSystem()
const SubSystem* GController::getSubSystem () const inline
Get the SubSystem ptr.
Definition at line 93 of file GController.h.
References Output::_subSystem.
initializeBoundary()
Boundary * GController::initializeBoundary (BoundaryType & BType)
Initialize and return a boundary based on input parameters Used at system initialization.
Definition at line 205 of file GController.cpp.
References All, SysParams::Boundaries(), BoundaryType::boundaryMove, BoundaryType::boundaryShape, None, and Top.
Referenced by Controller::initialize().
initializeGrid()
CompartmentGrid * GController::initializeGrid ()
Initialize and return the grid based on input parameters Used at system initialization.
Definition at line 157 of file GController.cpp.
References GeoParams::compartmentSizeX, GeoParams::compartmentSizeY, GeoParams::compartmentSizeZ, SysParams::Geometry(), GeoParams::nDim, GeoParams::NX, GeoParams::NY, and GeoParams::NZ.
Referenced by Controller::initialize().
setActiveCompartments()
void GController::setActiveCompartments ()
Set compartments in compartment grid as active based on boundary.
Used at system initialization.
Definition at line 277 of file GController.cpp.
Referenced by Controller::initialize().
Friends And Related Function Documentation
Output
friend class Output friend
Definition at line 58 of file GController.h.
Member Data Documentation
_boundary
Boundary* GController::_boundary private
The boundary that this controls.
Definition at line 69 of file GController.h.
_centerGrid
vector< double > GController::_centerGrid = {} static private
The center of the grid.
Definition at line 64 of file GController.h.
Referenced by getRandomCoordinates().
_compartmentGrid
CompartmentGrid * GController::_compartmentGrid = 0 static private
The compartment grid.
Definition at line 67 of file GController.h.
Referenced by getRandomCoordinates().
_compartmentSize
vector< double > GController::_compartmentSize = {} static private
Compartment size in each dimension.
Definition at line 63 of file GController.h.
Referenced by getRandomCoordinates().
_grid
vector< int > GController::_grid = {} static private
Size of each dimension, in compartment lengths.
Definition at line 62 of file GController.h.
Referenced by getRandomCoordinates().
_nDim
short GController::_nDim = 0 static private
Number of dimensions in the system.
Definition at line 61 of file GController.h.
Referenced by getRandomCoordinates().
_size
vector< double > GController::_size = {} static private
The size of the full grid in each dimension.
Definition at line 65 of file GController.h.
Referenced by getRandomCoordinates().
_subSystem
SubSystem* GController::_subSystem private
SubSystem ptr.
Definition at line 71 of file GController.h.
The documentation for this class was generated from the following files:
src/GController.h
src/GController.cpp