M3Sym: CylinderNLContainer Class Reference
CylinderNLContainer Class Reference
Holds a CylinderNeighborList.
#include <NeighborListContainer.h>
Public Member Functions
CylinderNLContainer (float rMax=0.0, float rMin=0.0, bool crossFilamentOnly=false)
Constructor, adds a cylinder neighbor list to the database.
~CylinderNLContainer ()
Destructor, removes cylinder neighbor list from the database.
CylinderNeighborList * getNeighborList ()
Get neighbor list.
Private Attributes
CylinderNeighborList * _neighborList
Detailed Description
Holds a CylinderNeighborList.
Definition at line 22 of file NeighborListContainer.h.
Constructor & Destructor Documentation
CylinderNLContainer::CylinderNLContainer (float rMax = 0.0, float rMin = 0.0, bool crossFilamentOnly = false) inline
Constructor, adds a cylinder neighbor list to the database.
Definition at line 29 of file NeighborListContainer.h.
References _neighborList, NeighborListDB::addNeighborList(), and NeighborListDB::instance().
CylinderNLContainer::~CylinderNLContainer () inline
Destructor, removes cylinder neighbor list from the database.
Definition at line 35 of file NeighborListContainer.h.
References _neighborList, NeighborListDB::instance(), and NeighborListDB::removeNeighborList().
Member Function Documentation
CylinderNeighborList* CylinderNLContainer::getNeighborList () inline
Get neighbor list.
Definition at line 41 of file NeighborListContainer.h.
References _neighborList.
Member Data Documentation
CylinderNeighborList* CylinderNLContainer::_neighborList private
Definition at line 25 of file NeighborListContainer.h.
Referenced by CylinderNLContainer(), getNeighborList(), and ~CylinderNLContainer().
The documentation for this class was generated from the following file:
M3SYM/Structure/NeighborListContainer.h