MEDYAN: Restart Class Reference
Restart Class Reference
#include <Restart.h>
Public Member Functions
Restart (SubSystem *s, tuple< vector< tuple< short, vector< double >, vector< double >>>, vector< tuple< string, short, vector< vector< double >>>>, vector< tuple< string, short, vector< double >>>, vector< vector< double >> > f, ChemistryData _cd)
int getnumchemsteps ()
void settorestartphase ()
void addtoHeaplinkermotor ()
void addtoHeapbranchers ()
void redistributediffusingspecies ()
Private Member Functions
vector< double > getAngleDeltaPos (vector< double >leg, vector< double > site1, vector< double > site2)
void crosschecklinkermotor ()
void setdiffspeciesnumber (vector< string > rxnspecies, Cylinder *c)
Private Attributes
SubSystem * _subSystem
A pointer to the subsystem that this controls.
vector< double > temp_diffrate_vector
tuple< vector< tuple< short, vector< double >, vector< double > > >, vector< tuple< string, short, vector< vector< double > > > >, vector< tuple< string, short, vector< double > > >, vector< vector< double > > > filaments
vector of diffusion rates
ChemistryData _chemData
vector< double > CopyNumbers
unordered_multimap< int, tuple< CCylinder *, short > > _unsortedpairings
vector< LinkerBindingManager * > affectedManagers
vector< tuple< string, short, vector< vector< double > > > > boundVector
int _numChemSteps =0
Detailed Description
Definition at line 61 of file Restart.h.
Constructor & Destructor Documentation
Restart()
Restart::Restart (SubSystem * s, tuple< vector< tuple< short, vector< double >, vector< double >>>, vector< tuple< string, short, vector< vector< double >>>>, vector< tuple< string, short, vector< double >>>, vector< vector< double >> > f, ChemistryData _cd) inline
Definition at line 209 of file Restart.h.
Member Function Documentation
addtoHeapbranchers()
void Restart::addtoHeapbranchers () inline
Definition at line 308 of file Restart.h.
References ChemParams::bindingSites, SysParams::Chemistry(), GeoParams::cylinderNumMon, GeoParams::cylinderSize, SysParams::Geometry(), SubSystem::getCompartmentGrid(), CompartmentGrid::getCompartments(), mathfunc::midPointCoordinate(), ChemistryData::speciesDiffusing, and mathfunc::twoPointDistance().
Referenced by Controller::run().
addtoHeaplinkermotor()
void Restart::addtoHeaplinkermotor () inline
Definition at line 250 of file Restart.h.
References ChemParams::bindingSites, SysParams::Chemistry(), GeoParams::cylinderNumMon, SysParams::Geometry(), SubSystem::getCompartmentGrid(), and CompartmentGrid::getCompartments().
Referenced by Controller::run().
crosschecklinkermotor()
void Restart::crosschecklinkermotor () inline private
Definition at line 89 of file Restart.h.
References GeoParams::cylinderNumMon, SysParams::Geometry(), mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
getAngleDeltaPos()
vector<double> Restart::getAngleDeltaPos (vector< double > leg, vector< double > site1, vector< double > site2) inline private
Definition at line 74 of file Restart.h.
References mathfunc::dotProduct(), mathfunc::normalizedVector(), and mathfunc::twoPointDistance().
getnumchemsteps()
int Restart::getnumchemsteps () inline
Definition at line 212 of file Restart.h.
Referenced by Controller::run().
redistributediffusingspecies()
void Restart::redistributediffusingspecies () inline
Definition at line 424 of file Restart.h.
References SubSystem::getCompartmentGrid(), CompartmentGrid::getCompartments(), and ChemistryData::speciesDiffusing.
Referenced by Controller::run().
setdiffspeciesnumber()
void Restart::setdiffspeciesnumber (vector< string > rxnspecies, Cylinder * c) inline private
Definition at line 189 of file Restart.h.
References Compartment::findSpeciesByName(), Cylinder::getCompartment(), Compartment::getDiffusionReactionContainer(), ChemistryData::speciesDiffusing, and ReactionPtrContainerVector::updatePropensityComprtment().
settorestartphase()
void Restart::settorestartphase () inline
Definition at line 213 of file Restart.h.
References CompartmentGrid::countDiffusingSpecies(), Bead::getBeads(), SubSystem::getCompartmentGrid(), CompartmentGrid::getCompartments(), ChemistryData::speciesDiffusing, and mathfunc::twoPointDistance().
Referenced by Controller::run().
Member Data Documentation
_chemData
ChemistryData Restart::_chemData private
Definition at line 67 of file Restart.h.
_numChemSteps
int Restart::_numChemSteps =0 private
Definition at line 72 of file Restart.h.
_subSystem
SubSystem* Restart::_subSystem private
A pointer to the subsystem that this controls.
Definition at line 63 of file Restart.h.
_unsortedpairings
unordered_multimap<int, tuple<CCylinder*, short> > Restart::_unsortedpairings private
Definition at line 69 of file Restart.h.
affectedManagers
vector<LinkerBindingManager*> Restart::affectedManagers private
Definition at line 70 of file Restart.h.
boundVector
vector<tuple<string, short, vector<vector<double> > > > Restart::boundVector private
Definition at line 71 of file Restart.h.
CopyNumbers
vector<double> Restart::CopyNumbers private
Definition at line 68 of file Restart.h.
filaments
tuple< vector<tuple<short, vector<double>, vector<double> > > , vector<tuple<string, short, vector<vector<double> > > >, vector<tuple<string, short, vector<double> > > , vector<vector<double> > > Restart::filaments private
vector of diffusion rates
Definition at line 66 of file Restart.h.
temp_diffrate_vector
vector<double> Restart::temp_diffrate_vector private
Definition at line 64 of file Restart.h.
The documentation for this class was generated from the following file:
src/Restart.h