MEDYAN: SystemParser Class Reference
SystemParser Class Reference
To parse a system input file, initialized by the Controller.
#include <Parser.h>
Public Member Functions
SystemParser (string inputFileName)
~SystemParser ()
FilamentSetup readFilamentSetup ()
Read Filament information.
BubbleSetup readBubbleSetup ()
Read Bubble information.
ChemistrySetup readChemistrySetup ()
Chemistry information.
void readMechParams ()
Parameter parser.
void readChemParams ()
Parameter parser.
void readGeoParams ()
Parameter parser.
void readBoundParams ()
Parameter parser.
void readDyRateParams ()
Parameter parser.
MechanicsAlgorithm readMechanicsAlgorithm ()
Algorithm parser.
ChemistryAlgorithm readChemistryAlgorithm ()
Algorithm parser.
MechanicsFFType readMechanicsFFType ()
Type parser.
DynamicRateType readDynamicRateType ()
Type parser.
BoundaryType readBoundaryType ()
Type parser.
SpecialSetupType readSpecialSetupType ()
Type parser.
Protected Attributes
fstream _inputFile
input file being used
Detailed Description
To parse a system input file, initialized by the Controller.
Definition at line 339 of file Parser.h.
Constructor & Destructor Documentation
SystemParser()
SystemParser::SystemParser (string inputFileName) inline
Definition at line 341 of file Parser.h.
~SystemParser()
SystemParser::~SystemParser () inline
Definition at line 342 of file Parser.h.
Member Function Documentation
readBoundaryType()
BoundaryType SystemParser::readBoundaryType ()
Type parser.
Definition at line 1244 of file Parser.cpp.
References Parser::_inputFile, BoundaryType::boundaryMove, and BoundaryType::boundaryShape.
Referenced by Controller::initialize().
readBoundParams()
void SystemParser::readBoundParams ()
Parameter parser.
Reads input directly into system parameters
Note
- does not check for correctness and consistency here.
Definition at line 1016 of file Parser.cpp.
References Parser::_inputFile, BoundParams::BoundaryCutoff, BoundParams::BoundaryK, SysParams::BParams, BoundParams::BScreenLength, GeoParams::compartmentSizeX, BoundParams::diameter, SysParams::Geometry(), BoundParams::moveEndTime, BoundParams::moveSpeed, and BoundParams::moveStartTime.
Referenced by Controller::initialize().
readBubbleSetup()
BubbleSetup SystemParser::readBubbleSetup ()
Read Bubble information.
Definition at line 1562 of file Parser.cpp.
References Parser::_inputFile, BubbleSetup::bubbleType, BubbleSetup::inputFile, and BubbleSetup::numBubbles.
Referenced by Controller::setupInitialNetwork().
readChemistryAlgorithm()
ChemistryAlgorithm SystemParser::readChemistryAlgorithm ()
Algorithm parser.
Definition at line 224 of file Parser.cpp.
References Parser::_inputFile, ChemistryAlgorithm::algorithm, ChemistryAlgorithm::minimizationSteps, ChemistryAlgorithm::minimizationTime, ChemistryAlgorithm::neighborListSteps, ChemistryAlgorithm::neighborListTime, ChemistryAlgorithm::runSteps, ChemistryAlgorithm::runTime, ChemistryAlgorithm::snapshotSteps, and ChemistryAlgorithm::snapshotTime.
Referenced by Controller::initialize().
readChemistrySetup()
ChemistrySetup SystemParser::readChemistrySetup ()
Chemistry information.
Definition at line 359 of file Parser.cpp.
References Parser::_inputFile, and ChemistrySetup::inputFile.
Referenced by Controller::initialize().
readChemParams()
void SystemParser::readChemParams ()
Parameter parser.
Reads input directly into system parameters
Note
- does not check for correctness and consistency here.
Definition at line 18 of file Parser.cpp.
References Parser::_inputFile, ChemParams::bindingSites, SysParams::CParams, GeoParams::cylinderNumMon, SysParams::Geometry(), ChemParams::makeFilamentsStatic, ChemParams::makeFilamentsStaticTime, ChemParams::makeLinkersStatic, ChemParams::makeLinkersStaticTime, ChemParams::motorNumHeadsMax, ChemParams::motorNumHeadsMin, ChemParams::motorStepSize, ChemParams::numBindingSites, ChemParams::numBoundSpecies, ChemParams::numBrancherSpecies, ChemParams::numBulkSpecies, ChemParams::numDiffusingSpecies, ChemParams::numFilaments, ChemParams::numFilamentSpecies, ChemParams::numLinkerSpecies, ChemParams::numMinusEndSpecies, ChemParams::numMotorSpecies, and ChemParams::numPlusEndSpecies.
Referenced by Controller::initialize().
readDynamicRateType()
DynamicRateType SystemParser::readDynamicRateType ()
Type parser.
Definition at line 1188 of file Parser.cpp.
References Parser::_inputFile, DynamicRateType::dFPolymerizationType, DynamicRateType::dLUnbindingType, DynamicRateType::dMUnbindingType, and DynamicRateType::dMWalkingType.
Referenced by Controller::initialize().
readDyRateParams()
void SystemParser::readDyRateParams ()
Parameter parser.
Reads input directly into system parameters
Note
- does not check for correctness and consistency here.
Definition at line 1113 of file Parser.cpp.
References Parser::_inputFile, DyRateParams::dFilPolymerizationCharLength, DyRateParams::dLinkerUnbindingAmplitude, DyRateParams::dLinkerUnbindingCharLength, DyRateParams::dMotorUnbindingCharForce, DyRateParams::dMotorWalkingCharForce, and SysParams::DRParams.
Referenced by Controller::initialize().
readFilamentSetup()
FilamentSetup SystemParser::readFilamentSetup ()
Read Filament information.
Definition at line 1486 of file Parser.cpp.
References Parser::_inputFile, FilamentSetup::filamentLength, FilamentSetup::filamentType, FilamentSetup::inputFile, FilamentSetup::numFilaments, FilamentSetup::projectionType, and SysParams::RUNSTATE.
Referenced by Controller::setupInitialNetwork().
readGeoParams()
void SystemParser::readGeoParams ()
Parameter parser.
Reads input directly into system parameters
Note
- does not check for correctness and consistency here.
Definition at line 1359 of file Parser.cpp.
References Parser::_inputFile, GeoParams::compartmentSizeX, GeoParams::compartmentSizeY, GeoParams::compartmentSizeZ, GeoParams::cylinderNumMon, GeoParams::cylinderSize, SysParams::Geometry(), SysParams::GParams, GeoParams::largestCompartmentSide, GeoParams::minCylinderNumMon, GeoParams::minCylinderSize, GeoParams::monomerSize, GeoParams::nDim, GeoParams::NX, GeoParams::NY, and GeoParams::NZ.
Referenced by Controller::initialize().
readMechanicsAlgorithm()
MechanicsAlgorithm SystemParser::readMechanicsAlgorithm ()
Algorithm parser.
Definition at line 956 of file Parser.cpp.
References Parser::_inputFile, MechanicsAlgorithm::ConjugateGradient, MechanicsAlgorithm::gradientTolerance, MechanicsAlgorithm::lambdaMax, MechanicsAlgorithm::maxDistance, and MechanicsAlgorithm::MD.
Referenced by Controller::initialize().
readMechanicsFFType()
MechanicsFFType SystemParser::readMechanicsFFType ()
Type parser.
Definition at line 392 of file Parser.cpp.
References Parser::_inputFile, MechanicsFFType::BoundaryFFType, MechanicsFFType::BrBendingType, MechanicsFFType::BrDihedralType, MechanicsFFType::BrPositionType, MechanicsFFType::BrStretchingType, MechanicsFFType::BubbleFFType, MechanicsFFType::FBendingType, MechanicsFFType::FStretchingType, MechanicsFFType::FTwistingType, MechanicsFFType::LBendingType, MechanicsFFType::LStretchingType, MechanicsFFType::LTwistingType, MechanicsFFType::MBendingType, MechanicsFFType::MStretchingType, MechanicsFFType::MTOCFFType, MechanicsFFType::MTwistingType, and MechanicsFFType::VolumeFFType.
Referenced by Controller::initialize().
readMechParams()
void SystemParser::readMechParams ()
Parameter parser.
Reads input directly into system parameters
Note
- does not check for correctness and consistency here.
Definition at line 631 of file Parser.cpp.
References Parser::_inputFile, MechParams::BrBendingK, MechParams::BrBendingTheta, MechParams::BrDihedralK, MechParams::BrPositionK, MechParams::BrStretchingK, MechParams::BrStretchingL, MechParams::BubbleCutoff, MechParams::BubbleK, MechParams::BubbleRadius, MechParams::BubbleScreenLength, MechParams::FBendingK, MechParams::FBendingTheta, MechParams::FStretchingK, MechParams::FTwistingK, MechParams::FTwistingPhi, MechParams::LBendingK, MechParams::LBendingTheta, MechParams::LStretchingK, MechParams::LTwistingK, MechParams::LTwistingPhi, MechParams::MBendingK, MechParams::MBendingTheta, SysParams::MParams, MechParams::MStretchingK, MechParams::MTwistingK, MechParams::numBubbleTypes, MechParams::pinBoundaryFilaments, MechParams::pinK, MechParams::pinTime, MechParams::VolumeCutoff, and MechParams::VolumeK.
Referenced by Controller::initialize().
readSpecialSetupType()
SpecialSetupType SystemParser::readSpecialSetupType ()
Type parser.
Definition at line 1282 of file Parser.cpp.
References Parser::_inputFile, SpecialSetupType::mtoc, SpecialSetupType::mtocBubbleType, SpecialSetupType::mtocFilamentLength, SpecialSetupType::mtocFilamentType, and SpecialSetupType::mtocNumFilaments.
Referenced by Controller::setupSpecialStructures().
Member Data Documentation
_inputFile
fstream Parser::_inputFile protected inherited
input file being used
Definition at line 322 of file Parser.h.
Referenced by readBoundaryType(), readBoundParams(), BubbleParser::readBubbles(), readBubbleSetup(), readChemistryAlgorithm(), ChemistryParser::readChemistryInput(), readChemistrySetup(), readChemParams(), readDynamicRateType(), readDyRateParams(), FilamentParser::readFilaments(), readFilamentSetup(), readGeoParams(), readMechanicsAlgorithm(), readMechanicsFFType(), readMechParams(), and readSpecialSetupType().
The documentation for this class was generated from the following files:
src/Parser.h
src/Parser.cpp