MEDYAN: ChemSimImpl Class Reference
ChemSimImpl Class Reference abstract
An abstract base class for algorithms that run stochastic chemical kinetics.
#include <ChemSimImpl.h>
Public Member Functions
virtual ~ChemSimImpl () noexcept
virtual void initialize ()=0
After all initial reactions have been added via addReaction(...) method, invoke initialize() prior to invoking run()
virtual void addReaction (ReactionBase *r)=0
Add Reaction *r to the chemical network which needs to be simulated.
virtual void removeReaction (ReactionBase *r)=0
Remove Reaction *r from the simulated chemical network.
virtual bool run (double time)=0
Run the chemical dynamics for a set amount of time.
virtual bool runSteps (int steps)=0
Run the chemical dynamics for a set amount of reaction steps.
virtual void printReactions () const =0
Mainly used for debugging: print chemical reactions in the network at this moment.
Detailed Description
An abstract base class for algorithms that run stochastic chemical kinetics.
Specific stochastic kinetics algorithm classes should inherit from ChemSimImpl. A user will then attach the corresponding algorithm to ChemSim via the algoritm's base class ChemSimImpl.
Definition at line 28 of file ChemSimImpl.h.
Constructor & Destructor Documentation
~ChemSimImpl()
virtual ChemSimImpl::~ChemSimImpl () inline virtual noexcept
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 34 of file ChemSimImpl.h.
References addReaction(), initialize(), printReactions(), removeReaction(), run(), and runSteps().
Member Function Documentation
addReaction()
virtual void ChemSimImpl::addReaction (ReactionBase * r) pure virtual
Add Reaction *r to the chemical network which needs to be simulated.
Implemented in ChemNRMImpl, ChemGillespieImpl, and ChemSimpleGillespieImpl.
Referenced by ChemSim::addReaction(), and ~ChemSimImpl().
initialize()
virtual void ChemSimImpl::initialize () pure virtual
After all initial reactions have been added via addReaction(...) method, invoke initialize() prior to invoking run()
Implemented in ChemNRMImpl, ChemGillespieImpl, and ChemSimpleGillespieImpl.
Referenced by ChemSim::initialize(), and ~ChemSimImpl().
printReactions()
virtual void ChemSimImpl::printReactions () const pure virtual
Mainly used for debugging: print chemical reactions in the network at this moment.
Implemented in ChemNRMImpl, ChemGillespieImpl, and ChemSimpleGillespieImpl.
Referenced by ChemSim::printReactions(), and ~ChemSimImpl().
removeReaction()
virtual void ChemSimImpl::removeReaction (ReactionBase * r) pure virtual
Remove Reaction *r from the simulated chemical network.
Implemented in ChemNRMImpl, ChemGillespieImpl, and ChemSimpleGillespieImpl.
Referenced by ChemSim::removeReaction(), and ~ChemSimImpl().
run()
virtual bool ChemSimImpl::run (double time) pure virtual
Run the chemical dynamics for a set amount of time.
Implemented in ChemNRMImpl, ChemGillespieImpl, and ChemSimpleGillespieImpl.
Referenced by ChemSim::run(), and ~ChemSimImpl().
runSteps()
virtual bool ChemSimImpl::runSteps (int steps) pure virtual
Run the chemical dynamics for a set amount of reaction steps.
Implemented in ChemNRMImpl, ChemGillespieImpl, and ChemSimpleGillespieImpl.
Referenced by ChemSim::runSteps(), and ~ChemSimImpl().
The documentation for this class was generated from the following file:
src/Chemistry/ChemSimImpl.h