MEDYAN: BoundaryFF Class Reference
BoundaryFF Class Reference
An implementation of the ForceField class that calculates BoundaryElement repulsion and attraction to Beads in the system.
#include <BoundaryFF.h>
Public Member Functions
BoundaryFF (string type)
Initialize the forcefields (repulsion, attraction, etc)
virtual string getName ()
Get the name of this forcefield.
virtual void whoIsCulprit ()
In the case of a calculation error, print the culprit of the FF error.
virtual double computeEnergy (double d)
Compute total energy of this forcefield in the system.
virtual void computeForces ()
Compute forces of this forcefield in the system.
virtual void computeForcesAux ()
Compute auxiliary forces of this forcefield in the system.
virtual void computeLoadForces ()
BoundaryFF can compute load forces from all boundaries.
virtual vector< NeighborList * > getNeighborLists ()
Get all neighbor lists associated with a ForceField.
Private Attributes
vector< unique_ptr< BoundaryInteractions > > _boundaryInteractionVector
Vector of initialized boundary element interactions.
BoundaryInteractions * _culpritInteraction
The culprit in the case of an error.
Detailed Description
An implementation of the ForceField class that calculates BoundaryElement repulsion and attraction to Beads in the system.
Definition at line 30 of file BoundaryFF.h.
Constructor & Destructor Documentation
BoundaryFF()
BoundaryFF::BoundaryFF (string type)
Initialize the forcefields (repulsion, attraction, etc)
Definition at line 29 of file BoundaryFF.cpp.
References _boundaryInteractionVector, and SysParams::Mechanics().
Member Function Documentation
computeEnergy()
double BoundaryFF::computeEnergy (double d) virtual
Compute total energy of this forcefield in the system.
Returns
the energy value if valid. If an inf or NaN value has been calculated, return -1.
Implements ForceField.
Definition at line 68 of file BoundaryFF.cpp.
References _boundaryInteractionVector, and _culpritInteraction.
Referenced by getName().
computeForces()
void BoundaryFF::computeForces () virtual
Compute forces of this forcefield in the system.
Update Bead forces accordingly.
Implements ForceField.
Definition at line 88 of file BoundaryFF.cpp.
References _boundaryInteractionVector.
Referenced by getName().
computeForcesAux()
void BoundaryFF::computeForcesAux () virtual
Compute auxiliary forces of this forcefield in the system.
Update Bead auxiliary forces accordingly.
Implements ForceField.
Definition at line 94 of file BoundaryFF.cpp.
References _boundaryInteractionVector.
Referenced by getName().
computeLoadForces()
void BoundaryFF::computeLoadForces () virtual
BoundaryFF can compute load forces from all boundaries.
Implements ForceField.
Definition at line 101 of file BoundaryFF.cpp.
References _boundaryInteractionVector.
Referenced by getName().
getName()
virtual string BoundaryFF::getName () inline virtual
Get the name of this forcefield.
Implements ForceField.
Definition at line 42 of file BoundaryFF.h.
References computeEnergy(), computeForces(), computeForcesAux(), computeLoadForces(), getNeighborLists(), and whoIsCulprit().
getNeighborLists()
vector< NeighborList * > BoundaryFF::getNeighborLists () virtual
Get all neighbor lists associated with a ForceField.
Implements ForceField.
Definition at line 107 of file BoundaryFF.cpp.
References _boundaryInteractionVector.
Referenced by getName().
whoIsCulprit()
void BoundaryFF::whoIsCulprit () virtual
In the case of a calculation error, print the culprit of the FF error.
Typically, will just print the Trackable element where the error came from.
Implements ForceField.
Definition at line 49 of file BoundaryFF.cpp.
References BoundaryInteractions::_boundaryElementCulprit, _culpritInteraction, BoundaryInteractions::_otherCulprit, BoundaryInteractions::getName(), BoundaryElement::printSelf(), and Component::printSelf().
Referenced by getName().
Member Data Documentation
_boundaryInteractionVector
vector<unique_ptr<BoundaryInteractions> > BoundaryFF::_boundaryInteractionVector private
Vector of initialized boundary element interactions.
Definition at line 34 of file BoundaryFF.h.
Referenced by BoundaryFF(), computeEnergy(), computeForces(), computeForcesAux(), computeLoadForces(), and getNeighborLists().
_culpritInteraction
BoundaryInteractions* BoundaryFF::_culpritInteraction private
The culprit in the case of an error.
Definition at line 37 of file BoundaryFF.h.
Referenced by computeEnergy(), and whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Boundary/BoundaryFF.h
src/Mechanics/ForceField/Boundary/BoundaryFF.cpp