MEDYAN: MotorGhost Class Reference
MotorGhost Class Reference
A container to store a MMotorGhost and CMotorGhost.
#include <MotorGhost.h>
Public Member Functions
MotorGhost (Cylinder *c1, Cylinder *c2, short motorType, double position1=0.5, double position2=0.5, double onRate=0.0, double offRate=0.0)
Standard constructor.
virtual ~MotorGhost () noexcept
void updateCoordinate ()
Helper to get coordinate.
void setCMotorGhost (CMotorGhost *cMotorGhost)
Set chem motor ghost.
CMotorGhost * getCMotorGhost ()
Get chem motor ghost.
MMotorGhost * getMMotorGhost ()
Get mech motor ghost.
float getBirthTime ()
Get the birth time.
virtual void updatePosition ()
Update the position, inherited from Movable.
virtual void updateReactionRates ()
Update the reaction rates, inherited from Reactable.
void moveMotorHead (Cylinder *c, double oldPosition, double newPosition, short boundType, SubSystem *ps)
Move a motor head forward.
void moveMotorHead (Cylinder *oldC, Cylinder *newC, double oldPosition, double newPosition, short boundType, SubSystem *ps)
Move a motor head to a new cylinder.
virtual void printSelf ()
Prints information about this node. Useful for debugging.
virtual bool apply (Visitor &v)
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
virtual bool apply (SpeciesVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual size_t numberOfChildren () const
Returns the number of children of this node.
virtual bool isComposite () const
Returns true if this node is a Composite node.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
virtual size_t numberOfSpecies () const
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t numberOfReactions () const
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual string getFullName () const
Return a string indicating the full name of this node (presumably used mainly for debugging)
virtual size_t countDescendents () const
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const
Return the number of Species contained under this node's hieararchy.
virtual size_t countReactions () const
Return the number of ReactionBase objects contained under this node's hieararchy.
Cylinder * getFirstCylinder ()
Get cylinder.
Cylinder * getSecondCylinder ()
Get cylinder.
void setFirstCylinder (Cylinder *cylinder)
Set cylinder.
void setSecondCylinder (Cylinder *cylinder)
Set cylinder.
double getFirstPosition ()
Position management function.
void setFirstPosition (double position1)
Position management function.
double getSecondPosition ()
Position management function.
void setSecondPosition (double position2)
Position management function.
virtual int getType ()
Parameter management.
int getID ()
Parameter management.
void setID (int ID)
Parameter management.
virtual void addToSubSystem ()
SubSystem management, inherited from Trackable.
virtual void removeFromSubSystem ()
SubSystem management, inherited from Trackable.
Static Public Member Functions
static const vector< MotorGhost * > & getMotorGhosts ()
Get all instances of this class from the SubSystem.
static int numMotorGhosts ()
Get the number of motors in this system.
static Histogram * getLifetimes ()
Get the lifetimes.
static Histogram * getWalkLengths ()
Get walk lengths.
static species_copy_t countSpecies (const string &name)
Count the number of motor species with a given name in the system.
Public Attributes
vector< double > coordinate
coordinate of midpoint, updated with updatePosition()
Protected Attributes
bool _movable
Object type.
bool _reactable
Object type.
bool _dneighbor
Object type.
bool _neighbor
Object type.
Static Protected Attributes
static SubSystem * _subSystem = 0
A subsystem pointer for every trackable.
Private Attributes
unique_ptr< MMotorGhost > _mMotorGhost
Pointer to mech motor ghost.
unique_ptr< CMotorGhost > _cMotorGhost
Pointer to chem motor ghost.
Cylinder * _c1
First cylinder the motor is bound to.
Cylinder * _c2
Second cylinder the motor is bound to.
double _position1
Position on first cylinder.
double _position2
Position on second cylinder.
short _motorType
Integer specifying the type of linker.
int _motorID
Integer ID of this motor, managed by Database.
float _birthTime
Birth time.
float _walkLength = 0
Walk length of ensemble.
Compartment * _compartment
Where this motorghost is.
int _numHeads = 1
Number of heads that this motor contains.
double _numBoundHeads = 1
Number of bound heads in the ensemble, which is force-dependent.
double _onRate = 0.0
Kinetic rates of individual motor heads.
double _offRate = 0.0
Kinetic rates of individual motor heads.
Static Private Attributes
static Database< MotorGhost * > _motorGhosts
Collection in SubSystem.
static vector< MotorRateChanger * > _unbindingChangers
For dynamic rate unbinding.
static vector< MotorRateChanger * > _walkingChangers
For dynamic rate walking.
static Histogram * _lifetimes
Histogram data.
static Histogram * _walkLengths
Histogram data.
Friends
class Controller
class DRController
class MotorBindingManager
struct UpdateMotorIDCallback
struct MotorBindingCallback
struct MotorUnbindingCallback
Detailed Description
A container to store a MMotorGhost and CMotorGhost.
MotorGhost class is used to manage and store a MMotorGhost and CMotorGhost. Upon intialization, both of these components are created.
Extending the Movable class, the positions of all instances can be updated by the SubSystem.
Extending the Reactable class, the reactions associated with all instances can be updated by the SubSystem.
Definition at line 47 of file MotorGhost.h.
Constructor & Destructor Documentation
MotorGhost()
MotorGhost::MotorGhost (Cylinder * c1, Cylinder * c2, short motorType, double position1 = 0.5, double position2 = 0.5, double onRate = 0.0, double offRate = 0.0)
Standard constructor.
Definition at line 44 of file MotorGhost.cpp.
References _c1, _c2, _cMotorGhost, _compartment, _mMotorGhost, _motorType, _numBoundHeads, _numHeads, _offRate, _onRate, _unbindingChangers, SysParams::Chemistry(), Bead::coordinate, coordinate, SysParams::Geometry(), Cylinder::getCCylinder(), GController::getCompartment(), Cylinder::getFirstBead(), Cylinder::getSecondBead(), Cylinder::getType(), printSelf(), Rand::randInteger(), and updateCoordinate().
~MotorGhost()
MotorGhost::~MotorGhost () virtual noexcept
Note
- record lifetime data here
Definition at line 99 of file MotorGhost.cpp.
References _birthTime, _lifetimes, _walkLength, _walkLengths, Histogram::addValue(), Histogram::getMax(), Histogram::getMin(), and tau().
Member Function Documentation
addToSubSystem()
virtual void MotorGhost::addToSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 157 of file MotorGhost.h.
Referenced by getBirthTime().
apply() [1/3]
bool Component::apply (Visitor & v) virtual inherited
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
However, the ConditionalVisitor allows the visit() function to be applied only selectively to nodes that conform to specific criteria.
Reimplemented in Composite.
Definition at line 26 of file Component.cpp.
References Visitor::visit().
Referenced by Component::~Component().
apply() [2/3]
virtual bool Component::apply (SpeciesVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented in Composite.
Definition at line 61 of file Component.h.
References Component::apply_impl().
apply() [3/3]
virtual bool Component::apply (ReactionVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented in Composite.
Definition at line 69 of file Component.h.
References Component::apply_impl().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
countDescendents()
virtual size_t Component::countDescendents () const inline virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 118 of file Component.h.
countReactions()
virtual size_t Component::countReactions () const inline virtual inherited
Return the number of ReactionBase objects contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 126 of file Component.h.
References Component::getType(), and Component::printSelf().
countSpecies() [1/2]
virtual size_t Component::countSpecies () const inline virtual inherited
Return the number of Species contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 122 of file Component.h.
Referenced by Linker::getLifetimes(), getWalkLengths(), BranchingPoint::numBranchingPoints(), and Chemistry::print().
countSpecies() [2/2]
species_copy_t MotorGhost::countSpecies (const string & name) static
Count the number of motor species with a given name in the system.
Definition at line 390 of file MotorGhost.cpp.
References _lifetimes, _motorGhosts, _unbindingChangers, _walkingChangers, _walkLengths, Database< T >::getElements(), and SpeciesNamesDB::removeUniqueFilName().
getBirthTime()
float MotorGhost::getBirthTime () inline
Get the birth time.
Definition at line 153 of file MotorGhost.h.
References _birthTime, Database< T >::addElement(), and addToSubSystem().
getCMotorGhost()
CMotorGhost* MotorGhost::getCMotorGhost () inline
Get chem motor ghost.
Definition at line 130 of file MotorGhost.h.
getFirstCylinder()
Cylinder* MotorGhost::getFirstCylinder () inline
Get cylinder.
Definition at line 115 of file MotorGhost.h.
getFirstPosition()
double MotorGhost::getFirstPosition () inline
Position management function.
Definition at line 137 of file MotorGhost.h.
Referenced by getMMotorGhost().
getFullName()
virtual string Component::getFullName () const inline virtual inherited
Return a string indicating the full name of this node (presumably used mainly for debugging)
Reimplemented in Compartment, CompartmentGrid, and Composite.
Definition at line 114 of file Component.h.
getID()
int MotorGhost::getID () inline
Parameter management.
Definition at line 147 of file MotorGhost.h.
References _motorID.
getLifetimes()
static Histogram* MotorGhost::getLifetimes () inline static
Get the lifetimes.
Definition at line 171 of file MotorGhost.h.
References _lifetimes.
Referenced by MotorLifetimes::print().
getMMotorGhost()
MMotorGhost* MotorGhost::getMMotorGhost () inline
Get mech motor ghost.
Definition at line 133 of file MotorGhost.h.
References _position1, and getFirstPosition().
getMotorGhosts()
static const vector<MotorGhost*>& MotorGhost::getMotorGhosts () inline static
Get all instances of this class from the SubSystem.
Definition at line 162 of file MotorGhost.h.
References Database< T >::getElements().
Referenced by MotorGhostStretching< MStretchingInteractionType >::computeEnergy(), MotorGhostStretching< MStretchingInteractionType >::computeForces(), MotorGhostStretching< MStretchingInteractionType >::computeForcesAux(), BasicSnapshot::print(), BirthTimes::print(), Forces::print(), Tensions::print(), WallTensions::print(), Types::print(), and Controller::run().
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getSecondCylinder()
Cylinder* MotorGhost::getSecondCylinder () inline
Get cylinder.
Definition at line 116 of file MotorGhost.h.
References _c2, and setFirstCylinder().
getSecondPosition()
double MotorGhost::getSecondPosition () inline
Position management function.
Definition at line 140 of file MotorGhost.h.
References _position2.
getType()
virtual int MotorGhost::getType () inline virtual
Parameter management.
Implements Component.
Definition at line 146 of file MotorGhost.h.
Referenced by setSecondPosition().
getWalkLengths()
static Histogram* MotorGhost::getWalkLengths () inline static
Get walk lengths.
Definition at line 174 of file MotorGhost.h.
References _walkLengths, Component::countSpecies(), moveMotorHead(), printSelf(), updatePosition(), and updateReactionRates().
Referenced by MotorWalkLengths::print().
isComposite()
virtual bool Component::isComposite () const inline virtual inherited
Returns true if this node is a Composite node.
Reimplemented in Composite.
Definition at line 95 of file Component.h.
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
moveMotorHead() [1/2]
void MotorGhost::moveMotorHead (Cylinder * c, double oldPosition, double newPosition, short boundType, SubSystem * ps)
Move a motor head forward.
Note
- Updates chemical binding and mechanical parameters accordingly
Definition at line 298 of file MotorGhost.cpp.
References _c1, _cMotorGhost, _motorType, _position1, _position2, _walkLength, GeoParams::cylinderSize, SysParams::Geometry(), Cylinder::getCCylinder(), and Cylinder::getType().
Referenced by getWalkLengths().
moveMotorHead() [2/2]
void MotorGhost::moveMotorHead (Cylinder * oldC, Cylinder * newC, double oldPosition, double newPosition, short boundType, SubSystem * ps)
Move a motor head to a new cylinder.
Note
- Updates chemical binding and mechanical parameters accordingly
Definition at line 327 of file MotorGhost.cpp.
References _c1, _c2, _cMotorGhost, _motorType, _position1, _position2, _walkLength, GeoParams::cylinderSize, SysParams::Geometry(), Cylinder::getCCylinder(), and Cylinder::getType().
numberOfChildren()
virtual size_t Component::numberOfChildren () const inline virtual inherited
Returns the number of children of this node.
Note
Species and ReactionBase objects are not counted.
Reimplemented in Composite.
Definition at line 92 of file Component.h.
numberOfReactions()
virtual size_t Component::numberOfReactions () const inline virtual inherited
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 110 of file Component.h.
numberOfSpecies()
virtual size_t Component::numberOfSpecies () const inline virtual inherited
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 106 of file Component.h.
numMotorGhosts()
static int MotorGhost::numMotorGhosts () inline static
Get the number of motors in this system.
Definition at line 166 of file MotorGhost.h.
References Database< T >::countElements().
Referenced by BasicSnapshot::print(), BirthTimes::print(), Forces::print(), Tensions::print(), WallTensions::print(), and Types::print().
printSelf()
void MotorGhost::printSelf () virtual
Prints information about this node. Useful for debugging.
Implements Component.
Definition at line 355 of file MotorGhost.cpp.
References _birthTime, _c1, _c2, _cMotorGhost, _motorID, _motorType, _numHeads, _position1, _position2, coordinate, and Cylinder::printSelf().
Referenced by getWalkLengths(), MotorGhost(), updatePosition(), and MotorGhostFF::whoIsCulprit().
removeFromSubSystem()
virtual void MotorGhost::removeFromSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 158 of file MotorGhost.h.
References Database< T >::removeElement().
setCMotorGhost()
void MotorGhost::setCMotorGhost (CMotorGhost * cMotorGhost) inline
Set chem motor ghost.
Definition at line 126 of file MotorGhost.h.
Referenced by updatePosition().
setFirstCylinder()
void MotorGhost::setFirstCylinder (Cylinder * cylinder) inline
Set cylinder.
Definition at line 121 of file MotorGhost.h.
Referenced by getSecondCylinder().
setFirstPosition()
void MotorGhost::setFirstPosition (double position1) inline
Position management function.
Definition at line 138 of file MotorGhost.h.
setID()
void MotorGhost::setID (int ID) inline
Parameter management.
Definition at line 149 of file MotorGhost.h.
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
setSecondCylinder()
void MotorGhost::setSecondCylinder (Cylinder * cylinder) inline
Set cylinder.
Definition at line 122 of file MotorGhost.h.
setSecondPosition()
void MotorGhost::setSecondPosition (double position2) inline
Position management function.
Definition at line 141 of file MotorGhost.h.
References _motorType, and getType().
updateCoordinate()
void MotorGhost::updateCoordinate ()
Helper to get coordinate.
Definition at line 30 of file MotorGhost.cpp.
References mathfunc::midPointCoordinate().
Referenced by MotorGhost(), and updatePosition().
updatePosition()
void MotorGhost::updatePosition () virtual
Update the position, inherited from Movable.
Note
- changes compartment if needed
Implements Movable.
Definition at line 114 of file MotorGhost.cpp.
References _c1, _c2, _cMotorGhost, _compartment, _mMotorGhost, _motorType, _numBoundHeads, _numHeads, _offRate, _onRate, _position1, _position2, _unbindingChangers, Bead::coordinate, coordinate, Cylinder::getCCylinder(), GController::getCompartment(), Cylinder::getFirstBead(), Cylinder::getSecondBead(), mathfunc::midPointCoordinate(), printSelf(), setCMotorGhost(), mathfunc::twoPointDistance(), and updateCoordinate().
Referenced by getWalkLengths().
updateReactionRates()
void MotorGhost::updateReactionRates () virtual
Update the reaction rates, inherited from Reactable.
Updates unbinding rates based on the stretch force.
Note
- This function updates forward walking rates using the stetching force in the opposite direction of the motor walk. Does not consider negative forces in this direction. Does not consider compression forces, only stretching.
Implements Reactable.
Definition at line 185 of file MotorGhost.cpp.
References _c1, _c2, _cMotorGhost, _mMotorGhost, _motorType, _numBoundHeads, _numHeads, _offRate, _onRate, _position1, _position2, _unbindingChangers, _walkingChangers, ReactionBase::activateReaction(), Bead::coordinate, mathfunc::dotProduct(), Cylinder::getFirstBead(), Species::getRSpecies(), Cylinder::getSecondBead(), mathfunc::midPointCoordinate(), MOTORWALKINGBACKWARD, MOTORWALKINGFORWARD, RSpecies::reactantReactions(), SysParams::RUNSTATE, ReactionBase::setRate(), and mathfunc::twoPointDirection().
Referenced by getWalkLengths().
Friends And Related Function Documentation
Controller
friend class Controller friend
Definition at line 49 of file MotorGhost.h.
DRController
friend class DRController friend
Definition at line 50 of file MotorGhost.h.
MotorBindingCallback
friend struct MotorBindingCallback friend
Definition at line 55 of file MotorGhost.h.
MotorBindingManager
friend class MotorBindingManager friend
Definition at line 52 of file MotorGhost.h.
MotorUnbindingCallback
friend struct MotorUnbindingCallback friend
Definition at line 56 of file MotorGhost.h.
UpdateMotorIDCallback
friend struct UpdateMotorIDCallback friend
Definition at line 54 of file MotorGhost.h.
Member Data Documentation
_birthTime
float MotorGhost::_birthTime private
Birth time.
Definition at line 71 of file MotorGhost.h.
Referenced by getBirthTime(), printSelf(), and ~MotorGhost().
_c1
Cylinder* MotorGhost::_c1 private
First cylinder the motor is bound to.
Definition at line 62 of file MotorGhost.h.
Referenced by MotorGhost(), moveMotorHead(), printSelf(), updatePosition(), and updateReactionRates().
_c2
Cylinder* MotorGhost::_c2 private
Second cylinder the motor is bound to.
Definition at line 63 of file MotorGhost.h.
Referenced by getSecondCylinder(), MotorGhost(), moveMotorHead(), printSelf(), updatePosition(), and updateReactionRates().
_cMotorGhost
unique_ptr<CMotorGhost> MotorGhost::_cMotorGhost private
Pointer to chem motor ghost.
Definition at line 60 of file MotorGhost.h.
Referenced by MotorGhost(), moveMotorHead(), printSelf(), updatePosition(), and updateReactionRates().
_compartment
Compartment* MotorGhost::_compartment private
Where this motorghost is.
Definition at line 74 of file MotorGhost.h.
Referenced by MotorGhost(), and updatePosition().
_dneighbor
bool Trackable::_dneighbor protected inherited
Object type.
Definition at line 54 of file Trackable.h.
_lifetimes
Histogram * MotorGhost::_lifetimes static private
Histogram data.
Definition at line 90 of file MotorGhost.h.
Referenced by countSpecies(), getLifetimes(), and ~MotorGhost().
_mMotorGhost
unique_ptr<MMotorGhost> MotorGhost::_mMotorGhost private
Pointer to mech motor ghost.
Definition at line 59 of file MotorGhost.h.
Referenced by MotorGhost(), updatePosition(), and updateReactionRates().
_motorGhosts
Database< MotorGhost * > MotorGhost::_motorGhosts static private
Collection in SubSystem.
Definition at line 86 of file MotorGhost.h.
Referenced by countSpecies().
_motorID
int MotorGhost::_motorID private
Integer ID of this motor, managed by Database.
Definition at line 69 of file MotorGhost.h.
Referenced by getID(), and printSelf().
_motorType
short MotorGhost::_motorType private
Integer specifying the type of linker.
Definition at line 68 of file MotorGhost.h.
Referenced by MotorGhost(), moveMotorHead(), printSelf(), setSecondPosition(), updatePosition(), and updateReactionRates().
_movable
bool Trackable::_movable protected inherited
Object type.
Definition at line 52 of file Trackable.h.
_neighbor
bool Trackable::_neighbor protected inherited
Object type.
Definition at line 55 of file Trackable.h.
_numBoundHeads
double MotorGhost::_numBoundHeads = 1 private
Number of bound heads in the ensemble, which is force-dependent.
Definition at line 77 of file MotorGhost.h.
Referenced by MotorGhost(), updatePosition(), and updateReactionRates().
_numHeads
int MotorGhost::_numHeads = 1 private
Number of heads that this motor contains.
Definition at line 76 of file MotorGhost.h.
Referenced by MotorGhost(), printSelf(), updatePosition(), and updateReactionRates().
_offRate
double MotorGhost::_offRate = 0.0 private
Kinetic rates of individual motor heads.
Definition at line 83 of file MotorGhost.h.
Referenced by MotorGhost(), updatePosition(), and updateReactionRates().
_onRate
double MotorGhost::_onRate = 0.0 private
Kinetic rates of individual motor heads.
Definition at line 82 of file MotorGhost.h.
Referenced by MotorGhost(), updatePosition(), and updateReactionRates().
_position1
double MotorGhost::_position1 private
Position on first cylinder.
Definition at line 65 of file MotorGhost.h.
Referenced by getMMotorGhost(), moveMotorHead(), printSelf(), updatePosition(), and updateReactionRates().
_position2
double MotorGhost::_position2 private
Position on second cylinder.
Definition at line 66 of file MotorGhost.h.
Referenced by getSecondPosition(), moveMotorHead(), printSelf(), updatePosition(), and updateReactionRates().
_reactable
bool Trackable::_reactable protected inherited
Object type.
Definition at line 53 of file Trackable.h.
_subSystem
SubSystem * Trackable::_subSystem = 0 static protected inherited
A subsystem pointer for every trackable.
Definition at line 46 of file Trackable.h.
Referenced by Controller::Controller(), and BranchingPoint::~BranchingPoint().
_unbindingChangers
vector< MotorRateChanger * > MotorGhost::_unbindingChangers static private
For dynamic rate unbinding.
Definition at line 95 of file MotorGhost.h.
Referenced by countSpecies(), DRController::initialize(), MotorGhost(), updatePosition(), and updateReactionRates().
_walkingChangers
vector< MotorRateChanger * > MotorGhost::_walkingChangers static private
For dynamic rate walking.
Definition at line 97 of file MotorGhost.h.
Referenced by countSpecies(), DRController::initialize(), and updateReactionRates().
_walkLength
float MotorGhost::_walkLength = 0 private
Walk length of ensemble.
Definition at line 72 of file MotorGhost.h.
Referenced by moveMotorHead(), and ~MotorGhost().
_walkLengths
Histogram * MotorGhost::_walkLengths static private
Histogram data.
Definition at line 91 of file MotorGhost.h.
Referenced by countSpecies(), getWalkLengths(), and ~MotorGhost().
coordinate
vector<double> MotorGhost::coordinate
coordinate of midpoint, updated with updatePosition()
Definition at line 100 of file MotorGhost.h.
Referenced by MotorGhost(), printSelf(), and updatePosition().
The documentation for this class was generated from the following files:
src/Structure/MotorGhost.h
src/Structure/MotorGhost.cpp