MEDYAN: FilamentFF Class Reference
FilamentFF Class Reference
An implementation of the ForceField class that calculates Filament interactions.
#include <FilamentFF.h>
Public Member Functions
FilamentFF (string &stretching, string &bending, string &twisting)
Constructor, intializes stretching, bending, and twisting forces.
virtual string getName ()
Get the name of this forcefield.
virtual void whoIsCulprit ()
In the case of a calculation error, print the culprit of the FF error.
virtual double computeEnergy (double d)
Compute total energy of this forcefield in the system.
virtual void computeForces ()
Compute forces of this forcefield in the system.
virtual void computeForcesAux ()
Compute auxiliary forces of this forcefield in the system.
virtual void computeLoadForces ()
Compute all load forces on beads in this system.
virtual vector< NeighborList * > getNeighborLists ()
Get all neighbor lists associated with a ForceField.
Private Attributes
vector< unique_ptr< FilamentInteractions > > _filamentInteractionVector
Vector of initialized filament interactions.
FilamentInteractions * _culpritInteraction
Culprit in case of error.
Detailed Description
An implementation of the ForceField class that calculates Filament interactions.
Definition at line 28 of file FilamentFF.h.
Constructor & Destructor Documentation
FilamentFF()
FilamentFF::FilamentFF (string & stretching, string & bending, string & twisting)
Constructor, intializes stretching, bending, and twisting forces.
Definition at line 25 of file FilamentFF.cpp.
References _filamentInteractionVector.
Member Function Documentation
computeEnergy()
double FilamentFF::computeEnergy (double d) virtual
Compute total energy of this forcefield in the system.
Returns
the energy value if valid. If an inf or NaN value has been calculated, return -1.
Implements ForceField.
Definition at line 62 of file FilamentFF.cpp.
References _culpritInteraction, and _filamentInteractionVector.
Referenced by getName().
computeForces()
void FilamentFF::computeForces () virtual
Compute forces of this forcefield in the system.
Update Bead forces accordingly.
Implements ForceField.
Definition at line 82 of file FilamentFF.cpp.
References _filamentInteractionVector.
Referenced by getName().
computeForcesAux()
void FilamentFF::computeForcesAux () virtual
Compute auxiliary forces of this forcefield in the system.
Update Bead auxiliary forces accordingly.
Implements ForceField.
Definition at line 88 of file FilamentFF.cpp.
References _filamentInteractionVector.
Referenced by getName().
computeLoadForces()
virtual void FilamentFF::computeLoadForces () inline virtual
Compute all load forces on beads in this system.
Updates all Bead's load force components for Reaction updating.
Implements ForceField.
Definition at line 46 of file FilamentFF.h.
getName()
virtual string FilamentFF::getName () inline virtual
Get the name of this forcefield.
Implements ForceField.
Definition at line 39 of file FilamentFF.h.
References computeEnergy(), computeForces(), computeForcesAux(), and whoIsCulprit().
getNeighborLists()
virtual vector<NeighborList*> FilamentFF::getNeighborLists () inline virtual
Get all neighbor lists associated with a ForceField.
Implements ForceField.
Definition at line 48 of file FilamentFF.h.
whoIsCulprit()
void FilamentFF::whoIsCulprit () virtual
In the case of a calculation error, print the culprit of the FF error.
Typically, will just print the Trackable element where the error came from.
Implements ForceField.
Definition at line 49 of file FilamentFF.cpp.
References _culpritInteraction, FilamentInteractions::_filamentCulprit, FilamentInteractions::getName(), and Filament::printSelf().
Referenced by getName().
Member Data Documentation
_culpritInteraction
FilamentInteractions* FilamentFF::_culpritInteraction private
Culprit in case of error.
Definition at line 34 of file FilamentFF.h.
Referenced by computeEnergy(), and whoIsCulprit().
_filamentInteractionVector
vector<unique_ptr<FilamentInteractions> > FilamentFF::_filamentInteractionVector private
Vector of initialized filament interactions.
Definition at line 32 of file FilamentFF.h.
Referenced by computeEnergy(), computeForces(), computeForcesAux(), and FilamentFF().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Filament/FilamentFF.h
src/Mechanics/ForceField/Filament/FilamentFF.cpp