M3Sym: SpeciesFilament Class Reference
SpeciesFilament Class Reference
Used for species that can be in a Filament.
#include <Species.h>
Public Member Functions
SpeciesFilament ()
Default constructor.
SpeciesFilament (const string &name, species_copy_t n=0, species_copy_t ulim=1)
The main constructor.
SpeciesFilament (const SpeciesFilament &rhs)
Copy constructor.
SpeciesFilament (SpeciesFilament &&rhs) noexcept
Move constructor.
SpeciesFilament & operator= (const SpeciesFilament &rhs)
Regular Assignment.
SpeciesFilament & operator= (SpeciesFilament &&rhs)
Move assignment.
virtual SpeciesFilament * clone ()
virtual string getFullName () const
Return the full name of this Species in a string format (e.g. "Actin{Filament}".
~SpeciesFilament () noexcept
Default destructor.
Composite * getParent ()
void setParent (Composite *other)
bool hasParent () const
Composite * getRoot ()
RSpecies & getRSpecies ()
Return a reference to RSpecies.
const RSpecies & getRSpecies () const
Return a constant reference to RSpecies.
void setN (species_copy_t n)
Sets the copy number for this Species.
species_copy_t getN () const
Return the current copy number of this Species.
string getName () const
Return this Species' name.
int getMolecule () const
Return the molecule index associated with this Species' (as int)
virtual size_t countSpecies () const
Detailed Description
Used for species that can be in a Filament.
These species can not move cross-compartment.
Definition at line 385 of file Species.h.
Constructor & Destructor Documentation
SpeciesFilament::SpeciesFilament () inline
Default constructor.
Definition at line 388 of file Species.h.
Referenced by clone().
SpeciesFilament::SpeciesFilament (const string & name, species_copy_t n = 0, species_copy_t ulim = 1) inline
The main constructor.
Parameters
name - Example, "G-Actin" or "Arp2/3"
n - copy number
Definition at line 393 of file Species.h.
SpeciesFilament::SpeciesFilament (const SpeciesFilament & rhs) inline
Copy constructor.
Definition at line 397 of file Species.h.
SpeciesFilament::SpeciesFilament (SpeciesFilament && rhs) inline noexcept
Move constructor.
Definition at line 400 of file Species.h.
SpeciesFilament::~SpeciesFilament () inline noexcept
Default destructor.
Definition at line 424 of file Species.h.
Member Function Documentation
virtual SpeciesFilament* SpeciesFilament::clone () inline virtual
Reimplemented from Species.
Definition at line 416 of file Species.h.
References SpeciesFilament().
Referenced by CMonomer::CMonomer().
virtual size_t Species::countSpecies () const inline virtual inherited
Definition at line 295 of file Species.h.
virtual string SpeciesFilament::getFullName () const inline virtual
Return the full name of this Species in a string format (e.g. "Actin{Filament}".
Reimplemented from Species.
Definition at line 421 of file Species.h.
References Species::getName().
int Species::getMolecule () const inline inherited
Return the molecule index associated with this Species' (as int)
Definition at line 241 of file Species.h.
References Species::_molecule.
Referenced by Compartment::addSpeciesBound(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPlusEnd(), Compartment::addSpeciesUnique(), and Compartment::setDiffusionRate().
species_copy_t Species::getN () const inline inherited
Return the current copy number of this Species.
Definition at line 230 of file Species.h.
References Species::_rspecies, and RSpecies::getN().
Referenced by Linker::Linker(), main(), MotorGhost::MotorGhost(), operator<<(), Species::operator=(), CMonomer::print(), Species::Species(), Linker::~Linker(), and MotorGhost::~MotorGhost().
string Species::getName () const inline inherited
Return this Species' name.
Definition at line 238 of file Species.h.
References Species::_molecule, SpeciesNamesDB::Instance(), and SpeciesNamesDB::intToString().
Referenced by Species::getFullName(), SpeciesBulk::getFullName(), SpeciesDiffusing::getFullName(), getFullName(), SpeciesBound::getFullName(), SpeciesLinker::getFullName(), SpeciesMotor::getFullName(), SpeciesPlusEnd::getFullName(), SpeciesMinusEnd::getFullName(), and CMonomer::print().
Composite* Species::getParent () inline inherited
Definition at line 209 of file Species.h.
References Species::_parent.
Referenced by Species::getRoot(), and main().
Composite * Species::getRoot () inherited
Definition at line 36 of file Species.cpp.
References Species::getParent(), Component::getRoot(), and Species::hasParent().
RSpecies& Species::getRSpecies () inline inherited
Return a reference to RSpecies.
Notice that value copying won't be allowed because RSpecies is not copyable.
Definition at line 219 of file Species.h.
References Species::_rspecies.
Referenced by ChemSignal::connect(), SimpleManagerImpl::initializeCCylinder(), Linker::Linker(), main(), MotorGhost::MotorGhost(), Linker::~Linker(), and MotorGhost::~MotorGhost().
const RSpecies& Species::getRSpecies () const inline inherited
Return a constant reference to RSpecies.
Definition at line 222 of file Species.h.
References Species::_rspecies.
bool Species::hasParent () const inline inherited
Definition at line 213 of file Species.h.
References Species::_parent.
Referenced by Species::getRoot().
SpeciesFilament& SpeciesFilament::operator= (const SpeciesFilament & rhs) inline
Regular Assignment.
Definition at line 404 of file Species.h.
References Species::operator=().
SpeciesFilament& SpeciesFilament::operator= (SpeciesFilament && rhs) inline
Move assignment.
Definition at line 410 of file Species.h.
References Species::operator=().
void Species::setN (species_copy_t n) inline inherited
Sets the copy number for this Species.
Parameters
n should be a non-negative number, but no checking is done in run time
Note
The operation does not emit any signals about the copy number change.
Definition at line 227 of file Species.h.
References Species::_rspecies, and RSpecies::setN().
void Species::setParent (Composite * other) inline inherited
Definition at line 211 of file Species.h.
References Species::_parent.
Referenced by Compartment::addSpeciesBound(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPlusEnd(), and Compartment::addSpeciesUnique().
The documentation for this class was generated from the following file:
M3SYM/Structure/Species.h