MEDYAN: FilamentBindingManager Class Reference
FilamentBindingManager Class Reference abstract
To store and manage binding reactions.
#include <BindingManager.h>
Public Member Functions
FilamentBindingManager (ReactionBase *reaction, Compartment *compartment, short boundInt, string boundName, short filamentType)
~FilamentBindingManager ()
virtual void updateAllPossibleBindings ()=0
update all possible binding reactions that could occur
virtual int numBindingSites ()=0
Get current number of binding sites.
short getBoundInt ()
Get the bound species integer index.
string getBoundName ()
Get the bound species name.
void setNLIndex (int index)
Set the index of this manager, for access to NeighborList.
void setMIndex (int index)
Set the index of this manager, for access to other managers.
virtual bool isConsistent ()=0
Check consistency and correctness of binding sites. Used for debugging.
short getfilamentType ()
get the filament that the species binds to aravind June 30, 2016.
virtual void appendpossibleBindings (tuple< CCylinder *, short > t1, tuple< CCylinder *, short > t2)=0
ARAVIND ADDED FEB 17 2016. append possible bindings.
vector< string > getrxnspecies ()
aravind, June 30,2016.
virtual void clearpossibleBindings ()=0
virtual void addPossibleBindings (CCylinder *cc, short bindingSite)=0
add possible binding reactions that could occur
virtual void addPossibleBindings (CCylinder *cc)=0
add possible binding reactions that could occur
virtual void removePossibleBindings (CCylinder *cc, short bindingSite)=0
Remove all bindings including this cylinder.
virtual void removePossibleBindings (CCylinder *cc)=0
Remove all bindings including this cylinder.
Protected Member Functions
void updateBindingReaction (int oldN, int newN)
helper function to update copy number and reactions
Protected Attributes
ReactionBase * _bindingReaction
The binding reaction for this compartment.
Compartment * _compartment
Compartment this is in.
short _boundInt
Integer index in CMonomer of bound chemical value.
string _boundName
String name of bound chemical value.
short _filamentType
The filament type to operate on.
Species * _bindingSpecies
The binding species that this manager tracks.
short _nlIndex = 0
Index of this manager (for access of neighbor lists)
short _mIndex = 0
Index of this manager (for access in other compartments)
Static Protected Attributes
static SubSystem * _subSystem = 0
Ptr to the SubSystem.
Friends
class ChemManager
Detailed Description
To store and manage binding reactions.
FilamentBindingManager is used to store a binding Reaction on Filaments in Compartment. Contains the binding reaction, possible binding sites, and integers representing the binding species involved in the reaction. Classes that extend this will implement their own data structures for holding possible reaction sites, etc.
The main function of this class is to call updatePossibleBindings(), which will update the possible binding sites if the binding reaction is called in this compartment. Also contains functions to replace ccylinders in the structure, as well as remove a ccylinder from the structure when it is removed from the subsystem.
When the binding reaction is fired, the manager will choose a random binding based on its current data structure state, and perform whatever callback is associated with that binding reaction.
Definition at line 60 of file BindingManager.h.
Constructor & Destructor Documentation
FilamentBindingManager()
FilamentBindingManager::FilamentBindingManager (ReactionBase * reaction, Compartment * compartment, short boundInt, string boundName, short filamentType) inline
Definition at line 113 of file BindingManager.h.
~FilamentBindingManager()
FilamentBindingManager::~FilamentBindingManager () inline
Definition at line 128 of file BindingManager.h.
References addPossibleBindings(), numBindingSites(), removePossibleBindings(), and updateAllPossibleBindings().
Member Function Documentation
addPossibleBindings() [1/2]
virtual void FilamentBindingManager::addPossibleBindings (CCylinder * cc, short bindingSite) pure virtual
add possible binding reactions that could occur
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
Referenced by BranchingManager::~BranchingManager(), ~FilamentBindingManager(), LinkerBindingManager::~LinkerBindingManager(), and MotorBindingManager::~MotorBindingManager().
addPossibleBindings() [2/2]
virtual void FilamentBindingManager::addPossibleBindings (CCylinder * cc) pure virtual
add possible binding reactions that could occur
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
appendpossibleBindings()
virtual void FilamentBindingManager::appendpossibleBindings (tuple< CCylinder *, short > t1, tuple< CCylinder *, short > t2) pure virtual
ARAVIND ADDED FEB 17 2016. append possible bindings.
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
Referenced by getfilamentType().
clearpossibleBindings()
virtual void FilamentBindingManager::clearpossibleBindings () pure virtual
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
Referenced by getrxnspecies().
getBoundInt()
short FilamentBindingManager::getBoundInt () inline
Get the bound species integer index.
Definition at line 149 of file BindingManager.h.
References _boundInt.
getBoundName()
string FilamentBindingManager::getBoundName () inline
Get the bound species name.
Definition at line 151 of file BindingManager.h.
References _boundName.
getfilamentType()
short FilamentBindingManager::getfilamentType () inline
get the filament that the species binds to aravind June 30, 2016.
Definition at line 163 of file BindingManager.h.
References _filamentType, and appendpossibleBindings().
getrxnspecies()
vector<string> FilamentBindingManager::getrxnspecies () inline
aravind, June 30,2016.
Definition at line 168 of file BindingManager.h.
References clearpossibleBindings(), and ReactionBase::getreactantspecies().
isConsistent()
virtual bool FilamentBindingManager::isConsistent () pure virtual
Check consistency and correctness of binding sites. Used for debugging.
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
Referenced by BranchingManager::chooseBindingSite(), LinkerBindingManager::chooseBindingSites(), MotorBindingManager::chooseBindingSites(), and setMIndex().
numBindingSites()
virtual int FilamentBindingManager::numBindingSites () pure virtual
Get current number of binding sites.
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
Referenced by BranchingManager::appendpossibleBindings(), LinkerBindingManager::appendpossibleBindings(), MotorBindingManager::appendpossibleBindings(), BranchingManager::clearpossibleBindings(), LinkerBindingManager::clearpossibleBindings(), MotorBindingManager::clearpossibleBindings(), updateBindingReaction(), and ~FilamentBindingManager().
removePossibleBindings() [1/2]
virtual void FilamentBindingManager::removePossibleBindings (CCylinder * cc, short bindingSite) pure virtual
Remove all bindings including this cylinder.
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
Referenced by BranchingManager::~BranchingManager(), ~FilamentBindingManager(), LinkerBindingManager::~LinkerBindingManager(), and MotorBindingManager::~MotorBindingManager().
removePossibleBindings() [2/2]
virtual void FilamentBindingManager::removePossibleBindings (CCylinder * cc) pure virtual
Remove all bindings including this cylinder.
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
setMIndex()
void FilamentBindingManager::setMIndex (int index) inline
Set the index of this manager, for access to other managers.
Definition at line 157 of file BindingManager.h.
References isConsistent().
Referenced by ChemManager::genFilBindingReactions().
setNLIndex()
void FilamentBindingManager::setNLIndex (int index) inline
Set the index of this manager, for access to NeighborList.
Definition at line 154 of file BindingManager.h.
Referenced by ChemManager::genFilBindingReactions().
updateAllPossibleBindings()
virtual void FilamentBindingManager::updateAllPossibleBindings () pure virtual
update all possible binding reactions that could occur
Implemented in MotorBindingManager, LinkerBindingManager, and BranchingManager.
Referenced by BranchingManager::~BranchingManager(), ~FilamentBindingManager(), LinkerBindingManager::~LinkerBindingManager(), and MotorBindingManager::~MotorBindingManager().
updateBindingReaction()
void FilamentBindingManager::updateBindingReaction (int oldN, int newN) inline protected
helper function to update copy number and reactions
Definition at line 85 of file BindingManager.h.
References Species::down(), Species::getN(), numBindingSites(), Species::up(), and ReactionBase::updatePropensity().
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingManager::appendpossibleBindings(), LinkerBindingManager::appendpossibleBindings(), MotorBindingManager::appendpossibleBindings(), BranchingManager::clearpossibleBindings(), LinkerBindingManager::clearpossibleBindings(), MotorBindingManager::clearpossibleBindings(), BranchingManager::removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
Friends And Related Function Documentation
ChemManager
friend class ChemManager friend
Definition at line 62 of file BindingManager.h.
Member Data Documentation
_bindingReaction
ReactionBase* FilamentBindingManager::_bindingReaction protected
The binding reaction for this compartment.
Definition at line 65 of file BindingManager.h.
_bindingSpecies
Species* FilamentBindingManager::_bindingSpecies protected
The binding species that this manager tracks.
Resposible for all copy number changes
Definition at line 76 of file BindingManager.h.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingManager::BranchingManager(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), BranchingManager::removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_boundInt
short FilamentBindingManager::_boundInt protected
Integer index in CMonomer of bound chemical value.
Note
- THIS ALSO REPRESENTS THE SPECIES TYPE THAT IS MANAGED.
Definition at line 69 of file BindingManager.h.
Referenced by getBoundInt().
_boundName
string FilamentBindingManager::_boundName protected
String name of bound chemical value.
Definition at line 72 of file BindingManager.h.
Referenced by getBoundName().
_compartment
Compartment* FilamentBindingManager::_compartment protected
Compartment this is in.
Definition at line 67 of file BindingManager.h.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingManager::BranchingManager(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_filamentType
short FilamentBindingManager::_filamentType protected
The filament type to operate on.
Definition at line 74 of file BindingManager.h.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), getfilamentType(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), BranchingManager::removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_mIndex
short FilamentBindingManager::_mIndex = 0 protected
Index of this manager (for access in other compartments)
Definition at line 80 of file BindingManager.h.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), LinkerBindingManager::removePossibleBindings(), and MotorBindingManager::removePossibleBindings().
_nlIndex
short FilamentBindingManager::_nlIndex = 0 protected
Index of this manager (for access of neighbor lists)
Definition at line 79 of file BindingManager.h.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), MotorBindingManager::isConsistent(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), and MotorBindingManager::updateAllPossibleBindings().
_subSystem
SubSystem * FilamentBindingManager::_subSystem = 0 static protected
Ptr to the SubSystem.
Definition at line 82 of file BindingManager.h.
Referenced by BranchingManager::addPossibleBindings(), ChemManager::genFilBindingReactions(), MotorBindingManager::isConsistent(), and BranchingManager::updateAllPossibleBindings().
The documentation for this class was generated from the following files:
src/Chemistry/BindingManager.h
src/Chemistry/BindingManager.cpp