M3Sym: TypeVisitorLambda< ComponentType > Class Template Reference
TypeVisitorLambda< ComponentType > Class Template Reference
#include <Visitor.h>
Public Member Functions
void setLambda (std::function< bool(Component *)> g)
Sets the action to be perfomed on each node as std::function<bool (Component*)> g.
void setLambdaPred (std::function< bool(Component *)> pred)
Sets the predicate which checks whether the node should be evaluated as std::function<bool (Component*)> g.
bool visit (Component *c)
When this conditional Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
Protected Member Functions
virtual bool predImpl (Component *c) override
Implementation of the pred(...) method.
virtual bool visitImpl (Component *c) override
Implementation of the visit(...) method.
Protected Attributes
std::function< bool(Component *)> _f
The function to be perfomed on each node.
std::function< bool(Component *)> _pred = [](Component*){return true;}
The predicate which checks whether the node should be evaluated.
Detailed Description
template<class ComponentType>
class TypeVisitorLambda< ComponentType >
Definition at line 92 of file Visitor.h.
Member Function Documentation
template<class ComponentType> virtual bool TypeVisitorLambda< ComponentType >::predImpl (Component * c) inline override protected virtual
Implementation of the pred(...) method.
Reimplemented from VisitorLambda.
Definition at line 94 of file Visitor.h.
References VisitorLambda::predImpl().
void VisitorLambda::setLambda (std::function< bool(Component *)> g) inline inherited
Sets the action to be perfomed on each node as std::function<bool (Component*)> g.
Definition at line 68 of file Visitor.h.
References VisitorLambda::_f.
Referenced by main().
void VisitorLambda::setLambdaPred (std::function< bool(Component *)> pred) inline inherited
Sets the predicate which checks whether the node should be evaluated as std::function<bool (Component*)> g.
Definition at line 71 of file Visitor.h.
References VisitorLambda::_pred.
bool Visitor::visit (Component * c) inline inherited
When this conditional Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(c), if v->pred(c) returns true.
If v->visit(c) returns a false value, then the further propagation of the tree is terminated.
Definition at line 39 of file Visitor.h.
References Visitor::predImpl(), and Visitor::visitImpl().
Referenced by Component::apply(), and Composite::apply().
virtual bool VisitorLambda::visitImpl (Component * c) inline override protected virtual inherited
Implementation of the visit(...) method.
Implements Visitor.
Definition at line 77 of file Visitor.h.
References VisitorLambda::_f.
Member Data Documentation
std::function<bool (Component*)> VisitorLambda::_f protected inherited
The function to be perfomed on each node.
Definition at line 73 of file Visitor.h.
Referenced by VisitorLambda::setLambda(), and VisitorLambda::visitImpl().
std::function<bool (Component*)> VisitorLambda::_pred = [](Component*){return true;} protected inherited
The predicate which checks whether the node should be evaluated.
Definition at line 74 of file Visitor.h.
Referenced by VisitorLambda::predImpl(), and VisitorLambda::setLambdaPred().
The documentation for this class was generated from the following file:
M3SYM/Visitor.h