MEDYAN: PolyPlusEndTemplate Class Reference
PolyPlusEndTemplate Class Reference
Template for polymerization at plus end of Filament.
#include <ReactionTemplate.h>
Public Member Functions
PolyPlusEndTemplate (short filamentType, vector< tuple< int, SpeciesType >> reactants, vector< tuple< int, SpeciesType >> products, float rate)
~PolyPlusEndTemplate ()
virtual void addReaction (CCylinder *cc)
Add this chemical reaction. Adds all extension and retraction callbacks needed.
virtual void addReaction (CCylinder *cc1, CCylinder *cc2)
Add this chemical reaction along a filament.
Protected Attributes
short _filamentType
Filament type that this template acts on.
vector< tuple< int, SpeciesType > > _reactants
Reactants in this reaction.
vector< tuple< int, SpeciesType > > _products
Products in this reaction.
float _rate
Rate of reaction.
Static Protected Attributes
static SubSystem * _ps = 0
A subsystem pointer to initialize and call chemical callbacks.
Detailed Description
Template for polymerization at plus end of Filament.
Definition at line 87 of file ReactionTemplate.h.
Constructor & Destructor Documentation
PolyPlusEndTemplate()
PolyPlusEndTemplate::PolyPlusEndTemplate (short filamentType, vector< tuple< int, SpeciesType >> reactants, vector< tuple< int, SpeciesType >> products, float rate) inline
Definition at line 90 of file ReactionTemplate.h.
~PolyPlusEndTemplate()
PolyPlusEndTemplate::~PolyPlusEndTemplate () inline
Definition at line 95 of file ReactionTemplate.h.
References FilamentReactionTemplate::addReaction().
Member Function Documentation
addReaction() [1/2]
void PolyPlusEndTemplate::addReaction (CCylinder * cc) virtual
Add this chemical reaction. Adds all extension and retraction callbacks needed.
Implements FilamentReactionTemplate.
Definition at line 27 of file ReactionTemplate.cpp.
References CCylinder::addInternalReaction(), ChemParams::bindingIndices, BULK, SysParams::Chemistry(), DIFFUSING, Compartment::findSpeciesByMolecule(), CCylinder::getCMonomer(), CCylinder::getCompartment(), CCylinder::getCylinder(), getInt(), CCylinder::getSize(), getType(), POLYMERIZATIONPLUSEND, ReactionBase::setReactionType(), CMonomer::speciesBound(), CMonomer::speciesFilament(), and CMonomer::speciesPlusEnd().
addReaction() [2/2]
virtual void PolyPlusEndTemplate::addReaction (CCylinder * cc1, CCylinder * cc2) inline virtual
Add this chemical reaction along a filament.
Note
assumes cc1 and cc2 are in order, that is, cc2 is the next cylinder after cc1
Implements FilamentReactionTemplate.
Definition at line 98 of file ReactionTemplate.h.
Member Data Documentation
_filamentType
short FilamentReactionTemplate::_filamentType protected inherited
Filament type that this template acts on.
Definition at line 54 of file ReactionTemplate.h.
_products
vector<tuple<int,SpeciesType> > FilamentReactionTemplate::_products protected inherited
Products in this reaction.
Definition at line 57 of file ReactionTemplate.h.
_ps
SubSystem * FilamentReactionTemplate::_ps = 0 static protected inherited
A subsystem pointer to initialize and call chemical callbacks.
Definition at line 52 of file ReactionTemplate.h.
Referenced by SeveringTemplate::addReaction(), and CController::initialize().
_rate
float FilamentReactionTemplate::_rate protected inherited
Rate of reaction.
Definition at line 59 of file ReactionTemplate.h.
_reactants
vector<tuple<int,SpeciesType> > FilamentReactionTemplate::_reactants protected inherited
Reactants in this reaction.
Definition at line 56 of file ReactionTemplate.h.
The documentation for this class was generated from the following files:
src/Chemistry/ReactionTemplate.h
src/Chemistry/ReactionTemplate.cpp