MEDYAN: RSpeciesReg Class Reference
RSpeciesReg Class Reference
A RSpecies implementation that changes copy number regularly.
#include <RSpecies.h>
Public Member Functions
RSpeciesReg (Species &parent, species_copy_t n=0, species_copy_t ulim=max_ulim)
Constructors.
RSpeciesReg (const RSpeciesReg &r)=delete
deleted copy constructor - each RSpeciesRegular is uniquely created by the parent Species
RSpeciesReg (RSpeciesReg &&r)=delete
deleted move constructor - each RSpeciesRegular is uniquely created by the parent Species
RSpeciesReg & operator= (RSpeciesReg &)=delete
deleted assignment operator - each RSpeciesRegular is uniquely created by the parent Species
virtual void up ()
If the copy number changes from 0 to 1, calls a "callback"-like method to activate previously passivated [Reactions](Reaction), where this RSpecies is a Reactant.
virtual void down ()
If the copy number changes from 1 to 0, calls a "callback"-like method to passivate previously activated [Reactions](Reaction), where this RSpecies is a Reactant.
virtual float getN () const
Return the true copy number.
void setN (species_copy_t n)
Sets the copy number for this RSpecies.
void addAsReactant (ReactionBase *r)
void addAsProduct (ReactionBase *r)
void removeAsReactant (const ReactionBase *r)
void removeAsProduct (const ReactionBase *r)
void activateAssocReactantReactions ()
void activateAssocProductReactions ()
void passivateAssocReactantReactions ()
void passivateAssocProductReactions ()
Species & getSpecies ()
return parent Species as a reference
const Species & getSpecies () const
return parent Species as a const reference
string getFullName () const
Return the full name of this Species in a string format (e.g. "Arp2/3{Bulk}")
vector< ReactionBase * > & reactantReactions ()
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Reactant.
vector< ReactionBase * > & productReactions ()
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Product.
vr_iterator beginReactantReactions ()
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Reactant.
vr_iterator beginProductReactions ()
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Product.
vr_iterator endReactantReactions ()
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Reactant.
vr_iterator endProductReactions ()
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Product.
virtual species_copy_t getTrueN () const
Return the true copy number of this RSpecies.
Protected Attributes
vector< ReactionBase * > _as_reactants = {}
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
vector< ReactionBase * > _as_products = {}
a vector of Reactions where this RSpecies is a Product
Species & _species
reference to the parent Species object
species_copy_t _n
Current copy number of this RSpecies.
RSpeciesType _type
The RSpecies type.
Detailed Description
A RSpecies implementation that changes copy number regularly.
The RSpeciesReg class represents a typical RSpecies. Upon calling up() or down(), the copy number is incremented normally. getN() and getTrueN() both return the true copy number tracked in the base class.
The RSpeciesReg can be used for any type of Species in the chemical system.
Definition at line 279 of file RSpecies.h.
Constructor & Destructor Documentation
RSpeciesReg() [1/3]
RSpeciesReg::RSpeciesReg (Species & parent, species_copy_t n = 0, species_copy_t ulim = max_ulim) inline
Constructors.
Definition at line 283 of file RSpecies.h.
References RSpecies::_type, RSpecies::operator=(), and REG.
RSpeciesReg() [2/3]
RSpeciesReg::RSpeciesReg (const RSpeciesReg & r) delete
deleted copy constructor - each RSpeciesRegular is uniquely created by the parent Species
RSpeciesReg() [3/3]
RSpeciesReg::RSpeciesReg (RSpeciesReg && r) delete
deleted move constructor - each RSpeciesRegular is uniquely created by the parent Species
Member Function Documentation
activateAssocProductReactions()
void RSpecies::activateAssocProductReactions () inherited
Attempts to activate previously passivated Reactions where this RSpecies is involved as a Product. Usually, the Reaction was first passivated, for example if the RSpecies copy number of one of the reactants went up to max_ulim.
Definition at line 77 of file RSpecies.cpp.
References RSpecies::_as_products.
Referenced by down(), RSpeciesAvg::down(), and RSpecies::removeAsProduct().
activateAssocReactantReactions()
void RSpecies::activateAssocReactantReactions () inherited
Attempts to activate previously passivated Reactions where this RSpecies is involved as a Reactant. Usually, the Reaction was first passivated, for example if the RSpecies copy number of one of the reactants dropeed to zero. This attempt may not succeed if there are still other reactants in the same Reaction with zero copy count.
Definition at line 72 of file RSpecies.cpp.
References RSpecies::_as_reactants.
Referenced by RSpecies::removeAsProduct(), up(), and RSpeciesAvg::up().
addAsProduct()
void RSpecies::addAsProduct (ReactionBase * r) inline inherited
Definition at line 138 of file RSpecies.h.
addAsReactant()
void RSpecies::addAsReactant (ReactionBase * r) inline inherited
Definition at line 134 of file RSpecies.h.
beginProductReactions()
vr_iterator RSpecies::beginProductReactions () inline inherited
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Product.
Definition at line 249 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
beginReactantReactions()
vr_iterator RSpecies::beginReactantReactions () inline inherited
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Reactant.
Definition at line 245 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
down()
virtual void RSpeciesReg::down () inline virtual
If the copy number changes from 1 to 0, calls a "callback"-like method to passivate previously activated [Reactions](Reaction), where this RSpecies is a Reactant.
Also emits a signal with the change in copy number if attached.
Implements RSpecies.
Definition at line 332 of file RSpecies.h.
References RSpecies::_n, RSpecies::activateAssocProductReactions(), and RSpecies::passivateAssocReactantReactions().
endProductReactions()
vr_iterator RSpecies::endProductReactions () inline inherited
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Product.
Definition at line 257 of file RSpecies.h.
References RSpecies::down(), RSpecies::getN(), and RSpecies::up().
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
endReactantReactions()
vr_iterator RSpecies::endReactantReactions () inline inherited
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Reactant.
Definition at line 253 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
getFullName()
string RSpecies::getFullName () const inherited
Return the full name of this Species in a string format (e.g. "Arp2/3{Bulk}")
Definition at line 67 of file RSpecies.cpp.
References RSpecies::_species, and Species::getFullName().
Referenced by RSpecies::getSpecies(), and operator<<().
getN()
virtual float RSpeciesReg::getN () const inline virtual
Return the true copy number.
Implements RSpecies.
Definition at line 352 of file RSpecies.h.
References RSpecies::_n.
getSpecies() [1/2]
Species& RSpecies::getSpecies () inline inherited
return parent Species as a reference
Definition at line 227 of file RSpecies.h.
References RSpecies::_species.
Referenced by BranchingManager::BranchingManager(), CBranchingPoint::createOffReaction(), Reaction< 1, 1 >::is_equal(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), and CMotorGhost::moveMotorHead().
getSpecies() [2/2]
const Species& RSpecies::getSpecies () const inline inherited
return parent Species as a const reference
Definition at line 230 of file RSpecies.h.
References RSpecies::_species, and RSpecies::getFullName().
getTrueN()
virtual species_copy_t RSpecies::getTrueN () const inline virtual inherited
Return the true copy number of this RSpecies.
Definition at line 267 of file RSpecies.h.
References RSpecies::_n.
operator=()
RSpeciesReg& RSpeciesReg::operator= (RSpeciesReg &) delete
deleted assignment operator - each RSpeciesRegular is uniquely created by the parent Species
passivateAssocProductReactions()
void RSpecies::passivateAssocProductReactions () inherited
Passivates all Reactions where this RSpecies is among the products.
Definition at line 87 of file RSpecies.cpp.
References RSpecies::_as_products.
Referenced by RSpecies::removeAsProduct(), up(), and RSpeciesAvg::up().
passivateAssocReactantReactions()
void RSpecies::passivateAssocReactantReactions () inherited
Passivates all Reactions where this RSpecies is among the reactants.
Definition at line 82 of file RSpecies.cpp.
References RSpecies::_as_reactants.
Referenced by down(), RSpeciesAvg::down(), and RSpecies::removeAsProduct().
productReactions()
vector<ReactionBase *>& RSpecies::productReactions () inline inherited
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Product.
Definition at line 241 of file RSpecies.h.
References RSpecies::_as_products.
reactantReactions()
vector<ReactionBase *>& RSpecies::reactantReactions () inline inherited
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Reactant.
Definition at line 237 of file RSpecies.h.
References RSpecies::_as_reactants.
Referenced by Species::activateReactantReactions(), Species::passivateReactantReactions(), Species::updateReactantPropensities(), and MotorGhost::updateReactionRates().
removeAsProduct()
void RSpecies::removeAsProduct (const ReactionBase * r) inline inherited
Definition at line 158 of file RSpecies.h.
References RSpecies::activateAssocProductReactions(), RSpecies::activateAssocReactantReactions(), RSpecies::passivateAssocProductReactions(), RSpecies::passivateAssocReactantReactions(), and RSpecies::~RSpecies().
removeAsReactant()
void RSpecies::removeAsReactant (const ReactionBase * r) inline inherited
Definition at line 142 of file RSpecies.h.
setN()
void RSpecies::setN (species_copy_t n) inline inherited
Sets the copy number for this RSpecies.
Parameters
n should be a non-negative number, but no checking is done in run time
Note
The operation does not emit any signals about the copy number change.
Definition at line 121 of file RSpecies.h.
Referenced by Species::setN().
up()
virtual void RSpeciesReg::up () inline virtual
If the copy number changes from 0 to 1, calls a "callback"-like method to activate previously passivated [Reactions](Reaction), where this RSpecies is a Reactant.
Also emits a signal with the change in copy number if attached.
Implements RSpecies.
Definition at line 311 of file RSpecies.h.
References RSpecies::_n, RSpecies::activateAssocReactantReactions(), and RSpecies::passivateAssocProductReactions().
Member Data Documentation
_as_products
vector<ReactionBase *> RSpecies::_as_products = {} protected inherited
a vector of Reactions where this RSpecies is a Product
Definition at line 73 of file RSpecies.h.
Referenced by RSpecies::activateAssocProductReactions(), RSpecies::passivateAssocProductReactions(), RSpecies::productReactions(), and RSpecies::~RSpecies().
_as_reactants
vector<ReactionBase *> RSpecies::_as_reactants = {} protected inherited
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
a vector of Reactions where this RSpecies is a Reactant
Definition at line 70 of file RSpecies.h.
Referenced by RSpecies::activateAssocReactantReactions(), RSpecies::passivateAssocReactantReactions(), RSpecies::reactantReactions(), and RSpecies::~RSpecies().
_n
species_copy_t RSpecies::_n protected inherited
Current copy number of this RSpecies.
this RSpecies (usually when a single step of this Reaction occurs)
Definition at line 77 of file RSpecies.h.
Referenced by down(), RSpeciesConst::down(), RSpeciesAvg::down(), getN(), RSpecies::getTrueN(), up(), and RSpeciesAvg::up().
_species
Species& RSpecies::_species protected inherited
reference to the parent Species object
Definition at line 76 of file RSpecies.h.
Referenced by RSpecies::getFullName(), and RSpecies::getSpecies().
_type
RSpeciesType RSpecies::_type protected inherited
The RSpecies type.
Definition at line 88 of file RSpecies.h.
Referenced by Species::operator=(), RSpeciesAvg::RSpeciesAvg(), RSpeciesConst::RSpeciesConst(), RSpeciesReg(), and Species::Species().
The documentation for this class was generated from the following file:
src/Chemistry/RSpecies.h