MEDYAN: BoundaryCylinderAttachment< BAttachmentInteractionType > Class Template Reference
BoundaryCylinderAttachment< BAttachmentInteractionType > Class Template Reference
Represents an attractive interaction between a cylinder and its pin point near a boundary.
#include <BoundaryCylinderAttachment.h>
Public Member Functions
BoundaryCylinderAttachment ()
Constructor.
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual void computeLoadForces ()
Compute the load forces on beads from this interaction.
virtual NeighborList * getNeighborList ()
Just return null - no neighbor list here.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
BoundaryElement * _boundaryElementCulprit = nullptr
In the case of an error.
Component * _otherCulprit = nullptr
In the case of an error.
Private Attributes
BAttachmentInteractionType _FFType
Detailed Description
template<class BAttachmentInteractionType>
class BoundaryCylinderAttachment< BAttachmentInteractionType >
Represents an attractive interaction between a cylinder and its pin point near a boundary.
Note
- This BoundaryInteractions implementation really does not involve Boundaries at all. The pinned position of the beads is preset by the special protocol in which Bead elements are chosen with the criteria of being a certain distance away from the Boundary. In reality, any Bead could be pinned at a certain position, but for now associating this potential with a Boundary makes more sense.
Definition at line 37 of file BoundaryCylinderAttachment.h.
Constructor & Destructor Documentation
BoundaryCylinderAttachment()
template<class BAttachmentInteractionType > BoundaryCylinderAttachment< BAttachmentInteractionType >::BoundaryCylinderAttachment () inline
Constructor.
Definition at line 44 of file BoundaryCylinderAttachment.h.
References BoundaryCylinderAttachment< BAttachmentInteractionType >::computeEnergy(), BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForces(), and BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForcesAux().
Member Function Documentation
computeEnergy()
template<class BAttachmentInteractionType > template double BoundaryCylinderAttachment< BAttachmentInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BoundaryInteractions.
Definition at line 23 of file BoundaryCylinderAttachment.cpp.
References Bead::getPinnedBeads(), SysParams::Mechanics(), and MechParams::pinK.
Referenced by BoundaryCylinderAttachment< BAttachmentInteractionType >::BoundaryCylinderAttachment(), and BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForcesAux().
computeForces()
template<class BAttachmentInteractionType > template void BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements BoundaryInteractions.
Definition at line 54 of file BoundaryCylinderAttachment.cpp.
References Bead::getPinnedBeads(), SysParams::Mechanics(), and MechParams::pinK.
Referenced by BoundaryCylinderAttachment< BAttachmentInteractionType >::BoundaryCylinderAttachment(), and BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForcesAux().
computeForcesAux()
template<class BAttachmentInteractionType > template void BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements BoundaryInteractions.
Definition at line 65 of file BoundaryCylinderAttachment.cpp.
References BoundaryCylinderAttachment< BAttachmentInteractionType >::computeEnergy(), BoundaryCylinderAttachment< BAttachmentInteractionType >::computeForces(), Bead::getPinnedBeads(), SysParams::Mechanics(), and MechParams::pinK.
Referenced by BoundaryCylinderAttachment< BAttachmentInteractionType >::BoundaryCylinderAttachment().
computeLoadForces()
template<class BAttachmentInteractionType > virtual void BoundaryCylinderAttachment< BAttachmentInteractionType >::computeLoadForces () inline virtual
Compute the load forces on beads from this interaction.
Implements BoundaryInteractions.
Definition at line 51 of file BoundaryCylinderAttachment.h.
getName()
template<class BAttachmentInteractionType > virtual const string BoundaryCylinderAttachment< BAttachmentInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BoundaryInteractions.
Definition at line 56 of file BoundaryCylinderAttachment.h.
getNeighborList()
template<class BAttachmentInteractionType > virtual NeighborList* BoundaryCylinderAttachment< BAttachmentInteractionType >::getNeighborList () inline virtual
Just return null - no neighbor list here.
Implements BoundaryInteractions.
Definition at line 54 of file BoundaryCylinderAttachment.h.
Member Data Documentation
_boundaryElementCulprit
BoundaryElement* BoundaryInteractions::_boundaryElementCulprit = nullptr protected inherited
In the case of an error.
Definition at line 33 of file BoundaryInteractions.h.
Referenced by BoundaryFF::whoIsCulprit().
_FFType
template<class BAttachmentInteractionType > BAttachmentInteractionType BoundaryCylinderAttachment< BAttachmentInteractionType >::_FFType private
Definition at line 40 of file BoundaryCylinderAttachment.h.
_otherCulprit
Component* BoundaryInteractions::_otherCulprit = nullptr protected inherited
In the case of an error.
Definition at line 34 of file BoundaryInteractions.h.
Referenced by BoundaryFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Boundary/BoundaryCylinderAttachment.h
src/Mechanics/ForceField/Boundary/BoundaryCylinderAttachment.cpp