MEDYAN: ReactionPtrContainerVector Class Reference
ReactionPtrContainerVector Class Reference
A concrete class implementing the ReactionPtrContainerIFace, using vector<unique_ptr<ReactionBase>> as the container implementation.
#include <ReactionContainer.h>
Public Member Functions
ReactionPtrContainerVector ()
Default constructor.
ReactionPtrContainerVector (const ReactionPtrContainerVector &)=delete
Copying not allowed.
ReactionPtrContainerVector & operator= (ReactionPtrContainerVector &)=delete
Assignment not allowed.
virtual void clear ()
Clear the container.
virtual ReactionBase * addReactionUnique (unique_ptr< ReactionBase > &&Reaction)
Add a unique reaction ptr to this container.
template<unsigned short M, unsigned short N, typename ... Args>
ReactionBase * addReaction (Args &&...args)
Add a general reaction to this container.
template<template< unsigned short M, unsigned short N > class RXN, unsigned short M, unsigned short N>
ReactionBase * add (initializer_list< Species *> species, float rate)
Add a general reaction class to this container.
virtual void removeReaction (ReactionBase *R)
Remove a reaction from this container.
virtual void updatePropensityComprtment ()
virtual void removeReactions (Species *s)
Remove all reactions that contain a certain species from this container.
virtual ReactionBase * findReaction (size_t index)
Find a reaction by index in this container.
vector< unique_ptr< ReactionBase > > & reactions ()
Get all reactions in vector form.
const vector< unique_ptr< ReactionBase > > & reactions () const
virtual void printReactions ()
Print all reactions in this container.
virtual ReactionBase * findSimilarReaction (const ReactionBase &r)
Find a similar reaction in this container (satistifes equality operator)
virtual void printReaction ()
Print all reactions from this container.
Protected Attributes
vector< unique_ptr< ReactionBase > > _reactions
Reaction ptr container.
Friends
void swap (ReactionPtrContainerVector &first, ReactionPtrContainerVector &second)
Detailed Description
A concrete class implementing the ReactionPtrContainerIFace, using vector<unique_ptr<ReactionBase>> as the container implementation.
Definition at line 42 of file ReactionContainer.h.
Constructor & Destructor Documentation
ReactionPtrContainerVector() [1/2]
ReactionPtrContainerVector::ReactionPtrContainerVector () inline
Default constructor.
Definition at line 48 of file ReactionContainer.h.
ReactionPtrContainerVector() [2/2]
ReactionPtrContainerVector::ReactionPtrContainerVector (const ReactionPtrContainerVector &) delete
Copying not allowed.
Member Function Documentation
add()
template<template< unsigned short M, unsigned short N > class RXN, unsigned short M, unsigned short N> ReactionBase* ReactionPtrContainerVector::add (initializer_list< Species *> species, float rate) inline
Add a general reaction class to this container.
Definition at line 85 of file ReactionContainer.h.
Referenced by CompartmentGrid::addBulk(), and Compartment::addInternal().
addReaction()
template<unsigned short M, unsigned short N, typename ... Args> ReactionBase* ReactionPtrContainerVector::addReaction (Args &&... args) inline
Add a general reaction to this container.
Definition at line 75 of file ReactionContainer.h.
Referenced by CompartmentGrid::addBulkReaction(), Compartment::addDiffusionReaction(), and Compartment::addInternalReaction().
addReactionUnique()
virtual ReactionBase* ReactionPtrContainerVector::addReactionUnique (unique_ptr< ReactionBase > && Reaction) inline virtual
Add a unique reaction ptr to this container.
Implements ReactionPtrContainerIFace.
Definition at line 68 of file ReactionContainer.h.
Referenced by CompartmentGrid::addBulkReactionUnique(), Compartment::addDiffusionReaction(), Compartment::addDiffusionReactionUnique(), Compartment::addInternalReaction(), and Compartment::addInternalReactionUnique().
clear()
virtual void ReactionPtrContainerVector::clear () inline virtual
Clear the container.
Implements ReactionPtrContainerIFace.
Definition at line 65 of file ReactionContainer.h.
Referenced by Compartment::operator=(), and Compartment::removeAllDiffusionReactions().
findReaction()
virtual ReactionBase* ReactionPtrContainerVector::findReaction (size_t index) inline virtual
Find a reaction by index in this container.
Note
no check on the index
Implements ReactionPtrContainerIFace.
Definition at line 119 of file ReactionContainer.h.
findSimilarReaction()
virtual ReactionBase* ReactionPtrContainerVector::findSimilarReaction (const ReactionBase & r) inline virtual
Find a similar reaction in this container (satistifes equality operator)
Note
returns the first similar reaction found
Definition at line 135 of file ReactionContainer.h.
Referenced by Compartment::findSimilarDiffusionReaction(), and Compartment::findSimilarInternalReaction().
operator=()
ReactionPtrContainerVector& ReactionPtrContainerVector::operator= (ReactionPtrContainerVector &) delete
Assignment not allowed.
printReaction()
virtual void ReactionPtrContainerIFace::printReaction () inline virtual inherited
Print all reactions from this container.
Definition at line 37 of file ReactionContainer.h.
printReactions()
virtual void ReactionPtrContainerVector::printReactions () inline virtual
Print all reactions in this container.
Definition at line 128 of file ReactionContainer.h.
Referenced by Compartment::printReactions().
reactions() [1/2]
vector<unique_ptr<ReactionBase> >& ReactionPtrContainerVector::reactions () inline
Get all reactions in vector form.
Definition at line 124 of file ReactionContainer.h.
Referenced by Compartment::addChemSimReactions(), Compartment::apply_impl(), Compartment::clearReactions(), Compartment::cloneReactions(), Compartment::numberOfInternalReactions(), Compartment::numberOfReactions(), operator==(), Compartment::removeAllDiffusionReactions(), and Compartment::removeDiffusionReactions().
reactions() [2/2]
const vector<unique_ptr<ReactionBase> >& ReactionPtrContainerVector::reactions () const inline
Definition at line 125 of file ReactionContainer.h.
removeReaction()
virtual void ReactionPtrContainerVector::removeReaction (ReactionBase * R) inline virtual
Remove a reaction from this container.
Implements ReactionPtrContainerIFace.
Definition at line 92 of file ReactionContainer.h.
Referenced by CompartmentGrid::removeBulkReaction(), Compartment::removeDiffusionReaction(), Compartment::removeDiffusionReactions(), and Compartment::removeInternalReaction().
removeReactions()
virtual void ReactionPtrContainerVector::removeReactions (Species * s) inline virtual
Remove all reactions that contain a certain species from this container.
Definition at line 106 of file ReactionContainer.h.
References ReactionPtrContainerIFace::removeReaction().
Referenced by CompartmentGrid::removeBulkReactions(), Compartment::removeDiffusionReactions(), and Compartment::removeInternalReactions().
updatePropensityComprtment()
virtual void ReactionPtrContainerVector::updatePropensityComprtment () inline virtual
Definition at line 101 of file ReactionContainer.h.
Referenced by Restart::setdiffspeciesnumber().
Friends And Related Function Documentation
swap
void swap (ReactionPtrContainerVector & first, ReactionPtrContainerVector & second) friend
Definition at line 56 of file ReactionContainer.h.
Member Data Documentation
_reactions
vector<unique_ptr<ReactionBase> > ReactionPtrContainerVector::_reactions protected
Reaction ptr container.
Definition at line 44 of file ReactionContainer.h.
The documentation for this class was generated from the following file:
src/Chemistry/ReactionContainer.h