MEDYAN: Controller Class Reference
Controller Class Reference
Used to initialize, manage, and run an entire simulation.
#include <Controller.h>
Public Member Functions
Controller (SubSystem *s)
~Controller ()
void initialize (string inputFile, string inputDirectory, string outputDirectory)
Initialize the system, given an input and output directory.
void run ()
Run the simulation.
Private Member Functions
void setupInitialNetwork (SystemParser &p)
INITIALIZATION HELPER FUNCTIONS.
void setupSpecialStructures (SystemParser &p)
Setup any special structures needed.
void moveBoundary (double deltaTau)
RUNTIME HELPER FUNCTIONS.
void updatePositions ()
Update the positions of all elements in the system.
void updateNeighborLists ()
Update neighbors lists, called in run.
void executeSpecialProtocols ()
Execute any special protocols needed, for example, making Linker and Filament species static.
void pinBoundaryFilaments ()
Helper function to pin filaments near the boundary.
Private Attributes
SubSystem * _subSystem
A pointer to the subsystem that this controls.
MController * _mController
Chemical controller used.
CController * _cController
Mechanical controller used.
GController * _gController
Geometry controller used.
DRController * _drController
Dynamic rate controller used.
string _inputDirectory
Input directory being used.
string _outputDirectory
Output directory being used.
vector< Output * > _outputs
Vector of specified outputs.
double _runTime
Total desired runtime for simulation.
double _snapshotTime
Desired time for each snapshot.
double _minimizationTime
Frequency of mechanical minimization.
double _neighborListTime
Frequency of neighbor list updates.
double _runSteps
Same parameter set as timestep, but in terms of chemical reaction steps.
double _snapshotSteps
Same parameter set as timestep, but in terms of chemical reaction steps.
double _minimizationSteps
Same parameter set as timestep, but in terms of chemical reaction steps.
double _neighborListSteps
Same parameter set as timestep, but in terms of chemical reaction steps.
ChemistryData _chemData
Same parameter set as timestep, but in terms of chemical reaction steps.
ChemistryAlgorithm _cAlgorithm
Same parameter set as timestep, but in terms of chemical reaction steps.
vector< tuple< short, vector< double >, vector< double > > > fil
Same parameter set as timestep, but in terms of chemical reaction steps.
tuple< vector< tuple< short, vector< double >, vector< double > > >, vector< tuple< string, short, vector< vector< double > > > >, vector< tuple< string, short, vector< double > > >, vector< vector< double > > > filaments
Same parameter set as timestep, but in terms of chemical reaction steps.
Detailed Description
Used to initialize, manage, and run an entire simulation.
The Controller is initialized in the main program, and initializes the SubSystem given an initial input directory. After initialization of all member controllers, the Controller class can run a simulation given the already read input parameters, by iteratively switching between mechanical equilibration and stochastic chemical steps. The Controller is also responsible for updating positions, reaction rates, and neighbors lists through its corresponding sub-controllers and the Subsystem.
Definition at line 40 of file Controller.h.
Constructor & Destructor Documentation
Controller()
Controller::Controller (SubSystem * s)
Definition at line 47 of file Controller.cpp.
References _cController, _drController, _gController, _mController, _subSystem, and Trackable::_subSystem.
~Controller()
Controller::~Controller () inline
Definition at line 113 of file Controller.h.
References initialize(), and run().
Member Function Documentation
executeSpecialProtocols()
void Controller::executeSpecialProtocols () private
Execute any special protocols needed, for example, making Linker and Filament species static.
Definition at line 395 of file Controller.cpp.
References SysParams::Chemistry(), Cylinder::getCylinders(), Linker::getLinkers(), SysParams::Mechanics(), pinBoundaryFilaments(), and tau().
Referenced by run().
initialize()
void Controller::initialize (string inputFile, string inputDirectory, string outputDirectory)
Initialize the system, given an input and output directory.
Definition at line 62 of file Controller.cpp.
References _cAlgorithm, _cController, _chemData, _drController, _gController, _inputDirectory, _mController, _minimizationSteps, _minimizationTime, _neighborListSteps, _neighborListTime, _outputDirectory, _outputs, _runSteps, _runTime, _snapshotSteps, _snapshotTime, _subSystem, SysParams::checkChemParameters(), SysParams::checkDyRateParameters(), SysParams::checkGeoParameters(), SysParams::checkMechParameters(), SubSystem::getCompartmentGrid(), DRController::initialize(), MController::initialize(), CController::initialize(), GController::initializeBoundary(), GController::initializeGrid(), SystemParser::readBoundaryType(), SystemParser::readBoundParams(), SystemParser::readChemistryAlgorithm(), ChemistryParser::readChemistryInput(), SystemParser::readChemistrySetup(), SystemParser::readChemParams(), SystemParser::readDynamicRateType(), SystemParser::readDyRateParams(), SystemParser::readGeoParams(), SystemParser::readMechanicsAlgorithm(), SystemParser::readMechanicsFFType(), SystemParser::readMechParams(), GController::setActiveCompartments(), setupInitialNetwork(), and setupSpecialStructures().
Referenced by main(), and ~Controller().
moveBoundary()
void Controller::moveBoundary (double deltaTau) private
RUNTIME HELPER FUNCTIONS.
Move the boundary based on the timestep
Definition at line 370 of file Controller.cpp.
References _cController, _subSystem, CController::activate(), SysParams::Boundaries(), CController::deactivate(), SubSystem::getBoundary(), SubSystem::getCompartmentGrid(), CompartmentGrid::getCompartments(), Boundary::move(), BoundParams::moveSpeed, tau(), and Boundary::within().
Referenced by run().
pinBoundaryFilaments()
void Controller::pinBoundaryFilaments () private
Helper function to pin filaments near the boundary.
Definition at line 449 of file Controller.cpp.
References _subSystem, Boundary::distance(), Bead::getBeads(), SubSystem::getBoundary(), Cylinder::getFirstBead(), Filament::getMinusEndCylinder(), Component::getParent(), Bead::getPinnedBeads(), Filament::getPlusEndCylinder(), Cylinder::getSecondBead(), SysParams::Mechanics(), and MechParams::pinDistance.
Referenced by executeSpecialProtocols().
run()
void Controller::run ()
Run the simulation.
Definition at line 481 of file Controller.cpp.
References _cController, _chemData, _mController, _minimizationSteps, _minimizationTime, _neighborListSteps, _neighborListTime, _outputs, _runSteps, _runTime, _snapshotSteps, _snapshotTime, _subSystem, Restart::addtoHeapbranchers(), Restart::addtoHeaplinkermotor(), areEqual(), executeSpecialProtocols(), filaments, BranchingPoint::getBranchingPoints(), SubSystem::getCompartmentGrid(), CompartmentGrid::getCompartments(), Linker::getLinkers(), MotorGhost::getMotorGhosts(), Restart::getnumchemsteps(), moveBoundary(), Restart::redistributediffusingspecies(), resetglobaltime(), CController::restart(), MController::run(), CController::run(), SysParams::RUNSTATE, CController::runSteps(), Restart::settorestartphase(), tau(), SubSystem::updateBindingManagers(), updateNeighborLists(), and updatePositions().
Referenced by main(), and ~Controller().
setupInitialNetwork()
void Controller::setupInitialNetwork (SystemParser & p) private
INITIALIZATION HELPER FUNCTIONS.
Set up an initial configuration of a network For now, only Bubbles and Filaments can be initialized before the simulation begins. Any other elements should be initialized in this function.
Definition at line 216 of file Controller.cpp.
References _inputDirectory, _subSystem, SubSystem::addTrackable(), BubbleSetup::bubbleType, SysParams::Chemistry(), BubbleInitializer::createBubbles(), GeoParams::cylinderSize, fil, FilamentSetup::filamentLength, filaments, FilamentSetup::filamentType, SysParams::Geometry(), SubSystem::getBoundary(), FilamentSetup::inputFile, BubbleSetup::inputFile, SysParams::Mechanics(), BubbleSetup::numBubbles, MechParams::numBubbleTypes, ChemParams::numFilaments, FilamentSetup::numFilaments, FilamentSetup::projectionType, BubbleParser::readBubbles(), SystemParser::readBubbleSetup(), FilamentParser::readFilaments(), SystemParser::readFilamentSetup(), tau(), mathfunc::twoPointDirection(), and mathfunc::twoPointDistance().
Referenced by initialize().
setupSpecialStructures()
void Controller::setupSpecialStructures (SystemParser & p) private
Setup any special structures needed.
Definition at line 316 of file Controller.cpp.
References _subSystem, MTOC::addFilament(), SubSystem::addTrackable(), FilamentInitializer::createFilaments(), GeoParams::cylinderSize, fil, filaments, SysParams::Geometry(), GController::getSize(), SysParams::Mechanics(), SpecialSetupType::mtoc, SpecialSetupType::mtocBubbleType, SpecialSetupType::mtocFilamentLength, SpecialSetupType::mtocFilamentType, SpecialSetupType::mtocNumFilaments, SystemParser::readSpecialSetupType(), MTOC::setBubble(), tau(), mathfunc::twoPointDirection(), and mathfunc::twoPointDistance().
Referenced by initialize().
updateNeighborLists()
void Controller::updateNeighborLists () private
Update neighbors lists, called in run.
Definition at line 439 of file Controller.cpp.
References _subSystem, SubSystem::resetNeighborLists(), and SubSystem::updateBindingManagers().
Referenced by run().
updatePositions()
void Controller::updatePositions () private
Update the positions of all elements in the system.
Definition at line 423 of file Controller.cpp.
References _subSystem, Cylinder::getCylinders(), SubSystem::getMovables(), and SubSystem::getReactables().
Referenced by run().
Member Data Documentation
_cAlgorithm
ChemistryAlgorithm Controller::_cAlgorithm private
Same parameter set as timestep, but in terms of chemical reaction steps.
Useful for small runs and debugging.
Definition at line 71 of file Controller.h.
Referenced by initialize().
_cController
CController* Controller::_cController private
Mechanical controller used.
Definition at line 46 of file Controller.h.
Referenced by Controller(), initialize(), moveBoundary(), and run().
_chemData
ChemistryData Controller::_chemData private
Same parameter set as timestep, but in terms of chemical reaction steps.
Useful for small runs and debugging.
Definition at line 70 of file Controller.h.
Referenced by initialize(), and run().
_drController
DRController* Controller::_drController private
Dynamic rate controller used.
Definition at line 48 of file Controller.h.
Referenced by Controller(), and initialize().
_gController
GController* Controller::_gController private
Geometry controller used.
Definition at line 47 of file Controller.h.
Referenced by Controller(), and initialize().
_inputDirectory
string Controller::_inputDirectory private
Input directory being used.
Definition at line 50 of file Controller.h.
Referenced by initialize(), and setupInitialNetwork().
_mController
MController* Controller::_mController private
Chemical controller used.
Definition at line 45 of file Controller.h.
Referenced by Controller(), initialize(), and run().
_minimizationSteps
double Controller::_minimizationSteps private
Same parameter set as timestep, but in terms of chemical reaction steps.
Useful for small runs and debugging.
Definition at line 68 of file Controller.h.
Referenced by initialize(), and run().
_minimizationTime
double Controller::_minimizationTime private
Frequency of mechanical minimization.
Definition at line 59 of file Controller.h.
Referenced by initialize(), and run().
_neighborListSteps
double Controller::_neighborListSteps private
Same parameter set as timestep, but in terms of chemical reaction steps.
Useful for small runs and debugging.
Definition at line 69 of file Controller.h.
Referenced by initialize(), and run().
_neighborListTime
double Controller::_neighborListTime private
Frequency of neighbor list updates.
Definition at line 60 of file Controller.h.
Referenced by initialize(), and run().
_outputDirectory
string Controller::_outputDirectory private
Output directory being used.
Definition at line 51 of file Controller.h.
Referenced by initialize().
_outputs
vector<Output*> Controller::_outputs private
Vector of specified outputs.
Definition at line 53 of file Controller.h.
Referenced by initialize(), and run().
_runSteps
double Controller::_runSteps private
Same parameter set as timestep, but in terms of chemical reaction steps.
Useful for small runs and debugging.
Definition at line 65 of file Controller.h.
Referenced by initialize(), and run().
_runTime
double Controller::_runTime private
Total desired runtime for simulation.
Definition at line 55 of file Controller.h.
Referenced by initialize(), and run().
_snapshotSteps
double Controller::_snapshotSteps private
Same parameter set as timestep, but in terms of chemical reaction steps.
Useful for small runs and debugging.
Definition at line 66 of file Controller.h.
Referenced by initialize(), and run().
_snapshotTime
double Controller::_snapshotTime private
Desired time for each snapshot.
Definition at line 57 of file Controller.h.
Referenced by initialize(), and run().
_subSystem
SubSystem* Controller::_subSystem private
A pointer to the subsystem that this controls.
Definition at line 43 of file Controller.h.
Referenced by Controller(), initialize(), moveBoundary(), pinBoundaryFilaments(), run(), setupInitialNetwork(), setupSpecialStructures(), updateNeighborLists(), and updatePositions().
fil
vector<tuple<short, vector<double>, vector<double> > > Controller::fil private
Same parameter set as timestep, but in terms of chemical reaction steps.
Useful for small runs and debugging.
Definition at line 72 of file Controller.h.
Referenced by setupInitialNetwork(), and setupSpecialStructures().
filaments
tuple< vector<tuple<short, vector<double>, vector<double> > > , vector<tuple<string, short, vector<vector<double> > > > , vector<tuple<string, short, vector<double> > > , vector<vector<double> > > Controller::filaments private
Same parameter set as timestep, but in terms of chemical reaction steps.
Useful for small runs and debugging.
Definition at line 73 of file Controller.h.
Referenced by run(), setupInitialNetwork(), and setupSpecialStructures().
The documentation for this class was generated from the following files:
src/Controller.h
src/Controller.cpp