MEDYAN: RNode Class Reference
RNode Class Reference abstract
This is an abstract base class for classes that need to be associated with the given Reaction object.
#include <ChemRNode.h>
Public Member Functions
virtual ~RNode () noexcept
Dtor.
virtual void activateReaction ()=0
This method is called by Reaction::activateReaction().
virtual void passivateReaction ()=0
This method is called by Reaction::passivateReaction().
virtual bool isPassivated () const =0
Return true if the Reaction is currently passivated.
Detailed Description
This is an abstract base class for classes that need to be associated with the given Reaction object.
Definition at line 21 of file ChemRNode.h.
Constructor & Destructor Documentation
~RNode()
virtual RNode::~RNode () inline virtual noexcept
Dtor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 28 of file ChemRNode.h.
References activateReaction(), isPassivated(), and passivateReaction().
Member Function Documentation
activateReaction()
virtual void RNode::activateReaction () pure virtual
This method is called by Reaction::activateReaction().
Its effect depends on the underlying stochastic simulation algorithm. For example, in the NRM algorithm, a new tau and a are computed and the heap is updated.
Implemented in RNodeNRM, and RNodeGillespie.
Referenced by DiffusionReaction::updatePropensityImpl(), and ~RNode().
isPassivated()
virtual bool RNode::isPassivated () const pure virtual
Return true if the Reaction is currently passivated.
Implemented in RNodeNRM, and RNodeGillespie.
Referenced by ~RNode().
passivateReaction()
virtual void RNode::passivateReaction () pure virtual
This method is called by Reaction::passivateReaction().
Its effect depends on the underlying stochastic simulatin algorithm. For example, in the NRM algorithm, a tau is set to infinity and the heap is updated.
Implemented in RNodeNRM, and RNodeGillespie.
Referenced by ~RNode().
The documentation for this class was generated from the following file:
src/Chemistry/ChemRNode.h