MEDYAN: BubbleFF Class Reference
BubbleFF Class Reference
An implementation of the ForceField class that calculates Bubble repulsion and attraction to Beads in the system.
#include <BubbleFF.h>
Public Member Functions
BubbleFF (string type, string mtoc)
Initialize the forcefields.
virtual string getName ()
Get the name of this forcefield.
virtual void whoIsCulprit ()
In the case of a calculation error, print the culprit of the FF error.
virtual double computeEnergy (double d)
Compute total energy of this forcefield in the system.
virtual void computeForces ()
Compute forces of this forcefield in the system.
virtual void computeForcesAux ()
Compute auxiliary forces of this forcefield in the system.
virtual void computeLoadForces ()
BubbleFF can compute load forces on all Bead from Bubble elements.
virtual vector< NeighborList * > getNeighborLists ()
Get all neighbor lists associated with a ForceField.
Private Attributes
vector< unique_ptr< BubbleInteractions > > _bubbleInteractionVector
Vector of initialized bubble interactions.
BubbleInteractions * _culpritInteraction
The culprit in the case of an error.
Detailed Description
An implementation of the ForceField class that calculates Bubble repulsion and attraction to Beads in the system.
Definition at line 29 of file BubbleFF.h.
Constructor & Destructor Documentation
BubbleFF()
BubbleFF::BubbleFF (string type, string mtoc)
Initialize the forcefields.
Definition at line 29 of file BubbleFF.cpp.
References _bubbleInteractionVector.
Member Function Documentation
computeEnergy()
double BubbleFF::computeEnergy (double d) virtual
Compute total energy of this forcefield in the system.
Returns
the energy value if valid. If an inf or NaN value has been calculated, return -1.
Implements ForceField.
Definition at line 72 of file BubbleFF.cpp.
References _bubbleInteractionVector, and _culpritInteraction.
Referenced by getName().
computeForces()
void BubbleFF::computeForces () virtual
Compute forces of this forcefield in the system.
Update Bead forces accordingly.
Implements ForceField.
Definition at line 92 of file BubbleFF.cpp.
References _bubbleInteractionVector.
Referenced by getName().
computeForcesAux()
void BubbleFF::computeForcesAux () virtual
Compute auxiliary forces of this forcefield in the system.
Update Bead auxiliary forces accordingly.
Implements ForceField.
Definition at line 98 of file BubbleFF.cpp.
References _bubbleInteractionVector.
Referenced by getName().
computeLoadForces()
void BubbleFF::computeLoadForces () virtual
BubbleFF can compute load forces on all Bead from Bubble elements.
Implements ForceField.
Definition at line 104 of file BubbleFF.cpp.
References _bubbleInteractionVector.
Referenced by getName().
getName()
virtual string BubbleFF::getName () inline virtual
Get the name of this forcefield.
Implements ForceField.
Definition at line 41 of file BubbleFF.h.
References computeEnergy(), computeForces(), computeForcesAux(), computeLoadForces(), getNeighborLists(), and whoIsCulprit().
getNeighborLists()
vector< NeighborList * > BubbleFF::getNeighborLists () virtual
Get all neighbor lists associated with a ForceField.
Implements ForceField.
Definition at line 110 of file BubbleFF.cpp.
References _bubbleInteractionVector.
Referenced by getName().
whoIsCulprit()
void BubbleFF::whoIsCulprit () virtual
In the case of a calculation error, print the culprit of the FF error.
Typically, will just print the Trackable element where the error came from.
Implements ForceField.
Definition at line 56 of file BubbleFF.cpp.
References BubbleInteractions::_bubbleCulprit, _culpritInteraction, BubbleInteractions::_otherCulprit, BubbleInteractions::getName(), Bubble::printSelf(), and Component::printSelf().
Referenced by getName().
Member Data Documentation
_bubbleInteractionVector
vector<unique_ptr<BubbleInteractions> > BubbleFF::_bubbleInteractionVector private
Vector of initialized bubble interactions.
Definition at line 33 of file BubbleFF.h.
Referenced by BubbleFF(), computeEnergy(), computeForces(), computeForcesAux(), computeLoadForces(), and getNeighborLists().
_culpritInteraction
BubbleInteractions* BubbleFF::_culpritInteraction private
The culprit in the case of an error.
Definition at line 36 of file BubbleFF.h.
Referenced by computeEnergy(), and whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Bubble/BubbleFF.h
src/Mechanics/ForceField/Bubble/BubbleFF.cpp