MEDYAN: Cylinder Class Reference
Cylinder Class Reference
A container to store a MCylinder and CCylinder.
#include <Cylinder.h>
Public Member Functions
Cylinder (Composite *parent, Bead *b1, Bead *b2, short type, int position, bool extensionFront=false, bool extensionBack=false, bool initialization=false)
Constructor, initializes a cylinder.
virtual ~Cylinder () noexcept
MCylinder * getMCylinder ()
Get mech cylinder.
CCylinder * getCCylinder ()
Get chem cylinder.
void setCCylinder (CCylinder *c)
set chem cylinder
virtual int getType ()
Get cylinder type.
Compartment * getCompartment ()
Get compartment.
int getID ()
Get ID.
int getPosition ()
virtual void updatePosition ()
Update the position, inherited from Movable.
virtual void updateReactionRates ()
Update the reaction rates, inherited from Reactable.
bool isFullLength ()
Check if this cylinder is grown to full length.
virtual void printSelf ()
Prints information about this node. Useful for debugging.
virtual bool within (Cylinder *other, double dist)
Returns whether a cylinder is within a certain distance from another Uses the closest point between the two cylinders.
virtual bool apply (Visitor &v)
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
virtual bool apply (SpeciesVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual size_t numberOfChildren () const
Returns the number of children of this node.
virtual bool isComposite () const
Returns true if this node is a Composite node.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
virtual size_t numberOfSpecies () const
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t numberOfReactions () const
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual string getFullName () const
Return a string indicating the full name of this node (presumably used mainly for debugging)
virtual size_t countDescendents () const
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const
Return the number of Species contained under this node's hieararchy.
virtual size_t countReactions () const
Return the number of ReactionBase objects contained under this node's hieararchy.
Bead * getFirstBead ()
Get beads.
Bead * getSecondBead ()
Get beads.
void setFirstBead (Bead *b)
Set beads.
void setSecondBead (Bead *b)
Set beads.
Cylinder * getBranchingCylinder ()
Branching cylinder management.
void setBranchingCylinder (Cylinder *c)
Branching cylinder management.
bool isPlusEnd ()
void setPlusEnd (bool plusEnd)
bool isMinusEnd ()
void setMinusEnd (bool minusEnd)
virtual void addToSubSystem ()
SubSystem management, inherited from Trackable.
virtual void removeFromSubSystem ()
SubSystem management, inherited from Trackable.
Static Public Member Functions
static const vector< Cylinder * > & getCylinders ()
Get all instances of this class from the SubSystem.
static int numCylinders ()
Get the number of cylinders in this system.
Public Attributes
vector< double > coordinate
Coordinates of midpoint, updated with updatePosition()
Protected Attributes
bool _movable
Object type.
bool _reactable
Object type.
bool _dneighbor
Object type.
bool _neighbor
Object type.
Static Protected Attributes
static SubSystem * _subSystem = 0
A subsystem pointer for every trackable.
Private Member Functions
void updateCoordinate ()
Helper to get coordinate.
Private Attributes
Bead * _b1
Pointer to the first bead.
Bead * _b2
Pointer to the end bead.
unique_ptr< MCylinder > _mCylinder
Pointer to mech cylinder.
unique_ptr< CCylinder > _cCylinder
Pointer to chem cylinder.
int _position
Position on structure.
bool _plusEnd = false
If the cylinder is at the plus end.
bool _minusEnd = false
If the cylinder is at the minus end.
short _type
Type of cylinder, either corresponding to Filament or other.
int _ID
Unique ID of cylinder, managed by Database.
Compartment * _compartment = nullptr
Where this cylinder is.
Cylinder * _branchingCylinder = nullptr
ptr to a branching cylinder
Static Private Attributes
static Database< Cylinder * > _cylinders
Collection in SubSystem.
static vector< FilamentRateChanger * > _polyChanger
For dynamic polymerization rate.
static ChemManager * _chemManager
A pointer to the ChemManager, intiailized by CController.
Friends
class CController
class DRController
Detailed Description
A container to store a MCylinder and CCylinder.
Cylinder class is used to manage and store a MCylinder and CCylinder. Upon intialization, both of these components are created.
Extending the Movable class, the positions of all instances can be updated by the SubSystem.
Extending the Reactable class, the reactions associated with all instances can be updated by the SubSystem.
Extending the DynamicNeighbor class, all instances can be kept in NeighborLists.
Definition at line 50 of file Cylinder.h.
Constructor & Destructor Documentation
Cylinder()
Cylinder::Cylinder (Composite * parent, Bead * b1, Bead * b2, short type, int position, bool extensionFront = false, bool extensionBack = false, bool initialization = false)
Constructor, initializes a cylinder.
Definition at line 35 of file Cylinder.cpp.
References _cCylinder, _chemManager, _compartment, _mCylinder, _type, Composite::addChild(), Compartment::addCylinder(), Bead::coordinate, coordinate, GController::getCompartment(), ChemManager::initializeCCylinder(), printSelf(), mathfunc::twoPointDistance(), and updateCoordinate().
~Cylinder()
Cylinder::~Cylinder () virtual noexcept
Definition at line 77 of file Cylinder.cpp.
References _compartment, and Compartment::removeCylinder().
Member Function Documentation
addToSubSystem()
virtual void Cylinder::addToSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 148 of file Cylinder.h.
Referenced by getPosition().
apply() [1/3]
bool Component::apply (Visitor & v) virtual inherited
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
However, the ConditionalVisitor allows the visit() function to be applied only selectively to nodes that conform to specific criteria.
Reimplemented in Composite.
Definition at line 26 of file Component.cpp.
References Visitor::visit().
Referenced by Component::~Component().
apply() [2/3]
virtual bool Component::apply (SpeciesVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented in Composite.
Definition at line 61 of file Component.h.
References Component::apply_impl().
apply() [3/3]
virtual bool Component::apply (ReactionVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented in Composite.
Definition at line 69 of file Component.h.
References Component::apply_impl().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
countDescendents()
virtual size_t Component::countDescendents () const inline virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 118 of file Component.h.
countReactions()
virtual size_t Component::countReactions () const inline virtual inherited
Return the number of ReactionBase objects contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 126 of file Component.h.
References Component::getType(), and Component::printSelf().
countSpecies()
virtual size_t Component::countSpecies () const inline virtual inherited
Return the number of Species contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 122 of file Component.h.
Referenced by Linker::getLifetimes(), MotorGhost::getWalkLengths(), BranchingPoint::numBranchingPoints(), and Chemistry::print().
getBranchingCylinder()
Cylinder* Cylinder::getBranchingCylinder () inline
Branching cylinder management.
Definition at line 128 of file Cylinder.h.
Referenced by getCompartment().
getCCylinder()
CCylinder* Cylinder::getCCylinder () inline
Get chem cylinder.
Definition at line 103 of file Cylinder.h.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), BranchingPoint::BranchingPoint(), Linker::Linker(), MotorGhost::MotorGhost(), MotorGhost::moveMotorHead(), BranchingPoint::updatePosition(), Linker::updatePosition(), MotorGhost::updatePosition(), and BranchingPoint::~BranchingPoint().
getCompartment()
Compartment* Cylinder::getCompartment () inline
Get compartment.
Definition at line 124 of file Cylinder.h.
References _branchingCylinder, _compartment, and getBranchingCylinder().
Referenced by Restart::setdiffspeciesnumber(), and CylinderCylinderNL::updateNeighbors().
getCylinders()
static const vector<Cylinder*>& Cylinder::getCylinders () inline static
Get all instances of this class from the SubSystem.
Definition at line 153 of file Cylinder.h.
References Database< T >::getElements().
Referenced by CylinderExclVolume< CVolumeInteractionType >::computeEnergy(), CylinderExclVolume< CVolumeInteractionType >::computeForces(), CylinderExclVolume< CVolumeInteractionType >::computeForcesAux(), Controller::executeSpecialProtocols(), CylinderCylinderNL::reset(), BoundaryCylinderNL::updateNeighbors(), BubbleCylinderNL::updateNeighbors(), and Controller::updatePositions().
getFirstBead()
Bead* Cylinder::getFirstBead () inline
Get beads.
Definition at line 113 of file Cylinder.h.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), MTOCAttachment< MTOCInteractionType >::computeEnergy(), MTOCAttachment< MTOCInteractionType >::computeForces(), MTOCAttachment< MTOCInteractionType >::computeForcesAux(), Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), Linker::Linker(), MotorGhost::MotorGhost(), Controller::pinBoundaryFilaments(), Filament::polymerizeMinusEnd(), Filament::polymerizePlusEnd(), Filament::retractMinusEnd(), setCCylinder(), Linker::updatePosition(), MotorGhost::updatePosition(), MotorGhost::updateReactionRates(), and BranchingPoint::~BranchingPoint().
getFullName()
virtual string Component::getFullName () const inline virtual inherited
Return a string indicating the full name of this node (presumably used mainly for debugging)
Reimplemented in Compartment, CompartmentGrid, and Composite.
Definition at line 114 of file Component.h.
getID()
int Cylinder::getID () inline
Get ID.
Definition at line 133 of file Cylinder.h.
References _ID.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), and CylinderCylinderNL::updateNeighbors().
getMCylinder()
MCylinder* Cylinder::getMCylinder () inline
Get mech cylinder.
Definition at line 100 of file Cylinder.h.
Referenced by MTOCAttachment< MTOCInteractionType >::computeEnergy(), MTOCAttachment< MTOCInteractionType >::computeForces(), MTOCAttachment< MTOCInteractionType >::computeForcesAux(), Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), Filament::polymerizeMinusEnd(), Filament::polymerizePlusEnd(), and Tensions::print().
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), updatePosition(), and BranchingPoint::~BranchingPoint().
getPosition()
int Cylinder::getPosition () inline
Definition at line 144 of file Cylinder.h.
References _position, Database< T >::addElement(), and addToSubSystem().
Referenced by Filament::extendMinusEnd(), Filament::extendPlusEnd(), and CylinderCylinderNL::updateNeighbors().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getSecondBead()
Bead* Cylinder::getSecondBead () inline
Get beads.
Definition at line 114 of file Cylinder.h.
References _b2, and setFirstBead().
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), Linker::Linker(), MotorGhost::MotorGhost(), Controller::pinBoundaryFilaments(), Filament::polymerizeMinusEnd(), Filament::polymerizePlusEnd(), WallTensions::print(), Filament::retractMinusEnd(), Filament::retractPlusEnd(), Linker::updatePosition(), MotorGhost::updatePosition(), and MotorGhost::updateReactionRates().
getType()
int Cylinder::getType () virtual
Get cylinder type.
Get filament type.
Implements Component.
Definition at line 85 of file Cylinder.cpp.
References _type.
Referenced by BranchingPoint::BranchingPoint(), CCylinder::CCylinder(), CCylinder::getType(), Linker::Linker(), MotorGhost::MotorGhost(), MotorGhost::moveMotorHead(), Types::print(), setCCylinder(), BranchingPoint::~BranchingPoint(), and CCylinder::~CCylinder().
isComposite()
virtual bool Component::isComposite () const inline virtual inherited
Returns true if this node is a Composite node.
Reimplemented in Composite.
Definition at line 95 of file Component.h.
isFullLength()
bool Cylinder::isFullLength ()
Check if this cylinder is grown to full length.
Referenced by numCylinders(), and updatePosition().
isMinusEnd()
bool Cylinder::isMinusEnd () inline
Set plus and minus end boolean markers
Definition at line 140 of file Cylinder.h.
References _minusEnd.
isPlusEnd()
bool Cylinder::isPlusEnd () inline
Set plus and minus end boolean markers
Definition at line 137 of file Cylinder.h.
References _plusEnd.
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
numberOfChildren()
virtual size_t Component::numberOfChildren () const inline virtual inherited
Returns the number of children of this node.
Note
Species and ReactionBase objects are not counted.
Reimplemented in Composite.
Definition at line 92 of file Component.h.
numberOfReactions()
virtual size_t Component::numberOfReactions () const inline virtual inherited
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 110 of file Component.h.
numberOfSpecies()
virtual size_t Component::numberOfSpecies () const inline virtual inherited
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 106 of file Component.h.
numCylinders()
static int Cylinder::numCylinders () inline static
Get the number of cylinders in this system.
Definition at line 157 of file Cylinder.h.
References Database< T >::countElements(), isFullLength(), printSelf(), updatePosition(), updateReactionRates(), and within().
printSelf()
virtual void Cylinder::printSelf () virtual
Prints information about this node. Useful for debugging.
Implements Component.
Referenced by Cylinder(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), numCylinders(), BranchingPoint::printSelf(), Linker::printSelf(), MotorGhost::printSelf(), updatePosition(), and CylinderVolumeFF::whoIsCulprit().
removeFromSubSystem()
virtual void Cylinder::removeFromSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 149 of file Cylinder.h.
References Database< T >::removeElement().
setBranchingCylinder()
void Cylinder::setBranchingCylinder (Cylinder * c) inline
Branching cylinder management.
Definition at line 129 of file Cylinder.h.
Referenced by BranchingPoint::BranchingPoint(), and BranchingPoint::~BranchingPoint().
setCCylinder()
void Cylinder::setCCylinder (CCylinder * c) inline
set chem cylinder
Note
: since this is a unique ptr, will implicitly delete old chem cylinder
Definition at line 106 of file Cylinder.h.
References _b1, getFirstBead(), and getType().
Referenced by updatePosition().
setFirstBead()
void Cylinder::setFirstBead (Bead * b) inline
Set beads.
Definition at line 119 of file Cylinder.h.
Referenced by getSecondBead().
setMinusEnd()
void Cylinder::setMinusEnd (bool minusEnd) inline
Set plus and minus end boolean markers
Definition at line 141 of file Cylinder.h.
Referenced by Filament::extendMinusEnd().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
setPlusEnd()
void Cylinder::setPlusEnd (bool plusEnd) inline
Set plus and minus end boolean markers
Definition at line 138 of file Cylinder.h.
Referenced by Filament::extendPlusEnd(), and Filament::Filament().
setSecondBead()
void Cylinder::setSecondBead (Bead * b) inline
Set beads.
Definition at line 120 of file Cylinder.h.
updateCoordinate()
void Cylinder::updateCoordinate () private
Helper to get coordinate.
Definition at line 29 of file Cylinder.cpp.
References mathfunc::midPointCoordinate().
Referenced by Cylinder(), and updatePosition().
updatePosition()
void Cylinder::updatePosition () virtual
Update the position, inherited from Movable.
Note
- changes compartment if needed
Note
- The function uses the bead load force to calculate this changed rate. If there is no force on the beads the reaction rates are set to the bare.
Implements Movable.
Definition at line 87 of file Cylinder.cpp.
References _b1, _b2, _branchingCylinder, _cCylinder, _chemManager, _compartment, _cylinders, _ID, _mCylinder, _minusEnd, _plusEnd, _polyChanger, _position, _type, Compartment::addCylinder(), areEqual(), Bead::coordinate, coordinate, GeoParams::cylinderSize, SysParams::Geometry(), GController::getCompartment(), Bead::getLoadForcesM(), Bead::getLoadForcesP(), Component::getParent(), isFullLength(), POLYMERIZATIONMINUSEND, POLYMERIZATIONPLUSEND, Bead::printSelf(), printSelf(), Compartment::removeCylinder(), setCCylinder(), mathfunc::twoPointDistance(), updateCoordinate(), updateReactionRates(), and within().
Referenced by numCylinders().
updateReactionRates()
virtual void Cylinder::updateReactionRates () virtual
Update the reaction rates, inherited from Reactable.
Implements Reactable.
Referenced by numCylinders(), and updatePosition().
within()
virtual bool Cylinder::within (Cylinder * other, double dist) virtual
Returns whether a cylinder is within a certain distance from another Uses the closest point between the two cylinders.
Referenced by numCylinders(), and updatePosition().
Friends And Related Function Documentation
CController
friend class CController friend
Definition at line 53 of file Cylinder.h.
DRController
friend class DRController friend
Definition at line 54 of file Cylinder.h.
Member Data Documentation
_b1
Bead* Cylinder::_b1 private
Pointer to the first bead.
Definition at line 57 of file Cylinder.h.
Referenced by setCCylinder(), and updatePosition().
_b2
Bead* Cylinder::_b2 private
Pointer to the end bead.
Definition at line 58 of file Cylinder.h.
Referenced by getSecondBead(), and updatePosition().
_branchingCylinder
Cylinder* Cylinder::_branchingCylinder = nullptr private
ptr to a branching cylinder
Definition at line 74 of file Cylinder.h.
Referenced by getCompartment(), and updatePosition().
_cCylinder
unique_ptr<CCylinder> Cylinder::_cCylinder private
Pointer to chem cylinder.
Definition at line 61 of file Cylinder.h.
Referenced by Cylinder(), and updatePosition().
_chemManager
ChemManager* Cylinder::_chemManager static private
A pointer to the ChemManager, intiailized by CController.
Definition at line 81 of file Cylinder.h.
Referenced by Cylinder(), CController::initialize(), and updatePosition().
_compartment
Compartment* Cylinder::_compartment = nullptr private
Where this cylinder is.
Definition at line 72 of file Cylinder.h.
Referenced by Cylinder(), getCompartment(), updatePosition(), and ~Cylinder().
_cylinders
Database<Cylinder*> Cylinder::_cylinders static private
Collection in SubSystem.
Definition at line 76 of file Cylinder.h.
Referenced by updatePosition().
_dneighbor
bool Trackable::_dneighbor protected inherited
Object type.
Definition at line 54 of file Trackable.h.
_ID
int Cylinder::_ID private
Unique ID of cylinder, managed by Database.
Definition at line 70 of file Cylinder.h.
Referenced by getID(), and updatePosition().
_mCylinder
unique_ptr<MCylinder> Cylinder::_mCylinder private
Pointer to mech cylinder.
Definition at line 60 of file Cylinder.h.
Referenced by Cylinder(), and updatePosition().
_minusEnd
bool Cylinder::_minusEnd = false private
If the cylinder is at the minus end.
Definition at line 66 of file Cylinder.h.
Referenced by isMinusEnd(), and updatePosition().
_movable
bool Trackable::_movable protected inherited
Object type.
Definition at line 52 of file Trackable.h.
_neighbor
bool Trackable::_neighbor protected inherited
Object type.
Definition at line 55 of file Trackable.h.
_plusEnd
bool Cylinder::_plusEnd = false private
If the cylinder is at the plus end.
Definition at line 65 of file Cylinder.h.
Referenced by isPlusEnd(), and updatePosition().
_polyChanger
vector<FilamentRateChanger*> Cylinder::_polyChanger static private
For dynamic polymerization rate.
Definition at line 79 of file Cylinder.h.
Referenced by DRController::initialize(), and updatePosition().
_position
int Cylinder::_position private
Position on structure.
Definition at line 63 of file Cylinder.h.
Referenced by getPosition(), and updatePosition().
_reactable
bool Trackable::_reactable protected inherited
Object type.
Definition at line 53 of file Trackable.h.
_subSystem
SubSystem * Trackable::_subSystem = 0 static protected inherited
A subsystem pointer for every trackable.
Definition at line 46 of file Trackable.h.
Referenced by Controller::Controller(), and BranchingPoint::~BranchingPoint().
_type
short Cylinder::_type private
Type of cylinder, either corresponding to Filament or other.
Definition at line 68 of file Cylinder.h.
Referenced by Cylinder(), getType(), and updatePosition().
coordinate
vector<double> Cylinder::coordinate
Coordinates of midpoint, updated with updatePosition()
Definition at line 88 of file Cylinder.h.
Referenced by BoundaryCylinderNL::addDynamicNeighbor(), BubbleCylinderNL::addNeighbor(), Cylinder(), CylinderCylinderNL::updateNeighbors(), and updatePosition().
The documentation for this class was generated from the following files:
src/Structure/Cylinder.h
src/Structure/Cylinder.cpp