MEDYAN: BubbleInitializer Class Reference
BubbleInitializer Class Reference abstract
An interface to initialize an initial configuration of Bubbles in the SubSystem.
#include <BubbleInitializer.h>
Public Member Functions
virtual ~BubbleInitializer () noexcept
Destructor.
virtual BubbleData createBubbles (Boundary *b, int numBubbles, int bubbleType)=0
Returns a vector of tuples representing the Bubble type and beginning and end coordinates, similar to the structure of manual parsing.
Detailed Description
An interface to initialize an initial configuration of Bubbles in the SubSystem.
Bubblenitiazer class should be inherited to provide an intial scheme for filling a SubSystem with Bubbles. The bubbles could be completely random or distributed in other ways.
Definition at line 31 of file BubbleInitializer.h.
Constructor & Destructor Documentation
~BubbleInitializer()
virtual BubbleInitializer::~BubbleInitializer () inline virtual noexcept
Destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 39 of file BubbleInitializer.h.
References createBubbles().
Member Function Documentation
createBubbles()
virtual BubbleData BubbleInitializer::createBubbles (Boundary * b, int numBubbles, int bubbleType) pure virtual
Returns a vector of tuples representing the Bubble type and beginning and end coordinates, similar to the structure of manual parsing.
Implemented in RandomBubbleDist.
Referenced by Controller::setupInitialNetwork(), and ~BubbleInitializer().
The documentation for this class was generated from the following file:
src/BubbleInitializer.h