MEDYAN: BubbleCylinderNL Class Reference
BubbleCylinderNL Class Reference
An implementation of NeighborList for Bubble-Cylinder interactions.
#include <NeighborListImpl.h>
Public Member Functions
BubbleCylinderNL (float rMax)
virtual void addNeighbor (Neighbor *n)
Add neighbor.
virtual void removeNeighbor (Neighbor *n)
Remove a neighbor if possible.
virtual void reset ()
Re-initialize the neighborlist.
vector< Cylinder * > getNeighbors (Bubble *bb)
Get all Cylinder neighbors of a bubble.
virtual void addDynamicNeighbor (DynamicNeighbor *n)
The implementation of these functions calls the static version, all Bubbles and Cylinders are dynamic.
virtual void removeDynamicNeighbor (DynamicNeighbor *n)
The implementation of these functions calls the static version, all Bubbles and Cylinders are dynamic.
Protected Attributes
float _rMax
max distance cutoff
float _rMin
min distance cutoff
Private Member Functions
void updateNeighbors (Bubble *bb)
Helper function to update neighbors.
Private Attributes
unordered_map< Bubble *, vector< Cylinder * > > _list
The neighbors list, as a hash map.
Detailed Description
An implementation of NeighborList for Bubble-Cylinder interactions.
Definition at line 149 of file NeighborListImpl.h.
Constructor & Destructor Documentation
BubbleCylinderNL()
BubbleCylinderNL::BubbleCylinderNL (float rMax) inline
Definition at line 159 of file NeighborListImpl.h.
References CylinderCylinderNL::addDynamicNeighbor(), CylinderCylinderNL::addNeighbor(), and CylinderCylinderNL::removeNeighbor().
Member Function Documentation
addDynamicNeighbor()
virtual void BubbleCylinderNL::addDynamicNeighbor (DynamicNeighbor * n) inline virtual
The implementation of these functions calls the static version, all Bubbles and Cylinders are dynamic.
Implements NeighborList.
Definition at line 167 of file NeighborListImpl.h.
addNeighbor()
void BubbleCylinderNL::addNeighbor (Neighbor * n) virtual
Add neighbor.
Implements NeighborList.
Definition at line 345 of file NeighborListImpl.cpp.
References Cylinder::coordinate, and mathfunc::twoPointDistance().
getNeighbors()
vector< Cylinder * > BubbleCylinderNL::getNeighbors (Bubble * bb)
Get all Cylinder neighbors of a bubble.
Definition at line 388 of file NeighborListImpl.cpp.
removeDynamicNeighbor()
virtual void BubbleCylinderNL::removeDynamicNeighbor (DynamicNeighbor * n) inline virtual
The implementation of these functions calls the static version, all Bubbles and Cylinders are dynamic.
Implements NeighborList.
Definition at line 168 of file NeighborListImpl.h.
References CylinderCylinderNL::getNeighbors(), CylinderCylinderNL::removeNeighbor(), and CylinderCylinderNL::reset().
removeNeighbor()
void BubbleCylinderNL::removeNeighbor (Neighbor * n) virtual
Remove a neighbor if possible.
Implements NeighborList.
Definition at line 363 of file NeighborListImpl.cpp.
reset()
void BubbleCylinderNL::reset () virtual
Re-initialize the neighborlist.
Implements NeighborList.
Definition at line 379 of file NeighborListImpl.cpp.
References Bubble::getBubbles().
updateNeighbors()
void BubbleCylinderNL::updateNeighbors (Bubble * bb) private
Helper function to update neighbors.
BUBBLE - CYLINDER.
Definition at line 330 of file NeighborListImpl.cpp.
References Bubble::coordinate, Cylinder::getCylinders(), and mathfunc::twoPointDistance().
Member Data Documentation
_list
unordered_map<Bubble*, vector<Cylinder*> > BubbleCylinderNL::_list private
The neighbors list, as a hash map.
Definition at line 152 of file NeighborListImpl.h.
_rMax
float NeighborList::_rMax protected inherited
max distance cutoff
Definition at line 36 of file NeighborList.h.
_rMin
float NeighborList::_rMin protected inherited
min distance cutoff
Definition at line 37 of file NeighborList.h.
The documentation for this class was generated from the following files:
src/Structure/NeighborListImpl.h
src/Structure/NeighborListImpl.cpp