M3Sym: ChemManagerImpl Class Reference
ChemManagerImpl Class Reference abstract
An abstract base class for initialization of all chemistry in the system.
#include <ChemManagerImpl.h>
Public Member Functions
virtual ~ChemManagerImpl () noexcept
Destructor does nothing.
virtual void initialize (ChemistryData &chem)=0
virtual void initializeCCylinder (CCylinder *cc, Filament *f, bool extensionFront, bool extensionBack, bool creation)=0
virtual void updateCCylinder (CCylinder *cc)=0
Detailed Description
An abstract base class for initialization of all chemistry in the system.
Definition at line 34 of file ChemManagerImpl.h.
Constructor & Destructor Documentation
virtual ChemManagerImpl::~ChemManagerImpl () inline virtual noexcept
Destructor does nothing.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 41 of file ChemManagerImpl.h.
Member Function Documentation
virtual void ChemManagerImpl::initialize (ChemistryData & chem) pure virtual
Implemented in SimpleManagerImpl.
Referenced by ChemManager::initialize().
virtual void ChemManagerImpl::initializeCCylinder (CCylinder * cc, Filament * f, bool extensionFront, bool extensionBack, bool creation) pure virtual
Implemented in SimpleManagerImpl.
Referenced by ChemManager::initializeCCylinder().
virtual void ChemManagerImpl::updateCCylinder (CCylinder * cc) pure virtual
Implemented in SimpleManagerImpl.
Referenced by ChemManager::updateCCylinder().
The documentation for this class was generated from the following file:
M3SYM/Chemistry/ChemManagerImpl.h