M3Sym: ReactionVisitorLambda Class Reference
ReactionVisitorLambda Class Reference
Allows using C++11 lambda expressions to set the action to be performed on each Reaction of the node and its descendent nodes.
#include <Visitor.h>
Public Member Functions
ReactionVisitorLambda ()=default
Default Constructor.
ReactionVisitorLambda (std::function< bool(ReactionBase *)> g, std::function< bool(ReactionBase *)> pred=[](ReactionBase *){return true;})
Constructor:
void setLambda (std::function< bool(ReactionBase *)> g)
Sets the action to be perfomed on each node as std::function<bool (Component*)> g.
void setLambdaPred (std::function< bool(ReactionBase *)> pred)
Sets the predicate which checks whether the node should be evaluated as std::function<bool (Component*)> g.
bool visit (ReactionBase *r)
When this Visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(s), for each of the Reaction *r of that node.
Protected Member Functions
virtual bool visitImpl (ReactionBase *r) override
Implementation of the visit(...) method.
virtual bool predImpl (ReactionBase *r) override
Implementation of the pred(...) method.
Protected Attributes
std::function< bool(ReactionBase *)> _f
The function to be perfomed on each node.
std::function< bool(ReactionBase *)> _pred
The predicate which checks whether the Reaction should be evaluated.
Detailed Description
Allows using C++11 lambda expressions to set the action to be performed on each Reaction of the node and its descendent nodes.
Definition at line 179 of file Visitor.h.
Constructor & Destructor Documentation
ReactionVisitorLambda::ReactionVisitorLambda () default
Default Constructor.
ReactionVisitorLambda::ReactionVisitorLambda (std::function< bool(ReactionBase *)> g, std::function< bool(ReactionBase *)> pred = [](ReactionBase *){return true;}) inline
Constructor:
Parameters
std::function<bool (Reaction*)> g defines the action to be perfomed on each Reaction of the node
std::function<bool (Reaction*)> pred defines the predicate whether the particular Reaction should be processed
Definition at line 187 of file Visitor.h.
Member Function Documentation
virtual bool ReactionVisitorLambda::predImpl (ReactionBase * r) inline override protected virtual
Implementation of the pred(...) method.
Implements ReactionVisitor.
Definition at line 202 of file Visitor.h.
References _pred.
void ReactionVisitorLambda::setLambda (std::function< bool(ReactionBase *)> g) inline
Sets the action to be perfomed on each node as std::function<bool (Component*)> g.
Definition at line 190 of file Visitor.h.
References _f.
Referenced by main().
void ReactionVisitorLambda::setLambdaPred (std::function< bool(ReactionBase *)> pred) inline
Sets the predicate which checks whether the node should be evaluated as std::function<bool (Component*)> g.
Definition at line 193 of file Visitor.h.
References _pred.
Referenced by main().
bool ReactionVisitor::visit (ReactionBase * r) inline inherited
When this Visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(s), for each of the Reaction *r of that node.
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Definition at line 156 of file Visitor.h.
References ReactionVisitor::predImpl(), and ReactionVisitor::visitImpl().
Referenced by Compartment::apply_impl().
virtual bool ReactionVisitorLambda::visitImpl (ReactionBase * r) inline override protected virtual
Implementation of the visit(...) method.
Implements ReactionVisitor.
Definition at line 199 of file Visitor.h.
References _f.
Member Data Documentation
std::function<bool (ReactionBase *)> ReactionVisitorLambda::_f protected
The function to be perfomed on each node.
Definition at line 195 of file Visitor.h.
Referenced by setLambda(), and visitImpl().
std::function<bool (ReactionBase *)> ReactionVisitorLambda::_pred protected
The predicate which checks whether the Reaction should be evaluated.
Definition at line 196 of file Visitor.h.
Referenced by predImpl(), and setLambdaPred().
The documentation for this class was generated from the following file:
M3SYM/Visitor.h