MEDYAN: Species Class Reference
Species Class Reference
Represents chemical molecules, tracks their copy number and can be used in Reactions.
#include <Species.h>
Public Member Functions
Species (const Species &rhs)
Copy constructor.
Species (Species &&rhs) noexcept
Move constructor - makes it possible to easily add Species to STL containers, such as vector<Species> One has to be careful with vector<Species> as opposed to vector<Species*>.
Species & operator= (const Species &rhs)
Assignment operator An assignment A = B copies the name of B to A.
Species & operator= (Species &&rhs)
Move assignment is needed for the same reasons as move constructor.
virtual Species * clone ()
Composite * getParent ()
void setParent (Composite *other)
bool hasParent () const
Composite * getRoot ()
RSpecies & getRSpecies ()
Return a reference to RSpecies.
RSpecies * getRSpeciesPtr ()
Return a reference ptr to RSpecies.
const RSpecies & getRSpecies () const
Return a constant reference to RSpecies.
void setN (species_copy_t n)
Sets the copy number for this Species.
species_copy_t getN () const
Return the current copy number of this Species.
string getName () const
Return this Species' name.
int getMolecule () const
Return the molecule index associated with this Species' (as int)
virtual ~Species () noexcept
Virtual destructor.
virtual string getFullName () const
Return the full name of this Species in a string format (e.g. "Arp2/3{Bulk}".
virtual size_t countSpecies () const
void updateReactantPropensities ()
Update the reaction propensities associated with this species.
void activateReactantReactions ()
Activate the reactions associated with this species.
void passivateReactantReactions ()
Passivate the reactions associated with this species.
virtual void up ()
Change copy number.
virtual void down ()
Change copy number.
Protected Member Functions
Species ()
Default Constructor; Should not be used by the end users - only internally By default, creates a RSpeciesReg.
Species (const string &name, species_copy_t n, species_copy_t ulim, RSpeciesType type)
The constructor for this base class of Species should not be called directly - only by the concrete subclasses.
Protected Attributes
int _molecule
unique id identifying the molecule (e.g.
RSpecies * _rspecies
pointer to RSpecies; Species is responsible for creating and destroying RSpecies
Composite * _parent
pointer to the "container" object holding this Species (could be a nullptr)
Friends
bool operator== (const Species &a, const Species &b)
Returns true if two Species objects are equal.
bool operator!= (const Species &a, const Species &b)
Return true if two Species are not equal.
Detailed Description
Represents chemical molecules, tracks their copy number and can be used in Reactions.
This abstract class represents chemical species, such as G-Actin. As a class, it provides Species' name, the current copy number of molecules, Species type (e.g. SpeciesType::Bulk), and a few other characteristics of a Species. This class is synergetic with the Reaction, since Species can be added to Reactions. As a type, Species is composed of the following primary fields: type, name, copy number. A subclass may added additional primary fields. Two Species are mathematically equal, if their primary fields are equal. This means that applying the copy constructor will guarantee that primary fields will be equal.
Note
Each Species owns an unshared RSpecies object. However, the RSpecies field is not among the primary fields defining the Species identity (hence, the equality operator). In particular, upon copying, the source and target Species will have distinct RSpecies fields. However, in a fully constructed program, the source and target species (after applying the copy constructor) should eventually be involved in the same set of equivalent reactions. This means that their respective reactions will return true when the equlaity operator is applied.
The Species class allows callbacks (see makeSignaling and related methods).
Definition at line 171 of file Species.h.
Constructor & Destructor Documentation
Species() [1/4]
Species::Species () inline protected
Default Constructor; Should not be used by the end users - only internally By default, creates a RSpeciesReg.
Definition at line 183 of file Species.h.
References SpeciesNamesDB::stringToInt().
Species() [2/4]
Species::Species (const string & name, species_copy_t n, species_copy_t ulim, RSpeciesType type) inline protected
The constructor for this base class of Species should not be called directly - only by the concrete subclasses.
Parameters
name - a string for the Species name associated with this Species. For example, "G-Actin" or "Arp2/3"
n - copy number
ulim - upper limit for this species' copy number
type - the type of RSpecies to be created
numEvents - the number of events if using averaging
Definition at line 197 of file Species.h.
References RSpeciesFactory::createRSpecies().
Species() [3/4]
Species::Species (const Species & rhs) inline
Copy constructor.
Note
The associated RSpecies subpart is not copied, but a new one is created. This means that the copied destination Species won't be included in any Reaction interactions of the original source Species. The species copy numbered is copied to the target. The A Species parent attriute is not copied, but set to nullptr.
Definition at line 210 of file Species.h.
References _rspecies, RSpecies::_type, AVG, RSpeciesFactory::createRSpecies(), getN(), and max_ulim.
Species() [4/4]
Species::Species (Species && rhs) inline noexcept
Move constructor - makes it possible to easily add Species to STL containers, such as vector<Species> One has to be careful with vector<Species> as opposed to vector<Species*>.
The latter is "safe" in terms of being internally moved around by vector.resize, etc., but vector<Species> would copy Species if a move constructor is not available. This will then destruct the original Species (with its associated RSpecies), hence, the Reaction network of the Species will be lost. Since this behavior is most likely not desired or unacceptable, the internal vector operations should only "move" the Species around, without copying. Moving transfers the RSpecies pointer from source to target, stealing resources from the source, leaving it for destruction. The Species parent attriute is moved it.
Definition at line 245 of file Species.h.
~Species()
virtual Species::~Species () inline virtual noexcept
Virtual destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 384 of file Species.h.
Member Function Documentation
activateReactantReactions()
void Species::activateReactantReactions ()
Activate the reactions associated with this species.
i.e. if passivated, will activate accordingly and update propensities and all dependents.
Definition at line 47 of file Species.cpp.
References _rspecies, and RSpecies::reactantReactions().
Referenced by ChemManager::updateCopyNumbers().
clone()
virtual Species* Species::clone () inline virtual
Reimplemented in SpeciesPairBinding, SpeciesSingleBinding, SpeciesMinusEnd, SpeciesPlusEnd, SpeciesBrancher, SpeciesMotor, SpeciesLinker, SpeciesBound, SpeciesFilament, SpeciesDiffusing, and SpeciesBulk.
Definition at line 295 of file Species.h.
Referenced by Compartment::cloneSpecies().
countSpecies()
virtual size_t Species::countSpecies () const inline virtual
Definition at line 393 of file Species.h.
References RSpecies::up().
down()
virtual void Species::down () inline virtual
Change copy number.
Definition at line 398 of file Species.h.
References RSpecies::down().
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), ChemManager::initializeCCylinder(), Filament::sever(), FilamentBindingManager::updateBindingReaction(), ChemManager::updateCopyNumbers(), and BranchingPoint::~BranchingPoint().
getFullName()
virtual string Species::getFullName () const inline virtual
Return the full name of this Species in a string format (e.g. "Arp2/3{Bulk}".
Reimplemented in SpeciesPairBinding, SpeciesSingleBinding, SpeciesMinusEnd, SpeciesPlusEnd, SpeciesBrancher, SpeciesMotor, SpeciesLinker, SpeciesBound, SpeciesFilament, SpeciesDiffusing, and SpeciesBulk.
Definition at line 391 of file Species.h.
Referenced by RSpecies::getFullName(), and operator<<().
getMolecule()
int Species::getMolecule () const inline
Return the molecule index associated with this Species' (as int)
Definition at line 334 of file Species.h.
Referenced by Compartment::addSpeciesBound(), Compartment::addSpeciesBrancher(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPairBinding(), Compartment::addSpeciesPlusEnd(), Compartment::addSpeciesSingleBinding(), Compartment::addSpeciesUnique(), and Compartment::setDiffusionRate().
getN()
species_copy_t Species::getN () const inline
Return the current copy number of this Species.
Definition at line 323 of file Species.h.
References RSpecies::getN().
Referenced by CMonomer::activeSpeciesBrancher(), CMonomer::activeSpeciesFilament(), CMonomer::activeSpeciesLinker(), CMonomer::activeSpeciesMinusEnd(), CMonomer::activeSpeciesMotor(), CMonomer::activeSpeciesPlusEnd(), BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CMonomer::isConsistent(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), MotorBindingManager::MotorBindingManager(), operator<<(), operator=(), CMonomer::print(), BranchingManager::removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), Species(), Compartment::transferSpecies(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), MotorBindingManager::updateAllPossibleBindings(), FilamentBindingManager::updateBindingReaction(), and ChemManager::updateCopyNumbers().
getName()
string Species::getName () const inline
Return this Species' name.
Definition at line 331 of file Species.h.
References SpeciesNamesDB::intToString().
Referenced by BranchingManager::BranchingManager(), CMonomer::isConsistent(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), CMonomer::print(), and BranchingPoint::~BranchingPoint().
getParent()
Composite* Species::getParent () inline
Definition at line 299 of file Species.h.
Referenced by getRoot().
getRoot()
Composite * Species::getRoot ()
Definition at line 29 of file Species.cpp.
References getParent(), Component::getRoot(), and hasParent().
getRSpecies() [1/2]
RSpecies& Species::getRSpecies () inline
Return a reference to RSpecies.
Notice that value copying won't be allowed because RSpecies is not copyable.
Definition at line 309 of file Species.h.
Referenced by ChemManager::genSpecies(), and MotorGhost::updateReactionRates().
getRSpecies() [2/2]
const RSpecies& Species::getRSpecies () const inline
Return a constant reference to RSpecies.
Definition at line 315 of file Species.h.
getRSpeciesPtr()
RSpecies* Species::getRSpeciesPtr () inline
Return a reference ptr to RSpecies.
Definition at line 312 of file Species.h.
hasParent()
bool Species::hasParent () const inline
Definition at line 303 of file Species.h.
Referenced by getRoot().
operator=() [1/2]
Species& Species::operator= (const Species & rhs) inline
Assignment operator An assignment A = B copies the name of B to A.
It destroys the Reaction interactions of A, and resents them to a blank value (i.e. A won't be involved in any Reactions). B's Reaction interactions are not copied. The copy number of B is copied to A. The A Species parent attriute is not copied, but set to nullptr.
Definition at line 257 of file Species.h.
References _molecule, _rspecies, RSpecies::_type, AVG, RSpeciesFactory::createRSpecies(), getN(), and max_ulim.
Referenced by SpeciesBulk::operator=(), SpeciesDiffusing::operator=(), SpeciesFilament::operator=(), SpeciesBound::operator=(), SpeciesPlusEnd::operator=(), SpeciesMinusEnd::operator=(), SpeciesSingleBinding::operator=(), and SpeciesPairBinding::operator=().
operator=() [2/2]
Species& Species::operator= (Species && rhs) inline
Move assignment is needed for the same reasons as move constructor.
See also
Species (Species &&rhs)
Definition at line 286 of file Species.h.
References _molecule.
passivateReactantReactions()
void Species::passivateReactantReactions ()
Passivate the reactions associated with this species.
i.e. if activated, will passivate accordingly and update propensities and all dependents.
Definition at line 54 of file Species.cpp.
References SpeciesNamesDB::_map_string_int, SpeciesNamesDB::_num, _rspecies, SpeciesNamesDB::_vec_int_string, and RSpecies::reactantReactions().
Referenced by ChemManager::updateCopyNumbers().
setN()
void Species::setN (species_copy_t n) inline
Sets the copy number for this Species.
Parameters
n should be a non-negative number, but no checking is done in run time
Note
The operation does not emit any signals about the copy number change.
Definition at line 320 of file Species.h.
References RSpecies::setN().
Referenced by ChemManager::updateCopyNumbers().
setParent()
void Species::setParent (Composite * other) inline
Definition at line 301 of file Species.h.
Referenced by Compartment::addSpeciesBound(), Compartment::addSpeciesBrancher(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPairBinding(), Compartment::addSpeciesPlusEnd(), Compartment::addSpeciesSingleBinding(), and Compartment::addSpeciesUnique().
up()
virtual void Species::up () inline virtual
Change copy number.
Definition at line 397 of file Species.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), ChemManager::initializeCCylinder(), Filament::nucleate(), Filament::sever(), FilamentBindingManager::updateBindingReaction(), ChemManager::updateCopyNumbers(), and BranchingPoint::~BranchingPoint().
updateReactantPropensities()
void Species::updateReactantPropensities ()
Update the reaction propensities associated with this species.
This will not activate the reactions if currently passivated, or update any dependents asosciated with these reactions.
Definition at line 41 of file Species.cpp.
References _rspecies, and RSpecies::reactantReactions().
Referenced by ChemManager::updateCopyNumbers(), and BranchingPoint::~BranchingPoint().
Friends And Related Function Documentation
operator!=
bool operator!= (const Species & a, const Species & b) friend
Return true if two Species are not equal.
See also
operator ==(const Species& a, const Species& b) above
Definition at line 373 of file Species.h.
operator==
bool operator== (const Species & a, const Species & b) friend
Returns true if two Species objects are equal.
This function would accept derived class of Species, such as SpeciesBulk Two Species are equal if their SType(s) are equal (i.e. are of the same class), their names are equal.
Definition at line 364 of file Species.h.
Member Data Documentation
_molecule
int Species::_molecule protected
unique id identifying the molecule (e.g.
the integer id corresponding to "Arp2/3")
Definition at line 174 of file Species.h.
Referenced by operator=().
_parent
Composite* Species::_parent protected
pointer to the "container" object holding this Species (could be a nullptr)
Definition at line 178 of file Species.h.
_rspecies
RSpecies* Species::_rspecies protected
pointer to RSpecies; Species is responsible for creating and destroying RSpecies
Definition at line 176 of file Species.h.
Referenced by activateReactantReactions(), operator=(), passivateReactantReactions(), Species(), and updateReactantPropensities().
The documentation for this class was generated from the following files:
src/Chemistry/Species.h
src/Chemistry/Species.cpp