MEDYAN: MotorGhostFF Class Reference
MotorGhostFF Class Reference
An implementation of the ForceField class that calculates MotorGhost stretching, bending, and twisting.
#include <MotorGhostFF.h>
Public Member Functions
MotorGhostFF (string &stretching, string &bending, string &twisting)
Constructor, intializes stretching, bending, and twisting forces.
virtual string getName ()
Get the name of this forcefield.
virtual void whoIsCulprit ()
In the case of a calculation error, print the culprit of the FF error.
virtual double computeEnergy (double d)
Compute total energy of this forcefield in the system.
virtual void computeForces ()
Compute forces of this forcefield in the system.
virtual void computeForcesAux ()
Compute auxiliary forces of this forcefield in the system.
virtual void computeLoadForces ()
Compute all load forces on beads in this system.
virtual vector< NeighborList * > getNeighborLists ()
Get all neighbor lists associated with a ForceField.
Private Attributes
vector< unique_ptr< MotorGhostInteractions > > _motorGhostInteractionVector
Vector of initialized motor interactions.
MotorGhostInteractions * _culpritInteraction
Culprit in case of error.
Detailed Description
An implementation of the ForceField class that calculates MotorGhost stretching, bending, and twisting.
Definition at line 29 of file MotorGhostFF.h.
Constructor & Destructor Documentation
MotorGhostFF()
MotorGhostFF::MotorGhostFF (string & stretching, string & bending, string & twisting)
Constructor, intializes stretching, bending, and twisting forces.
Definition at line 21 of file MotorGhostFF.cpp.
References _motorGhostInteractionVector.
Member Function Documentation
computeEnergy()
double MotorGhostFF::computeEnergy (double d) virtual
Compute total energy of this forcefield in the system.
Returns
the energy value if valid. If an inf or NaN value has been calculated, return -1.
Implements ForceField.
Definition at line 45 of file MotorGhostFF.cpp.
References _culpritInteraction, and _motorGhostInteractionVector.
Referenced by getName().
computeForces()
void MotorGhostFF::computeForces () virtual
Compute forces of this forcefield in the system.
Update Bead forces accordingly.
Implements ForceField.
Definition at line 66 of file MotorGhostFF.cpp.
References _motorGhostInteractionVector.
Referenced by getName().
computeForcesAux()
void MotorGhostFF::computeForcesAux () virtual
Compute auxiliary forces of this forcefield in the system.
Update Bead auxiliary forces accordingly.
Implements ForceField.
Definition at line 72 of file MotorGhostFF.cpp.
References _motorGhostInteractionVector.
Referenced by getName().
computeLoadForces()
virtual void MotorGhostFF::computeLoadForces () inline virtual
Compute all load forces on beads in this system.
Updates all Bead's load force components for Reaction updating.
Implements ForceField.
Definition at line 47 of file MotorGhostFF.h.
getName()
virtual string MotorGhostFF::getName () inline virtual
Get the name of this forcefield.
Implements ForceField.
Definition at line 40 of file MotorGhostFF.h.
References computeEnergy(), computeForces(), computeForcesAux(), and whoIsCulprit().
getNeighborLists()
virtual vector<NeighborList*> MotorGhostFF::getNeighborLists () inline virtual
Get all neighbor lists associated with a ForceField.
Implements ForceField.
Definition at line 49 of file MotorGhostFF.h.
whoIsCulprit()
void MotorGhostFF::whoIsCulprit () virtual
In the case of a calculation error, print the culprit of the FF error.
Typically, will just print the Trackable element where the error came from.
Implements ForceField.
Definition at line 33 of file MotorGhostFF.cpp.
References _culpritInteraction, MotorGhostInteractions::_motorCulprit, MotorGhostInteractions::getName(), and MotorGhost::printSelf().
Referenced by getName().
Member Data Documentation
_culpritInteraction
MotorGhostInteractions* MotorGhostFF::_culpritInteraction private
Culprit in case of error.
Definition at line 35 of file MotorGhostFF.h.
Referenced by computeEnergy(), and whoIsCulprit().
_motorGhostInteractionVector
vector<unique_ptr<MotorGhostInteractions> > MotorGhostFF::_motorGhostInteractionVector private
Vector of initialized motor interactions.
Definition at line 33 of file MotorGhostFF.h.
Referenced by computeEnergy(), computeForces(), computeForcesAux(), and MotorGhostFF().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/MotorGhost/MotorGhostFF.h
src/Mechanics/ForceField/MotorGhost/MotorGhostFF.cpp