M3Sym: ChemSim Class Reference
ChemSim Class Reference
Used to manage running a network of chemical reactions.
#include <ChemSim.h>
Public Member Functions
ChemSim (const ChemSim &rhs)=delete
Copying is not allowed.
ChemSim & operator= (ChemSim &rhs)=delete
Assignment is not allowed.
Static Public Member Functions
static void setInstance (ChemSimImpl *csi)
SetInstance.
static void initialize ()
After all initial reactions have been added via addReaction(...) method, invoke initialize() prior to invoking run()
static void addReaction (ReactionBase *r)
Add Reaction *r to the chemical network which needs to be simulated.
static void removeReaction (ReactionBase *r)
Remove Reaction *r from the simulated chemical network.
static bool run (int steps)
Run the chemical dynamics for a specific number of steps.
static void printReactions ()
Mainly used for debugging: print chemical reactions in the network at this moment.
Private Member Functions
ChemSim ()
Static Private Attributes
static ChemSimImpl * _pimpl = 0
Store a pointer to a specific implementation of stochastic chemical kinetics; no ownership.
Detailed Description
Used to manage running a network of chemical reactions.
ChemSim implements a Strategy pattern, allowing custom algorithms for running stochastic chemical simulations. It itself is a singleton, with a pointer to a single static implementation of ChemSimImpl. After the specific algorithm is chosen and ChemSim is instantiated, ChemSim can be used to manage simulations, through such methods as run(steps) etc. Here is an example (assuming key is valid for all functions):
SpeciesBulk A1("A1",  25);
SpeciesBulk A2("A2", 25);
Reaction r1 = { {&A1,&A2}, 1, 1, 100.0 };
ChemSim::setInstance(key, new ChemNRMImpl());
ChemSim::addReaction(key, &r1);
ChemSim::initialize(key);
ChemSim::run(key)
Specific functions in this class require a key to be accessed. The key declarations are above. These keys can only be created and/or destroyed by the classes that are "friends" with the key.
Definition at line 44 of file ChemSim.h.
Constructor & Destructor Documentation
ChemSim::ChemSim (const ChemSim & rhs) delete
Copying is not allowed.
ChemSim::ChemSim () inline private
Definition at line 75 of file ChemSim.h.
Member Function Documentation
void ChemSim::addReaction (ReactionBase * r) static
Add Reaction *r to the chemical network which needs to be simulated.
Definition at line 26 of file ChemSim.cpp.
References _pimpl, and ChemSimImpl::addReaction().
Referenced by CompartmentGrid::addChemSimReactions(), Compartment::addChemSimReactions(), CCylinder::addCrossCylinderReaction(), CCylinder::addInternalReaction(), and main().
void ChemSim::initialize () static
After all initial reactions have been added via addReaction(...) method, invoke initialize() prior to invoking run()
Definition at line 38 of file ChemSim.cpp.
References _pimpl, and ChemSimImpl::initialize().
Referenced by CController::initialize(), and main().
ChemSim& ChemSim::operator= (ChemSim & rhs) delete
Assignment is not allowed.
void ChemSim::printReactions () static
Mainly used for debugging: print chemical reactions in the network at this moment.
Definition at line 42 of file ChemSim.cpp.
References _pimpl, and ChemSimImpl::printReactions().
Referenced by main().
void ChemSim::removeReaction (ReactionBase * r) static
Remove Reaction *r from the simulated chemical network.
Definition at line 30 of file ChemSim.cpp.
References _pimpl, and ChemSimImpl::removeReaction().
Referenced by CCylinder::removeAllCrossCylinderReactions(), CCylinder::removeAllInternalReactions(), CCylinder::removeCrossCylinderReactions(), and CCylinder::removeInternalReaction().
bool ChemSim::run (int steps) static
Run the chemical dynamics for a specific number of steps.
Definition at line 34 of file ChemSim.cpp.
References _pimpl, and ChemSimImpl::run().
Referenced by main(), and CController::run().
void ChemSim::setInstance (ChemSimImpl * csi) static
SetInstance.
Parameters
ChemSimImpl *csi is a pointer the concrete implementation of stochastic simulation algorithm.
Note
ChemSim simply stores the csi pointer but does not manage its memory. Make sure that csi is always a valid pointer while ChemSim is used.
Definition at line 20 of file ChemSim.cpp.
References _pimpl.
Referenced by CController::initialize().
Member Data Documentation
ChemSimImpl * ChemSim::_pimpl = 0 static private
Store a pointer to a specific implementation of stochastic chemical kinetics; no ownership.
Definition at line 74 of file ChemSim.h.
Referenced by addReaction(), initialize(), printReactions(), removeReaction(), run(), and setInstance().
The documentation for this class was generated from the following files:
M3SYM/Chemistry/ChemSim.h
M3SYM/Chemistry/ChemSim.cpp