MEDYAN: MCylinder Class Reference
MCylinder Class Reference
Used to hold mechanical properties of a Cylinder.
#include <MCylinder.h>
Public Member Functions
MCylinder (short filamentType, double eqLength)
Constructor sets equlilibrium length, and also adjusts other parameters according to this length.
~MCylinder ()
void setCylinder (Cylinder *c)
Set parent.
Cylinder * getCylinder ()
void setEqLength (short filamentType, double l)
Set the equlilibrium length, which changes mechanical constants accordingly.
double getEqLength ()
Get the current equlibrium length of this MCylinder.
void setEqTheta (double theta)
Mechanical parameter management function.
double getEqTheta ()
Mechanical parameter management function.
void setEqPhi (double phi)
Mechanical parameter management function.
double getEqPhi ()
Mechanical parameter management function.
void setStretchingConst (double k)
Mechanical parameter management function.
double getStretchingConst ()
Mechanical parameter management function.
void setBendingConst (double k)
Mechanical parameter management function.
double getBendingConst ()
Mechanical parameter management function.
void setTwistingConst (double k)
Mechanical parameter management function.
double getTwistingConst ()
Mechanical parameter management function.
void setExVolConst (double k)
Mechanical parameter management function.
double getExVolConst ()
Mechanical parameter management function.
void setLength (double l)
Mechanical parameter management function.
double getLength ()
Mechanical parameter management function.
Private Attributes
Cylinder * _pCylinder
parent cylinder
double _eqLength
Length of unstretched cylinder.
double _eqTheta
Equilibrium value for angle in bending potential.
double _eqPhi
Equilibrium value of twisiting potential.
double _kStretch
Local stretching constant, describes axial stretching of a single cylinder.
double _kBend
Local bending constant, which describes bending interaction between current and PREVIOUS cylinders.
double _kTwist
Local twisting constant, which describes stretching interaction between current and PREVIOUS cylinders.
double _kExVol
Local excluded volume constant, which describes excluded volume interactions between cylinders.
double _currentLength
The current length of the cylinder.
Detailed Description
Used to hold mechanical properties of a Cylinder.
The class describes interaction between 2 Beads connected by a Cylinder in the same Filament, and its associated equilibrium constants.
Definition at line 29 of file MCylinder.h.
Constructor & Destructor Documentation
MCylinder()
MCylinder::MCylinder (short filamentType, double eqLength)
Constructor sets equlilibrium length, and also adjusts other parameters according to this length.
Definition at line 21 of file MCylinder.cpp.
References MechParams::FBendingTheta, SysParams::Mechanics(), and MechParams::VolumeK.
~MCylinder()
MCylinder::~MCylinder () inline
Definition at line 53 of file MCylinder.h.
Member Function Documentation
getBendingConst()
double MCylinder::getBendingConst () inline
Mechanical parameter management function.
Definition at line 76 of file MCylinder.h.
References _kBend.
getCylinder()
Cylinder* MCylinder::getCylinder () inline
Definition at line 57 of file MCylinder.h.
References _pCylinder, and setEqLength().
getEqLength()
double MCylinder::getEqLength () inline
Get the current equlibrium length of this MCylinder.
Definition at line 62 of file MCylinder.h.
References _eqLength, and setEqTheta().
Referenced by Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), Filament::polymerizeMinusEnd(), Filament::polymerizePlusEnd(), and Tensions::print().
getEqPhi()
double MCylinder::getEqPhi () inline
Mechanical parameter management function.
Definition at line 70 of file MCylinder.h.
References _eqPhi.
getEqTheta()
double MCylinder::getEqTheta () inline
Mechanical parameter management function.
Definition at line 67 of file MCylinder.h.
References _eqTheta.
getExVolConst()
double MCylinder::getExVolConst () inline
Mechanical parameter management function.
Definition at line 82 of file MCylinder.h.
References _kExVol.
getLength()
double MCylinder::getLength () inline
Mechanical parameter management function.
Definition at line 85 of file MCylinder.h.
References _currentLength.
Referenced by Tensions::print().
getStretchingConst()
double MCylinder::getStretchingConst () inline
Mechanical parameter management function.
Definition at line 73 of file MCylinder.h.
References _kStretch.
Referenced by MTOCAttachment< MTOCInteractionType >::computeEnergy(), MTOCAttachment< MTOCInteractionType >::computeForces(), MTOCAttachment< MTOCInteractionType >::computeForcesAux(), and Tensions::print().
getTwistingConst()
double MCylinder::getTwistingConst () inline
Mechanical parameter management function.
Definition at line 79 of file MCylinder.h.
References _kTwist.
setBendingConst()
void MCylinder::setBendingConst (double k) inline
Mechanical parameter management function.
Definition at line 75 of file MCylinder.h.
setCylinder()
void MCylinder::setCylinder (Cylinder * c) inline
Set parent.
Definition at line 56 of file MCylinder.h.
setEqLength()
void MCylinder::setEqLength (short filamentType, double l)
Set the equlilibrium length, which changes mechanical constants accordingly.
Definition at line 35 of file MCylinder.cpp.
References GeoParams::cylinderSize, MechParams::FBendingK, MechParams::FStretchingK, SysParams::Geometry(), and SysParams::Mechanics().
Referenced by Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), getCylinder(), Filament::polymerizeMinusEnd(), and Filament::polymerizePlusEnd().
setEqPhi()
void MCylinder::setEqPhi (double phi) inline
Mechanical parameter management function.
Definition at line 69 of file MCylinder.h.
setEqTheta()
void MCylinder::setEqTheta (double theta) inline
Mechanical parameter management function.
Definition at line 66 of file MCylinder.h.
Referenced by getEqLength().
setExVolConst()
void MCylinder::setExVolConst (double k) inline
Mechanical parameter management function.
Definition at line 81 of file MCylinder.h.
setLength()
void MCylinder::setLength (double l) inline
Mechanical parameter management function.
Definition at line 84 of file MCylinder.h.
setStretchingConst()
void MCylinder::setStretchingConst (double k) inline
Mechanical parameter management function.
Definition at line 72 of file MCylinder.h.
setTwistingConst()
void MCylinder::setTwistingConst (double k) inline
Mechanical parameter management function.
Definition at line 78 of file MCylinder.h.
Member Data Documentation
_currentLength
double MCylinder::_currentLength private
The current length of the cylinder.
Definition at line 47 of file MCylinder.h.
Referenced by getLength().
_eqLength
double MCylinder::_eqLength private
Length of unstretched cylinder.
Definition at line 34 of file MCylinder.h.
Referenced by getEqLength().
_eqPhi
double MCylinder::_eqPhi private
Equilibrium value of twisiting potential.
Definition at line 37 of file MCylinder.h.
Referenced by getEqPhi().
_eqTheta
double MCylinder::_eqTheta private
Equilibrium value for angle in bending potential.
For interaction between this cylinder and PREVIOUS
Definition at line 35 of file MCylinder.h.
Referenced by getEqTheta().
_kBend
double MCylinder::_kBend private
Local bending constant, which describes bending interaction between current and PREVIOUS cylinders.
Definition at line 40 of file MCylinder.h.
Referenced by getBendingConst().
_kExVol
double MCylinder::_kExVol private
Local excluded volume constant, which describes excluded volume interactions between cylinders.
Definition at line 44 of file MCylinder.h.
Referenced by getExVolConst().
_kStretch
double MCylinder::_kStretch private
Local stretching constant, describes axial stretching of a single cylinder.
Definition at line 38 of file MCylinder.h.
Referenced by getStretchingConst().
_kTwist
double MCylinder::_kTwist private
Local twisting constant, which describes stretching interaction between current and PREVIOUS cylinders.
Definition at line 42 of file MCylinder.h.
Referenced by getTwistingConst().
_pCylinder
Cylinder* MCylinder::_pCylinder private
parent cylinder
Definition at line 32 of file MCylinder.h.
Referenced by getCylinder().
The documentation for this class was generated from the following files:
src/Structure/MCylinder.h
src/Structure/MCylinder.cpp