M3Sym: MotorBindingManager Class Reference
MotorBindingManager Class Reference
Manager for MotorGhost binding.
#include <ReactionManager.h>
Public Member Functions
MotorBindingManager (vector< tuple< int, SpeciesType >> reactants, vector< tuple< int, SpeciesType >> products, float rate, float rMin, float rMax, int ID)
~MotorBindingManager ()
virtual void addReaction (CCylinder *cc1, CCylinder *cc2)
Add this chemical reaction to two ccylinders if within the reaction range.
CylinderNeighborList * getNeighborList ()
Get neighbor list.
float getRMin ()
Getter for parameters of reaction.
float getRMax ()
Getter for parameters of reaction.
int getReactionID ()
Getter for parameters of reaction.
Protected Attributes
vector< tuple< int, SpeciesType > > _reactants
Species identifier vectors.
vector< tuple< int, SpeciesType > > _products
Products in this reaction.
float _rate
Rate of reaction.
float _rMin
Minimum reaction range.
float _rMax
Maximum reaction range.
int _reactionID
Static Protected Attributes
static SubSystem * _ps = 0
A subsystem pointer to intialize and call chemical callbacks.
Detailed Description
Manager for MotorGhost binding.
Definition at line 247 of file ReactionManager.h.
Constructor & Destructor Documentation
MotorBindingManager::MotorBindingManager (vector< tuple< int, SpeciesType >> reactants, vector< tuple< int, SpeciesType >> products, float rate, float rMin, float rMax, int ID) inline
Definition at line 250 of file ReactionManager.h.
MotorBindingManager::~MotorBindingManager () inline
Definition at line 254 of file ReactionManager.h.
Member Function Documentation
void MotorBindingManager::addReaction (CCylinder * cc1, CCylinder * cc2) virtual
Add this chemical reaction to two ccylinders if within the reaction range.
Implements CrossFilamentRxnManager.
Definition at line 1046 of file ReactionManager.cpp.
References CCylinder::addCrossCylinderReaction(), BULK, DIFFUSING, Compartment::findSpeciesByMolecule(), SystemParameters::Geometry(), CCylinder::getCMonomer(), CCylinder::getCompartment(), CompartmentGrid::instance(), MOTORBINDING, ReactionBase::setReactionID(), ReactionBase::setReactionType(), CMonomer::speciesBound(), and CMonomer::speciesMotor().
CylinderNeighborList* CylinderNLContainer::getNeighborList () inline inherited
Get neighbor list.
Definition at line 41 of file NeighborListContainer.h.
References CylinderNLContainer::_neighborList.
int CrossFilamentRxnManager::getReactionID () inline inherited
Getter for parameters of reaction.
Definition at line 228 of file ReactionManager.h.
References CrossFilamentRxnManager::_reactionID.
float CrossFilamentRxnManager::getRMax () inline inherited
Getter for parameters of reaction.
Definition at line 227 of file ReactionManager.h.
References CrossFilamentRxnManager::_rMax.
float CrossFilamentRxnManager::getRMin () inline inherited
Getter for parameters of reaction.
Definition at line 226 of file ReactionManager.h.
Member Data Documentation
vector<tuple<int,SpeciesType> > CrossFilamentRxnManager::_products protected inherited
Products in this reaction.
Definition at line 205 of file ReactionManager.h.
SubSystem * CrossFilamentRxnManager::_ps = 0 static protected inherited
A subsystem pointer to intialize and call chemical callbacks.
Definition at line 201 of file ReactionManager.h.
Referenced by SimpleManagerImpl::initialize().
float CrossFilamentRxnManager::_rate protected inherited
Rate of reaction.
Definition at line 207 of file ReactionManager.h.
vector<tuple<int,SpeciesType> > CrossFilamentRxnManager::_reactants protected inherited
Species identifier vectors.
Reactants in this reaction
Definition at line 204 of file ReactionManager.h.
int CrossFilamentRxnManager::_reactionID protected inherited
Definition at line 211 of file ReactionManager.h.
Referenced by CrossFilamentRxnManager::getReactionID().
float CrossFilamentRxnManager::_rMax protected inherited
Maximum reaction range.
Definition at line 209 of file ReactionManager.h.
Referenced by CrossFilamentRxnManager::getRMax().
float CrossFilamentRxnManager::_rMin protected inherited
Minimum reaction range.
Definition at line 208 of file ReactionManager.h.
The documentation for this class was generated from the following files:
M3SYM/Chemistry/ReactionManager.h
M3SYM/Chemistry/ReactionManager.cpp