M3Sym: FletcherRieves Class Reference
FletcherRieves Class Reference
The Fletcher-Rieves method for conjugate gradient minimization.
#include <CGFletcherRievesMethod.h>
Public Member Functions
void minimize (ForceFieldManager &FFM)
Minimize the system.
Protected Member Functions
void swap (double &a, double &b)
helpers for searching and bracketing
void shift2 (double &a, double &b, double c)
void shift3 (double &a, double &b, double &c, double d)
double sign (double a, double b)
void makeBracket (ForceFieldManager &FFM, double &ax, double &bx, double &cx, double &fa, double &fb, double &fc)
Gracketing function (from Numerical Recipes in C++, second edition)
void printForces ()
double gradSquare ()
For use in minimization.
double gradAuxSquare ()
For use in minimization.
double gradDotProduct ()
For use in minimization.
void moveBeads (double d)
For use in minimization.
void moveBeadsAux (double d)
For use in minimization.
void shiftGradient (double d)
For use in minimization.
double goldenSection1 (ForceFieldManager &FFM)
Linear search method.
double goldenSection2 (ForceFieldManager &FFM)
Linear search method.
double binarySearch (ForceFieldManager &FFM)
Linear search method.
double backtrackingLineSearch (ForceFieldManager &FFM)
Linear search method.
double quadraticLineSearch (ForceFieldManager &FFM)
Linear search method.
Protected Attributes
const double LSENERGYTOL = 1e-6
Line search energy tolerance for all linesearch methods.
int _energyChangeCounter = 0
Energy counter, for use in linear search methods.
const int ENERGYCHANGEITER = 20
Max number of iterations allowed where """.
const double GRADTOL = 1e-10
Gradient minimization tolerance.
const double LAMBDAMIN = 0.001
Lambda parameter for use in linear search methods.
const double LAMBDAMAX = 1
Max lambda that can be returned, used in all methods.
const double MAXDIST = 1
Max distance beads can be moved, used only in backtracking line search.
const double LAMBDAREDUCE = 0.1
Parameter used in backtracking line search.
const double BACKTRACKSLOPE = 0.1
Backtrack slope parameter.
const double QUADRATICTOL = 0.1
Parameter used in quadratic line search.
const double EPSQUAD = 1e-28
Parameter used in quadratic line search.
const double PHI = (1 + sqrt(5)) / 2
Parameter used in golden section.
const double R = 0.61803399
Parameter used in golden section.
const double C = 1 - R
Parameter used in golden section.
Detailed Description
The Fletcher-Rieves method for conjugate gradient minimization.
Definition at line 27 of file CGFletcherRievesMethod.h.
Member Function Documentation
double CGMethod::backtrackingLineSearch (ForceFieldManager & FFM) protected inherited
Linear search method.
Definition at line 263 of file CGMethod.cpp.
References CGMethod::_energyChangeCounter, CGMethod::BACKTRACKSLOPE, ForceFieldManager::computeEnergy(), BeadDB::instance(), CGMethod::LAMBDAMAX, CGMethod::LAMBDAREDUCE, CGMethod::LSENERGYTOL, and CGMethod::MAXDIST.
Referenced by minimize(), and PolakRibiere::minimize().
double CGMethod::binarySearch (ForceFieldManager & FFM) protected inherited
Linear search method.
Definition at line 249 of file CGMethod.cpp.
References ForceFieldManager::computeEnergy(), and CGMethod::LSENERGYTOL.
double CGMethod::goldenSection1 (ForceFieldManager & FFM) protected inherited
Linear search method.
Definition at line 180 of file CGMethod.cpp.
References ForceFieldManager::computeEnergy(), CGMethod::LAMBDAMAX, CGMethod::LAMBDAMIN, and CGMethod::LSENERGYTOL.
double CGMethod::goldenSection2 (ForceFieldManager & FFM) protected inherited
Linear search method.
Definition at line 209 of file CGMethod.cpp.
References CGMethod::C, ForceFieldManager::computeEnergy(), CGMethod::LAMBDAMAX, CGMethod::LAMBDAMIN, CGMethod::LSENERGYTOL, CGMethod::R, CGMethod::shift2(), and CGMethod::shift3().
double CGMethod::gradAuxSquare () protected inherited
For use in minimization.
Definition at line 116 of file CGMethod.cpp.
References BeadDB::instance().
Referenced by minimize(), and PolakRibiere::minimize().
double CGMethod::gradDotProduct () protected inherited
For use in minimization.
Definition at line 125 of file CGMethod.cpp.
References BeadDB::instance().
Referenced by minimize(), PolakRibiere::minimize(), and CGMethod::quadraticLineSearch().
double CGMethod::gradSquare () protected inherited
For use in minimization.
Definition at line 108 of file CGMethod.cpp.
References BeadDB::instance().
Referenced by minimize(), and PolakRibiere::minimize().
void CGMethod::makeBracket (ForceFieldManager & FFM, double & ax, double & bx, double & cx, double & fa, double & fb, double & fc) protected inherited
Gracketing function (from Numerical Recipes in C++, second edition)
Definition at line 42 of file CGMethod.cpp.
References ForceFieldManager::computeEnergy(), CGMethod::PHI, CGMethod::shift3(), CGMethod::sign(), and CGMethod::swap().
void FletcherRieves::minimize (ForceFieldManager & FFM) virtual
Minimize the system.
!!!!!! need to know
Implements CGMethod.
Definition at line 19 of file CGFletcherRievesMethod.cpp.
References CGMethod::_energyChangeCounter, CGMethod::backtrackingLineSearch(), ForceFieldManager::computeEnergy(), ForceFieldManager::computeForces(), ForceFieldManager::computeForcesAux(), CGMethod::ENERGYCHANGEITER, CGMethod::gradAuxSquare(), CGMethod::gradDotProduct(), CGMethod::gradSquare(), CGMethod::GRADTOL, BeadDB::instance(), CGMethod::moveBeads(), CGMethod::printForces(), and CGMethod::shiftGradient().
void CGMethod::moveBeads (double d) protected inherited
For use in minimization.
Definition at line 135 of file CGMethod.cpp.
References BeadDB::instance().
Referenced by minimize(), and PolakRibiere::minimize().
void CGMethod::moveBeadsAux (double d) protected inherited
For use in minimization.
Definition at line 148 of file CGMethod.cpp.
References BeadDB::instance().
Referenced by CGMethod::quadraticLineSearch().
void CGMethod::printForces () protected inherited
Definition at line 169 of file CGMethod.cpp.
References BeadDB::instance().
Referenced by minimize(), and PolakRibiere::minimize().
double CGMethod::quadraticLineSearch (ForceFieldManager & FFM) protected inherited
Linear search method.
Definition at line 316 of file CGMethod.cpp.
References CGMethod::_energyChangeCounter, CGMethod::BACKTRACKSLOPE, ForceFieldManager::computeEnergy(), ForceFieldManager::computeForcesAux(), CGMethod::EPSQUAD, CGMethod::gradDotProduct(), BeadDB::instance(), CGMethod::LAMBDAMAX, CGMethod::LAMBDAREDUCE, CGMethod::LSENERGYTOL, and CGMethod::moveBeadsAux().
void CGMethod::shift2 (double & a, double & b, double c) inline protected inherited
Definition at line 25 of file CGMethod.cpp.
Referenced by CGMethod::goldenSection2().
void CGMethod::shift3 (double & a, double & b, double & c, double d) inline protected inherited
Definition at line 30 of file CGMethod.cpp.
Referenced by CGMethod::goldenSection2(), and CGMethod::makeBracket().
void CGMethod::shiftGradient (double d) protected inherited
For use in minimization.
Definition at line 159 of file CGMethod.cpp.
References BeadDB::instance().
Referenced by minimize(), and PolakRibiere::minimize().
double CGMethod::sign (double a, double b) inline protected inherited
Definition at line 36 of file CGMethod.cpp.
Referenced by CGMethod::makeBracket().
void CGMethod::swap (double & a, double & b) inline protected inherited
helpers for searching and bracketing
Definition at line 19 of file CGMethod.cpp.
Referenced by CGMethod::makeBracket().
Member Data Documentation
int CGMethod::_energyChangeCounter = 0 protected inherited
Energy counter, for use in linear search methods.
Number of iterations where energy has not changed by an amount more than LSENERGYTOL
Definition at line 72 of file CGMethod.h.
Referenced by CGMethod::backtrackingLineSearch(), minimize(), PolakRibiere::minimize(), and CGMethod::quadraticLineSearch().
const double CGMethod::BACKTRACKSLOPE = 0.1 protected inherited
Backtrack slope parameter.
Definition at line 45 of file CGMethod.h.
Referenced by CGMethod::backtrackingLineSearch(), and CGMethod::quadraticLineSearch().
const double CGMethod::C = 1 - R protected inherited
Parameter used in golden section.
Definition at line 58 of file CGMethod.h.
Referenced by CGMethod::goldenSection2().
const int CGMethod::ENERGYCHANGEITER = 20 protected inherited
Max number of iterations allowed where """.
Definition at line 73 of file CGMethod.h.
Referenced by minimize(), and PolakRibiere::minimize().
const double CGMethod::EPSQUAD = 1e-28 protected inherited
Parameter used in quadratic line search.
Definition at line 51 of file CGMethod.h.
Referenced by CGMethod::quadraticLineSearch().
const double CGMethod::GRADTOL = 1e-10 protected inherited
Gradient minimization tolerance.
Definition at line 75 of file CGMethod.h.
Referenced by minimize(), and PolakRibiere::minimize().
const double CGMethod::LAMBDAMAX = 1 protected inherited
Max lambda that can be returned, used in all methods.
Definition at line 38 of file CGMethod.h.
Referenced by CGMethod::backtrackingLineSearch(), CGMethod::goldenSection1(), CGMethod::goldenSection2(), and CGMethod::quadraticLineSearch().
const double CGMethod::LAMBDAMIN = 0.001 protected inherited
Lambda parameter for use in linear search methods.
Minimum lambda that can be returned, used only in golden section for now
Definition at line 37 of file CGMethod.h.
Referenced by CGMethod::goldenSection1(), and CGMethod::goldenSection2().
const double CGMethod::LAMBDAREDUCE = 0.1 protected inherited
Parameter used in backtracking line search.
Lambda reduction parameter for backtracking
Definition at line 44 of file CGMethod.h.
Referenced by CGMethod::backtrackingLineSearch(), and CGMethod::quadraticLineSearch().
const double CGMethod::LSENERGYTOL = 1e-6 protected inherited
Line search energy tolerance for all linesearch methods.
Definition at line 61 of file CGMethod.h.
Referenced by CGMethod::backtrackingLineSearch(), CGMethod::binarySearch(), CGMethod::goldenSection1(), CGMethod::goldenSection2(), and CGMethod::quadraticLineSearch().
const double CGMethod::MAXDIST = 1 protected inherited
Max distance beads can be moved, used only in backtracking line search.
Definition at line 39 of file CGMethod.h.
Referenced by CGMethod::backtrackingLineSearch().
const double CGMethod::PHI = (1 + sqrt(5)) / 2 protected inherited
Parameter used in golden section.
Definition at line 56 of file CGMethod.h.
Referenced by CGMethod::makeBracket().
const double CGMethod::QUADRATICTOL = 0.1 protected inherited
Parameter used in quadratic line search.
Definition at line 50 of file CGMethod.h.
const double CGMethod::R = 0.61803399 protected inherited
Parameter used in golden section.
Definition at line 57 of file CGMethod.h.
Referenced by CGMethod::goldenSection2().
The documentation for this class was generated from the following files:
M3SYM/Mechanics/Minimizer/CGFletcherRievesMethod.h
M3SYM/Mechanics/Minimizer/CGFletcherRievesMethod.cpp