M3Sym: LinkerDB Class Reference
LinkerDB Class Reference
A database for all Linkers in the system.
#include <LinkerDB.h>
Public Member Functions
LinkerDB (const LinkerDB &rhs)=delete
Copying is not allowed.
LinkerDB & operator= (LinkerDB &rhs)=delete
Assignment is not allowed.
void addLinker (Linker *l)
Create a new linker.
void removeLinker (Linker *l)
Remove a linker.
int getLinkerID ()
Get current linker ID, and update the ID counter.
Static Public Member Functions
static LinkerDB * instance ()
Get instance.
Private Types
typedef list< Linker * > ldb
Private Member Functions
LinkerDB ()
Private Attributes
T elements
STL member.
Static Private Attributes
static int _currentLinkerID = 0
To assign linker IDs.
static LinkerDB * _instance = 0
Singleton instance.
Detailed Description
A database for all Linkers in the system.
This LinkerDB inherits from list and manage all creations and removing of Linkers objects, as well as some standard list functions and iterators.
Definition at line 29 of file LinkerDB.h.
Member Typedef Documentation
typedef list<Linker*> LinkerDB::ldb private
Definition at line 31 of file LinkerDB.h.
Constructor & Destructor Documentation
LinkerDB::LinkerDB (const LinkerDB & rhs) delete
Copying is not allowed.
LinkerDB::LinkerDB () inline private
Definition at line 60 of file LinkerDB.h.
Referenced by instance().
Member Function Documentation
void LinkerDB::addLinker (Linker * l) inline
Create a new linker.
Definition at line 49 of file LinkerDB.h.
Referenced by Linker::Linker().
int LinkerDB::getLinkerID () inline
Get current linker ID, and update the ID counter.
Definition at line 54 of file LinkerDB.h.
References _currentLinkerID.
Referenced by Linker::Linker().
LinkerDB * LinkerDB::instance () static
Get instance.
Definition at line 19 of file LinkerDB.cpp.
References _instance, and LinkerDB().
Referenced by LinkerFF::computeEnergy(), LinkerFF::computeForces(), LinkerFF::computeForcesAux(), Linker::Linker(), Output::printBasicSnapshot(), Controller::updateSystem(), and Linker::~Linker().
LinkerDB& LinkerDB::operator= (LinkerDB & rhs) delete
Assignment is not allowed.
void LinkerDB::removeLinker (Linker * l) inline
Remove a linker.
Definition at line 51 of file LinkerDB.h.
Referenced by Linker::~Linker().
Member Data Documentation
int LinkerDB::_currentLinkerID = 0 static private
To assign linker IDs.
Definition at line 57 of file LinkerDB.h.
Referenced by getLinkerID().
LinkerDB * LinkerDB::_instance = 0 static private
Singleton instance.
Definition at line 59 of file LinkerDB.h.
Referenced by instance().
T std::list< T >::elements inherited
STL member.
The documentation for this class was generated from the following files:
M3SYM/Structure/LinkerDB.h
M3SYM/Structure/LinkerDB.cpp