CytoSim: SpeciesDB Class Reference
SpeciesDB Class Reference
SpeciesDB should be used for obtaining new objects of the Species hieararchy.
#include <SpeciesDB.h>
Public Member Functions
void Initialize ()
Species * makeSpecies (const SpeciesType &name, int N=0)
SBulk * makeSBulk (const SpeciesType &name, int N=0)
Static Public Member Functions
static SpeciesDB * getInstance ()
Detailed Description
SpeciesDB should be used for obtaining new objects of the Species hieararchy.
It internally uses the StandardSpeciesFactory to accomplish the construction. It is also a database that can be queried to obtain a pointer to a Species if the Species' ID is known. This class is a singleton, and should be used like this:
 SpeciesDB *sdb = SpeciesDB::getInstance();
 sdb->Initialize();
Definition at line 38 of file SpeciesDB.h.
Member Function Documentation
SpeciesDB * SpeciesDB::getInstance () [static]
Definition at line 14 of file SpeciesDB.cpp.
Referenced by main().
void SpeciesDB::Initialize ()
Definition at line 21 of file SpeciesDB.cpp.
Referenced by main().
SBulk* SpeciesDB::makeSBulk (const SpeciesType & name, int N = 0) [inline]
Definition at line 47 of file SpeciesDB.h.
References SpeciesFactory::makeSBulk().
Referenced by main().
Species* SpeciesDB::makeSpecies (const SpeciesType & name, int N = 0) [inline]
Definition at line 42 of file SpeciesDB.h.
References SpeciesFactory::makeSpecies().
Referenced by main().
The documentation for this class was generated from the following files:
CytoSim/SpeciesDB.h
CytoSim/SpeciesDB.cpp