M3Sym: Reaction< M, N > Class Template Reference
Reaction< M, N > Class Template Reference
Represents a concrete chemical reaction, such as A + B -> C, where M is the number of reactants and N is the number of products.
#include <Reaction.h>
Public Member Functions
Reaction (initializer_list< Species * > species, float rate=0.0, bool isProtoCompartment=false)
The main constructor:
template<typename InputContainer >
Reaction (const InputContainer &species, float rate=0.0, bool isProtoCompartment=false)
The main constructor:
Reaction (const Reaction &rb)=delete
no copying (including all derived classes)
Reaction & operator= (Reaction &rb)=delete
no assignment (including all derived classes)
virtual ~Reaction () noexcept
Destructor Tell Rspecies to remove this Reaction from its internal lists of reactions.
virtual RSpecies ** rspecies () override
Returns a pointer to the first element of array<RSpecies*, M+N> The type of the pointer is RSpecies**.
virtual vector< ReactionBase * > getAffectedReactions () override
Return a list of reactions which rates would be affected if this reaction were to be executed.
ReactionBase * clone (const SpeciesPtrContainerVector &spcv)
Copy this reaction using SpeciesPtrContainerVector &spcv as a source of analogous Species.
void setReactionType (ReactionType rxnType)
Set reaction type.
ReactionType getReactionType ()
Get reaction type.
void setRate (float rate)
Sets the ReactionBase rate to the parameter "rate".
void setRnode (RNode *rhs)
Sets the RNode pointer associated with this ReactionBase to rhs.
float getRate () const
Returns the rate associated with this ReactionBase.
float getBareRate () const
Returns the bare rate associated with this ReacitonBase.
void setReactionID (int ID)
For cross filament reactions (SHOULD EVENTUALLY BE MOVED)
int getReactionID ()
RNode * getRnode () const
Returns a pointer to the RNode associated with this ReactionBase.
unsigned short getM () const
Returns the number of reactant RSpecies.
unsigned short getN () const
Returns the number of product RSpecies.
unsigned short size () const
Returns the total number of RSpecies.
Composite * getParent ()
Return the parent Composite object pointer, to which this Reaction belongs to.
void setParent (Composite *other)
Set the parent Composite object pointer to which this Reaction belongs to.
bool hasParent () const
Returns true if this Reaction has a parent Composite object to which it belongs to.
Composite * getRoot ()
Get the root parent (i.e. follow the pointers of parentage until the root node in the Composition hieararchy)
int getProductOfReactants () const
Computes the product of the copy number of all reactant RSpecies.
int getProductOfProducts () const
Computes the product of the copy number of all product RSpecies minus maxium allowed copy number.
bool isPassivated () const
Return true if the ReactionBase is currently passivated.
bool containsSpecies (Species *s) const
Returns true of this Reaction contains Species *s either as a reactant or a product.
const vector< ReactionBase * > & dependents ()
Return a const reference to the vector of dependent ReactionBases.
void makeStep ()
Fire the ReactionBase - make a single step, where reactant RSpecies copy numbers are decreased by one, and the product RSpecies copy numbers are increased by one.
float computePropensity () const
Compute the ReactionBase propensity that is needed by a Gillespie like algorithm: rate*reactant_1.getN()*reactant_2.getN()...
void passivateReaction ()
Usually is applied to ReactionBase objects with propensity of 0 (e.g.
void activateReactionUnconditional ()
Requests that ReactionBase objects that may affect this Reaction to start tracking it, which can be used to follow ReactionBase objects whose propensities change upong firing of some ReactionBase.
void activateReaction ()
Requests that Reaction objects that may affect this Reaction to start tracking it, which can be used to follow Reaction objects whose propensities change upong firing of some Reaction.
void printDependents ()
Print the ReactionBases that are affacted by this ReactionBase being fired.
void registerNewDependent (ReactionBase *r)
Request that the ReactionBase *r adds this ReactionBase to its list of dependents which it affects.
void unregisterDependent (ReactionBase *r)
Request that the ReactionBase *r removes this ReactionBase from its list of dependents which it affects.
Protected Member Functions
template<typename InputContainer >
void initializeSpecies (const InputContainer &species)
An implementation method used by the constructor.
virtual unsigned short getMImpl () const override
Implementation of getM()
virtual unsigned short getNImpl () const override
Implementation of getN()
virtual unsigned short sizeImpl () const override
Implementation of size()
virtual bool is_equal (const ReactionBase &other) const override
Implementation of the operator==(...)
virtual int getProductOfReactantsImpl () const override
Implementation of getProductOfReactants()
virtual float computePropensityImpl () const override
Implementation of computePropensity()
virtual int getProductOfProductsImpl () const override
Implementation of getProductOfProducts()
virtual bool containsSpeciesImpl (Species *s) const override
Implementation of containsSpecies()
virtual void makeStepImpl () override
Implementation of makeStep()
virtual void activateReactionUnconditionalImpl () override
Implementation of activateReactionUnconditional()
virtual void passivateReactionImpl () override
Implementation of passivateReaction()
virtual void printToStream (ostream &os) const override
Print information about this reaction to ostream.
virtual Reaction< M, N > * cloneImpl (const SpeciesPtrContainerVector &spcv) override
Implementation of clone()
template<>
float computePropensityImpl () const
(Private) implementation of the computePropensity() method to be elaborated in derived classes.
template<>
void makeStepImpl ()
(Private) implementation of the makeStep() method to be elaborated in derived classes.
Protected Attributes
vector< ReactionBase * > _dependents
Pointers to ReactionBase objects that depend on this ReactionBase being executed.
RNode * _rnode
A pointer to an RNode object which is used to implement a Gillespie-like algorithm (e.g. NRM)
Composite * _parent
A pointer to a Composite object to which this Reaction belongs.
float _rate
the rate for this ReactionBase
float _rate_bare
the bare rate for this ReactionBase (original rate)
ReactionType _reactionType
Reaction type enumeration.
bool _isProtoCompartment = false
short _reactionID = -1
Reaction is in proto compartment (Do not copy as a dependent, not in chemsim)
Private Attributes
array< RSpecies *, M+N > _rspecies
An array of RSpecies objects (reactants followed by products)
Detailed Description
template<unsigned short M, unsigned short N>
class Reaction< M, N >
Represents a concrete chemical reaction, such as A + B -> C, where M is the number of reactants and N is the number of products.
Reaction<M,N> encodes a chemical reaction between M reactants and N products. It follows the ReactionBase interface, where many methods are defined. Most of the methods defined in Reaction<M,N> are specific implementations of virtual functions declared in ReactionBase. Hence, to a very large degree, Reaction<M,N> is an implementation class, while ReactionBase provides the public interface for reaction objects. The documentation of the latter should be mainly consulted when working with reactions.
Definition at line 31 of file Reaction.h.
Constructor & Destructor Documentation
template<unsigned short M, unsigned short N> Reaction< M, N >::Reaction (initializer_list< Species * > species, float rate = 0.0, bool isProtoCompartment = false) inline
The main constructor:
Parameters
species - are reactants and products put together into a single list (starting from reactants)
rate - the rate constant for this ReactionBase
Definition at line 38 of file Reaction.h.
References Reaction< M, N >::initializeSpecies().
template<unsigned short M, unsigned short N> template<typename InputContainer > Reaction< M, N >::Reaction (const InputContainer & species, float rate = 0.0, bool isProtoCompartment = false) inline
The main constructor:
Parameters
it_begin - an iterator to the beginning of an RSpecies* container
it_end - an iterator to the end of an RSpecies* container
rate - the rate constant for this ReactionBase
Definition at line 48 of file Reaction.h.
References Reaction< M, N >::initializeSpecies().
template<unsigned short M, unsigned short N> Reaction< M, N >::Reaction (const Reaction< M, N > & rb) delete
no copying (including all derived classes)
template<unsigned short M, unsigned short N> virtual Reaction< M, N >::~Reaction () inline virtual noexcept
Destructor Tell Rspecies to remove this Reaction from its internal lists of reactions.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 71 of file Reaction.h.
Member Function Documentation
void ReactionBase::activateReaction () inline inherited
Requests that Reaction objects that may affect this Reaction to start tracking it, which can be used to follow Reaction objects whose propensities change upong firing of some Reaction.
This request will be ignored if the Reaction's propensity is still zero.
Definition at line 297 of file ReactionBase.h.
References ReactionBase::activateReactionUnconditional(), ReactionBase::getProductOfProducts(), and ReactionBase::getProductOfReactants().
Referenced by CCylinder::addCrossCylinderReaction(), and CCylinder::addInternalReaction().
void ReactionBase::activateReactionUnconditional () inline inherited
Requests that ReactionBase objects that may affect this Reaction to start tracking it, which can be used to follow ReactionBase objects whose propensities change upong firing of some ReactionBase.
This request is acted upond unconditionally.
Definition at line 290 of file ReactionBase.h.
References ReactionBase::activateReactionUnconditionalImpl().
Referenced by ReactionBase::activateReaction().
template<unsigned short M, unsigned short N> template void Reaction< M, N >::activateReactionUnconditionalImpl () override protected virtual
Implementation of activateReactionUnconditional()
Implements ReactionBase.
Definition at line 26 of file Reaction.cpp.
References RSpecies::beginProductReactions(), RSpecies::beginReactantReactions(), RSpecies::endProductReactions(), and RSpecies::endReactantReactions().
ReactionBase* ReactionBase::clone (const SpeciesPtrContainerVector & spcv) inline inherited
Copy this reaction using SpeciesPtrContainerVector &spcv as a source of analogous Species.
Returns
the cloned ReactionBase pointer.
Note
the receving object should take care of the memory management of the returned pointer
Definition at line 105 of file ReactionBase.h.
References ReactionBase::cloneImpl().
template<unsigned short M, unsigned short N> template Reaction< 3, 0 > * Reaction< M, N >::cloneImpl (const SpeciesPtrContainerVector & spcv) override protected virtual
Implementation of clone()
check if that species exists in the compartment
if we didn't find it, use the old species
Create new reaction, copy ownership of signal
Copy reaction type
Implements ReactionBase.
Definition at line 67 of file Reaction.cpp.
References ReactionBase::_reactionID, ReactionBase::_reactionType, and SpeciesPtrContainerVector::species().
float ReactionBase::computePropensity () const inline inherited
Compute the ReactionBase propensity that is needed by a Gillespie like algorithm: rate*reactant_1.getN()*reactant_2.getN()...
Definition at line 273 of file ReactionBase.h.
References ReactionBase::computePropensityImpl().
Referenced by main(), ChemSimpleGillespieImpl::makeStep(), Reaction< M, N >::printToStream(), RNodeGillespie::reComputePropensity(), RNodeNRM::reComputePropensity(), RNodeGillespie::reset(), and RNodeNRM::RNodeNRM().
template<unsigned short M, unsigned short N> virtual float Reaction< M, N >::computePropensityImpl () const inline override protected virtual
Implementation of computePropensity()
Implements ReactionBase.
Definition at line 149 of file Reaction.h.
References ReactionBase::_rate, and Reaction< M, N >::getProductOfReactantsImpl().
template<> float Reaction< 1, 1 >::computePropensityImpl () const inline protected virtual
(Private) implementation of the computePropensity() method to be elaborated in derived classes.
Implements ReactionBase.
Definition at line 247 of file Reaction.h.
bool ReactionBase::containsSpecies (Species * s) const inline inherited
Returns true of this Reaction contains Species *s either as a reactant or a product.
Definition at line 202 of file ReactionBase.h.
References ReactionBase::containsSpeciesImpl().
template<unsigned short M, unsigned short N> virtual bool Reaction< M, N >::containsSpeciesImpl (Species * s) const inline override protected virtual
Implementation of containsSpecies()
Implements ReactionBase.
Definition at line 174 of file Reaction.h.
References Reaction< M, N >::_rspecies.
const vector<ReactionBase*>& ReactionBase::dependents () inline inherited
Return a const reference to the vector of dependent ReactionBases.
Note
One can obtain two different lists of affected ReactionBases: 1) via getAffectedReactionBases(), where the copy numbers do influence the dependencies, and 2) via dependents(), where dependencies stop being counted if the copy numbers of reactant species drop to 0.
Definition at line 242 of file ReactionBase.h.
References ReactionBase::_dependents.
Referenced by ChemGillespieImpl::makeStep(), ChemNRMImpl::makeStep(), RNodeGillespie::printDependents(), and RNodeNRM::printDependents().
template<unsigned short M, unsigned short N> virtual vector<ReactionBase*> Reaction< M, N >::getAffectedReactions () inline override virtual
Return a list of reactions which rates would be affected if this reaction were to be executed.
Implements ReactionBase.
Definition at line 84 of file Reaction.h.
References Reaction< M, N >::_rspecies.
Referenced by Reaction< M, N >::initializeSpecies(), and main().
float ReactionBase::getBareRate () const inline inherited
Returns the bare rate associated with this ReacitonBase.
Definition at line 134 of file ReactionBase.h.
References ReactionBase::_rate_bare.
unsigned short ReactionBase::getM () const inline inherited
Returns the number of reactant RSpecies.
Definition at line 146 of file ReactionBase.h.
References ReactionBase::getMImpl().
template<unsigned short M, unsigned short N> virtual unsigned short Reaction< M, N >::getMImpl () const inline override protected virtual
Implementation of getM()
Implements ReactionBase.
Definition at line 118 of file Reaction.h.
unsigned short ReactionBase::getN () const inline inherited
Returns the number of product RSpecies.
Definition at line 152 of file ReactionBase.h.
References ReactionBase::getNImpl().
Referenced by Reaction< M, N >::getProductOfReactantsImpl().
template<unsigned short M, unsigned short N> virtual unsigned short Reaction< M, N >::getNImpl () const inline override protected virtual
Implementation of getN()
Implements ReactionBase.
Definition at line 121 of file Reaction.h.
References A_reversible_B_numeric::N.
Composite* ReactionBase::getParent () inline inherited
Return the parent Composite object pointer, to which this Reaction belongs to.
If not present, return a nullptr.
Definition at line 165 of file ReactionBase.h.
References ReactionBase::_parent.
Referenced by ReactionBase::getRoot(), and main().
int ReactionBase::getProductOfProducts () const inline inherited
Computes the product of the copy number of all product RSpecies minus maxium allowed copy number.
Can be used to quickly determine whether this ReactionBase should be allowed to activate - if one of the products has a copy number equal to the maximum allowed, then zero is returned, indicating that this ReactionBase should not be (yet) activated.
Definition at line 189 of file ReactionBase.h.
References ReactionBase::getProductOfProductsImpl().
Referenced by ReactionBase::activateReaction().
template<unsigned short M, unsigned short N> virtual int Reaction< M, N >::getProductOfProductsImpl () const inline override protected virtual
Implementation of getProductOfProducts()
Implements ReactionBase.
Definition at line 160 of file Reaction.h.
References Reaction< M, N >::_rspecies, and A_reversible_B_numeric::N.
int ReactionBase::getProductOfReactants () const inline inherited
Computes the product of the copy number of all reactant RSpecies.
Can be used to quickly determine whether this ReactionBase should be allowed to activate - if one of the reactants has a copy number equal to zero, then zero is returned, indicating that this ReactionBase should not be (yet) activated.
Definition at line 180 of file ReactionBase.h.
References ReactionBase::getProductOfReactantsImpl().
Referenced by ReactionBase::activateReaction(), and RNodeNRM::getProductOfReactants().
template<unsigned short M, unsigned short N> virtual int Reaction< M, N >::getProductOfReactantsImpl () const inline override protected virtual
Implementation of getProductOfReactants()
Implements ReactionBase.
Definition at line 139 of file Reaction.h.
References Reaction< M, N >::_rspecies, and ReactionBase::getN().
Referenced by Reaction< M, N >::computePropensityImpl().
float ReactionBase::getRate () const inline inherited
Returns the rate associated with this ReactionBase.
Definition at line 131 of file ReactionBase.h.
References ReactionBase::_rate.
Referenced by main(), and Reaction< M, N >::printToStream().
int ReactionBase::getReactionID () inline inherited
Definition at line 140 of file ReactionBase.h.
References ReactionBase::_reactionID.
ReactionType ReactionBase::getReactionType () inline inherited
Get reaction type.
Definition at line 121 of file ReactionBase.h.
References ReactionBase::_reactionType.
RNode* ReactionBase::getRnode () const inline inherited
Returns a pointer to the RNode associated with this ReactionBase.
Definition at line 143 of file ReactionBase.h.
References ReactionBase::_rnode.
Composite * ReactionBase::getRoot () inherited
Get the root parent (i.e. follow the pointers of parentage until the root node in the Composition hieararchy)
Definition at line 29 of file ReactionBase.cpp.
References ReactionBase::getParent(), Component::getRoot(), and ReactionBase::hasParent().
bool ReactionBase::hasParent () const inline inherited
Returns true if this Reaction has a parent Composite object to which it belongs to.
Definition at line 171 of file ReactionBase.h.
References ReactionBase::_parent.
Referenced by ReactionBase::getRoot().
template<unsigned short M, unsigned short N> template<typename InputContainer > void Reaction< M, N >::initializeSpecies (const InputContainer & species) inline protected
An implementation method used by the constructor.
Definition at line 101 of file Reaction.h.
References ReactionBase::_dependents, ReactionBase::_isProtoCompartment, Reaction< M, N >::_rspecies, Reaction< M, N >::getAffectedReactions(), and A_reversible_B_numeric::N.
Referenced by Reaction< M, N >::Reaction().
template<unsigned short M, unsigned short N> virtual bool Reaction< M, N >::is_equal (const ReactionBase & other) const inline override protected virtual
Implementation of the operator==(...)
Implements ReactionBase.
Definition at line 127 of file Reaction.h.
References Reaction< M, N >::_rspecies, A_B_C_Cycle::A, A_B_C_Cycle::B, and RSpecies::getSpecies().
bool ReactionBase::isPassivated () const inline inherited
Return true if the ReactionBase is currently passivated.
Definition at line 198 of file ReactionBase.h.
Referenced by RNodeGillespie::isPassivated(), and RNodeNRM::isPassivated().
void ReactionBase::makeStep () inline inherited
Fire the ReactionBase - make a single step, where reactant RSpecies copy numbers are decreased by one, and the product RSpecies copy numbers are increased by one.
Note
This method does not send a ReactionBase event Signal. The latter is usually done from within a Gillespie-like algorithm.
Definition at line 266 of file ReactionBase.h.
References ReactionBase::makeStepImpl().
Referenced by main(), RNodeGillespie::makeStep(), ChemSimpleGillespieImpl::makeStep(), and RNodeNRM::makeStep().
template<unsigned short M, unsigned short N> virtual void Reaction< M, N >::makeStepImpl () inline override protected virtual
Implementation of makeStep()
Implements ReactionBase.
Definition at line 183 of file Reaction.h.
References Reaction< M, N >::_rspecies, and A_reversible_B_numeric::N.
template<> void Reaction< 1, 1 >::makeStepImpl () inline protected virtual
(Private) implementation of the makeStep() method to be elaborated in derived classes.
Implements ReactionBase.
Definition at line 259 of file Reaction.h.
template<unsigned short M, unsigned short N> Reaction& Reaction< M, N >::operator= (Reaction< M, N > & rb) delete
no assignment (including all derived classes)
void ReactionBase::passivateReaction () inline inherited
Usually is applied to ReactionBase objects with propensity of 0 (e.g.
when one of the copy numbers of reactants has dropped to 0. This method call notifies all other ReactionBase objects that may affect this ReactionBase to stop tracking this ReactionBase. Eventually, activateReaction() may be called to restart tracking, if the propensity stops being 0.
Definition at line 282 of file ReactionBase.h.
References ReactionBase::passivateReactionImpl().
Referenced by CCylinder::removeInternalReaction().
template<unsigned short M, unsigned short N> template void Reaction< M, N >::passivateReactionImpl () override protected virtual
Implementation of passivateReaction()
Implements ReactionBase.
Definition at line 47 of file Reaction.cpp.
References RSpecies::beginProductReactions(), RSpecies::beginReactantReactions(), RSpecies::endProductReactions(), and RSpecies::endReactantReactions().
void ReactionBase::printDependents () inherited
Print the ReactionBases that are affacted by this ReactionBase being fired.
Definition at line 64 of file ReactionBase.cpp.
References ReactionBase::_dependents.
template<unsigned short M, unsigned short N> virtual void Reaction< M, N >::printToStream (ostream & os) const inline override protected virtual
Print information about this reaction to ostream.
Implements ReactionBase.
Definition at line 198 of file Reaction.h.
References Reaction< M, N >::_rspecies, ReactionBase::computePropensity(), ReactionBase::getRate(), and A_reversible_B_numeric::N.
void ReactionBase::registerNewDependent (ReactionBase * r) inherited
Request that the ReactionBase *r adds this ReactionBase to its list of dependents which it affects.
Definition at line 36 of file ReactionBase.cpp.
References ReactionBase::_dependents.
template<unsigned short M, unsigned short N> virtual RSpecies** Reaction< M, N >::rspecies () inline override virtual
Returns a pointer to the first element of array<RSpecies*, M+N> The type of the pointer is RSpecies**.
In conjunction with getM() and getN(), this pointer can be used to iterate over RSpecies associated with this reaction.
Implements ReactionBase.
Definition at line 80 of file Reaction.h.
References Reaction< M, N >::_rspecies.
void ReactionBase::setParent (Composite * other) inline inherited
Set the parent Composite object pointer to which this Reaction belongs to.
Definition at line 168 of file ReactionBase.h.
References ReactionBase::_parent.
Referenced by CompartmentGrid::addBulk(), CompartmentGrid::addBulkReaction(), CompartmentGrid::addBulkReactionUnique(), Compartment::addDiffusionReaction(), Compartment::addDiffusionReactionUnique(), Compartment::addInternal(), Compartment::addInternalReaction(), and Compartment::addInternalReactionUnique().
void ReactionBase::setRate (float rate) inline inherited
Sets the ReactionBase rate to the parameter "rate".
Definition at line 124 of file ReactionBase.h.
References ReactionBase::_rate.
void ReactionBase::setReactionID (int ID) inline inherited
For cross filament reactions (SHOULD EVENTUALLY BE MOVED)
Set and get ID
Definition at line 139 of file ReactionBase.h.
References ReactionBase::_reactionID.
Referenced by LinkerBindingManager::addReaction(), and MotorBindingManager::addReaction().
void ReactionBase::setReactionType (ReactionType rxnType) inline inherited
Set reaction type.
Definition at line 118 of file ReactionBase.h.
References ReactionBase::_reactionType.
Referenced by PolyPlusEndManager::addReaction(), PolyMinusEndManager::addReaction(), DepolyPlusEndManager::addReaction(), DepolyMinusEndManager::addReaction(), BasicBindingManager::addReaction(), UnbindingManager::addReaction(), MotorWalkFManager::addReaction(), MotorWalkBManager::addReaction(), LinkerBindingManager::addReaction(), MotorBindingManager::addReaction(), and Compartment::generateDiffusionReactions().
void ReactionBase::setRnode (RNode * rhs) inline inherited
Sets the RNode pointer associated with this ReactionBase to rhs.
Usually is called only by the Gillespie-like algorithms.
Definition at line 128 of file ReactionBase.h.
References ReactionBase::_rnode.
Referenced by RNodeGillespie::RNodeGillespie(), RNodeNRM::RNodeNRM(), RNodeGillespie::~RNodeGillespie(), and RNodeNRM::~RNodeNRM().
unsigned short ReactionBase::size () const inline inherited
Returns the total number of RSpecies.
Definition at line 158 of file ReactionBase.h.
References ReactionBase::sizeImpl().
template<unsigned short M, unsigned short N> virtual unsigned short Reaction< M, N >::sizeImpl () const inline override protected virtual
Implementation of size()
Implements ReactionBase.
Definition at line 124 of file Reaction.h.
References A_reversible_B_numeric::N.
void ReactionBase::unregisterDependent (ReactionBase * r) inherited
Request that the ReactionBase *r removes this ReactionBase from its list of dependents which it affects.
This is usually requested when the ReactionBase propensity drops to zero (i.e. via passivateReactionBase()).
Definition at line 41 of file ReactionBase.cpp.
References ReactionBase::_dependents.
Member Data Documentation
vector<ReactionBase*> ReactionBase::_dependents protected inherited
Pointers to ReactionBase objects that depend on this ReactionBase being executed.
Definition at line 69 of file ReactionBase.h.
Referenced by ReactionBase::dependents(), Reaction< M, N >::initializeSpecies(), ReactionBase::printDependents(), ReactionBase::registerNewDependent(), and ReactionBase::unregisterDependent().
bool ReactionBase::_isProtoCompartment = false protected inherited
Definition at line 81 of file ReactionBase.h.
Referenced by Reaction< M, N >::initializeSpecies().
Composite* ReactionBase::_parent protected inherited
A pointer to a Composite object to which this Reaction belongs.
Definition at line 71 of file ReactionBase.h.
Referenced by ReactionBase::getParent(), ReactionBase::hasParent(), and ReactionBase::setParent().
float ReactionBase::_rate protected inherited
the rate for this ReactionBase
Definition at line 72 of file ReactionBase.h.
Referenced by Reaction< M, N >::computePropensityImpl(), ReactionBase::getRate(), and ReactionBase::setRate().
float ReactionBase::_rate_bare protected inherited
the bare rate for this ReactionBase (original rate)
Definition at line 73 of file ReactionBase.h.
Referenced by ReactionBase::getBareRate().
short ReactionBase::_reactionID = -1 protected inherited
Reaction is in proto compartment (Do not copy as a dependent, not in chemsim)
Unique id of this reaction
Definition at line 83 of file ReactionBase.h.
Referenced by Reaction< M, N >::cloneImpl(), ReactionBase::getReactionID(), and ReactionBase::setReactionID().
ReactionType ReactionBase::_reactionType protected inherited
Reaction type enumeration.
Definition at line 80 of file ReactionBase.h.
Referenced by Reaction< M, N >::cloneImpl(), ReactionBase::getReactionType(), and ReactionBase::setReactionType().
RNode* ReactionBase::_rnode protected inherited
A pointer to an RNode object which is used to implement a Gillespie-like algorithm (e.g. NRM)
Definition at line 70 of file ReactionBase.h.
Referenced by ReactionBase::getRnode(), and ReactionBase::setRnode().
template<unsigned short M, unsigned short N> array<RSpecies*, M+N> Reaction< M, N >::_rspecies private
An array of RSpecies objects (reactants followed by products)
Definition at line 33 of file Reaction.h.
Referenced by Reaction< M, N >::containsSpeciesImpl(), Reaction< M, N >::getAffectedReactions(), Reaction< M, N >::getProductOfProductsImpl(), Reaction< M, N >::getProductOfReactantsImpl(), Reaction< M, N >::initializeSpecies(), Reaction< M, N >::is_equal(), Reaction< M, N >::makeStepImpl(), Reaction< M, N >::printToStream(), and Reaction< M, N >::rspecies().
The documentation for this class was generated from the following files:
M3SYM/Structure/Reaction.h
M3SYM/Structure/Reaction.cpp