M3Sym: CylinderNeighborList Class Reference
CylinderNeighborList Class Reference
An implementation of NeighborList for Cylinder-Cylinder interactions.
#include <NeighborList.h>
Public Member Functions
CylinderNeighborList (float rMax=0.0, float rMin=0.0, bool crossFilamentOnly=false)
virtual void addNeighbor (Neighbor *n)
Add neighbor.
virtual void updateNeighbors (Neighbor *n)
U pdate a neighbor.
vector< Cylinder * > getNeighbors (Cylinder *cylinder)
Get all cylinder neighbors.
virtual void removeNeighbor (Neighbor *n)
Remove a neighbor if possible.
virtual void reset ()
Re-initialize the neighborlist.
Protected Attributes
unordered_map< Neighbor
*, vector< Neighbor * > > _list
The neighbors list, as a hash map.
float _rMax
max distance cutoff
float _rMin
min distance cutoff
Private Attributes
bool _crossFilamentOnly
Whether to include cylinders in same filament.
Detailed Description
An implementation of NeighborList for Cylinder-Cylinder interactions.
Definition at line 77 of file NeighborList.h.
Constructor & Destructor Documentation
CylinderNeighborList::CylinderNeighborList (float rMax = 0.0, float rMin = 0.0, bool crossFilamentOnly = false) inline
Definition at line 83 of file NeighborList.h.
Member Function Documentation
void CylinderNeighborList::addNeighbor (Neighbor * n) virtual
Add neighbor.
return if not a cylinder!
update neighbors
Implements NeighborList.
Definition at line 25 of file NeighborList.cpp.
vector< Cylinder * > CylinderNeighborList::getNeighbors (Cylinder * cylinder)
Get all cylinder neighbors.
Definition at line 74 of file NeighborList.cpp.
virtual void NeighborList::removeNeighbor (Neighbor * n) inline virtual inherited
Remove a neighbor if possible.
Definition at line 56 of file NeighborList.h.
References NeighborList::_list.
virtual void NeighborList::reset () inline virtual inherited
Re-initialize the neighborlist.
clear vector of neighbors
Definition at line 59 of file NeighborList.h.
References NeighborList::_list, and NeighborList::updateNeighbors().
void CylinderNeighborList::updateNeighbors (Neighbor * n) virtual
U pdate a neighbor.
clear existing
Find surrounding compartments (For now its conservative, change soon)
Dont add if ID is more than cylinder
Don't add if on the same filament
if cross filament only interaction, dont add
if not cross filament, check if not neighboring
Dont add if not within range
If we got through all of this, add it!
Implements NeighborList.
Definition at line 35 of file NeighborList.cpp.
References Cylinder::coordinate, GController::findCompartments(), SystemParameters::Geometry(), Cylinder::getCompartment(), Cylinder::getFilament(), Cylinder::getID(), Cylinder::getPositionFilament(), GeometryParameters::largestCompartmentSide, and mathfunc::TwoPointDistance().
Member Data Documentation
bool CylinderNeighborList::_crossFilamentOnly private
Whether to include cylinders in same filament.
Definition at line 80 of file NeighborList.h.
unordered_map<Neighbor*, vector<Neighbor*> > NeighborList::_list protected inherited
The neighbors list, as a hash map.
Definition at line 41 of file NeighborList.h.
Referenced by NeighborList::removeNeighbor(), and NeighborList::reset().
float NeighborList::_rMax protected inherited
max distance cutoff
Definition at line 42 of file NeighborList.h.
float NeighborList::_rMin protected inherited
min distance cutoff
Definition at line 43 of file NeighborList.h.
The documentation for this class was generated from the following files:
M3SYM/Structure/NeighborList.h
M3SYM/Structure/NeighborList.cpp