MEDYAN: FilamentBendingCosine Class Reference
FilamentBendingCosine Class Reference
A cosine potential used by the FilamentBending template.
#include <FilamentBendingCosine.h>
Public Member Functions
double energy (Bead *, Bead *, Bead *, double, double)
double energy (Bead *, Bead *, Bead *, double, double, double)
void forces (Bead *, Bead *, Bead *, double, double)
void forcesAux (Bead *, Bead *, Bead *, double, double)
Detailed Description
A cosine potential used by the FilamentBending template.
Definition at line 23 of file FilamentBendingCosine.h.
Member Function Documentation
energy() [1/2]
double FilamentBendingCosine::energy (Bead * b1, Bead * b2, Bead * b3, double kBend, double eqTheta)
Definition at line 21 of file FilamentBendingCosine.cpp.
References Bead::coordinate, safeacos(), and mathfunc::scalarProduct().
energy() [2/2]
double FilamentBendingCosine::energy (Bead * b1, Bead * b2, Bead * b3, double kBend, double eqTheta, double d)
Definition at line 39 of file FilamentBendingCosine.cpp.
References Bead::coordinate, Bead::force, safeacos(), and mathfunc::scalarProductStretched().
forces()
void FilamentBendingCosine::forces (Bead * b1, Bead * b2, Bead * b3, double kBend, double eqTheta)
Definition at line 63 of file FilamentBendingCosine.cpp.
References areEqual(), Bead::coordinate, Bead::force, safeacos(), and mathfunc::scalarProduct().
forcesAux()
void FilamentBendingCosine::forcesAux (Bead * b1, Bead * b2, Bead * b3, double kBend, double eqTheta)
Definition at line 123 of file FilamentBendingCosine.cpp.
References areEqual(), Bead::coordinate, Bead::forceAux, safeacos(), and mathfunc::scalarProduct().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Filament/FilamentBendingCosine.h
src/Mechanics/ForceField/Filament/FilamentBendingCosine.cpp