M3Sym: DepolyPlusEndManager Class Reference
DepolyPlusEndManager Class Reference
Manager for depolymerization at plus end.
#include <ReactionManager.h>
Public Member Functions
DepolyPlusEndManager (vector< tuple< int, SpeciesType >> reactants, vector< tuple< int, SpeciesType >> products, float rate)
~DepolyPlusEndManager ()
virtual void addReaction (CCylinder *cc)
Add this chemical reaction to a CCylinder. Adds all extension and retraction callbacks needed.
virtual void addReaction (CCylinder *cc1, CCylinder *cc2)
Add this chemical reaction cross two CCylinders.
Protected Attributes
vector< tuple< int, SpeciesType > > _reactants
Species identifier vectors.
vector< tuple< int, SpeciesType > > _products
Products in this reaction.
float _rate
Rate of reaction.
Static Protected Attributes
static SubSystem * _ps = 0
A subsystem pointer to initialize and call chemical callbacks.
Detailed Description
Manager for depolymerization at plus end.
Definition at line 100 of file ReactionManager.h.
Constructor & Destructor Documentation
DepolyPlusEndManager::DepolyPlusEndManager (vector< tuple< int, SpeciesType >> reactants, vector< tuple< int, SpeciesType >> products, float rate) inline
Definition at line 103 of file ReactionManager.h.
DepolyPlusEndManager::~DepolyPlusEndManager () inline
Definition at line 106 of file ReactionManager.h.
Member Function Documentation
void DepolyPlusEndManager::addReaction (CCylinder * cc) virtual
Add this chemical reaction to a CCylinder. Adds all extension and retraction callbacks needed.
Implements InternalFilamentRxnManager.
Definition at line 323 of file ReactionManager.cpp.
References CCylinder::addInternalReaction(), BULK, DEPOLYMERIZATION, DIFFUSING, Compartment::findSpeciesByMolecule(), CCylinder::getCMonomer(), CCylinder::getCompartment(), CCylinder::getCylinder(), Cylinder::getFilament(), CCylinder::getSize(), CompartmentGrid::instance(), ReactionBase::setReactionType(), CMonomer::speciesBound(), CMonomer::speciesFilament(), and CMonomer::speciesPlusEnd().
void DepolyPlusEndManager::addReaction (CCylinder * cc1, CCylinder * cc2) virtual
Add this chemical reaction cross two CCylinders.
Note
assumes cc1 and cc2 are in order, that is, cc2 is the next cylinder after cc1
Implements InternalFilamentRxnManager.
Definition at line 474 of file ReactionManager.cpp.
References CCylinder::addCrossCylinderReaction(), BULK, DEPOLYMERIZATION, DIFFUSING, Compartment::findSpeciesByMolecule(), CCylinder::getCMonomer(), CCylinder::getCompartment(), CCylinder::getCylinder(), Cylinder::getFilament(), CCylinder::getSize(), CompartmentGrid::instance(), ReactionBase::setReactionType(), CMonomer::speciesBound(), CMonomer::speciesFilament(), and CMonomer::speciesPlusEnd().
Member Data Documentation
vector<tuple<int,SpeciesType> > InternalFilamentRxnManager::_products protected inherited
Products in this reaction.
Definition at line 54 of file ReactionManager.h.
SubSystem * InternalFilamentRxnManager::_ps = 0 static protected inherited
A subsystem pointer to initialize and call chemical callbacks.
Definition at line 50 of file ReactionManager.h.
Referenced by SimpleManagerImpl::initialize().
float InternalFilamentRxnManager::_rate protected inherited
Rate of reaction.
Definition at line 56 of file ReactionManager.h.
vector<tuple<int,SpeciesType> > InternalFilamentRxnManager::_reactants protected inherited
Species identifier vectors.
Reactants in this reaction
Definition at line 53 of file ReactionManager.h.
The documentation for this class was generated from the following files:
M3SYM/Chemistry/ReactionManager.h
M3SYM/Chemistry/ReactionManager.cpp