MEDYAN: SpeciesMotor Class Reference
SpeciesMotor Class Reference
Used for species that can be bound to a Filament.
#include <Species.h>
Public Member Functions
SpeciesMotor ()
Default constructor.
SpeciesMotor (const string &name, species_copy_t n=0, species_copy_t ulim=1)
The main constructor.
SpeciesMotor (const SpeciesMotor &rhs)
Copy constructor.
SpeciesMotor (SpeciesMotor &&rhs) noexcept
Move constructor.
SpeciesMotor & operator= (const SpeciesMotor &rhs)
Regular Assignment.
SpeciesMotor & operator= (SpeciesMotor &&rhs)
Move assignment.
virtual SpeciesMotor * clone ()
virtual string getFullName () const
Return the full name of this Species in a string format (e.g. "Myosin{Motor}".
~SpeciesMotor () noexcept
Default destructor.
void setCBound (CBound *cBound)
Setter and getter for CBound.
CBound * getCBound ()
void removeCBound ()
remove cBound ptr
Composite * getParent ()
void setParent (Composite *other)
bool hasParent () const
Composite * getRoot ()
RSpecies & getRSpecies ()
Return a reference to RSpecies.
const RSpecies & getRSpecies () const
Return a constant reference to RSpecies.
RSpecies * getRSpeciesPtr ()
Return a reference ptr to RSpecies.
void setN (species_copy_t n)
Sets the copy number for this Species.
species_copy_t getN () const
Return the current copy number of this Species.
string getName () const
Return this Species' name.
int getMolecule () const
Return the molecule index associated with this Species' (as int)
virtual size_t countSpecies () const
void updateReactantPropensities ()
Update the reaction propensities associated with this species.
void activateReactantReactions ()
Activate the reactions associated with this species.
void passivateReactantReactions ()
Passivate the reactions associated with this species.
virtual void up ()
Change copy number.
virtual void down ()
Change copy number.
Protected Attributes
CBound * _cBound = nullptr
CBound object.
int _molecule
unique id identifying the molecule (e.g.
RSpecies * _rspecies
pointer to RSpecies; Species is responsible for creating and destroying RSpecies
Composite * _parent
pointer to the "container" object holding this Species (could be a nullptr)
Detailed Description
Used for species that can be bound to a Filament.
These species can not move cross-compartment. Contains a pointer to a CMotorGhost object that this represents.
Definition at line 662 of file Species.h.
Constructor & Destructor Documentation
SpeciesMotor() [1/4]
SpeciesMotor::SpeciesMotor () inline
Default constructor.
Definition at line 666 of file Species.h.
SpeciesMotor() [2/4]
SpeciesMotor::SpeciesMotor (const string & name, species_copy_t n = 0, species_copy_t ulim = 1) inline
The main constructor.
Parameters
name - Example, "G-Actin" or "Arp2/3"
n - copy number
Definition at line 671 of file Species.h.
SpeciesMotor() [3/4]
SpeciesMotor::SpeciesMotor (const SpeciesMotor & rhs) inline
Copy constructor.
Definition at line 675 of file Species.h.
SpeciesMotor() [4/4]
SpeciesMotor::SpeciesMotor (SpeciesMotor && rhs) inline noexcept
Move constructor.
Definition at line 678 of file Species.h.
~SpeciesMotor()
SpeciesMotor::~SpeciesMotor () inline noexcept
Default destructor.
Definition at line 702 of file Species.h.
Member Function Documentation
activateReactantReactions()
void Species::activateReactantReactions () inherited
Activate the reactions associated with this species.
i.e. if passivated, will activate accordingly and update propensities and all dependents.
Definition at line 47 of file Species.cpp.
References Species::_rspecies, and RSpecies::reactantReactions().
Referenced by ChemManager::updateCopyNumbers().
clone()
virtual SpeciesMotor* SpeciesMotor::clone () inline virtual
Reimplemented from SpeciesBound.
Definition at line 694 of file Species.h.
countSpecies()
virtual size_t Species::countSpecies () const inline virtual inherited
Definition at line 393 of file Species.h.
References RSpecies::up().
down()
virtual void Species::down () inline virtual inherited
Change copy number.
Definition at line 398 of file Species.h.
References RSpecies::down().
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), ChemManager::initializeCCylinder(), Filament::sever(), FilamentBindingManager::updateBindingReaction(), ChemManager::updateCopyNumbers(), and BranchingPoint::~BranchingPoint().
getCBound()
CBound* SpeciesBound::getCBound () inline inherited
Definition at line 606 of file Species.h.
Referenced by CMonomer::CMonomer().
getFullName()
virtual string SpeciesMotor::getFullName () const inline virtual
Return the full name of this Species in a string format (e.g. "Myosin{Motor}".
Reimplemented from SpeciesBound.
Definition at line 699 of file Species.h.
getMolecule()
int Species::getMolecule () const inline inherited
Return the molecule index associated with this Species' (as int)
Definition at line 334 of file Species.h.
Referenced by Compartment::addSpeciesBound(), Compartment::addSpeciesBrancher(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPairBinding(), Compartment::addSpeciesPlusEnd(), Compartment::addSpeciesSingleBinding(), Compartment::addSpeciesUnique(), and Compartment::setDiffusionRate().
getN()
species_copy_t Species::getN () const inline inherited
Return the current copy number of this Species.
Definition at line 323 of file Species.h.
References RSpecies::getN().
Referenced by CMonomer::activeSpeciesBrancher(), CMonomer::activeSpeciesFilament(), CMonomer::activeSpeciesLinker(), CMonomer::activeSpeciesMinusEnd(), CMonomer::activeSpeciesMotor(), CMonomer::activeSpeciesPlusEnd(), BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CMonomer::isConsistent(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), MotorBindingManager::MotorBindingManager(), operator<<(), Species::operator=(), CMonomer::print(), BranchingManager::removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), MotorBindingManager::removePossibleBindings(), Species::Species(), Compartment::transferSpecies(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), MotorBindingManager::updateAllPossibleBindings(), FilamentBindingManager::updateBindingReaction(), and ChemManager::updateCopyNumbers().
getName()
string Species::getName () const inline inherited
Return this Species' name.
Definition at line 331 of file Species.h.
References SpeciesNamesDB::intToString().
Referenced by BranchingManager::BranchingManager(), CMonomer::isConsistent(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), CMonomer::print(), and BranchingPoint::~BranchingPoint().
getParent()
Composite* Species::getParent () inline inherited
Definition at line 299 of file Species.h.
Referenced by Species::getRoot().
getRoot()
Composite * Species::getRoot () inherited
Definition at line 29 of file Species.cpp.
References Species::getParent(), Component::getRoot(), and Species::hasParent().
getRSpecies() [1/2]
RSpecies& Species::getRSpecies () inline inherited
Return a reference to RSpecies.
Notice that value copying won't be allowed because RSpecies is not copyable.
Definition at line 309 of file Species.h.
Referenced by ChemManager::genSpecies(), and MotorGhost::updateReactionRates().
getRSpecies() [2/2]
const RSpecies& Species::getRSpecies () const inline inherited
Return a constant reference to RSpecies.
Definition at line 315 of file Species.h.
getRSpeciesPtr()
RSpecies* Species::getRSpeciesPtr () inline inherited
Return a reference ptr to RSpecies.
Definition at line 312 of file Species.h.
hasParent()
bool Species::hasParent () const inline inherited
Definition at line 303 of file Species.h.
Referenced by Species::getRoot().
operator=() [1/2]
SpeciesMotor& SpeciesMotor::operator= (const SpeciesMotor & rhs) inline
Regular Assignment.
Definition at line 682 of file Species.h.
References SpeciesBound::operator=().
operator=() [2/2]
SpeciesMotor& SpeciesMotor::operator= (SpeciesMotor && rhs) inline
Move assignment.
Definition at line 688 of file Species.h.
References SpeciesBound::operator=().
passivateReactantReactions()
void Species::passivateReactantReactions () inherited
Passivate the reactions associated with this species.
i.e. if activated, will passivate accordingly and update propensities and all dependents.
Definition at line 54 of file Species.cpp.
References SpeciesNamesDB::_map_string_int, SpeciesNamesDB::_num, Species::_rspecies, SpeciesNamesDB::_vec_int_string, and RSpecies::reactantReactions().
Referenced by ChemManager::updateCopyNumbers().
removeCBound()
void SpeciesBound::removeCBound () inline inherited
remove cBound ptr
Definition at line 609 of file Species.h.
Referenced by CBound::setFirstSpecies(), CBound::setSecondSpecies(), and CBound::~CBound().
setCBound()
void SpeciesBound::setCBound (CBound * cBound) inline inherited
Setter and getter for CBound.
Definition at line 605 of file Species.h.
Referenced by CBound::setFirstSpecies(), and CBound::setSecondSpecies().
setN()
void Species::setN (species_copy_t n) inline inherited
Sets the copy number for this Species.
Parameters
n should be a non-negative number, but no checking is done in run time
Note
The operation does not emit any signals about the copy number change.
Definition at line 320 of file Species.h.
References RSpecies::setN().
Referenced by ChemManager::updateCopyNumbers().
setParent()
void Species::setParent (Composite * other) inline inherited
Definition at line 301 of file Species.h.
Referenced by Compartment::addSpeciesBound(), Compartment::addSpeciesBrancher(), Compartment::addSpeciesDiffusing(), Compartment::addSpeciesFilament(), Compartment::addSpeciesLinker(), Compartment::addSpeciesMinusEnd(), Compartment::addSpeciesMotor(), Compartment::addSpeciesPairBinding(), Compartment::addSpeciesPlusEnd(), Compartment::addSpeciesSingleBinding(), and Compartment::addSpeciesUnique().
up()
virtual void Species::up () inline virtual inherited
Change copy number.
Definition at line 397 of file Species.h.
Referenced by CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), ChemManager::initializeCCylinder(), Filament::nucleate(), Filament::sever(), FilamentBindingManager::updateBindingReaction(), ChemManager::updateCopyNumbers(), and BranchingPoint::~BranchingPoint().
updateReactantPropensities()
void Species::updateReactantPropensities () inherited
Update the reaction propensities associated with this species.
This will not activate the reactions if currently passivated, or update any dependents asosciated with these reactions.
Definition at line 41 of file Species.cpp.
References Species::_rspecies, and RSpecies::reactantReactions().
Referenced by ChemManager::updateCopyNumbers(), and BranchingPoint::~BranchingPoint().
Member Data Documentation
_cBound
CBound* SpeciesBound::_cBound = nullptr protected inherited
CBound object.
Definition at line 562 of file Species.h.
_molecule
int Species::_molecule protected inherited
unique id identifying the molecule (e.g.
the integer id corresponding to "Arp2/3")
Definition at line 174 of file Species.h.
Referenced by Species::operator=().
_parent
Composite* Species::_parent protected inherited
pointer to the "container" object holding this Species (could be a nullptr)
Definition at line 178 of file Species.h.
_rspecies
RSpecies* Species::_rspecies protected inherited
pointer to RSpecies; Species is responsible for creating and destroying RSpecies
Definition at line 176 of file Species.h.
Referenced by Species::activateReactantReactions(), Species::operator=(), Species::passivateReactantReactions(), Species::Species(), and Species::updateReactantPropensities().
The documentation for this class was generated from the following file:
src/Chemistry/Species.h