MEDYAN: ForceFieldManager Class Reference
ForceFieldManager Class Reference
A class to store and iterate over all ForceFields.
#include <ForceFieldManager.h>
Public Member Functions
double computeEnergy (double d, bool verbose=false)
Compute the energy using all available force fields.
void computeForces ()
Compute the forces of all force fields.
void computeForcesAux ()
Compute the forcesAux of all force fields.
void computeForcesAuxP ()
Compute forcesAuxP of all force fields.
void computeLoadForces ()
Compute the load forces on the beads.
void resetForces ()
Reset the forces of all objects.
void resetForcesAux ()
Reset the forcesAux of all objects.
Public Attributes
vector< ForceField * > _forceFields
All forcefields in the system.
Detailed Description
A class to store and iterate over all ForceFields.
The ForceFieldManager is used to store all ForceFields initialized by the system, as well as iterate over these potentials and calculate total forces and energies. This class contains functions for the said calculations.
Definition at line 30 of file ForceFieldManager.h.
Member Function Documentation
computeEnergy()
double ForceFieldManager::computeEnergy (double d, bool verbose = false)
Compute the energy using all available force fields.
Returns
Returns infinity if there was a problem with a ForceField energy calculation, such that beads will not be moved to this problematic configuration.
Parameters
print - prints detailed info about energies
Definition at line 16 of file ForceFieldManager.cpp.
References _forceFields.
Referenced by CGMethod::backtrackingLineSearch(), SteepestDescent::minimize(), FletcherRieves::minimize(), PolakRibiere::minimize(), and CGMethod::safeBacktrackingLineSearch().
computeForces()
void ForceFieldManager::computeForces ()
Compute the forces of all force fields.
Definition at line 50 of file ForceFieldManager.cpp.
References _forceFields, Bead::getBeads(), and resetForces().
Referenced by FletcherRieves::minimize(), SteepestDescent::minimize(), and PolakRibiere::minimize().
computeForcesAux()
void ForceFieldManager::computeForcesAux ()
Compute the forcesAux of all force fields.
Definition at line 63 of file ForceFieldManager.cpp.
References _forceFields, and resetForcesAux().
Referenced by FletcherRieves::minimize(), SteepestDescent::minimize(), and PolakRibiere::minimize().
computeForcesAuxP()
void ForceFieldManager::computeForcesAuxP ()
Compute forcesAuxP of all force fields.
Definition at line 73 of file ForceFieldManager.cpp.
References Bead::getBeads().
Referenced by PolakRibiere::minimize().
computeLoadForces()
void ForceFieldManager::computeLoadForces ()
Compute the load forces on the beads.
This does not update the force (xyz) vector contained by Bead, but updates the loadForce vector which contains precalculated load values based on the bead's directionality of growth in a filament.
Definition at line 80 of file ForceFieldManager.cpp.
References _forceFields, and Bead::getBeads().
Referenced by FletcherRieves::minimize(), SteepestDescent::minimize(), and PolakRibiere::minimize().
resetForces()
void ForceFieldManager::resetForces ()
Reset the forces of all objects.
Definition at line 93 of file ForceFieldManager.cpp.
References Bead::getBeads().
Referenced by computeForces().
resetForcesAux()
void ForceFieldManager::resetForcesAux ()
Reset the forcesAux of all objects.
Definition at line 102 of file ForceFieldManager.cpp.
References Bead::getBeads().
Referenced by computeForcesAux().
Member Data Documentation
_forceFields
vector<ForceField*> ForceFieldManager::_forceFields
All forcefields in the system.
Definition at line 33 of file ForceFieldManager.h.
Referenced by computeEnergy(), computeForces(), computeForcesAux(), computeLoadForces(), and MController::initializeFF().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/ForceFieldManager.h
src/Mechanics/ForceField/ForceFieldManager.cpp