MEDYAN: BubbleCylinderRepulsion< BRepulsionInteractionType > Class Template Reference
BubbleCylinderRepulsion< BRepulsionInteractionType > Class Template Reference
Represents a repulsive interaction between a Bubble and Cylinder.
#include <BubbleCylinderRepulsion.h>
Public Member Functions
BubbleCylinderRepulsion ()
Constructor.
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual void computeLoadForces ()
Compute the load forces on beads from this interaction.
virtual NeighborList * getNeighborList ()
Get the neighbor list for this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
Bubble * _bubbleCulprit = nullptr
In the case of an error.
Component * _otherCulprit = nullptr
In the case of an error.
Private Attributes
BRepulsionInteractionType _FFType
BubbleCylinderNL * _neighborList
Neighbor list of Bubble-Cylinder.
Detailed Description
template<class BRepulsionInteractionType>
class BubbleCylinderRepulsion< BRepulsionInteractionType >
Represents a repulsive interaction between a Bubble and Cylinder.
Definition at line 31 of file BubbleCylinderRepulsion.h.
Constructor & Destructor Documentation
BubbleCylinderRepulsion()
template<class BRepulsionInteractionType > BubbleCylinderRepulsion< BRepulsionInteractionType >::BubbleCylinderRepulsion () inline
Constructor.
Definition at line 39 of file BubbleCylinderRepulsion.h.
References BubbleCylinderRepulsion< BRepulsionInteractionType >::computeEnergy(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeForces(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), and SysParams::Mechanics().
Member Function Documentation
computeEnergy()
template<class BRepulsionInteractionType > template double BubbleCylinderRepulsion< BRepulsionInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BubbleInteractions.
Definition at line 28 of file BubbleCylinderRepulsion.cpp.
References Bubble::getBubbles().
Referenced by BubbleCylinderRepulsion< BRepulsionInteractionType >::BubbleCylinderRepulsion(), and BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces().
computeForces()
template<class BRepulsionInteractionType > template void BubbleCylinderRepulsion< BRepulsionInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements BubbleInteractions.
Definition at line 86 of file BubbleCylinderRepulsion.cpp.
References Bubble::getBubbles().
Referenced by BubbleCylinderRepulsion< BRepulsionInteractionType >::BubbleCylinderRepulsion(), and BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces().
computeForcesAux()
template<class BRepulsionInteractionType > template void BubbleCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements BubbleInteractions.
Definition at line 126 of file BubbleCylinderRepulsion.cpp.
References Bubble::getBubbles().
Referenced by BubbleCylinderRepulsion< BRepulsionInteractionType >::BubbleCylinderRepulsion(), and BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces().
computeLoadForces()
template<class BRepulsionInteractionType > template void BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces () virtual
Compute the load forces on beads from this interaction.
this normal is in the direction of polymerization
this normal is in the direction of polymerization
Implements BubbleInteractions.
Definition at line 165 of file BubbleCylinderRepulsion.cpp.
References BubbleCylinderRepulsion< BRepulsionInteractionType >::computeEnergy(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeForces(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeForcesAux(), Bead::coordinate, GeoParams::cylinderNumMon, SysParams::Geometry(), Bubble::getBubbles(), Bead::getType(), Bead::lfim, Bead::lfip, Bead::loadForcesM, Bead::loadForcesP, GeoParams::monomerSize, mathfunc::normalizedVector(), and mathfunc::twoPointDirection().
Referenced by BubbleCylinderRepulsion< BRepulsionInteractionType >::BubbleCylinderRepulsion().
getName()
template<class BRepulsionInteractionType > virtual const string BubbleCylinderRepulsion< BRepulsionInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BubbleInteractions.
Definition at line 53 of file BubbleCylinderRepulsion.h.
getNeighborList()
template<class BRepulsionInteractionType > virtual NeighborList* BubbleCylinderRepulsion< BRepulsionInteractionType >::getNeighborList () inline virtual
Get the neighbor list for this interaction.
Implements BubbleInteractions.
Definition at line 51 of file BubbleCylinderRepulsion.h.
References BubbleCylinderRepulsion< BRepulsionInteractionType >::_neighborList.
Member Data Documentation
_bubbleCulprit
Bubble* BubbleInteractions::_bubbleCulprit = nullptr protected inherited
In the case of an error.
Definition at line 32 of file BubbleInteractions.h.
Referenced by BubbleFF::whoIsCulprit().
_FFType
template<class BRepulsionInteractionType > BRepulsionInteractionType BubbleCylinderRepulsion< BRepulsionInteractionType >::_FFType private
Definition at line 34 of file BubbleCylinderRepulsion.h.
_neighborList
template<class BRepulsionInteractionType > BubbleCylinderNL* BubbleCylinderRepulsion< BRepulsionInteractionType >::_neighborList private
Neighbor list of Bubble-Cylinder.
Definition at line 35 of file BubbleCylinderRepulsion.h.
Referenced by BubbleCylinderRepulsion< BRepulsionInteractionType >::getNeighborList().
_otherCulprit
Component* BubbleInteractions::_otherCulprit = nullptr protected inherited
In the case of an error.
Definition at line 33 of file BubbleInteractions.h.
Referenced by BubbleFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Bubble/BubbleCylinderRepulsion.h
src/Mechanics/ForceField/Bubble/BubbleCylinderRepulsion.cpp