MEDYAN: Component Class Reference
Component Class Reference abstract
The base class for the Composite pattern hieararchy.
#include <Component.h>
Public Member Functions
Component ()
Default Constructor; Parent is assigned to nullptr.
virtual ~Component () noexcept
Virtual Destructor.
virtual bool apply (Visitor &v)
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
virtual bool apply (SpeciesVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply (ReactionVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual size_t numberOfChildren () const
Returns the number of children of this node.
virtual bool isComposite () const
Returns true if this node is a Composite node.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
virtual size_t numberOfSpecies () const
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t numberOfReactions () const
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual string getFullName () const
Return a string indicating the full name of this node (presumably used mainly for debugging)
virtual size_t countDescendents () const
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const
Return the number of Species contained under this node's hieararchy.
virtual size_t countReactions () const
Return the number of ReactionBase objects contained under this node's hieararchy.
virtual void printSelf ()=0
Prints information about this node. Useful for debugging.
virtual int getType ()=0
Return the type of this element as an integer index.
Private Attributes
Composite * _parent
The parent of this object.
Detailed Description
The base class for the Composite pattern hieararchy.
The Composite pattern allows building of complex hieararchical objects, with convenient methods for applying a function to all nodes (i.e. the Visitor pattern). Each node in the hieararchy may have a parent and may contain several children nodes. A class that is derived directly from Component and not from Composite, cannot contain children, i.e. it is a leaf node.
Note
Component objects may contain Species and ReactionBase collections, however, this is treated seperately from the Composite pattern (i.e. separate methods exist for the corresponding access to elements, changes, etc.)
Definition at line 37 of file Component.h.
Constructor & Destructor Documentation
Component()
Component::Component () inline
Default Constructor; Parent is assigned to nullptr.
Definition at line 44 of file Component.h.
~Component()
virtual Component::~Component () inline virtual noexcept
Virtual Destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 51 of file Component.h.
References apply().
Member Function Documentation
apply() [1/3]
bool Component::apply (Visitor & v) virtual
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
However, the ConditionalVisitor allows the visit() function to be applied only selectively to nodes that conform to specific criteria.
Reimplemented in Composite.
Definition at line 26 of file Component.cpp.
References Visitor::visit().
Referenced by ~Component().
apply() [2/3]
virtual bool Component::apply (SpeciesVisitor & v) inline virtual
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented in Composite.
Definition at line 61 of file Component.h.
References apply_impl().
apply() [3/3]
virtual bool Component::apply (ReactionVisitor & v) inline virtual
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented in Composite.
Definition at line 69 of file Component.h.
References apply_impl().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
countDescendents()
virtual size_t Component::countDescendents () const inline virtual
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 118 of file Component.h.
countReactions()
virtual size_t Component::countReactions () const inline virtual
Return the number of ReactionBase objects contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 126 of file Component.h.
References getType(), and printSelf().
countSpecies()
virtual size_t Component::countSpecies () const inline virtual
Return the number of Species contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 122 of file Component.h.
Referenced by Linker::getLifetimes(), MotorGhost::getWalkLengths(), BranchingPoint::numBranchingPoints(), and Chemistry::print().
getFullName()
virtual string Component::getFullName () const inline virtual
Return a string indicating the full name of this node (presumably used mainly for debugging)
Reimplemented in Compartment, CompartmentGrid, and Composite.
Definition at line 114 of file Component.h.
getParent()
Composite* Component::getParent () inline
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References _parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and BranchingPoint::~BranchingPoint().
getRoot()
Composite * Component::getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References getParent(), getRoot(), and isRoot().
Referenced by getRoot(), ReactionBase::getRoot(), Species::getRoot(), and isRoot().
getType()
virtual int Component::getType () pure virtual
Return the type of this element as an integer index.
Implemented in Compartment, Filament, CompartmentGrid, MotorGhost, Bead, BoundaryElement, Linker, Cylinder, BranchingPoint, MTOC, and Bubble.
Referenced by countReactions(), and Bead::getType().
isComposite()
virtual bool Component::isComposite () const inline virtual
Returns true if this node is a Composite node.
Reimplemented in Composite.
Definition at line 95 of file Component.h.
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References getRoot().
Referenced by getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
numberOfChildren()
virtual size_t Component::numberOfChildren () const inline virtual
Returns the number of children of this node.
Note
Species and ReactionBase objects are not counted.
Reimplemented in Composite.
Definition at line 92 of file Component.h.
numberOfReactions()
virtual size_t Component::numberOfReactions () const inline virtual
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 110 of file Component.h.
numberOfSpecies()
virtual size_t Component::numberOfSpecies () const inline virtual
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 106 of file Component.h.
printSelf()
virtual void Component::printSelf () pure virtual
Prints information about this node. Useful for debugging.
Implemented in Compartment, Filament, MotorGhost, Cylinder, Linker, Bead, BranchingPoint, BoundaryElement, CompartmentGrid, Bubble, and MTOC.
Referenced by Bead::Bead(), countReactions(), Bead::updatePosition(), BubbleFF::whoIsCulprit(), and BoundaryFF::whoIsCulprit().
setParent()
void Component::setParent (Composite * other) inline
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
Member Data Documentation
_parent
Composite* Component::_parent private
The parent of this object.
May be a nullptr if this object has no parent.
Definition at line 39 of file Component.h.
Referenced by getParent().
The documentation for this class was generated from the following files:
src/Component.h
src/Component.cpp