MEDYAN: CCylinder Class Reference
CCylinder Class Reference
Holds all CMonomers and Reactions associated with it.
#include <CCylinder.h>
Public Member Functions
CCylinder (Compartment *C, Cylinder *c)
Default constructor, sets compartment and cylinder.
CCylinder (const CCylinder &rhs, Compartment *c)
Copy constructor.
CCylinder & operator= (CCylinder &rhs)=delete
Assignment is not allowed.
~CCylinder ()
Default destructor, explicitly removes CMonomers(including their species, rxns) Removes all reactions associated with this CCylinder, including ones owned by this as well as other CCylinders.
virtual CCylinder * clone (Compartment *c)
Clone, calls copy constructor.
Compartment * getCompartment ()
Get compartment.
void setCylinder (Cylinder *c)
Set parent.
Cylinder * getCylinder ()
Get parent.
void addCMonomer (CMonomer *monomer)
Add a monomer.
CMonomer * getCMonomer (int index)
Get monomer at an index.
const unordered_set< ReactionBase * > & getInternalReactions ()
Get list of reactions associated.
const unordered_set< CCylinder * > & getReactingCylinders ()
Get list of reacting cylinders associated.
map< CCylinder *, unordered_set< ReactionBase * > > & getCrossCylinderReactions ()
Get map of reactions associated.
vector< ReactionBase * > getAllReactions ()
Get all reactions that this CCylinder has ownership of.
virtual void printCCylinder ()
Print.
bool isConsistent ()
short getSize ()
Get size in number of monomers.
short getType ()
Get the type.
void addInternalReaction (ReactionBase *r)
Reaction management function.
void removeInternalReaction (ReactionBase *r)
Reaction management function.
void removeAllInternalReactions ()
Reaction management function.
void addCrossCylinderReaction (CCylinder *other, ReactionBase *r)
Reaction management function.
void removeCrossCylinderReaction (CCylinder *other, ReactionBase *r)
Reaction management function.
void removeCrossCylinderReactions (CCylinder *other)
Reaction management function.
void removeAllCrossCylinderReactions ()
Reaction management function.
void addReactingCylinder (CCylinder *other)
Reaction management function.
void removeReactingCylinder (CCylinder *other)
Reaction management function.
void removeAllReactingCylinders ()
Reaction management function.
void passivatefilreactions ()
Reaction management function.
void activatefilreactions ()
Reaction management function.
Private Attributes
vector< unique_ptr< CMonomer > > _monomers
List of monomers.
unordered_set< ReactionBase * > _internalReactions
REACTION CONTAINERS.
unordered_set< CCylinder * > _reactingCylinders
Set of ccylinders that this ccylinder has reactions with, but not ownership.
map< CCylinder *, unordered_set< ReactionBase * > > _crossCylinderReactions
Map of cross-cylinder reactions owned.
Compartment * _compartment
Compartment this ccylinder is in.
Cylinder * _pCylinder
Parent cylinder.
short _size = 0
Maximum length.
Static Private Attributes
static ChemSim * _chemSim = 0
A pointer to the ChemSim, initialized by CController.
Friends
class CController
Detailed Description
Holds all CMonomers and Reactions associated with it.
The CCylinder class has lists of the CMonomers that it contains.
A CCylinder also stores the Reactions associated with it internally, as well as cross-cylinder reactions (still "owned" by this CCylinder, but has reactants and/or products that contain a species in another CCylinder). This information is stored in the reaction map. This map can be used to add and delete reactions when a CCylinder changes compartment or is removed from the system.
Lastly, the CCylinder stores a list of other CCylinders that it has cross-cylinder reactions with, but does not have ownership of these reactions. This list can be used to change or delete reactions when needed, but will not be tied to a Compartment transfer of this CCylinder.
Definition at line 44 of file CCylinder.h.
Constructor & Destructor Documentation
CCylinder() [1/2]
CCylinder::CCylinder (Compartment * C, Cylinder * c)
Default constructor, sets compartment and cylinder.
Definition at line 24 of file CCylinder.cpp.
References _size, GeoParams::cylinderSize, SysParams::Geometry(), Cylinder::getType(), and GeoParams::monomerSize.
Referenced by clone().
CCylinder() [2/2]
CCylinder::CCylinder (const CCylinder & rhs, Compartment * c)
Copy constructor.
Note
This constructor will create a new CCylinder with different Species and Reactions within the Compartment that is chosen as a parameter to the constructor. The copied and original CCylinder will not share reactions or species, but will be copied into a new Compartment.
Definition at line 33 of file CCylinder.cpp.
References _crossCylinderReactions, _internalReactions, _monomers, _reactingCylinders, addCrossCylinderReaction(), addInternalReaction(), ReactionBase::clone(), ReactionBase::getCBound(), Compartment::getSpeciesContainer(), and CBound::setOffReaction().
~CCylinder()
CCylinder::~CCylinder ()
Default destructor, explicitly removes CMonomers(including their species, rxns) Removes all reactions associated with this CCylinder, including ones owned by this as well as other CCylinders.
Definition at line 198 of file CCylinder.cpp.
References _compartment, _monomers, CMonomer::_numBSpecies, CMonomer::_numFSpecies, _pCylinder, Cylinder::getType(), removeAllCrossCylinderReactions(), removeAllInternalReactions(), removeAllReactingCylinders(), and Compartment::removeSpecies().
Member Function Documentation
activatefilreactions()
void CCylinder::activatefilreactions ()
Reaction management function.
Definition at line 232 of file CCylinder.cpp.
References _internalReactions, AGING, DEPOLYMERIZATIONMINUSEND, DEPOLYMERIZATIONPLUSEND, FILAMENTDESTRUCTION, POLYMERIZATIONMINUSEND, POLYMERIZATIONPLUSEND, and SEVERING.
Referenced by getCrossCylinderReactions().
addCMonomer()
void CCylinder::addCMonomer (CMonomer * monomer) inline
Add a monomer.
Definition at line 99 of file CCylinder.h.
Referenced by ChemManager::initializeCCylinder().
addCrossCylinderReaction()
void CCylinder::addCrossCylinderReaction (CCylinder * other, ReactionBase * r)
Reaction management function.
Definition at line 113 of file CCylinder.cpp.
References _chemSim, _compartment, _crossCylinderReactions, ReactionBase::activateReaction(), Compartment::addInternalReaction(), addReactingCylinder(), and ChemSim::addReaction().
Referenced by DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), DestructionTemplate::addReaction(), CCylinder(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), getCrossCylinderReactions(), and CMotorGhost::moveMotorHead().
addInternalReaction()
void CCylinder::addInternalReaction (ReactionBase * r)
Reaction management function.
Definition at line 83 of file CCylinder.cpp.
References _chemSim, _compartment, _internalReactions, ReactionBase::activateReaction(), Compartment::addInternalReaction(), and ChemSim::addReaction().
Referenced by PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), AgingTemplate::addReaction(), DestructionTemplate::addReaction(), SeveringTemplate::addReaction(), CCylinder(), CBranchingPoint::createOffReaction(), and getCrossCylinderReactions().
addReactingCylinder()
void CCylinder::addReactingCylinder (CCylinder * other)
Reaction management function.
Definition at line 128 of file CCylinder.cpp.
References _reactingCylinders.
Referenced by addCrossCylinderReaction(), and getCrossCylinderReactions().
clone()
virtual CCylinder* CCylinder::clone (Compartment * c) inline virtual
Clone, calls copy constructor.
Definition at line 86 of file CCylinder.h.
References CCylinder().
getAllReactions()
vector< ReactionBase * > CCylinder::getAllReactions ()
Get all reactions that this CCylinder has ownership of.
Definition at line 245 of file CCylinder.cpp.
References _crossCylinderReactions, and _internalReactions.
Referenced by getCrossCylinderReactions().
getCMonomer()
CMonomer* CCylinder::getCMonomer (int index) inline
Get monomer at an index.
Note
no check on index
Definition at line 104 of file CCylinder.h.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), AgingTemplate::addReaction(), DestructionTemplate::addReaction(), SeveringTemplate::addReaction(), CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), ChemManager::initializeCCylinder(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), CMotorGhost::moveMotorHead(), Filament::nucleate(), Filament::sever(), and BranchingPoint::~BranchingPoint().
getCompartment()
Compartment* CCylinder::getCompartment () inline
Get compartment.
Definition at line 91 of file CCylinder.h.
References _compartment.
Referenced by PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), DestructionTemplate::addReaction(), and ChemManager::initializeCCylinder().
getCrossCylinderReactions()
map<CCylinder*,unordered_set<ReactionBase*> >& CCylinder::getCrossCylinderReactions () inline
Get map of reactions associated.
Definition at line 113 of file CCylinder.h.
References _crossCylinderReactions, activatefilreactions(), addCrossCylinderReaction(), addInternalReaction(), addReactingCylinder(), getAllReactions(), isConsistent(), passivatefilreactions(), printCCylinder(), removeAllCrossCylinderReactions(), removeAllInternalReactions(), removeAllReactingCylinders(), removeCrossCylinderReaction(), removeCrossCylinderReactions(), removeInternalReaction(), and removeReactingCylinder().
getCylinder()
Cylinder* CCylinder::getCylinder () inline
Get parent.
Definition at line 96 of file CCylinder.h.
References _pCylinder.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), DestructionTemplate::addReaction(), SeveringTemplate::addReaction(), ChemManager::initializeCCylinder(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), and MotorBindingManager::isConsistent().
getInternalReactions()
const unordered_set<ReactionBase*>& CCylinder::getInternalReactions () inline
Get list of reactions associated.
Definition at line 107 of file CCylinder.h.
References _internalReactions.
getReactingCylinders()
const unordered_set<CCylinder*>& CCylinder::getReactingCylinders () inline
Get list of reacting cylinders associated.
Definition at line 110 of file CCylinder.h.
References _reactingCylinders.
getSize()
short CCylinder::getSize () inline
Get size in number of monomers.
Definition at line 148 of file CCylinder.h.
References _size, and getType().
Referenced by PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), AgingTemplate::addReaction(), DestructionTemplate::addReaction(), ChemManager::initializeCCylinder(), and Filament::sever().
getType()
short CCylinder::getType ()
Get the type.
Definition at line 290 of file CCylinder.cpp.
References _pCylinder, and Cylinder::getType().
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), getSize(), BranchingManager::removePossibleBindings(), LinkerBindingManager::removePossibleBindings(), and MotorBindingManager::removePossibleBindings().
isConsistent()
bool CCylinder::isConsistent ()
Definition at line 276 of file CCylinder.cpp.
References _monomers.
Referenced by getCrossCylinderReactions().
operator=()
CCylinder& CCylinder::operator= (CCylinder & rhs) delete
Assignment is not allowed.
passivatefilreactions()
void CCylinder::passivatefilreactions ()
Reaction management function.
Definition at line 222 of file CCylinder.cpp.
References _internalReactions, AGING, DEPOLYMERIZATIONMINUSEND, DEPOLYMERIZATIONPLUSEND, FILAMENTDESTRUCTION, POLYMERIZATIONMINUSEND, POLYMERIZATIONPLUSEND, and SEVERING.
Referenced by getCrossCylinderReactions().
printCCylinder()
void CCylinder::printCCylinder () virtual
Print.
Definition at line 264 of file CCylinder.cpp.
References _compartment, and _monomers.
Referenced by getCrossCylinderReactions().
removeAllCrossCylinderReactions()
void CCylinder::removeAllCrossCylinderReactions ()
Reaction management function.
Definition at line 177 of file CCylinder.cpp.
References _crossCylinderReactions, and removeCrossCylinderReactions().
Referenced by getCrossCylinderReactions(), and ~CCylinder().
removeAllInternalReactions()
void CCylinder::removeAllInternalReactions ()
Reaction management function.
Definition at line 132 of file CCylinder.cpp.
References _internalReactions, and removeInternalReaction().
Referenced by getCrossCylinderReactions(), and ~CCylinder().
removeAllReactingCylinders()
void CCylinder::removeAllReactingCylinders ()
Reaction management function.
Definition at line 190 of file CCylinder.cpp.
References _reactingCylinders.
Referenced by getCrossCylinderReactions(), and ~CCylinder().
removeCrossCylinderReaction()
void CCylinder::removeCrossCylinderReaction (CCylinder * other, ReactionBase * r)
Reaction management function.
Definition at line 138 of file CCylinder.cpp.
References _chemSim, _compartment, _crossCylinderReactions, _reactingCylinders, ReactionBase::passivateReaction(), Compartment::removeInternalReaction(), and ChemSim::removeReaction().
Referenced by getCrossCylinderReactions(), CMotorGhost::moveMotorHead(), removeCrossCylinderReactions(), CLinker::~CLinker(), and CMotorGhost::~CMotorGhost().
removeCrossCylinderReactions()
void CCylinder::removeCrossCylinderReactions (CCylinder * other)
Reaction management function.
Definition at line 169 of file CCylinder.cpp.
References _crossCylinderReactions, and removeCrossCylinderReaction().
Referenced by getCrossCylinderReactions(), removeAllCrossCylinderReactions(), removeReactingCylinder(), and Filament::sever().
removeInternalReaction()
void CCylinder::removeInternalReaction (ReactionBase * r)
Reaction management function.
Definition at line 97 of file CCylinder.cpp.
References _chemSim, _compartment, _internalReactions, ReactionBase::passivateReaction(), Compartment::removeInternalReaction(), and ChemSim::removeReaction().
Referenced by getCrossCylinderReactions(), removeAllInternalReactions(), and CBranchingPoint::~CBranchingPoint().
removeReactingCylinder()
void CCylinder::removeReactingCylinder (CCylinder * other)
Reaction management function.
Definition at line 185 of file CCylinder.cpp.
References removeCrossCylinderReactions().
Referenced by getCrossCylinderReactions().
setCylinder()
void CCylinder::setCylinder (Cylinder * c) inline
Set parent.
Definition at line 94 of file CCylinder.h.
Friends And Related Function Documentation
CController
friend class CController friend
Definition at line 46 of file CCylinder.h.
Member Data Documentation
_chemSim
ChemSim * CCylinder::_chemSim = 0 static private
A pointer to the ChemSim, initialized by CController.
Definition at line 64 of file CCylinder.h.
Referenced by addCrossCylinderReaction(), addInternalReaction(), CController::initialize(), removeCrossCylinderReaction(), and removeInternalReaction().
_compartment
Compartment* CCylinder::_compartment private
Compartment this ccylinder is in.
Definition at line 59 of file CCylinder.h.
Referenced by addCrossCylinderReaction(), addInternalReaction(), getCompartment(), printCCylinder(), removeCrossCylinderReaction(), removeInternalReaction(), and ~CCylinder().
_crossCylinderReactions
map<CCylinder*,unordered_set<ReactionBase*> > CCylinder::_crossCylinderReactions private
Map of cross-cylinder reactions owned.
Definition at line 56 of file CCylinder.h.
Referenced by addCrossCylinderReaction(), CCylinder(), getAllReactions(), getCrossCylinderReactions(), removeAllCrossCylinderReactions(), removeCrossCylinderReaction(), and removeCrossCylinderReactions().
_internalReactions
unordered_set<ReactionBase*> CCylinder::_internalReactions private
REACTION CONTAINERS.
Set of internal reactions associated
Definition at line 52 of file CCylinder.h.
Referenced by activatefilreactions(), addInternalReaction(), CCylinder(), getAllReactions(), getInternalReactions(), passivatefilreactions(), removeAllInternalReactions(), and removeInternalReaction().
_monomers
vector<unique_ptr<CMonomer> > CCylinder::_monomers private
List of monomers.
Definition at line 49 of file CCylinder.h.
Referenced by CCylinder(), isConsistent(), printCCylinder(), and ~CCylinder().
_pCylinder
Cylinder* CCylinder::_pCylinder private
Parent cylinder.
Definition at line 60 of file CCylinder.h.
Referenced by getCylinder(), getType(), and ~CCylinder().
_reactingCylinders
unordered_set<CCylinder*> CCylinder::_reactingCylinders private
Set of ccylinders that this ccylinder has reactions with, but not ownership.
Definition at line 54 of file CCylinder.h.
Referenced by addReactingCylinder(), CCylinder(), getReactingCylinders(), removeAllReactingCylinders(), and removeCrossCylinderReaction().
_size
short CCylinder::_size = 0 private
Maximum length.
Definition at line 62 of file CCylinder.h.
Referenced by CCylinder(), and getSize().
The documentation for this class was generated from the following files:
src/Structure/CCylinder.h
src/Structure/CCylinder.cpp