MEDYAN: FilamentReactionTemplate Class Reference
FilamentReactionTemplate Class Reference abstract
To store Filament chemical reaction information read from an input file.
#include <ReactionTemplate.h>
Public Member Functions
FilamentReactionTemplate (short filamentType, vector< tuple< int, SpeciesType >> reactants, vector< tuple< int, SpeciesType >> products, float rate)
~FilamentReactionTemplate ()
virtual void addReaction (CCylinder *cc)=0
Add this chemical reaction. Adds all extension and retraction callbacks needed.
virtual void addReaction (CCylinder *cc1, CCylinder *cc2)=0
Add this chemical reaction along a filament.
Protected Attributes
short _filamentType
Filament type that this template acts on.
vector< tuple< int, SpeciesType > > _reactants
Reactants in this reaction.
vector< tuple< int, SpeciesType > > _products
Products in this reaction.
float _rate
Rate of reaction.
Static Protected Attributes
static SubSystem * _ps = 0
A subsystem pointer to initialize and call chemical callbacks.
Friends
class CController
Detailed Description
To store Filament chemical reaction information read from an input file.
FilamentReactionTemplate is used to store a Filament reaction. It contains vectors of tuples that represent the position in the CMonomer in which the species is stored (for products and reactants), as well as the rate of the reaction. The integer value that is the position of the species in the CMonomer vector is held by the ChemManager.
Note
if the species is a bulk or diffusing species, the integer molecule value in the tuple stored in the SpeciesNamesDB.
This class also has functions to add the filament reaction to a CCylinder, as well as add a connection reaction between two neighboring CCylinders.
Definition at line 47 of file ReactionTemplate.h.
Constructor & Destructor Documentation
FilamentReactionTemplate()
FilamentReactionTemplate::FilamentReactionTemplate (short filamentType, vector< tuple< int, SpeciesType >> reactants, vector< tuple< int, SpeciesType >> products, float rate) inline
Definition at line 62 of file ReactionTemplate.h.
~FilamentReactionTemplate()
FilamentReactionTemplate::~FilamentReactionTemplate () inline
Definition at line 75 of file ReactionTemplate.h.
References addReaction().
Member Function Documentation
addReaction() [1/2]
virtual void FilamentReactionTemplate::addReaction (CCylinder * cc) pure virtual
Add this chemical reaction. Adds all extension and retraction callbacks needed.
Implemented in SeveringTemplate, DestructionTemplate, AgingTemplate, MotorWalkMTemplate, MotorWalkPTemplate, DepolyMinusEndTemplate, DepolyPlusEndTemplate, PolyMinusEndTemplate, and PolyPlusEndTemplate.
Referenced by AgingTemplate::~AgingTemplate(), DepolyMinusEndTemplate::~DepolyMinusEndTemplate(), DepolyPlusEndTemplate::~DepolyPlusEndTemplate(), DestructionTemplate::~DestructionTemplate(), ~FilamentReactionTemplate(), MotorWalkMTemplate::~MotorWalkMTemplate(), MotorWalkPTemplate::~MotorWalkPTemplate(), PolyMinusEndTemplate::~PolyMinusEndTemplate(), PolyPlusEndTemplate::~PolyPlusEndTemplate(), and SeveringTemplate::~SeveringTemplate().
addReaction() [2/2]
virtual void FilamentReactionTemplate::addReaction (CCylinder * cc1, CCylinder * cc2) pure virtual
Add this chemical reaction along a filament.
Note
assumes cc1 and cc2 are in order, that is, cc2 is the next cylinder after cc1
Implemented in SeveringTemplate, DestructionTemplate, AgingTemplate, MotorWalkMTemplate, MotorWalkPTemplate, DepolyMinusEndTemplate, DepolyPlusEndTemplate, PolyMinusEndTemplate, and PolyPlusEndTemplate.
Friends And Related Function Documentation
CController
friend class CController friend
Definition at line 49 of file ReactionTemplate.h.
Member Data Documentation
_filamentType
short FilamentReactionTemplate::_filamentType protected
Filament type that this template acts on.
Definition at line 54 of file ReactionTemplate.h.
_products
vector<tuple<int,SpeciesType> > FilamentReactionTemplate::_products protected
Products in this reaction.
Definition at line 57 of file ReactionTemplate.h.
_ps
SubSystem * FilamentReactionTemplate::_ps = 0 static protected
A subsystem pointer to initialize and call chemical callbacks.
Definition at line 52 of file ReactionTemplate.h.
Referenced by SeveringTemplate::addReaction(), and CController::initialize().
_rate
float FilamentReactionTemplate::_rate protected
Rate of reaction.
Definition at line 59 of file ReactionTemplate.h.
_reactants
vector<tuple<int,SpeciesType> > FilamentReactionTemplate::_reactants protected
Reactants in this reaction.
Definition at line 56 of file ReactionTemplate.h.
The documentation for this class was generated from the following files:
src/Chemistry/ReactionTemplate.h
src/Chemistry/ReactionTemplate.cpp