MEDYAN: CController Class Reference
CController Class Reference
Used to intialize, control, and run the chemical components of a simulation.
#include <CController.h>
Public Member Functions
CController (SubSystem *s)
Constructor which sets subsystem pointer.
void activate (Compartment *C)
Activate a compartment. Wrapper function for Compartment::activate().
void deactivate (Compartment *C)
Deactivate a compartment. Wrapper function for Compartment::deactivate().
void initialize (string &chemAlgorithm, ChemistryData &chem)
Initialize the ChemSim algorithm as well as the ChemManager.
void restart ()
bool run (double time)
Run chemistry for a given amount of time.
bool runSteps (int steps)
Run chemistry for a given number of reaction steps.
void removeReactions ()
Remove set of reactions at runtime, specified by input.
Private Attributes
SubSystem * _subSystem
A pointer to the SubSystem.
ChemSim * _chemSim
Holding pointers to control all chemistry.
ChemManager * _chemManager
Holding pointers to control all chemistry.
Detailed Description
Used to intialize, control, and run the chemical components of a simulation.
ChemController is a class used by the SubSystem to instantiate, control, and run the chemical dynamics of a simulation. It has functions to initialize a chemical system, which, based on a choice of the reaction-diffusion algorithm as well as the type of manager which controls the reactions in the simulation, as well as run the chemical components of the simulation.
The controller initializes all chemical objects used, including ChemSim and ChemManager to the correct implementations, given that they are implemented.
Definition at line 41 of file CController.h.
Constructor & Destructor Documentation
CController()
CController::CController (SubSystem * s) inline
Constructor which sets subsystem pointer.
Definition at line 53 of file CController.h.
Member Function Documentation
activate()
void CController::activate (Compartment * C) inline
Activate a compartment. Wrapper function for Compartment::activate().
Definition at line 56 of file CController.h.
References Compartment::activate().
Referenced by Controller::moveBoundary().
deactivate()
void CController::deactivate (Compartment * C) inline
Deactivate a compartment. Wrapper function for Compartment::deactivate().
Definition at line 58 of file CController.h.
References Compartment::deactivate(), initialize(), removeReactions(), restart(), run(), and runSteps().
Referenced by Controller::moveBoundary().
initialize()
void CController::initialize (string & chemAlgorithm, ChemistryData & chem)
Initialize the ChemSim algorithm as well as the ChemManager.
Parameters
chemAlgorithm - a string defining the chemical algorithm to be used
chemInitializer - a string defining the chemical manager used
Definition at line 27 of file CController.cpp.
References _chemManager, Cylinder::_chemManager, _chemSim, CCylinder::_chemSim, FilamentReactionTemplate::_ps, _subSystem, ChemSim::initialize(), ChemManager::initializeSystem(), and ChemSim::setInstance().
Referenced by deactivate(), and Controller::initialize().
removeReactions()
void CController::removeReactions ()
Remove set of reactions at runtime, specified by input.
Referenced by deactivate().
restart()
void CController::restart ()
Definition at line 88 of file CController.cpp.
References _chemSim, and ChemSim::initialize().
Referenced by deactivate(), and Controller::run().
run()
bool CController::run (double time)
Run chemistry for a given amount of time.
Definition at line 78 of file CController.cpp.
References _chemManager, _chemSim, ChemSim::run(), and ChemManager::updateCopyNumbers().
Referenced by deactivate(), and Controller::run().
runSteps()
bool CController::runSteps (int steps)
Run chemistry for a given number of reaction steps.
Definition at line 91 of file CController.cpp.
References _chemManager, _chemSim, ChemSim::runSteps(), and ChemManager::updateCopyNumbers().
Referenced by deactivate(), and Controller::run().
Member Data Documentation
_chemManager
ChemManager* CController::_chemManager private
Holding pointers to control all chemistry.
Definition at line 48 of file CController.h.
Referenced by initialize(), run(), and runSteps().
_chemSim
ChemSim* CController::_chemSim private
Holding pointers to control all chemistry.
Definition at line 48 of file CController.h.
Referenced by initialize(), restart(), run(), and runSteps().
_subSystem
SubSystem* CController::_subSystem private
A pointer to the SubSystem.
Definition at line 44 of file CController.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/CController.h
src/CController.cpp