MEDYAN: MLinker Class Reference
MLinker Class Reference
Represents the mechanical component of a Linker.
#include <MLinker.h>
Public Member Functions
MLinker (int linkerType, double position1, double position2, const vector< double > &coord11, const vector< double > &coord12, const vector< double > &coord21, const vector< double > &coord22)
Main constructor.
void setLinker (Linker *linker)
Set parent.
Linker * getLinker ()
Get parent.
double getStretchingConstant ()
Getter for constants.
double getEqLength ()
Getter for constants.
void setLength (double l)
Length management.
double getLength ()
Length management.
Public Attributes
double stretchForce = 0.0
Stretching force of linker at current state.
Private Attributes
double _eqLength
Equilibrium length, set at construction.
double _kStretch
Stretching constant.
Linker * _pLinker
Pointer to parent linker.
double _currentLength
Current length of the linker.
Detailed Description
Represents the mechanical component of a Linker.
The class describes interaction between 4 Beads connected by a Linker, and its associated equilibrium constants. Initial length of a Linker is determined by the condition of zero initial stress, i.e., it calculated within the constructor at initiation. A Linker heads positions on a segment (between two consecutive beads on a Filament) determined by two numbers (double from 0 to 1) position1 and position2 held in the parent Linker.
Definition at line 33 of file MLinker.h.
Constructor & Destructor Documentation
MLinker()
MLinker::MLinker (int linkerType, double position1, double position2, const vector< double > & coord11, const vector< double > & coord12, const vector< double > & coord21, const vector< double > & coord22)
Main constructor.
Parameters
position - position on cylinder 1 and 2, respectively
coord - coordinates of cylinder1's bead 1, bead 2, etc
Definition at line 21 of file MLinker.cpp.
References MechParams::LStretchingK, SysParams::Mechanics(), mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
Member Function Documentation
getEqLength()
double MLinker::getEqLength () inline
Getter for constants.
Definition at line 48 of file MLinker.h.
References _eqLength.
getLength()
double MLinker::getLength () inline
Length management.
Definition at line 59 of file MLinker.h.
References _currentLength.
getLinker()
Linker* MLinker::getLinker () inline
Get parent.
Definition at line 54 of file MLinker.h.
References _currentLength, _pLinker, and setLength().
getStretchingConstant()
double MLinker::getStretchingConstant () inline
Getter for constants.
Definition at line 47 of file MLinker.h.
setLength()
void MLinker::setLength (double l) inline
Length management.
Definition at line 58 of file MLinker.h.
Referenced by getLinker().
setLinker()
void MLinker::setLinker (Linker * linker) inline
Set parent.
Definition at line 52 of file MLinker.h.
References _pLinker.
Member Data Documentation
_currentLength
double MLinker::_currentLength private
Current length of the linker.
Definition at line 68 of file MLinker.h.
Referenced by getLength(), and getLinker().
_eqLength
double MLinker::_eqLength private
Equilibrium length, set at construction.
Definition at line 63 of file MLinker.h.
Referenced by getEqLength().
_kStretch
double MLinker::_kStretch private
Stretching constant.
Definition at line 64 of file MLinker.h.
_pLinker
Linker* MLinker::_pLinker private
Pointer to parent linker.
Definition at line 66 of file MLinker.h.
Referenced by getLinker(), and setLinker().
stretchForce
double MLinker::stretchForce = 0.0
Stretching force of linker at current state.
Definition at line 36 of file MLinker.h.
The documentation for this class was generated from the following files:
src/Structure/MLinker.h
src/Structure/MLinker.cpp