MEDYAN: BoundaryBubbleRepulsion< BRepulsionInteractionType > Class Template Reference
BoundaryBubbleRepulsion< BRepulsionInteractionType > Class Template Reference
Represents a repulsive interaction between a BoundaryElement and Bubble.
#include <BoundaryBubbleRepulsion.h>
Public Member Functions
BoundaryBubbleRepulsion ()
Constructor.
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual void computeLoadForces ()
Compute the load forces on beads from this interaction.
virtual NeighborList * getNeighborList ()
Get the neighbor list for this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
BoundaryElement * _boundaryElementCulprit = nullptr
In the case of an error.
Component * _otherCulprit = nullptr
In the case of an error.
Private Attributes
BRepulsionInteractionType _FFType
BoundaryBubbleNL * _neighborList
Neighbor list of Bubble's bead - BoundaryElement.
Detailed Description
template<class BRepulsionInteractionType>
class BoundaryBubbleRepulsion< BRepulsionInteractionType >
Represents a repulsive interaction between a BoundaryElement and Bubble.
Definition at line 32 of file BoundaryBubbleRepulsion.h.
Constructor & Destructor Documentation
BoundaryBubbleRepulsion()
template<class BRepulsionInteractionType > BoundaryBubbleRepulsion< BRepulsionInteractionType >::BoundaryBubbleRepulsion () inline
Constructor.
Definition at line 40 of file BoundaryBubbleRepulsion.h.
References SysParams::Boundaries(), BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForces(), and BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux().
Member Function Documentation
computeEnergy()
template<class BRepulsionInteractionType > template double BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BoundaryInteractions.
Definition at line 23 of file BoundaryBubbleRepulsion.cpp.
References Bead::coordinate, Bead::force, and BoundaryElement::getBoundaryElements().
Referenced by BoundaryBubbleRepulsion< BRepulsionInteractionType >::BoundaryBubbleRepulsion(), and BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux().
computeForces()
template<class BRepulsionInteractionType > template void BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements BoundaryInteractions.
Definition at line 64 of file BoundaryBubbleRepulsion.cpp.
References Bead::coordinate, and BoundaryElement::getBoundaryElements().
Referenced by BoundaryBubbleRepulsion< BRepulsionInteractionType >::BoundaryBubbleRepulsion(), and BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux().
computeForcesAux()
template<class BRepulsionInteractionType > template void BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements BoundaryInteractions.
Definition at line 86 of file BoundaryBubbleRepulsion.cpp.
References BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeEnergy(), BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeForces(), Bead::coordinate, and BoundaryElement::getBoundaryElements().
Referenced by BoundaryBubbleRepulsion< BRepulsionInteractionType >::BoundaryBubbleRepulsion().
computeLoadForces()
template<class BRepulsionInteractionType > virtual void BoundaryBubbleRepulsion< BRepulsionInteractionType >::computeLoadForces () inline virtual
Compute the load forces on beads from this interaction.
Implements BoundaryInteractions.
Definition at line 49 of file BoundaryBubbleRepulsion.h.
getName()
template<class BRepulsionInteractionType > virtual const string BoundaryBubbleRepulsion< BRepulsionInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BoundaryInteractions.
Definition at line 54 of file BoundaryBubbleRepulsion.h.
getNeighborList()
template<class BRepulsionInteractionType > virtual NeighborList* BoundaryBubbleRepulsion< BRepulsionInteractionType >::getNeighborList () inline virtual
Get the neighbor list for this interaction.
Implements BoundaryInteractions.
Definition at line 52 of file BoundaryBubbleRepulsion.h.
References BoundaryBubbleRepulsion< BRepulsionInteractionType >::_neighborList.
Member Data Documentation
_boundaryElementCulprit
BoundaryElement* BoundaryInteractions::_boundaryElementCulprit = nullptr protected inherited
In the case of an error.
Definition at line 33 of file BoundaryInteractions.h.
Referenced by BoundaryFF::whoIsCulprit().
_FFType
template<class BRepulsionInteractionType > BRepulsionInteractionType BoundaryBubbleRepulsion< BRepulsionInteractionType >::_FFType private
Definition at line 35 of file BoundaryBubbleRepulsion.h.
_neighborList
template<class BRepulsionInteractionType > BoundaryBubbleNL* BoundaryBubbleRepulsion< BRepulsionInteractionType >::_neighborList private
Neighbor list of Bubble's bead - BoundaryElement.
Definition at line 36 of file BoundaryBubbleRepulsion.h.
Referenced by BoundaryBubbleRepulsion< BRepulsionInteractionType >::getNeighborList().
_otherCulprit
Component* BoundaryInteractions::_otherCulprit = nullptr protected inherited
In the case of an error.
Definition at line 34 of file BoundaryInteractions.h.
Referenced by BoundaryFF::whoIsCulprit().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Boundary/BoundaryBubbleRepulsion.h
src/Mechanics/ForceField/Boundary/BoundaryBubbleRepulsion.cpp