MEDYAN: ChemSimpleGillespieImpl Class Reference
ChemSimpleGillespieImpl Class Reference
Implements the simplest version of the Gillespie algorithm, without caching, etc.
#include <ChemSimpleGillespieImpl.h>
Public Member Functions
ChemSimpleGillespieImpl ()
Ctor: Seeds the random number generator, sets global time to 0.0.
ChemSimpleGillespieImpl (const ChemSimpleGillespieImpl &rhs)=delete
Copying is not allowed.
ChemSimpleGillespieImpl & operator= (ChemSimpleGillespieImpl &rhs)=delete
Assignment is not allowed.
virtual ~ChemSimpleGillespieImpl () noexcept
Dtor: The reaction network is cleared.
size_t getSize () const
Return the number of reactions in the network.
double getTime () const
Return the current global time (which should be the sum of all previously occurred tau-s of the Gillespie algorithm)
void resetTime ()
Sets global time to 0.0.
void syncGlobalTime ()
Sets global time variable to ChemSimpleGillespieImpl's global time.
virtual void addReaction (ReactionBase *r)
Add ReactionBase *r to the network.
virtual void removeReaction (ReactionBase *r)
Remove ReactionBase *r from the network.
double computeTotalA ()
Compute the total propensity of the reaction network, by adding all individual reaction propensities.
double generateTau (double a)
A pure function (without sideeffects), which returns a random time tau, drawn from the exponential distribution, with the propensity given by a.
double generateUniform ()
This function generates a random number between 0 and 1.
void initialize ()
This function needs to be called before calling run(...).
virtual bool run (double time)
This method runs the Gillespie algorithm for the given amount of time.
virtual bool runSteps (int steps)
This method runs the Gillespie algorithm for the given amount of reaction steps.
virtual void printReactions () const
Prints all Reaction objects in the reaction network.
Private Member Functions
bool makeStep ()
This subroutine implements the vanilla version of the Gillespie algorithm.
Private Attributes
vector< ReactionBase * > _reactions
The database of Reaction objects, representing the reaction network.
mt19937 _eng
Random number generator.
exponential_distribution< double > _exp_distr
Adaptor for the exponential distribution.
uniform_real_distribution< double > _uniform_distr
Adaptor for the uniform distribution.
double _t
global time
Detailed Description
Implements the simplest version of the Gillespie algorithm, without caching, etc.
ChemSimpleGillespieImpl manages the Gillespie algorithm at the level of the network of reactions. Reaction objects can be added and removed from the ChemSimpleGillespieImpl instance.
Definition at line 33 of file ChemSimpleGillespieImpl.h.
Constructor & Destructor Documentation
ChemSimpleGillespieImpl() [1/2]
ChemSimpleGillespieImpl::ChemSimpleGillespieImpl () inline
Ctor: Seeds the random number generator, sets global time to 0.0.
Definition at line 36 of file ChemSimpleGillespieImpl.h.
References operator=(), resetTime(), and ~ChemSimpleGillespieImpl().
ChemSimpleGillespieImpl() [2/2]
ChemSimpleGillespieImpl::ChemSimpleGillespieImpl (const ChemSimpleGillespieImpl & rhs) delete
Copying is not allowed.
~ChemSimpleGillespieImpl()
ChemSimpleGillespieImpl::~ChemSimpleGillespieImpl () virtual noexcept
Dtor: The reaction network is cleared.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 21 of file ChemSimpleGillespieImpl.cpp.
References _reactions.
Referenced by ChemSimpleGillespieImpl().
Member Function Documentation
addReaction()
void ChemSimpleGillespieImpl::addReaction (ReactionBase * r) virtual
Add ReactionBase *r to the network.
Implements ChemSimImpl.
Definition at line 84 of file ChemSimpleGillespieImpl.cpp.
References _reactions.
Referenced by syncGlobalTime().
computeTotalA()
double ChemSimpleGillespieImpl::computeTotalA ()
Compute the total propensity of the reaction network, by adding all individual reaction propensities.
Definition at line 35 of file ChemSimpleGillespieImpl.cpp.
References _reactions.
Referenced by makeStep(), and syncGlobalTime().
generateTau()
double ChemSimpleGillespieImpl::generateTau (double a)
A pure function (without sideeffects), which returns a random time tau, drawn from the exponential distribution, with the propensity given by a.
Definition at line 25 of file ChemSimpleGillespieImpl.cpp.
References _eng, and _exp_distr.
Referenced by makeStep(), and syncGlobalTime().
generateUniform()
double ChemSimpleGillespieImpl::generateUniform ()
This function generates a random number between 0 and 1.
Definition at line 31 of file ChemSimpleGillespieImpl.cpp.
References _eng, and _uniform_distr.
Referenced by makeStep(), and syncGlobalTime().
getSize()
size_t ChemSimpleGillespieImpl::getSize () const inline
Return the number of reactions in the network.
Definition at line 54 of file ChemSimpleGillespieImpl.h.
References _reactions.
getTime()
double ChemSimpleGillespieImpl::getTime () const inline
Return the current global time (which should be the sum of all previously occurred tau-s of the Gillespie algorithm)
Definition at line 58 of file ChemSimpleGillespieImpl.h.
References _t.
initialize()
void ChemSimpleGillespieImpl::initialize () virtual
This function needs to be called before calling run(...).
Note
If somewhere in the middle of simulaiton initialize() is called, it will be analogous to starting the simulation from scratch, except with the Species copy numbers given at that moment in time. The global time is reset to zero again.
Implements ChemSimImpl.
Definition at line 16 of file ChemSimpleGillespieImpl.cpp.
References resetTime().
Referenced by syncGlobalTime().
makeStep()
bool ChemSimpleGillespieImpl::makeStep () private
This subroutine implements the vanilla version of the Gillespie algorithm.
Definition at line 43 of file ChemSimpleGillespieImpl.cpp.
References _reactions, _t, ReactionBase::computePropensity(), computeTotalA(), generateTau(), generateUniform(), ReactionBase::makeStep(), syncGlobalTime(), and tau().
Referenced by run(), and runSteps().
operator=()
ChemSimpleGillespieImpl& ChemSimpleGillespieImpl::operator= (ChemSimpleGillespieImpl & rhs) delete
Assignment is not allowed.
Referenced by ChemSimpleGillespieImpl().
printReactions()
void ChemSimpleGillespieImpl::printReactions () const virtual
Prints all Reaction objects in the reaction network.
Implements ChemSimImpl.
Definition at line 96 of file ChemSimpleGillespieImpl.cpp.
References _reactions.
Referenced by runSteps().
removeReaction()
void ChemSimpleGillespieImpl::removeReaction (ReactionBase * r) virtual
Remove ReactionBase *r from the network.
Implements ChemSimImpl.
Definition at line 90 of file ChemSimpleGillespieImpl.cpp.
References _reactions.
Referenced by syncGlobalTime().
resetTime()
void ChemSimpleGillespieImpl::resetTime () inline
Sets global time to 0.0.
Definition at line 61 of file ChemSimpleGillespieImpl.h.
References _t, and syncGlobalTime().
Referenced by ChemSimpleGillespieImpl(), and initialize().
run()
virtual bool ChemSimpleGillespieImpl::run (double time) inline virtual
This method runs the Gillespie algorithm for the given amount of time.
Returns
true if successful.
Implements ChemSimImpl.
Definition at line 91 of file ChemSimpleGillespieImpl.h.
References _t, and makeStep().
runSteps()
virtual bool ChemSimpleGillespieImpl::runSteps (int steps) inline virtual
This method runs the Gillespie algorithm for the given amount of reaction steps.
Returns
true if successful.
Implements ChemSimImpl.
Definition at line 105 of file ChemSimpleGillespieImpl.h.
References makeStep(), and printReactions().
syncGlobalTime()
void ChemSimpleGillespieImpl::syncGlobalTime () inline
Sets global time variable to ChemSimpleGillespieImpl's global time.
Definition at line 64 of file ChemSimpleGillespieImpl.h.
References _t, addReaction(), computeTotalA(), generateTau(), generateUniform(), global_time, initialize(), and removeReaction().
Referenced by makeStep(), and resetTime().
Member Data Documentation
_eng
mt19937 ChemSimpleGillespieImpl::_eng private
Random number generator.
Definition at line 125 of file ChemSimpleGillespieImpl.h.
Referenced by generateTau(), and generateUniform().
_exp_distr
exponential_distribution<double> ChemSimpleGillespieImpl::_exp_distr private
Adaptor for the exponential distribution.
Definition at line 126 of file ChemSimpleGillespieImpl.h.
Referenced by generateTau().
_reactions
vector<ReactionBase*> ChemSimpleGillespieImpl::_reactions private
The database of Reaction objects, representing the reaction network.
Definition at line 123 of file ChemSimpleGillespieImpl.h.
Referenced by addReaction(), computeTotalA(), getSize(), makeStep(), printReactions(), removeReaction(), and ~ChemSimpleGillespieImpl().
_t
double ChemSimpleGillespieImpl::_t private
global time
Definition at line 128 of file ChemSimpleGillespieImpl.h.
Referenced by getTime(), makeStep(), resetTime(), run(), and syncGlobalTime().
_uniform_distr
uniform_real_distribution<double> ChemSimpleGillespieImpl::_uniform_distr private
Adaptor for the uniform distribution.
Definition at line 127 of file ChemSimpleGillespieImpl.h.
Referenced by generateUniform().
The documentation for this class was generated from the following files:
src/Chemistry/ChemSimpleGillespieImpl.h
src/Chemistry/ChemSimpleGillespieImpl.cpp