MEDYAN: BranchingStretchingHarmonic Class Reference
BranchingStretchingHarmonic Class Reference
Represents a harmonic potential used by the [BranchingStretching](BranchingStretching) template.
#include <BranchingStretchingHarmonic.h>
Public Member Functions
double energy (Bead *, Bead *, Bead *, double position, double kStretch, double eqLength)
double energy (Bead *, Bead *, Bead *, double position, double kStretch, double eqLength, double d)
void forces (Bead *, Bead *, Bead *, double position, double kStretch, double eqLength)
void forcesAux (Bead *, Bead *, Bead *, double position, double kStretch, double eqLength)
Detailed Description
Represents a harmonic potential used by the [BranchingStretching](BranchingStretching) template.
Definition at line 24 of file BranchingStretchingHarmonic.h.
Member Function Documentation
energy() [1/2]
double BranchingStretchingHarmonic::energy (Bead * b1, Bead * b2, Bead * b3, double position, double kStretch, double eqLength)
Definition at line 21 of file BranchingStretchingHarmonic.cpp.
References Bead::coordinate, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
energy() [2/2]
double BranchingStretchingHarmonic::energy (Bead * b1, Bead * b2, Bead * b3, double position, double kStretch, double eqLength, double d)
Definition at line 34 of file BranchingStretchingHarmonic.cpp.
References Bead::coordinate, Bead::force, mathfunc::midPointCoordinateStretched(), and mathfunc::twoPointDistanceStretched().
forces()
void BranchingStretchingHarmonic::forces (Bead * b1, Bead * b2, Bead * b3, double position, double kStretch, double eqLength)
Definition at line 50 of file BranchingStretchingHarmonic.cpp.
References Bead::coordinate, Bead::force, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
forcesAux()
void BranchingStretchingHarmonic::forcesAux (Bead * b1, Bead * b2, Bead * b3, double position, double kStretch, double eqLength)
Definition at line 79 of file BranchingStretchingHarmonic.cpp.
References Bead::coordinate, Bead::forceAux, mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Branching/BranchingStretchingHarmonic.h
src/Mechanics/ForceField/Branching/BranchingStretchingHarmonic.cpp