MEDYAN: BranchingBending< BBendingInteractionType > Class Template Reference
BranchingBending< BBendingInteractionType > Class Template Reference
Represents an interaction maintaining a BranchingPoint angle (~270 for Arp2/3)
#include <BranchingBending.h>
Public Member Functions
virtual double computeEnergy (double d)
Template specializations.
virtual void computeForces ()
Compute forces of this interaction.
virtual void computeForcesAux ()
Compute auxiliary forces of this interaction.
virtual const string getName ()
Get the name of this interaction.
Protected Attributes
BranchingPoint * _branchingCulprit = nullptr
The branching point in the case of an error.
Private Attributes
BBendingInteractionType _FFType
Detailed Description
template<class BBendingInteractionType>
class BranchingBending< BBendingInteractionType >
Represents an interaction maintaining a BranchingPoint angle (~270 for Arp2/3)
Definition at line 26 of file BranchingBending.h.
Member Function Documentation
computeEnergy()
template<class BBendingInteractionType > template double BranchingBending< BBendingInteractionType >::computeEnergy (double d) virtual
Template specializations.
Implements BranchingInteractions.
Definition at line 23 of file BranchingBending.cpp.
References BranchingPoint::getBranchingPoints().
Referenced by BranchingBending< BBendingInteractionType >::computeForcesAux().
computeForces()
template<class BBendingInteractionType > template void BranchingBending< BBendingInteractionType >::computeForces () virtual
Compute forces of this interaction.
Implements BranchingInteractions.
Definition at line 58 of file BranchingBending.cpp.
References BranchingPoint::getBranchingPoints().
Referenced by BranchingBending< BBendingInteractionType >::computeForcesAux().
computeForcesAux()
template<class BBendingInteractionType > template void BranchingBending< BBendingInteractionType >::computeForcesAux () virtual
Compute auxiliary forces of this interaction.
Implements BranchingInteractions.
Definition at line 74 of file BranchingBending.cpp.
References BranchingBending< BBendingInteractionType >::computeEnergy(), BranchingBending< BBendingInteractionType >::computeForces(), and BranchingPoint::getBranchingPoints().
getName()
template<class BBendingInteractionType > virtual const string BranchingBending< BBendingInteractionType >::getName () inline virtual
Get the name of this interaction.
Implements BranchingInteractions.
Definition at line 36 of file BranchingBending.h.
Member Data Documentation
_branchingCulprit
BranchingPoint* BranchingInteractions::_branchingCulprit = nullptr protected inherited
The branching point in the case of an error.
Definition at line 31 of file BranchingInteractions.h.
Referenced by BranchingFF::whoIsCulprit().
_FFType
template<class BBendingInteractionType > BBendingInteractionType BranchingBending< BBendingInteractionType >::_FFType private
Definition at line 29 of file BranchingBending.h.
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Branching/BranchingBending.h
src/Mechanics/ForceField/Branching/BranchingBending.cpp