MEDYAN: CMonomer Class Reference
CMonomer Class Reference
Represents a container for all Species that could be contained in a particular filament element at a given position.
#include <CMonomer.h>
Public Member Functions
CMonomer (short filamentType)
Constructor does nothing but memset arrays.
virtual ~CMonomer () noexcept
Default destructor.
CMonomer (const CMonomer &rhs, Compartment *c)
Copy constructor This constructor will create a new CMonomer, identical to the copied, in a new compartment.
CMonomer & operator= (CMonomer &rhs)=delete
Assignment is not allowed.
virtual CMonomer * clone (Compartment *c)
Clone a CMonomer. Transfers all CBounds to the new CMonomer.
void print ()
Print the Species.
SpeciesFilament * speciesFilament (int index)
Get Species at a specific index.
SpeciesFilament * speciesPlusEnd (int index)
Get Species at a specific index.
SpeciesFilament * speciesMinusEnd (int index)
Get Species at a specific index.
SpeciesBound * speciesBound (int index)
Get Species at a specific index.
SpeciesBound * speciesLinker (int index)
Get Species at a specific index.
SpeciesBound * speciesMotor (int index)
Get Species at a specific index.
SpeciesBound * speciesBrancher (int index)
Get Species at a specific index.
short activeSpeciesFilament ()
Get the active species of the corresponding type.
short activeSpeciesPlusEnd ()
Get the active species of the corresponding type.
short activeSpeciesMinusEnd ()
Get the active species of the corresponding type.
short activeSpeciesLinker ()
Get the active species of the corresponding type.
short activeSpeciesMotor ()
Get the active species of the corresponding type.
short activeSpeciesBrancher ()
Get the active species of the corresponding type.
bool isConsistent ()
Check the consistency of the CMonomer for debugging.
Private Attributes
short _filamentType
Filament type that this monomer is in.
SpeciesFilament ** _speciesFilament
Species array.
SpeciesBound ** _speciesBound
Species array.
Static Private Attributes
static vector< short > _numFSpecies = vector<short>(MAX_FILAMENT_TYPES)
Number of species for each filament type.
static vector< short > _numBSpecies = vector<short>(MAX_FILAMENT_TYPES)
static vector< vector< short > > _speciesFilamentIndex = vector<vector<short>>(MAX_FILAMENT_TYPES)
Species index vectors These index vectors are used to access the correct species in the actual species arrays.
static vector< vector< short > > _speciesBoundIndex = vector<vector<short>>(MAX_FILAMENT_TYPES)
Species index vectors These index vectors are used to access the correct species in the actual species arrays.
Friends
class ChemManager
class CCylinder
Detailed Description
Represents a container for all Species that could be contained in a particular filament element at a given position.
CMonomer provides a container to hold all Species that are held at a given filament position. The species are held in an standard vector.
Definition at line 28 of file CMonomer.h.
Constructor & Destructor Documentation
CMonomer() [1/2]
CMonomer::CMonomer (short filamentType)
Constructor does nothing but memset arrays.
Definition at line 19 of file CMonomer.cpp.
References _filamentType, _numBSpecies, _numFSpecies, _speciesBound, and _speciesFilament.
Referenced by clone().
~CMonomer()
CMonomer::~CMonomer () virtual noexcept
Default destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 25 of file CMonomer.cpp.
References _speciesBound, and _speciesFilament.
CMonomer() [2/2]
CMonomer::CMonomer (const CMonomer & rhs, Compartment * c)
Copy constructor This constructor will create a new CMonomer, identical to the copied, in a new compartment.
The original species will remain intact, while new identical species will be initialized.
Definition at line 32 of file CMonomer.cpp.
References _filamentType, _numFSpecies, _speciesBound, _speciesFilament, Compartment::addSpeciesUnique(), SpeciesFilament::clone(), SpeciesBound::clone(), SpeciesBound::getCBound(), CBound::getFirstSpecies(), CBound::setFirstSpecies(), and CBound::setSecondSpecies().
Member Function Documentation
activeSpeciesBrancher()
short CMonomer::activeSpeciesBrancher ()
Get the active species of the corresponding type.
Note
these functions will return -1 if the corresponding type has no marked species at this point.
Definition at line 174 of file CMonomer.cpp.
References _filamentType, _speciesBound, _speciesBoundIndex, areEqual(), SysParams::Chemistry(), Species::getN(), ChemParams::numBrancherSpecies, and SPECIESBRANCHER.
Referenced by clone().
activeSpeciesFilament()
short CMonomer::activeSpeciesFilament ()
Get the active species of the corresponding type.
Note
these functions will return -1 if the corresponding type has no marked species at this point.
Definition at line 120 of file CMonomer.cpp.
References _filamentType, _speciesFilament, _speciesFilamentIndex, areEqual(), SysParams::Chemistry(), Species::getN(), ChemParams::numFilamentSpecies, and SPECIESFILAMENT.
Referenced by clone(), isConsistent(), Filament::sever(), and BranchingPoint::~BranchingPoint().
activeSpeciesLinker()
short CMonomer::activeSpeciesLinker ()
Get the active species of the corresponding type.
Note
these functions will return -1 if the corresponding type has no marked species at this point.
Definition at line 153 of file CMonomer.cpp.
References _filamentType, _speciesBound, _speciesBoundIndex, areEqual(), SysParams::Chemistry(), Species::getN(), ChemParams::numLinkerSpecies, and SPECIESLINKER.
Referenced by clone().
activeSpeciesMinusEnd()
short CMonomer::activeSpeciesMinusEnd ()
Get the active species of the corresponding type.
Note
these functions will return -1 if the corresponding type has no marked species at this point.
Definition at line 141 of file CMonomer.cpp.
References _filamentType, _speciesFilament, _speciesFilamentIndex, areEqual(), SysParams::Chemistry(), Species::getN(), ChemParams::numMinusEndSpecies, and SPECIESMINUSEND.
Referenced by clone(), isConsistent(), and Filament::sever().
activeSpeciesMotor()
short CMonomer::activeSpeciesMotor ()
Get the active species of the corresponding type.
Note
these functions will return -1 if the corresponding type has no marked species at this point.
Definition at line 164 of file CMonomer.cpp.
References _filamentType, _speciesBound, _speciesBoundIndex, areEqual(), SysParams::Chemistry(), Species::getN(), ChemParams::numMotorSpecies, and SPECIESMOTOR.
Referenced by clone().
activeSpeciesPlusEnd()
short CMonomer::activeSpeciesPlusEnd ()
Get the active species of the corresponding type.
Note
these functions will return -1 if the corresponding type has no marked species at this point.
Definition at line 130 of file CMonomer.cpp.
References _filamentType, _speciesFilament, _speciesFilamentIndex, areEqual(), SysParams::Chemistry(), Species::getN(), ChemParams::numPlusEndSpecies, and SPECIESPLUSEND.
Referenced by clone(), isConsistent(), and BranchingPoint::~BranchingPoint().
clone()
virtual CMonomer* CMonomer::clone (Compartment * c) inline virtual
Clone a CMonomer. Transfers all CBounds to the new CMonomer.
Definition at line 76 of file CMonomer.h.
References activeSpeciesBrancher(), activeSpeciesFilament(), activeSpeciesLinker(), activeSpeciesMinusEnd(), activeSpeciesMotor(), activeSpeciesPlusEnd(), CMonomer(), isConsistent(), print(), speciesBound(), speciesBrancher(), speciesFilament(), speciesLinker(), speciesMinusEnd(), speciesMotor(), and speciesPlusEnd().
isConsistent()
bool CMonomer::isConsistent ()
Check the consistency of the CMonomer for debugging.
Definition at line 185 of file CMonomer.cpp.
References _filamentType, _numBSpecies, _numFSpecies, _speciesBoundIndex, _speciesFilament, _speciesFilamentIndex, activeSpeciesFilament(), activeSpeciesMinusEnd(), activeSpeciesPlusEnd(), areEqual(), Species::getN(), Species::getName(), and MAX_FILAMENT_TYPES.
Referenced by clone().
operator=()
CMonomer& CMonomer::operator= (CMonomer & rhs) delete
Assignment is not allowed.
print()
void CMonomer::print ()
Print the Species.
Definition at line 71 of file CMonomer.cpp.
References _filamentType, _numFSpecies, _speciesBound, _speciesFilament, areEqual(), Species::getN(), and Species::getName().
Referenced by clone().
speciesBound()
SpeciesBound * CMonomer::speciesBound (int index)
Get Species at a specific index.
Note
no check on this index. The index value of a species is stored in the chemical initializer when all reactions are initialized from the chemical input file.
Definition at line 100 of file CMonomer.cpp.
References _filamentType, _speciesBound, _speciesBoundIndex, and SPECIESBOUND.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), SeveringTemplate::addReaction(), CBranchingPoint::CBranchingPoint(), CLinker::CLinker(), clone(), CMotorGhost::CMotorGhost(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), ChemManager::initializeCCylinder(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), CMotorGhost::moveMotorHead(), Filament::nucleate(), Filament::sever(), and BranchingPoint::~BranchingPoint().
speciesBrancher()
SpeciesBound * CMonomer::speciesBrancher (int index)
Get Species at a specific index.
Note
no check on this index. The index value of a species is stored in the chemical initializer when all reactions are initialized from the chemical input file.
Definition at line 112 of file CMonomer.cpp.
References _filamentType, _speciesBound, _speciesBoundIndex, and SPECIESBRANCHER.
Referenced by CBranchingPoint::CBranchingPoint(), clone(), and CBranchingPoint::createOffReaction().
speciesFilament()
SpeciesFilament * CMonomer::speciesFilament (int index)
Get Species at a specific index.
Note
no check on this index. The index value of a species is stored in the chemical initializer when all reactions are initialized from the chemical input file.
Definition at line 87 of file CMonomer.cpp.
References _filamentType, _speciesFilament, _speciesFilamentIndex, and SPECIESFILAMENT.
Referenced by PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), AgingTemplate::addReaction(), SeveringTemplate::addReaction(), clone(), ChemManager::initializeCCylinder(), Filament::nucleate(), Filament::sever(), and BranchingPoint::~BranchingPoint().
speciesLinker()
SpeciesBound * CMonomer::speciesLinker (int index)
Get Species at a specific index.
Note
no check on this index. The index value of a species is stored in the chemical initializer when all reactions are initialized from the chemical input file.
Definition at line 104 of file CMonomer.cpp.
References _filamentType, _speciesBound, _speciesBoundIndex, and SPECIESLINKER.
Referenced by CLinker::CLinker(), and clone().
speciesMinusEnd()
SpeciesFilament * CMonomer::speciesMinusEnd (int index)
Get Species at a specific index.
Note
no check on this index. The index value of a species is stored in the chemical initializer when all reactions are initialized from the chemical input file.
Definition at line 95 of file CMonomer.cpp.
References _filamentType, _speciesFilament, _speciesFilamentIndex, and SPECIESMINUSEND.
Referenced by PolyMinusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), AgingTemplate::addReaction(), DestructionTemplate::addReaction(), clone(), Filament::extendMinusEnd(), ChemManager::initializeCCylinder(), Filament::nucleate(), Filament::sever(), and BranchingPoint::~BranchingPoint().
speciesMotor()
SpeciesBound * CMonomer::speciesMotor (int index)
Get Species at a specific index.
Note
no check on this index. The index value of a species is stored in the chemical initializer when all reactions are initialized from the chemical input file.
Definition at line 108 of file CMonomer.cpp.
References _filamentType, _speciesBound, _speciesBoundIndex, and SPECIESMOTOR.
Referenced by MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), clone(), CMotorGhost::CMotorGhost(), and CMotorGhost::moveMotorHead().
speciesPlusEnd()
SpeciesFilament * CMonomer::speciesPlusEnd (int index)
Get Species at a specific index.
Note
no check on this index. The index value of a species is stored in the chemical initializer when all reactions are initialized from the chemical input file.
Definition at line 91 of file CMonomer.cpp.
References _filamentType, _speciesFilament, _speciesFilamentIndex, and SPECIESPLUSEND.
Referenced by PolyPlusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), AgingTemplate::addReaction(), DestructionTemplate::addReaction(), clone(), Filament::extendPlusEnd(), ChemManager::initializeCCylinder(), Filament::nucleate(), and Filament::sever().
Friends And Related Function Documentation
CCylinder
friend class CCylinder friend
Definition at line 31 of file CMonomer.h.
ChemManager
friend class ChemManager friend
Definition at line 30 of file CMonomer.h.
Member Data Documentation
_filamentType
short CMonomer::_filamentType private
Filament type that this monomer is in.
Definition at line 41 of file CMonomer.h.
Referenced by activeSpeciesBrancher(), activeSpeciesFilament(), activeSpeciesLinker(), activeSpeciesMinusEnd(), activeSpeciesMotor(), activeSpeciesPlusEnd(), CMonomer(), isConsistent(), print(), speciesBound(), speciesBrancher(), speciesFilament(), speciesLinker(), speciesMinusEnd(), speciesMotor(), and speciesPlusEnd().
_numBSpecies
vector< short > CMonomer::_numBSpecies = vector<short>(MAX_FILAMENT_TYPES) static private
Definition at line 55 of file CMonomer.h.
Referenced by CMonomer(), ChemManager::configCMonomer(), isConsistent(), and CCylinder::~CCylinder().
_numFSpecies
vector< short > CMonomer::_numFSpecies = vector<short>(MAX_FILAMENT_TYPES) static private
Number of species for each filament type.
Definition at line 54 of file CMonomer.h.
Referenced by CMonomer(), ChemManager::configCMonomer(), isConsistent(), print(), and CCylinder::~CCylinder().
_speciesBound
SpeciesBound** CMonomer::_speciesBound private
Species array.
Definition at line 37 of file CMonomer.h.
Referenced by activeSpeciesBrancher(), activeSpeciesLinker(), activeSpeciesMotor(), CMonomer(), ChemManager::initCMonomer(), print(), speciesBound(), speciesBrancher(), speciesLinker(), speciesMotor(), and ~CMonomer().
_speciesBoundIndex
vector< vector< short > > CMonomer::_speciesBoundIndex = vector<vector<short>>(MAX_FILAMENT_TYPES) static private
Species index vectors These index vectors are used to access the correct species in the actual species arrays.
Each index in the species index vector corresponds to an offset for that species in the species array.
Note
- this is a 2D vector for different filament types.
Definition at line 50 of file CMonomer.h.
Referenced by activeSpeciesBrancher(), activeSpeciesLinker(), activeSpeciesMotor(), ChemManager::configCMonomer(), isConsistent(), speciesBound(), speciesBrancher(), speciesLinker(), and speciesMotor().
_speciesFilament
SpeciesFilament** CMonomer::_speciesFilament private
Species array.
Definition at line 36 of file CMonomer.h.
Referenced by activeSpeciesFilament(), activeSpeciesMinusEnd(), activeSpeciesPlusEnd(), CMonomer(), ChemManager::initCMonomer(), isConsistent(), print(), speciesFilament(), speciesMinusEnd(), speciesPlusEnd(), and ~CMonomer().
_speciesFilamentIndex
vector< vector< short > > CMonomer::_speciesFilamentIndex = vector<vector<short>>(MAX_FILAMENT_TYPES) static private
Species index vectors These index vectors are used to access the correct species in the actual species arrays.
Each index in the species index vector corresponds to an offset for that species in the species array.
Note
- this is a 2D vector for different filament types.
Definition at line 49 of file CMonomer.h.
Referenced by activeSpeciesFilament(), activeSpeciesMinusEnd(), activeSpeciesPlusEnd(), ChemManager::configCMonomer(), isConsistent(), speciesFilament(), speciesMinusEnd(), and speciesPlusEnd().
The documentation for this class was generated from the following files:
src/Structure/CMonomer.h
src/Structure/CMonomer.cpp