MEDYAN: BranchingPoint Class Reference
BranchingPoint Class Reference
A container to store a MBranchingPoint and CBranchingPoint.
#include <BranchingPoint.h>
Public Member Functions
BranchingPoint (Cylinder *c1, Cylinder *c2, short branchType, double position=0.5)
virtual ~BranchingPoint () noexcept
void setCBranchingPoint (CBranchingPoint *cBranchingPoint)
Set chem branch point.
CBranchingPoint * getCBranchingPoint ()
Get chem branch point.
MBranchingPoint * getMBranchingPoint ()
Get mech branch point.
Compartment * getCompartment ()
Get compartment.
float getBirthTime ()
Get the birth time.
virtual void updatePosition ()
Update the position, inherited from Movable.
virtual void printSelf ()
Prints information about this node. Useful for debugging.
virtual bool apply (Visitor &v)
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
virtual bool apply (SpeciesVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
virtual bool apply (ReactionVisitor &v)
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
virtual bool apply_impl (SpeciesVisitor &v)
Applies SpeciesVisitor v to every Species* object directly owned by this node.
virtual bool apply_impl (ReactionVisitor &v)
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
Composite * getParent ()
Returns the pointer to the parent node.
void setParent (Composite *other)
Sets the parent of this node to other.
bool isRoot () const
Returns true if this node is the root node.
Composite * getRoot ()
Returns the root node of the hieararchy to which this node belongs to.
virtual size_t numberOfChildren () const
Returns the number of children of this node.
virtual bool isComposite () const
Returns true if this node is a Composite node.
virtual bool isSpeciesContainer () const
Returns true if this node contains non-zero number of Species.
virtual bool isReactionsContainer () const
Returns true if this node contains non-zero number of reactions (i.e.
virtual size_t numberOfSpecies () const
Returns the number of Species being immediately managed by this node (i.e.
virtual size_t numberOfReactions () const
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
virtual string getFullName () const
Return a string indicating the full name of this node (presumably used mainly for debugging)
virtual size_t countDescendents () const
Return the total number of nodes contained under this node's hieararchy.
virtual size_t countSpecies () const
Return the number of Species contained under this node's hieararchy.
virtual size_t countReactions () const
Return the number of ReactionBase objects contained under this node's hieararchy.
Cylinder * getFirstCylinder ()
Get attached cylinder.
Cylinder * getSecondCylinder ()
Get attached cylinder.
double getPosition ()
Position management.
void setPosition (double position)
Position management.
virtual int getType ()
Get branch parameter.
int getID ()
Get branch parameter.
virtual void addToSubSystem ()
SubSystem management, inherited from Trackable.
virtual void removeFromSubSystem ()
SubSystem management, inherited from Trackable.
Static Public Member Functions
static const vector< BranchingPoint * > & getBranchingPoints ()
Get all instances of this class from the SubSystem.
static int numBranchingPoints ()
Get the number of branching points in this system.
static species_copy_t countSpecies (const string &name)
Count the number of brancher species with a given name in the system.
Public Attributes
vector< double > coordinate
coordinate of midpoint, updated with updatePosition()
Protected Attributes
bool _movable
Object type.
bool _reactable
Object type.
bool _dneighbor
Object type.
bool _neighbor
Object type.
Static Protected Attributes
static SubSystem * _subSystem = 0
A subsystem pointer for every trackable.
Private Member Functions
void updateCoordinate ()
Helper to get coordinate.
Private Attributes
unique_ptr< MBranchingPoint > _mBranchingPoint
Pointer to mech branch point.
unique_ptr< CBranchingPoint > _cBranchingPoint
Pointer to chem branch point.
Cylinder * _c1
Mother cylinder.
Cylinder * _c2
Branching cylinder.
double _position
Position on mother cylinder.
short _branchType
Integer specifying the type.
int _branchID
Integer ID of this specific branch point, managed by the Database.
float _birthTime
Birth time.
Compartment * _compartment
Where this branch point is.
Static Private Attributes
static Database< BranchingPoint * > _branchingPoints
Collection in SubSystem.
Detailed Description
A container to store a MBranchingPoint and CBranchingPoint.
BranchingPoint class is used to manage and store a MBranchingPoint and CBranchingPoint. Upon intialization, both of these components are created.
Extending the Movable class, the positions of all instances can be updated by the SubSystem.
Definition at line 39 of file BranchingPoint.h.
Constructor & Destructor Documentation
BranchingPoint()
BranchingPoint::BranchingPoint (Cylinder * c1, Cylinder * c2, short branchType, double position = 0.5)
Definition at line 37 of file BranchingPoint.cpp.
References _c1, _c2, _cBranchingPoint, _compartment, _mBranchingPoint, coordinate, SysParams::Geometry(), Cylinder::getCCylinder(), GController::getCompartment(), Cylinder::getType(), printSelf(), Cylinder::setBranchingCylinder(), and updateCoordinate().
~BranchingPoint()
BranchingPoint::~BranchingPoint () virtual noexcept
Definition at line 72 of file BranchingPoint.cpp.
References _c1, _c2, _compartment, Trackable::_subSystem, CMonomer::activeSpeciesFilament(), CMonomer::activeSpeciesPlusEnd(), SysParams::Chemistry(), Bead::coordinate, Species::down(), Compartment::findSpeciesByName(), SysParams::Geometry(), Cylinder::getCCylinder(), CCylinder::getCMonomer(), SubSystem::getCompartmentGrid(), Cylinder::getFirstBead(), Species::getName(), Component::getParent(), Cylinder::getType(), GeoParams::monomerSize, Rand::randDouble(), Rand::randInteger(), SubSystem::removeTrackable(), SpeciesNamesDB::removeUniqueFilName(), Cylinder::setBranchingCylinder(), CMonomer::speciesBound(), CMonomer::speciesFilament(), CMonomer::speciesMinusEnd(), Species::up(), and Species::updateReactantPropensities().
Member Function Documentation
addToSubSystem()
virtual void BranchingPoint::addToSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 108 of file BranchingPoint.h.
Referenced by getBirthTime().
apply() [1/3]
bool Component::apply (Visitor & v) virtual inherited
When this function is applied to a ConditionalVisitor v, the corresponding v.visit(this) is called, and v is further applied to all children of this node recursively.
However, the ConditionalVisitor allows the visit() function to be applied only selectively to nodes that conform to specific criteria.
Reimplemented in Composite.
Definition at line 26 of file Component.cpp.
References Visitor::visit().
Referenced by Component::~Component().
apply() [2/3]
virtual bool Component::apply (SpeciesVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain Species.
Reimplemented in Composite.
Definition at line 61 of file Component.h.
References Component::apply_impl().
apply() [3/3]
virtual bool Component::apply (ReactionVisitor & v) inline virtual inherited
Implements the apply_if() method of the Component class by recursively applying it to itself and all its children that contain ReactionBase.
Reimplemented in Composite.
Definition at line 69 of file Component.h.
References Component::apply_impl().
apply_impl() [1/2]
virtual bool Component::apply_impl (SpeciesVisitor & v) inline virtual inherited
Applies SpeciesVisitor v to every Species* object directly owned by this node.
This method needs to be overriden by descendent classes that contain Species.
Reimplemented in Compartment.
Definition at line 65 of file Component.h.
Referenced by Component::apply(), and Composite::apply().
apply_impl() [2/2]
virtual bool Component::apply_impl (ReactionVisitor & v) inline virtual inherited
Applies ReactionBaseVisitor v to every ReactionBase* object directly owned by this node.
This method needs to be overriden by descendent classes that contain ReactionBase.
Reimplemented in Compartment.
Definition at line 74 of file Component.h.
countDescendents()
virtual size_t Component::countDescendents () const inline virtual inherited
Return the total number of nodes contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 118 of file Component.h.
countReactions()
virtual size_t Component::countReactions () const inline virtual inherited
Return the number of ReactionBase objects contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 126 of file Component.h.
References Component::getType(), and Component::printSelf().
countSpecies() [1/2]
virtual size_t Component::countSpecies () const inline virtual inherited
Return the number of Species contained under this node's hieararchy.
Note
This is a recursive call, and all nodes under this node are visited.
Reimplemented in Composite.
Definition at line 122 of file Component.h.
Referenced by Linker::getLifetimes(), MotorGhost::getWalkLengths(), numBranchingPoints(), and Chemistry::print().
countSpecies() [2/2]
species_copy_t BranchingPoint::countSpecies (const string & name) static
Count the number of brancher species with a given name in the system.
Definition at line 219 of file BranchingPoint.cpp.
References _branchingPoints, Database< T >::getElements(), and SpeciesNamesDB::removeUniqueFilName().
getBirthTime()
float BranchingPoint::getBirthTime () inline
Get the birth time.
Definition at line 104 of file BranchingPoint.h.
References _birthTime, Database< T >::addElement(), and addToSubSystem().
getBranchingPoints()
static const vector<BranchingPoint*>& BranchingPoint::getBranchingPoints () inline static
Get all instances of this class from the SubSystem.
Definition at line 113 of file BranchingPoint.h.
References Database< T >::getElements().
Referenced by BranchingBending< BBendingInteractionType >::computeEnergy(), BranchingDihedral< BDihedralInteractionType >::computeEnergy(), BranchingPosition< BStretchingInteractionType >::computeEnergy(), BranchingStretching< BStretchingInteractionType >::computeEnergy(), BranchingPosition< BStretchingInteractionType >::computeForces(), BranchingBending< BBendingInteractionType >::computeForces(), BranchingDihedral< BDihedralInteractionType >::computeForces(), BranchingStretching< BStretchingInteractionType >::computeForces(), BranchingPosition< BStretchingInteractionType >::computeForcesAux(), BranchingBending< BBendingInteractionType >::computeForcesAux(), BranchingStretching< BStretchingInteractionType >::computeForcesAux(), BranchingDihedral< BDihedralInteractionType >::computeForcesAux(), BasicSnapshot::print(), BirthTimes::print(), Forces::print(), Tensions::print(), WallTensions::print(), Types::print(), and Controller::run().
getCBranchingPoint()
CBranchingPoint* BranchingPoint::getCBranchingPoint () inline
Get chem branch point.
Definition at line 83 of file BranchingPoint.h.
getCompartment()
Compartment* BranchingPoint::getCompartment () inline
Get compartment.
Definition at line 101 of file BranchingPoint.h.
References _compartment.
getFirstCylinder()
Cylinder* BranchingPoint::getFirstCylinder () inline
Get attached cylinder.
Definition at line 74 of file BranchingPoint.h.
getFullName()
virtual string Component::getFullName () const inline virtual inherited
Return a string indicating the full name of this node (presumably used mainly for debugging)
Reimplemented in Compartment, CompartmentGrid, and Composite.
Definition at line 114 of file Component.h.
getID()
int BranchingPoint::getID () inline
Get branch parameter.
Definition at line 97 of file BranchingPoint.h.
References _branchID.
getMBranchingPoint()
MBranchingPoint* BranchingPoint::getMBranchingPoint () inline
Get mech branch point.
Definition at line 86 of file BranchingPoint.h.
References _position, and getPosition().
getParent()
Composite* Component::getParent () inline inherited
Returns the pointer to the parent node.
The returned value could be a nullptr if a parent does not exist.
Definition at line 78 of file Component.h.
References Component::_parent.
Referenced by LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Bead::Bead(), Component::getRoot(), Bead::getType(), ChemManager::initializeCCylinder(), Controller::pinBoundaryFilaments(), CylinderCylinderNL::updateNeighbors(), Bead::updatePosition(), Cylinder::updatePosition(), and ~BranchingPoint().
getPosition()
double BranchingPoint::getPosition () inline
Position management.
Definition at line 90 of file BranchingPoint.h.
Referenced by getMBranchingPoint().
getRoot()
Composite * Component::getRoot () inherited
Returns the root node of the hieararchy to which this node belongs to.
Definition at line 19 of file Component.cpp.
References Component::getParent(), Component::getRoot(), and Component::isRoot().
Referenced by Component::getRoot(), ReactionBase::getRoot(), Species::getRoot(), and Component::isRoot().
getSecondCylinder()
Cylinder* BranchingPoint::getSecondCylinder () inline
Get attached cylinder.
Definition at line 75 of file BranchingPoint.h.
References _c2.
getType()
virtual int BranchingPoint::getType () inline virtual
Get branch parameter.
Implements Component.
Definition at line 96 of file BranchingPoint.h.
Referenced by setPosition().
isComposite()
virtual bool Component::isComposite () const inline virtual inherited
Returns true if this node is a Composite node.
Reimplemented in Composite.
Definition at line 95 of file Component.h.
isReactionsContainer()
virtual bool Component::isReactionsContainer () const inline virtual inherited
Returns true if this node contains non-zero number of reactions (i.e.
ReactionBase pointers)
Reimplemented in Compartment.
Definition at line 102 of file Component.h.
Referenced by Composite::countReactions().
isRoot()
bool Component::isRoot () const inline inherited
Returns true if this node is the root node.
A root node has no parent, and the corresponding getParent() call would return a nullptr.
Definition at line 85 of file Component.h.
References Component::getRoot().
Referenced by Component::getRoot().
isSpeciesContainer()
virtual bool Component::isSpeciesContainer () const inline virtual inherited
Returns true if this node contains non-zero number of Species.
Reimplemented in Compartment.
Definition at line 98 of file Component.h.
Referenced by Composite::countSpecies().
numberOfChildren()
virtual size_t Component::numberOfChildren () const inline virtual inherited
Returns the number of children of this node.
Note
Species and ReactionBase objects are not counted.
Reimplemented in Composite.
Definition at line 92 of file Component.h.
numberOfReactions()
virtual size_t Component::numberOfReactions () const inline virtual inherited
Returns the number of ReactionBase objets being immediately managed by this node (i.e.
not counting reactions belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 110 of file Component.h.
numberOfSpecies()
virtual size_t Component::numberOfSpecies () const inline virtual inherited
Returns the number of Species being immediately managed by this node (i.e.
not counting Species belonging to children nodes, etc.
Reimplemented in Compartment, and Composite.
Definition at line 106 of file Component.h.
numBranchingPoints()
static int BranchingPoint::numBranchingPoints () inline static
Get the number of branching points in this system.
Definition at line 117 of file BranchingPoint.h.
References Database< T >::countElements(), Component::countSpecies(), printSelf(), and updatePosition().
Referenced by BasicSnapshot::print(), BirthTimes::print(), Forces::print(), Tensions::print(), WallTensions::print(), and Types::print().
printSelf()
void BranchingPoint::printSelf () virtual
Prints information about this node. Useful for debugging.
Implements Component.
Definition at line 191 of file BranchingPoint.cpp.
References _birthTime, _branchID, _branchType, _c1, _c2, _cBranchingPoint, _position, coordinate, and Cylinder::printSelf().
Referenced by BranchingPoint(), numBranchingPoints(), updatePosition(), and BranchingFF::whoIsCulprit().
removeFromSubSystem()
virtual void BranchingPoint::removeFromSubSystem () inline virtual
SubSystem management, inherited from Trackable.
Implements Trackable.
Definition at line 109 of file BranchingPoint.h.
References Database< T >::removeElement().
setCBranchingPoint()
void BranchingPoint::setCBranchingPoint (CBranchingPoint * cBranchingPoint) inline
Set chem branch point.
Definition at line 79 of file BranchingPoint.h.
Referenced by updatePosition().
setParent()
void Component::setParent (Composite * other) inline inherited
Sets the parent of this node to other.
Definition at line 81 of file Component.h.
setPosition()
void BranchingPoint::setPosition (double position) inline
Position management.
Definition at line 91 of file BranchingPoint.h.
References _branchType, and getType().
updateCoordinate()
void BranchingPoint::updateCoordinate () private
Helper to get coordinate.
Definition at line 30 of file BranchingPoint.cpp.
References mathfunc::midPointCoordinate().
Referenced by BranchingPoint(), and updatePosition().
updatePosition()
void BranchingPoint::updatePosition () virtual
Update the position, inherited from Movable.
Note
- changes compartment if needed
Implements Movable.
Definition at line 156 of file BranchingPoint.cpp.
References _c1, _c2, _cBranchingPoint, _compartment, coordinate, Cylinder::getCCylinder(), GController::getCompartment(), printSelf(), setCBranchingPoint(), and updateCoordinate().
Referenced by numBranchingPoints().
Member Data Documentation
_birthTime
float BranchingPoint::_birthTime private
Birth time.
Definition at line 55 of file BranchingPoint.h.
Referenced by getBirthTime(), and printSelf().
_branchID
int BranchingPoint::_branchID private
Integer ID of this specific branch point, managed by the Database.
Definition at line 52 of file BranchingPoint.h.
Referenced by getID(), and printSelf().
_branchingPoints
Database< BranchingPoint * > BranchingPoint::_branchingPoints static private
Collection in SubSystem.
Definition at line 59 of file BranchingPoint.h.
Referenced by countSpecies().
_branchType
short BranchingPoint::_branchType private
Integer specifying the type.
Definition at line 50 of file BranchingPoint.h.
Referenced by printSelf(), and setPosition().
_c1
Cylinder* BranchingPoint::_c1 private
Mother cylinder.
Definition at line 45 of file BranchingPoint.h.
Referenced by BranchingPoint(), printSelf(), updatePosition(), and ~BranchingPoint().
_c2
Cylinder* BranchingPoint::_c2 private
Branching cylinder.
Definition at line 46 of file BranchingPoint.h.
Referenced by BranchingPoint(), getSecondCylinder(), printSelf(), updatePosition(), and ~BranchingPoint().
_cBranchingPoint
unique_ptr<CBranchingPoint> BranchingPoint::_cBranchingPoint private
Pointer to chem branch point.
Definition at line 43 of file BranchingPoint.h.
Referenced by BranchingPoint(), printSelf(), and updatePosition().
_compartment
Compartment* BranchingPoint::_compartment private
Where this branch point is.
Definition at line 57 of file BranchingPoint.h.
Referenced by BranchingPoint(), getCompartment(), updatePosition(), and ~BranchingPoint().
_dneighbor
bool Trackable::_dneighbor protected inherited
Object type.
Definition at line 54 of file Trackable.h.
_mBranchingPoint
unique_ptr<MBranchingPoint> BranchingPoint::_mBranchingPoint private
Pointer to mech branch point.
Definition at line 42 of file BranchingPoint.h.
Referenced by BranchingPoint().
_movable
bool Trackable::_movable protected inherited
Object type.
Definition at line 52 of file Trackable.h.
_neighbor
bool Trackable::_neighbor protected inherited
Object type.
Definition at line 55 of file Trackable.h.
_position
double BranchingPoint::_position private
Position on mother cylinder.
Definition at line 48 of file BranchingPoint.h.
Referenced by getMBranchingPoint(), and printSelf().
_reactable
bool Trackable::_reactable protected inherited
Object type.
Definition at line 53 of file Trackable.h.
_subSystem
SubSystem * Trackable::_subSystem = 0 static protected inherited
A subsystem pointer for every trackable.
Definition at line 46 of file Trackable.h.
Referenced by Controller::Controller(), and ~BranchingPoint().
coordinate
vector<double> BranchingPoint::coordinate
coordinate of midpoint, updated with updatePosition()
Definition at line 65 of file BranchingPoint.h.
Referenced by BranchingPoint(), printSelf(), and updatePosition().
The documentation for this class was generated from the following files:
src/Structure/BranchingPoint.h
src/Structure/BranchingPoint.cpp