MEDYAN: CylinderExclVolRepulsion Class Reference
CylinderExclVolRepulsion Class Reference
Represents a repulsive excluded volume potential used by the CylinderExclVolume template.
#include <CylinderExclVolRepulsion.h>
Public Member Functions
double energy (Bead *, Bead *, Bead *, Bead *, double Krepuls)
double energy (Bead *, Bead *, Bead *, Bead *, double Krepuls, double d)
void forces (Bead *, Bead *, Bead *, Bead *, double Krepuls)
void forcesAux (Bead *, Bead *, Bead *, Bead *, double Krepuls)
Detailed Description
Represents a repulsive excluded volume potential used by the CylinderExclVolume template.
Definition at line 24 of file CylinderExclVolRepulsion.h.
Member Function Documentation
energy() [1/2]
double CylinderExclVolRepulsion::energy (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double Krepuls)
Definition at line 42 of file CylinderExclVolRepulsion.cpp.
References mathfunc::areInPlane(), mathfunc::areParallel(), Bead::coordinate, mathfunc::movePointOutOfPlane(), mathfunc::scalarProduct(), and mathfunc::twoPointDistance().
energy() [2/2]
double CylinderExclVolRepulsion::energy (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double Krepuls, double d)
Definition at line 99 of file CylinderExclVolRepulsion.cpp.
References mathfunc::areInPlane(), mathfunc::areParallel(), Bead::coordinate, Bead::force, mathfunc::movePointOutOfPlane(), mathfunc::scalarProduct(), and mathfunc::twoPointDistance().
forces()
void CylinderExclVolRepulsion::forces (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double Krepuls)
Definition at line 175 of file CylinderExclVolRepulsion.cpp.
References mathfunc::areInPlane(), mathfunc::areParallel(), Bead::coordinate, Bead::force, mathfunc::movePointOutOfPlane(), mathfunc::scalarProduct(), and mathfunc::twoPointDistance().
forcesAux()
void CylinderExclVolRepulsion::forcesAux (Bead * b1, Bead * b2, Bead * b3, Bead * b4, double Krepuls)
Definition at line 312 of file CylinderExclVolRepulsion.cpp.
References mathfunc::areInPlane(), mathfunc::areParallel(), Bead::coordinate, Bead::forceAux, mathfunc::movePointOutOfPlane(), mathfunc::scalarProduct(), and mathfunc::twoPointDistance().
The documentation for this class was generated from the following files:
src/Mechanics/ForceField/Volume/CylinderExclVolRepulsion.h
src/Mechanics/ForceField/Volume/CylinderExclVolRepulsion.cpp