MEDYAN: ReactionBase Class Reference
ReactionBase Class Reference abstract
Represents an abstract interface for simple chemical reactions of the form A + B -> C.
#include <ReactionBase.h>
Public Member Functions
ReactionBase (float rate, bool isProtoCompartment)
The main constructor:
ReactionBase (const ReactionBase &rb)=delete
No copying (including all derived classes)
ReactionBase & operator= (ReactionBase &rb)=delete
no assignment (including all derived classes)
virtual ~ReactionBase () noexcept
Destructor.
ReactionBase * clone (const SpeciesPtrContainerVector &spcv)
Copy this reaction using SpeciesPtrContainerVector &spcv as a source of analogous Species.
virtual ReactionBase * cloneImpl (const SpeciesPtrContainerVector &spcv)=0
(Private) implementation of the clone() method to be elaborated in derived classes
virtual RSpecies ** rspecies ()=0
Returns a pointer to the first element of the array<RSpecies*>.
vector< string > getreactantspecies ()
void setReactionType (ReactionType rxnType)
Set reaction type.
ReactionType getReactionType ()
Get reaction type.
void setCBound (CBound *cBound)
Set CBound.
CBound * getCBound ()
Get CBound.
void setRate (float rate)
Sets the ReactionBase rate to the parameter "rate".
void setRnode (RNode *rhs)
Sets the RNode pointer associated with this ReactionBase to rhs.
RNode * getRNode ()
Get the RNode pointer.
float getRate () const
Returns the rate associated with this ReactionBase.
float getBareRate () const
Returns the bare rate associated with this ReactionBase.
void setBareRate (float a)
aravind June 24, 2016
RNode * getRnode () const
Returns a pointer to the RNode associated with this ReactionBase.
unsigned short getM () const
Returns the number of reactant RSpecies.
virtual unsigned short getMImpl () const =0
(Private) implementation of the getM() method to be elaborated in derived classes.
unsigned short getN () const
Returns the number of product RSpecies.
virtual unsigned short getNImpl () const =0
(Private) implementation of the getN() method to be elaborated in derived classes.
unsigned short size () const
Returns the total number of RSpecies.
virtual unsigned short sizeImpl () const =0
(Private) implementation of the size() method to be elaborated in derived classes.
Composite * getParent ()
Return the parent Composite object pointer, to which this Reaction belongs to.
void setParent (Composite *other)
Set the parent Composite object pointer to which this Reaction belongs to.
bool hasParent () const
Returns true if this Reaction has a parent Composite object to which it belongs to.
Composite * getRoot ()
Get the root parent (i.e.
double getProductOfReactants () const
Computes the product of the copy number of all reactant RSpecies.
virtual double getProductOfReactantsImpl () const =0
(Private) implementation of the getProductOfReactants() method to be elaborated in derived classes.
double getProductOfProducts () const
Computes the product of the copy number of all product RSpecies minus maximum allowed copy number.
virtual double getProductOfProductsImpl () const =0
(Private) implementation of the getProductOfProducts() method to be elaborated in derived classes.
bool isPassivated () const
Return true if the ReactionBase is currently passivated.
bool containsSpecies (Species *s) const
Returns true of this Reaction contains Species *s either as a reactant or a product.
virtual bool containsSpeciesImpl (Species *s) const =0
(Private) implementation of the containsSpecies() method to be elaborated in derived classes.
const unordered_set< ReactionBase * > & dependents ()
Return a const reference to the set of dependent ReactionBases.
virtual bool is_equal (const ReactionBase &b) const =0
(Private) implementation of the operator==(...) method to be elaborated in derived classes.
void makeStep ()
Fire the ReactionBase - make a single step, where reactant RSpecies copy numbers are decreased by one, and the product RSpecies copy numbers are increased by one.
virtual void makeStepImpl ()=0
(Private) implementation of the makeStep() method to be elaborated in derived classes.
double computePropensity () const
Compute the ReactionBase propensity that is needed by a Gillespie like algorithm, rate*reactant_1.getN()*reactant_2.getN()...
virtual double computePropensityImpl () const =0
(Private) implementation of the computePropensity() method to be elaborated in derived classes.
void passivateReaction ()
Usually is applied to ReactionBase objects with propensity of 0 (e.g.
virtual void passivateReactionImpl ()=0
(Private) implementation of the passivateReaction() method to be elaborated in derived classes.
void activateReactionUnconditional ()
Requests that ReactionBase objects that may affect this Reaction to start tracking it, which can be used to follow ReactionBase objects whose propensities change upong firing of some ReactionBase.
virtual void activateReactionUnconditionalImpl ()=0
void activateReaction ()
Requests that Reaction objects that may affect this Reaction to start tracking it, which can be used to follow Reaction objects whose propensities change upon firing of some Reaction.
void updatePropensity ()
Performs a simple updating of the propensity of this ReactionBase.
virtual void updatePropensityImpl ()=0
void printDependents ()
Print the ReactionBases that are affacted by this ReactionBase being fired.
virtual vector< ReactionBase * > getAffectedReactions ()=0
Return the list of ReactionBase objects that are affected when this ReactionBase is fired.
void registerNewDependent (ReactionBase *r)
Request that the ReactionBase *r adds this ReactionBase to its list of dependents which it affects.
void unregisterDependent (ReactionBase *r)
Request that the ReactionBase *r removes this ReactionBase from its list of dependents which it affects.
virtual void printToStream (ostream &os) const =0
virtual bool updateDependencies ()=0
Whether the dependencies should be updated.
Protected Attributes
unordered_set< ReactionBase * > _dependents
Pointers to ReactionBase objects that depend on this ReactionBase being executed.
RNode * _rnode
A pointer to an RNode object which is used to implement a Gillespie-like algorithm (e.g.
Composite * _parent
A pointer to a Composite object to which this Reaction belongs.
float _rate
the rate for this ReactionBase
float _rate_bare
the bare rate for this ReactionBase (original rate)
ReactionType _reactionType
Reaction type enumeration.
bool _isProtoCompartment = false
Reaction is in proto compartment (Do not copy as a dependent, not in ChemSim)
CBound * _cBound = nullptr
CBound that is attached to this reaction.
Friends
bool operator== (const ReactionBase &a, const ReactionBase &b)
Returns true if two ReactionBase objects are equal.
bool operator!= (const ReactionBase &a, const ReactionBase &b)
Return true if two ReactionBase are not equal.
ostream & operator<< (ostream &os, const ReactionBase &rr)
Print self into an iostream.
Detailed Description
Represents an abstract interface for simple chemical reactions of the form A + B -> C.
ReactionBase provides an interface for managing a chemical reaction. It is an abstract interface, so it cannot be directly instantiated, but other concrete classes may be derived from it. ReactionBase may have a composite object as a parent. A signaling interface may be used to make callbacks when some event, such as a single reaction step, has been executed. The ReactionBase indicates a forward process only. For processes in both directions, e.g. A <-> B, two ReactionBases objects need to be defined, corresponding to A->B and B->A. A ReactionBase tracks other ReactionBase objects that are affected if this ReactionBase is executed. A ReactionBase may be set up such that it "signals" when a ReactionBase event happens, in which case the corresponding callbacks are called.
Definition at line 73 of file ReactionBase.h.
Constructor & Destructor Documentation
ReactionBase() [1/2]
ReactionBase::ReactionBase (float rate, bool isProtoCompartment)
The main constructor:
Parameters
rate - the rate constant for this ReactionBase
Definition at line 18 of file ReactionBase.cpp.
ReactionBase() [2/2]
ReactionBase::ReactionBase (const ReactionBase & rb) delete
No copying (including all derived classes)
~ReactionBase()
virtual ReactionBase::~ReactionBase () inline virtual noexcept
Destructor.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 116 of file ReactionBase.h.
Member Function Documentation
activateReaction()
void ReactionBase::activateReaction () inline
Requests that Reaction objects that may affect this Reaction to start tracking it, which can be used to follow Reaction objects whose propensities change upon firing of some Reaction.
This request will be ignored if the Reaction's propensity is still zero.
Definition at line 345 of file ReactionBase.h.
References activateReactionUnconditional(), areEqual(), getProductOfProducts(), and getProductOfReactants().
Referenced by CCylinder::addCrossCylinderReaction(), CCylinder::addInternalReaction(), and MotorGhost::updateReactionRates().
activateReactionUnconditional()
void ReactionBase::activateReactionUnconditional () inline
Requests that ReactionBase objects that may affect this Reaction to start tracking it, which can be used to follow ReactionBase objects whose propensities change upong firing of some ReactionBase.
This request is acted upon unconditionally.
Definition at line 337 of file ReactionBase.h.
References activateReactionUnconditionalImpl().
Referenced by activateReaction().
activateReactionUnconditionalImpl()
virtual void ReactionBase::activateReactionUnconditionalImpl () pure virtual
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by activateReactionUnconditional().
clone()
ReactionBase* ReactionBase::clone (const SpeciesPtrContainerVector & spcv) inline
Copy this reaction using SpeciesPtrContainerVector &spcv as a source of analogous Species.
Returns
the cloned ReactionBase pointer.
Note
the receving object should take care of the memory management of the returned pointer
Definition at line 123 of file ReactionBase.h.
References cloneImpl(), and rspecies().
Referenced by CCylinder::CCylinder().
cloneImpl()
virtual ReactionBase* ReactionBase::cloneImpl (const SpeciesPtrContainerVector & spcv) pure virtual
(Private) implementation of the clone() method to be elaborated in derived classes
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by clone().
computePropensity()
double ReactionBase::computePropensity () const inline
Compute the ReactionBase propensity that is needed by a Gillespie like algorithm, rate*reactant_1.getN()*reactant_2.getN()...
Definition at line 316 of file ReactionBase.h.
References computePropensityImpl().
Referenced by ChemSimpleGillespieImpl::makeStep(), Reaction< 1, 1 >::printToStream(), RNodeGillespie::reComputePropensity(), RNodeGillespie::reset(), and RNodeNRM::RNodeNRM().
computePropensityImpl()
virtual double ReactionBase::computePropensityImpl () const pure virtual
(Private) implementation of the computePropensity() method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by computePropensity().
containsSpecies()
bool ReactionBase::containsSpecies (Species * s) const inline
Returns true of this Reaction contains Species *s either as a reactant or a product.
Definition at line 236 of file ReactionBase.h.
References containsSpeciesImpl().
containsSpeciesImpl()
virtual bool ReactionBase::containsSpeciesImpl (Species * s) const pure virtual
(Private) implementation of the containsSpecies() method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by containsSpecies().
dependents()
const unordered_set<ReactionBase*>& ReactionBase::dependents () inline
Return a const reference to the set of dependent ReactionBases.
Note
One can obtain two different lists of affected ReactionBases: 1) via getAffectedReactionBases(), where the copy numbers do influence the dependencies, and 2) via dependents(), where dependencies stop being counted if the copy numbers of reactant species drop to 0.
Definition at line 279 of file ReactionBase.h.
References _dependents.
Referenced by ChemGillespieImpl::makeStep(), ChemNRMImpl::makeStep(), RNodeGillespie::printDependents(), and RNodeNRM::printDependents().
getAffectedReactions()
virtual vector<ReactionBase*> ReactionBase::getAffectedReactions () pure virtual
Return the list of ReactionBase objects that are affected when this ReactionBase is fired.
Returns
a vector of pointers to the affected ReactionBase objects
Note
This method is "expensive" because it computes from scratch the dependencies. Importantly, the copy numbers of molecules do not influence the result of this function.
See also
dependents()
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by updatePropensity().
getBareRate()
float ReactionBase::getBareRate () const inline
Returns the bare rate associated with this ReactionBase.
Definition at line 166 of file ReactionBase.h.
References _rate_bare.
Referenced by Linker::updateReactionRates().
getCBound()
CBound* ReactionBase::getCBound () inline
Get CBound.
Definition at line 151 of file ReactionBase.h.
References _cBound.
Referenced by CCylinder::CCylinder().
getM()
unsigned short ReactionBase::getM () const inline
Returns the number of reactant RSpecies.
Definition at line 174 of file ReactionBase.h.
References getMImpl().
getMImpl()
virtual unsigned short ReactionBase::getMImpl () const pure virtual
(Private) implementation of the getM() method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by getM().
getN()
unsigned short ReactionBase::getN () const inline
Returns the number of product RSpecies.
Definition at line 180 of file ReactionBase.h.
References getNImpl().
Referenced by Reaction< 1, 1 >::getProductOfReactantsImpl().
getNImpl()
virtual unsigned short ReactionBase::getNImpl () const pure virtual
(Private) implementation of the getN() method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by getN().
getParent()
Composite* ReactionBase::getParent () inline
Return the parent Composite object pointer, to which this Reaction belongs to.
If not present, return a nullptr.
Definition at line 193 of file ReactionBase.h.
References _parent.
Referenced by getRoot().
getProductOfProducts()
double ReactionBase::getProductOfProducts () const inline
Computes the product of the copy number of all product RSpecies minus maximum allowed copy number.
Can be used to quickly determine whether this ReactionBase should be allowed to activate - if one of the products has a copy number equal to the maximum allowed, then zero is returned, indicating that this ReactionBase should not be (yet) activated.
Definition at line 221 of file ReactionBase.h.
References getProductOfProductsImpl(), and isPassivated().
Referenced by activateReaction().
getProductOfProductsImpl()
virtual double ReactionBase::getProductOfProductsImpl () const pure virtual
(Private) implementation of the getProductOfProducts() method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by getProductOfProducts().
getProductOfReactants()
double ReactionBase::getProductOfReactants () const inline
Computes the product of the copy number of all reactant RSpecies.
Can be used to quickly determine whether this ReactionBase should be allowed to activate - if one of the reactants has a copy number equal to zero, then zero is returned, indicating that this ReactionBase should not be (yet) activated.
Definition at line 210 of file ReactionBase.h.
References getProductOfReactantsImpl().
Referenced by activateReaction().
getProductOfReactantsImpl()
virtual double ReactionBase::getProductOfReactantsImpl () const pure virtual
(Private) implementation of the getProductOfReactants() method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by getProductOfReactants().
getRate()
float ReactionBase::getRate () const inline
Returns the rate associated with this ReactionBase.
Definition at line 163 of file ReactionBase.h.
References _rate.
Referenced by Reaction< 1, 1 >::printToStream().
getreactantspecies()
vector<string> ReactionBase::getreactantspecies () inline
Definition at line 136 of file ReactionBase.h.
References rspecies().
Referenced by FilamentBindingManager::getrxnspecies().
getReactionType()
ReactionType ReactionBase::getReactionType () inline
Get reaction type.
Definition at line 146 of file ReactionBase.h.
References _reactionType.
Referenced by ChemNRMImpl::makeStep().
getRNode()
RNode* ReactionBase::getRNode () inline
Get the RNode pointer.
Definition at line 160 of file ReactionBase.h.
References _rnode.
getRnode()
RNode* ReactionBase::getRnode () const inline
Returns a pointer to the RNode associated with this ReactionBase.
Definition at line 171 of file ReactionBase.h.
References _rnode.
getRoot()
Composite * ReactionBase::getRoot ()
Get the root parent (i.e.
follow the pointers of parentage until the root node in the Composition hieararchy)
Definition at line 29 of file ReactionBase.cpp.
References getParent(), Component::getRoot(), and hasParent().
Referenced by hasParent().
hasParent()
bool ReactionBase::hasParent () const inline
Returns true if this Reaction has a parent Composite object to which it belongs to.
Definition at line 200 of file ReactionBase.h.
References getRoot().
Referenced by getRoot().
is_equal()
virtual bool ReactionBase::is_equal (const ReactionBase & b) const pure virtual
(Private) implementation of the operator==(...) method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
isPassivated()
bool ReactionBase::isPassivated () const inline
Return true if the ReactionBase is currently passivated.
Definition at line 231 of file ReactionBase.h.
Referenced by Reaction< 1, 1 >::computePropensityImpl(), getProductOfProducts(), and RNodeGillespie::isPassivated().
makeStep()
void ReactionBase::makeStep () inline
Fire the ReactionBase - make a single step, where reactant RSpecies copy numbers are decreased by one, and the product RSpecies copy numbers are increased by one.
Note
This method does not send a ReactionBase event Signal. The latter is usually done from within a Gillespie-like algorithm.
Definition at line 308 of file ReactionBase.h.
References makeStepImpl().
Referenced by RNodeGillespie::makeStep(), and ChemSimpleGillespieImpl::makeStep().
makeStepImpl()
virtual void ReactionBase::makeStepImpl () pure virtual
(Private) implementation of the makeStep() method to be elaborated in derived classes.
Implemented in DiffusionReaction, Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by makeStep().
operator=()
ReactionBase& ReactionBase::operator= (ReactionBase & rb) delete
no assignment (including all derived classes)
passivateReaction()
void ReactionBase::passivateReaction () inline
Usually is applied to ReactionBase objects with propensity of 0 (e.g.
when one of the copy numbers of reactants has dropped to 0. This method call notifies all other ReactionBase objects that may affect this ReactionBase to stop tracking this ReactionBase. Eventually, activateReaction() may be called to restart tracking, if the propensity stops being 0.
Definition at line 327 of file ReactionBase.h.
References passivateReactionImpl().
Referenced by CCylinder::removeCrossCylinderReaction(), and CCylinder::removeInternalReaction().
passivateReactionImpl()
virtual void ReactionBase::passivateReactionImpl () pure virtual
(Private) implementation of the passivateReaction() method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by passivateReaction().
printDependents()
void ReactionBase::printDependents ()
Print the ReactionBases that are affacted by this ReactionBase being fired.
Definition at line 56 of file ReactionBase.cpp.
References _dependents.
Referenced by updatePropensity().
printToStream()
virtual void ReactionBase::printToStream (ostream & os) const pure virtual
Implemented in Reaction< M, N >.
Referenced by updatePropensity().
registerNewDependent()
void ReactionBase::registerNewDependent (ReactionBase * r)
Request that the ReactionBase *r adds this ReactionBase to its list of dependents which it affects.
Definition at line 35 of file ReactionBase.cpp.
References _dependents.
Referenced by updatePropensity().
rspecies()
virtual RSpecies** ReactionBase::rspecies () pure virtual
Returns a pointer to the first element of the array<RSpecies*>.
This pointer can be used to iterate over RSpecies* if necessary (also by relying on getM() and size() to determine the iteration limits). The corresponding array<RSpecies*> is defined by the derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by BranchingManager::BranchingManager(), clone(), CBranchingPoint::createOffReaction(), CLinker::createOffReaction(), CMotorGhost::createOffReaction(), getreactantspecies(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), and CMotorGhost::moveMotorHead().
setBareRate()
void ReactionBase::setBareRate (float a) inline
aravind June 24, 2016
Definition at line 169 of file ReactionBase.h.
setCBound()
void ReactionBase::setCBound (CBound * cBound) inline
Set CBound.
Definition at line 149 of file ReactionBase.h.
Referenced by CBound::setOffReaction().
setParent()
void ReactionBase::setParent (Composite * other) inline
Set the parent Composite object pointer to which this Reaction belongs to.
Definition at line 196 of file ReactionBase.h.
Referenced by CompartmentGrid::addBulk(), CompartmentGrid::addBulkReaction(), CompartmentGrid::addBulkReactionUnique(), Compartment::addDiffusionReaction(), Compartment::addDiffusionReactionUnique(), Compartment::addInternal(), Compartment::addInternalReaction(), and Compartment::addInternalReactionUnique().
setRate()
void ReactionBase::setRate (float rate) inline
Sets the ReactionBase rate to the parameter "rate".
Definition at line 154 of file ReactionBase.h.
Referenced by Reaction< 1, 1 >::cloneImpl(), Linker::updateReactionRates(), and MotorGhost::updateReactionRates().
setReactionType()
void ReactionBase::setReactionType (ReactionType rxnType) inline
Set reaction type.
Definition at line 143 of file ReactionBase.h.
Referenced by PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), AgingTemplate::addReaction(), DestructionTemplate::addReaction(), SeveringTemplate::addReaction(), CLinker::createOffReaction(), CBranchingPoint::createOffReaction(), CMotorGhost::createOffReaction(), ChemManager::genBulkReactions(), ChemManager::genFilBindingReactions(), ChemManager::genGeneralReactions(), ChemManager::genNucleationReactions(), and CMotorGhost::moveMotorHead().
setRnode()
void ReactionBase::setRnode (RNode * rhs) inline
Sets the RNode pointer associated with this ReactionBase to rhs.
Usually is called only by the Gillespie-like algorithms.
Definition at line 158 of file ReactionBase.h.
Referenced by RNodeGillespie::RNodeGillespie(), RNodeNRM::RNodeNRM(), RNodeGillespie::~RNodeGillespie(), and RNodeNRM::~RNodeNRM().
size()
unsigned short ReactionBase::size () const inline
Returns the total number of RSpecies.
Definition at line 186 of file ReactionBase.h.
References sizeImpl().
Referenced by Reaction< 1, 1 >::Reaction(), DiffusionReaction::updatePropensityImpl(), and DiffusionReaction::~DiffusionReaction().
sizeImpl()
virtual unsigned short ReactionBase::sizeImpl () const pure virtual
(Private) implementation of the size() method to be elaborated in derived classes.
Implemented in Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by size().
unregisterDependent()
void ReactionBase::unregisterDependent (ReactionBase * r)
Request that the ReactionBase *r removes this ReactionBase from its list of dependents which it affects.
This is usually requested when the ReactionBase propensity drops to zero (i.e. via passivateReactionBase()).
Definition at line 37 of file ReactionBase.cpp.
References _dependents.
Referenced by updatePropensity().
updateDependencies()
virtual bool ReactionBase::updateDependencies () pure virtual
Whether the dependencies should be updated.
Implemented in DiffusionReaction, Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by ChemGillespieImpl::makeStep(), and ChemNRMImpl::makeStep().
updatePropensity()
void ReactionBase::updatePropensity () inline
Performs a simple updating of the propensity of this ReactionBase.
Does not change dependents, only updates the RNode if initialized.
Definition at line 361 of file ReactionBase.h.
References getAffectedReactions(), printDependents(), printToStream(), registerNewDependent(), unregisterDependent(), and updatePropensityImpl().
Referenced by FilamentBindingManager::updateBindingReaction(), and Linker::updateReactionRates().
updatePropensityImpl()
virtual void ReactionBase::updatePropensityImpl () pure virtual
Implemented in DiffusionReaction, Reaction< M, N >, and Reaction< 1, 1 >.
Referenced by updatePropensity().
Friends And Related Function Documentation
operator!=
bool operator!= (const ReactionBase & a, const ReactionBase & b) friend
Return true if two ReactionBase are not equal.
See also
operator ==(const ReactionBase& a, const ReactionBase& b) above
Definition at line 299 of file ReactionBase.h.
operator<<
ostream& operator<< (ostream & os, const ReactionBase & rr) friend
Print self into an iostream.
Definition at line 389 of file ReactionBase.h.
operator==
bool operator== (const ReactionBase & a, const ReactionBase & b) friend
Returns true if two ReactionBase objects are equal.
Two ReactionBase objects are equal if each of their reactants and products are equal
Definition at line 284 of file ReactionBase.h.
Member Data Documentation
_cBound
CBound* ReactionBase::_cBound = nullptr protected
CBound that is attached to this reaction.
Definition at line 98 of file ReactionBase.h.
Referenced by getCBound().
_dependents
unordered_set<ReactionBase*> ReactionBase::_dependents protected
Pointers to ReactionBase objects that depend on this ReactionBase being executed.
Definition at line 75 of file ReactionBase.h.
Referenced by dependents(), Reaction< 1, 1 >::initializeSpecies(), printDependents(), registerNewDependent(), and unregisterDependent().
_isProtoCompartment
bool ReactionBase::_isProtoCompartment = false protected
Reaction is in proto compartment (Do not copy as a dependent, not in ChemSim)
Definition at line 95 of file ReactionBase.h.
Referenced by Reaction< 1, 1 >::initializeSpecies().
_parent
Composite* ReactionBase::_parent protected
A pointer to a Composite object to which this Reaction belongs.
Definition at line 81 of file ReactionBase.h.
Referenced by getParent().
_rate
float ReactionBase::_rate protected
the rate for this ReactionBase
Definition at line 84 of file ReactionBase.h.
Referenced by Reaction< 1, 1 >::computePropensityImpl(), and getRate().
_rate_bare
float ReactionBase::_rate_bare protected
the bare rate for this ReactionBase (original rate)
Definition at line 85 of file ReactionBase.h.
Referenced by getBareRate().
_reactionType
ReactionType ReactionBase::_reactionType protected
Reaction type enumeration.
Definition at line 93 of file ReactionBase.h.
Referenced by Reaction< 1, 1 >::cloneImpl(), DiffusionReaction::DiffusionReaction(), and getReactionType().
_rnode
RNode* ReactionBase::_rnode protected
A pointer to an RNode object which is used to implement a Gillespie-like algorithm (e.g.
NRM)
Definition at line 78 of file ReactionBase.h.
Referenced by getRNode(), getRnode(), and DiffusionReaction::updatePropensityImpl().
The documentation for this class was generated from the following files:
src/Chemistry/ReactionBase.h
src/Chemistry/ReactionBase.cpp