MEDYAN: ReactionVisitor Class Reference
ReactionVisitor Class Reference abstract
The Visitor pattern allows a functor to visit each node of the Composite pattern.
#include <Visitor.h>
Public Member Functions
bool visit (ReactionBase *r)
When this Visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(s), for each of the Reaction *r of that node.
virtual ~ReactionVisitor ()
Virtual destructor.
Protected Member Functions
virtual bool visitImpl (ReactionBase *r)=0
When this Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
virtual bool predImpl (ReactionBase *r)=0
Return true if the Reaction *r satisfies the desired predicate.
Detailed Description
The Visitor pattern allows a functor to visit each node of the Composite pattern.
Concrete classes derived from Visitor must implement the visit(Component *c) method.
Definition at line 158 of file Visitor.h.
Constructor & Destructor Documentation
~ReactionVisitor()
virtual ReactionVisitor::~ReactionVisitor () inline virtual
Virtual destructor.
Definition at line 172 of file Visitor.h.
References Visitor::predImpl(), and Visitor::visitImpl().
Member Function Documentation
predImpl()
virtual bool ReactionVisitor::predImpl (ReactionBase * r) protected pure virtual
Return true if the Reaction *r satisfies the desired predicate.
Implemented in ReactionVisitorLambda.
visit()
bool ReactionVisitor::visit (ReactionBase * r) inline
When this Visitor, *v, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: v->visit(s), for each of the Reaction *r of that node.
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Definition at line 165 of file Visitor.h.
References Visitor::predImpl(), and Visitor::visitImpl().
Referenced by Compartment::apply_impl().
visitImpl()
virtual bool ReactionVisitor::visitImpl (ReactionBase * r) protected pure virtual
When this Visitor, *cv, is propagated through the Composite hieararchy, at each Component node pointer *c, the following method is called: cv->visit(c).
If a false value is returned from this function called, then the further propagation of the tree is terminated.
Implemented in ReactionVisitorLambda.
The documentation for this class was generated from the following file:
src/Visitor.h