M3Sym: SimpleManagerImpl Class Reference
SimpleManagerImpl Class Reference
A concrete implementation of the ChemManagerImpl class.
#include <SimpleManagerImpl.h>
Public Member Functions
SimpleManagerImpl (SubSystem *subSystem)
Constructor sets subsystem pointer.
virtual void initialize (ChemistryData &chem)
virtual void initializeCCylinder (CCylinder *cc, Filament *f, bool extensionFront, bool extensionBack, bool creation)
virtual void updateCCylinder (CCylinder *cc)
Private Member Functions
void genGeneralReactions (ChemistryData &chem, Compartment &protoCompartment)
Generate the general, non-filament reactions.
void genBulkReactions (ChemistryData &chem)
Generate bulk reactions.
void genIFRxnManagers (ChemistryData &chem)
Set up all reaction managers from the setup struct.
void genCFRxnManagers (ChemistryData &chem)
Set up all reaction managers from the setup struct.
Private Attributes
SubSystem * _subSystem
A pointer to subsytem for creation of callbacks, etc.
vector< unique_ptr
< InternalFilamentRxnManager > > _IFRxnManagers
A list of reactions to add to every new CCylinder.
vector< unique_ptr
< CrossFilamentRxnManager > > _CFRxnManagers
A list of cross filament reactions to add to CCylinders.
vector< string > _speciesFilament
Vector of Filament -related species in system.
vector< string > _speciesPlusEnd
Vector of Filament -related species in system.
vector< string > _speciesMinusEnd
Vector of Filament -related species in system.
vector< string > _speciesBound
Vector of Filament -related species in system.
vector< string > _speciesLinker
Vector of Filament -related species in system.
vector< string > _speciesMotor
Vector of Filament -related species in system.
Detailed Description
A concrete implementation of the ChemManagerImpl class.
See also
ChemManager for documentation on implemented methods.
Definition at line 32 of file SimpleManagerImpl.h.
Constructor & Destructor Documentation
SimpleManagerImpl::SimpleManagerImpl (SubSystem * subSystem) inline
Constructor sets subsystem pointer.
Definition at line 63 of file SimpleManagerImpl.h.
Member Function Documentation
void SimpleManagerImpl::genBulkReactions (ChemistryData & chem) private
Generate bulk reactions.
Definition at line 1274 of file SimpleManagerImpl.cpp.
References CompartmentGrid::addBulkReactionUnique(), ChemistryData::bulkReactions, CompartmentGrid::instance(), and ChemistryData::speciesBulk.
void SimpleManagerImpl::genCFRxnManagers (ChemistryData & chem) private
Set up all reaction managers from the setup struct.
Definition at line 829 of file SimpleManagerImpl.cpp.
References BOUND, BULK, DIFFUSING, SpeciesNamesDB::Instance(), LINKER, LINKERBINDING, ChemistryData::linkerBindingReactions, MOTOR, MOTORBINDING, ChemistryData::motorBindingReactions, ChemistryData::speciesBulk, and ChemistryData::speciesDiffusing.
void SimpleManagerImpl::genGeneralReactions (ChemistryData & chem, Compartment & protoCompartment) private
Generate the general, non-filament reactions.
Definition at line 1156 of file SimpleManagerImpl.cpp.
References Compartment::addInternalReactionUnique(), Compartment::findSpeciesByName(), ChemistryData::genReactions, CompartmentGrid::instance(), ChemistryData::speciesBulk, and ChemistryData::speciesDiffusing.
void SimpleManagerImpl::genIFRxnManagers (ChemistryData & chem) private
Set up all reaction managers from the setup struct.
Definition at line 26 of file SimpleManagerImpl.cpp.
References BACKWARD, ChemistryData::bindingReactions, BOUND, BULK, ChemistryData::depolymerizationReactions, DIFFUSING, FILAMENT, FORWARD, SpeciesNamesDB::Instance(), LINKER, MINUSEND, MOTOR, MOTORWALKINGBACKWARD, MOTORWALKINGFORWARD, ChemistryData::motorWalkingReactions, PLUSEND, ChemistryData::polymerizationReactions, ChemistryData::speciesBulk, ChemistryData::speciesDiffusing, and ChemistryData::unbindingReactions.
void SimpleManagerImpl::initialize (ChemistryData & chem) virtual
Implements ChemManagerImpl.
Definition at line 1365 of file SimpleManagerImpl.cpp.
References InternalFilamentRxnManager::_ps, CrossFilamentRxnManager::_ps, CompartmentGrid::addChemSimReactions(), CompartmentGrid::addSpeciesBulk(), Compartment::addSpeciesUnique(), A_B_C_Cycle::C, Composite::children(), Compartment::generateAllDiffusionReactions(), CompartmentGrid::getProtoCompartment(), CompartmentGrid::instance(), ChemistryData::speciesBound, ChemistryData::speciesBulk, ChemistryData::speciesDiffusing, ChemistryData::speciesFilament, ChemistryData::speciesLinker, ChemistryData::speciesMinusEnd, ChemistryData::speciesMotor, and ChemistryData::speciesPlusEnd.
void SimpleManagerImpl::initializeCCylinder (CCylinder * cc, Filament * f, bool extensionFront, bool extensionBack, bool creation) virtual
Implements ChemManagerImpl.
Definition at line 1414 of file SimpleManagerImpl.cpp.
References CCylinder::addCMonomer(), CMonomer::addSpeciesBound(), Compartment::addSpeciesBound(), CMonomer::addSpeciesFilament(), Compartment::addSpeciesFilament(), CMonomer::addSpeciesLinker(), Compartment::addSpeciesLinker(), CMonomer::addSpeciesMinusEnd(), Compartment::addSpeciesMinusEnd(), CMonomer::addSpeciesMotor(), Compartment::addSpeciesMotor(), CMonomer::addSpeciesPlusEnd(), Compartment::addSpeciesPlusEnd(), CCylinder::getCMonomer(), CCylinder::getCompartment(), Filament::getCylinderVector(), Species::getRSpecies(), CCylinder::getSize(), SpeciesNamesDB::Instance(), RSpecies::setN(), CMonomer::speciesBound(), CMonomer::speciesFilament(), CMonomer::speciesMinusEnd(), and CMonomer::speciesPlusEnd().
void SimpleManagerImpl::updateCCylinder (CCylinder * cc) virtual
Implements ChemManagerImpl.
Definition at line 1530 of file SimpleManagerImpl.cpp.
References CCylinder::getCrossCylinderReactions(), CCylinder::getCylinder(), Cylinder::getFilament(), and CCylinder::removeCrossCylinderReactions().
Member Data Documentation
vector<unique_ptr<CrossFilamentRxnManager> > SimpleManagerImpl::_CFRxnManagers private
A list of cross filament reactions to add to CCylinders.
Definition at line 40 of file SimpleManagerImpl.h.
vector<unique_ptr<InternalFilamentRxnManager> > SimpleManagerImpl::_IFRxnManagers private
A list of reactions to add to every new CCylinder.
Definition at line 38 of file SimpleManagerImpl.h.
vector<string> SimpleManagerImpl::_speciesBound private
Vector of Filament -related species in system.
Definition at line 44 of file SimpleManagerImpl.h.
vector<string> SimpleManagerImpl::_speciesFilament private
Vector of Filament -related species in system.
Definition at line 44 of file SimpleManagerImpl.h.
vector<string> SimpleManagerImpl::_speciesLinker private
Vector of Filament -related species in system.
Definition at line 44 of file SimpleManagerImpl.h.
vector<string> SimpleManagerImpl::_speciesMinusEnd private
Vector of Filament -related species in system.
Definition at line 44 of file SimpleManagerImpl.h.
vector<string> SimpleManagerImpl::_speciesMotor private
Vector of Filament -related species in system.
Definition at line 44 of file SimpleManagerImpl.h.
vector<string> SimpleManagerImpl::_speciesPlusEnd private
Vector of Filament -related species in system.
Definition at line 44 of file SimpleManagerImpl.h.
SubSystem* SimpleManagerImpl::_subSystem private
A pointer to subsytem for creation of callbacks, etc.
Definition at line 35 of file SimpleManagerImpl.h.
The documentation for this class was generated from the following files:
M3SYM/Chemistry/SimpleManagerImpl.h
M3SYM/Chemistry/SimpleManagerImpl.cpp