MEDYAN: RSpecies Class Reference
RSpecies Class Reference abstract
Represents the reactive aspect of chemical molecules.
#include <RSpecies.h>
Public Member Functions
void setN (species_copy_t n)
Sets the copy number for this RSpecies.
void addAsReactant (ReactionBase *r)
void addAsProduct (ReactionBase *r)
void removeAsReactant (const ReactionBase *r)
void removeAsProduct (const ReactionBase *r)
void activateAssocReactantReactions ()
void activateAssocProductReactions ()
void passivateAssocReactantReactions ()
void passivateAssocProductReactions ()
virtual ~RSpecies () noexcept
It is required that all Reactions associated with this RSpecies are destructed before this RSpecies is destructed.
Species & getSpecies ()
return parent Species as a reference
const Species & getSpecies () const
return parent Species as a const reference
string getFullName () const
Return the full name of this Species in a string format (e.g. "Arp2/3{Bulk}")
vector< ReactionBase * > & reactantReactions ()
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Reactant.
vector< ReactionBase * > & productReactions ()
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Product.
vr_iterator beginReactantReactions ()
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Reactant.
vr_iterator beginProductReactions ()
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Product.
vr_iterator endReactantReactions ()
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Reactant.
vr_iterator endProductReactions ()
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Product.
virtual void up ()=0
Increases the copy number of this RSpecies.
virtual void down ()=0
Decreases the copy number of this RSpecies.
virtual float getN () const =0
Return the effective copy number of this RSpecies.
virtual species_copy_t getTrueN () const
Return the true copy number of this RSpecies.
Protected Member Functions
RSpecies (Species &parent, species_copy_t n, species_copy_t ulim)
Constructor.
RSpecies (const RSpecies &r)=delete
deleted copy constructor - each RSpecies is uniquely created by the parent Species
RSpecies (RSpecies &&r)=delete
deleted move constructor - each RSpecies is uniquely created by the parent Species
RSpecies & operator= (RSpecies &)=delete
deleted assignment operator - each RSpecies is uniquely created by the parent Species
Protected Attributes
vector< ReactionBase * > _as_reactants = {}
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
vector< ReactionBase * > _as_products = {}
a vector of Reactions where this RSpecies is a Product
Species & _species
reference to the parent Species object
species_copy_t _n
Current copy number of this RSpecies.
RSpeciesType _type
The RSpecies type.
Friends
class Species
class CMonomer
Detailed Description
Represents the reactive aspect of chemical molecules.
It tracks their copy number and can be used in Reactions.
This abstract class represents the reactivity of chemical species. The name RSpecies stems from reacting species. RSpecies tracks the copy number of molecules and the Reactions in which it is involed (
See also
Reaction).
Note
Each intantiation of RSpecies is unique, and hence, cannot be neither copied nor moved (C++11). This has significant implications - e.g., RSpecies cannot be used in vector<RSpecies>. Instead, one should use either vector<RSpecies*> if not owning the RSpecies pointers, or vector<unique_ptr<RSpecies>> if owning the RSpecies pointers. A special allocator can be written such that dynamically allocated RSpecies (through new), are arranged contigiously in memory.
Definition at line 65 of file RSpecies.h.
Constructor & Destructor Documentation
RSpecies() [1/3]
RSpecies::RSpecies (Species & parent, species_copy_t n, species_copy_t ulim) inline protected
Constructor.
Parameters
parent - the Species object to which this RSpecies belongs
n - copy number
Definition at line 95 of file RSpecies.h.
References operator=().
RSpecies() [2/3]
RSpecies::RSpecies (const RSpecies & r) protected delete
deleted copy constructor - each RSpecies is uniquely created by the parent Species
RSpecies() [3/3]
RSpecies::RSpecies (RSpecies && r) protected delete
deleted move constructor - each RSpecies is uniquely created by the parent Species
~RSpecies()
RSpecies::~RSpecies () virtual noexcept
It is required that all Reactions associated with this RSpecies are destructed before this RSpecies is destructed.
Most of the time, this will occur naturally. If not, an assertion will ungracefully terminate the program.
Note
noexcept is important here. Otherwise, gcc flags the constructor as potentially throwing, which in turn disables move operations by the STL containers. This behaviour is a gcc bug (as of gcc 4.703), and will presumbaly be fixed in the future.
Definition at line 23 of file RSpecies.cpp.
References _as_products, and _as_reactants.
Referenced by removeAsProduct().
Member Function Documentation
activateAssocProductReactions()
void RSpecies::activateAssocProductReactions ()
Attempts to activate previously passivated Reactions where this RSpecies is involved as a Product. Usually, the Reaction was first passivated, for example if the RSpecies copy number of one of the reactants went up to max_ulim.
Definition at line 77 of file RSpecies.cpp.
References _as_products.
Referenced by RSpeciesReg::down(), RSpeciesAvg::down(), and removeAsProduct().
activateAssocReactantReactions()
void RSpecies::activateAssocReactantReactions ()
Attempts to activate previously passivated Reactions where this RSpecies is involved as a Reactant. Usually, the Reaction was first passivated, for example if the RSpecies copy number of one of the reactants dropeed to zero. This attempt may not succeed if there are still other reactants in the same Reaction with zero copy count.
Definition at line 72 of file RSpecies.cpp.
References _as_reactants.
Referenced by removeAsProduct(), RSpeciesReg::up(), and RSpeciesAvg::up().
addAsProduct()
void RSpecies::addAsProduct (ReactionBase * r) inline
Definition at line 138 of file RSpecies.h.
addAsReactant()
void RSpecies::addAsReactant (ReactionBase * r) inline
Definition at line 134 of file RSpecies.h.
beginProductReactions()
vr_iterator RSpecies::beginProductReactions () inline
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Product.
Definition at line 249 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
beginReactantReactions()
vr_iterator RSpecies::beginReactantReactions () inline
Return vector<ReactionBase *>::iterator, which points to the beginning of all Reactions where this RSpecies is involved as a Reactant.
Definition at line 245 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
down()
virtual void RSpecies::down () pure virtual
Decreases the copy number of this RSpecies.
Implemented in RSpeciesAvg, RSpeciesConst, and RSpeciesReg.
Referenced by Species::down(), and endProductReactions().
endProductReactions()
vr_iterator RSpecies::endProductReactions () inline
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Product.
Definition at line 257 of file RSpecies.h.
References down(), getN(), and up().
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
endReactantReactions()
vr_iterator RSpecies::endReactantReactions () inline
Return vector<ReactionBase *>::iterator, which points to the end of all Reactions where this RSpecies is involved as a Reactant.
Definition at line 253 of file RSpecies.h.
Referenced by Reaction< 1, 1 >::activateReactionUnconditionalImpl(), and Reaction< 1, 1 >::passivateReactionImpl().
getFullName()
string RSpecies::getFullName () const
Return the full name of this Species in a string format (e.g. "Arp2/3{Bulk}")
Definition at line 67 of file RSpecies.cpp.
References _species, and Species::getFullName().
Referenced by getSpecies(), and operator<<().
getN()
virtual float RSpecies::getN () const pure virtual
Return the effective copy number of this RSpecies.
Implemented in RSpeciesAvg, RSpeciesConst, and RSpeciesReg.
Referenced by RSpeciesConst::down(), endProductReactions(), Species::getN(), and operator<<().
getSpecies() [1/2]
Species& RSpecies::getSpecies () inline
return parent Species as a reference
Definition at line 227 of file RSpecies.h.
References _species.
Referenced by BranchingManager::BranchingManager(), CBranchingPoint::createOffReaction(), Reaction< 1, 1 >::is_equal(), LinkerBindingManager::LinkerBindingManager(), MotorBindingManager::MotorBindingManager(), and CMotorGhost::moveMotorHead().
getSpecies() [2/2]
const Species& RSpecies::getSpecies () const inline
return parent Species as a const reference
Definition at line 230 of file RSpecies.h.
References _species, and getFullName().
getTrueN()
virtual species_copy_t RSpecies::getTrueN () const inline virtual
Return the true copy number of this RSpecies.
Definition at line 267 of file RSpecies.h.
References _n.
operator=()
RSpecies& RSpecies::operator= (RSpecies &) protected delete
deleted assignment operator - each RSpecies is uniquely created by the parent Species
Referenced by RSpecies(), RSpeciesAvg::RSpeciesAvg(), RSpeciesConst::RSpeciesConst(), and RSpeciesReg::RSpeciesReg().
passivateAssocProductReactions()
void RSpecies::passivateAssocProductReactions ()
Passivates all Reactions where this RSpecies is among the products.
Definition at line 87 of file RSpecies.cpp.
References _as_products.
Referenced by removeAsProduct(), RSpeciesReg::up(), and RSpeciesAvg::up().
passivateAssocReactantReactions()
void RSpecies::passivateAssocReactantReactions ()
Passivates all Reactions where this RSpecies is among the reactants.
Definition at line 82 of file RSpecies.cpp.
References _as_reactants.
Referenced by RSpeciesReg::down(), RSpeciesAvg::down(), and removeAsProduct().
productReactions()
vector<ReactionBase *>& RSpecies::productReactions () inline
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Product.
Definition at line 241 of file RSpecies.h.
References _as_products.
reactantReactions()
vector<ReactionBase *>& RSpecies::reactantReactions () inline
Return vector<ReactionBase *>, which contains pointers to all [Reactions](Reaction) where this RSpecies is involved as a Reactant.
Definition at line 237 of file RSpecies.h.
References _as_reactants.
Referenced by Species::activateReactantReactions(), Species::passivateReactantReactions(), Species::updateReactantPropensities(), and MotorGhost::updateReactionRates().
removeAsProduct()
void RSpecies::removeAsProduct (const ReactionBase * r) inline
Definition at line 158 of file RSpecies.h.
References activateAssocProductReactions(), activateAssocReactantReactions(), passivateAssocProductReactions(), passivateAssocReactantReactions(), and ~RSpecies().
removeAsReactant()
void RSpecies::removeAsReactant (const ReactionBase * r) inline
Definition at line 142 of file RSpecies.h.
setN()
void RSpecies::setN (species_copy_t n) inline
Sets the copy number for this RSpecies.
Parameters
n should be a non-negative number, but no checking is done in run time
Note
The operation does not emit any signals about the copy number change.
Definition at line 121 of file RSpecies.h.
Referenced by Species::setN().
up()
virtual void RSpecies::up () pure virtual
Increases the copy number of this RSpecies.
Implemented in RSpeciesAvg, RSpeciesConst, and RSpeciesReg.
Referenced by Species::countSpecies(), endProductReactions(), and RSpeciesConst::RSpeciesConst().
Friends And Related Function Documentation
CMonomer
friend class CMonomer friend
Definition at line 67 of file RSpecies.h.
Species
friend class Species friend
Definition at line 66 of file RSpecies.h.
Member Data Documentation
_as_products
vector<ReactionBase *> RSpecies::_as_products = {} protected
a vector of Reactions where this RSpecies is a Product
Definition at line 73 of file RSpecies.h.
Referenced by activateAssocProductReactions(), passivateAssocProductReactions(), productReactions(), and ~RSpecies().
_as_reactants
vector<ReactionBase *> RSpecies::_as_reactants = {} protected
Reactions calls addAsReactant(), removeAsReactant() - which other classes should not call.
a vector of Reactions where this RSpecies is a Reactant
Definition at line 70 of file RSpecies.h.
Referenced by activateAssocReactantReactions(), passivateAssocReactantReactions(), reactantReactions(), and ~RSpecies().
_n
species_copy_t RSpecies::_n protected
Current copy number of this RSpecies.
this RSpecies (usually when a single step of this Reaction occurs)
Definition at line 77 of file RSpecies.h.
Referenced by RSpeciesReg::down(), RSpeciesConst::down(), RSpeciesAvg::down(), RSpeciesReg::getN(), getTrueN(), RSpeciesReg::up(), and RSpeciesAvg::up().
_species
Species& RSpecies::_species protected
reference to the parent Species object
Definition at line 76 of file RSpecies.h.
Referenced by getFullName(), and getSpecies().
_type
RSpeciesType RSpecies::_type protected
The RSpecies type.
Definition at line 88 of file RSpecies.h.
Referenced by Species::operator=(), RSpeciesAvg::RSpeciesAvg(), RSpeciesConst::RSpeciesConst(), RSpeciesReg::RSpeciesReg(), and Species::Species().
The documentation for this class was generated from the following files:
src/Chemistry/RSpecies.h
src/Chemistry/RSpecies.cpp