MEDYAN: src/common.h File Reference
common.h File Reference
#include <iostream>
#include <vector>
#include <boost/signals2/shared_connection_block.hpp>
#include "utility.h"
Macros
#define MAX_FILAMENT_TYPES 10
Num filament types maximum.
#define SPECIESFILAMENT 0
Constant Species index identifiers.
#define SPECIESPLUSEND 1
Constant Species index identifiers.
#define SPECIESMINUSEND 2
Constant Species index identifiers.
#define SPECIESBOUND 0
Constant Species index identifiers.
#define SPECIESLINKER 1
Constant Species index identifiers.
#define SPECIESMOTOR 2
Constant Species index identifiers.
#define SPECIESBRANCHER 3
Constant Species index identifiers.
#define POLYREACTANTS 2
Constant Reaction reactant and product numbers.
#define POLYPRODUCTS 2
Constant Reaction reactant and product numbers.
#define DEPOLYREACTANTS 2
Depolymerization.
#define DEPOLYPRODUCTS 2
Constant Reaction reactant and product numbers.
#define LMBINDINGREACTANTS 3
Linker and motor binding.
#define LMBINDINGPRODUCTS 2
Constant Reaction reactant and product numbers.
#define LMUNBINDINGREACTANTS 2
Linker and motor unbinding.
#define LMUNBINDINGPRODUCTS 3
Constant Reaction reactant and product numbers.
#define MWALKINGREACTANTS 2
Motor walking.
#define MWALKINGPRODUCTS 2
Constant Reaction reactant and product numbers.
#define NUCLEATIONREACTANTS 2
Nucleation.
#define NUCLEATIONPRODUCTS 3
Constant Reaction reactant and product numbers.
#define DESTRUCTIONREACTANTS 2
Destruction.
#define DESTRUCTIONPRODUCTS 2
Constant Reaction reactant and product numbers.
#define AGINGREACTANTS 1
Aging.
#define AGINGPRODUCTS 1
Constant Reaction reactant and product numbers.
#define SEVERINGREACTANTS 1
Severing.
#define SEVERINGPRODUCTS 0
Constant Reaction reactant and product numbers.
#define BRANCHINGREACTANTS 3
Branching.
#define BRANCHINGPRODUCTS 2
Constant Reaction reactant and product numbers.
#define BUNBINDINGREACTANTS 1
Branch unbinding.
#define BUNBINDINGPRODUCTS 2
Constant Reaction reactant and product numbers.
Typedefs
typedef unsigned int species_copy_t
Species constants.
typedef boost::signals2::shared_connection_block ConnectionBlock
Boost typedef.
Functions
double tau ()
void resetglobaltime ()
Variables
const species_copy_t max_ulim = 1000000
double global_time
Global time.
const double kT = 4.1
Some constants.
Macro Definition Documentation
AGINGPRODUCTS
#define AGINGPRODUCTS 1
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 92 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
AGINGREACTANTS
#define AGINGREACTANTS 1
Aging.
Definition at line 91 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
BRANCHINGPRODUCTS
#define BRANCHINGPRODUCTS 2
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 100 of file common.h.
Referenced by ChemManager::genFilBindingReactions(), and ChemManager::genSpecies().
BRANCHINGREACTANTS
#define BRANCHINGREACTANTS 3
Branching.
Definition at line 99 of file common.h.
Referenced by ChemManager::genFilBindingReactions(), and ChemManager::genSpecies().
BUNBINDINGPRODUCTS
#define BUNBINDINGPRODUCTS 2
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 104 of file common.h.
BUNBINDINGREACTANTS
#define BUNBINDINGREACTANTS 1
Branch unbinding.
Definition at line 103 of file common.h.
DEPOLYPRODUCTS
#define DEPOLYPRODUCTS 2
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 68 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
DEPOLYREACTANTS
#define DEPOLYREACTANTS 2
Depolymerization.
Definition at line 67 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
DESTRUCTIONPRODUCTS
#define DESTRUCTIONPRODUCTS 2
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 88 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
DESTRUCTIONREACTANTS
#define DESTRUCTIONREACTANTS 2
Destruction.
Definition at line 87 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
LMBINDINGPRODUCTS
#define LMBINDINGPRODUCTS 2
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 72 of file common.h.
Referenced by ChemManager::genFilBindingReactions(), and ChemManager::genSpecies().
LMBINDINGREACTANTS
#define LMBINDINGREACTANTS 3
Linker and motor binding.
Definition at line 71 of file common.h.
Referenced by ChemManager::genFilBindingReactions(), and ChemManager::genSpecies().
LMUNBINDINGPRODUCTS
#define LMUNBINDINGPRODUCTS 3
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 76 of file common.h.
LMUNBINDINGREACTANTS
#define LMUNBINDINGREACTANTS 2
Linker and motor unbinding.
Definition at line 75 of file common.h.
MAX_FILAMENT_TYPES
#define MAX_FILAMENT_TYPES 10
Num filament types maximum.
Definition at line 42 of file common.h.
Referenced by CMonomer::isConsistent().
MWALKINGPRODUCTS
#define MWALKINGPRODUCTS 2
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 80 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
MWALKINGREACTANTS
#define MWALKINGREACTANTS 2
Motor walking.
Definition at line 79 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
NUCLEATIONPRODUCTS
#define NUCLEATIONPRODUCTS 3
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 84 of file common.h.
Referenced by ChemManager::genNucleationReactions().
NUCLEATIONREACTANTS
#define NUCLEATIONREACTANTS 2
Nucleation.
Definition at line 83 of file common.h.
Referenced by ChemManager::genNucleationReactions().
POLYPRODUCTS
#define POLYPRODUCTS 2
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 64 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
POLYREACTANTS
#define POLYREACTANTS 2
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 63 of file common.h.
Referenced by ChemManager::genFilReactionTemplates().
SEVERINGPRODUCTS
#define SEVERINGPRODUCTS 0
Constant Reaction reactant and product numbers.
Note
- DO NOT CHANGE!!! Polymerization
Definition at line 96 of file common.h.
SEVERINGREACTANTS
#define SEVERINGREACTANTS 1
Severing.
Definition at line 95 of file common.h.
SPECIESBOUND
#define SPECIESBOUND 0
Constant Species index identifiers.
Note
- DO NOT CHANGE!!!
Definition at line 52 of file common.h.
Referenced by CMonomer::speciesBound().
SPECIESBRANCHER
#define SPECIESBRANCHER 3
Constant Species index identifiers.
Note
- DO NOT CHANGE!!!
Definition at line 55 of file common.h.
Referenced by CMonomer::activeSpeciesBrancher(), and CMonomer::speciesBrancher().
SPECIESFILAMENT
#define SPECIESFILAMENT 0
Constant Species index identifiers.
Note
- DO NOT CHANGE!!!
Definition at line 48 of file common.h.
Referenced by CMonomer::activeSpeciesFilament(), and CMonomer::speciesFilament().
SPECIESLINKER
#define SPECIESLINKER 1
Constant Species index identifiers.
Note
- DO NOT CHANGE!!!
Definition at line 53 of file common.h.
Referenced by CMonomer::activeSpeciesLinker(), and CMonomer::speciesLinker().
SPECIESMINUSEND
#define SPECIESMINUSEND 2
Constant Species index identifiers.
Note
- DO NOT CHANGE!!!
Definition at line 50 of file common.h.
Referenced by CMonomer::activeSpeciesMinusEnd(), and CMonomer::speciesMinusEnd().
SPECIESMOTOR
#define SPECIESMOTOR 2
Constant Species index identifiers.
Note
- DO NOT CHANGE!!!
Definition at line 54 of file common.h.
Referenced by CMonomer::activeSpeciesMotor(), and CMonomer::speciesMotor().
SPECIESPLUSEND
#define SPECIESPLUSEND 1
Constant Species index identifiers.
Note
- DO NOT CHANGE!!!
Definition at line 49 of file common.h.
Referenced by CMonomer::activeSpeciesPlusEnd(), and CMonomer::speciesPlusEnd().
Typedef Documentation
ConnectionBlock
typedef boost::signals2::shared_connection_block ConnectionBlock
Boost typedef.
Definition at line 39 of file common.h.
species_copy_t
typedef unsigned int species_copy_t
Species constants.
Definition at line 24 of file common.h.
Function Documentation
resetglobaltime()
void resetglobaltime () inline
Definition at line 31 of file common.h.
References global_time.
Referenced by Controller::run().
tau()
double tau () inline
Definition at line 30 of file common.h.
References global_time.
Referenced by RSpeciesAvg::computeAverageN(), RSpeciesAvg::down(), Controller::executeSpecialProtocols(), ChemSimpleGillespieImpl::makeStep(), ChemGillespieImpl::makeStep(), Controller::moveBoundary(), RNodeNRM::passivateReaction(), BasicSnapshot::print(), BirthTimes::print(), Forces::print(), Tensions::print(), WallTensions::print(), Types::print(), Chemistry::print(), MotorLifetimes::print(), MotorWalkLengths::print(), LinkerLifetimes::print(), FilamentTurnoverTimes::print(), Filament::retractMinusEnd(), RSpeciesAvg::RSpeciesAvg(), Controller::run(), RNodeNRM::setTau(), Controller::setupInitialNetwork(), Controller::setupSpecialStructures(), Filament::straightFilamentProjection(), mathfunc::twoPointDirection(), RSpeciesAvg::up(), ChemManager::updateCopyNumbers(), Filament::zigZagFilamentProjection(), Linker::~Linker(), and MotorGhost::~MotorGhost().
Variable Documentation
global_time
double global_time
Global time.
Definition at line 16 of file common.cpp.
Referenced by resetglobaltime(), ChemSimpleGillespieImpl::syncGlobalTime(), ChemGillespieImpl::syncGlobalTime(), ChemNRMImpl::syncGlobalTime(), and tau().
kT
const double kT = 4.1
Some constants.
Definition at line 33 of file common.h.
Referenced by BrownianRatchet::changeRate(), LinkerCatchSlip::changeRate(), and LinkerSlip::changeRate().
max_ulim
const species_copy_t max_ulim = 1000000
Definition at line 25 of file common.h.
Referenced by ChemManager::genSpecies(), Species::operator=(), and Species::Species().