M3Sym: M3SYM/Structure/Compartment.cpp File Reference
Compartment.cpp File Reference
#include "Compartment.h"
#include "Visitor.h"
Functions
bool operator== (const Compartment &a, const Compartment &b)
Function Documentation
bool operator== (const Compartment & a, const Compartment & b)
Two Compartment objects are equal if each contains analogous Species and Reaction objects, in the same order
Definition at line 76 of file Compartment.cpp.
References Compartment::_internal_reactions, Compartment::_species, A_B_C_Cycle::A, A_B_C_Cycle::B, Compartment::numberOfInternalReactions(), Compartment::numberOfSpecies(), ReactionPtrContainerVector::reactions(), and SpeciesPtrContainerVector::species().