M3Sym: M3SYM/EXAMPLES/example_composite.cpp File Reference
example_composite.cpp File Reference
#include <iostream>
#include <fstream>
#include <boost/heap/pairing_heap.hpp>
#include "System.h"
#include "ChemNRMImpl.h"
#include "ChemSim.h"
#include "Signaling.h"
#include "Composite.h"
#include "CompartmentContainer.h"
#include "Visitor.h"
Functions
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
Definition at line 27 of file example_composite.cpp.
References A_B_C_Cycle::C, Composite::countReactions(), Species::getN(), ReactionBase::getParent(), Species::getParent(), CompartmentGrid::getProtoCompartment(), ReactionBase::getRate(), Component::numberOfSpecies(), VisitorLambda::setLambda(), SpeciesVisitorLambda::setLambda(), ReactionVisitorLambda::setLambda(), SpeciesVisitorLambda::setLambdaPred(), and ReactionVisitorLambda::setLambdaPred().