M3Sym: M3SYM/EXAMPLES/example_misc.cpp File Reference
example_misc.cpp File Reference
#include <iostream>
#include <fstream>
#include <boost/heap/pairing_heap.hpp>
#include "System.h"
#include "ChemNRMImpl.h"
#include "ChemSim.h"
Classes
struct PrintSpecies
Functions
void print_species (RSpecies *s, int i)
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
Definition at line 38 of file example_misc.cpp.
References ChemSim::addReaction(), ReactionBase::computePropensity(), Reaction< M, N >::getAffectedReactions(), Species::getRSpecies(), ChemSim::initialize(), ReactionBase::makeStep(), ChemSim::printReactions(), and ChemSim::run().
void print_species (RSpecies * s, int i)
Definition at line 25 of file example_misc.cpp.
References RSpecies::getFullName(), and RSpecies::getN().