MEDYAN: src/Structure/Filament.cpp File Reference
Filament.cpp File Reference
#include <time.h>
#include <random>
#include <math.h>
#include <algorithm>
#include <functional>
#include <numeric>
#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/io.hpp>
#include <boost/numeric/ublas/operation.hpp>
#include <boost/range/numeric.hpp>
#include <fstream>
#include "Filament.h"
#include "Cylinder.h"
#include "Bead.h"
#include "SubSystem.h"
#include "SysParams.h"
#include "MathFunctions.h"
#include "GController.h"
#include "Rand.h"
Functions
void marsagila (vector< double > &v)
Create a projection.
void matrix_mul (boost::numeric::ublas::matrix< double > &X, boost::numeric::ublas::matrix< double > &Y, boost::numeric::ublas::matrix< double > &Z, vector< double > &x, vector< double > &y, vector< double > &z, int nbeads, vector< vector< double >> &coordinate)
Matrix multiply.
void arcOutward (vector< double > &v1, vector< double > &v2, vector< vector< double >> &v)
Function Documentation
arcOutward()
void arcOutward (vector< double > & v1, vector< double > & v2, vector< vector< double >> & v)
Definition at line 736 of file Filament.cpp.
References GController::getCenter(), mathfunc::midPointCoordinate(), and mathfunc::twoPointDistance().
Referenced by Filament::arcFilamentProjection().
marsagila()
void marsagila (vector< double > & v)
Create a projection.
Note
- created by Aravind 12/2014
Definition at line 629 of file Filament.cpp.
References Rand::randDouble().
matrix_mul()
void matrix_mul (boost::numeric::ublas::matrix< double > & X, boost::numeric::ublas::matrix< double > & Y, boost::numeric::ublas::matrix< double > & Z, vector< double > & x, vector< double > & y, vector< double > & z, int nbeads, vector< vector< double >> & coordinate)
Matrix multiply.
Note
- created by Aravind 12/2014
Definition at line 653 of file Filament.cpp.
References std::sum().
Referenced by Filament::arcFilamentProjection().