MEDYAN: src/MEDYAN.cpp File Reference
MEDYAN.cpp File Reference
#include <getopt.h>
#include "common.h"
#include "Controller.h"
#include "SubSystem.h"
Functions
void printUsage ()
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 79 of file MEDYAN.cpp.
References Controller::initialize(), printUsage(), and Controller::run().
printUsage()
void printUsage ()
Definition at line 75 of file MEDYAN.cpp.
Referenced by main().