MEDYAN: mathfunc Namespace Reference
mathfunc Namespace Reference
is used for the mathematics module for the entire codebase mathfunc includes functions to calculate distances, products, and midpoints
Functions
vector< double > movePointOutOfPlane (const vector< double > &p1, const vector< double > &p2, const vector< double > &p3, const vector< double > &p4, int i, double d)
Function to move bead out of plane by specified amount.
tuple< vector< double >, vector< double > > branchProjection (const vector< double > &n, const vector< double > &p, double l, double m, double theta)
Function to create a initial branching point and direction, given an initial normal vector and point.
void normalize (vector< double > &v)
Normalize a vector.
vector< double > normalizedVector (const vector< double > &v)
Return normalized vector.
double magnitude (const vector< double > &v)
Get the magnitude of a vector.
double twoPointDistance (const vector< double > &v1, const vector< double > &v2)
Compute distance between two points with coordinates: (x1,y1,z1) and (x2,y2,z3)
double twoPointDistanceStretched (const vector< double > &v1, const vector< double > &p1, const vector< double > &v2, const vector< double > &p2, double d)
Compute distance between two points with coordinates (x1 -d*p1x,y1-d*p1y,z1-d*p1z) and (x2-d*p2x,y2-d*p2y,z2-d*p2z)
vector< double > twoPointDirection (const vector< double > &v1, const vector< double > &v2)
Calculates a normal to a line starting at (x1,y1,z1) and ending at (x2,y2,z2)
double dotProduct (const vector< double > &v1, const vector< double > &v2)
Scalar product of two vectors v1(x,y,z) and v2(x,y,z)
double scalarProduct (const vector< double > &v1, const vector< double > &v2, const vector< double > &v3, const vector< double > &v4)
Scalar product of two vectors with coordinates: (x2-x1,y2-y1,z2-z1) and (x4-x3,y4-y3,z4-z3)
double scalarProductStretched (const vector< double > &v1, const vector< double > &p1, const vector< double > &v2, const vector< double > &p2, const vector< double > &v3, const vector< double > &p3, const vector< double > &v4, const vector< double > &p4, double d)
Scalar product of two vectors with coordinates: (x2-x1,y2-y1,z2-z1) and (x4-x3,y4-y3,z4-z3) but with x+d*p coordinates.
double dotProductStretched (const vector< double > &v1, const vector< double > &p1, const vector< double > &v2, const vector< double > &p2, double d)
Scalar product of two vectors with coordinates: v1[z,y,z] + d*p1[x,y,z] and v2[x,y,z] + d*p2[x,y,z].
vector< double > vectorProduct (const vector< double > &v1, const vector< double > &v2, const vector< double > &v3, const vector< double > &v4)
Vector product of two vectors with coordinates: (x2-x1,y2-y1,z2-z1) and (x4-x3,y4-y3,z4-z3).
vector< double > vectorProductStretched (const vector< double > &v1, const vector< double > &p1, const vector< double > &v2, const vector< double > &p2, const vector< double > &v3, const vector< double > &p3, const vector< double > &v4, const vector< double > &p4, double d)
Vector product of two vectors with coordinates: (x2-x1,y2-y1,z2-z1) and (x4-x3,y4-y3,z4-z3), but with v -> v+d*p.
vector< double > crossProduct (const vector< double > &v1, const vector< double > &v2)
Vector product of two vectors v1[x,y,z] and v2[x,y,z]. Returns a 3d vector.
vector< double > crossProductStretched (const vector< double > &v1, const vector< double > &p1, const vector< double > &v2, const vector< double > &p2, double d)
Vector product of two vectors v1[x,y,z] and v2[x,y,z]. Returns a 3d vector.
vector< double > nextPointProjection (const vector< double > &coordinate, double d, const vector< double > &tau)
Projection of a new point based on a given direction and starting point.
vector< double > midPointCoordinate (const vector< double > &v1, const vector< double > &v2, double alpha)
Returns coordinates of a point v located on a line between v1 and v2.
vector< double > midPointCoordinateStretched (const vector< double > &v1, const vector< double > &p1, const vector< double > &v2, const vector< double > &p2, double alpha, double d)
Returns coordinates of a point v located on a line between v1 and v2.
bool areParallel (const vector< double > &p1, const vector< double > &p2, const vector< double > &p3, const vector< double > &p4)
Returns true if two vectors (p1->p2 and p3->p4) are parallel.
bool areInPlane (const vector< double > &p1, const vector< double > &p2, const vector< double > &p3, const vector< double > &p4)
Returns true if two vectors (p1->p2 and p3->p4) are in the same plane.
Detailed Description
is used for the mathematics module for the entire codebase mathfunc includes functions to calculate distances, products, and midpoints
Function Documentation
areInPlane()
bool mathfunc::areInPlane (const vector< double > & p1, const vector< double > & p2, const vector< double > & p3, const vector< double > & p4) inline
Returns true if two vectors (p1->p2 and p3->p4) are in the same plane.
Definition at line 277 of file MathFunctions.h.
References areEqual(), branchProjection(), crossProduct(), dotProduct(), and movePointOutOfPlane().
Referenced by CylinderExclVolRepulsion::energy(), CylinderExclVolRepulsion::forces(), and CylinderExclVolRepulsion::forcesAux().
areParallel()
bool mathfunc::areParallel (const vector< double > & p1, const vector< double > & p2, const vector< double > & p3, const vector< double > & p4) inline
Returns true if two vectors (p1->p2 and p3->p4) are parallel.
Definition at line 267 of file MathFunctions.h.
References areEqual(), crossProduct(), and magnitude().
Referenced by CylinderExclVolRepulsion::energy(), CylinderExclVolRepulsion::forces(), and CylinderExclVolRepulsion::forcesAux().
branchProjection()
tuple< vector< double >, vector< double > > mathfunc::branchProjection (const vector< double > & n, const vector< double > & p, double l, double m, double theta)
Function to create a initial branching point and direction, given an initial normal vector and point.
Parameters
l - the distance of the branch from the original point
m - the size of the branch projection
theta - the angle of branching
Returns
a vector describing the initial branching direction and point
Definition at line 76 of file MathFunctions.cpp.
References crossProduct(), normalize(), Rand::randDouble(), and twoPointDirection().
Referenced by areInPlane().
crossProduct()
vector<double> mathfunc::crossProduct (const vector< double > & v1, const vector< double > & v2) inline
Vector product of two vectors v1[x,y,z] and v2[x,y,z]. Returns a 3d vector.
Definition at line 195 of file MathFunctions.h.
Referenced by areInPlane(), areParallel(), branchProjection(), and movePointOutOfPlane().
crossProductStretched()
vector<double> mathfunc::crossProductStretched (const vector< double > & v1, const vector< double > & p1, const vector< double > & v2, const vector< double > & p2, double d) inline
Vector product of two vectors v1[x,y,z] and v2[x,y,z]. Returns a 3d vector.
Definition at line 211 of file MathFunctions.h.
dotProduct()
double mathfunc::dotProduct (const vector< double > & v1, const vector< double > & v2) inline
Scalar product of two vectors v1(x,y,z) and v2(x,y,z)
Definition at line 88 of file MathFunctions.h.
Referenced by areInPlane(), BranchingDihedralCosine::energy(), BranchingDihedralCosine::forces(), BranchingDihedralCosine::forcesAux(), Restart::getAngleDeltaPos(), WallTensions::print(), and MotorGhost::updateReactionRates().
dotProductStretched()
double mathfunc::dotProductStretched (const vector< double > & v1, const vector< double > & p1, const vector< double > & v2, const vector< double > & p2, double d) inline
Scalar product of two vectors with coordinates: v1[z,y,z] + d*p1[x,y,z] and v2[x,y,z] + d*p2[x,y,z].
Definition at line 126 of file MathFunctions.h.
magnitude()
double mathfunc::magnitude (const vector< double > & v) inline
Get the magnitude of a vector.
Definition at line 48 of file MathFunctions.h.
Referenced by areParallel().
midPointCoordinate()
vector<double> mathfunc::midPointCoordinate (const vector< double > & v1, const vector< double > & v2, double alpha) inline
Returns coordinates of a point v located on a line between v1 and v2.
|v-v1|/|v2-v1| = alpha.
Definition at line 241 of file MathFunctions.h.
Referenced by BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Restart::addtoHeapbranchers(), arcOutward(), Restart::crosschecklinkermotor(), LinkerStretchingHarmonic::energy(), MotorGhostStretchingHarmonic::energy(), BranchingPositionCosine::energy(), BranchingDihedralCosine::energy(), BranchingStretchingHarmonic::energy(), BranchingDihedralCosine::forces(), BranchingPositionCosine::forces(), BranchingStretchingHarmonic::forces(), LinkerStretchingHarmonic::forces(), MotorGhostStretchingHarmonic::forces(), BranchingDihedralCosine::forcesAux(), BranchingPositionCosine::forcesAux(), BranchingStretchingHarmonic::forcesAux(), LinkerStretchingHarmonic::forcesAux(), MotorGhostStretchingHarmonic::forcesAux(), MLinker::MLinker(), MMotorGhost::MMotorGhost(), BasicSnapshot::print(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), MotorBindingManager::updateAllPossibleBindings(), BranchingPoint::updateCoordinate(), Linker::updateCoordinate(), Cylinder::updateCoordinate(), MotorGhost::updateCoordinate(), Linker::updatePosition(), MotorGhost::updatePosition(), and MotorGhost::updateReactionRates().
midPointCoordinateStretched()
vector<double> mathfunc::midPointCoordinateStretched (const vector< double > & v1, const vector< double > & p1, const vector< double > & v2, const vector< double > & p2, double alpha, double d) inline
Returns coordinates of a point v located on a line between v1 and v2.
|v-v1|/|v2-v| = alpha, but with x-d*p coordinates
Definition at line 253 of file MathFunctions.h.
Referenced by BranchingDihedralCosine::energy(), BranchingPositionCosine::energy(), LinkerStretchingHarmonic::energy(), BranchingStretchingHarmonic::energy(), and MotorGhostStretchingHarmonic::energy().
movePointOutOfPlane()
vector< double > mathfunc::movePointOutOfPlane (const vector< double > & p1, const vector< double > & p2, const vector< double > & p3, const vector< double > & p4, int i, double d)
Function to move bead out of plane by specified amount.
Definition at line 23 of file MathFunctions.cpp.
References crossProduct(), and normalizedVector().
Referenced by areInPlane(), CylinderExclVolRepulsion::energy(), CylinderExclVolRepulsion::forces(), and CylinderExclVolRepulsion::forcesAux().
nextPointProjection()
vector<double> mathfunc::nextPointProjection (const vector< double > & coordinate, double d, const vector< double > & tau) inline
Projection of a new point based on a given direction and starting point.
Definition at line 230 of file MathFunctions.h.
Referenced by RandomFilamentDist::createFilaments(), ConnectedFilamentDist::createFilaments(), MTOCFilamentDist::createFilaments(), Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), Filament::Filament(), Filament::polymerizeMinusEnd(), and Filament::polymerizePlusEnd().
normalize()
void mathfunc::normalize (vector< double > & v) inline
Normalize a vector.
Definition at line 28 of file MathFunctions.h.
Referenced by branchProjection().
normalizedVector()
vector<double> mathfunc::normalizedVector (const vector< double > & v) inline
Return normalized vector.
Definition at line 36 of file MathFunctions.h.
Referenced by BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), RandomFilamentDist::createFilaments(), ConnectedFilamentDist::createFilaments(), MTOCFilamentDist::createFilaments(), BranchingDihedralCosine::energy(), BubbleBubbleRepulsionExp::forces(), BoundaryCylinderAttachmentHarmonic::forces(), BubbleCylinderRepulsionExp::forces(), BubbleBubbleRepulsionExp::forcesAux(), BoundaryCylinderAttachmentHarmonic::forcesAux(), BubbleCylinderRepulsionExp::forcesAux(), Restart::getAngleDeltaPos(), and movePointOutOfPlane().
scalarProduct()
double mathfunc::scalarProduct (const vector< double > & v1, const vector< double > & v2, const vector< double > & v3, const vector< double > & v4) inline
Scalar product of two vectors with coordinates: (x2-x1,y2-y1,z2-z1) and (x4-x3,y4-y3,z4-z3)
Definition at line 94 of file MathFunctions.h.
Referenced by BranchingBendingCosine::energy(), FilamentBendingCosine::energy(), BranchingPositionCosine::energy(), FilamentBendingHarmonic::energy(), CylinderExclVolRepulsion::energy(), BranchingBendingCosine::forces(), BranchingDihedralCosine::forces(), FilamentBendingCosine::forces(), FilamentBendingHarmonic::forces(), BranchingPositionCosine::forces(), CylinderExclVolRepulsion::forces(), BranchingDihedralCosine::forcesAux(), BranchingPositionCosine::forcesAux(), BranchingBendingCosine::forcesAux(), FilamentBendingCosine::forcesAux(), FilamentBendingHarmonic::forcesAux(), and CylinderExclVolRepulsion::forcesAux().
scalarProductStretched()
double mathfunc::scalarProductStretched (const vector< double > & v1, const vector< double > & p1, const vector< double > & v2, const vector< double > & p2, const vector< double > & v3, const vector< double > & p3, const vector< double > & v4, const vector< double > & p4, double d) inline
Scalar product of two vectors with coordinates: (x2-x1,y2-y1,z2-z1) and (x4-x3,y4-y3,z4-z3) but with x+d*p coordinates.
Definition at line 104 of file MathFunctions.h.
Referenced by BranchingBendingCosine::energy(), FilamentBendingHarmonic::energy(), FilamentBendingCosine::energy(), and BranchingPositionCosine::energy().
twoPointDirection()
vector<double> mathfunc::twoPointDirection (const vector< double > & v1, const vector< double > & v2) inline
Calculates a normal to a line starting at (x1,y1,z1) and ending at (x2,y2,z2)
Definition at line 77 of file MathFunctions.h.
References tau(), and twoPointDistance().
Referenced by branchProjection(), BubbleCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), BoundaryCylinderRepulsion< BRepulsionInteractionType >::computeLoadForces(), ConnectedFilamentDist::createFilaments(), MTOCFilamentDist::createFilaments(), Filament::depolymerizeMinusEnd(), Filament::depolymerizePlusEnd(), Filament::extendMinusEnd(), Filament::extendPlusEnd(), Filament::Filament(), BubbleBubbleRepulsionExp::forces(), BoundaryCylinderAttachmentHarmonic::forces(), BubbleCylinderRepulsionExp::forces(), BubbleBubbleRepulsionExp::forcesAux(), BubbleCylinderRepulsionExp::forcesAux(), BoundaryCylinderAttachmentHarmonic::forcesAux(), SphereBoundaryElement::normal(), CylindricalZBoundaryElement::normal(), HalfSphereZBoundaryElement::normal(), Filament::polymerizeMinusEnd(), Filament::polymerizePlusEnd(), WallTensions::print(), Controller::setupInitialNetwork(), Controller::setupSpecialStructures(), and MotorGhost::updateReactionRates().
twoPointDistance()
double mathfunc::twoPointDistance (const vector< double > & v1, const vector< double > & v2) inline
Compute distance between two points with coordinates: (x1,y1,z1) and (x2,y2,z3)
Definition at line 54 of file MathFunctions.h.
Referenced by BubbleCylinderNL::addNeighbor(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), Restart::addtoHeapbranchers(), arcOutward(), RandomFilamentDist::createFilaments(), ConnectedFilamentDist::createFilaments(), Restart::crosschecklinkermotor(), Cylinder::Cylinder(), SphereBoundaryElement::distance(), CylindricalZBoundaryElement::distance(), HalfSphereZBoundaryElement::distance(), MotorGhostStretchingHarmonic::energy(), MTOCAttachmentHarmonic::energy(), FilamentStretchingHarmonic::energy(), LinkerStretchingHarmonic::energy(), CylinderExclVolRepulsion::energy(), BranchingStretchingHarmonic::energy(), BubbleBubbleRepulsionExp::energy(), BubbleCylinderRepulsionExp::energy(), BoundaryCylinderAttachmentHarmonic::energy(), GController::findCompartments(), MTOCAttachmentHarmonic::forces(), FilamentStretchingHarmonic::forces(), CylinderExclVolRepulsion::forces(), BubbleBubbleRepulsionExp::forces(), BubbleCylinderRepulsionExp::forces(), BoundaryCylinderAttachmentHarmonic::forces(), BranchingStretchingHarmonic::forces(), MotorGhostStretchingHarmonic::forces(), LinkerStretchingHarmonic::forces(), MTOCAttachmentHarmonic::forcesAux(), FilamentStretchingHarmonic::forcesAux(), CylinderExclVolRepulsion::forcesAux(), BubbleBubbleRepulsionExp::forcesAux(), BubbleCylinderRepulsionExp::forcesAux(), BoundaryCylinderAttachmentHarmonic::forcesAux(), BranchingStretchingHarmonic::forcesAux(), LinkerStretchingHarmonic::forcesAux(), MotorGhostStretchingHarmonic::forcesAux(), Restart::getAngleDeltaPos(), BubbleCylinderRepulsionExp::loadForces(), MLinker::MLinker(), MMotorGhost::MMotorGhost(), WallTensions::print(), Restart::settorestartphase(), Controller::setupInitialNetwork(), Controller::setupSpecialStructures(), Filament::straightFilamentProjection(), twoPointDirection(), LinkerBindingManager::updateAllPossibleBindings(), MotorBindingManager::updateAllPossibleBindings(), CylinderCylinderNL::updateNeighbors(), BubbleBubbleNL::updateNeighbors(), BubbleCylinderNL::updateNeighbors(), Linker::updatePosition(), Cylinder::updatePosition(), MotorGhost::updatePosition(), and Filament::zigZagFilamentProjection().
twoPointDistanceStretched()
double mathfunc::twoPointDistanceStretched (const vector< double > & v1, const vector< double > & p1, const vector< double > & v2, const vector< double > & p2, double d) inline
Compute distance between two points with coordinates (x1 -d*p1x,y1-d*p1y,z1-d*p1z) and (x2-d*p2x,y2-d*p2y,z2-d*p2z)
Definition at line 63 of file MathFunctions.h.
Referenced by MTOCAttachmentHarmonic::energy(), FilamentStretchingHarmonic::energy(), BranchingStretchingHarmonic::energy(), BubbleCylinderRepulsionExp::energy(), BubbleBubbleRepulsionExp::energy(), and BoundaryCylinderAttachmentHarmonic::energy().
vectorProduct()
vector<double> mathfunc::vectorProduct (const vector< double > & v1, const vector< double > & v2, const vector< double > & v3, const vector< double > & v4) inline
Vector product of two vectors with coordinates: (x2-x1,y2-y1,z2-z1) and (x4-x3,y4-y3,z4-z3).
Returns a 3d vector.
Definition at line 142 of file MathFunctions.h.
Referenced by BranchingDihedralCosine::energy(), BranchingDihedralCosine::forces(), and BranchingDihedralCosine::forcesAux().
vectorProductStretched()
vector<double> mathfunc::vectorProductStretched (const vector< double > & v1, const vector< double > & p1, const vector< double > & v2, const vector< double > & p2, const vector< double > & v3, const vector< double > & p3, const vector< double > & v4, const vector< double > & p4, double d) inline
Vector product of two vectors with coordinates: (x2-x1,y2-y1,z2-z1) and (x4-x3,y4-y3,z4-z3), but with v -> v+d*p.
Returns a 3d vector.
Definition at line 162 of file MathFunctions.h.
Referenced by BranchingDihedralCosine::energy().