MEDYAN: src/Chemistry/ReactionTemplate.h File Reference
ReactionTemplate.h File Reference
#include <vector>
#include <cmath>
#include "common.h"
#include "Species.h"
#include "SysParams.h"
Classes
class FilamentReactionTemplate
To store Filament chemical reaction information read from an input file.
class PolyPlusEndTemplate
Template for polymerization at plus end of Filament.
class PolyMinusEndTemplate
Template for polymerization at minus end of Filament.
class DepolyPlusEndTemplate
Template for depolymerization at plus end of Filament.
class DepolyMinusEndTemplate
Template for depolymerization at minus end of Filament.
class MotorWalkPTemplate
Template for MotorGhost walking.
class MotorWalkMTemplate
Template for MotorGhost walking.
class AgingTemplate
Template for Filament aging.
class DestructionTemplate
Template for Filament destruction.
class SeveringTemplate
Template for severing a Filament.
Enumerations
enum FilamentReactionDirection { FORWARD, BACKWARD, INPLACE }
Enumeration for direction of reaction.
Functions
int getInt (tuple< int, SpeciesType > x)
Helper for tuple getter.
SpeciesType getType (tuple< int, SpeciesType > x)
Helper for tuple getter.
Enumeration Type Documentation
FilamentReactionDirection
enum FilamentReactionDirection
Enumeration for direction of reaction.
Enumerator
FORWARD
BACKWARD
INPLACE
Definition at line 27 of file ReactionTemplate.h.
Function Documentation
getInt()
int getInt (tuple< int, SpeciesType > x) inline
Helper for tuple getter.
Definition at line 230 of file ReactionTemplate.h.
Referenced by PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), MotorWalkPTemplate::addReaction(), MotorWalkMTemplate::addReaction(), AgingTemplate::addReaction(), DestructionTemplate::addReaction(), and SeveringTemplate::addReaction().
getType()
SpeciesType getType (tuple< int, SpeciesType > x) inline
Helper for tuple getter.
Definition at line 231 of file ReactionTemplate.h.
Referenced by PolyPlusEndTemplate::addReaction(), PolyMinusEndTemplate::addReaction(), DepolyPlusEndTemplate::addReaction(), DepolyMinusEndTemplate::addReaction(), AgingTemplate::addReaction(), and DestructionTemplate::addReaction().