MEDYAN: src/Chemistry/RSpecies.h File Reference
RSpecies.h File Reference
#include <vector>
#include <string>
#include <unordered_map>
#include <algorithm>
#include <cassert>
#include <stdexcept>
#include <boost/signals2/signal.hpp>
#include <boost/signals2/connection.hpp>
#include <boost/signals2/shared_connection_block.hpp>
#include "common.h"
Classes
class RSpecies
Represents the reactive aspect of chemical molecules.
class RSpeciesReg
A RSpecies implementation that changes copy number regularly.
class RSpeciesConst
A constant RSpecies whose copy number does not change.
class RSpeciesAvg
An average RSpecies that tracks the average copy number over a number of events.
class RSpeciesFactory
A factory class to create RSpecies objects.
Typedefs
typedef vector< ReactionBase * >::iterator vr_iterator
vr stands for vector of Reactions
typedef vector< ReactionBase * >::const_iterator vr_const_iterator
typedef vector< RSpecies * >::iterator vrsp_iterator
vsp stands for vector of RSpecies
typedef vector< RSpecies * >::const_iterator vrsp_const_iterator
typedef boost::signals2::signal< void(RSpecies *, int)> RSpeciesCopyNChangedSignal
This is a RSpecies signal object that can be used to signal when the copy number changes.
Enumerations
enum RSpeciesType { REG, AVG, CONST }
Enumeration for RSpecies types.
Functions
ostream & operator<< (ostream &os, const RSpecies &s)
Print self into an iostream.
Typedef Documentation
RSpeciesCopyNChangedSignal
typedef boost::signals2::signal<void (RSpecies *, int)> RSpeciesCopyNChangedSignal
This is a RSpecies signal object that can be used to signal when the copy number changes.
Definition at line 50 of file RSpecies.h.
vr_const_iterator
typedef vector<ReactionBase*>::const_iterator vr_const_iterator
Definition at line 42 of file RSpecies.h.
vr_iterator
typedef vector<ReactionBase*>::iterator vr_iterator
vr stands for vector of Reactions
Definition at line 38 of file RSpecies.h.
vrsp_const_iterator
typedef vector<RSpecies*>::const_iterator vrsp_const_iterator
Definition at line 46 of file RSpecies.h.
vrsp_iterator
typedef vector<RSpecies*>::iterator vrsp_iterator
vsp stands for vector of RSpecies
Definition at line 45 of file RSpecies.h.
Enumeration Type Documentation
RSpeciesType
enum RSpeciesType
Enumeration for RSpecies types.
Enumerator
REG
AVG
CONST
Definition at line 31 of file RSpecies.h.
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const RSpecies & s)
Print self into an iostream.
Definition at line 33 of file RSpecies.cpp.
References RSpecies::getFullName(), and RSpecies::getN().
Referenced by RSpeciesAvg::getN().