MEDYAN: src/Chemistry/Species.h File Reference
Species.h File Reference
#include <vector>
#include <string>
#include <unordered_map>
#include <algorithm>
#include <cassert>
#include <stdexcept>
#include <type_traits>
#include "common.h"
#include "RSpecies.h"
Classes
class SpeciesNamesDB
Used to associate unique integers with character based names of Species.
class Species
Represents chemical molecules, tracks their copy number and can be used in Reactions.
class SpeciesBulk
Used for species without spatial information (i.e. well-mixed in the container)
class SpeciesDiffusing
Used for species which can move spatially from one compartment to the neighboring one (i.e.
class SpeciesFilament
Used for species that can be in a Filament.
class SpeciesBound
Used for species that can be bound to a Filament.
class SpeciesLinker
Used for species that can be bound to a Filament.
class SpeciesMotor
Used for species that can be bound to a Filament.
class SpeciesBrancher
Used for species that can be bound to a Filament.
class SpeciesPlusEnd
Used for a plus end species on a Filament.
class SpeciesMinusEnd
Used for a minus end species on a Filament.
class SpeciesSingleBinding
Used to represent a single binding site in a compartment.
class SpeciesPairBinding
Used to represent a pair binding site in a compartment.
Enumerations
enum SpeciesType {
BULK, DIFFUSING, FILAMENT, BOUND,
LINKER, MOTOR, BRANCHER, PLUSEND,
MINUSEND
}
Enumeration for Species types.
Functions
ostream & operator<< (ostream &os, const Species &s)
Print self into an iostream.
Enumeration Type Documentation
SpeciesType
enum SpeciesType
Enumeration for Species types.
Enumerator
BULK
DIFFUSING
FILAMENT
BOUND
LINKER
MOTOR
BRANCHER
PLUSEND
MINUSEND
Definition at line 35 of file Species.h.
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const Species & s)
Print self into an iostream.
Definition at line 36 of file Species.cpp.
References Species::getFullName(), and Species::getN().
Referenced by SpeciesPairBinding::~SpeciesPairBinding().