M3Sym: MotorWalkingBackwardCallback Struct Reference
MotorWalkingBackwardCallback Struct Reference
Callback to walk a MotorGhost on a Filament.
#include <ChemCallbacks.h>
Public Member Functions
MotorWalkingBackwardCallback (SpeciesMotor *sm1, SpeciesMotor *sm2)
void operator() (ReactionBase *r)
Public Attributes
SpeciesMotor * _sm1
SpeciesMotor * _sm2
Detailed Description
Callback to walk a MotorGhost on a Filament.
Definition at line 231 of file ChemCallbacks.h.
Constructor & Destructor Documentation
MotorWalkingBackwardCallback::MotorWalkingBackwardCallback (SpeciesMotor * sm1, SpeciesMotor * sm2) inline
Definition at line 236 of file ChemCallbacks.h.
Member Function Documentation
void MotorWalkingBackwardCallback::operator() (ReactionBase * r) inline
Definition at line 239 of file ChemCallbacks.h.
References _sm1, _sm2, GeometryParameters::cylinderIntSize, SystemParameters::Geometry(), SpeciesBound::getCBound(), MotorGhost::getCMotorGhost(), MotorGhost::getFirstPosition(), CBound::getFirstSpecies(), MotorGhost::getSecondPosition(), MotorGhost::setFirstPosition(), CBound::setFirstSpecies(), MotorGhost::setSecondPosition(), and CBound::setSecondSpecies().
Member Data Documentation
SpeciesMotor* MotorWalkingBackwardCallback::_sm1
Definition at line 233 of file ChemCallbacks.h.
Referenced by operator()().
SpeciesMotor* MotorWalkingBackwardCallback::_sm2
Definition at line 234 of file ChemCallbacks.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
M3SYM/Chemistry/ChemCallbacks.h