M3Sym: LinkerBindingCallback Struct Reference
LinkerBindingCallback Struct Reference
Callback to bind a linker to filaments.
#include <ChemCallbacks.h>
Public Member Functions
LinkerBindingCallback (CCylinder *cc1, CCylinder *cc2, short linkerType, short position1, short position2, SubSystem *ps)
void operator() (ReactionBase *r)
Public Attributes
SubSystem * _ps
CCylinder * _cc1
CCylinder * _cc2
short _linkerType
short _position1
short _position2
Detailed Description
Callback to bind a linker to filaments.
Definition at line 124 of file ChemCallbacks.h.
Constructor & Destructor Documentation
LinkerBindingCallback::LinkerBindingCallback (CCylinder * cc1, CCylinder * cc2, short linkerType, short position1, short position2, SubSystem * ps) inline
Definition at line 131 of file ChemCallbacks.h.
Member Function Documentation
void LinkerBindingCallback::operator() (ReactionBase * r) inline
Definition at line 134 of file ChemCallbacks.h.
References _cc1, _cc2, _linkerType, _position1, _position2, _ps, SubSystem::addNewLinker(), GeometryParameters::cylinderIntSize, SystemParameters::Geometry(), and CCylinder::getCylinder().
Member Data Documentation
CCylinder* LinkerBindingCallback::_cc1
Definition at line 127 of file ChemCallbacks.h.
Referenced by operator()().
CCylinder * LinkerBindingCallback::_cc2
Definition at line 127 of file ChemCallbacks.h.
Referenced by operator()().
short LinkerBindingCallback::_linkerType
Definition at line 128 of file ChemCallbacks.h.
Referenced by operator()().
short LinkerBindingCallback::_position1
Definition at line 129 of file ChemCallbacks.h.
Referenced by operator()().
short LinkerBindingCallback::_position2
Definition at line 129 of file ChemCallbacks.h.
Referenced by operator()().
SubSystem* LinkerBindingCallback::_ps
Definition at line 126 of file ChemCallbacks.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
M3SYM/Chemistry/ChemCallbacks.h