M3Sym: UnbindingCallback Struct Reference
UnbindingCallback Struct Reference
Callback to unbind a CBound from a Filament.
#include <ChemCallbacks.h>
Public Member Functions
UnbindingCallback (SpeciesBound *s1, SubSystem *ps)
void operator() (ReactionBase *r)
Public Attributes
SubSystem * _ps
SpeciesBound * _s1
Detailed Description
Callback to unbind a CBound from a Filament.
Definition at line 171 of file ChemCallbacks.h.
Constructor & Destructor Documentation
UnbindingCallback::UnbindingCallback (SpeciesBound * s1, SubSystem * ps) inline
Definition at line 176 of file ChemCallbacks.h.
Member Function Documentation
void UnbindingCallback::operator() (ReactionBase * r) inline
Definition at line 178 of file ChemCallbacks.h.
References _ps, _s1, SpeciesBound::getCBound(), SubSystem::removeLinker(), and SubSystem::removeMotorGhost().
Member Data Documentation
SubSystem* UnbindingCallback::_ps
Definition at line 173 of file ChemCallbacks.h.
Referenced by operator()().
SpeciesBound* UnbindingCallback::_s1
Definition at line 174 of file ChemCallbacks.h.
Referenced by UnbindingManager::addReaction(), and operator()().
The documentation for this struct was generated from the following file:
M3SYM/Chemistry/ChemCallbacks.h