M3Sym: MotorMovingCylinderForwardCallback Struct Reference
MotorMovingCylinderForwardCallback Struct Reference
Callback to walk a MotorGhost on a Filament to a new Cylinder.
#include <ChemCallbacks.h>
Public Member Functions
MotorMovingCylinderForwardCallback (SpeciesMotor *sm1, SpeciesMotor *sm2, CCylinder *newCCylinder)
void operator() (ReactionBase *r)
Public Attributes
SpeciesMotor * _sm1
SpeciesMotor * _sm2
CCylinder * _newCCylinder
Detailed Description
Callback to walk a MotorGhost on a Filament to a new Cylinder.
Definition at line 267 of file ChemCallbacks.h.
Constructor & Destructor Documentation
MotorMovingCylinderForwardCallback::MotorMovingCylinderForwardCallback (SpeciesMotor * sm1, SpeciesMotor * sm2, CCylinder * newCCylinder) inline
Definition at line 274 of file ChemCallbacks.h.
Member Function Documentation
void MotorMovingCylinderForwardCallback::operator() (ReactionBase * r) inline
Definition at line 277 of file ChemCallbacks.h.
References _newCCylinder, _sm1, _sm2, SpeciesBound::getCBound(), MotorGhost::getCMotorGhost(), CCylinder::getCylinder(), CBound::getFirstSpecies(), MotorGhost::setFirstCylinder(), MotorGhost::setFirstPosition(), CBound::setFirstSpecies(), MotorGhost::setSecondCylinder(), MotorGhost::setSecondPosition(), and CBound::setSecondSpecies().
Member Data Documentation
CCylinder* MotorMovingCylinderForwardCallback::_newCCylinder
Definition at line 272 of file ChemCallbacks.h.
Referenced by operator()().
SpeciesMotor* MotorMovingCylinderForwardCallback::_sm1
Definition at line 270 of file ChemCallbacks.h.
Referenced by operator()().
SpeciesMotor* MotorMovingCylinderForwardCallback::_sm2
Definition at line 271 of file ChemCallbacks.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
M3SYM/Chemistry/ChemCallbacks.h