M3Sym: MotorMovingCylinderBackwardCallback Struct Reference
MotorMovingCylinderBackwardCallback Struct Reference
Callback to walk a MotorGhost on a Filament to a new Cylinder.
#include <ChemCallbacks.h>
Public Member Functions
MotorMovingCylinderBackwardCallback (SpeciesMotor *sm1, SpeciesMotor *sm2, CCylinder *newCCylinder)
void operator() (ReactionBase *r)
Public Attributes
SpeciesMotor * _sm1
SpeciesMotor * _sm2
CCylinder * _newCCylinder
Detailed Description
Callback to walk a MotorGhost on a Filament to a new Cylinder.
Definition at line 305 of file ChemCallbacks.h.
Constructor & Destructor Documentation
MotorMovingCylinderBackwardCallback::MotorMovingCylinderBackwardCallback (SpeciesMotor * sm1, SpeciesMotor * sm2, CCylinder * newCCylinder) inline
Definition at line 312 of file ChemCallbacks.h.
Member Function Documentation
void MotorMovingCylinderBackwardCallback::operator() (ReactionBase * r) inline
Definition at line 315 of file ChemCallbacks.h.
References _newCCylinder, _sm1, _sm2, GeometryParameters::cylinderIntSize, SystemParameters::Geometry(), SpeciesBound::getCBound(), MotorGhost::getCMotorGhost(), CCylinder::getCylinder(), CBound::getFirstSpecies(), MotorGhost::setFirstCylinder(), MotorGhost::setFirstPosition(), CBound::setFirstSpecies(), MotorGhost::setSecondCylinder(), MotorGhost::setSecondPosition(), and CBound::setSecondSpecies().
Member Data Documentation
CCylinder* MotorMovingCylinderBackwardCallback::_newCCylinder
Definition at line 310 of file ChemCallbacks.h.
Referenced by operator()().
SpeciesMotor* MotorMovingCylinderBackwardCallback::_sm1
Definition at line 308 of file ChemCallbacks.h.
Referenced by operator()().
SpeciesMotor* MotorMovingCylinderBackwardCallback::_sm2
Definition at line 309 of file ChemCallbacks.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
M3SYM/Chemistry/ChemCallbacks.h