M3Sym: MotorBindingCallback Struct Reference
MotorBindingCallback Struct Reference
Callback to bind a MotorGhost to Filament.
#include <ChemCallbacks.h>
Public Member Functions
MotorBindingCallback (CCylinder *cc1, CCylinder *cc2, short motorType, short position1, short position2, SubSystem *ps)
void operator() (ReactionBase *r)
Public Attributes
SubSystem * _ps
CCylinder * _cc1
CCylinder * _cc2
short _motorType
short _position1
short _position2
Detailed Description
Callback to bind a MotorGhost to Filament.
Definition at line 147 of file ChemCallbacks.h.
Constructor & Destructor Documentation
MotorBindingCallback::MotorBindingCallback (CCylinder * cc1, CCylinder * cc2, short motorType, short position1, short position2, SubSystem * ps) inline
Definition at line 154 of file ChemCallbacks.h.
Member Function Documentation
void MotorBindingCallback::operator() (ReactionBase * r) inline
Definition at line 157 of file ChemCallbacks.h.
References _cc1, _cc2, _motorType, _position1, _position2, _ps, SubSystem::addNewMotorGhost(), GeometryParameters::cylinderIntSize, SystemParameters::Geometry(), and CCylinder::getCylinder().
Member Data Documentation
CCylinder* MotorBindingCallback::_cc1
Definition at line 150 of file ChemCallbacks.h.
Referenced by operator()().
CCylinder * MotorBindingCallback::_cc2
Definition at line 150 of file ChemCallbacks.h.
Referenced by operator()().
short MotorBindingCallback::_motorType
Definition at line 151 of file ChemCallbacks.h.
Referenced by operator()().
short MotorBindingCallback::_position1
Definition at line 152 of file ChemCallbacks.h.
Referenced by operator()().
short MotorBindingCallback::_position2
Definition at line 152 of file ChemCallbacks.h.
Referenced by operator()().
SubSystem* MotorBindingCallback::_ps
Definition at line 149 of file ChemCallbacks.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
M3SYM/Chemistry/ChemCallbacks.h