MEDYAN: src/utility.h File Reference
utility.h File Reference
#include <tuple>
#include <chrono>
#include <memory>
#include <math.h>
#include <vector>
#include <sstream>
#include <iterator>
Classes
struct std::hash< std::tuple< TT... > >
Functions
unsigned long long rdtsc ()
A random seed based on clock cycles.
bool areEqual (double d1, double d2)
Check equaility of doubles.
double safeacos (double x)
Safe arc cos function.
template<typename T , typename ... Args>
unique_ptr< T > make_unique (Args &&...args)
Make a unique ptr.
template<typename T , typename U >
bool isSame (const U &x)
Compare types.
template<typename T >
vector< T > split (const string &line)
Split a string by whitespace into generic type.
short std::sum (vector< short > vec)
Sum a vector of shorts.
Variables
const double ZERO_PREC = 1E-6
Function Documentation
areEqual()
bool areEqual (double d1, double d2) inline
Check equaility of doubles.
Definition at line 34 of file utility.h.
References ZERO_PREC.
Referenced by ReactionBase::activateReaction(), CMonomer::activeSpeciesBrancher(), CMonomer::activeSpeciesFilament(), CMonomer::activeSpeciesLinker(), CMonomer::activeSpeciesMinusEnd(), CMonomer::activeSpeciesMotor(), CMonomer::activeSpeciesPlusEnd(), BranchingManager::addPossibleBindings(), LinkerBindingManager::addPossibleBindings(), MotorBindingManager::addPossibleBindings(), mathfunc::areInPlane(), mathfunc::areParallel(), CBranchingPoint::CBranchingPoint(), SysParams::checkMechParameters(), CLinker::CLinker(), CMotorGhost::CMotorGhost(), Reaction< 1, 1 >::computePropensityImpl(), FilamentBendingCosine::forces(), BoundaryCylinderAttachmentHarmonic::forces(), FilamentBendingCosine::forcesAux(), BoundaryCylinderAttachmentHarmonic::forcesAux(), CMonomer::isConsistent(), BranchingManager::isConsistent(), LinkerBindingManager::isConsistent(), MotorBindingManager::isConsistent(), FletcherRieves::minimize(), PolakRibiere::minimize(), CMonomer::print(), Controller::run(), RSpeciesAvg::up(), BranchingManager::updateAllPossibleBindings(), LinkerBindingManager::updateAllPossibleBindings(), MotorBindingManager::updateAllPossibleBindings(), ChemManager::updateCopyNumbers(), and Cylinder::updatePosition().
isSame()
template<typename T , typename U > bool isSame (const U & x)
Compare types.
Definition at line 55 of file utility.h.
make_unique()
template<typename T , typename ... Args> unique_ptr<T> make_unique (Args &&... args)
Make a unique ptr.
Definition at line 48 of file utility.h.
rdtsc()
unsigned long long rdtsc ()
A random seed based on clock cycles.
Definition at line 16 of file utility.cpp.
safeacos()
double safeacos (double x) inline
Safe arc cos function.
Definition at line 40 of file utility.h.
Referenced by BranchingBendingCosine::energy(), BranchingPositionCosine::energy(), FilamentBendingCosine::energy(), BranchingBendingCosine::forces(), FilamentBendingCosine::forces(), BranchingPositionCosine::forces(), BranchingBendingCosine::forcesAux(), FilamentBendingCosine::forcesAux(), and BranchingPositionCosine::forcesAux().
split()
template<typename T > vector<T> split (const string & line)
Split a string by whitespace into generic type.
Definition at line 61 of file utility.h.
sum()
short std::sum (vector< short > vec) inline
Sum a vector of shorts.
Definition at line 117 of file utility.h.
References std::sum().
Referenced by SysParams::checkChemParameters(), SysParams::checkDyRateParameters(), SysParams::checkMechParameters(), Composite::countDescendents(), Composite::countReactions(), Composite::countSpecies(), DRController::initialize(), matrix_mul(), and std::sum().
Variable Documentation
ZERO_PREC
const double ZERO_PREC = 1E-6
Definition at line 28 of file utility.h.
Referenced by areEqual().