name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: |
        sudo apt install libboost-dev
        sudo apt install libboost-all-dev
    - name: prepare dependencies
      run: |
        export MEDYAN_BOOST_INSTALL_MODE="find"
        # Use avx2 (default avx512 causes trouble in UMEsimd)
        sed -i 's/-mtune=native -march=native/-mavx2/g' CMakeLists.txt
        # add --no-as-needed to correctly link pthread
        sed -i -e '/    target_link_libraries(medyan PRIVATE Threads::Threads)/a\' -e '    target_link_options(medyan BEFORE PRIVATE "-Wl,--no-as-needed")' CMakeLists.txt
        ./conf.sh
    - name: build with make
      run: |
        cd build
        make VERBOSE=1
    - name: run tests
      run: |
        ./build/medyan test

  # build-macos:

  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: prepare dependencies
  #     run: |
  #       brew install pkg-config
  #       # Use avx
  #       # (avx2 is not available on github MacOS environment (Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz as of the time of commit))
  #       sed -i '' -e 's/-mtune=native -march=native/-mavx/g' CMakeLists.txt
  #       ./conf.sh
  #   - name: build with make
  #     run: |
  #       cd build
  #       make VERBOSE=1
  #   - name: run tests
  #     run: |
  #       ./build/medyan test

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: |
        cd "$env:TEMP"
        git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.72.0 https://github.com/boostorg/boost.git
        cd boost
        .\bootstrap.bat
        .\b2.exe
    - name: prepare dependencies
      run: |
        # Configure medyan build.
        $MEDYAN_BOOST_INSTALL_MODE = "manual"
        $MEDYAN_BOOST_INCLUDE_DIR = "$env:TEMP\boost\boost"
        $MEDYAN_BOOST_LIBRARY_DIR = "$env:TEMP\boost\stage\lib"
        .\conf.ps1
    - name: build with MSBuild
      working-directory: ${{ github.workspace }}
      run: |
        cd build
        # Set up chocolatey profile so that refreshenv is an ps alias
        # $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."   
        # Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        # refreshenv
        # Build solution
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" .\MEDYAN.sln /property:Configuration=Release /property:Platform=x64
    - name: run tests
      run: |
        .\build\Release\medyan.exe test
